### ISSUE TITLE
Minor typo in textbook: Overridden methods have same return type

### ISSUE THREAD

**Issue by E0735389** [nus-cs2103-AY2324S2/forum#1]
Textbook:

https://nus-cs2103-ay2324s2.github.io/website/schedule/week1/topics.html#paradigms-oop-inheritance-overriding

> Method overriding is when a sub-class changes the behavior inherited from the parent class by re-implementing the method. Overridden methods have the same name, same type signature, and same return type.

Actually, Java supports covariant return type. https://stackoverflow.com/a/14694885

------

Edit: probably more appropriate to report on https://github.com/se-edu/se-book/issues/116 .

**Comment by damithc** [comment]
Fixed. Thanks @E0735389 for the heads up.
