### ISSUE TITLE
MS Team Link not responsive

### ISSUE THREAD

**Issue by c-wenlong** [nus-cs2103-AY2324S2/forum#10]
<img width="319" alt="Screenshot 2024-01-20 at 04 03 30" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/122634467/64de3f93-284b-4bb8-b25a-d32ffc1f8e5d">

Unable to join the course on MSTeam, will it be enabled in week 3?

**Comment by damithc** [comment]
@c-wenlong Not to worry. We'll mass-add all of you to that MST team soon.  No need to join by yourself.

**Comment by damithc** [comment]
@c-wenlong We have added all students to [CS2103/T MS Team](https://teams.microsoft.com/l/team/19%3aYCe26jtZ6Trwa-l0rrppXwjAAojUIcYQRpKFiBES4FI1%40thread.tacv2/conversations?groupId=0e16445f-71b1-4996-be7a-fec0560a1e17&tenantId=5ba5ef5e-3109-4e77-85bd-cfeb0d347e82). You should be able to access it now.
