### ISSUE TITLE
Week 2 automated testing

### ISSUE THREAD

**Issue by timothysashimi** [nus-cs2103-AY2324S2/forum#100]
Hi everyone, can i check whether it's compulsory or optional to do the automated text testing for week 2? Thank you!

**Comment by damithc** [comment]
@timothysashimi Optional increments will be clearly marked as such. `A-TextUiTesting`  is not an optional increment.

**Comment by chewbum** [comment]
It's compulsory, you can just take a look at the tags on the dashboard for reference on what's needed!

**Comment by damithc** [comment]
> It's compulsory, you can just take a look at the tags on the dashboard for reference on what's needed!

Yup, [iP progress dashboard](https://nus-cs2103-ay2324s2.github.io/dashboards/contents/ip-progress.html) is another way to cross-check the status of an iP increment, including whether it is optional.
