### ISSUE TITLE
JUnit test method naming conventions

### ISSUE THREAD

**Issue by jeong-jaeho** [nus-cs2103-AY2324S2/forum#1000]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/109773933/1eabf105-a9c1-4f71-8c29-a59ab8794999)
The coding standard states to make method names sound like a verb.
However, the method name for the JUnit test doesn't use the verb format. Doesn't the standard apply as well?

**Comment by fy17ohhh** [comment]
The test standard is as follows
<img width="1270" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/103088135/53636cbc-5f85-4410-a41c-ae6a61fae908">
intDivision is a valid `featureUnderTest`
and zeroDivisor is also a valid `testScenario`
