### ISSUE TITLE
Practice paper part 3 Q16 

### ISSUE THREAD

**Issue by STELLA-LYE** [nus-cs2103-AY2324S2/forum#1001]
<img width="568" alt="Screenshot 2024-04-25 at 12 50 08 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/108970868/9fed4646-6731-4028-ae54-daf327159213">

For the above question, could a possible answer be 2 where one is s = null and s.length() = 1 to obtain the smallest number of test cases ? Since the number of possible loop is only one loop and this test case will cover 100% of the loop coverage for the above method. 

Thank You :)

**Comment by fy17ohhh** [comment]
I think the question here is to achieve `100% path overage`. The number of paths through the loop is very large, as each possible length of `s` produces a unique path. 

So in your example `s = null` and `s.length() = 1` will not cover 100% path coverage as the path of iterating two times is not covererd.

**Comment by baskargopinath** [comment]
is it infinite or the largest possible string since s can be any length

**Comment by aureliony** [comment]
I think if the string has a length limit, then the number of possible paths is finite. Otherwise, if the string has no length limit, then the number of possible paths is infinite.
