### ISSUE TITLE
How to know when is a dependency and when is association between 2 classes?

### ISSUE THREAD

**Issue by cheahTJ** [nus-cs2103-AY2324S2/forum#1002]
I am not very sure as to what is the distinct gap to separate the two

**Comment by UdhayaShan1** [comment]
Association is a type of dependency, likely a reference.

```
class A {
private B x;
}
```
Clear association between both and can even show navigability from A to B


Dependency may not neccesarily be a reference kept by A, it can be 

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39399745/46a2cd8f-94db-4e79-8413-3b515621ae97)

Common one is B being passed in as method argument of some A function and A can have dependency on B.

**Comment by damithc** [comment]
> Dependency may not neccesarily be a reference kept by A, it can be
> 
> ![image](https://private-user-images.githubusercontent.com/39399745/325487861-46a2cd8f-94db-4e79-8413-3b515621ae97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMjYxNzYsIm5iZiI6MTcxNDAyNTg3NiwicGF0aCI6Ii8zOTM5OTc0NS8zMjU0ODc4NjEtNDZhMmNkOGYtOTRkYi00ZTc5LTg0MTMtM2I1MTU2MjFhZTk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDA2MTc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwOWYxZDQyNjIxODc0NTAyMzA5ZTI1ZGJlZmJhNzkyODU0ZThhMjJmYWQ1NDE0ZDFlMDFhNmUxYjkyMzU4ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aeO574vsDKhGQuDiwEvUT-vuB8VBFFsAKhpZ9vzV8lY)
> 
> Common one is B being passed in as method argument of some A function and A can have dependency on B.

I think @cheahTJ is asking about UML dependency arrows, which has a narrower definition.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/9b480c73-165a-475f-bb46-1d372b4d2577)

**Comment by cheahTJ** [comment]
Thank youu appreciate it!
