### ISSUE TITLE
Syllabus For exam 

### ISSUE THREAD

**Issue by RunjiaChen** [nus-cs2103-AY2324S2/forum#1004]
I noticed that the coding standard for the canvas only covers from basic + intermediate, and other things like git, github are not included. Will they be tested as well? (e.g. esp for coding standard, where there is extra stuff in advanced")

**Comment by damithc** [comment]
Java coding standard: advanced rules are optional, and therefore, not examinable.

**Comment by RunjiaChen** [comment]
Thank you!
