### ISSUE TITLE
Advice on how to draw the sequence diagram for this?

### ISSUE THREAD

**Issue by cheahTJ** [nus-cs2103-AY2324S2/forum#1005]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/122202483/8431f7ba-af33-4a9a-bbd8-8520a3294a42)

**Comment by dillontkh** [comment]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/40649376/ce71919a-c1ac-4969-96cf-8b3c1d285074)

This is how I would draw it

**Comment by cheahTJ** [comment]
Got it, thank you!
