### ISSUE TITLE
X for 'deletion'

### ISSUE THREAD

**Issue by jeong-jaeho** [nus-cs2103-AY2324S2/forum#1006]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/109773933/737a6a9b-47fb-47b8-84f0-239bd5bc2078)

Why is this false?

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/109773933/399e691e-9f64-4b2f-bfe3-240f6c9b199f)
Is it because the textbook states that it's dereferenced and garbage collected only? 
A bit confusing since the textbook uses the term 'deleted'.

**Comment by h4ow3i** [comment]
the red X should be drawn at where the line ends as shown in the textbook example
