### ISSUE TITLE
multiplicity in UML

### ISSUE THREAD

**Issue by doyelee0313** [nus-cs2103-AY2324S2/forum#1007]
<img width="750" alt="Screen Shot 2024-04-25 at 4 48 25 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/114212373/ae8441d8-eb2f-4999-b983-de1860b08eef">

Hi can I ask what is the difference between *..5 and 0..5 ?

**Comment by baskargopinath** [comment]
i think * is supposed to be infinity, so i guess infinity to 5 which is worng

**Comment by yisiox** [comment]
Concur that \*..5 is probably wrong?

Bit of trivia the [Kleene star](https://en.wikipedia.org/wiki/Kleene_star) ($\^\*$) applied to a set of strings means "any number of repetitions of strings from the set". e.g. $\\{a,b\\}\^\*=\\{\epsilon, a, b, aa, bb, ab, ba, aaa, bbb, \dots \\}$. This is where the use of \* in regex comes from. I see it as $a\^1=a$, $a\^2=aa$, $a\^3=aaa$ so $a\^\*$ is like a wildcard exponent. I guess \* tends to have the meaning of "any number of".

**Comment by damithc** [comment]
> I guess * tends to have the meaning of "any number of".

@yisiox Yup, that's the case here.

So `0..5` and `*..5` are not exactly interchangeable.
