### ISSUE TITLE
practice exam part 2 Q3

### ISSUE THREAD

**Issue by doyelee0313** [nus-cs2103-AY2324S2/forum#1008]
<img width="1154" alt="Screen Shot 2024-04-25 at 4 52 38 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/114212373/4fdcfbbf-34b9-481a-8f77-633103648117">
Hi can anyone explain why the answer is E?

**Comment by baskargopinath** [comment]
shouldnt show association as both lines and attributes

**Comment by aureliony** [comment]
`E` indicates that there are two separate associations of subactivities, but there is actually only one.
