### ISSUE TITLE
How to count the layers of abstraction for a given piece of code?

### ISSUE THREAD

**Issue by RunjiaChen** [nus-cs2103-AY2324S2/forum#1009]
How do we tell that there is only 2 layers of abstraction here? My reasoning is that since there are multiple sections, each section is like one "layer" of abstraction since they can be abstracted out, so it should be like 4-5 layers. 

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/142142406/bcf5ff93-4d89-412a-96a5-e77659fcb63c)

**Comment by damithc** [comment]
@RunjiaChen In this particular weekly briefing question, we chose 2 to indicate 'at least 2'. The explanation that was given with the aid of this slide (which was about "is this level of SLAP acceptable?") was the important part (and was the intended value); selecting an answer wasn't -- we just selected something reasonable to mark as the question as 'done'.

**Comment by RunjiaChen** [comment]
Okay, thank you! Is it right to say that we dont usually need to worry about how many layers there are, but rather if its an acceptable or not?

**Comment by damithc** [comment]
> Okay, thank you! Is it right to say that we dont usually need to worry about how many layers there are, but rather if its an acceptable or not?

@RunjiaChen Yes.

**Comment by RunjiaChen** [comment]
thank you

**Comment by Anant1902** [comment]
Hi @damithc and rest, what would be the different levels of abstraction here? Would the lambda functions be considered one? Would whatever is inside the for loop be considered another? I am not quite sure as to what classifies as different levels of abstractions.

**Comment by damithc** [comment]
@Anant1902 This code is some rubbish code. The point of the slide was to show how the code is organized into blocks with a high-level explanation of each block, which indicates at least there is two levels of abstractions.
To learn more about SLAP, you can watch the following video, starting at 4 minutes mark.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/ed0fd176-16af-4c35-9212-027d0b805be9)
