### ISSUE TITLE
Textbook PDF missing topic (TDD)

### ISSUE THREAD

**Issue by billyhoce** [nus-cs2103-AY2324S2/forum#1014]
TDD, despite being in the syllabus (not optional), is not included in the **PDF textbook handout** on Canvas, as well as the [printable version of the textbook on the course website](https://nus-cs2103-ay2324s2.github.io/website/se-book-adapted/print.html)

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/84035425/22de0c0a-b324-4413-9653-ee769b772dac)

TDD section should fall directly after dependency injection, according to the "Testing" Section of the textbook. But it is missing here. A search does not find it elsewhere as well.
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/84035425/3a6dd6a1-5bab-43ef-954a-96a12af3e3ba)

**Comment by damithc** [comment]
Good catch, @billyhoce Will fix in the next semester.
As this topic is not in the textbook PDF, it is also not covered in this semester's exam.

**Comment by billyhoce** [comment]
Alright thanks prof!
