### ISSUE TITLE
Bidirectional navigability

### ISSUE THREAD

**Issue by RunjiaChen** [nus-cs2103-AY2324S2/forum#1015]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/142142406/344e7aa3-f219-43d7-8d97-eb7ec610e693)

In the lecture briefing, it was mentioned that the usage of bidirectional arrows can be different even if the code can be the same, and the only way we can tell is by the context and the intent of the design. For the exam, may I know if we have to infer the context ourselves, or will it be explicitly stated for us? Thank you!

**Comment by damithc** [comment]
> For the exam, may I know if we have to infer the context ourselves, or will it be explicitly stated for us?

@RunjiaChen We'll give you enough information to infer the context.

**Comment by RunjiaChen** [comment]
thank you
