### ISSUE TITLE
Javadocs coding standard

### ISSUE THREAD

**Issue by aureliony** [nus-cs2103-AY2324S2/forum#1016]
Is it important that the first word is capitalized and the line must end with a period? It's not mentioned in "Note in particular".

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39163684/d9f850ba-baba-4bfa-8a6d-42fd870efab2)

**Comment by damithc** [comment]
@aureliony For the exam, you can consider them as _required_. We don't penalize missing this specific thing in tP code though.
