### ISSUE TITLE
Practice Exam p3.07 Question

### ISSUE THREAD

**Issue by RyanNgWH** [nus-cs2103-AY2324S2/forum#1017]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/44436551/cab59210-3994-4cca-b7b5-266ed470f630)

May I know why `A` is a more suitable answer to this question as compared to  `D`?

Based on my understanding, it would be ideal for the `c` to have the activation bar for the constructor and for `s` to have to have a longer lifeline than `c`. However, since this is not an option in the question, I was thinking that having the activation bar for the constructor of `c` to be more important than having a longer lifeline for `s`. Is this not the case?

**Comment by baskargopinath** [comment]
@RyanNgWH when u say longer lifeline do u mean s has to exist before c?

**Comment by tzyian** [comment]
I think just because activation bars are optional, but the ordering is not

**Comment by RyanNgWH** [comment]
@bgopi23 yes so the box for `s` is higher than that of `c`.

**Comment by RyanNgWH** [comment]
@rertyy Ohhhh that makes sense. Thanks!!
