### ISSUE TITLE
Activity diagram parallel paths: is it allowed for Fork to be vertical and the Join to be horizontal?

### ISSUE THREAD

**Issue by aureliony** [nus-cs2103-AY2324S2/forum#1020]
So far in all the examples in the textbook and tutorials, fork and join rectangles are either both vertical, or both horizontal. Is it valid for one to be vertical and the other to be horizontal?

Example (sorry for the bad lines):
![Untitled](https://github.com/nus-cs2103-AY2324S2/forum/assets/39163684/ea1fb447-de17-4b50-b5b3-cdf47afa6054)

**Comment by damithc** [comment]
@aureliony Yes, each can be vertical or horizontal, independent of the other.

**Comment by aureliony** [comment]
Just to add on, is it allowed for the rectangles to be diagonal?

And is it allowed for the arrows to be diagonal?

**Comment by damithc** [comment]
I suppose this likeness of the below, in _any_ orientation, is good enough to show it is a fork/join.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/42c05540-0e83-484d-bc73-b957053aaa3d)

**Comment by aureliony** [comment]
Thank you prof
