### ISSUE TITLE
p1.11 space after `if`

### ISSUE THREAD

**Issue by tzyian** [nus-cs2103-AY2324S2/forum#1021]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/107781565/73a3c1e5-999b-43d4-9a8a-882fd4046d39)

> Examiner note: 1: should be /** ; 2: should be Prints ; 7: missing {

p1.11 suggested answer is correct, but is missing that `if(abcd.length() > 3)` should also have a space after the `if`, which is a reserved word and not an operator

**Comment by damithc** [comment]
Good catch @rertyy 
The question should have added a space there
