### ISSUE TITLE
Practice Exam Part 2 abstract class implements interface

### ISSUE THREAD

**Issue by tzyian** [nus-cs2103-AY2324S2/forum#1022]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/107781565/3eae2ea7-6bd9-403c-9f04-2edb37c7a12d)

Why does `ProgressWatcher` not have `+update(int)`?

**Comment by baskargopinath** [comment]
@rertyy i think abstract classes dont have to provide implementations but concrete classes do

**Comment by Li-Zizhen** [comment]
@bgopi23  But the interface also doesn't have implementations?

**Comment by baskargopinath** [comment]
@Li-Zizhen thats the nature of interfaces, but any concrete classes extending it has to

**Comment by Li-Zizhen** [comment]
@bgopi23 Got it. Thank you.

**Comment by aureliony** [comment]
The abstract method can be shown:

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39163684/a4d219ca-5ea7-413a-8ead-452637ddd170)

**Comment by tzyian** [comment]
Hm if that's the case, why is `{abstract}` not shown for interface methods? Since by default interface methods are `abstract` unless it's a default method

**Comment by damithc** [comment]
> Hm if that's the case, why is `{abstract}` not shown for interface methods? Since by default interface methods are `abstract` unless it's a default method

@rertyy `<<interface>>` already tells us the methods are abstract. Adding it to every method in the diagram doesn't add value but adds noise. This is the same reason why we don't use the `abstract` keyword when defining methods in a Java interface.

**Comment by tzyian** [comment]
But default methods for interfaces exist, and we can't differentiate if implicitly we assume abstract? At least for static there's underline

**Comment by damithc** [comment]
> But default methods for interfaces exist, and we can't differentiate if implicitly we assume abstract? At least for static there's underline

@rertyy Default methods are just a recent quirk introduced into Java. It is more of an implementation detail, not a natural part of what we normally call an 'interface'. UML `<<interface>>` is not specific to Java, and models a more general concept of an interface.

If you must include a default method in a class diagram, you can indicate them using some other way e.g., using a custom stereotype `<<default>>` in front of the method, or a UML note.
