### ISSUE TITLE
Examplify colours lost on using highlighter or eraser tool

### ISSUE THREAD

**Issue by tzyian** [nus-cs2103-AY2324S2/forum#1023]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/107781565/630a229d-11ec-44ed-886f-dfc3770c8c33)

If the question has colours in Examplify, using the highlighter tool or the eraser tool will erase the colours. 
Screenshot for relevant question (p3.14)

**Comment by damithc** [comment]
@rertyy I see.
Besides, colors might not work well for color blind students. So, we use colors as an extra indicator but we do not rely on them entirely. In this case, negative values are invalid inputs, irrespective of colors.
