### ISSUE TITLE
Multiple levels of abstraction

### ISSUE THREAD

**Issue by jannaleong** [nus-cs2103-AY2324S2/forum#1025]
Hi, could i ask what exactly are the multiple levels of abstraction. Throughout the method, it seems to be quite low level with print statements, for loops and variable definitions. 
<img width="1202" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/96218110/79ba29e6-a0c4-431d-9a61-5e6d0b1b83d9">

**Comment by logical-1985516** [comment]
From my understanding, SLAP requires that a method performs only a single task. It has nothing to do with how it is implemented.

**Comment by yisiox** [comment]
From the textbook:
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/107540644/05520d81-2dc3-4666-9485-48599a4c0817)

The example seems to imply that expanding everything into the lowest level reasonable isn't the same as having a single level of abstraction, being that there exists a higher level to expand in the first place. But it does show that we don't have to follow SLAP rigidly. SLAP does apply here though since the tutorial example given has the resulting effect of a (somewhat) long method and could stand to benefit in terms of readability by abstracting the high level actions behind methods, so we are inclined to SLAP it.

**Comment by damithc** [comment]
> From my understanding, SLAP requires that a method performs only a single task. It has nothing to do with how it is implemented.

@logical-1985516 This is not correct. While each method should do only one thing, SLAP is not  about that, and has everything to do with how the method is implemented. Did any of the course materials led you to the above incorrect conclusion (in which case we need to improve it)?

**Comment by damithc** [comment]
@jannaleong The tutor should have explained that this method has several levels of abstractions. 
At the highest level (red):
```
1. show intro message
2. initialize
3. process commands
```

3rd step can be stated at a lower level abstration:
```
while not bye,
  read command
  if bye,
    show exit message
  else if list,
    show all tasks
  ...
```

`show all tasks` can be stated at an even lower level of abstraction:
```
show intro message
for each taks
  ...
```

Hence, multiple levels of abstraction (i.e., weak SLAP).

**Comment by logical-1985516** [comment]
> > From my understanding, SLAP requires that a method performs only a single task. It has nothing to do with how it is implemented.
> 
> @logical-1985516 This is not correct. While each method should do only one thing, SLAP is not about that, and has everything to do with how the method is implemented. Did any of the course materials led you to the above incorrect conclusion (in which case we need to improve it)?

My bad with the phrasing. I misunderstood SLAP slightly and combined it with SRP. Perhaps I should have changed it to "tasks of similar complexity". For the implementation part, I was referring to this part:
> Throughout the method, it seems to be quite low level with print statements, for loops and variable definitions.

I meant that whether a method uses low level statements has nothing to do with the level of abstraction. After all, no matter the complexity of a method, it can always be broken down into low level code.
