### ISSUE TITLE
Do non instantiated fields not have respective association lines?

### ISSUE THREAD

**Issue by Anant1902** [nus-cs2103-AY2324S2/forum#1026]
In the question below, (b) is incorrect because 'only one class keeps track of the association'. Wanted to clarify that if there are fields of object types that are not instantiated yet (as seen in the Bot class), do we not need to draw association lines? Seems counterintuitive though, cause in any method in the class, it might potentially be instantiated?

<img width="592" alt="Screenshot 2024-04-26 at 12 29 41 AM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/60879977/20f0af37-9c36-449d-b237-9f95d7aeb15e">
<img width="560" alt="Screenshot 2024-04-26 at 12 30 07 AM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/60879977/0597a764-8c1d-4a13-be92-0f305301da85">

**Comment by damithc** [comment]
> not instantiated yet

@Anant1902 When you say 'yet', what point of time are you referring to? Class diagrams (unlike object diagrams) are not tied to a specific point of time.

**Comment by Anant1902** [comment]
> > not instantiated yet
> 
> 
> 
> @Anant1902 When you say 'yet', what point of time are you referring to? Class diagrams (unlike object diagrams) are not tied to a specific point of time.

Hi Prof! Sorry for the ambiguity, I meant that it might possibly be instantiated within the init() method (since the method implementation is not shown, we don't know).

**Comment by Anant1902** [comment]
> > > not instantiated yet
> > 
> > 
> > 
> > @Anant1902 When you say 'yet', what point of time are you referring to? Class diagrams (unlike object diagrams) are not tied to a specific point of time.
> 
> Hi Prof! Sorry for the ambiguity, I meant that it might possibly be instantiated within the init() method (since the method implementation is not shown, we don't know). 

But regardless of this actually, I guess my question would be - if a field is not instantiated, we do not have to draw the association lines for it?

**Comment by damithc** [comment]
> But regardless of this actually, I guess my question would be - if a field is not instantiated, we do not have to draw the association lines for it?

@Anant1902 Based on the information we have, the class diagram should show that `a Mat object can hold up to 5 Bot objects, in the role of helpers` (this statement doesn't changes based on when, or if, those objects are actually instantiated).

**Comment by Anant1902** [comment]
> this statement doesn't changes based on when, or if, those objects are actually instantiated

Go it prof, thanks!

**Comment by damithc** [comment]
@Anant1902 to add, class diagrams show _rules_ that govern relationship between classes. For that, timing doesn't matter, as rules are meant to be followed _all the time_.
Object diagrams show the object structure at a specific time. For _that_, we need to know if the object has been instantiated or not.

**Comment by Anant1902** [comment]
That makes a lot of sense. Thanks prof!
