### ISSUE TITLE
Quiz 5 Q50

### ISSUE THREAD

**Issue by tankh99** [nus-cs2103-AY2324S2/forum#1028]
<img width="875" alt="Screenshot 2024-04-26 at 10 22 04 AM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/56617918/7673737f-945d-41c9-8ef9-8289578463eb">

In the refactored function printDetails(), where does the name parameter come from?

**Comment by aureliony** [comment]
I guess it's either a static or non-static attribute

**Comment by damithc** [comment]
> I guess it's either a static or non-static attribute

Yup 👍

**Comment by tankh99** [comment]
Oh thanks @aureliony !
