### ISSUE TITLE
Reverse direction of control in sequence diagram possible?

### ISSUE THREAD

**Issue by cheahTJ** [nus-cs2103-AY2324S2/forum#1029]
With regards to this diagram, can I check if it can be drawn as such as the conventional and typical diagrams we always saw is the passing of control from the left to right, but in this case is right to left, from `bar` to `foo`. So is this possible?

![Screenshot 2024-04-26 at 12 07 01 PM](https://github.com/nus-cs2103-AY2324S2/forum/assets/122202483/da0d4907-c24c-4152-b127-a12db1b103a9)

**Comment by damithc** [comment]
@cheahTJ The direction can be left or right, provided they are horizontal and not angled up/down.

But yes, normally we start the interaction from a top left position, although it is not a rule.

**Comment by cheahTJ** [comment]
Got it thank you prof!
