### ISSUE TITLE
Minor Typo in [W3.2] RCS: Creating Pull Requests 

### ISSUE THREAD

**Issue by jyztintan** [nus-cs2103-AY2324S2/forum#103]
Under "Problem: merge conflicts", pointer 2, it states:

"In the local repo, and attempt to merge the master branch (that you updated in the previous step) onto the PR branch, in order to bring over the new code in the master branch to your PR branch."

i think it should be:
 
"In the local repo, ~~and~~ attempt to merge the master branch (that you updated in the previous step) onto the PR branch, in order to bring over the new code in the master branch to your PR branch."

**Comment by damithc** [comment]
Fixed. Thanks for the bug report, @jyztintan
