### ISSUE TITLE
Verification of quiz answer

### ISSUE THREAD

**Issue by cheahTJ** [nus-cs2103-AY2324S2/forum#1030]
The method m2 should belong to the Foo class right? Just making sure there is no lapse in my understanding.

![Screenshot 2024-04-26 at 12 12 12 PM](https://github.com/nus-cs2103-AY2324S2/forum/assets/122202483/d8a816c0-189d-4237-8682-3ac038ac0cac)

**Comment by cheahTJ** [comment]
I think I have got it, the method m2 should belong to the `Bar class as can be seen from the sequence diagram above, the 'control' is being passed to the `Bar` class. Is this understanding correct?

**Comment by yashpola** [comment]
@cheahTJ 

Yes I think the `f:Foo` object is calling the `m2` method of the `b:Bar` object. So `m2` belongs to `Bar`
