### ISSUE TITLE
Association in Object Diagrams (Tutorial 5)

### ISSUE THREAD

**Issue by cliftonchee** [nus-cs2103-AY2324S2/forum#1032]
![photo1714103148](https://github.com/nus-cs2103-AY2324S2/forum/assets/70459953/808804eb-566f-4b63-b8be-abf760237ca3)

Hi! I would like to check on my understanding of association between objects in an object diagram. My understanding is that in this bidirectional navigability between children and fiction means to say that:

children object has a reference to fiction (and vice versa) e.g.
```
Category cat = fiction;
```

But between student and loan (and book), there is no navigability(?) between the objects, unless we chose to omit such details as it may not be necessary? 

Thanks in advance!

**Comment by damithc** [comment]
> But between student and loan (and book), there is no navigability(?) between the objects, unless we chose to omit such details as it may not be necessary?

@cliftonchee In this diagram, those navigabilities have been omitted.

**Comment by cliftonchee** [comment]
Okay! Thank you Prof!
