### ISSUE TITLE
[Practice exam p1.06] UML: OD to CD

### ISSUE THREAD

**Issue by damithc** [nus-cs2103-AY2324S2/forum#1034]
Question received from a student, posting here for discussion:

>![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/3a50340d-86b9-4da2-a245-25d2afebbe3b)
>May I know why the last option is not valid for the following question?

**Comment by amanzainal** [comment]
The last option is invalid because it implies that each table must have 1 door. (Not 0..1 or more than 1, but exactly 1)

The object diagram doesn't have a door.

**Comment by damithc** [comment]
Good answer @amanzainal
