### ISSUE TITLE
Confusion between branch and condition coverage

### ISSUE THREAD

**Issue by cheahTJ** [nus-cs2103-AY2324S2/forum#1035]
What is the main distinctive difference between these 2?

**Comment by dillontkh** [comment]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/40649376/307ebdd3-feab-40a3-90a0-099a645ae7b0)

```
if (x > 2 && x < 44) {
    // path a
} else {
    // path b
}
```

Given the above example, to achieve 100% branch coverage you just need to ensure your test cases hit `path a` and `path b`.

However to hit 100% condition coverage, you need to ensure that `x > 2` gets evaluated to `true` and `false`, and `x < 44` gets evaluated to `true` and `false`.

**Comment by damithc** [comment]
Good answer @dillontkh

**Comment by cheahTJ** [comment]
Thank you !! @dillontkh
