### ISSUE TITLE
Issue with Question 3 of Mock Exam: Clarification on Terminology

### ISSUE THREAD

**Issue by amanzainal** [nus-cs2103-AY2324S2/forum#1036]
I noticed a discrepancy between the explanation provided in Question 3 of the Mock Exam (Model Answers) and the terminology used in our textbook. 

In the mock exam explanation, "coding standard" and "coding quality" are treated as distinct concepts. However, in the textbook, they seem to be used interchangeably. 

Here are the specific references:

1. In the mock exam explanation, "coding standard" and "coding quality" are discussed as separate entities.
   ![Mock Exam Explanation](https://github.com/nus-cs2103-AY2324S2/forum/assets/69044708/112cb6ac-3fa2-4bdf-a523-61177591dfad)

2. In the textbook, both terms are sometimes used interchangeably.
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/69044708/d74dcd47-a5a0-4579-81f7-d05e685bb470)

Could someone assist to clarify whether there's intended to be a difference between "coding standard" and "coding quality" in our course material? Thank you!

**Comment by baskargopinath** [comment]
i think coding standard violations refers to everything in SE-EDU page for Java Coding Standard, it is separate from code quality issues

https://github.com/nus-cs2103-AY2324S2/forum/issues/968 This is an example of code quality violation and not code standard violation

**Comment by damithc** [comment]
> In the mock exam explanation, "coding standard" and "coding quality" are treated as distinct concepts. However, in the textbook, they seem to be used interchangeably.

@amanzainal one is a subset of the other.

From tutorial 3:
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/c955e4a0-a424-4ac2-8111-52e4cd46dddc)

From the week 4 briefing:

<img src="https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/2b41a35b-0026-46ee-b049-37f8c048412f" width="400" />

**Comment by amanzainal** [comment]
Thanks @bgopi23 and prof for the clarifications.
