### ISSUE TITLE
Package private

### ISSUE THREAD

**Issue by tengcharmaine** [nus-cs2103-AY2324S2/forum#1037]
Hello! I am not sure of when a method is considered package private. Is there a way to know when I would need to label methods as packaged private?

For the practice exam, the methods under the Activity class are packaged private.
<img width="548" alt="Screenshot 2024-04-26 at 1 03 51 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/122196137/48d3677e-56d1-4677-9671-672b533442bc">

However, the methods in Billable (from tutorial) are not packaged private as shown in the screenshot below.
<img width="1184" alt="T8_Class_Object_Diagram" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/122196137/52ef7f6e-be89-40ad-bede-70fe3ab8d3c6">

Thank you! :)

**Comment by baskargopinath** [comment]
@tengcharmaine  https://github.com/nus-cs2103-AY2324S2/forum/issues/924#issuecomment-2071989600
