### ISSUE TITLE
Activation Bar is optional in a Sequence Diagram?

### ISSUE THREAD

**Issue by SherisseTJW** [nus-cs2103-AY2324S2/forum#1038]
Hi, I would just like to confirm whether the Activation Bar is optional in a Sequence Diagram, or if this is a bug. This is from Quiz 6.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/63995220/33d97766-47af-40f5-b844-e087989f101e)

**Comment by dillontkh** [comment]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/40649376/5c59afef-1931-406d-b367-f39ec5c91dba)

Yep, activation bars and return arrows are indeed optional. ([source](https://nus-cs2103-ay2324s2.github.io/website/se-book-adapted/chapters/uml.html#minimal-notation))

**Comment by SherisseTJW** [comment]
ooo, thanks thanks
