### ISSUE TITLE
Is activation bar optional?

### ISSUE THREAD

**Issue by doyelee0313** [nus-cs2103-AY2324S2/forum#1039]
<img width="726" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/114212373/6b1d778f-75b1-447a-a1a6-483a46219a98">

For this question, I think the activation bar is missing but it says it is acceptable. Can I check if activation bar is optional?

**Comment by baskargopinath** [comment]
activation bar is optional

**Comment by doyelee0313** [comment]
thanks!
