### ISSUE TITLE
Clarification for Level 8

### ISSUE THREAD

**Issue by yashma-sonara** [nus-cs2103-AY2324S2/forum#104]
For level 8, we have to implement Date and time for Deadline tasks so that it is treated as a date rather than just a string. 

What should we do if user enters a Time or different format (Ex. deadline /by 9pm || deadline /by Sunday). Is it an error and exception thrown, or should we have backward compatibility to store as a string?

**Comment by damithc** [comment]
> What should we do if user enters a Time or different format (Ex. deadline /by 9pm || deadline /by Sunday). Is it an error and exception thrown, or should we have backward compatibility to store as a string?

@yashma-sonara There is no specific requirement from our side. So, consider it as an opportunity to make a design decision yourself, after considering cost and benefits, from both developer and user point of view. Getting better at making such decisions is an intended learning outcome of this course. Feel free to discuss such decisions here in the forum too, so that others can benefit from it too.

**Comment by NeoHW** [comment]
Hi yashma, I interpreted it as that we have backward compatibility to store as a string!

**Comment by miffi** [comment]
My decision was to just allow one date and time format. Advantages are that it's unambiguous and easy to implement. My code throws an error if it's not in that one format.

There is also the alternative design idea of having a custom flexible time system similar to how [taskwarrior](https://taskwarrior.org/docs/dates/#synonyms-hahahugoshortcode-s0-hbhb) does it. It's less cumbersome and faster from a UX standpoint, but it's scope is probably way too big for a project like this.

Keeping backwards compatibility as a string won't really make sense if any filtering based on date is implemented later, but maybe they can be kept around for output purposes.

**Comment by damithc** [comment]
> There is also the alternative design idea of having a custom flexible time system similar to how [taskwarrior](https://taskwarrior.org/docs/dates/#synonyms-hahahugoshortcode-s0-hbhb) does it. It's less cumbersome and faster from a UX standpoint, but it's scope is probably way too big for a project like this.

Thanks for sharing about taskwarrior, @miffi 
It's good to keep an eye on similar products out there.

**Comment by yashma-sonara** [comment]
Thank you guys for the responses:)
