### ISSUE TITLE
How detailed must the open ended follow up to MCQ questions be?

### ISSUE THREAD

**Issue by drustanyjt** [nus-cs2103-AY2324S2/forum#1042]
The grading seems to focus on the MCQ itself. I'm assuming the open ended response is just to make sure you're not blindly guessing an option? Would it be okay to write a response using (reasonable) abbreviations and/or will the responses be graded leniently?

**Comment by damithc** [comment]
@drustanyjt Yes, keep it as short as possible. It's fine as long as a human grader can understand your answer.

**Comment by ZhiWei1010** [comment]
Hi prof @damithc Adding on to this question, if we were to use elimination method to choose the answer, can our explanation be explaining why other options does not make sense instead?

Also would we be penalised if our explanation is wrong but we chose the correct answer?

**Comment by damithc** [comment]
> Hi prof @damithc Adding on to this question, if we were to use elimination method to choose the answer, can our explanation be explaining why other options does not make sense instead?

@ZhiWei1010 Yes.

> Also would we be penalised if our explanation is wrong but we chose the correct answer?

Yes, you may not get full marks if the explanation is not satisfactory.
