### ISSUE TITLE
Practice Paper p3.10: Is it compulsory to report doubts?

### ISSUE THREAD

**Issue by fy17ohhh** [nus-cs2103-AY2324S2/forum#1045]
For practice paper part3 p3.10
the provided answer for Section A2 is not the justifications of why the option `Path coverage is easier to achieve than statement coverage` is incorrect.
May I clarify in this case, do we needed write both justifications and the doubts of the "out-of-scope" choices?
<img width="1026" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/103088135/3e61a22f-1a0b-496c-9047-9d598009ee69">

**Comment by E0735389** [comment]
If I understood correctly:

* Looks like a formatting error. Of course in the open-ended answer field you should type in the explanation, but I suppose the instructor consider it obvious.
* Of course the doubt is written in the NOTES section of Examplify. Not compulsory, but encouraged.

**Comment by damithc** [comment]
> May I clarify in this case, do we needed write both justifications and the doubts of the "out-of-scope" choices?

Encouraged to write doubts in NOTES but not compulsory. For example, if it turned out the question had two correct answers, we give marks to everyone who chose either one of them, irrespective of whether they indicated that in the NOTES.

**Comment by fy17ohhh** [comment]
I see, thank you!
