### ISSUE TITLE
Typo in Week 4 Tutorial UML Diagram

### ISSUE THREAD

**Issue by chengjunyuan** [nus-cs2103-AY2324S2/forum#1046]
While revising for finals, noted the following typo [here](https://nus-cs2103-ay2324s2.github.io/website/schedule/week4/tutorial.html)

<img width="210" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/122239268/015f53ac-e79d-4a5d-b62d-53820d3b64a0">

It should be `abstract`, not `abastract`.

**Comment by damithc** [comment]
Thanks @chengjunyuan I've noted it down, to fix next semester.
