### ISSUE TITLE
What is the main difference between SRP and Soc?

### ISSUE THREAD

**Issue by cheahTJ** [nus-cs2103-AY2324S2/forum#1048]
I still dont really understand what is the difference for them:

SRP: If a class has only one responsibility, it needs to change only when there is a change to that responsibility.
SoC: separate the code into distinct sections, such that each section addresses a separate concern

They seem to be doing the same thing which is to modularise the code such that some classes/methods handle some functionality

**Comment by UdhayaShan1** [comment]
I feel like SRP is strict, _one, and only one, reason to change_, while SoC merely seperates into concerns which is not as strict. SRP implies SoC but not other way around, I guess

**Comment by ThatGirlJam** [comment]
I believe SRP is strictly about a *class* having only one reason to change. SoC can be applied at the class level or higher levels (system)

**Comment by damithc** [comment]
> I believe SRP is strictly about a _class_ having only one reason to change. SoC can be applied at the class level or higher levels (system)

Yup. SoC is more general, applies system-wide, and not strictly limited to OOP systems either.
SRP is specifically a principle that one applies to a class (hence, tied to OOP).

**Comment by cheahTJ** [comment]
Thank you all!!
