### ISSUE TITLE
Help with some quiz questions

### ISSUE THREAD

**Issue by cheahTJ** [nus-cs2103-AY2324S2/forum#1049]
Could I get some help with the explanations of these questions:

![Screenshot 2024-04-26 at 1 29 48 PM](https://github.com/nus-cs2103-AY2324S2/forum/assets/122202483/8802109b-0466-4a5e-8386-9295fb03dc25)
![Screenshot 2024-04-26 at 1 12 37 PM](https://github.com/nus-cs2103-AY2324S2/forum/assets/122202483/b2f70bc9-a840-46a6-957c-fe2fb0349e80)

**Comment by aureliony** [comment]
First qn: `int` is a primitive type, so the set of all `non-int values` is empty (i.e., compiler error if you try to pass in a `non-int value`).

Second qn: `x==0` and `x>=0` are not mutually exclusive and do not cover all cases (i.e., `x < 0` case is missing).

Quote from textbook:

> Exactly one of the guard conditions should be true at any given branch node.

**Comment by yashma-sonara** [comment]
For q1, its like the question in the tutorial: (any other data type would be inapplicable for equivalence partitions.
<img width="650" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/44407952/937b9fa5-88bd-4de8-bb1e-967af67c793b">

**Comment by cheahTJ** [comment]
Alright got it thank you to yall!!
