### ISSUE TITLE
Do we assume the accessibility if not given ?

### ISSUE THREAD

**Issue by justincred** [nus-cs2103-AY2324S2/forum#1052]
for example , in the picture below, why is it not A given that the information provided does not supply the accessibility as shown in the second picture? 
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/95204474/b180661d-c94b-49d9-b477-d4f3d45e5828)
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/95204474/8ae51a7c-a502-43f1-a319-c7e87fafac64)

**Comment by baskargopinath** [comment]
if accessibility if not provided, 

Default accessibility for interface is public (+)

Default accessibility for non-interface classes is package-private (~)

also https://github.com/nus-cs2103-AY2324S2/forum/issues/1033#issuecomment-2078674859

**Comment by justincred** [comment]
thanks bro v nice
