### ISSUE TITLE
Value of class level attribute

### ISSUE THREAD

**Issue by RunjiaChen** [nus-cs2103-AY2324S2/forum#1053]
Are we required to state the value of the class level attribute if its public static final? 

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/142142406/f9459618-f22f-4f24-898f-f6453dc43b03)

Or can we simply leave it as MAX:int

**Comment by damithc** [comment]
@RunjiaChen showing the value is optional (like many things in class diagrams) but it adds more information to the diagram.

**Comment by RunjiaChen** [comment]
Thank you Prof!
