### ISSUE TITLE
EP inquiry

### ISSUE THREAD

**Issue by jeong-jaeho** [nus-cs2103-AY2324S2/forum#1055]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/109773933/6c42520a-54c8-4ae1-975e-4b8dad997290)
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/109773933/e3cf2a40-40fa-45f4-af24-997238e22e7f)

Do EPs need to be adjacent? 
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/109773933/15ae368f-69ee-4606-b6c4-743576a76931)
This example shows EPs don't need to be adjacent though hmm..

**Comment by baskargopinath** [comment]
i dont think EP's have to be adjacent. in ur screenshot of the textbook it also says EPs may not have adjacent values

**Comment by jeong-jaeho** [comment]
@damithc Is it that EPs need to follow the input param's type? For example, the reason why 'all non int values' isn't accepted is because type 'int' can only accept test cases that can be substituted into the type 'int'.

Since the second example's input type is String, it can accept all types of strings and also 'null'?

**Comment by damithc** [comment]
> @damithc Is it that EPs need to follow the input param's type? For example, the reason why 'all non int values' isn't accepted is because type 'int' can only accept test cases that can be substituted into the type 'int'.
> 
> Since the second example's input type is String, it can accept all types of strings and also 'null'?

@jeong-jaeho See if https://github.com/nus-cs2103-AY2324S2/forum/issues/1043 helps
