### ISSUE TITLE
Quiz question for sequence diagram

### ISSUE THREAD

**Issue by RunjiaChen** [nus-cs2103-AY2324S2/forum#1059]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/142142406/0460245e-4f56-4fd3-9cb8-865dec285ee3)

Why is it false for this question? Thank you!

**Comment by baskargopinath** [comment]
line should stop at the X

**Comment by drustanyjt** [comment]
I think someone mentioned previously it might just be because the lifeline does not end after the X. See #832

**Comment by RunjiaChen** [comment]
Thank you
