### ISSUE TITLE
Clarification regarding Level-7

### ISSUE THREAD

**Issue by radeon2525** [nus-cs2103-AY2324S2/forum#106]
For level-7 after generating a conversation with the chatbot, I need to basically need to rerun the program, and it should still store the previous conversation right?

**Comment by damithc** [comment]
@radeon2525 No need to save the exact conversations but the _tasks_ user created in earlier runs of the chatbot should still be there in subsequent runs of the chatbot.

**Comment by radeon2525** [comment]
Okay so just to confirm, if I have a conversation saying 
todo ...
event...
bye
Then when I again run my chatbot so "todo" and "event" should be visible right?

**Comment by damithc** [comment]
> Then when I again run my chatbot so "todo" and "event" should be visible right?

The requirement: 2nd and subsequent times you run the chatbot, the `list` command (or the equivalent command) should also list tasks created in the previous runs. It is not required that you display input commands or responses from previous runs.

For example, suppose the following happened in the first run:
* `list` -> nothing listed
* `todo read book`
* `list` -> lists `read book`
* `bye`

In the second run:
* `list` -> lists `read book` 
  (before Level-7, this command would list nothing, as every run will start with an empty list of tasks).

**Comment by radeon2525** [comment]
Thank you prof, I understand now.

After modifying my code I am able to create a new file called logfile.txt in my system when I run my program but I also subsequently get the following error:

Exception in thread "main" java.io.FileNotFoundException: .\data\logfile.txt (The system cannot find the path specified)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileReader.<init>(FileReader.java:75)
	at FileIO.readFromFile(FileIO.java:27)
	at Duke.<init>(Duke.java:12)
	at Duke.main(Duke.java:23)

Process finished with exit code 1

**Comment by damithc** [comment]
> After modifying my code I am able to create a new file called logfile.txt in my system when I run my program but I also subsequently get the following error:
> 
> Exception in thread "main" java.io.FileNotFoundException: .\data\logfile.txt (The system cannot find the path specified) at java.base/java.io.FileInputStream.open0(Native Method) at java.base/java.io.FileInputStream.open(FileInputStream.java:219) at java.base/java.io.FileInputStream.(FileInputStream.java:157) at java.base/java.io.FileReader.(FileReader.java:75) at FileIO.readFromFile(FileIO.java:27) at Duke.(Duke.java:12) at Duke.main(Duke.java:23)

@radeon2525 As this is a separate issue, you may want to post it as a new issue. Also, it might help to share the code you use to create/write/read the file so that others can understand the issue better.

**Comment by radeon2525** [comment]
Alright I will do that prof.
