### ISSUE TITLE
Finals question of Object diagram to class diagram

### ISSUE THREAD

**Issue by cheahTJ** [nus-cs2103-AY2324S2/forum#1060]
Does anybody know why is d) not correct?

![Screenshot 2024-04-26 at 10 43 59 PM](https://github.com/nus-cs2103-AY2324S2/forum/assets/122202483/8ed8bfb8-0e74-434b-a77f-7f216e77d8b8)

**Comment by ThatGirlJam** [comment]
Hi! The last one (d) implies that a Table MUST have 1 Door, but the Object diagram does not follow that.

**Comment by cheahTJ** [comment]
Thank you @ThatGirlJam
