### ISSUE TITLE
Multiplicity for variable

### ISSUE THREAD

**Issue by justincred** [nus-cs2103-AY2324S2/forum#1061]
Hi for something like this without other constraints, is the multiplicty 0...1 since it can be null for class diagram?
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/95204474/984b0df5-322f-4e62-8747-4f575dc6b28e)

**Comment by jinhanfromNUS** [comment]
Yes. As far as I concern, if there is no statement, then it shall be 0..1.

**Comment by damithc** [comment]
Yes, a regular variable has 0..1 multiplicity by default.

**Comment by justincred** [comment]
thanks
