### ISSUE TITLE
can show dependency even if there is association in other direction?

### ISSUE THREAD

**Issue by UdhayaShan1** [nus-cs2103-AY2324S2/forum#1063]
creds to fren for diagram, this is extra part 2 qns 

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39399745/83a9022d-cc29-444e-b1c2-5e3d5ca525de)

Between handout and seciton,

1. While there is a composition relationship, it is still right to show a dependency in other direction right
2. that being said, suppose if there was no direction and composition in that association line, will adding a dependency in the other direction add any value? Since association is a stricter dependency, this means the implementation is ambiguous.

**Comment by baskargopinath** [comment]
If the dependency and association are in opposite directions u cannot omit the dependency arrow

**Comment by damithc** [comment]
> 2\. that being said, if there was no direction and composition in that association line, will adding a dependency in the other direction add any value? Since association is a stricter dependency, this means the implementation is ambiguous.

Dependency arrows are used to show dependencies that are not already captured by navigabilities shown. So, if there is no navigability in the diagram, it may not be worthwhile to show dependencies either.

**Comment by UdhayaShan1** [comment]
Thanks! This makes sense now
@bgopi23 
@damithc
