### ISSUE TITLE
Default access modifier?

### ISSUE THREAD

**Issue by jinhanfromNUS** [nus-cs2103-AY2324S2/forum#1064]
Below is the answer for practice part 3:
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/111408810/57a7425a-795a-4fac-a6a1-a569e629cce0)

May I know why is A wrong? As far as I concern, if the method/attribute is without any access modifiers, it can be interpretated as default (`~`). Besides, I recall access modifiers are optional too.

**Comment by fy17ohhh** [comment]
The problem here asks for best match,
so B in this case have more details than A

**Comment by jinhanfromNUS** [comment]
Thanks :)

Just to clarify, if `B` is not in the option, can `A` be the answer?

**Comment by fy17ohhh** [comment]
> Thanks :)
> 
> Just to clarify, if `B` is not in the option, can `A` be the answer?

Edited; I think in this case `A` would be the answer

**Comment by damithc** [comment]
> As far as I concern, if the method/attribute is without any access modifiers, it can be interpretated as ...

@jinhanfromNUS This is for java code; not for UML. UML diagrams don't have a `if not shown, then it is by default ~` rule.
