### ISSUE TITLE
Does composition need an arrow or just a line?

### ISSUE THREAD

**Issue by jinhanfromNUS** [nus-cs2103-AY2324S2/forum#1066]
If we are looking at `B` and `C` of the image below, we notice that the composition is an arrow.
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/111408810/363ee46e-b2ff-4f08-b1fb-dd939149db79)

However, in this object diagram, it is just a simple line.
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/111408810/fed72966-1a2a-4090-ada7-56799c1eecae)

From the textbook, it is also without arrow and just a simple line
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/111408810/695285ee-bf2e-4b02-88d6-0027b8b4dc7b)

My doubt is, is composition an arrow (ends with `>`) or just a line?

**Comment by damithc** [comment]
> My doubt is, is composition an arrow (ends with `>`) or just a line?

@jinhanfromNUS It is the diamond, not the line, nor the arrow. The line is the association, and the arrowhead is the navigability. The three are independent of each other.
