### ISSUE TITLE
Isnt java methods by default public?

### ISSUE THREAD

**Issue by cheahTJ** [nus-cs2103-AY2324S2/forum#1068]
Hi, why isnt the answer E given the constraints given in the question?

![Screenshot 2024-04-26 at 11 37 02 PM](https://github.com/nus-cs2103-AY2324S2/forum/assets/122202483/3b69dd26-b802-4d92-8a10-b3c58bb861d8)

![Screenshot 2024-04-26 at 11 35 32 PM](https://github.com/nus-cs2103-AY2324S2/forum/assets/122202483/1d8ccf50-00df-4d1a-96a8-2df7fa771e5e)

**Comment by tzyian** [comment]
Java class methods by default are `default` visibility i.e. package private, represented by `~`.

Java _interface_ methods are by default public.

**Comment by cheahTJ** [comment]
Thank you so much!
