### ISSUE TITLE
Query on level 7

### ISSUE THREAD

**Issue by cheahTJ** [nus-cs2103-AY2324S2/forum#107]
Could I check with the addition of level 7, does it mean that when the user types 'list', it should output whats on the local hard disk or it should be listed out from say for example an ArrayList data structure which is used to store the tasks?

**Comment by damithc** [comment]
@cheahTJ Either is fine, provided the tasks created are preserved between from one run of the chatbot to the other. Also see https://github.com/nus-cs2103-AY2324S2/forum/issues/106#issuecomment-1913509492

**Comment by cheahTJ** [comment]
Thank you prof!
