### ISSUE TITLE
Practice Paper 3.05

### ISSUE THREAD

**Issue by ryanlimdx** [nus-cs2103-AY2324S2/forum#1070]
Hi! May I ask why B instead of E is selected? Since ProgressWatcher implements Watcher, shouldn't it indicate the update method as well? In option B, there is the operations section which is empty while in option E, there is no visibility attribute standardisation (the update method do not have a visibility)
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/91833948/cab2af5d-df5f-44d4-8325-ba2cbad9734b)
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/91833948/398e0700-3967-4526-895e-2fe64b5ab38b)

**Comment by dillontkh** [comment]
Abstract classes may not necessarily implenent the interface methods, and the code snippet does not suggest it does either, so it wouldn't be right to assume that the abstract `ProgressWatcher` implements `update()`.

**Comment by YuvBindal** [comment]
Yes, as mentioned I believe B would be the correct answer due to ProgressWatcher not requiring to implement update() this can also be deduced from the implementation of ProgressWatcher in Part 2

**Comment by ryanlimdx** [comment]
I see..thank you!
