### ISSUE TITLE
Practice Paper 3.03 and 3.04

### ISSUE THREAD

**Issue by chiralcentre** [nus-cs2103-AY2324S2/forum#1071]
Am I correct to say the answer for 3.03 is E because sub-activities cannot be both an association and an attribute at the same time?

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/83827461/4aaf1b02-6925-491f-ba62-14b257a5dfaa)

For 3.04, can I clarify why the dashed arrow should be from Activity to ProgressWatcher? I My understanding is that the dashed arrow represents implementation of an interface, so shouldn't the dashed arrow be from ProgressWatcher to Watcher?
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/83827461/5ce28a3b-1aa5-4130-868a-6b6e7cab719e)

**Comment by YuvBindal** [comment]
Yes, that is correct it should be E for the reason mentioned for 3.03
For 3.04 this represents a dependency, an implementation has a triangle with dashed ~~arrow~~ line!

**Comment by chiralcentre** [comment]
Noted thank you!
