### ISSUE TITLE
Setting up markbind locally

### ISSUE THREAD

**Issue by chiralcentre** [nus-cs2103-AY2324S2/forum#1075]
Does anyone know how we can find the package.json to use for the `npm ci` command as stated here? I went to the `docs` folder in the AB3 repo and I was still unable to find the relevant file. I tried using `npm install markbind-cli` locally, but the error `markbind command not recognised` showed up on my terminal after using `markbind serve`.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/83827461/0e1962bf-1cbc-41d6-affb-1a605de2f9b0)

**Comment by yadunut** [comment]
You can use `npx markbind serve` from the `website` folder and it should work as intended

**Comment by aureliony** [comment]
It should be `npm install -g markbind-cli` instead of `npm install markbind-cli`.
