### ISSUE TITLE
Practice Exam p1.06 Clarification

### ISSUE THREAD

**Issue by c-wenlong** [nus-cs2103-AY2324S2/forum#1076]
<img width="732" alt="Screenshot 2024-04-27 at 02 14 53" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/122634467/34d405db-5f79-44e2-9d60-e71ede1039bb">

Hi, just wanted to confirm that option 4 is not valid because the multiplicity of table to door should be exactly 1, and it was not represented on the object diagram?

**Comment by tankh99** [comment]
Yes correct. Object diagram failed to represent that association so the class diagram is invalid

**Comment by c-wenlong** [comment]
@tankh99 got it thanks!
