### ISSUE TITLE
How to draw a (possibly UML) diagram for a particular situation

### ISSUE THREAD

**Issue by yisiox** [nus-cs2103-AY2324S2/forum#1078]
@drustanyjt and I want to create documentation for a somewhat sizable software stack. The high level structure consists of several logical components, some of which can be grouped together into a subsystem. Each component in actuality could vary between a single class, or a group of classes together performing some specific functionality. The system is online (constantly processes new data flowing in) and has no databases. The goal is to communicate the structure of the system, which components form subsystems, and what data is passed between each component to new maintainers.

I know of the UML component diagram from the textbook, and it seems to fit the requirement of describing logical structure, subsystems, and the interfaces can represent what data is passed between components. But the textbook does not provide any details and material online for component diagrams seem to be scarce/inconsistent/not detailed. The UML specification feels more syntactic than sematic and I am having trouble understanding how to use the elements together in a diagram beyond just what each element is. Is there a detailed resource for component diagrams? Or is it okay so long as it is sufficient to convey what I intend to be conveyed (credibility is less important here)?

Another obvious candidate is architecture diagrams. Since they are meant to be free-form diagrams, can I simply come up with anything that is representative of the system? The textbook mentions that they are meant to be a very high level design, but since here the detail of data passed between components is important, does this indicate I should talk about the components relationship and data passed separately at different levels of abstraction (e.g. describe high level architecture with architecture diagram then show data flow with data flow diagram elsewhere)?

**Comment by damithc** [comment]
> Another obvious candidate is architecture diagrams. Since they are meant to be free-form diagrams, can I simply come up with anything that is representative of the system?

@yisiox This is a good choice (it is what we do in AB3 as well). Yes, you may use any reasonable symbol.



> The textbook mentions that they are meant to be a very high level design, but since here the detail of data passed between components is important, does this indicate I should talk about the components relationship and data passed separately at different levels of abstraction (e.g. describe high level architecture with architecture diagram then show data flow with data flow diagram elsewhere)?

Yes, that's right.
Another example https://teammates.github.io/teammates/design.html

**Comment by yisiox** [comment]
👍 Thank you Prof @damithc
