### ISSUE TITLE
Where do I find the questions for the Canvas bonus quiz questions?

### ISSUE THREAD

**Issue by sindhurajain** [nus-cs2103-AY2324S2/forum#108]
The week 3 quiz on canvas have a few bonus questions at the start but the questions are incomplete. Where do I find the questions?

I watched week 3's briefing but the questions were not mentioned. Thanks!

<img width="811" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/115209308/accd536a-316c-4173-aa75-0b1e3a467972">

**Comment by damithc** [comment]
@sindhurajain Most likely you watched only the pre-recorded _course_ briefing segment mentioned in https://nus-cs2103-ay2324s2.github.io/website/

These questions come from the Zoom recording of the Week 3 _weekly_ briefing -- recording link posted in https://canvas.nus.edu.sg/courses/56105

**Comment by yashma-sonara** [comment]
In last Friday's briefing, he goes over all the questions and answers. Maybe you can try to watch the video again as he goes over them throughout the lecture time.

**Comment by sindhurajain** [comment]
I had missed the weekly briefing as prof pointed out, thanks for your help!
