### ISSUE TITLE
Unable to run unit tests using either Gradle or JUnit

### ISSUE THREAD

**Issue by yashpola** [nus-cs2103-AY2324S2/forum#109]
**Error faced:** 

<img width="935" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/105275750/53653a42-bf28-4394-97c7-0d12382f9788">

**Test file sample:**

```
package Task;

import NicoleExceptions.NicoleException;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.fail;

public class DeadlineTest {
    @Test
    void deadline_noDescriptionGiven_nicoleExceptionThrown() {
        try {
            new Deadline("2024");
            fail();
        } catch (NicoleException e) {
            assertEquals(
                    "ERROR. Describe your deadline like this: deadline [task] by YYYY-MM-DD",
                    e.getMessage());
        }
    }
```

I have useJUnitPlatform() in the test section of my build.gradle and the dependencies are: 
```
dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
}
```

Any help would be appreciated

**Comment by yashpola** [comment]
This is the result when I run `./gradlew test` from the cli: 

<img width="619" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/105275750/f13c2823-3fb8-463a-8b04-fee72d54af7e">

but I have no context for why these tests are failing and how to rectify this

**Comment by damithc** [comment]
While waiting for peer inputs, if using Intellij, try these 'common remedies' one-at-a-time in this order:
  * Choose `File` -> `Invalidate caches`
  * Close Intellij -> Delete the `.idea` folder -> Re open the project in Intellij
  * Clone the fork to a different location and open the project in Intellij again to get a fresh start without losing changes you did so far.
  
Once you are able to run tests via Intellij, you can easily see the reason for failure.

**Comment by macareonie** [comment]
Try running the tests using Intellij to check if the problem is with the test case code or your configuration of Gradle:
settings > build, execution, deployment > build tools > gradle and change the "run tests using" from gradle default to intellij 

If the issue is with your code itself, maybe try printing the NicoleException e in the catch block and using toString/getMessage to check if you are getting the right error message for your test

**Comment by yashpola** [comment]
I had to do both of these to make it work! 

1. Change back testing from gradle to intellij in project settings.
2. Change e.getMessage() to e.toString() since when I throw exceptions I'm printing them to System.out, thus e.getMessage() was coming up as null.

Thanks sm @macareonie :)
