### ISSUE TITLE
github tags

### ISSUE THREAD

**Issue by yashma-sonara** [nus-cs2103-AY2324S2/forum#11]
The tasks for Week 2 explain that we have to use tags in iP. Is this once we finish the part for that level, or should we create all tags now? Thanks.

**Comment by damithc** [comment]
@yashma-sonara When you finish implementing an iP increment, you should commit the code, and tag that commit using Git (not Github). So, the tag for an iP increment should be attached to the commit that contains the code of that increment.  You will be creating tags at different points of the iP, not all at once.

**Comment by neyapraveen** [comment]
@yashma-sonara To explain further, a tag acts like a pointer to a particular commit or points in Git history (e.g. the tag Level-2 should point to the commit in which you have completed the increments for Level 2). 
As such, you would want your tag to reference the commit in which you have completed the increment, and as prof said, should be created at different points in time. 
[https://nus-cs2103-ay2324s2.github.io/website/book/gitAndGithub/tag/](url)

**Comment by damithc** [comment]
Thanks for the additional explanation, @neyapraveen
