### ISSUE TITLE
Are we allowed to use SQLite?

### ISSUE THREAD

**Issue by tankh99** [nus-cs2103-AY2324S2/forum#111]
Or must we implement our own file reading capabilities?

**Comment by damithc** [comment]
@tankh99 In the iP, there is no restriction on the data storage mechanism (in the tP, it is required to be a human-readable file, and relational databases are not allowed. More info https://nus-cs2103-ay2324s2.github.io/website/admin/tp-constraints.html).

That said, even in the iP you need to eventually package your chatbot as a .jar file for distribution. So, don't use any storage method that will get in the way of distributing the app as a single .jar file, or will require the user to install any additional software in their computer.

**Comment by tankh99** [comment]
Understood, thank you!
