### ISSUE TITLE
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

### ISSUE THREAD

**Issue by NeoHW** [nus-cs2103-AY2324S2/forum#112]
Hi, I would like to ask if anyone received this message at the end of using `./gradlew clean build` or `./gradlew run`?

```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.6.2/userguide/command_line_interface.html#sec:command_line_warnings
```

Was wondering if this would affect future requirements and how did this come about as I don't recall changing the version of gradlew

**Comment by damithc** [comment]
@NeoHW deprecation warnings are not urgent to handle. So, let's wait for a while to see if anyone else is facing similar issues.

**Comment by hjungwoo01** [comment]
Hi, I encountered the same deprecation warning. After updating Gradle and running the program again, the issue was resolved, and everything now works as expected.

**Comment by kervyntan** [comment]
Hi, so far I haven't encountered this error using Gradle

**Comment by NeoHW** [comment]
shall try the update out thank you
