### ISSUE TITLE
Switch Statement Coding Standard for the Default Case

### ISSUE THREAD

**Issue by DhiraPT** [nus-cs2103-AY2324S2/forum#113]
Is it considered a violation of the coding standard to omit the `break` statement in the `default` case, given that it is unnecessary?
If no, do we still need to include the `//Fallthrough` comment in the `default` case, even though it is obvious that the execution will go to the end of the switch block?

**Comment by damithc** [comment]
The main goal of the coding standard is consistency. So, the best course of action is to just follow the coding standard as much as possible. If something is not specified in the coding standard, you can decide your own convention for it, in which case you should apply that consistently across the entire codebase.
In this specific case, there is an example in the coding standard that uses a `break` with the `default`, so you can do the same.
