### ISSUE TITLE
Issue Tracker

### ISSUE THREAD

**Issue by Darkarche3** [nus-cs2103-AY2324S2/forum#114]
Does anyone know how to turn on Issue Tracker for the IP? I don't have the Issues button in my bar and also can't find it in the settings. Thanks ahead for any help!

**Comment by Jerome-j** [comment]
Hello @Darkarche3,

I believe it is this setting:

<img width="765" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/49815108/ca0147ed-a95c-4cec-a41d-3b1eb4415615">

**Comment by Darkarche3** [comment]
Thanks @Jerome-j !
