### ISSUE TITLE
iP: Automated Text UI Testing for Special Characters 

### ISSUE THREAD

**Issue by billyhoce** [nus-cs2103-AY2324S2/forum#115]
For my chatbot, I have made use of some special characters for text-art (Not normally found on keyboard) such as:
███╗░░░███╗ and ━━━━━━

However, upon following the steps for automated UI testing, I encountered multiple lines of the following error when running my `runtest.bat`

`..\src\main\java\MeanDuke.java:8: error: unmappable character (0x90) for encoding windows-1252`

Upon some research, I came across a solution that asks me to add this tag into the javac compile line in the `runtest.bat` file
`-encoding ISO-8859-1`

Of which resolved the error, but results in different results between my actual and expected files:

Actual: Multiple lines of 
`G??G??G??G??G??G??G??G??G??G??G??G??G??G??G??G??G??G??G??G??G??G??G??G??G??G??G??G??G??G??G??G??G??G??G??G??G??G??G??G??G??G??G`

Expected: Multiple lines of
`GûêGûêGûêGòùGûæGûæGûæGûêGûêGûêGòùGûêGûêGûêGûêGûêGûêGûêGòùGûæGûêGûêGûêGûêGûêGòùGûæGûêGûêGûêGòùGûæGûæGûêGûêGòùGûæGûæGûæGûæGûæGûæG`

What may this to due to and how do I resolve it. Thank you!

**Comment by damithc** [comment]
@billyhoce The best is to avoid such special characters. Even if you resolve it now, it will cause problems at later stages when you package the chatbot into an executable for others to use.

**Comment by billyhoce** [comment]
Okay, thanks prof @damithc! Will take your advice and avoid using these characters. Interesting to see how different types of character encoding can affect programs.
