### ISSUE TITLE
Unable to access file directory running with jar

### ISSUE THREAD

**Issue by UdhayaShan1** [nus-cs2103-AY2324S2/forum#118]
I am able to create the JAR file using Gradle/or building artifact but both run into the same issue

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39399745/cfea6ef0-66bd-47d6-b678-68b0bba8a89a)

My directory is as such
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39399745/98cf42a4-d66b-4329-8989-6f31f9a3b3d1)

I am not sure which step I am missing to allow the jar file to recognise such directory (i am guessing its something to do with relative path and jar files don't know what im referring to)?

Im accessing by 
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39399745/b895cec9-3df5-43dd-8d64-d4a4ccffc3f6)

and 

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39399745/f24a1a43-4a39-4a46-81f0-f73c2b47addd)

Appreciate any help, thanks

**Comment by UdhayaShan1** [comment]
It works when copy pasting to the jar directory

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39399745/237643d1-8030-4b5d-8014-dd4211b38603)

But this means a desync..

**Comment by yleeyilin** [comment]
Hi, I am not sure if this will help rectify your issue, but it seems like maybe your new file code is unable to create a new directory?  you might want to try something like that where the mkdirs will create the necessary directory for you to write into the file. File file = new File(filePath);
        if (!file.exists()) {
            try {
                file.getParentFile().mkdirs();
                file.createNewFile();
            } catch (IOException e) {
                new DukeException(e.getMessage());
            }
        }

**Comment by UdhayaShan1** [comment]
@yleeyilin Thanks will try,  does your JAR then create a new directory in build/libs then? next to the JAR

**Comment by yleeyilin** [comment]
@UdhayaShan1 yup it does create a new dir. 
<img width="591" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/116061001/ce85eaad-71df-4dff-8ebb-580d4b76aa81">

**Comment by UdhayaShan1** [comment]
Gave up on trying to link to the same txt file in root/data

Simply just created new directory instead.

```ruby
  File file = new File(filePath);
  //We first check if file directory exists. We will create the folder for user instead.
  if (!file.exists()) {
      try {
          Files.createDirectories(file.toPath().getParent());
          Files.createFile(file.toPath());
          System.out.println("File created successfully\n It will appear in data folder.: " + filePath);
      } catch (IOException e) {
          System.err.println("Failed to create file.\n Do try again!: " + e.getMessage());
      }
  }
```

**Comment by damithc** [comment]
> Gave up on trying to link to the same txt file in root/data

@UdhayaShan1 that was never intended anyway. The chatbot run in one location is not meant to access the data file created when it was run in a different location.

**Comment by hansstanley** [comment]
Hi @UdhayaShan1, I'm from a senior batch dropping in to see if I can help.

> But this means a desync..

> Gave up on trying to link to the same txt file in root/data

It seems like you're trying to specifically access the `data` in your project directory from the JAR, which generally would not work as the JAR file is meant for distribution and would not have access to your project directory.

In the real world, there are established places to store program-specific data that you might have seen before (e.g. `ProgramData` in Windows, `Application Support` in macOS), but that is probably out of syllabus and you're already on the right track with the file checking and creating.

**Comment by UdhayaShan1** [comment]
Thanks!, not sure why I tried linking them
