### ISSUE TITLE
Type of printing/input classes for iP

### ISSUE THREAD

**Issue by UdhayaShan1** [nus-cs2103-AY2324S2/forum#12]
Sorry if I have missed this somewhere, are we only allowed to use the basic System.out.println and Scanner for our I/O? Can we use BufferedReader/PrintWriter as I have learnt from 2040S.

Thank you.

**Comment by damithc** [comment]
> Can we use BufferedReader/PrintWriter as I have learnt from 2040S.

@UdhayaShan1 Yes, that's fine too. It's up to you.

**Comment by UdhayaShan1** [comment]
Thanks!
