### ISSUE TITLE
Issue in saving the tasks for Level-7

### ISSUE THREAD

**Issue by radeon2525** [nus-cs2103-AY2324S2/forum#120]
I am not able to save my tasks in the file. The following is part of my saveToFile function's code for Todo, I have done it similarly for deadline and event

protected void saveToFile(List<Task> l) throws IOException{
        try {
            if (!FILE.exists()) {
                createFile();
            }
            FileWriter fw = new FileWriter(FILE);
            for (int m = 0; m < l.size(); m++) {
                Task task = l.get(m);
                if (task instanceof ToDo) {
                    fw.write("T | " + task.getStatusIcon() + " | " + task.description + "\n");
                } 
            }
            fw.close();
        }
        catch (IOException e) {
            System.out.println(e.getMessage());
        }
    }

**Comment by NeoHW** [comment]
Hi, 
Judging from your code, you seem to be iterating through your list and rewriting to FILE, which would lead to multiple overwriting of a single task. 
If that is the case, you can create a FileWriter object that appends to the file (instead of overwriting the current content) by specifying an additional boolean parameter to the constructor.
For Example: `FileWriter fw = new FileWriter(FILE, true); ` 

I would also suggest wrapping your code in a code block and also providing other useful information to help with debugging this issue such as `FILE`, `createFile()` etc.

**Comment by yleeyilin** [comment]
Hi, you might want to try a different method of handling the case where the file does not exist. if (!file.exists()) {
                file.getParentFile().mkdirs();
                file.createNewFile();  }

**Comment by damithc** [comment]
> protected void saveToFile(List l) throws IOException{
> try {
> if (!FILE.exists()) {
> createFile();
> }
> FileWriter fw = new FileWriter(FILE);
> for (int m = 0; m < l.size(); m++) {
> Task task = l.get(m);
> if (task instanceof ToDo) {
> fw.write("T | " + task.getStatusIcon() + " | " + task.description + "\n");
> }
> }
> fw.close();
> }
> catch (IOException e) {
> System.out.println(e.getMessage());
> }
> }

Tip: You can se [fenced code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) to format your post for better readability.

e.g.,
```java
protected void saveToFile(List<Task> l) throws IOException{
        try {
            if (!FILE.exists()) {
                createFile();
            }
            FileWriter fw = new FileWriter(FILE);
            for (int m = 0; m < l.size(); m++) {
                Task task = l.get(m);
                if (task instanceof ToDo) {
                    fw.write("T | " + task.getStatusIcon() + " | " + task.description + "\n");
                } 
            }
            fw.close();
        }
        catch (IOException e) {
            System.out.println(e.getMessage());
        }
    }
```

**Comment by UdhayaShan1** [comment]
I think you are rewriting

Consider using a StringBuilder then,
StringBuilder toAdd = new StringBuilder();
...
  try {
      FileWriter fw = new FileWriter(this.filePath);
      fw.write(toAdd.toString());
      fw.close();
  } catch (IOException e) {
      System.out.println("Error writing! Weird as f");
  }

**Comment by radeon2525** [comment]
Alright understood, thank you
