### ISSUE TITLE
Clarification on automated testing

### ISSUE THREAD

**Issue by xinen26** [nus-cs2103-AY2324S2/forum#121]
Upon reviewing my week 2 IP submission, I realized that I neglected to update my automated testing for levels 5 and 6. As a result, the automated testing currently only accommodates level 4. Will I get penalized for this oversight? 
Thank you!

**Comment by damithc** [comment]
@xinen26
Short answer: no. 
Long answer: in this [FAQ](https://nus-cs2103-ay2324s2.github.io/website/schedule/week2/project.html#:~:text=What%20if%20I%20discovered%20a%20bug%20after%20I%20finished%20an%20increment%3F)

**Comment by xinen26** [comment]
oh i see, thanks!
