### ISSUE TITLE
Minor typo in iP: Week 3 Level-7 FAQ

### ISSUE THREAD

**Issue by logical-1985516** [nus-cs2103-AY2324S2/forum#123]
For this FAQ on the course website:
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/107944536/daa4f9b5-d76c-4571-ae75-b54ab2320718)

I think `welcome to (but not _required) to)` should be `welcome (but not required) to`.

**Comment by damithc** [comment]
Fixed. Thanks for reporting this, @logical-1985516
