### ISSUE TITLE
Gradle cannot run Duke

### ISSUE THREAD

**Issue by ChuaZiLong** [nus-cs2103-AY2324S2/forum#127]
I am using Intellij
I got an error Cannot locate tasks that match ':Duke.main()' as task 'Duke.main()' not found in root project 'ip'.

I tried putting Duke.java with the main function in my ip folder but I am still getting the same error even though I think I am addressing the issue directly.

**Comment by NeoHW** [comment]
This issue might be due to your gradle task configurations:
Make sure that the mainClass in your build.gradle file is correctly set to the main class where your main method is located. 

```
application {
    mainClass.set("<your_main_class>")
}
```

**Comment by UdhayaShan1** [comment]
What is your application {}?

If your main class is like here,
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39399745/a3457d9d-1696-4e32-9161-5564a7ad2fda)


application {
    mainClass.set("RyanGosling")
}

This should work

**Comment by ChuaZiLong** [comment]
Thanks everyone. I did set my application correctly, but for some reason when intellij configured build.gradle.kts, kotlin wasn't set to the latest version. I set it to kotlin("jvm") version "2.0.0-Beta3", refreshed using gradle, and then it worked.
