### ISSUE TITLE
[Fulfilling the recommended goal of using Gradle

### ISSUE THREAD

**Issue by cheahTJ** [nus-cs2103-AY2324S2/forum#128]
Hi all, with regards to setting up gradle to run unit tests, may I know what exactly does this entail? I have tried to follow this guide: https://se-education.org/guides/tutorials/junit.html but it seems like all teh required dependencies are already added into the necessary build gradle files when the branch (add-gradle-support) is being merged to the master branch. Could I get some guidance on this?

**Comment by cheahTJ** [comment]
Does it mean to set up for example the respective test classes?

**Comment by damithc** [comment]
@cheahTJ Just ensure you can run JUnit tests using Gradle. Yes, the Gradle file provided already has the required dependencies. Provided you did the initial Gradle set up correctly and you added JUnit tests the way Gradle expects them to be, this requirement is met automatically.
Note that adding JUnit is in the is a separate iP increment. So, you can wait till you reach that first.

**Comment by cheahTJ** [comment]
Thank you prof for the clarification!
