### ISSUE TITLE
Handle edge cases for tasks

### ISSUE THREAD

**Issue by UdhayaShan1** [nus-cs2103-AY2324S2/forum#13]
Is handling edge cases considered additional effort from the expectations, for example if task is done and we call mark on it, should we just ignore that it has already been marked and just mark again as if it was unmarked or give it a specialised message.

Thanks.

**Comment by damithc** [comment]
@UdhayaShan1 Expectations as to the level of error handling is given in [`Level-5` increment](https://nus-cs2103-ay2324s2.github.io/website/se-book-adapted/projectDuke/index.html#level-5-handle-errors).

> for example if task is done and we call mark on it, should we just ignore that it has already been marked and just mark again as if it was unmarked or give it a specialised message.

This one is up to you (i.e., it's above the 'minimum requirement')

**Comment by UdhayaShan1** [comment]
I see, thank you!
