### ISSUE TITLE
Git Standard tag

### ISSUE THREAD

**Issue by g-tejas** [nus-cs2103-AY2324S2/forum#130]
![CleanShot 2024-01-30 at 17 22 19@2x](https://github.com/nus-cs2103-AY2324S2/forum/assets/76802638/628cc545-db1d-46e3-b072-f105bfa593a6)
It was mentioned here that it's discouraged to edit past commit messages to comply with the Git standard. Would that mean that it would no longer be possible to fulfil this even if the subsequent weeks all comply (currently my dashboard doesnt show this fulfilled) if you have a single commit that violates the git standard? Or is the tag only relevant for the current week?

**Comment by damithc** [comment]
@g-tejas It will continue to check the latest 5 commits. So, it should eventually turn green if you start following the Git standard from now on, and will stay green as long as the latest 5 commits are compliant with the Git standard.
