### ISSUE TITLE
packages question

### ISSUE THREAD

**Issue by yashma-sonara** [nus-cs2103-AY2324S2/forum#131]
Hi, I was a bit confused about what is required for the packages increment. In my understanding, this doesn't involve changing much code, and mostly just rearranging the files. Will appreciate if others can explain this a bit more. Thanks

**Comment by damithc** [comment]
@yashma-sonara If your classes are already in packages, nothing to do. Otherwise, move them all inside suitably-named packages.

**Comment by yashma-sonara** [comment]
Thanks prof.
