### ISSUE TITLE
Clarification in Level-8

### ISSUE THREAD

**Issue by radeon2525** [nus-cs2103-AY2324S2/forum#133]
What should the input and output format of the event task be for level-8?

Also just to clarify on the Deadline task, we just need to output the Date in the format given in the question and not the time right?

**Comment by damithc** [comment]
> What should the input and output format of the event task be for level-8?

@radeon2525 up to you.

> Also just to clarify on the Deadline task, we just need to output the Date in the format given in the question and not the time right?

Factoring in the times is not a requirement, but you are welcome to do so.

**Comment by radeon2525** [comment]
Thank you for the clarification prof.
