### ISSUE TITLE
I/O testing for level 7

### ISSUE THREAD

**Issue by Ko-Khan** [nus-cs2103-AY2324S2/forum#134]
Saving my list to a file "./data/bit.txt". This does not cause not issues with manual testing. But when using i/o testing to test for regressions, I receive error :"java.io.IOException: The system cannot find the path specified".

**Comment by bachletuankhai** [comment]
Can you show your testing script and your code for loading and saving data? The location where you run your class is important since your program will look for the specified path in the current working directory.

Also, did you handle the case where "data/bit.txt" does not exist in the current working directory? You will need to create them (the directory AND the file) before trying to read from or write to the text file. Hope this helps.

**Comment by Ko-Khan** [comment]
` public static boolean createFile(File myFile) {
        try {
            if (myFile.createNewFile()) {
                return true;
            } else {
                return true;
            }
        } catch (IOException e) {
            System.out.println(e);
            return false;
        }
 }
`
I will run this in main with:
```
myFile= new File("./data/bit.txt");

if (!createFile(myFile)) {
            System.out.println("Error! Something went wrong while creating your file!");
            return;
        }
        try {
            FileWriter myWriter = new FileWriter(address, true);
        }   catch (IOException e) {
            System.out.println("I could not write to the file!:C");
        }
```

**Comment by Ko-Khan** [comment]
Is there a way I could always start from project root regardless of where I am executing my code?

**Comment by damithc** [comment]
> Is there a way I could always start from project root regardless of where I am executing my code?

@Ko-Khan That is not the intended behavior. When you give this product to others, there will not even be a 'project root' in their computers. So, the simpler thing is to save the file relative to where it is being run.

**Comment by Ko-Khan** [comment]
Oh! Thank you!

**Comment by bachletuankhai** [comment]
> `public static boolean createFile(File myFile) { try { if (myFile.createNewFile()) { return true; } else { return true; } } catch (IOException e) { System.out.println(e); return false; } }` I will run this in main with:
> 
> ```java
> myFile= new File("./data/bit.txt");
> 
> if (!createFile(myFile)) {
>             System.out.println("Error! Something went wrong while creating your file!");
>             return;
>         }
>         try {
>             FileWriter myWriter = new FileWriter(address, true);
>         }   catch (IOException e) {
>             System.out.println("I could not write to the file!:C");
>         }
> ```

You should add `myFile.getParentFile().mkdirs()` to create the parent directory before calling `createNewFile()` to create the file.

**Comment by yisiox** [comment]
Perhaps for clarity and the benefit of others who ran into the same issue as I did too, the issue seems to indeed be that the folder containing the file needs to be created first if it does not already exist.

A possible program flow is thus
```java
File myfile = new File("./data/bit.txt");
boolean isFolderMade = file.getParentFile().mkdirs(); // make parent folder
boolean isFileMade = file.createNewFile();
if (isFolderMade || isFileMade) {
    // file surely missing
}
```

**Comment by bachletuankhai** [comment]
> ```java
> if (isFolderMade || isFileMade) {
>     // file surely missing
> }
> ```

For checking if the file existed or not, I use `File::exists()`. Here is the full code snippet:
```java
File file = new File(filePath);
if (!file.exists()) {
    file.getParentFile().mkdirs();
    file.createNewFile();
}
```
