### ISSUE TITLE
Queries on JUnit test

### ISSUE THREAD

**Issue by cheahTJ** [nus-cs2103-AY2324S2/forum#135]
Hi all, could I check with regards to the JUnit testing on our methods in our classes, is it similar to the Text UI testing we did last week where we would test the method and see if it returns the same output that we anticipate (hardcoded in a sense since we know how our method should perform) by asserting equal them?

**Comment by cheahTJ** [comment]
Could I also enquire is there a reason why my tests failed but when I look at the assertEquals Difference actual and expected outputs comparison, they are identical?

**Comment by itstrueitstrueitsrealitsreal** [comment]
For your second question, remember to override the `Object::equals()` method in order to make your test pass, if you are comparing two objects which have the same attributes but have a different hash. This is because `assertEquals()` uses the `.equals()` method to compare the two objects.

**Comment by wilsonwid** [comment]
> Could I also enquire is there a reason why my tests failed but when I look at the assertEquals Difference actual and expected outputs comparison, they are identical?

This might be due to them being of different classes, e.g., one of them is a String and the other a custom-made class. This might be due to having the `toString()` method in your custom-made class redefined.

**Comment by NeoHW** [comment]
A suggestion would be that if there are non-visible characters that might be causing issues, you could also consider using a  diff checker to identify the differences.

**Comment by cheahTJ** [comment]
Thank you all for your inputs!! May I also check given the requirement of the JUnit section to test our method reasonably well, does it mean/is it a good practice to have multiple assertEquals() statements within a test method to test for one method?

**Comment by NeoHW** [comment]
That's one way to think about it, but as long as you're making sure that the functionality of your method is working regardless of how many asserts statements there are, it should be fine!

**Comment by cheahTJ** [comment]
@NeoHW  Thank you!!
