### ISSUE TITLE
More than 1 branch created...??

### ISSUE THREAD

**Issue by acekhoon** [nus-cs2103-AY2324S2/forum#136]
Hi!

I have just submitted level 7, and found out that more than 1 required branch is created which I am not very sure why it is the case. Basically, what I did was as follows:

1. Used git command "git branch branch-level-7" in order to create the branch, then "git checkout branch-level-7" in order to move my head to the branch created.
2. Then I did some modifications, then did git commit to update my branch as usual through "git add -> git commit -> git push -u origin branch-level-7" in order to push my commit to the github.

Above two processes, however, somehow created two duplicate branch named branch-level-7 as shown by gitk:

<img width="308" alt="Screenshot 2024-01-31 at 10 04 08 AM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/109423589/ec13c808-0f04-4b23-bc10-67e6c1dd5ac1">

Could anyone possibly advise me how to fix this error / why there are two duplicate branches with the identical name? I am not very sure why this happened (since I tried to follow the information from week 3 branch section). Thanks!!

**Comment by drustanyjt** [comment]
@acekhoon I believe this is correct, you have a local version of branch-level-7, and a remote version (on your github repo online, designated by `remotes/origin`). This happened when you used `git push` to push the branch commits to github.

**Comment by yadunut** [comment]
are the 2 branches that you talk about `branch-level-7` and `remotes/origin/branch-level-7`? If it is, `branch-level-7` points to the local branch and `remotes/origin/branch-level-7` points to the branch that is pushed to github. If you were to add more commits to your local branch, and look at gitk, you'll notice that the `branch-level-7` would be ahead of `remotes/origin/branch-level-7`and on `git push`, it would sync back to pointing to the same commit.

**Comment by acekhoon** [comment]
I see. I was wondering about this more because I somehow got 3 branches on my github page, and based on the above comment, I believe it is because there are 2 branches; one from local repository and the other from the github (remote repo). Thanks!!
