### ISSUE TITLE
JUnit problems

### ISSUE THREAD

**Issue by yashma-sonara** [nus-cs2103-AY2324S2/forum#137]
Hi, I've been trying to set up the JUnit tests. I made the src/test/java/duke/task folder. Although I have written the tests for Todo.java and there are no errors in the file. When I try to run the tests I get the below error:

      Execution failed for task ':test'.
      > No tests found for given includes: [duke.task.TodoTest](--tests filter)

I tried to restart and remove the .idea folder. However, I still have the same problem. The stack trace is very long and just says : Gradle Test Run :test FAILED.

Will appreciate if someone can share what they did, if they had a similar issue. Thanks

**Comment by damithc** [comment]
@yashma-sonara Perhaps you can push your code to the fork (possibly on a separate branch) and share the link here so that others can try to replicate the problem?

**Comment by yashma-sonara** [comment]
https://github.com/yashma-sonara/ip/tree/unit-tests

In the above branch, is my code for unit tests and gradle setup

**Comment by aureliony** [comment]
I cloned your branch locally and ran `./gradlew test`. It completed successfully. It's likely an issue with your IntelliJ setup.

**Comment by JiaXinEu** [comment]
Try `./gradlew clean`, then run the tests with `./gradlew test`.

**Comment by yashma-sonara** [comment]
@JiaXinEu Thanks, this seemed to work and pass my tests :)

**Comment by damithc** [comment]
Resolved within 2 hours! Nice work @aureliony @JiaXinEu 💯
