### ISSUE TITLE
Scanner.nextline() returns an invisible character

### ISSUE THREAD

**Issue by billyhoce** [nus-cs2103-AY2324S2/forum#138]
I have a .txt file containing the following 

TODO
todo1
false
DEADLINE
deadline1
...

When I do
```
Scanner s = new Scanner(saveFile);
while (s.hasNext()) {
    String next = s.nextLine();
    System.out.println(next);
```

after the line 3 "false", I am getting an invisible character being scanned by s.nextLine().

More specifically, this is my code and output

```
Scanner s = new Scanner(saveFile);
            while (s.hasNext()) {
                String next = s.nextLine();
                System.out.println(next);
                switch (next) {
                case "TODO":
                    tasklist.add(new ToDo(s.nextLine(), s.nextBoolean()));
                    break;
                case "DEADLINE":
                    tasklist.add(new Deadline(s.nextLine(), s.nextBoolean(), s.nextLine()));
                    break;
                case "EVENT":
                    tasklist.add(new Event(s.nextLine(), s.nextBoolean(), s.nextLine(), s.nextLine()));
                    break;
                default:
                    throw new NoSuchElementException(s.nextLine());
                }
            }
```
Output (note empty line between TODO and exception line):
```
TODO

java.util.NoSuchElementException: DEADLINE
```

Anyone can help with this behaviour? The text file is attached. Running intellij on windows.

[MeanDuke.txt](https://github.com/nus-cs2103-AY2324S2/forum/files/14107256/MeanDuke.txt)

**Comment by aureliony** [comment]
`nextBoolean()` scans only the next token which is `false`. It does not scan the `'\n'` after false. Hence the `nextLine()` will scan `'\n'` instead of the next line. You can use `s.skip("\n");` to fix this issue.

**Comment by billyhoce** [comment]
> `nextBoolean()` scans only the next token which is `false`. It does not scan the `'\n'` after false. Hence the `nextLine()` will scan `'\n'` instead of the next line. You can use `s.skip("\n");` to fix this issue.

@aureliony Indeed that was the problem! Thank you and resolved.
