### ISSUE TITLE
issues with Gradle integration into iP

### ISSUE THREAD

**Issue by Zack-Tay** [nus-cs2103-AY2324S2/forum#139]
Hi all, currently experiencing an issue with integrating gradle into my iP. After merging the add-gradle-support branch to master branch and then following the instructions as stated, I have received the following error messages (redid multiple times):

Starting Gradle Daemon...
Gradle Daemon started in 2 s 127 ms

FAILURE: Build failed with an exception.

* What went wrong:
Could not open init generic class cache for initialization script 'C:\Users\user\AppData\Local\Temp\ijmapper.gradle' (C:\Users\user\.gradle\caches\7.6.2\scripts\do9ng9okg4cokvn4advsx65hp).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 65

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights. 

* Exception is:
org.gradle.cache.CacheOpenException: Could not open init generic class cache for initialization script

Unsupported class file major version 65

Appreciate any help to fix this issue thanks!

**Comment by aureliony** [comment]
Your likely configured the Java version as 21 on IntelliJ. Follow [this link](https://stackoverflow.com/a/67101848) to fix it.

**Comment by Zack-Tay** [comment]
> Your likely configured the Java version as 21 on IntelliJ. Follow [this link](https://stackoverflow.com/a/67101848) to fix it.

Thank you for the solution. It has been fixed.
