### ISSUE TITLE
Question in Level-3

### ISSUE THREAD

**Issue by radeon2525** [nus-cs2103-AY2324S2/forum#14]
I am having trouble figuring out how to store the integer which comes after "mark" or "unmark" to use it to traverse the list and what should I do if the user enters an integer that is out of range.

**Comment by UdhayaShan1** [comment]
Not sure if your asking about parsing, if so its Integer.parseInt(<string>.split(" ")[1])

For second part, #13

**Comment by radeon2525** [comment]
Okay understood thanks
