### ISSUE TITLE
Do I need to do A-MoreOOP and A-Packages?

### ISSUE THREAD

**Issue by tankh99** [nus-cs2103-AY2324S2/forum#140]
Hi, I would like to ask for advice on whether or not my code needs MoreOOP. Not asking for a code review, just want to get a brief sensing. I have the following classes:

1. TaskManager - Similar to TaskList, manages the entire command line parsing, as well as CRUD of tasks 
2. Database - Similar to Storage, manages the data access layer, but also FileUtils, and DAO classes to help with the data management
3. StringUtils - Similar to Parser, as well as the individual Dao classes which has a getFrom() method which converts String input into model objects
4. UIManager - Similar to UI, it essentially is called whenever an operation is made, e.g. delete, list and is only used to print out UI

Are these sufficient enough to pass MoreOOP?

Similarly, if I already organise my files into separate folders, e.g. Enums, Dao, Utils, am I considered to have passed this?

**Comment by yashma-sonara** [comment]
I also did 4 classes similar to yours. However, my command line parsing is all done in a `parser` class separate from the `task `class.

**Comment by damithc** [comment]
@tankh99 The minimal requirement is to have at least these four classes (or equivalent):

* Ui: deals with interactions with the user
* Storage: deals with loading tasks from the file and saving tasks in the file
* Parser: deals with making sense of the user command
* TaskList: contains the task list e.g., it has operations to add/delete tasks in the list

**Comment by tankh99** [comment]
Got it, thanks. I guess I just wanted to make sure

**Comment by tankh99** [comment]
Thanks for the replies! Forgive me if I've misunderstood something, but regarding A-Packages, does this increment want us to just organise our files into logical file organisations, or that it wants us to change the project directory from src/main/java to src/main/java/duke?

**Comment by damithc** [comment]
> regarding A-Packages, does this increment want us to just organise our files into logical file organisations, or that it wants us to change the project directory from src/main/java to src/main/java/duke?

@tankh99 The former. In fact, we don't normally expect a folder named duke or a class named `Duke.java` at this point because the product name was supposed to be changed in Level-0

**Comment by tankh99** [comment]
Ah, I see. I've amended accordingly since it sees like I missed this step in Level-0. Thanks for the clarification prof!
