### ISSUE TITLE
Unable to remove a commit that has been pushed to remote repo

### ISSUE THREAD

**Issue by youdonnnn** [nus-cs2103-AY2324S2/forum#141]
I was testing out how to add a new branch and did a test commit both on the new branch and on master. After merging them together, I wanted to reset back to my Use Enums commit and remove all future commits.

But when I did a hard reset back to my Use Enums commit and tried to force push to remote repo, the option was not available. When I did a normal push, I was hit with a push rejected (screenshot attached) and both options available there did not resolve my issue, I still get the push rejected notice everytime..

<img width="346" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/123254704/eb8ff555-8800-4670-a872-b26bf8bd4b77">

**Comment by tankh99** [comment]
Looks like you need to merge the two branches. Perhaps because you removed a commit, then now one branch is behind the other. Try merging?

**Comment by damithc** [comment]
@tankh99 Some GUI doesn't allow the force-push as much as the CLI. So, you can try force-pushing via the CLI.

**Comment by tankh99** [comment]
> @tankh99 Some GUI doesn't allow the force-push as much as the CLI. So, you can try force-pushing via the CLI.

Oh, then if this is the case, try running `git push --force` on your branch. But make sure your commits are all up to date first because sometimes you may lose commits by force pushing.

**Comment by youdonnnn** [comment]
> > @tankh99 Some GUI doesn't allow the force-push as much as the CLI. So, you can try force-pushing via the CLI.
> 
> Oh, then if this is the case, try running `git push --force` on your branch. But make sure your commits are all up to date first because sometimes you may lose commits by force pushing.

Thank you so much! I've managed to resolve the issue using this command!
