### ISSUE TITLE
Minor Typo In Static Analysis Video

### ISSUE THREAD

**Issue by jieqiboh** [nus-cs2103-AY2324S2/forum#144]
In the [Static Analysis Section](https://nus-cs2103-ay2324s2.github.io/website/schedule/week4/topics.html#w4-7-static-analysis) page, there is a typo in the video title.

In

> Quality Assurance - Static Analsysis - What

It should be,

> Quality Assurance - Static Analysis - What

Below is a screenshot for reference:
<img width="944" alt="Screenshot 2024-01-31 at 8 08 57 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/93033071/45b0e2f5-a40c-476f-a8b8-01d0b7886b4f">

**Comment by damithc** [comment]
Fixed. Thanks for reporting it, @jieqiboh
