### ISSUE TITLE
Forgot to follow the Git standard commit style

### ISSUE THREAD

**Issue by sethteo** [nus-cs2103-AY2324S2/forum#145]
I accidentally forgotten to use the Git standard in my commits for level 7 and level 8 but have followed the Git standard for subsequent commits should I rename the commits.

**Comment by damithc** [comment]
@sethteo No need. It will keep checking and turn back to green once your latest 5 commits are compliant with the standard, and will stay green as long as you keep following the standard.

**Comment by sethteo** [comment]
> @sethteo No need. It will keep checking and turn back to green once your latest 5 commits are compliant with the standard, and will stay green as long as you keep following the standard.

Thank you Prof!
