### ISSUE TITLE
JUnit Tests run only when I right click on the test folder, not from the actual testing class

### ISSUE THREAD

**Issue by appleraincoat** [nus-cs2103-AY2324S2/forum#146]
Hi, I'm using IntelliJ and trying to implement a test class. I have created the test class in the correct manner, but when I right click the class name and select the option to run as stated in the instructions:
"To run a specific JUnit test class (e.g., src/test/java/seedu/DukeTest.java), right-click on the test class, and choose  Run {classname}."
<img width="367" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/122220024/a12a3389-f736-4c59-aa4c-278c17f2d594">

I get an error saying Execution failed for task ':test'. No tests found for given includes: [Commands.CommandTest](--tests filter).
<img width="474" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/122220024/954ab36c-29f5-43d9-8a16-2801f4235900">

However, when I run the tests from the test folder it is able to work.
<img width="306" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/122220024/40185361-262d-41c6-8126-79d133cf527c">

 Is this something I need to fix or is it ok as long as I can run the tests? Thank you!

**Comment by yashma-sonara** [comment]
If your tests run and pass, that should be fine. But you can try doing `./gradlew clean`, then run the tests with `./gradlew test`. That may work since I had the same error as you.

**Comment by appleraincoat** [comment]
@yashma-sonara i am able to run and pass the tests using CLI with gradlew test, but running on IDE still gives the same error.

**Comment by damithc** [comment]
@appleraincoat Try these 'common remedies' one-at-a-time in this order:
  * Choose `File` -> `Invalidate caches`
  * Close Intellij -> Delete the `.idea` folder -> Re open the project in Intellij
  * Clone the fork to a different location and open the project in Intellij again to get a fresh start without losing changes you did so far.

**Comment by appleraincoat** [comment]
@damithc hi Prof, thank you for the suggestions. unfortunately, the issue has remained exactly the same even after doing all the steps in order. i'm not sure if i can conclude that the gradle setup was done incorrectly because "gradlew test" still runs correctly from CLI.

**Comment by damithc** [comment]
@appleraincoat See if changing this setting to `Intellij` makes a difference:

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/8d3d5f05-4767-4fbb-8360-504cfcb92ea1)

**Comment by appleraincoat** [comment]
@damithc hi Prof, it works now after changing to IntelliJ. thank you very much! is it supposed to work with both set as Gradle? or did i miss an instruction to change it to IntelliJ?

**Comment by damithc** [comment]
> Prof, it works now after changing to IntelliJ. thank you very much! is it supposed to work with both set as Gradle? or did i miss an instruction to change it to IntelliJ?

@appleraincoat I don't think we mentioned it specifically in our instructions, but I suspect this setting is required to run one test at a time. Could be due to some recent change in IntelliJ, as I don't remember encountering this in previous semesters.

**Comment by appleraincoat** [comment]
@damithc Understood. thank you very much for the help Prof!

**Comment by appleraincoat** [comment]
@damithc Understood. thank you very much for the help Prof!
