### ISSUE TITLE
How do i branch-level-7 properly

### ISSUE THREAD

**Issue by LargeCrowd** [nus-cs2103-AY2324S2/forum#147]
I didnt seem to be able to successfully branch-level-7, so now imtrying to figure out how to branch-level-8 and let it meet the iP tracker thing, because im quite confused. I've been using github desktop for this btw.

I would appreciate some indepth instructions please and thank you :')

```
Do Level 7 in a branch named branch-Level-7. Here are the steps:

- [X] Start a branch branch-Level-7. 
- [X] Implement Level 7 while committing to that branch at appropriate points,
- [ not sure if i did this right. is the master branch in this instance the upstream master or my local master? ] Merge the branch back to the master branch (remember to create a merge commit i.e., no fast-forward).
- [ ] Git tag the merge commit in the master branch as usual (i.e., add the tag Level-7).
- [ not sure how to do this/ what it means] Push the master branch, push the branch-Level-7, and push the tag, to your fork.

 ! Advanced git users: do not delete the branch after merging.
 ! Only merged branches are detected by the script. After merging a branch b1 to the master branch, you need to push both the master and the b1 branches to the fork. Pushing the master branch does not automatically take the b1 branch along with it just because it is already merged to the master branch.
```

**Comment by bachletuankhai** [comment]
- From your local master branch, create a new branch `branch-Level-7`

**Comment by LargeCrowd** [comment]
OK I figured it out.

Using github desktop,
- Start a branch branch-Level-7. 
- Commit Level 7 implementations to branch-level-7. 
- Switch branch back to master
- In the top toolbar, Branch -> Merge into current branch... -> select branch-level-7 -> create a merge commit
- Add the tags into the master commit
- Push all the branches and tags to origin
