### ISSUE TITLE
Creating JAR file

### ISSUE THREAD

**Issue by cheahTJ** [nus-cs2103-AY2324S2/forum#148]
Hi, did anybody encounter this when trying to build your JAR file: java: JDK isn't specified for module 'ip.main'? This is the IntelliJ method of trying to create the JAR file. I wanted to try using the Gradle way but I can't seem to run the command 'gradlew shadowJar' because the command gradlew is not found. Could I get some help on this?

**Comment by JiaXinEu** [comment]
Have you tried `./gradlew shadowJar` , with the `./` in front?

**Comment by damithc** [comment]
@cheahTJ You need to go back to the Gradle option. The Intellij option becomes harder later after we add a GUI. You can post the Gradle problem as a separate issue. I'm have a feeling it is solvable.

**Comment by itstrueitstrueitsrealitsreal** [comment]
have you tried `./gradlew shadowJar`?

**Comment by cheahTJ** [comment]
HI yes this was the issue. But after running that, 2 jar files were built (one named ip.jar and the other named duke.jar). However, when I try to run the duke.jar: i got this error:

Error: Could not find or load main class seedu.duke.Duke
Caused by: java.lang.ClassNotFoundException: seedu.duke.Duke

And when i run the ip.jar file i got this error:
no main manifest attribute, in /Users/(my name)/Desktop/ip/build/libs/ip.jar

Could I get some help on this?
> Have you tried `./gradlew shadowJar` , with the `./` in front?

**Comment by cheahTJ** [comment]
> @cheahTJ You need to go back to the Gradle option. The Intellij option becomes harder later after we add a GUI. You can post the Gradle problem as a separate issue. I'm have a feeling it is solvable.

Yup prof, I have reverted back to using Gradle but I am met with the issues above ^

**Comment by damithc** [comment]
In case those files are from previous faulty attempts, you can try `./gradlew clean shadowJar`

**Comment by cheahTJ** [comment]
Hi prof, I have tried running this command ./gradlew clean shadowJar but running those 2 jar files give me the same error as the one stated above @damithc

**Comment by damithc** [comment]
@cheahTJ You might want to share the contents of your build.gradle file here so that others can try to use it for troubleshooting your problem.
Also, delete those problematic jar files manually.

**Comment by cheahTJ** [comment]
This is the content of my build.gradle: 
```
plugins {
    id 'java'
    id 'application'
    id 'com.github.johnrengelman.shadow' version '7.1.2'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.10.0'
    testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.10.0'
}

test {
    useJUnitPlatform()

    testLogging {
        events "passed", "skipped", "failed"

        showExceptions true
        exceptionFormat "full"
        showCauses true
        showStackTraces true
        showStandardStreams = false
    }
}

application {
    mainClass.set("seedu.duke.Duke")
}

shadowJar {
    archiveBaseName = "duke"
    archiveClassifier = null
    dependsOn("distZip", "distTar")
}

run{
    standardInput = System.in
    enableAssertions = true
}
```

On a side note, I was wondering if the issue lies with me not having this line of code: mainClassName = 'seedu.duke.Main'
but I am not sure if that is equivalent to "mainClass.set("seedu.duke.Duke")" in the application section

**Comment by damithc** [comment]
@cheahTJ While waiting for others to comment, a separate thing you might want to take note of (and fix later): as your product is no longer called Duke (as per Level-0), there should not be a class named Duke.java in your project.

**Comment by cheahTJ** [comment]
Would it be recommended to change now before I create the jar file?

**Comment by UdhayaShan1** [comment]
(If it still dosent work), Can we see your main directory as well.

**Comment by cheahTJ** [comment]
Here is my main directory, I'm still stuck:
![Screenshot 2024-02-01 at 12 45 47 AM](https://github.com/nus-cs2103-AY2324S2/forum/assets/122202483/14a2c017-0029-4ac3-8da4-8a71002d73fe)

**Comment by itstrueitstrueitsrealitsreal** [comment]
Judging by your directory structure and the code in your repo, you should set the mainClass to Duke, i.e 
```shell
application {
    mainClass.set("Duke")
}
```

**Comment by chewbum** [comment]
this is my config for my build.gradle file, my directory structure is the same as yours 

```
application {
    mainClass.set("duke.Duke")
}

shadowJar {
    archiveBaseName = "duke"
    archiveClassifier = null
    dependsOn("distZip", "distTar")
}
```

**Comment by cheahTJ** [comment]
I have tried changing my build file to this configuration but it still does not work given my directory structure below:
Inside my Pingme.java file also have a public static main method which calls a run() function to start my application as per guided in the A-OOP section. May I get some help on this?

```
application {
    mainClass.set("Pingme")
}

shadowJar {
    archiveBaseName = "Pingme"
    archiveClassifier = null
    dependsOn("distZip", "distTar")
}
```

![Screenshot 2024-02-01 at 1 09 45 PM](https://github.com/nus-cs2103-AY2324S2/forum/assets/122202483/25453325-c509-4c36-b9e2-7b1003557bdc)

**Comment by Javiery3889** [comment]
@cheahTJ Based on your directory structure, I believe the correct format  is `mainClass.set(<package_name>.<class_name>)` in `build.gradle`. Judging by your project structure, I believe it should be:
```
application {
    mainClass.set("pingmebot.Pingme")
}

shadowJar {
    archiveBaseName = "pingmebot"
    archiveClassifier = null
    dependsOn("distZip", "distTar")
}
```

**Comment by cheahTJ** [comment]
@Javiery3889 Yup this works, thank you!! After running ./gradlew clean shadowJar, ip.jar and pingmebot.jar were created but when I try to run ip.jar, is it normal to get this error (pingmebot.jar can be executed now though):

```
no main manifest attribute, in /Users/myname/Desktop/ip/build/libs/ip.jar
```

**Comment by cheahTJ** [comment]
With regards to the above, is it okay for just the jar file of the main class (in my case is pingmbot.jar) to be working and be uploaded as a new release on my fork (as per the instruction of A-jar) or do I need to upload both the WORKING ip.jar and pingmebot.jar files?

**Comment by damithc** [comment]
> With regards to the above, is it okay for just the jar file of the main class (in my case is pingmbot.jar) to be working and be uploaded as a new release

@cheahTJ Yes, that's enough. In fact there is no need to generate two jar files.
Try removing this line.
`dependsOn("distZip", "distTar")`

**Comment by cheahTJ** [comment]
@damithc  Thank you prof !! Yup indeed after removing this line, 1 jar file was created only. May I ask what does this line actually mean: dependsOn("distZip", "distTar")?

**Comment by damithc** [comment]
> May I ask what does this line actually mean: dependsOn("distZip", "distTar")?

Good question @cheahTJ Let's see if anyone can pitch in with the answer...

**Comment by ReganChoy** [comment]
From what I understand, distZip and distTar are both from the "distribution" plugin. A new "distribution" directory will be created and the [root_name].jar will be packaged into a zip and tar folder respectively.

dependsOn seems to reinforce an order in executing tasks.
A.dependsOn(B) would mean A can only run if B is done or present. This is different from mustRunAfter where A.mustRunAfter(B).
If both A and B are present, B runs first then A. However, if B is not present, A can still execute.

Do correct me if I am wrong!

Sources:
https://docs.gradle.org/current/userguide/distribution_plugin.html
https://melix.github.io/blog/2021/10/gradle-quickie-dependson.html
https://stackoverflow.com/questions/42033490/whats-the-difference-between-mustrunafter-and-dependson-in-gradle

**Comment by cheahTJ** [comment]
Thank you all!! I will proceed to close this issue.
