### ISSUE TITLE
Why doesn't my graph show the branching?

### ISSUE THREAD

**Issue by SherwynNg** [nus-cs2103-AY2324S2/forum#149]
Hi, I would like to ask why doesn't my graph show the branching. I have creating a new branch named "branch-level-8" and committed in my branch but it doesn't show the graph. Is it suppose to be like this? 

Thanks in advance!

<img width="1470" alt="Screenshot 2024-02-01 at 1 34 14 AM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/84394326/66e07b0b-4f81-4c75-89bf-73b62920e8d1">

**Comment by NeoHW** [comment]
this would most likely be due to your merges being a fast forward. If you would like to see the branching, you can check the box under settings: "do not fast-forward, always create commit when merging" option

**Comment by damithc** [comment]
Good diagnosis, @NeoHW 💯 
@SherwynNg we advise not to use fast-forward in the iP, so that branches appear more visual in the revision graph.
