### ISSUE TITLE
Early Submission participation for Quizzes 

### ISSUE THREAD

**Issue by cheahTJ** [nus-cs2103-AY2324S2/forum#15]
Hi prof, may I confirm if i submit a quiz attempt before Monday and decide to retry the quiz again after Monday, would I still get the early submission participation points despite resubmitting another attempt (on Monday onwards)?

**Comment by damithc** [comment]
@cheahTJ Depends on the score. Related https://github.com/nus-cs2103-AY2324S2/forum/issues/8#issuecomment-1900624951
