### ISSUE TITLE
Branches not detected by script after changing past commit messages.

### ISSUE THREAD

**Issue by chonghaoen** [nus-cs2103-AY2324S2/forum#150]
I changed my pushed commit messages to fit the Git standard as I had inserted punctuations by mistake. After googling how to do it, I did a rebase and a force push, but now my branch Level 7 and 8 cannot be detected by the scripts. Attached is how my Sourcetree looks right now.

![Screenshot 2024-02-01 085223](https://github.com/nus-cs2103-AY2324S2/forum/assets/109787103/6e44aad2-32c5-49b3-82b2-a55871098f07)

**Comment by damithc** [comment]
@chonghaoen It's not a big issue if you lost some branches. Remember to use branches in future increments, as specified.
It's also OK to miss the Git standard in a few commits, provided you follow it in future commits.
On a related note, editing past commits and force-pushing is discouraged in the iP/tP, as it will interfere with progress monitoring scripts.

**Comment by aureliony** [comment]
Changing commit messages using rebase would cause the commit hashes on the master branch to change. Hence the script would detect the branches as "not merged into master". You would need to re-merge them.

**Comment by chonghaoen** [comment]
Understood @damithc. Thank you! @aureliony
