### ISSUE TITLE
Delete (deleting tasks using remove(index) and yet the ArrayList is not reduced and its size() not updated

### ISSUE THREAD

**Issue by jeong-jaeho** [nus-cs2103-AY2324S2/forum#152]
I've  initialized the tasks ArrayList as follows: `ArrayList<Task> tasks = new ArrayList<>();`

```
else if (input.startsWith("delete")) {
                    if (input.length() <= 7) {
                        throw new DukeException("Please state the index of the task you want to delete with correct spacing" +
                                " (e.g. delete 3)");
                    }

                    Integer indexOfTask = Integer.parseInt(input.substring(7).trim()) - 1;

                    if (indexOfTask < 0 || indexOfTask >= tasks.size()) {
                        throw new DukeException("The task index is out of range.");
                    }

                    Task removedTask = tasks.get(indexOfTask);
                    System.out.println("Noted. I've removed this task: \n" + removedTask);

                    tasks.remove(indexOfTask);
                    System.out.println("Now you have " + tasks.size() + " tasks in the list.");
                }
```

When I add in the tasks and then use the delete command, it does correctly give back the removed task, but it doesn't update the total number of remaining tasks.
![1](https://github.com/nus-cs2103-AY2324S2/forum/assets/109773933/e90bef66-3aa6-4ec4-a338-a6793a677e2b)

May I know why the remove method isn't modifying the task ArrayList?

**Comment by damithc** [comment]
@jeong-jaeho While waiting for inputs from others, you may want to use [fenced code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) to format your post for better readability.

**Comment by tankh99** [comment]
You can't use Integer. .remove() index only works with ints
