### ISSUE TITLE
Typo in JavaFX tutorial part 2

### ISSUE THREAD

**Issue by dillontkh** [nus-cs2103-AY2324S2/forum#154]
Under the [styling the controls](https://se-education.org/guides/tutorials/javaFxPart2.html#styling-the-controls) section, in the code snippet provided, the comments for both part 1 and part 2 say "Formatting the window to look as expected".

<img width="959" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/40649376/985e2453-f5ec-440e-ae69-f709c8c39fc1">

Is part 1 is supposed to be a reference to the previous section which says "Setting up required components"?

<img width="766" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/40649376/244c28ed-060e-4408-94bd-98b8d0db7d57">

**Comment by E0735389** [comment]
Good point. You may also consider reporting the bug to the correct repository https://github.com/se-edu/guides --- or better, submit a pull request.

https://github.com/se-edu/guides/blob/bd4cf431a49a99c32ae5c05b2dca5d468d19b1cb/tutorials/javaFxPart2.md?plain=1#L134

**Comment by dillontkh** [comment]
Oh my bad, didn't realize it belonged to a different repo. Thanks for letting me know!

**Comment by damithc** [comment]
@dillontkh Thanks for reporting this 💯 
Fixed.
