### ISSUE TITLE
What is our tutorial group link?

### ISSUE THREAD

**Issue by camille-readbean** [nus-cs2103-AY2324S2/forum#155]
Hi! Kinda urgent my tutorial is in 4 minutes. 

Which zoom link do my team join? 

For T17 theres Teams 1,2 and Teams 3,4 in seperate zoom links

**Comment by damithc** [comment]
@camille-readbean See https://docs.google.com/spreadsheets/d/e/2PACX-1vTrKeWKHDaIhHWEWNvPkf2FaIaWqfI23uILMcOdfysVR_IrFA2rzQy6jv4e1KupUnR59hAtStqZMId6/pubhtml?gid=2018493570&single=true to find your team number

**Comment by camille-readbean** [comment]
Thanks found it in the end!
