### ISSUE TITLE
"The hard deadline for weekly tasks is the following weekly briefing i.e., do this week's task before the next week's briefing."

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#157]
im abit confused by this. does it mean the deadline for week 3 tasks are week 4 friday?

**Comment by itstrueitstrueitsrealitsreal** [comment]
yes

**Comment by damithc** [comment]
@bgopi23 Yes. Week 3 ends at this Friday 4pm (at which point we do the Week 4 briefing, and start Week 4). So, Week 3 tasks are expected to be done by tomorrow 4pm. 
That said, there is no penalty for not finishing everything by that deadline. Missing that deaadline simply means you've fallen behind and need to catch up. The missed items will also turn red in the iP progress dashboard, but they will turn back to green if you finish them within a week of the hard deadline.
But note that the above flexibility doesn't apply to submissions to be done via Canvas (e.g., weekly quizzes) or items that appear with a specific deadline.

**Comment by baskargopinath** [comment]
thank you
