### ISSUE TITLE
Level 7: "You may hard-code the file name and relative path from the project root e.g., ./data/duke.txt"

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#158]
for this, do we manually make a folder called data? and where do we put it, inside our src folder?

**Comment by damithc** [comment]
> where do we put it, inside our src folder?

@bgopi23 it is to be created relative to the location from which you are running the application.

**Comment by baskargopinath** [comment]
so in the same folder as bin, docs, out, src etc but not inside any of them right?

**Comment by hjungwoo01** [comment]
> so in the same folder as bin, docs, out, src etc but not inside any of them right?

yes. i made it so that it is created in the ip directory. same folder as bin, docs, out, src etc.

**Comment by baskargopinath** [comment]
thank u @hjungwoo01
