### ISSUE TITLE
Execution failed for task ':runShadow'

### ISSUE THREAD

**Issue by fy17ohhh** [nus-cs2103-AY2324S2/forum#159]
Hello, after running the runShadow task, I encountered the following error with Scanner.nextLine():
<img width="1192" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/103088135/8edc4c73-8744-4a66-b4ee-1faaa53327a3">

And here is my readCommand() method:
<img width="429" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/103088135/cea0e754-b5d2-4ced-9c9d-93adf2089d11">

I tried a few times changing the code or use while(sc.hasNext()) but encountered the same error, not sure if it is the problem with build.gradle or my readCommand() method.

Thx for the help in advance!

**Comment by aureliony** [comment]
Add this to your build.gradle to get runShadow to work.
```
runShadow {
    standardInput = System.in
}
```

**Comment by fy17ohhh** [comment]
> runShadow {
>     standardInput = System.in
> }

oh thank you! i tot I have run{standardInput = System.in} and just realized its diff from runShadow {standardInput = System.in}
