### ISSUE TITLE
Issue in Level-3

### ISSUE THREAD

**Issue by radeon2525** [nus-cs2103-AY2324S2/forum#16]
I am storing the tasks in the following format:
        List<String> l = new ArrayList<String>();

However I get an error in the following line:
                l.get(element_index).markDone();

The error says that it cannot resolve method 'markDone' in String.

**Comment by UdhayaShan1** [comment]
ArrayList uses generics, you need to initialise like
```ruby
ArrayList<Task> = new ArrayList<Task>;
```
And are you putting String objects inside instead of Task object?

**Comment by radeon2525** [comment]
If I do that then I get an issue in:
         list.add(user_word);
As user_word is a String which I cannot put inside list which is Task

**Comment by UdhayaShan1** [comment]
Correct so,
```ruby
Task newTask = new Task(taskName);
arr.add(newTask);
```
You should not put it as just the string.

**Comment by radeon2525** [comment]
Okay yeah that seems to resolve the issue. Thank you for your assistance.
