### ISSUE TITLE
JavaFX learning path

### ISSUE THREAD

**Issue by UdhayaShan1** [nus-cs2103-AY2324S2/forum#163]
The JavaFX guide posted goes through the chatbot example, but I was wondering if this is all that is needed/enough for our iP and tP. Is it recommended to learn from YouTube or other sources also? 

Thanks

**Comment by damithc** [comment]
@UdhayaShan1 My impression is that the provided tutorial is enough for the iP/tP. But you are welcome to learn from other resources, and encouraged to share if you found good resources.

**Comment by UdhayaShan1** [comment]
Sure thanks!
