### ISSUE TITLE
Tagging A-JavaDoc, A-CodingStandard, Level-9

### ISSUE THREAD

**Issue by sindhurajain** [nus-cs2103-AY2324S2/forum#164]
Do we tag A-JavaDoc, A-CodingStandard, Level-9 after we have merged them into the master branch and solved the merge conflicts or on separate branches before merging?

**Comment by damithc** [comment]
@sindhurajain tag after merging (you can tag the merge commit).

**Comment by sindhurajain** [comment]
Thanks!
