### ISSUE TITLE
Query regarding A-Gradle

### ISSUE THREAD

**Issue by radeon2525** [nus-cs2103-AY2324S2/forum#165]
I have been able to successfully build my Gradle file and my chatbot is also running in that. 

However, I haven't deleted the .idea folder. Should I delete it or let it be.

**Comment by itstrueitstrueitsrealitsreal** [comment]
Follow scenario 2 as outlined [here](https://se-education.org/guides/tutorials/gradle.html).

**Comment by damithc** [comment]
> However, I haven't deleted the .idea folder. Should I delete it or let it be.

@radeon2525 You can leave it be, if everything is working as expected. Even if you delete it, Intellij recreates it upon next start (deleting is simply a way to reset IntelliJ settings)

**Comment by radeon2525** [comment]
Yes, everything is working fine. Thank you prof.
