### ISSUE TITLE
Forgot to commit branches to remote repo.

### ISSUE THREAD

**Issue by acekhoon** [nus-cs2103-AY2324S2/forum#166]
Hi everyone,

This time I have question regarding the admin side. Yesterday I completed my Week 3 iP, but when I created my javadoc, level 9, coding standard branches and merged, I forgot to push the commit I made in those branches to remote repo before the merge happens so that even though my local repo shows history that I created respective branches, it does not show up on ip dashboard as I did not push it into my github. 

In this case, should I undo all of the merges I have done so far and redo the whole thing again, or is it okay to just keep those branches indicated on my local repo? Thank you very much!

**Comment by aureliony** [comment]
I made the same mistake, after pushing the branches they showed up on the dashboard.

**Comment by damithc** [comment]
@acekhoon is right. @acekhoon you can push those branches now, and they will be detected by the dashboard at the next update.

**Comment by acekhoon** [comment]
Hello, I managed to fix by git push —all. Thanks!!
