### ISSUE TITLE
accidentally merged before committing instead of commiting the branch then merging

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#168]
i merged level 7 to master then pushed the changes, then after that i pushed the level 7 branch itself 

* my master branch and level 7 branch are up to date currently with the changes i have made

**Comment by simkianseng** [comment]
I think it has been mentioned before that they do not see your commit history if you made a mistake as long as you rectify it in the future should be fine. I guess for now you can just create a new branch and commit first before merging it.

**Comment by damithc** [comment]
> I think it has been mentioned before that they do not see your commit history if you made a mistake as long as you rectify it in the future should be fine. I guess for now you can just create a new branch and commit first before merging it.

@SimKianSeng is correct.

Also, the order in which you push doesn't matter. You can push the master first and then the branch or the other way around.

**Comment by baskargopinath** [comment]
@damithc @SimKianSeng 
> I guess for now you can just create a new branch and commit first before merging it.

but i already pushed all the changes so i just continue with level 8?

**Comment by damithc** [comment]
> but i already pushed all the changes so i just continue with level 8?

@bgopi23 Sure, that should be fine.

**Comment by baskargopinath** [comment]
thank you @SimKianSeng , and apologies for the mistake prof @damithc
