### ISSUE TITLE
Minor typo in Week 4 content

### ISSUE THREAD

**Issue by wilsonwid** [nus-cs2103-AY2324S2/forum#169]
There is a minor typo in https://nus-cs2103-ay2324s2.github.io/website/schedule/week4/project.html#2-start-a-collaborative-doc-to-take-project-notes-before-the-tutorial.

## Actual
> Make sure all you current and future project notes (if split into in multiple documents) are reachable via links given in this document and are viewable by the public.

## Expected
> Make sure all __*your*__ current and future project notes (if split into in multiple documents) are reachable via links given in this document and are viewable by the public.

**Comment by damithc** [comment]
@wilsonwid Thanks for reporting this. Fixed.
