### ISSUE TITLE
Bash script for text ui testing closing quickly

### ISSUE THREAD

**Issue by UdhayaShan1** [nus-cs2103-AY2324S2/forum#17]
Tried running the bash script for text ui testing, but the script closes quickly without being able to check. Is this normal.

[input.txt](https://github.com/nus-cs2103-AY2324S2/forum/files/13998306/input.txt)

```ruby
@ECHO OFF

REM create bin directory if it doesn't exist
if not exist ..\bin mkdir ..\bin

REM delete output from previous run
if exist ACTUAL.TXT del ACTUAL.TXT

REM compile the code into the bin folder
javac  -cp ..\src\main\java -Xlint:none -d ..\bin ..\src\main\java\*.java
IF ERRORLEVEL 1 (
    echo ********** BUILD FAILURE **********
    exit /b 1
)
REM no error here, errorlevel == 0

REM run the program, feed commands from input.txt file and redirect the output to the ACTUAL.TXT
java -classpath ..\bin RyanGosling < input.txt > ACTUAL.TXT

REM compare the output to the expected output
FC ACTUAL.TXT EXPECTED.TXT

```

[ACTUAL.TXT](https://github.com/nus-cs2103-AY2324S2/forum/files/13998304/ACTUAL.TXT)
[EXPECTED.TXT](https://github.com/nus-cs2103-AY2324S2/forum/files/13998305/EXPECTED.TXT)

**Comment by damithc** [comment]
@UdhayaShan1 While waiting for inputs from peers, perhaps you can share how exactly did you run the script? e.g., did you double-click the file?

**Comment by UdhayaShan1** [comment]
Oops i double clicked it, I managed to view the error by running it in cmd just cd into the folder and 
\Desktop\CS2103T iP\text-ui-test>runtest.bat
