### ISSUE TITLE
Minor typo in W4.3 content

### ISSUE THREAD

**Issue by Yskie** [nus-cs2103-AY2324S2/forum#170]
The typo can be found in https://nus-cs2103-ay2324s2.github.io/website/schedule/week4/topics.html#modeling-dependencies.

<img width="684" alt="Screenshot 2024-02-02 at 7 35 55 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/50563302/0325049d-8ff2-4f3e-a60b-f78350442cef">

Actual:
> class to obtain the **the** maximum...

Expected:
> class to obtain the maximum...

**Comment by damithc** [comment]
Fixed. Thanks for reporting this @Yskie
