### ISSUE TITLE
Level-8

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#172]
is the localDate feature just for deadline? or did u guys do it for event also

"Minimal: Store deadline dates as a java.time.LocalDate (or java.time.LocalDateTime) in your task objects. Accept dates in a format such as yyyy-mm-dd format (e.g., 2019-10-15) and print in a different format such as MMM dd yyyy e.g., (Oct 15 2019)."

**Comment by camille-readbean** [comment]
I interpret the minimal as just deadlines only
