### ISSUE TITLE
What is implied on associations without multiplicity?

### ISSUE THREAD

**Issue by UdhayaShan1** [nus-cs2103-AY2324S2/forum#173]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39399745/7fd12b03-a4d3-4f6a-9542-e758b3c9fc22)

In cases of associations like this, do we assume that in actual object diagrams, there must be at least a associated class present, i e multiplicity is at least one or just one?

**Comment by camille-readbean** [comment]
I just think of it as a "there exists"?

So like a multiplicity doesn't matter kinda thing?

**Comment by damithc** [comment]
Good question @UdhayaShan1 and good guess @camille-readbean 
When multiplicity is not given, it means _unknown_/_unspecified_ (i.e., there is no 'default')

**Comment by UdhayaShan1** [comment]
I see thanks!
