### ISSUE TITLE
Query regardin A-CodingStandard

### ISSUE THREAD

**Issue by radeon2525** [nus-cs2103-AY2324S2/forum#174]
Do we need to refractor our entire code base in accordance with the given coding standard or some parts of it will suffice.

**Comment by tankh99** [comment]
I think you can just reformat the entire codebase by using IntelliJ's Code Style feature after modifying the intellij's java coding standard to match the course's required standards. That's what I did at least.

**Comment by Jerome-j** [comment]
Generally I feel like IntelliJ does a good job at reformatting code by default but of course we need to eyeball it after IntelliJ does its magic

**Comment by damithc** [comment]
> Do we need to refractor our entire code base in accordance with the given coding standard or some parts of it will suffice.

@radeon2525 The entire code needs to be compliant with the coding standard.

**Comment by radeon2525** [comment]
Alright understood. Thank you
