### ISSUE TITLE
Should we still review correct quiz questions

### ISSUE THREAD

**Issue by tankh99** [nus-cs2103-AY2324S2/forum#175]
Hi, I was wondering if it's still worthwhile to review  quiz answers that we got correct?

**Comment by Jerome-j** [comment]
@tankh99 i think it is worthwhile to revisit the question that you were unsure, but got correct.

**Comment by damithc** [comment]
> Hi, I was wondering if it's still worthwhile to review quiz answers that we got correct?

@tankh99 Yes, we encourage you to review the quiz result when it is released (which is within a day after the deadline is over). I hope Canvas allows you to see both correct/incorrect answers and general feedback we've provided for past quizzes. Let us know if that is not the case.

**Comment by tankh99** [comment]
Thank you @Jerome-j  and @damithc! I believe that comments are shown only for some questions. But I think that since we can just refer to the course website, then that's no issue.

**Comment by damithc** [comment]
> But I think that since we can just refer to the course website, then that's no issue.

Argh... Canvas quiz feature is infuriatingly deficient. Perhaps you can try submitting the quiz without answering _any_ questions, and Canvas will show feedback for all questions (as all answers are wrong)?
