### ISSUE TITLE
OOP Design for Duke, Ui, Storage etc for iP

### ISSUE THREAD

**Issue by billyhoce** [nus-cs2103-AY2324S2/forum#176]
Hi, this question is related to OOP Design and I am not sure if it belongs in this course but I'll appreciate any help given.

In Week 3 iP project, there was a suggestion of the Duke, Ui, Parser and Storage class. It seemed like in the suggested implementations, instances of those classes were created. When I did it, I did not create an instance of those classes, rather I just implemented static methods that I call directly from other classes. 

My question is: In cases like this where multiple instances of a class are highly unlikely to be needed (Duke, Ui, Storage class), should we still (using Parser as an example):
1. create an instance of the class, and treat it as an object

```
public class Parser {
     public void parse(String input) {
         //Code to parse input
     }
}

// In another class:
...
Parser p = new Parser();
p.parse(string);
...
```
2. Or just treat the whole class as an object and implement it using static methods?

```
public class Parser {
     public static void parse(String input) {
         //Code to parse input
     }
}

// In another class:
...
Parser.parse(string);
...
```

Edit: Changed typo in week of iP project (Week 2 -> Week 3)

**Comment by damithc** [comment]
Good point for discussion @billyhoce 
Let's wait to see what others think

**Comment by wilsonwid** [comment]
I think both are fine, but it seems that creating an object could possibly be easier, especially if we need to implement a method in another class that takes in an object of the current class.

**Comment by tankh99** [comment]
I had the exact same implementation where I made multiple class files which implemented purely static helper functions. 

My opinion is that creating instanced classes are useful when you want to keep state specific to that class. Such as if you have a Storage class, maybe when you instance it, you pass in the path to the file so that in future, you don't have to pass in the file path again if you want to reuse the function. But for stuff like Parser, I don't see much point to not using static. That's only my opinion

**Comment by billyhoce** [comment]
> I think both are fine, but it seems that creating an object could possibly be easier, especially if we need to implement a method in another class that takes in an object of the current class.

@wilsonwid oooo good point, I can see the need in some situations. But if my other class needs to access my parser and hence take it in as a reference parameter, I can instead just do Parcer.method() and it'll work fine right?

**Comment by camille-readbean** [comment]
> I had the exact same implementation where I made multiple class files which implemented purely static helper functions.
> 
> My opinion is that creating instanced classes are useful when you want to keep state specific to that class. Such as if you have a Storage class, maybe when you instance it, you pass in the path to the file so that in future, you don't have to pass in the file path again if you want to reuse the function. But for stuff like Parser, I don't see much point to not using static. That's only my opinion

I did the same thing in my application, everything except for the Tasks is static . . .   
  
Storage could be static as well considering theres only "one" database.  
Tasklist can be static as well if theres only "one" tasklist, thats how I see things hahaha.  
Ui could be static too...  
   
For example, `System.out` is `static` (you only have one standard out)  
  
  
I didn't see the point of instantiating an instance of the class as so far I have not needed any single instance yet.  
So in my design everything is mainly done through this `static` methods.  
  
Could also be possible to use [singleton pattern](https://en.wikipedia.org/wiki/Singleton_pattern).

**Comment by c-wenlong** [comment]
From what I gathered online and from gpt, instance (non-static) implementation allows for polymorphism and dynamic binding, whereas a static implementaion does allow for that, you could implement child classes that has the same static method, but you cannot "override" the parent method, which is not as OO as an instance implementation.

For instance, if you have different types of parsers or user interfaces, using instance methods allows you to define a common interface or base class and then provide specific implementations for each variant. This way, you can easily switch between different parsers or UIs at runtime, depending on the context or configuration, without changing the underlying system architecture.

Hope this makes sense.
