### ISSUE TITLE
Minor Typo in Week 4 (4.2) Video content

### ISSUE THREAD

**Issue by ongzhili** [nus-cs2103-AY2324S2/forum#178]
For Option (a) in the in-video quiz, I believe the problem with the option should be the missing colon instead of underline since Student is already underlined
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/122247557/52b21e3e-08e1-4c61-97af-51fab6ff15e8)

### Actual
> (a)
> Incorrect.
> No Underline.
### Expected
> (a)
> Incorrect.
> No colon.

**Comment by damithc** [comment]
Thanks for reporting this, @ongzhili 
Fixed.
