### ISSUE TITLE
Typo in Canvas Quiz week 4

### ISSUE THREAD

**Issue by NeoHW** [nus-cs2103-AY2324S2/forum#179]
# [Section] Class Diagrams: Intermeidate-Level

![Screenshot 2024-02-03 at 2 48 56 PM](https://github.com/nus-cs2103-AY2324S2/forum/assets/94470439/9974bdff-fdb1-4f74-9aa2-124a18ad3761)

It should be Intermediate instead of Intermeidate

**Comment by damithc** [comment]
Fixed. Thanks @NeoHW for reporting this.
