### ISSUE TITLE
Customising the chatbot

### ISSUE THREAD

**Issue by wilsonwid** [nus-cs2103-AY2324S2/forum#18]
> You are strongly encouraged to customize the chatbot: In addition to the command/display formats, you can even customize the personality of the chatbot to make your chatbot unique.

(from [https://nus-cs2103-ay2324s2.github.io/website/schedule/week2/project.html#level-1-echo](https://nus-cs2103-ay2324s2.github.io/website/schedule/week2/project.html#level-1-echo))

Does this imply that as long as the chatbot meets the requirements for each level, we are allowed to change some of the output (e.g., changing some parts of the greeting text)?

**Comment by damithc** [comment]
> Does this imply that as long as the chatbot meets the requirements for each level, we are allowed to change some of the output (e.g., changing some parts of the greeting text)?

Yes, that's right @wilsonwid Go crazy! 😁  
That said, it should be within reason. For example, the language used in the UI should remain English so that anyone else in the class can use your chatbot.

**Comment by wilsonwid** [comment]
Thank you Prof!
