### ISSUE TITLE
JavaFX Tutorial Part 3 possible typo

### ISSUE THREAD

**Issue by UdhayaShan1** [nus-cs2103-AY2324S2/forum#183]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39399745/65fca2d4-667f-450d-935f-7c1a78cc14ad)

I don't think its Main but Duke class. This method is being called in the overridden start method of Duke.

**Comment by damithc** [comment]
Thanks for raising this, @UdhayaShan1 
Anyone else doing the JavaFX tutorials can confirm this?

**Comment by azumieflare** [comment]
I believe it should be referring to Duke class instead as it is updating the same method as specific in the earlier part of the same tutorial and the Main class is only created in part 4 of the tutorial.

**Comment by damithc** [comment]
Fiixed.
