### ISSUE TITLE
Java FX Installation Issues

### ISSUE THREAD

**Issue by xiaorui-ui** [nus-cs2103-AY2324S2/forum#184]
I faced some problems with setting up Java FX, on Intellij and Windows laptop. I started out with the [guide](https://se-education.org/guides/tutorials/javaFx.html) given in the course website, and got the following error message:
```Error: JavaFX runtime components are missing, and are required to run this application```
I naturally proceed to download java fx 17.0.10(I couldn't find 17.0.7 as specified) after modifying the dependency in build.gradle and after adding it to the project structure as per steps 1 and 2 of [this](https://javabook.bloomu.edu/setupjavafx.html#:~:text=Click%20on%20the%20File%20menu,button%20to%20complete%20the%20process.) guide, I still got the same error message. I couldn't execute step 3 since I couldn't find the VM option. I have already closed and restarted Intellij a couple of times but it still wouldn't work.

Anyone who faced a similar problem would like to share how they resolved it? Thanks!

**Comment by Jerome-j** [comment]
Hello could you share the output of `java --version`?

**Comment by itstrueitstrueitsrealitsreal** [comment]
I had this problem on a Mac too, maybe you could try changing the mainClass to Launcher, if the class of your launcher is named that.

**Comment by xiaorui-ui** [comment]
> Hello could you share the output of `java --version`?

```
java 11.0.22 2024-01-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.22+9-LTS-219)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.22+9-LTS-219, mixed mode)```

**Comment by zhonghan721** [comment]
Hi @xiaorui-ui, I am a senior from a previous batch, dropping by to help out where I can.

From this [guide](https://javabook.bloomu.edu/setupjavafx.html#:~:text=Click%20on%20the%20File%20menu,button%20to%20complete%20the%20process) that you shared, I found that you could download Java FX 17.0.7 by toggling the `Include older versions` checkbox.

Additionally, do make sure that you have selected the correct Java version within Project Structure > Project inside IntelliJ. (Although this might be more important for mac users to use the prescribe version of Java)

I hope this helps with resolving the issue. If it does not work, do update here with more information.

**Comment by lhy-hoyin** [comment]
Hi @xiaorui-ui , I am a senior from a previous batch, dropping by to see if I can help out in the forum.

Edit: Ignore the following paragraph
>~I see that in [part 1](https://se-education.org/guides/tutorials/javaFxPart1.html) of the first guide you mentioned, it uses `String javaFxVersion = '17.0.7'`. Since you are using Java 11 (as indicated by your output of `java --version`), perhaps you can try changing it to `String javaFxVersion = '11'`?
Your program may be trying to find the JavaFX runtime components for Java 17, but is unable to (assuming you did not also install Java 17 SDK on your device).~

If the issue is still not resolved, perhaps you can push the latest code to you fork (or a branch of it) and give the link here so that we can take a look at your `build.gradle`?

**Comment by damithc** [comment]
> perhaps you can try changing it to `String javaFxVersion = '11'`?

@lhy-hoyin the recommended JavaFX version is 17, as per https://se-education.org/guides/tutorials/javaFxPart1.html#setting-up-java-fx
It should work with Java 11 (AB3 uses the same combination of JavaFX 17 and Java 11)

**Comment by lhy-hoyin** [comment]
Thank you @damithc for highlighting that. 

@xiaorui-ui You mentioned that you faced `Error: JavaFX runtime components are missing, and are required to run this application` when trying the [guide](https://se-education.org/guides/tutorials/javaFx.html). Can you let is know at which part (of the 4 parts) did you first see the error?

**Comment by SPWwj** [comment]
Hi @xiaorui-ui, I am a senior from a previous batch, stopping by to offer some assistance with this issue.

- From the error `JavaFX runtime components are missing`, there could be 2 possibilities: either you did not install the dependencies, or the Java SDK you are using for the project does not support JavaFX 17.0.7.

- For installing the dependencies, your Gradle file should look something like:

  ![Gradle](https://github.com/nus-cs2103-AY2324S2/forum/assets/30100720/ed83639a-2485-40bb-a4ad-33494172907c)
  You can install the dependency by clicking the reload button where the red arrows are pointing in the screenshot.



- For checking the SDK, you can refer to this screenshot:

![SDK](https://github.com/nus-cs2103-AY2324S2/forum/assets/30100720/b9e8f811-1dbb-43a1-b2e8-a180ba132959)


After checking the above-mentioned method, if you are still facing problems, you can refer to this repository: [https://github.com/SPWwj/ip-javafx-tut](https://github.com/SPWwj/ip-javafx-tut).

**Comment by hansstanley** [comment]
Hi @xiaorui-ui, I'm a senior too. Another possible cause for the error is that the Java 11 runtime strongly requires JavaFX to be available as a module instead of a JAR when the main class (Dune) extends `javafx.application.Application` (see [this issue comment](https://github.com/javafxports/openjdk-jfx/issues/236#issuecomment-426583174)). As far as I can tell, the JavaFX SDK from gluon comes as JARs, but if you had followed the pattern in Part 1 of the [guide](https://se-education.org/guides/tutorials/javaFx.html) with Dune extending `Application` and the `Launcher` class launching Dune, the error shouldn't appear as explained in the same issue comment. Perhaps you could share your progress in the guide?

**Comment by lihaoquan** [comment]
Hello, are you running the JavaFX UI through `Launcher.java` file?
When I tried running the program from `Main.java` I get the same error.

If your IntelliJ is set up to run like the following:
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/64543157/07b39124-ee24-4329-9369-70e508dceabb)

1. On the left "Project" panel, select `Launcher.java`
2. Press the "Run" button 
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/64543157/f1f1b116-b33f-4643-bd6f-d5f434da81e1)

**Comment by xiaorui-ui** [comment]
> * either you did not install the dependencies, or the Java SDK you are using for the project does not support JavaFX 17.0.7.
> *

Turns out I didn't add the dependencies correctly. I tried adding every jar file in the lib subfolder of javafx into project structure > global libraries, then added javafx swt into the project structure > project module > dependencies. Thanks guys!
