### ISSUE TITLE
Issue regarding JavaFX setup

### ISSUE THREAD

**Issue by radeon2525** [nus-cs2103-AY2324S2/forum#185]
So I have updated my dependencies as mentioned in the course for JavaFX. However when I import javafx into the class it says "cannot resolve symbol javafx". 

Do I need to go to project structure and create a Artifact for JavaFX application?

**Comment by itstrueitstrueitsrealitsreal** [comment]
I experienced something similar, but resolved it by changing the mainClass in `build.gradle` to be Launcher, when I was attempting the first part of the tutorial. Maybe you could try that?

**Comment by radeon2525** [comment]
@itstrueitstrueitsrealitsreal by Launcher do you mean the first entry point for the program. Right now my mainClass is duke.Duke which is my main file

**Comment by radeon2525** [comment]
I am getting the following error when I try to include the JavaFX lib folder into my project, Source root 'C:\Users\aashi\Documents\ip\src\test\java' is duplicated in module 'ip.test'. Can someone help me fix this

**Comment by damithc** [comment]
> ... when I try to include the JavaFX lib folder into my project

@radeon2525 How exactly did you do that?

**Comment by radeon2525** [comment]
I was trying to follow this tutorial I found online: https://www.youtube.com/watch?v=Ope4icw6bVk

**Comment by jamessinmaojun** [comment]
Hi! I too faced this problem when I first imported javafx. For me I simply rebuilt the project and it worked fine :) You may need to do a hard reset by clearing project cache and then rebuilding.

**Comment by radeon2525** [comment]
That solved it for me as well. Thank you @jamessinmaojun
