### ISSUE TITLE
I encountered error

### ISSUE THREAD

**Issue by PateShin** [nus-cs2103-AY2324S2/forum#186]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/81001954/8c75d4d9-1a8d-498b-94c2-b744dc18f857)

I have encountered this error, but it used to work well. Furthermore, when I tried running the code in VS Code, it executed successfully.

**Comment by damithc** [comment]
@PateShin it might help to explain what action caused this i.e., what change  made it go from working to not-working? Also, which iP increment are you in now?

**Comment by fy17ohhh** [comment]
Did you also use gradle in VSCode to run? If not could you share any more screenshots? i.e. your build.gradle file or more log output

**Comment by Jerome-j** [comment]
Maybe you can consider showing us your `java --version` output?

**Comment by PateShin** [comment]
> @PateShin it might help to explain what action caused this i.e., what change made it go from working to not-working? Also, which iP increment are you in now?

It happened after setting Gradle. However, I found that the JAR file is working, so for every change, including editing, I have to package as a JAR file to test, instead of running the code directly from the file using Shift+F10. As a result, I have completed A-JavaDoc, A-CodingStandard, and Level-9.

Just to add on, if Gradle is set, am I only allowed to run the code via a JAR file?

> Did you also use gradle in VSCode to run? If not could you share any more screenshots? i.e. your build.gradle file or more log output

I just opened the same directory in VSCode to see if the problem is related to the code or IDE.

```
plugins {
    id 'java'
    id 'application'
    id 'com.github.johnrengelman.shadow' version '7.1.2'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.10.0'
    testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.10.0'
}

test {
    useJUnitPlatform()

    testLogging {
        events "passed", "skipped", "failed"

        showExceptions true
        exceptionFormat "full"
        showCauses true
        showStackTraces true
        showStandardStreams = false
    }
}

application {
    mainClass.set("duke.Duke")
}

shadowJar {
    archiveBaseName = "duke"
    archiveClassifier = null
    dependsOn("distZip", "distTar")
}

run{
    standardInput = System.in
}
```
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/81001954/6aaa0024-5149-410a-9d2a-f72269543c56)
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/81001954/89b29d26-446c-4b3d-83df-9bbbc60bd3b6)


> Maybe you can consider showing us your `java --version` output?

Is this what you asked for?
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/81001954/87731348-325a-480e-9cd1-210fc1c4c4d6)

**Comment by Jerome-j** [comment]
Hi @PateShin Patrick, it seems like the problem is with where your IntelliJ is pointing to for the default Java environment which will explain why VS Code is working fine. I think what I can recommend is point IntelliJ to the same JDK as the one in VS Code
