### ISSUE TITLE
Small grammar/typo mistake in Week 2 Topics

### ISSUE THREAD

**Issue by lihaoquan** [nus-cs2103-AY2324S2/forum#19]
Spotted a small grammar mistake in [Week 2 Topics Page](https://nus-cs2103-ay2324s2.github.io/website/schedule/week2/topics.html#w2-4-rcs-remote-repos)

**[W2.3] RCS: Revision History** => **Tools → Git and GitHub → commit: Saving changes to history** => **5. Do a few more commits.** => **Pointer 2** 

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/64543157/0894c9ba-1bd2-42d4-a27a-0e6c1a8129fb)

The highlighted text in the above image can be corrected to `other`

The following snippet is provided for locating the exact paragraph in the page via `ctrl+f `

> You can decide what to stage and what to leave unstaged. When staging changes to commit, you can leave some files unstaged, if you wish to not include them in the next commit. In fact, Git even allows some changes in a file to be staged, while others changes in the same file to be unstaged. This flexibility is particularly useful when you want to put all related changes into a commit while leaving out unrelated changes.

**Comment by damithc** [comment]
Good catch @lihaoquan 
Fixed.
