### ISSUE TITLE
A-Gradle .idea folder

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#190]
for setting up Gradle, im following scenario 2 after merging master to gradle branch.
however, i dont see any .idea file in my ip folder. does that mean i dont need to delete anything?

**Comment by damithc** [comment]
@bgopi23 Which OS are you using? Some OS'es hide folders starting with a `.` (you need to 'unhide' them first)

**Comment by baskargopinath** [comment]
@damithc u were right it was hidden. i unhid it with (shift + cmd + .). thanks prof
