### ISSUE TITLE
Citing code from se-edu

### ISSUE THREAD

**Issue by tzyian** [nus-cs2103-AY2324S2/forum#191]
Do we need to cite code from the se-edu page? Eg from the following page

https://se-education.org/guides/tutorials/javaFx.html

**Comment by damithc** [comment]
@rertyy Not strictly necessary from a course admin point of view (because those resources were created by us and given to you for reuse). But you are welcome to cite them too.

**Comment by tzyian** [comment]
Noted, thank you!
