### ISSUE TITLE
Bidirectional vs 2 Unidirectional Associations 

### ISSUE THREAD

**Issue by jyztintan** [nus-cs2103-AY2324S2/forum#192]
Hello, in this weeks topic we learnt that two unidirectional associations in opposite directions do not add up to a single bidirectional association.
"In the code below, there is a bidirectional association between the Person class and the Cat class i.e., if Person p is the owner of the Cat c, p it will result in p and c having references to each other."

```
class Person {
    Cat pet;
    //...
}

class Cat{
    Person owner;
    //...
}

```
"The code below has two unidirectional associations between the Person class and the Cat class (in opposite directions) because the breeder is not necessarily the same person keeping the cat as a pet i.e., there are two separate associations here, which rules out it being a bidirectional association."
```
class Person {
    Cat pet;
    //...
}

class Cat{
    Person breeder;
    //...
}
```

Just to confirm/clarify a few things:
- In terms of the way our code is implemented, there is no difference between the 2, ie the code is essentially identical other than the variable names. The main point of this example is just to highlight there may be a difference in how our code is **intended** on being used. The semantics of these relationships would then influence the way we should model them in a class diagram.
- Building from this example, assume that we want Cats to have both breeder and owner attributes, and a Person may be a breeder (no Breeder class) and owner. Should we use 3 different association lines between Person and Cat class to represent a owner-pet association (1 bidirectional arrow) and a breeder-animal association (2 unidirectional arrows)? 

 Thank you!

**Comment by camille-readbean** [comment]
W4.2b 

UML Class Diagrams → Associations → Roles

https://nus-cs2103-ay2324s2.github.io/website/book/modeling/modelingStructures/classDiagramsBasic/

I think it can be similar to the below where there are multiple associations

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/52031118/1ebd719b-e432-471f-930d-806d17177aef)

**Comment by damithc** [comment]
@jyztintan Good questions. Let's wait a while to see what others think ...

**Comment by dillontkh** [comment]
Hmm, I think it depends on the application requirements. If you frequently need to find the breeder of a Cat, it would make sense to have the Person stored in the Cat class.

On the other hand if all you care about is finding the Cat bred by a Person, then storing the Cat in the Person class may be more suitable.

Regarding the two unidirectional arrows, I'm unable to think of a situation where a single bidirectional arrow would not portray the same information. Did you have a scenario in mind?

**Comment by jyztintan** [comment]
Hi @dillontkh, thanks for your reply. According to Topic W4.2, "Note that two unidirectional associations in opposite directions do not add up to a single bidirectional association." 

To better describe the example given to us in the notes, a bidirectional arrow can be used to represent the owner-pet association because in the pet's owner's pet should be the same Cat, and an owner's pet's owner should be the same Person. On the other hand, we use 2 single unidirectional arrows to portray the breeder-kitten association because multiple Cats can have the same owner, while a owner can have multiple Cats. 

I think another example for 2 unidirectional arrows that do not equate to a single bidirectional arrow would be this: 
<img width="554" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/98398940/36ad5f00-b89b-4996-9e55-4db0b9984c37">
In this case, Male has a 'mother' attribute to store a Female, while Female has a 'husband' attribute to store a Male. However, they do not refer to the same instance and hence should not be one bidirectional navigability

Feel free to correct me if I have made any misconceptions.

**Comment by dillontkh** [comment]
@jyztintan Oh I see! Thanks for sharing!

**Comment by jyztintan** [comment]
Hello everyone, I came up with 2 possible representations:
1. Model the breeder-kitten association with 2 unidirectional arrows:
<img width="580" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/98398940/a2362c25-044e-4242-a222-038eda6ab0a6">

or 

2. Model the breeder-kitten association with 1 bidirectional arrows: 
<img width="828" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/98398940/211c9e03-34c0-4d20-9a9d-7b1f3c37e109">

After some offline discussion, I think that if we wanted to keep track of the animals a breeder bred, and the breeder of the Cat, we should model it in 1 bidirectional arrow, with the multiplicities at both side, if would encapsulate what we want to represent. 

Please feel free to share your thoughts on this :)

**Comment by damithc** [comment]
Sorry, it took me longer than I intended to chime in. Thanks @camille-readbean @dillontkh @jyztintan for your inputs so far. Given below are some inputs from my side:

We are only _interpreting_ diagrams at this point. We will be revisiting these topics in future weeks when we cover drawing UML diagrams. So, don't worry if you are not fully comfortable with these concepts yet. 


> * In terms of the way our code is implemented, there is no difference between the 2, ie the code is essentially identical other than the variable names. The main point of this example is just to highlight there may be a difference in how our code is **intended** on being used. The semantics of these relationships would then influence the way we should model them in a class diagram.

Yes, this observation is correct.


> In this case, Male has a 'mother' attribute to store a Female, while Female has a 'husband' attribute to store a Male. However, they do not refer to the same instance and hence should not be one bidirectional navigability

This is a good observation. If the association X is bidirectional, it must translate to a _mutual_ relationship between a pair of objects taking part in the association. For example mother-child association: if A is the mother of B, then B must be a child of A. 

The key takeaway is to know that you can't naively combine any two unidirectional associations in opposite direction into one bi-directional association. We can do that only when the two associations form a mutual relationship.

**Comment by jyztintan** [comment]
Hi Prof @damithc, sorry I missed out on your reply. Thank you for your reply, it is a really concise explanation!
