### ISSUE TITLE
A-Gradle

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#194]
./gradlew test

im only able to run the tests by using this command but it doesnt work when i click run on the method or class itself

**Comment by NeoHW** [comment]
hi, do you mind sharing the IntelliJ IDEA's logs for any error messages or warnings related to running tests?
This would let us have some insights to the problem

**Comment by baskargopinath** [comment]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/73015364/2f2ba6c5-7ff7-48ee-b3fc-d6aabfa64af0)
@NeoHW 

this happens when i click the run icon

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/73015364/01a09f52-b6b3-4f1a-92c2-f850905276ab)


but if i use ./gradlew test in the terminal it runs properly without error

**Comment by LifHoshi** [comment]
I encountered the same issue before. It could run with Intellj but not with Gradle. So what I do are:

1. Run Gradle clear, then try whether or not it could be run.
2. clear all the current projects, and classes that are shown at the top of the IntelliJ(on the left of the Run button)
3. run the main() method first, after that, if it runs successfully, then run the class.
4. Check your current project environment, whether it is default Java version 11, and Language Level is SDK default.
5. clear the data files(your load and save)
6. make sure the gradle setting is as same as website mentioned.

I am indeed not sure why this happen but these are what I do. The first time after implementing Gradle I had the same issue as you, and it happened several times later. Every time it happens, I just repeat the process. It somehow happened and somehow not. But most of the time run 3 first, and then run the whole class is successful.

**Comment by baskargopinath** [comment]
i will just run gradle from command line then thank you @LifHoshi

**Comment by damithc** [comment]
@bgopi23 see if this helps https://github.com/nus-cs2103-AY2324S2/forum/issues/146#issuecomment-1919469390

**Comment by baskargopinath** [comment]
@damithc this fixed it thanks prof
