### ISSUE TITLE
Typo in SEEDU JavaFX Chapter 4

### ISSUE THREAD

**Issue by tankh99** [nus-cs2103-AY2324S2/forum#195]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/56617918/9d61f753-1de5-458d-8ac4-22f8dc683636)

I think there's an unnecessary "the" in the highlighted text above. 

Source: https://se-education.org/guides/tutorials/javaFxPart4.html

**Comment by damithc** [comment]
@tankh99 Thanks for the bug report. Fixed.
