### ISSUE TITLE
Which branch to use to update past code?

### ISSUE THREAD

**Issue by ZhiWei1010** [nus-cs2103-AY2324S2/forum#197]
Hi, Currently I have completed up to Level 6 of the iP. I have created a new branch and started working on level 7 on this branch. However, I wish to make edits regarding past tasks like A-Enums and editing other classes created in the past levels. Do I make these changes in the level 7 branch or create a new branch to make these edits, then merge it with my current level 7 branch, then continue working on my level 7 branch?

Appreciate all help!

**Comment by damithc** [comment]
@ZhiWei1010 To keep things simple, it is fine to do other changes in level-7 branch. When you are more comfortable with branching, you can 'upgrade' to doing separate things in separate branches, which is more preferable way. For example, if the other change you want to do is not related to the work done in level-7 branch so far, you can go back to the master branch and start a new branch to do that work.

**Comment by ZhiWei1010** [comment]
Ok thanks prof! I will update the past changes in level 7 for now and in the future create a separate branch to to update other work!
