### ISSUE TITLE
I got LinkageError

### ISSUE THREAD

**Issue by PateShin** [nus-cs2103-AY2324S2/forum#198]
I have encountered <b>LinkageError occurred while loading main class duke.Duke</b>.
                                <b>Process 'command 'C:/Program Files/Java/jdk-11.0.22/bin/java.exe'' finished with non-zero exit value 1</b>

This occurred after configuring Gradle. If I set the SDK to JDK 21, which is the same version that my PC has, the code runs.

Can I please know how to fix this?

**Comment by Jerome-j** [comment]
Hello @PateShin, could you double check which version your Gradle JVM is using. Make sure it is the same JDK as your system

<img width="976" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/49815108/3567accf-4542-49e5-a475-4e7af477fa3a">
Mine is set to Gradle JVM > Project SDK zulu-11

**Comment by garylow2001** [comment]
> I have encountered LinkageError occurred while loading main class duke.Duke. Process 'command 'C:/Program Files/Java/jdk-11.0.22/bin/java.exe'' finished with non-zero exit value 1
> 
> This occurred after configuring Gradle. If I set the SDK to JDK 21, which is the same version that my PC has, the code runs.
> 
> Can I please know how to fix this?

Hi @PateShin , I am a senior from a previous batch, dropping by to help out where I can.

The version of Gradle JVM must be compatible for the JDK you are using. From this guide [here](https://se-education.org/guides/tutorials/gradle.html) it states that you should accept the defaults but do ensure that the selected version of Gradle JVM matches the JDK being used for the project.
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/97083001/7c915bdc-772d-40e4-a574-969d72643a5f)

You can refer to the guide further for a closer fix.
