### ISSUE TITLE
Minor typo in schedule page

### ISSUE THREAD

**Issue by E0735389** [nus-cs2103-AY2324S2/forum#2]
On the page https://nus-cs2103-ay2324s2.github.io/website/schedule/week4/project.html#direction there's a small typo.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/97508964/f14e7f64-031f-4a7a-859b-a10e161f3838)

**Comment by lhy-hoyin** [comment]
For more clarity, the typo in question is "Contstraints", which should be spelled as "Constraints" (without the additional "t").
Thank you @E0735389 for pointing it out :)

**Comment by damithc** [comment]
Fixed. Thanks @E0735389 and @lhy-hoyin for your help. 👍
