### ISSUE TITLE
Forgot to create a merge commit

### ISSUE THREAD

**Issue by ZhiWei1010** [nus-cs2103-AY2324S2/forum#200]
Hi, I unfortunately forgotten to create a merge commit for level 7 branch as I did not untick the fast-forward option in source tree.

What can I do to rectify this?

My current commits looks like this:

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/60460444/ccd14d57-6696-4b29-a6d9-2f1189754da3)

**Comment by damithc** [comment]
@ZhiWei1010 It's fine. When tagging, you can tag the last commit of the branch (as there is no merge commit to tag).

**Comment by ZhiWei1010** [comment]
OK, thanks prof!
