### ISSUE TITLE
JavaFX not working despite using the Azul version of JDK (M2 Mac)

### ISSUE THREAD

**Issue by belligerentbeagle** [nus-cs2103-AY2324S2/forum#204]
Hi there, thanks for coming into my thread,

Here is the error given as I try to run Launcher. 

```Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found```

I followed the tutorial given on: https://se-education.org/guides/tutorials/javaFxPart1.html 

After some googling, some recommended [using a specific version of JavaFX](https://stackoverflow.com/questions/71622429/is-it-possible-to-run-javafx-with-java-11-on-m1-mac)

But to no avail. Any clues or help out there? Anyone had faced the same issue but solved it?

Many thanks in advance!

Related screenshot if it helps:
![Screenshot 2024-02-05 at 2 14 45 PM](https://github.com/nus-cs2103-AY2324S2/forum/assets/22781279/02ff68aa-000c-4f2a-adeb-75c741fdea71)
<img width="1642" alt="Screenshot 2024-02-05 at 2 10 07 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/22781279/538360c6-aff4-4e71-a4a6-5e5fa5c6d434">
<img width="1631" alt="Screenshot 2024-02-05 at 2 09 56 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/22781279/c297942e-bd4a-4364-88b1-7a4f2e8f4016">

**Comment by yashpola** [comment]
Check if your project sdk is also correctly changed to the azul 11. I faced some issues with launching as well despite checking java --version in the terminal however the project sdk needed to be changed

**Comment by lhy-hoyin** [comment]
Hello @belligerentbeagle, can I just double check if you downloaded/installed JavaFX manually, or did you let Gradle do it for you?

**Comment by anthonytamzil** [comment]
Hi @belligerentbeagle, I am a senior from the previous batch dropping in to help!

If I read your issue correctly, you downloaded and installed the Azul build of OpenJDK 11 version found [here](https://www.azul.com/downloads/?version=java-11-lts&os=macos&architecture=arm-64-bit&package=jdk-fx#zulu). 

Since you installed another version of OpenJDK, it is hardly recommended that you remove other versions of OpenJDK so that you do not accidentally use the wrong version.

Also, it is pointed out on the CS2103T website to make sure that you set the `JAVA_HOME/JDK_HOME` system variables to point to `/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home`.

I also second @yashpola in double-checking your project SDK to make sure that it is aligned with whatever you are planning to use.

Do let us know how it goes!

**Comment by belligerentbeagle** [comment]
https://github.com/nus-cs2103-AY2324S2/forum/issues/204#issuecomment-1927216156

> Check if your project sdk is also correctly changed to the azul 11. I faced some issues with launching as well despite checking java --version in the terminal however the project sdk needed to be changed

This did it for me, thank you Yash! <3

Some additional information of how it was solved:
Check under File > Project Structure > SDKs wasn't enough. 

After clicking run, I needed to make sure that the Run Configurations also had Azul 11 selected.
<img width="1710" alt="Screenshot 2024-02-06 at 11 09 35 AM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/22781279/0ab1a0b9-5038-4475-9eea-5355ec9206bd">

<img width="1710" alt="Screenshot 2024-02-06 at 11 09 30 AM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/22781279/812b190d-410d-4b7e-8971-384efc955a3b">

Now, I face a next-step issue, which I will open in another thread - Program perpetually stuck/waiting for user input and not opening a GUI.
<img width="1632" alt="Screenshot 2024-02-06 at 11 06 58 AM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/22781279/af235060-d61a-49e8-bf89-29872418475a">

**Comment by joenus** [comment]
I'm adding to this thread as I encountered some issues on my end as well.

For those using Intellij to manage JDK versions. Please ensure to download the x86 version of Azul and not the aarch64 version. For some reason, the arm version doesn't seem to play nice with JavaFX for me.
![Screenshot 2024-02-10 at 5 42 53 PM](https://github.com/nus-cs2103-AY2324S2/forum/assets/157573575/99dba800-42d6-4a74-a9f3-9264690c2c11)
