### ISSUE TITLE
[Typo] Possible Typo in Week 4 Project Step 3

### ISSUE THREAD

**Issue by camille-readbean** [nus-cs2103-AY2324S2/forum#205]
Potential source of ambiguity or typo.    

In <Week 4.Project Step 3> it links to https://nus-cs2103-ay2324s2.github.io/website/se-book-adapted/chapters/codeQuality.html  

> Comment on other code quality guidelines (see the section Naming in [this textbook chapter](https://nus-cs2103-ay2324s2.github.io/website/se-book-adapted/chapters/codeQuality.html)) you have learned so far. It's optional to comment on coding standard violations in this PR review.  
  
Theres no exact "Naming" section in that linked code quality page other than "Guideline: Name well" [https://nus-cs2103-ay2324s2.github.io/website/se-book-adapted/chapters/codeQuality.html#guideline-name-well](https://nus-cs2103-ay2324s2.github.io/website/se-book-adapted/chapters/codeQuality.html#guideline-name-well)  
  
I think there might be a _possible_ typo. Where the specific section should be changed or the link be changed to the direct link.  
  
I say this because in code _standard_ there _is_ a **Naming** section: https://se-education.org/guides/conventions/java/intermediate.html#naming

**Comment by damithc** [comment]
Fixed. Thanks @camille-readbean for raising this.
