### ISSUE TITLE
Which version of Scene Builder do we download?

### ISSUE THREAD

**Issue by appleraincoat** [nus-cs2103-AY2324S2/forum#206]
Hi, may I clarify on which version of Scene Builder we are supposed to download, or does it not matter too much? Only 2 versions are available, one for Java 17 and up and 1 for Java 8. Thank you!
<img width="902" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/122220024/10c6f606-502c-4ad4-82bc-75e49ca5325c">

**Comment by itstrueitstrueitsrealitsreal** [comment]
Personally, I downloaded the version for Java 17 (because I didn't really look at the compatibility haha), and it still worked fine for me. Maybe others who have downloaded the older version of Scene Builder can weigh in?

**Comment by darkv32** [comment]
Adding on to the above, I didn't use Scene Builder, but it looks like version 17.0.0 is targeted for Java 11 and above, so you use the older version to be safe.

**Comment by ys112** [comment]
I used the scene builder 21.0.0 and it worked fine for me on windows.

**Comment by kokerinks** [comment]
> I used the scene builder 21.0.0 and it worked fine for me on windows.

Same here, using SceneBuilder 21.0.0 on Windows 10, had no issues whatsoever

**Comment by NeoHW** [comment]
I used SceneBuilder 8.5.0 with no issues

**Comment by appleraincoat** [comment]
@itstrueitstrueitsrealitsreal @darkvoid32 @ys112 @kokerinks @NeoHW thank you all for your input and help! :)
