### ISSUE TITLE
How to make dialog box fit input

### ISSUE THREAD

**Issue by sethteo** [nus-cs2103-AY2324S2/forum#208]
![Screenshot 2024-02-05 at 9 29 37 PM](https://github.com/nus-cs2103-AY2324S2/forum/assets/119569146/a5e72cbd-ccd3-48ea-b7f4-a737711d4efc)

Hi does anyone know how to make the dialog box grow according to size of the input as currently anything above 4 lines will get shortened to "..."

**Comment by UdhayaShan1** [comment]
Credits to ChatGPT, helped me with this problem earlier
Code is in `DialogBox` class

```ruby
this.setMinHeight(calculateMinHeight(text));
...

private double calculateMinHeight(String text) {
    // Set a base height and adjust based on the length of the text
    double baseHeight = 50.0;
    double textLengthFactor = 0.5; // Adjust this factor as needed
    return baseHeight + text.length() * textLengthFactor;
}
```

**Comment by tayruxin** [comment]
Hi @sethteo, I'm from your senior batch, I have taken a look at your repo perhaps you can try to remove prefHeight from your "MainWindow.fxml" in this line `<VBox fx:id="dialogContainer" prefHeight="552.0" prefWidth="388.0" />` this way, the height of your dialog box can be adjusted dynamically. 

Please give it a try if the same issue persists feel try to comment.

**Comment by sethteo** [comment]
> <VBox fx:id="dialogContainer" prefHeight="552.0" prefWidth="388.0" />

omg this works thank you so much @tayruxin !!

**Comment by UdhayaShan1** [comment]
> Hi @sethteo, I'm from your senior batch, I have taken a look at your repo perhaps you can try to remove prefHeight from your "MainWindow.fxml" in this line `<VBox fx:id="dialogContainer" prefHeight="552.0" prefWidth="388.0" />` this way, the height of your dialog box can be adjusted dynamically.
> 
> Please give it a try if the same issue persists feel try to comment.

Thanks alot!

**Comment by itstrueitstrueitsrealitsreal** [comment]
Thanks for the solution @tayruxin, but now I have a separate issue...
<img width="390" alt="Screenshot 2024-02-06 at 2 34 55 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/120318851/e9c02905-518c-438b-8e79-8eefd17ec011">
The background colour only expands to the latest message, so it looks really ugly when I first start it up.

Is there any workaround for this?

**Comment by damithc** [comment]
> The background colour only expands to the latest message, so it looks really ugly when I first start it up.
> 
> Is there any workaround for this?

@itstrueitstrueitsrealitsreal as this is a separate issue, it's best posted as a new thread.
