### ISSUE TITLE
Accidentally approving PR Review

### ISSUE THREAD

**Issue by yleeyilin** [nus-cs2103-AY2324S2/forum#209]
<img width="610" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/116061001/defa8fd2-4ffe-44df-83d0-a01c9635ff1d">

Hi, I accidentally approved a review as I did not see the last point of step 1 which is to choose only comment. Is there another way to rectify this mistake? The only way I could find was the mark the comment as outdated. Any help will be appreciated!

**Comment by damithc** [comment]
@yleeyilin It's fine, no harm done.

**Comment by yleeyilin** [comment]
@damithc Okay, thanks!
