### ISSUE TITLE
Minor typo in w2.3e

### ISSUE THREAD

**Issue by yespiggy** [nus-cs2103-AY2324S2/forum#21]
**Location:** 
[w2.3e] https://nus-cs2103-ay2324s2.github.io/website/schedule/week2/topics.html
<img width="671" alt="Screenshot 2024-01-21 at 11 01 38 AM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/108997339/3d9c5053-39a4-4067-8587-f4fa2b1cc10f">

**Expected:**
tell git

**Comment by damithc** [comment]
Thanks for the heads up, @yespiggy 
Fixed
