### ISSUE TITLE
How to check if I have add-gradle-support

### ISSUE THREAD

**Issue by DominicFuMJ** [nus-cs2103-AY2324S2/forum#211]
I'm not sure how to check if I have add-gradle-support. Can someone help me? I tried to do the instructions from the image below, ![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/119829202/4e7349bf-1935-4223-8a0f-1bdcc67888bc)
but when I tried to pull, I got this error message.
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/119829202/6f9ce5ab-f6c3-406b-b9f9-adc806f69950)
I tried to pull from upstream.
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/119829202/16d4df8f-8b02-4670-a11f-5e1d5c36fd1c)

**Comment by damithc** [comment]
@DominicFuMJ As per https://github.com/DominicFuMJ/ip/branches you already have the add-gradle-support branch in your own fork (i.e., `origin`)
You can find it in your Sourcetree in the following way.
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/2e461bcf-3b4b-494c-ac11-b813bb44b55e)

To pull it to your local repo, follow [these instructions](https://nus-cs2103-ay2324s2.github.io/website/se-book-adapted/chapters/gitAndGithub.html#:~:text=%5BB%5D%20Pulling%20a%20remote%20branch%20for%20the%20first%20time).
(screenshot below is for cross reference)
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/827be783-070e-4c95-8f5b-4852e53a33fb)

**Comment by itstrueitstrueitsrealitsreal** [comment]
If you're not a SourceTree guy, you could also list all the branches using your CLI by running `git branch -a` to list all tags.

**Comment by YuvBindal** [comment]
Hey! These following steps helped me add gradle to my master branch using CLI:
1. git merge --no-ff add-gradle-support (merge the gradle branch to your main)
2. run ./gradlew build (if you see build successful you have implemented gradle)
3. run ./gradlew run

if you see errors then you might have to modify the path to your main class in gradle.build. Hope this helps!

Good luck

**Comment by DominicFuMJ** [comment]
Added the branch using instructions from https://nus-cs2103-ay2324s2.github.io/website/se-book-adapted/chapters/gitAndGithub.html#:~:text=%5BB%5D%20Pulling%20a%20remote%20branch%20for%20the%20first%20time.
