### ISSUE TITLE
Error in running Launcher.java

### ISSUE THREAD

**Issue by radeon2525** [nus-cs2103-AY2324S2/forum#212]
I am getting java.lang.ClassNotFoundException: MainWindow when I run my program, even though I am loading the MainWindow.fxml from my start() in Main.java: 

    @Override
    public void start(Stage stage) {
        try {
            FXMLLoader fxmlLoader = new FXMLLoader(Main.class.getResource("/view/MainWindow.fxml"));
            AnchorPane ap = fxmlLoader.load();
            Scene scene = new Scene(ap);
            stage.setScene(scene);
            fxmlLoader.<MainWindow>getController().setDuke(duke);
            stage.show();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

**Comment by yashpola** [comment]
Do you also have the MainWindow.java class? That is the required controller for MainWindow.fxml I believe

**Comment by tohlh** [comment]
A possible reason is not referring to the `MainWindow.java` class correctly from the `MainWindow.fxml` file.

`MainWindow.fxml`
```xml
<AnchorPane ... fx:controller="duke.ui.MainWindow">
...
</AnchorPane>
```

**Comment by itstrueitstrueitsrealitsreal** [comment]
@tohlh agreed on that, one of my peers also experienced the same issue on his project.

**Comment by radeon2525** [comment]
@tohlh Yes this fixed my bug as well, thank you for your help!
