### ISSUE TITLE
Checkstyle naming for constants

### ISSUE THREAD

**Issue by gavin331** [nus-cs2103-AY2324S2/forum#213]
From what I know, a variable is considered as a constant if it has the 'final' keyword associated with it and we should name constant variables with uppercases and underscores. However, I have a variable declared as private final ... STORAGE but it gives a checkstyle error stating that STORAGE shouldn't have more than 2 consecutive capital letters.  This error is removed only when i changed it to private static final ... STORAGE.  Is this intended?

**Comment by dillontkh** [comment]
Without the `static` keyword, you can have multiple instances of the class, each having their own `STORAGE`. This could result in there being multiple different `STORAGE`s.

When you tag it as `final`, that means the `STORAGE` is a constant only within an instance of a class. So you can't change it throughout the lifetime of that object.

However when you declare something with the `static final` keywords, that means it is a constant that exists even without an instance of the class being created.

e.g.
If you have a `Math.PI` that has only been declared as `final` (no `static`), you could potentially have the following scenario

```java
Math Math1 = new Math(3.14);
Math Math2 = new Math(3.15);
Math Math3 = new Math(3);

Math1.PI = 3.14
Math2.PI = 3.15
Math3.PI = 3
```

But if you declare it with `static final`, you will be able to ensure that `Math.PI` always refers to the same value. You also would not need to instantiate the class to refer to that value.

**Comment by gavin331** [comment]
Ok thanks!
