### ISSUE TITLE
How to Undo Merge & Commit?

### ISSUE THREAD

**Issue by ZhiWei1010** [nus-cs2103-AY2324S2/forum#214]
Hi I think I messed up the steps of merging add-gradle branch to my master.
I tried to undo the merge and commit but am quite confused as to what is going on.

What I did:
1. Checkout new branch "add-gradle-support".
2. Merge my Master branch to "add-gradle-support" branch. [I should have merged the other way round right?]

My source tree looks like this now:
<img width="1680" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/60460444/450781f9-aac2-40a2-9e54-cc03773267f8">

I'm not sure why there is 16 for the pull and 1 for push [add-gradle-support] branch.
When I tried to pull this error shows up.
<img width="636" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/60460444/53c36f80-2976-4202-89ba-08b695bbf6b9">

and when I try to push, this message shows up.
<img width="863" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/60460444/23b9ff65-ae34-4429-9156-9f9417a8a5cc">

Now I'm not sure how to fix this!! Appreciate any help I can get!!

**Comment by damithc** [comment]
@ZhiWei1010 merging master to the gradle branch was not intended, but it is not a deal breaker. It simply updates your gradle branch with the latest code in the master branch. Not needed but not a problem either.

You can now checkout the master branch and and merge the gradle branch to it, as was originally intended.

**Comment by ZhiWei1010** [comment]
I checked out the master branch and tried to merge it to the master branch but now my gradle branch is currently the latest commit and I'm unable to do that. I also could not merge the master branch to the current gradle again!

<img width="1680" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/60460444/e6865c4d-d7c9-4f22-b143-b60ab6db17c7">

**Comment by damithc** [comment]
Try the following:

Open the Git-bash terminal (2nd icon from top-right) 
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/f2931680-2509-4ead-93c1-11600087b921)

Run the following commands:
```
git checkout master
git merge --no-ff add-gradle-support
```
What's the output?

**Comment by ZhiWei1010** [comment]
Output: 
<img width="715" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/60460444/4f80be9e-8760-457e-a489-f6aabd2d4c93">

It seems like I have managed to merge with these commands!

Final source tree history:
<img width="1680" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/60460444/7e3887fc-f043-4fe9-a1dc-3a03f0700f13">

May I check that the branch is merged correctly and that I can continue?

**Comment by damithc** [comment]
Everything seems to be fine, @ZhiWei1010 
You can continue.

**Comment by ZhiWei1010** [comment]
Ok thanks for the help prof!
