### ISSUE TITLE
Query regarding DialogBox styling for Level-10

### ISSUE THREAD

**Issue by itstrueitstrueitsrealitsreal** [nus-cs2103-AY2324S2/forum#217]
After following the pointer @tayruxin gave in #208 regarding making the DialogBox stretch to fill the text, I encountered a new issue: 
<img width="387" alt="Screenshot 2024-02-06 at 8 27 27 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/120318851/63ff9a12-5c05-4ef5-b9e0-fe0a7cd3f0c0">

My current chatbot looks like this...
The background colour only expands to the latest message, so it looks really ugly when I first start it up.

Is there any workaround for this?

**Comment by Jerome-j** [comment]
Hi, not sure if you removed the image - but I am unable to see the image that you have posted. Could someone else please confirm?

**Comment by itstrueitstrueitsrealitsreal** [comment]
Oh I realised the picture doesn't show up on mobile. Edited the original post!

**Comment by dillontkh** [comment]
Perhaps you could set the color of the `AnchorPane`/`ScrollPane` to match the color of your `DialogBox`?

**Comment by itstrueitstrueitsrealitsreal** [comment]
@dillontkh It didn't seem to work... I changed it in the fxml file, that's probably why.

**Comment by dillontkh** [comment]
I ran your bot and it looks like this.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/40649376/cd261a5a-bf9a-4f0f-8f30-3fff71d933b7)

Whatever you did it seemed to have worked, good job!

**Comment by itstrueitstrueitsrealitsreal** [comment]
Glad to see you're enjoying my product 😁😁
But if you add enough items to the list, it'll start to get truncated...

Which is what I solved by removing the prefHeight section (not pushed), but it results in my screenshot being replicated.

Thanks for going through the effort to try it out on your machine!

**Comment by tayruxin** [comment]
Hi @itstrueitstrueitsrealitsreal your senior here again, I downloaded and tried it out on my end and I believe this is your intended outcome? 

<img width="405" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/106758300/df99aade-e73b-4368-b922-7ca2c56c9d04">

Perhaps you can try to set the background in `MainWindow.java` Hope this solves your issue 

```
    @FXML
    public void initialize() {
        scrollPane.vvalueProperty().bind(dialogContainer.heightProperty());
        dialogContainer.getChildren().add(DialogBox.getNarutoDialog("Hello! I'm Naruto, and I'm "
                        + "training to become a ninja!\nBelieve it!", narutoImage));
        scrollPane.setStyle("-fx-background: #C0C0C0;");
    }

```

**Comment by itstrueitstrueitsrealitsreal** [comment]
@tayruxin it worked!!! Closing this issue.
<img width="391" alt="Screenshot 2024-02-07 at 12 52 53 AM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/120318851/7c08c20f-bad0-4954-bb3c-4b933b403f5f">
