### ISSUE TITLE
Backwards compatibility

### ISSUE THREAD

**Issue by wilsonwid** [nus-cs2103-AY2324S2/forum#22]
Are we supposed to make our code backwards compatible? As an example, do we assume that at `Level-4`, all tasks are strictly in either one of the three categories, or do we still allow for a generic task to be created?

**Comment by UdhayaShan1** [comment]
Bit confused on this too, if it's incremement in level 5 we handle unknown commands but in level 2 it includes adding all types of commands by user

**Comment by damithc** [comment]
@UdhayaShan1 @wilsonwid It's fine for a later increment to change the behavior added in a previous increment, if needed.

**Comment by wilsonwid** [comment]
Thank you for the clarification, Prof!
