### ISSUE TITLE
Intellij keeps crashing after installing azul

### ISSUE THREAD

**Issue by RunjiaChen** [nus-cs2103-AY2324S2/forum#222]
Right after I installed azul, I can no longer open my ip, intellij keeps crashing. Is there any way to resolve this? How do I set the JAVA_HOME/JDK_HOME for mac? 

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/142142406/d6aadc72-35e4-4691-84a2-404b3d400b77)

For some reason I can't even create a new project now. I tried to select the sdk, even though it's there, it doesnt allow me to.

When I open the project, I just get this: (I cannot click on any of the icons to change the settings)

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/142142406/bd9212c3-44fb-4a9b-a4ac-8d5fd44ee187)

**Comment by NeoHW** [comment]
1) You could try reinstalling Inteliij for a start
2) to set `JAVA_HOME` for mac: open terminal and enter `vim ~/.zshrc` or `vim ~/.bash_profile`, depending on if you're using zsh or bash. Then, add in the follow line: `export JAVA_HOME=\$(/usr/libexec/java_home)`.
Restart your shell and you should be set

**Comment by damithc** [comment]
@RunjiaChen Still not resolved?

**Comment by RunjiaChen** [comment]
Sorry, managed to resolve it by doing a clean uninstall of intellij and reinstalling it
