### ISSUE TITLE
relative path

### ISSUE THREAD

**Issue by Darkarche3** [nus-cs2103-AY2324S2/forum#224]
private static final String FILE = "./data/duke.txt";

This is my relative path but I am getting this error: Error saving tasks to file: .\data\duke.txt (The system cannot find the path specified)

It was not working then working for a while and its not working again. I don't understand what is happening?

**Comment by Darkarche3** [comment]
the issue seems to be the IDE im using. It works on VScode but not Intellij.

**Comment by damithc** [comment]
@Darkarche3 Can you share the full code used for reading/writing files? Or confirm the latest code is in your fork so that others can have a look?

**Comment by yisiox** [comment]
@Darkarche3 The error sounds similar to #134 , if not maybe you can provide the OS, code snippet and error message.

**Comment by Darkarche3** [comment]
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.io.File;

public class Data {

    private static ArrayList<String> taskList = new ArrayList<String>();
    private static final String FILE = "./data/duke.txt";

    public static ArrayList<String> getTasks() {
        return taskList;
    }

    public static void setTasks() {
        taskList = Duke.instructions;
    }

    static void loadTasks() {
        Path path = Paths.get(FILE);
        if (Files.exists(path)) {
            try {
                List<String> lines = Files.readAllLines(path);
                for (String line : lines) {
                    String[] sentence = line.split(" ", 2);
                    
                    if(sentence.length == 1 ){
                        DukeException error = new DukeException(line);
                        System.out.println(error.toString());
                    }else{
                        String command = sentence[0];
                        if(command.equals("todo") || command.equals("deadline") || command.equals("event")){
                            Duke.addTask(line);
                        }else if(command.equals("mark")||command.equals("unmark")||command.equals("delete")){
                            Duke.modifyTask(line);
                        }else{
                            // any instruction that is not clear that has not been covered
                            DukeException error = new DukeException(line);
                            System.out.println(error.toString());
                        }
                    }
                }
            } catch (IOException e) {
                System.out.println("Error loading tasks from file: " + e.getMessage());
            }
        }
        
    }

    public static void saveTasks() {
        try {
            FileWriter writer = new FileWriter(FILE);
            for (String instruction : taskList) {
                writer.write(instruction + "\n");
            }
            writer.close();
        } catch (IOException e) {
            System.out.println("Error saving tasks to file: " + e.getMessage());
        }
    }
}

The code is above. The part where I am facing the error is when I run the saveTasks method. I am using Windows. This is the error when I run it on IntelliJ: Error saving tasks to file: .\data\duke.txt (The system cannot find the path specified) 

My code works perfectly when I run it on VS code.

**Comment by damithc** [comment]
@Darkarche3 Try this: change the file location as `private static final String FILE = "./storage/duke.txt";` and see if it still works in VSCode.

**Comment by Darkarche3** [comment]
It does not work on VScode anymore.

**Comment by damithc** [comment]
> It does not work on VScode anymore.

Right. so, it is not something to do with the IDE, but something to do with the way you handle the folder in which the file is supposed to be.

**Comment by c-wenlong** [comment]
Are you running the code in the correct location? Like within the terminal window, if you run the command on the CLI,
```
open ./data/duke.txt
```
It should open the file.

**Comment by ZhiWei1010** [comment]
Hi I think you can try following this guide, where you first get the home directory then append it to the front using the Paths.get method so the it can be used across different systems before adding the relevant file path.

I think currently home directory is not where u expect it to be so have to get it using the

```java
String home = System.getProperty("user.home");
```
method


https://www.sghill.net/2014/how-do-i-make-cross-platform-file-paths-in-java/


```java
String home = System.getProperty("user.home");

// inserts correct file path separator on *nix and Windows
// works on *nix
// works on Windows
java.nio.file.Path path = java.nio.file.Paths.get(home, "my", "app", "dir")
boolean directoryExists = java.nio.file.Files.exists(path);
```

**Comment by smolegz** [comment]
I've cloned your project, and it seems to work fine (no errors thrown on IntelliJ) when I repeatedly run and exit the program. If you have another terminal, maybe try running the same code on that terminal to test if that error is still thrown?

**Comment by Darkarche3** [comment]
Thank you for the help everyone. I still haven't managed to fix it but based on your comments, its clear that it has something to do with how I am handling the folder. I will update again if I have made any progress.

**Comment by Darkarche3** [comment]
Hi everyone, I managed to get it to work. Thanks for your help!!
