### ISSUE TITLE
GUI output shortening

### ISSUE THREAD

**Issue by yashma-sonara** [nus-cs2103-AY2324S2/forum#225]
Hi, does anyone have the issue with their gui, where if first command is LIST which outputs 10 tasks. The future commands take up space in the gui making the previous list display shortening? I added screenshots of the 2 cases I mentioned. Will appreciate if someone knows how I could fix this. Thanks.
<img width="286" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/44407952/ad942a28-1c4a-4764-901e-978ec8c2bb8a">
<img width="257" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/44407952/0b5954fb-768f-4185-956e-6fd57a231ee3">

**Comment by aureliony** [comment]
Here are two possible solutions:
1. In DialogBox.java, add the line:
`dialog.setMinSize(Label.USE_PREF_SIZE, Label.USE_PREF_SIZE);`

2. In DialogBox.fxml, modify the line to:
`<Label fx:id="dialog" text="Label" wrapText="true" minHeight="-Infinity">`

**Comment by yashma-sonara** [comment]
Thanks @aureliony. <Label fx:id="dialog" text="Label" wrapText="true" minHeight="-Infinity"> seems to work for me.
