### ISSUE TITLE
Git commit check

### ISSUE THREAD

**Issue by Ko-Khan** [nus-cs2103-AY2324S2/forum#226]
How can we check if our latest commits are up to standard?

**Comment by camille-readbean** [comment]
Check here

https://nus-cs2103-ay2324s2.github.io/dashboards/contents/ip-progress.html

find your ID, expand details and under iP admin tasks > look for the git standard box

**Comment by Ko-Khan** [comment]
So it is impossible to check them individually? Can only see if the last 5 are correct?

**Comment by camille-readbean** [comment]
I am not currently aware of a way to check each commit individually :(

**Comment by Ko-Khan** [comment]
Thanks for the clarification!
