### ISSUE TITLE
Request to use JSON in Java [package org.json] library for ip

### ISSUE THREAD

**Issue by RyanNgWH** [nus-cs2103-AY2324S2/forum#227]
## Library

[JSON in Java](https://github.com/stleary/JSON-java?tab=readme-ov-file)

## Purpose

To help in storing the data to disk in JSON format

## License

[Listed](https://github.com/stleary/JSON-java/blob/master/LICENSE) as `Public Domain`.

**Comment by damithc** [comment]
@RyanNgWH Approved. 
FYI, the tP uses Jackson for JSON handling https://github.com/FasterXML/jackson

**Comment by RyanNgWH** [comment]
@damithc oh alright will check it out. Thank you!

**Comment by wilsonwid** [comment]
> @RyanNgWH Approved. FYI, the tP uses Jackson for JSON handling https://github.com/FasterXML/jackson

Does this mean that we are also allowed to use Jackson for the tP? @damithc

**Comment by damithc** [comment]
> Does this mean that we are also allowed to use Jackson for the tP? @damithc

Yes.
