### ISSUE TITLE
Query in listing down multiple tasks

### ISSUE THREAD

**Issue by radeon2525** [nus-cs2103-AY2324S2/forum#228]
In the case where I have like 10 or 15 tasks, my GUI only shows the first 5 tasks and then does "..." for the rest. So how can I list all of my tasks irrespective of their number

**Comment by UdhayaShan1** [comment]
#208

**Comment by c-wenlong** [comment]
If #208 didn't work, follow the JavaFx tutorial, there is this line of code that makes the size of the dialoguebox dynamic, meaning its size changes with the size of the content.
```
dialogContainer.setPrefHeight(Region.USE_COMPUTED_SIZE);
```
You can find the instruction under part 2 of the JavaFx tutorial under the section - Styling the Controls.

**Comment by damithc** [comment]
This seems related https://github.com/nus-cs2103-AY2324S2/forum/issues/225#issuecomment-1931383635

**Comment by yorklim** [comment]
I also faced the same issue but i used a scrollpane instead which keeps the responses constant size as well

**Comment by radeon2525** [comment]
Alright I was able to fix this issue. Thank you everyone for your help!
