### ISSUE TITLE
How to practice javaFX

### ISSUE THREAD

**Issue by Ko-Khan** [nus-cs2103-AY2324S2/forum#229]
Could I ask how to practice javaFX outside of our current project? Can we fork the duke directory a second time?

**Comment by damithc** [comment]
@Ko-Khan GitHub doesn't allow you to fork the same repo multiple times but you can certainly clone our duke repo (or your fork of it) to a new location in your computer and use that to practice JavaFX (or anything else).

**Comment by Ko-Khan** [comment]
Thanks for the clarification! I cloned a version of my current project to attempt the javaFX tutorial.
