### ISSUE TITLE
Minor typo in course website

### ISSUE THREAD

**Issue by sindhurajain** [nus-cs2103-AY2324S2/forum#23]
https://nus-cs2103-ay2324s2.github.io/website/schedule/week2/index.html

In the Week 2 [Fri, Jan 19th] - Summary page (link above), there is a minor typo. "plus it's help us" should be "plus it helps us".
<img width="799" alt="Screenshot 2024-01-21 at 12 58 07 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/115209308/b372fb8f-fd4b-4c04-9685-f8cbc9989681">

**Comment by damithc** [comment]
Good catch, @sindhurajain 
Fixed
