### ISSUE TITLE
copying code from javaFX tutorials

### ISSUE THREAD

**Issue by Ko-Khan** [nus-cs2103-AY2324S2/forum#230]
Can I just copy code for classes such as MainWindow or DialogBox straight from the tutorials? Or do I need to come up with them from scratch?

**Comment by damithc** [comment]
Yes, you can reuse them @Ko-Khan. [more info ...](https://nus-cs2103-ay2324s2.github.io/website/admin/appendixB-policies.html#:~:text=Giving%20credit%20for%20reusing%20from%20course%20materials)

**Comment by Ko-Khan** [comment]
Thank you!
