### ISSUE TITLE
JUnit testing Unable to import class from main folder for test folder

### ISSUE THREAD

**Issue by DominicFuMJ** [nus-cs2103-AY2324S2/forum#232]
I'm trying to import the TaskList class from the tasklist folder to use in the DeadlineTest, EventTest and TodoTest. I keep getting an error as I think it's trying to get it from the test folder instead of the main folder. 
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/119829202/e844cdbd-2c94-407f-9193-20f49d90353a)

**Comment by damithc** [comment]
@DominicFuMJ What's the error?

**Comment by DominicFuMJ** [comment]
It kept saying that it is unable to find the file victor.tasklist.TaskList. It eventually fixed itself when I ran ./gradlew clean build and ./gradlew clean test in the terminal.
