### ISSUE TITLE
Why is new line in Label truncated?

### ISSUE THREAD

**Issue by fy17ohhh** [nus-cs2103-AY2324S2/forum#233]
Hi, previously I met the issue similar to #208, and managed to solve the issue by removing the `prefHeight`
However, since for my list response, I have a new line at the end, and now my bot is still showing the three dots, not at the end in the same line but starting in a new line
<img width="254" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/103088135/f2a8a33a-73d7-4448-ab2a-6d90c89ddcb6">
I also tried adding a new line char at the end of my welcome message, and there are the three dots again
Here is the comparison between no new line and having a new line at the end of the string
<img width="402" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/103088135/4bb2f67c-0f2e-4449-8151-908b029a60c3">

<img width="413" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/103088135/609c3bdb-2164-49fd-9154-5f50bb9b6bfa">

Any one knows why this happen? How could I solve this issue?

**Comment by itstrueitstrueitsrealitsreal** [comment]
Can refer to #208 for more info.

**Comment by fy17ohhh** [comment]
> Can refer to #208 for more info.

hi, I've alr removed the `prefHeight`, the issue seems a bit different from #208 now

**Comment by damithc** [comment]
@fy17ohhh is this code already in your fork, in case someone wants to replicate/diagnose the problem using your code?

**Comment by dillontkh** [comment]
@fy17ohhh maybe you could try the advice given here? https://github.com/nus-cs2103-AY2324S2/forum/issues/225#issuecomment-1931383635

**Comment by fy17ohhh** [comment]
> @fy17ohhh is this code already in your fork, in case someone wants to replicate/diagnose the problem using your code?

Hi prof, thx for the reminder, I just pushed the branch-Level-10 to my fork

**Comment by fy17ohhh** [comment]
> @fy17ohhh maybe you could try the advice given here? [#225 (comment)](https://github.com/nus-cs2103-AY2324S2/forum/issues/225#issuecomment-1931383635)

I've tried both approaches but neither worked, thx anyways

**Comment by itstrueitstrueitsrealitsreal** [comment]
> > Can refer to #208 for more info.
> 
> hi, I've alr removed the `prefHeight`, the issue seems a bit different from #208 now

My bad, didn't realise you already tried #208.

I tried pulling your code and running your project, and it looks pretty nice on my end. Nice work!

I refactored some of your code in ListCommand::execute(), and I think I fixed the problem (not for the case where a specific date is indicated though.)

I believe this is your desired output:
<img width="484" alt="Screenshot 2024-02-08 at 3 56 30 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/120318851/7d1ae663-c719-480d-a207-edeb624f46e1">
 
I refactored the section of your code which handled the case where no date was specified, by only appending a newline character if it was not the last task in the task list, which solved the problem.

Here's the relevant code snippet:
```java
//...
            } else if (i != tasks.size()) {
                sb.append(String.format("\t%d. %s\n", i, tasks.get(i - 1)));
                count++;
            } else {
                sb.append(String.format("\t%d. %s", i, tasks.get(i - 1)));
                count++;
            }
//...
```
As for why the \n character causes the three dots to appear at the bottom, I'm not really sure, but removing the newline character at the end of the message seems to be a quick fix.
Hope I helped!

**Comment by fy17ohhh** [comment]
> > > Can refer to #208 for more info.
> > 
> > 
> > hi, I've alr removed the `prefHeight`, the issue seems a bit different from #208 now
> 
> My bad, didn't realise you already tried #208.
> 
> I tried pulling your code and running your project, and it looks pretty nice on my end. Nice work!
> 
> I refactored some of your code in ListCommand::execute(), and I think I fixed the problem (not for the case where a specific date is indicated though.)
> 
> I believe this is your desired output: <img alt="Screenshot 2024-02-08 at 3 56 30 PM" width="484" src="https://private-user-images.githubusercontent.com/120318851/303253206-7d1ae663-c719-480d-a207-edeb624f46e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczNzk3NjEsIm5iZiI6MTcwNzM3OTQ2MSwicGF0aCI6Ii8xMjAzMTg4NTEvMzAzMjUzMjA2LTdkMWFlNjYzLWM3MTktNDgwZC1hMjA3LWVkZWI2MjRmNDZlMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOFQwODA0MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDIyMDY0ZTg3YjRiMTgxYjk0NThmODViMmFkMmRmZmI4ZDM2ODc1OTZhZDM0YzljMTcwNzM0OGJmZmE1OGY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NhXjZAHQf2W1p7qQ3_rJ8riFMuXHAnz3zd5dSevKPyI">
> 
> I refactored the section of your code which handled the case where no date was specified, by only appending a newline character if it was not the last task in the task list, which solved the problem.
> 
> Here's the relevant code snippet:
> 
> ```java
> //...
>             } else if (i != tasks.size()) {
>                 sb.append(String.format("\t%d. %s\n", i, tasks.get(i - 1)));
>                 count++;
>             } else {
>                 sb.append(String.format("\t%d. %s", i, tasks.get(i - 1)));
>                 count++;
>             }
> //...
> ```
> 
> As for why the \n character causes the three dots to appear at the bottom, I'm not really sure, but removing the newline character at the end of the message seems to be a quick fix. Hope I helped!

Hi, this fixes the problem perfectly! Thank you! :)

**Comment by lhy-hoyin** [comment]
> Hi prof, thx for the reminder, I just pushed the branch-Level-10 to my fork

If your issue is still unresolved, can you provide the fork's link here (for convenience)?

Additionally, it would be helpful to provide steps to replicate the issue, (the actual output), and also the desired output.

**Comment by fy17ohhh** [comment]
> itstrueitstrueitsrealitsreal

Hi, please see @itstrueitstrueitsrealitsreal's response for the solution and actual/desired output.

**Comment by fy17ohhh** [comment]
> > Hi prof, thx for the reminder, I just pushed the branch-Level-10 to my fork
> 
> If your issue is still unresolved, can you provide the fork's link here (for convenience)?
> 
> Additionally, it would be helpful to provide steps to replicate the issue, (the actual output), and also the desired output.

Hi, the issue was just resolved, please see @itstrueitstrueitsrealitsreal's response for the solution and actual/desired output.
