### ISSUE TITLE
Attribute arrows in UML diagrams

### ISSUE THREAD

**Issue by chengjunyuan** [nus-cs2103-AY2324S2/forum#234]
Why is `Board` written as "played on" `SquareGame` from the [Week 4 Topics](https://nus-cs2103-ay2324s2.github.io/website/schedule/week4/topics.html#W4-2b) example below?

<img width="669" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/122239268/d117cd4b-b731-4cb2-87f9-2b680878fe22">

According to the website,

> Association labels describe the meaning of the association. The arrow head indicates the direction in which the label is to be read.

In the example, the `SquareGame` should be played on a `Board`, yet the arrow in the association diagram is pointing the other way round, implying that a `Board` is played on a `SquareGame`. May I know if this was a typo or is there a mistake in my understanding of the example?

**Comment by damithc** [comment]
@chengjunyuan Good catch. The triangle should be in the other direction. i.e., `SquareGame` played on `Board`.
Will fix soon.

**Comment by damithc** [comment]
Fixed.
