### ISSUE TITLE
Import statement groupings for JavaFX and local packages

### ISSUE THREAD

**Issue by Javiery3889** [nus-cs2103-AY2324S2/forum#235]
I would like to clarify must import statements for JavaFX and local packages be separated? For example,
```java
import blu.ui.MainWindow;
import blu.ui.UI;
import blu.utils.BluLogger;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
```
Currently, `checkstyles.xml`is flagging out the newline as an "extra separation in import group", specifically between JavaFX and local packages. Editing the code as shown below will remove the error,
```java
import blu.ui.MainWindow;
import blu.ui.UI;
import blu.utils.BluLogger;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
```
I would like to ask which is correct? Thanks!

**Comment by camille-readbean** [comment]
**I think** the below is correct.  
  
I think it was said that if the Course's Java coding standard did not specify (https://se-education.org/guides/conventions/java/#package-and-import-statements), we fall back to Google's Java coding standard.   
The course's standard only mention ordering without reference to line breaks.    

https://google.github.io/styleguide/javaguide.html#s3.3.3-import-ordering-and-spacing

> Imports are ordered as follows:
>
>    All static imports in a single block.
>    All non-static imports in a single block.

**Comment by Javiery3889** [comment]
@camille-readbean Thanks for the pasting the necessary links, I missed out on Google's Java coding standard. I will be closing this issue. 👍
