### ISSUE TITLE
Question about citing the code

### ISSUE THREAD

**Issue by acekhoon** [nus-cs2103-AY2324S2/forum#236]
Hello!

I know it would be a somewhat trivial question, but for level 10 I referred to javaFX tutorial and modified the given template code for my level 10 code. I remember how to cite the code I used and referred to for my iP but somehow I cannot find how to cite the code from website. Could anyone help me out to figure out how to cite the code / webpage link to the info about citing the code?

Thanks!

**Comment by damithc** [comment]
@acekhoon There is no need. More info [here](https://nus-cs2103-ay2324s2.github.io/website/admin/appendixB-policies.html#:~:text=Giving%20credit%20for%20reusing%20from%20course%20materials)

**Comment by acekhoon** [comment]
Thank you very much prof!!
