### ISSUE TITLE
Query regarding ip grading

### ISSUE THREAD

**Issue by Morninggloryyy** [nus-cs2103-AY2324S2/forum#238]
Hi, I didn't submit deliverables in week 2 & 3 so falling below the bar of Project Management (Submitted some deliverables in at least 4 out of the 5 iP weeks (i.e., week 2 - week 6)). May I know if my total iP score will be limited to less than half the marks (7.5 marks) or only the score for this bar  will be limited to less than half the marks (1 mark), and if there are any remedies for it? Thank you!!

**Comment by damithc** [comment]
@Morninggloryyy iP is a formative assessment. So, we make allowances for those who start slow but catch up by the end. What you described will not cause you to fall below half-marks if you do better in the remainder of the iP and finish well.

**Comment by Morninggloryyy** [comment]
Thank you so much for your clarification!
