### ISSUE TITLE
Add an extension for the week 5 iP

### ISSUE THREAD

**Issue by kaiyi27** [nus-cs2103-AY2324S2/forum#239]
I just want to clarify whether this task requires us to add one extension from each category B, C, and D (total of 3 extensions) or to add one extension from category B or C or D (total of 1 extension).

**Comment by damithc** [comment]
@kaiyi27 Just one extension in total, not one from each category

**Comment by kaiyi27** [comment]
> @kaiyi27 Just one extension in total, not one from each category

Ok, thanks prof.
