### ISSUE TITLE
Citing the Java documentation

### ISSUE THREAD

**Issue by wilsonwid** [nus-cs2103-AY2324S2/forum#24]
Is citing the Java documentation (if we refer to it) something necessary to be done, or is the citation policy applicable only to resources aside from the documentation?

**Comment by damithc** [comment]
@wilsonwid Which Java documentation (do you mean documentation provided from Oracle)? And citing for what kind of situation (perhaps give an example)?

**Comment by wilsonwid** [comment]
Hi Prof, the Java documentation I was referring to is the documentation provided by Oracle. I was intending to clarify whether it is necessary to cite when we use the documentation to clarify doubts (e.g., looking up method arguments and return types).

**Comment by damithc** [comment]
> Hi Prof, the Java documentation I was referring to is the documentation provided by Oracle. I was intending to clarify whether it is necessary to cite when we use the documentation to clarify doubts (e.g., looking up method arguments and return types).

@wilsonwid It's not necessary to cite Java SDK API documentation, unless you think that information could be useful to a future developer reading the code.

**Comment by wilsonwid** [comment]
Thank you Prof!
