### ISSUE TITLE
participation points subject to soft deadline?

### ISSUE THREAD

**Issue by Darkarche3** [nus-cs2103-AY2324S2/forum#240]
Hi, may I check if the participation points is subject to the soft deadline?

For example, if I did the peer review due this week next week instead, would I still get the participation points?

Thank you for your help!

**Comment by damithc** [comment]
@Darkarche3 soft deadline doesn't make a difference when giving participation points to the iP PR review activity. But note that the hard deadline for that is 4pm today (i.e., weekly briefing time), after which it will be considered 'late'.
