### ISSUE TITLE
Error: JavaFX runtime components are missing, and are required to run this application

### ISSUE THREAD

**Issue by TarinPairor** [nus-cs2103-AY2324S2/forum#241]
After I download javafx-sdk-17.0.10 and add the `build.gradle` dependencies:
```
 String javaFxVersion = '17.0.7'

    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'linux'
```
and at this to VM options: 
`--module-path /Users/tarin/Downloads/javafx-sdk-17.0.10/lib/ --add-modules javafx.controls,javafx.fxml`
after I downloaded the sdk and it is currently in my Downloads fold. Why does it still throw the error.

```
> Task :run FAILED
Error: JavaFX runtime components are missing, and are required to run this application

FAILURE: Build failed with an exception.
```

**Comment by damithc** [comment]
@TarinPairor Which OS?

**Comment by TarinPairor** [comment]
macOS

**Comment by damithc** [comment]
@TarinPairor Which part of the instructions got you to download the JavaFX sdk?

**Comment by TarinPairor** [comment]
None, 
they never explained how to get it running on your program. When I did as they instructed ie added the dependencies in the `build.gradle` file, it originally had the same error message when I did `./gradlew run` ie `Error: JavaFX runtime components are missing, and are required to run this application` or when manually ran the ip main file:
```
package duke;

import java.io.IOException;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.stage.Stage;
import parser.Parser;
import processor.Processor;
import tasks.TaskList;
import ui.Ui;

/**
 * The Duke class is responsible for running the chatbot.
 */
public class Duke extends Application {
    private final Ui chatbotUi;
    private final TaskList taskList;
    private final Processor processor;
    private final Parser parser;

    /**
     * Constructs a Duke object with the specified Ui, TaskList, Processor, and Parser.
     */
    public Duke() {
        chatbotUi = new Ui();
        taskList = new TaskList();
        processor = new Processor(taskList, chatbotUi);
        parser = new Parser(processor);
    }

    /**
     * Executes the chatbot.
     * @throws IOException if an I/O error occurs while running the chatbot
     */
    public void run() throws IOException {
        // Greet User
        System.out.print(chatbotUi.greetingBox());

        String userInput;
        do {
            userInput = chatbotUi.getCommand();
            if (userInput.equals("bye")) {
                break;
            } else {
            parser.processCommand(userInput);

            }

        } while (true);

        System.out.println(chatbotUi.dividerWrapper(Ui.bye()));
    }



    /**
     * Starts the chatbot.
     * @param stage the stage to be used for the chatbot
     * @throws IOException if an I/O error occurs while starting the chatbot
     * @see Application#start(Stage)
     */
     @Override
    public void start(Stage stage) {
        Label helloWorld = new Label("Hello World!"); // Creating a new Label control
        Scene scene = new Scene(helloWorld); // Setting the scene to be our Label

        stage.setScene(scene); // Setting the stage to show our screen
        stage.show(); // Render the stage.
    }

    public static void main(String[] args) throws IOException {
        // Duke d = new Duke();
        // d.run();
        Application.launch(Duke.class, args);
    }

}
```

**Comment by TarinPairor** [comment]
So I had to figure out how to fix the error. When I looked into it further, I found someone's solution was to add the MV options but so far it hasn't worked.

**Comment by aureliony** [comment]
You need to have a separate Launcher.java class as stated in the tutorial. Running main() directly from Duke.java won't work.

**Comment by sindhurajain** [comment]
Try putting the start method in another class Main.java and Application.launch(Main.class, args); in another class Launcher.java. Also, once you do this, keep Main.class as the first argument of Application.launch(Main.class, args);, don't change in to Duke.class

**Comment by shawnnlimm** [comment]
@TarinPairor I’m on Windows and had something similar to you before. I did not download any new SDK etc. After adding the dependencies stated in Part 1 of the tutorial to the `build.gradle` file, I closed my IDE (IntelliJ), ran `gradlew clean build` from the terminal (or `./gradlew clean build` in your case), and restarted IntelliJ. This was what worked for me.

**Comment by damithc** [comment]
> @TarinPairor I’m on Windows and had something similar to you before. I did not download any new SDK etc. After adding the dependencies stated in Part 1 of the tutorial to the `build.gradle` file, I closed my IDE (IntelliJ), ran `gradlew clean build` from the terminal (or `./gradlew clean build` in your case), and restarted IntelliJ. This was what worked for me.

@shawnnlimm thanks for this pointer. I guess it's easy to forget about the need to load the dependencies after updating the build.gradle file. Just now I added a note about it in [here](https://se-education.org/guides/tutorials/javaFxPart1.html#:~:text=After%20updating%20the%20build.gradle%20file)

**Comment by TarinPairor** [comment]
No it still doesn't work for me.
I run `./gradlew clean build` (after restarting) and it works:
```
BUILD SUCCESSFUL in 3s
12 actionable tasks: 12 executed
```
but then when I run `./gradlew run` it says the same thing that `JavaFX runtime components are missing, and are required to run this application`. I also made a new Launcher.java file:
```

import duke.Duke;
import javafx.application.Application;

/**
 * A launcher class to workaround classpath issues.
 */
public class Launcher {
    public static void main(String[] args) {
        Application.launch(Duke.class, args);
    }
}

```

ran from Duke:

```
package duke;

import java.io.IOException;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.stage.Stage;
import parser.Parser;
import processor.Processor;
import tasks.TaskList;
import ui.Ui;

/**
 * The Duke class is responsible for running the chatbot.
 */
public class Duke extends Application{
    private final Ui chatbotUi;
    private final TaskList taskList;
    private final Processor processor;
    private final Parser parser;

    /**
     * Constructs a Duke object with the specified Ui, TaskList, Processor, and Parser.
     */
    public Duke() {
        chatbotUi = new Ui();
        taskList = new TaskList();
        processor = new Processor(taskList, chatbotUi);
        parser = new Parser(processor);
    }

    /**
     * Executes the chatbot.
     * @throws IOException if an I/O error occurs while running the chatbot
     */
    public void run() throws IOException {
        // Greet User
        System.out.print(chatbotUi.greetingBox());

        String userInput;
        do {
            userInput = chatbotUi.getCommand();
            if (userInput.equals("bye")) {
                break;
            } else {
            parser.processCommand(userInput);

            }

        } while (true);

        System.out.println(chatbotUi.dividerWrapper(Ui.bye()));
    }

    /**
     * Starts the chatbot.
     * @param stage the stage to be used for the chatbot
     * @throws IOException if an I/O error occurs while starting the chatbot
     * @see Application#start(Stage)
     */
    @Override
    public void start(Stage stage) {
        Label helloWorld = new Label("Hello World!"); // Creating a new Label control
        Scene scene = new Scene(helloWorld); // Setting the scene to be our Label

        stage.setScene(scene); // Setting the stage to show our screen
        stage.show(); // Render the stage.
    }





    public static void main(String[] args) throws IOException {
         Duke d = new Duke();
         d.run();
    }

}

```

**Comment by drustanyjt** [comment]
@TarinPairor I had a similar issue when using a '`public static void main`' method of a class that directly extends from '`Application`'.

What worked for me was creating another file '`Main.java`' and class '`Main`', and moving the entry point code (the '`main`' method) there.

**Comment by Pughal77** [comment]
@TarinPairor I also had a similar issue but it was resolved when I set my mainClass in my `build.gradle` to the right class path.

**Comment by camille-readbean** [comment]
> No it still doesn't work for me. I run `./gradlew clean build` (after restarting) and it works:
> 
> ```
> BUILD SUCCESSFUL in 3s
> 12 actionable tasks: 12 executed
> ```
> 
> but then when I run `./gradlew run` it says the same thing that `JavaFX runtime components are missing, and are required to run this application`. I also made a new Launcher.java file:
> 
> ```
> 
> import duke.Duke;
> import javafx.application.Application;
> 
> /**
>  * A launcher class to workaround classpath issues.
>  */
> public class Launcher {
>     public static void main(String[] args) {
>         Application.launch(Duke.class, args);
>     }
> }
> ```


Your gradle.build should point at Launcher instead of Duke, that solved the issue for me!

```
application {
    mainClass.set("Launcher")
}
```

**Comment by xinen26** [comment]
To add on to the above comment, if you want to run the program just to check if its working, you should run Launcher.java and not Duke.java. 
I was stuck on it for some time and kept getting the same error as you until I run Launcher class instead of Duke and it finally worked as per the JavaFX tutorial! :)

**Comment by damithc** [comment]
@TarinPairor is this issue resovled?

**Comment by TarinPairor** [comment]
Yes ok, I figured out the problem: I was using the wrong JDK. Although it was the correct version, I was supposed to download and use Azul Zulu 11 but my default version originally only had Java 11.
