### ISSUE TITLE
How should input not in the given date-time format be handled for Level 8?

### ISSUE THREAD

**Issue by kjw142857** [nus-cs2103-AY2324S2/forum#242]
When my friend and I were testing each other's iP implementations, I noticed a discrepancy in the way we handle our deadline tasks (implemented in Level 8). Normally, if a deadline is entered in a certain date format (e.g. yyyy-mm-dd), the chatbot is supposed to identify and convert the format. But what about deadlines which are not of this format (e.g. "tomorrow")? There are 2 possible approaches:

1. Accept the deadline as valid, and simply print out what the user has written in (e.g. [D][] submit CS2103T quiz (by: tomorrow))
2. Reject the deadline as invalid, and throw an exception (i.e. the chatbot informs the user that they _must_ enter a date)

Which of these situations would be accepted as valid in the context of this course?

**Comment by timothysashimi** [comment]
I believe it should be the second point. Leaving it as tomorrow would be very subjective, what if the user forgets when he keyed in the task, unless your parser would parse words like tomorrow or next week and convert them into respective dates.

If we have to implement a reminder function based on the task date in the future, then the second implementation would help more.

**Comment by sindhurajain** [comment]
I think it's better to go with option 2 so that you can meet Level 8's requirements of using LocalDate or LocalDateTime to store dates. I did a similar thing as well - I only accepted dates of a certain format and an invalid format or empty description  would throw an exception. 

Even if you go with option 1 and accept strings like "tomorrow" or "next week" then parse them into LocalDate or LocalDateTime), I think it would be too many variations of strings to parse.

**Comment by tituschewxj** [comment]
I think both approaches are valid, and the better approach would depend on what kind of product and target user you have in mind, as there are tradeoffs between each approach.

For example, if your target user is someone that prefers typing text fast over checking their calendar and inputting a date in the correct format, the first approach may be better, as it allows the user to quickly add tasks.

On the other hand, if your target user prefers the control and functionality over having actual dates, then the second approach may be better.

**Comment by kjw142857** [comment]
Thanks everyone for your input!
