### ISSUE TITLE
Gradle error - Zip end header not found

### ISSUE THREAD

**Issue by justincred** [nus-cs2103-AY2324S2/forum#244]
Gradle could run the week before but for some reason this week, it cannot run and I realised it was running on java 17 instead, so i removed and reinstalled java 11 and now the gradle java version is also 11 but it is still not able to run, giving the zip end header error 
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/95204474/e459c13b-033f-4983-a491-86909c984f30)
Attached below is my gradle version as well 
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/95204474/895046c7-5db0-4851-87bf-3d6f08ed10c7)

**Comment by UdhayaShan1** [comment]
A wild guess but after you changed the versions there is a corrupted cache. Try removing this corrupted cache and update if works

https://stackoverflow.com/questions/52411697/intellij-compilation-error-zip-end-header-not-found

**Comment by justincred** [comment]
hi, thanks for the reply, I have tried that before but didnt work and instead did `Remove-Item -Recurse -Force .gradle, gradle, build
` which reset the gradle files and worked
