### ISSUE TITLE
Peer Evaluation 

### ISSUE THREAD

**Issue by chewbum** [nus-cs2103-AY2324S2/forum#246]
Hi! Would like to ask if anyone has done the peer evaluation on Teammates. Can't seem to access any peer evaluation, other than the TP form we were supposed to submit.

**Comment by sindhurajain** [comment]
For the week 5 task prelim peer evaluation on Teammates due on Thursday, Feb 15th, we should be getting the Teammates link by Monday noon, as per the course website: https://nus-cs2103-ay2324s2.github.io/website/schedule/week5/admin.html

**Comment by damithc** [comment]
Thanks @sindhurajain 
@chewbum the TEAMMATES peer feedback session will open on Monday.

**Comment by chewbum** [comment]
@sindhurajain ok thank you!
