### ISSUE TITLE
Week 5 Topics Content Possible Mistake

### ISSUE THREAD

**Issue by lihaoquan** [nus-cs2103-AY2324S2/forum#249]
The following content may contain editing mistakes:

### **User Stories**

> W5.3c 
> Requirements → Specifying Requirements → User Stories → Introduction

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/64543157/3037b051-e85e-4023-94cd-c80deb3d130c)

The answers have checkboxes besides them. I'm not sure if this is intended as in the past, all answers were shown as plain text wihtout interactivity.

**Comment by damithc** [comment]
Thanks for mentioning this @lihaoquan 
I've changed them to be non-editable
