### ISSUE TITLE
[Set-up] Setting up of system variables

### ISSUE THREAD

**Issue by cheahTJ** [nus-cs2103-AY2324S2/forum#25]
Hi all, may I check with regards to this instruction "Set the JAVA_HOME/JDK_HOME system variables to point to /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home", is it to configure the system variable in my bashrc file if I am a mac user? If not, where shall I include this system variable?

**Comment by damithc** [comment]
@cheahTJ Let's wait a bit to see if other Mac users can pitch in with their inputs...

**Comment by 0liverkong** [comment]
you can just do JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home on Terminal, if you want to be permanent you can open your .zshrc file and write 
`export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home`
save it then type `source .zshrc` on terminal and it should be set that way each time you open terminal. (can check by typing echo $JAVA_HOME)

**Comment by cheahTJ** [comment]
@0liverkong Alright thank you! I'll give it a try.
