### ISSUE TITLE
Minor typo in guidance section for W5.6

### ISSUE THREAD

**Issue by itstrueitstrueitsrealitsreal** [nus-cs2103-AY2324S2/forum#250]
In the green box above W5.6's content, there is a small typo.

It states that: 

>They are shown here in case you haven't learned them before you would like to refresh your memory.

I think that it should be:
>They are shown here in case you haven't learned them before **if** you would like to refresh your memory.

Thanks!

**Comment by damithc** [comment]
Fixed. Thanks for reporting this @itstrueitstrueitsrealitsreal
