### ISSUE TITLE
How to clear level 10?

### ISSUE THREAD

**Issue by cheahTJ** [nus-cs2103-AY2324S2/forum#253]
Hi, I have already implemented the GUI as per branch-10 but it is still red under my IP progress for Level-10, may I know how else can I do to clear this portion?

Context:
I have a functional GUI but I have not really edited other UI aspects of the GUI yet (e.g. my text box may be too small for my text etc), could this be a reason?

**Comment by Jerome-j** [comment]
Hello! I dont think the minimal function is the problem cos it is "self declared progress".

I dont see your tag at https://github.com/cheahTJ/ip/releases/tag/Level-10

Did you forget to push your tag?

```git
git tag Level-10
git push origin Level-10
```

**Comment by cheahTJ** [comment]
Ohhh alright thank you!! @Jerome-j
