### ISSUE TITLE
Level-10 - GUI

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#254]
Which class should we implement the GUI in? The tutorial shows it being done in the Duke class but doesn't it make more sense to do it in Ui?

**Comment by Jerome-j** [comment]
I decided to use 2 main methods. One for the GUI and one for the Commandline.

This way I can still use the auto text redirection in the CI-CD workflow

**Comment by baskargopinath** [comment]
so u didnt alter ui? @Jerome-j

**Comment by DhiraPT** [comment]
For me, I created a new `gui` package consisting of `Main`, `MainWindow` and `DialogBox` classes. `Main` class extends `Application` and instantiates the `Duke` class. The entry point is the `main` method in the `Launcher` class which will then launch the `Main` class. Additionally, I converted `Ui` class into `Response` class, thus eliminating input from the command line entirely.

Here is my file structure:
```
.
├── gui
│   ├── Main.java
│   ├── MainWindow.java
│   ├── DialogBox.java
├── response
│   ├── Response.java
├── Duke.java
├── Launcher.java
```

**Comment by wxiaoyun** [comment]
perhaps you can consider having a view package that takes care of the gui. The structure that DhiraPT is very reasonable and I agree with his implementation.

**Comment by baskargopinath** [comment]
thanks everyone

**Comment by guanquann** [comment]
For me, I created a class Gui, which extends Ui class, and then override all the existing methods (things that have the print function) in Ui
