### ISSUE TITLE
How to add greetings for GUI

### ISSUE THREAD

**Issue by vnnamng** [nus-cs2103-AY2324S2/forum#255]
### Problem
If I follow JavaFX Tutorial, my GUI will only be able to response to the UserInput, but it cannot show the initial greeting when the app is open like in CLI UI.
### Attempted Solution
Changing initialized() method in MainWindow class allow me to add a customized dialog box at the beginning:
``` java
@FXML
    public void initialize() {
        scrollPane.vvalueProperty().bind(dialogContainer.heightProperty());
        dialogContainer.getChildren().add(
                DialogBox.getDukeDialog("Welcome", dukeImage)
        );
    }
```
**However**, it will not work if i want to trigger a method from duke such as `duke.greeting()` instead of the static String.

### Question
How to print out initial greeting for JavaFX GUI?

**Comment by DhiraPT** [comment]
You can add the `showInitialGreeting()` method in the `MainWindow` class and then retrieve the controller inside the `start` method in the `Main` class.

**Comment by damithc** [comment]
@vnnamng Is this issue resolved?

**Comment by vnnamng** [comment]
> @vnnamng Is this issue resolved?

Thank you, I got it.
