### ISSUE TITLE
What should we add to .gitignore?

### ISSUE THREAD

**Issue by PallonCX** [nus-cs2103-AY2324S2/forum#256]
From one of the topics about Git, we learnt that we can add files that we don't want Git to track in .gitignore. However, as far as I'm concerned, this course does not explicitly tell us what files should we add to .gitignore (e.g. the test functions, the storage file for tasks).

May I get some general guidances and advices about this issue?

**Comment by kawaijoe** [comment]
Generally, the following:

- Build files (eg jar file)
- IDE generated files (eg .idea/)
- Environment files especially if secrets are stored (eg .env)
- Dependencies
- OS generated files (eg .DS_Store on Mac)
- Code generated files (debatable)

**Comment by joenus** [comment]
Generally, the following:

- Build files (eg jar file)
- IDE generated files (eg .idea/)
- Environment files especially if secrets are stored (eg .env)
- Dependencies
- OS generated files (eg .DS_Store on Mac)
- Code generated files (debatable)

**Comment by camille-readbean** [comment]
To expand on @joenus 

These files varies from one developer or user to the Mac. E.g. different operating system, one use visual studio code another uses InteliJ.

Binaries, because they can vary

**Comment by yadunut** [comment]
A good tool to generate a template `gitignore` file (since there are common files for different projects) is [gitignore.io](https://www.toptal.com/developers/gitignore/).

**Comment by tanyunchao** [comment]
Building on @yadunut,

personally I'll always just google for the gitignore files for whichever framework the project is based on and it has usually worked fine.

**Comment by AdityaB4** [comment]
While the other comments have covered what you asked directly, I think [this guide](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository) is useful if you accidentally track (and push) sensitive data!

**Comment by PallonCX** [comment]
Thanks all for helping!
