### ISSUE TITLE
Do we still need CLI after implementing GUI?

### ISSUE THREAD

**Issue by 4llysa** [nus-cs2103-AY2324S2/forum#257]
Hi all, after implementing the GUI, are we supposed to ensure that the CLI still works at the same time as the GUI?

I suppose it is not too hard for the both GUI and CLI to work simultaneously, so the user has the choice of either – but is this necessary in the iP?

**Comment by damithc** [comment]
@4llysa you are welcome to, but it's not required. More info [here](https://nus-cs2103-ay2324s2.github.io/website/schedule/week4/project.html#:~:text=Note%20that%20you%20no%20longer%20need%20to%20keep%20the%20text%2Dbased%20UI%20after%20adding%20a%20GUI)
