### ISSUE TITLE
Getting java.lang.reflect.InvocationTargetException during runtime when giving incorrect input

### ISSUE THREAD

**Issue by larainezo** [nus-cs2103-AY2324S2/forum#258]
When giving an incorrect input, instead of returning the message after catching exceptions, I keep getting the InvocationTargetException. 
I realised that the error arises when I input "todo" without a task description, but my incorrect input is caught when I input a longer string like "todoooo" (also without a task description).

Could this have something to do with a short input string?

Below if my getResponse(String input) method.

`@FXML
    private void handleUserInput() {
        String input = userInput.getText();
        String response = duchess.getResponse(input);
        dialogContainer.getChildren().addAll(
                DialogBox.getUserDialog(input, userImage),
                DialogBox.getDuchessDialog(response, duchessImage)
        );
        userInput.clear();
    }`

**Comment by damithc** [comment]
@larainezo You may want to use [fenced code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) to format your post for better readability.

Also, push your latest code to your fork (or a branch in there) and share the link here so that others can try to reproduce the problem.

**Comment by larainezo** [comment]
@damithc Thanks prof for the feedback!

I have pushed my latest code to the Level-10 Branch [https://github.com/larainezo/ip/tree/Level-10](url).

The InvocationTargetException error seems to come from the `getResponse()` method in **MainWindow.java**
```java
@FXML private void handleUserInput() { 
    String input = userInput.getText(); 
    String response = duchess.getResponse(input); 
    dialogContainer.getChildren().addAll( DialogBox.getUserDialog(input, userImage), 
                                          DialogBox.getDuchessDialog(response, duchessImage) ); 
    userInput.clear(); 
}
```

**Comment by larainezo** [comment]
Bug fixed. Error was due to incorrect ordering of if-else statements to parse user input. Changes have been committed.

**Comment by yisiox** [comment]
Commenting here in case anyone encountered the same issue and found this thread. The invocation error is a wrapper around the actual error. There is a `getCause` method as explained [here](https://www.baeldung.com/java-lang-reflect-invocationtargetexception) to show the full error to help debug.
