### ISSUE TITLE
Minor Typo in W2-Project Tab, Duke Level-0

### ISSUE THREAD

**Issue by itstrueitstrueitsrealitsreal** [nus-cs2103-AY2324S2/forum#26]
There seems to be a minor [typo](https://nus-cs2103-ay2324s2.github.io/website/schedule/week2/project.html) at part (b) of Level-0, where it states:
>"Implement an initial skeletal version of the it that simply greets the user and exits."

It should instead be:

>"Implement an initial skeletal version of ~~the~~ it that simply greets the user and exits."

Attached is a screenshot of the typo.

<img width="792" alt="Screenshot 2024-01-21 at 7 15 33 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/120318851/9672a943-3d80-49a2-bb95-a808db49201b">

Thanks for taking the time to rectify it!

**Comment by damithc** [comment]
@itstrueitstrueitsrealitsreal thanks for the heads up. 
Fixed.
