### ISSUE TITLE
Query regarding CodeQuality

### ISSUE THREAD

**Issue by radeon2525** [nus-cs2103-AY2324S2/forum#260]
I have refactored all of my methods to be under 30 lines of code, however only one, which is:
 public void start(Stage stage)

is left in my Duke.java which is crossing the threshold. I have adapted it's implementation from the 2103/T website. Can I let this be or do I need to figure out on splitting it in multiple methods.

**Comment by damithc** [comment]
@radeon2525 we don't have a strict rule that method must be shorter than 30 lines. So, it is fine to keep a method longer than 30 lines if the costs of shortening it further outweigh the benefits.

**Comment by damithc** [comment]
@radeon2525 To add, I can see why the below textbook section made you think you need to make all methods to be shorter than 30 lines.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/93d1f6cd-4995-45a9-9305-18c99ee17cb5)

The above statement is more prescriptive than it should be. I'll revise it to be more flexible e.g., `Consider if shortening is possible when a method goes beyond ...`

**Comment by radeon2525** [comment]
Thank you for clarifying that for me Prof
