### ISSUE TITLE
Do update all branches once we create the PRs?

### ISSUE THREAD

**Issue by RunjiaChen** [nus-cs2103-AY2324S2/forum#261]
f![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/142142406/61d2c9f9-78e0-4bb6-9ade-dea1eb1ae20f)

Hello guys, just to clarify, are we supposed to update all the old branches and merge it with master? Or do we just need to sync with the recent branches. There is a lot of old branches we need to merge, and I am worried that we do not have enough time.

**Comment by damithc** [comment]
@RunjiaChen if you are referring to step 3, it says _un-merged_ branches (i.e., branches that you haven't merged back to `master` yet).

**Comment by RunjiaChen** [comment]
Thank you prof!
