### ISSUE TITLE
Is Implementing an interface really a IS-A relationship?

### ISSUE THREAD

**Issue by RingoftheKing** [nus-cs2103-AY2324S2/forum#262]
Week 4 notes suggest that "A class implementing an interface results in an is-a relationship"

> Suppose SalariedStaff is an interface that contains two methods setSalary(int) and getSalary(). AcademicStaff can declare itself as implementing the SalariedStaff interface, which means the AcademicStaff class must implement all the methods specified by the SalariedStaff interface i.e., setSalary(int) and getSalary()

However I would like to propose another example that isn't as clear that 

Suppose IHasAbility is an interface that contains the method useAbility(). A healer is a game character that can declare itself as implementing the IHasAbility interface. Which means the Healer must implement the method useAbility(). Yet However, this doesn't mean a healer IS-A HasAbility. I would like to think of implements as a promise of features rather than a IS-A relationship.

**Comment by drustanyjt** [comment]
@RingoftheKing I feel it could be argued that this is just a naming difference, and that every adjective-like interface could be rephrased into a noun-like interface. For example, you could rename the interface into `IAbilityable` (representing something that is able to use an ability) and then you could say a Healer **IS-A** IAbilityable. The example of a `GetAreable` interface from [cs2030s](https://nus-cs2030s.github.io/2223-s2/18-interface.html#Interface) comes to mind.

More generally, I feel like in the OOP paradigm, Classes are always essentially just a promise of features (or perhaps a promise of specific methods being available). So maybe the distinction between the idea of a "promise of features" and the "IS-A relationship" is not so important?
