### ISSUE TITLE
CheckStyle error

### ISSUE THREAD

**Issue by DominicFuMJ** [nus-cs2103-AY2324S2/forum#263]
Hi, could someone help explain what does this checkstyle error mean, and how to fix it? Thank you
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/119829202/77bcfbcd-0ab4-428b-bec0-21afb22cb912)

**Comment by drustanyjt** [comment]
@DominicFuMJ imports that start with `java.*` should usually appear before imports from other packages.

For example this would violate the checkstyle:

```
import duke.DukeException;
import java.time.LocalDate;
import duke.command.ByeCommand;
import duke.command.Command;
```

While this should not:

```
import java.time.LocalDate; # Notice that there is also a space after this import.

import duke.DukeException;
import duke.command.ByeCommand;
import duke.command.Command;
```

**Comment by DominicFuMJ** [comment]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/119829202/3739680b-e849-4814-975c-e8c6d949daaa)
Also got this error, but can't seem to figure it out.

**Comment by drustanyjt** [comment]
@DominicFuMJ you just need to add a new line to the end of your file. For example here line 153 is just a blank line (from pressing the return key).

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/110999129/9adcf449-4c4a-431c-a600-b89bee9a509f)

**Comment by DominicFuMJ** [comment]
Ok. Thank you for the help
