### ISSUE TITLE
Which Scene Builder version to download?

### ISSUE THREAD

**Issue by Li-Zizhen** [nus-cs2103-AY2324S2/forum#265]
# We are using java 11 but there is no scene builder for java 11. Which version should I download?
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/122284239/5430dc87-f0b0-4a97-bf05-fbbdc99a2695)

**Comment by damithc** [comment]
@Li-Zizhen You can download the one for Java 8 as that was the one students used in earlier semesters (although students have reported that both work)

**Comment by Li-Zizhen** [comment]
Got it, thanks.
