### ISSUE TITLE
Seeking clarification on "Add Increments as PRs"

### ISSUE THREAD

**Issue by cheahTJ** [nus-cs2103-AY2324S2/forum#267]
Hi, may I confirm that with regards to the instruction in my title, we are supposed to work on separate branches and then push ONLY THOSE SEPARATE BRANCHES to our github and create a pull request to merge with our remote main. Then what we do next is to pull these changes on the remote main to our local main and update our local branches accordingly and push these updated branches back to our github right?

**Comment by damithc** [comment]
@cheahTJ That's correct 👍

**Comment by cheahTJ** [comment]
Thank you for clarifying prof !
