### ISSUE TITLE
Fixing coding quality with checkstyle

### ISSUE THREAD

**Issue by cheahTJ** [nus-cs2103-AY2324S2/forum#268]
Hi, when I run ./gradlew checkstylemain and these errors keep surfacing but I can't seem to resolve them, how can I go about to resolve them? They all seem to have the same wordings but I don't understand what they actually mean as well:

```
Import statement for 'java.util.ArrayList' is in the wrong order. Should be in the 'STANDARD_JAVA_PACKAGE' group, expecting not assigned imports on this line. [CustomImportOrder]

Import statement for 'java.util.stream.Collectors' is in the wrong order. Should be in the 'STANDARD_JAVA_PACKAGE' group, expecting not assigned imports on this line. [CustomImportOrder]
```

**Comment by JiaXinEu** [comment]
I think this might be due to the order of the import statements. Have you tried putting these import statements before the imports of your custom package.class. 

eg.
```java
import java.util.ArrayList;

import duke.Duke; 
```

**Comment by cheahTJ** [comment]
@JiaXinEu  Thank you, that was indeed the problem! It has been resolved.

**Comment by damithc** [comment]
Good catch @JiaXinEu 💯
