### ISSUE TITLE
A-CI: ./gradlew check passes all tests locally, but workflow run failed on GitHub

### ISSUE THREAD

**Issue by ongzhili** [nus-cs2103-AY2324S2/forum#269]
Hi all, I've been trying to implement CI into my iP for hours, but with mixed results. when running `./gradle check` it passes all locally, but when I push to GitHub, it fails the CI (only on the job named 'Build and check with Gradle')

Error message looks like this on GitHub (2 failed tasks, 1 for checkstyleMain and 1 for checkstyleTest. I have tried setting the configFile manually like `configFile file("${project.rootDir}/config/checkstyle.xml")`, but to no avail. Would like some guidance on this. Thanks in advance 😄 

```
1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':checkstyleMain'.
> A failure occurred while executing org.gradle.api.plugins.quality.internal.CheckstyleAction
   > An unexpected error occurred configuring and executing Checkstyle.
      > Unable to create Root Module: config {/home/runner/work/ip/ip/config/checkstyle/checkstyle.xml}, classpath {null}.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================
```
Here are my `.github/workflows/gradle.yml` , `build.gradle`, and directory for reference.

```java
name: Java CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Set up repository
        uses: actions/checkout@master

      - name: Set up repository
        uses: actions/checkout@master
        with:
          ref: master

      - name: Merge to master
        run: git checkout --progress --force ${{ github.sha }}

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk+fx

      - name: Build and check with Gradle
        run: ./gradlew check
```
and my build.gradle looks like this:

```java
plugins {
    id 'java'
    id 'application'
    id 'checkstyle'
    id 'com.github.johnrengelman.shadow' version '7.1.2'
}

<truncated>

checkstyle {
    toolVersion = '10.2'
}

```

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/122247557/7fe6f1b4-f62b-4e66-ad51-5556b7231266)

**Comment by aureliony** [comment]
Your .gitignore contains:
`config/checkstyle/checkstyle.xml`
`config/checkstyle/suppressions.xml`

You should remove these 2 lines and push the files to the remote repository.

**Comment by ongzhili** [comment]
Thank you so much! This is genuinely a big 🤦 moment for me hahaha...

**Comment by damithc** [comment]
Good catch @aureliony 💯
