### ISSUE TITLE
Cannot import class from main into test

### ISSUE THREAD

**Issue by sarjinius** [nus-cs2103-AY2324S2/forum#270]
![1174741B-2261-4215-81C5-85D405D17336](https://github.com/nus-cs2103-AY2324S2/forum/assets/122223898/dd47b190-bbb1-49d7-a7ed-d054bc274d9c)
Hello, while I was trying to make a JUnit test class for the Todo class, I could not instantiate a Todo class in the test method. I tried to delete the test folder and create it again, I also tried invalidating cache. IntelliJ tells me to move the Todo class from main to test. Any way to resolve this? Thank you in advance!

**Comment by jovantanyk** [comment]
Hi, have you tried using `import virtue.Todo`?

**Comment by sarjinius** [comment]
![986334F6-D046-43E5-BC95-522B816A86B9](https://github.com/nus-cs2103-AY2324S2/forum/assets/122223898/23af1d3b-779e-44ab-ae1d-2f0acb60f3a4)
Yup, still nothing :(

**Comment by kailashgautham** [comment]
[Link](https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs)

You could try this, deleting the IDEA system directory sometimes helps. Also, I don't think you need the "import Todo" line so could you try removing that as well and see if it works?

**Comment by damithc** [comment]
> Also, I don't think you need the "import Todo" line

Yup, if `Todo` and `TodoTest` are in the same package (although in different folders),  there is no need to import.

**Comment by sarjinius** [comment]
They are in the same package, but I still cannot import

**Comment by damithc** [comment]
@sarjinius While waiting for inputs from others, , try these 'common remedies' one-at-a-time in this order:
  * Choose `File` -> `Invalidate caches`
  * Close Intellij -> Delete the `.idea` folder -> Re open the project in Intellij

If still doesn't work, perhaps push the latest code to your fork so that others can try to reproduce the problem?

**Comment by aureliony** [comment]
You can try right-clicking the test/java folder and marking it as "Test Sources Root"

**Comment by sarjinius** [comment]
I have pushed the problematic code to my fork, might want to take a look at that.

**Comment by jovantanyk** [comment]
> I have pushed the problematic code to my fork, might want to take a look at that.

I was able to replicate the issue by cloning from your fork. In your intellij go to Project Structure and make sure the only two modules are ip.main and ip.test. When i pulled from your fork, src was a module as well so the IDE was not able to find the proper class files
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/41192630/9f1a242f-751e-4868-9901-4f03e89170b2)

**Comment by simkianseng** [comment]
> I have pushed the problematic code to my fork, might want to take a look at that.

Perhaps I think there might be some issues with your Gradle configurations. It seems that the issue is resolved after performing these steps below:
1. Delete `settings.gradle` file
2. Load Gradle changes by pressing `Ctrl` + `Shift` + `O`

Do let me know if this works for you.

**Comment by sarjinius** [comment]
> > I have pushed the problematic code to my fork, might want to take a look at that.
> 
> Perhaps I think there might be some issues with your Gradle configurations. It seems that the issue is resolved after performing these steps below:
> 
> 1. Delete `settings.gradle` file
> 2. Load Gradle changes by pressing `Ctrl` + `Shift` + `O`
> 
> Do let me know if this works for you.

This worked for me, thank you very much!
