### ISSUE TITLE
Wrong Git tag

### ISSUE THREAD

**Issue by Lin-Shuang-Shuang** [nus-cs2103-AY2324S2/forum#271]
When working on each increment, I git tagged the commit then pushed the branch to my fork before creating a pull request. However, it seems that I should have tagged the merge commit instead as the instruction says 

> 5. As before, tag the merge commit in the master branch and push the tag to your fork.

Should i delete my previously created git tag and git tag the merge commit?

**Comment by damithc** [comment]
@Lin-Shuang-Shuang It's fine, as long as the tag is in the fork and reachable from the master branch.

**Comment by Lin-Shuang-Shuang** [comment]
@damithc I see, thank you!
