### ISSUE TITLE
Are virtual desktops allowed during tP PE?

### ISSUE THREAD

**Issue by amanzainal** [nus-cs2103-AY2324S2/forum#272]
From [Admin Info](https://nus-cs2103-ay2324s2.github.io/website/admin/tp-pe.html#tp-practical-exam), it states:

> **Only one screen is allowed** (for both remote mode and F2F mode). If you want to use the secondary monitor, you should switch off the primary monitor. The screen being used should be fully visible in the Zoom camera view.
If using a second device for Zoom proctoring, the screen of that device should only be used for Zoom.

As per the title, is it allowed if I use a single monitor with many virtual desktops?  (**Win + Tab** on Windows)

Thanks in advance!

**Comment by damithc** [comment]
@amanzainal Yes, that is fine. The restriction is on on the physical screen count only.
