### ISSUE TITLE
Imports failing and classes cannot be resolved

### ISSUE THREAD

**Issue by timothysashimi** [nus-cs2103-AY2324S2/forum#274]
<img width="958" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/120008429/38e84975-e5cd-491b-8786-af879590ecbd">
Hi all, can I ask why my classes cannot be resolved although I've imported them correctly? The launcher works fine sometimes and the GUI is able to load the program when i run it but sometimes it will not work because my classes cannot be resolved and my packages cannot be found.

**Comment by fy17ohhh** [comment]
Have you tried reimport the project or invalidate the cache?

**Comment by damithc** [comment]
> Have you tried reimport the project or invalidate the cache?

To elaborate on this suggestion, try the following remedies, one at a time.

  * Run `./gradlew clean build`
  * Choose `File` -> `Invalidate caches`
  * Close Intellij -> Delete the `.idea` folder -> Re open the project in Intellij
  * Clone the fork to a different location and open the project in Intellij again to get a fresh start without losing changes you did so far.

**Comment by yisiox** [comment]
@timothysashimi If it's still unresolved I had something like this once when I accidentally got the `package` statement at the top of the file wrong, might be worth a sanity check.

**Comment by timothysashimi** [comment]
hi all, thank you for the help! I tried prof's suggestion of cloning the fork to a different location (under a repo called ip2) and it works, should i continue working on ip2 or the original ip repo and how do i sync the changes between the 2 repos? Thank you!

**Comment by damithc** [comment]
> hi all, thank you for the help! I tried prof's suggestion of cloning the fork to a different location (under a repo called ip2) and it works, should i continue working on ip2 or the original ip repo and how do i sync the changes between the 2 repos? Thank you!

@timothysashimi what I suggested was to _clone_ your ip fork into a new folder in your computer, not create a new _fork_ or a new remote repo with a new name. You should keep pushing to the same fork as before (i.e., https://github.com/timothysashimi/ip) but you can push to it from your new clone in your computer. Just configure the `origin` of your new clone as `https://github.com/timothysashimi/ip.git` instead of `https://github.com/timothysashimi/ip2.git`
