### ISSUE TITLE
JavaFX App Runs in IDE but Fails with Architecture Mismatch Error in Shadow Jar on Apple Silicon Mac

### ISSUE THREAD

**Issue by hjungwoo01** [nus-cs2103-AY2324S2/forum#276]
Hello everyone,

I'm experiencing a challenging issue while attempting to run a JavaFX application on my Apple Silicon Mac, and I could really use some guidance from the community. Below are the details of my development setup and the problem at hand:

Issue Description:
While attempting to launch my JavaFX application, I encounter a series of UnsatisfiedLinkError exceptions related to loading native libraries for JavaFX, indicating an architecture mismatch (x86_64 vs. arm64). Here's a snippet of the error message:

Loading library prism_es2 from resource failed: java.lang.UnsatisfiedLinkError: /Users/username/.openjfx/cache/17.0.7/libprism_es2.dylib: dlopen(/Users/username/.openjfx/cache/17.0.7/libprism_es2.dylib, 0x0001): tried: '/Users/username/.openjfx/cache/17.0.7/libprism_es2.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

This issue prevents the JavaFX application from starting, with the system failing to find a suitable pipeline for the graphics rendering.

Attempted Solutions:
- I have ensured that my JavaFX SDK is intended for arm64 architecture.
- I've attempted to specify the --module-path and --add-modules options with the path to the arm64 JavaFX lib directory when executing my jar.

Additional Context:
Interestingly, my application works perfectly when I run it from my IDE using the launcher, but the issue arises only when I attempt to run the application from a shadow JAR file using `java -jar filename.jar`. This leads me to believe there might be something amiss with how the JAR file is being packaged or how it's handling the JavaFX dependencies, especially concerning native libraries and the architecture-specific configurations.

I'm reaching out to see if anyone else has encountered similar issues or has insights into potential solutions. Any advice on how to properly configure my environment to support JavaFX on an Apple Silicon Mac, especially regarding the packaging of a shadow JAR that correctly handles these dependencies, would be greatly appreciated.

Thank you in advance for your help!

**Comment by 0liverkong** [comment]
hi, by any chance do you have multiple java versions? im on apple m1 as well and i did run into this issue. Can you show what happens when you type java --version in terminal?

**Comment by ThatGirlJam** [comment]
Hi! I'm also using Apple Silicon Mac.

If you are using IntelliJ, you could check under File > Project Structure > Project Settings > Project to ensure that the SDK is Java 11 (Mine is 11.0.19). 

Also if I recall, though I'm not too sure because this was a while ago, I did encounter a problem with JavaFX whereby I had to close IntelliJ and restart it. I also had to check the JavaFxVersion under build.gradle (the tutorial version wasn't suitable somehow, but it works with `String javaFxVersion = '17.0.7'`).

Hope this helps!

**Comment by damithc** [comment]
> hi, by any chance do you have multiple java versions? im on apple m1 as well and i did run into this issue. Can you show what happens when you type java --version in terminal?

Yup, it is safer to have _only_ the prescribed version of Java in your computer so that there is no way another JDK is being used to create the JAR file.

**Comment by damithc** [comment]
Other things to point to the correct JDK:

1. the `JAVA_HOME` system variable (this matters when you use Gradle via the command line)
2. the JVM used by Gradle (this matters when you run Gradle tasks using the Intellij UI)
   ![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/199fe99f-2a22-434a-be22-8ed13f31e5eb)

**Comment by gosongying** [comment]
I am using Apple Silicon Mac as well. IIRC, I followed all the instructions provided except I did change javaFxVersion to "17.0.7" in build.gradle.

**Comment by hjungwoo01** [comment]
> hi, by any chance do you have multiple java versions? im on apple m1 as well and i did run into this issue. Can you show what happens when you type java --version in terminal?

this is my java version:
<img width="1045" alt="Screenshot 2024-02-14 at 9 20 34 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/67430390/a2554318-2164-44f9-b75c-104e27e8b407">

**Comment by hjungwoo01** [comment]
I encountered an unexpected disparity where my terminal was operating on Java 11, while IntelliJ IDEA's command line was configured with Java 21. Following the adjustment of my IntelliJ command line to Java 11, the issue has been successfully resolved. Thank you to all who contributed their insights and assistance.
