### ISSUE TITLE
[Tip] [Git] [VCS] [Commit]💡Intellij can limit commit message subject and body length

### ISSUE THREAD

**Issue by camille-readbean** [nus-cs2103-AY2324S2/forum#278]
IntelliJ can limit and check the number of characters in your commit messages.  
  
Go to Settings > Version Control > Commit.  
  
Set Subject line to 50 characters, body line to 72 characters!  
  
Credits: https://stackoverflow.com/questions/41407982/intellij-commit-50-character-line-length-reminder  
  
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/52031118/d59df10d-ecf9-4b4f-b1e4-ff3a6c152237)

Example:
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/52031118/ffd625b1-a406-4731-bdd3-3dd19b5e88d2)

**Comment by damithc** [comment]
Good find, @camille-readbean
