### ISSUE TITLE
Lecture 5 Questions

### ISSUE THREAD

**Issue by tankh99** [nus-cs2103-AY2324S2/forum#279]
I have a few questions
1. Are feature lists typically derived from user stories? Is it recommended to derive user stories from feature lists?
2. How do we interpret vague class diagrams like these where there is no specific direction, association or multiplicities here? My guess is that 
   3. Professor is related to Student and vice versa
   4. Admin is related to Student and Professor and vice versa 
<img width="577" alt="Screenshot 2024-02-15 at 12 12 13 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/56617918/e1da9ed8-8cc6-4cf2-9dab-03a8b3da37a8">
3. Referring to the above diagram: What does just a simple line represent specifically? Can it mean anything from dependency, inheritance, association, etc?

**Comment by damithc** [comment]
@tankh99 Good questions.

> * Are feature lists typically derived from user stories? Is it recommended to derive user stories from feature lists?

User stories should come before features. We should start with users' needs (i.e., user stories) and only then proceed to figure out how the software caters for those needs (i.e., features). 
Going in the other direction would be like 'solutions looking for problems'. But it is also a common mistake, which is one reason why poorly designed software is common.

> * How do we interpret vague class diagrams like these where there is no specific direction, association or multiplicities here? My guess is that
>   3. Professor is related to Student and vice versa
>   4. Admin is related to Student and Professor and vice versa
>   6. ![IMG_1559.png](https://camo.githubusercontent.com/6cb9214bef7027ffde556fbc6a5ab7afe604582c4f57242785491b9729fb4629/68747470733a2f2f70726f642d66696c65732d7365637572652e73332e75732d776573742d322e616d617a6f6e6177732e636f6d2f37636463323964662d333832652d346233612d393666612d6635346364346237313962302f66366430346632332d393831322d343763652d393261662d6432633036646233393339662f494d475f313535392e706e67)


The image is missing, probably a GitHub bug.
But in general, UML diagrams can omit details that are not relevant to the purpose of the diagram. So, it depends on the purpose of the diagram. For example, if the purpose is to show which classes are in the system, there is no need to show navigability, multiplicity, etc.

> * Referring to the above diagram: What does just a simple line represent specifically? Can it mean anything from dependency, inheritance, association, etc?

A simple line represents an association.

**Comment by tankh99** [comment]
Thank you Prof! I've fixed the image! But since you've already answered it, I'll close this issue now
