### ISSUE TITLE
Optional Parts of the TEAMMATES Peer Feedback

### ISSUE THREAD

**Issue by sindhurajain** [nus-cs2103-AY2324S2/forum#280]
Do I need to press the submit button on optional questions 4, 5, 6 on the TEAMMATES peer feedback form even if I leave them empty since they're optional, so that it will be counted for participation marks?

**
<img width="1252" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/115209308/add50904-4883-45b0-b21a-ed8a8d0d0706">
**

**Comment by damithc** [comment]
@sindhurajain No need to submit optional questions

**Comment by sindhurajain** [comment]
Thanks!
