### ISSUE TITLE
Cannnot see option for Merge Pull request

### ISSUE THREAD

**Issue by Shauryan123** [nus-cs2103-AY2324S2/forum#281]
![Screenshot 2024-02-15 at 9 49 47 AM](https://github.com/nus-cs2103-AY2324S2/forum/assets/119833428/4c5559a7-7a31-416a-b383-96f9c5053727)

As you can see, I want to merge the pull request from my branch-A-Assertions into master and even though there are no merge conflicts, the option for Merging the Pull Request is not being shown.

Please help me

**Comment by camille-readbean** [comment]
For those wondering why it was marked close.  
  
I think it was cause the pr was merging into the base repo. Not the forked one.
