### ISSUE TITLE
Query in C-Help

### ISSUE THREAD

**Issue by radeon2525** [nus-cs2103-AY2324S2/forum#282]
I wanted to clarify if for the C-Help extension, do we need to redirect the conversation to a different page or is the help information provided as part of the normal conversation also acceptable.

**Comment by damithc** [comment]
> I wanted to clarify if for the C-Help extension, do we need to redirect the conversation to a different page or is the help information provided as part of the normal conversation also acceptable.

@radeon2525 it's up to you. Both are acceptable.

**Comment by radeon2525** [comment]
Okay, thank you Prof
