### ISSUE TITLE
Extension and PR

### ISSUE THREAD

**Issue by RunjiaChen** [nus-cs2103-AY2324S2/forum#283]
Do we need to setup extension as PR as well? Or can we just create a branch and merge it locally before pushing to origin?

**Comment by sindhurajain** [comment]
The course website says this: Recommended to add the extension via a branch (branch name is up to you). Optional to add it via a PR. (https://nus-cs2103-ay2324s2.github.io/website/schedule/week5/project.html)

**Comment by damithc** [comment]
> The course website says this: Recommended to add the extension via a branch (branch name is up to you). Optional to add it via a PR. (https://nus-cs2103-ay2324s2.github.io/website/schedule/week5/project.html)

Yup, @RunjiaChen is correct.

**Comment by RunjiaChen** [comment]
okay, thank you
