### ISSUE TITLE
Code Quality Standard for FXML

### ISSUE THREAD

**Issue by DhiraPT** [nus-cs2103-AY2324S2/forum#284]
Is there any code quality standard for FXML?

For example, does the principle of avoiding deep nesting also apply to FXML and other markup languages, which I've noticed often involve significant nesting?

**Comment by damithc** [comment]
@DhiraPT we don't have a ~~code quality standard~~ _coding standard_ (aka _style guide_) for FXML.
You are free to adopt your own.
