### ISSUE TITLE
GUI File Path Error

### ISSUE THREAD

**Issue by KhoonSun47** [nus-cs2103-AY2324S2/forum#285]
Development Environment: MacOS

Hi, I am having trouble with the relative path for my images and FXML files. Attached is my build path, code and error messages. I tried using the absolute path and it works.

```java
/**
 * A GUI for William using FXML.
 */
public class Main extends Application {

    private William william = new William();

    @Override
    public void start(Stage primaryStage) throws Exception {
        try {
            
            FXMLLoader fxmlLoader = new FXMLLoader(MainWindow.class.getResource("/view/MainWindow.fxml"));
           
            AnchorPane ap = fxmlLoader.load();
            Scene scene = new Scene(ap);
            primaryStage.setScene(scene);
            primaryStage.setTitle("William ChatBot");
            fxmlLoader.<MainWindow>getController().setWilliam(william);
            primaryStage.show();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

}
```

<img width="203" alt="Screenshot 2024-02-16 at 10 55 31 AM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/133077437/4ea1add5-bfc4-4c22-89b9-5e990f1adfcb">

<img width="1105" alt="Screenshot 2024-02-16 at 11 04 29 AM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/133077437/97497007-2083-4b26-bec1-210610cd0171">

**Comment by camille-readbean** [comment]
Resources folder should be under main/ not main/java/

**Comment by KhoonSun47** [comment]
My resource folder is initially under main/, not main/java/, but it still does not work.

![IMG_2807](https://github.com/nus-cs2103-AY2324S2/forum/assets/133077437/1a916ba5-3ff7-4e35-8fcf-16c24da97025)

**Comment by damithc** [comment]
@KhoonSun47 is the issue resolved, or you closed this issue by mistake?

**Comment by KhoonSun47** [comment]
I close it by mistake

**Comment by damithc** [comment]
@KhoonSun47 Perhaps you can push your latest code to your fork/branch and share that info here so that others can try to replicate the problem?

**Comment by KhoonSun47** [comment]
I cloned the project on my friends computer, and the relative path works (for some reason). I think the environment or the build path is incorrect on my laptop.

**Comment by damithc** [comment]
> I cloned the project on my friends computer, and the relative path works (for some reason). I think the environment or the build path is incorrect on my laptop.

@KhoonSun47 Try running `./gradlew clean` first and then running the application.

Also, you can clone the fork to a different location of your own computer and try it from there. If that works, you continue your iP from that location.

**Comment by KhoonSun47** [comment]
I managed to solve it by using IntelliJ instead of Visual Studio, I think the environment on my Visual Studio is set wrongly. 

Thank you.
