### ISSUE TITLE
Error encountered with yml file 

### ISSUE THREAD

**Issue by PateShin** [nus-cs2103-AY2324S2/forum#286]
I tried to push on Sourcetree after committing the YML file. However, I encountered following error:

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/81001954/271d3de9-b7cb-41c5-9967-934a35c18f49)

How can I fix it and push?

**Comment by zhekaiii** [comment]
Hello, I have a feeling this solution will work for you. Do try it out and let me know :) https://stackoverflow.com/a/64080046

**Comment by yisiox** [comment]
@PateShin I think the issue is related to [this](https://stackoverflow.com/questions/64059610/how-to-resolve-refusing-to-allow-an-oauth-app-to-create-or-update-workflow-on).

**Comment by yisiox** [comment]
Ah we just answered the same link oops.

**Comment by pjanthony2001** [comment]
> Hello, I have a feeling this solution will work for you. Do try it out and let me know :) https://stackoverflow.com/a/64080046

Hi, I faced the same issue and this solution fixed it! You'd have to configure SourceTree to use the token (which isn't covered in stackoverflow) which is covered in this article

https://medium.com/geekculture/using-personal-access-token-in-sourcetree-to-connect-to-github-3702a29554d3

**Comment by wilsonwid** [comment]
I didn't seem to encounter this issue when using the Git CLI instead of Sourcetree.

**Comment by yashma-sonara** [comment]
Hi, I also had the same error. I wasn't able to figure out how to push from cli or sourcetree. So I ended up directly editing on github, which worked.

**Comment by zhekaiii** [comment]
If I'm not wrong, when logging into SourceTree with your GitHub account, a Personal Access Token (PAT) is required. This token is associated with configurable permissions, and it is possible that during its setup, the necessary permissions for configuring workflows were not enabled. Consequently, this omission may be hindering your ability to perform workflow setups through SourceTree.

**Comment by PateShin** [comment]
@zhekaiii @yashma-sonara @wilsonwid @pjanthony2001 @yisiox 

Thanks everyone, I have solved my problem 😄 👍
