### ISSUE TITLE
Inconsistent formatting of JavaDoc in the textbook?

### ISSUE THREAD

**Issue by E0735389** [nus-cs2103-AY2324S2/forum#287]
I notice that in the textbook, the JavaDoc does not always satisfy the coding standard.

For example:

https://nus-cs2103-ay2324s2.github.io/website/schedule/week3/topics.html#implementation-documentation-tools-javadoc-what

The code:
```java
 * @param url an absolute URL giving the base location of the image
 * @param name the location of the image, relative to the url argument
 * @return the image at the specified URL
 * @see Image
```

while the [coding standard](https://se-education.org/guides/conventions/java/intermediate.html#comments) states:

> Punctuation behind each parameter description.

There are some other points where it's inconsistent, although I'm not sure what is the guideline, or if either way is fine.

1. in the textbook in https://nus-cs2103-ay2324s2.github.io/website/schedule/week3/topics.html#c-to-java-junit-junit-basic there is a line
	```java
     * @throws Exception if second is 0
	```
	there's no punctuation.

	Although this is not a **parameter** description.

	On the other hand, https://nus-cs2103-ay2324s2.github.io/website/schedule/week3/topics.html#implementation-documentation-tools-javadoc-how has
	```java
	 * @throws IllegalArgumentException If zone is <= 0.
	```
	there is final punctuation.

2. Comparing the two example above, we see that in one case, the "if" is capitalized, while in the other it's not capitalized.
3. Meanwhile, in the [Java coding standard](https://se-education.org/guides/conventions/java/intermediate.html#comments):

	```java
	 * @throws IllegalArgumentException  If zone is <= 0.
	```
	there are **two** spaces before the "If".

Which one is correct? Or either way is fine?

**Comment by damithc** [comment]
Thanks for bringing these up, @E0735389 
Fixed.
