### ISSUE TITLE
Minor typo in w1.4c example

### ISSUE THREAD

**Issue by ashleyclx** [nus-cs2103-AY2324S2/forum#29]
In W1.4c  : 
C++ to Java → Collections → The HashMap class
In the example line 20 and subsequently line 3 should be "Key y1 exists? " not "Key x1 exists? "
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/122247464/4398351d-bde2-4a1e-8a98-b30ba42f9a8d)
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/122247464/2c6111a7-a118-4b62-be2c-3d8f2b41eed9)

**Comment by damithc** [comment]
Thanks for reporting this, @ashleyclx 
Fixed.
