### ISSUE TITLE
Question on selecting user stories for v1.2

### ISSUE THREAD

**Issue by belligerentbeagle** [nus-cs2103-AY2324S2/forum#290]
Hi Prof Damith, @damithc, I was encouraged to ask this question to you by a TA. My team and I were wondering if we could include NFRs in our selection of user stories in v1.2. 

For example, would `The application should handle common errors gracefully, such as incorrect data entry, without crashing or losing data.` constitute a suitable user story?

Many thanks in advance!

**Comment by damithc** [comment]
@belligerentbeagle Good question.

To answer a slightly different question though, yes, NFRs can be expressed in the form of user stories. More info [here](https://nus-cs2103-ay2324s2.github.io/website/se-book-adapted/chapters/specifyingRequirements.html#:~:text=User%20stories%20can%20capture%20non%2Dfunctional%20requirements%20too).

So, you can first express your NFRs in the form of user stories, and after that, apply the same criteria for them that you used when selecting other user stories for v1.2
Does that resolve your query?

**Comment by belligerentbeagle** [comment]
yes it does. Essentially come up with technical/explicit requirements that cover those NFRs. Then we can decide whether those are essential or not for v1.2
