### ISSUE TITLE
[tP] Setting up MarkBind

### ISSUE THREAD

**Issue by Ryan-Reno** [nus-cs2103-AY2324S2/forum#291]
Hi prof @damithc, Step 2 says to deploy from a branch called gh-pages. But our tP does not have that branch. Am I missing something? Or is it just referring to the switch-docs-to-markbind branch
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/111992508/0fe88acb-bc04-4779-8f04-e47db4367a2f)

**Comment by dillontkh** [comment]
I assume you are referring to the `A-UserGuide` increment. However, I am seeing a different instruction for that step.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/40649376/26281a58-6496-4662-9346-79f65a699981)

Could you verify that you are on the correct website for the current semester?
https://nus-cs2103-ay2324s2.github.io/website/schedule/week6/project.html

**Comment by dillontkh** [comment]
Ah never mind, I think you were referring to [this page](https://se-education.org/guides/tutorials/markbind-forked-sites.html#initiating-the-site) instead.

**Comment by aureliony** [comment]
After merging the switch-docs-to-markbind branch into master, the markbind action will be performed, and the documents will be pushed automatically to the gh-pages branch (assuming you allowed the required permissions as stated in the markbind guide).

**Comment by damithc** [comment]
@Ryan-Reno, As @aureliony observed, the `gh-pages` branch will only be present after you've pushed the config file changes to your fork. So, the current step 2 needs to be moved down a bit.
I've updated the instructions accordingly. just now.

**Comment by Ryan-Reno** [comment]
Ah okay then thanks for the clarification prof!

**Comment by Ryan-Reno** [comment]
Ah okay then thanks for the clarification prof!
