### ISSUE TITLE
Issue regarding welcome message in gui

### ISSUE THREAD

**Issue by radeon2525** [nus-cs2103-AY2324S2/forum#292]
I am not able to display the welcome message when my gui starts up. I have done the following in my start method:

@Override
    public void start(Stage stage) {
        try {
            FXMLLoader fxmlLoader = new FXMLLoader(Duke.class.getResource("/view/MainWindow.fxml"));
            AnchorPane ap = fxmlLoader.load();
            Scene scene = new Scene(ap);
            stage.setScene(scene);
            stage.setTitle("Duke");
            MainWindow controller = fxmlLoader.<MainWindow>getController(); //this line
            controller.setDuke(this);
            controller.displayWelcomeMessage();       //and this line                                    
            stage.show();
            ....

And added:
 public void displayWelcomeMessage() {
        String welcomeMessage = "Hello! I'm Duke\nWhat can I do for you?";
        addDialog(welcomeMessage, false);
    }
in my MainWindow.java

But I am still not able to see any welcome message in my gui

**Comment by damithc** [comment]
@radeon2525  While waiting for inputs from others, you may want to use [fenced code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) to format your post for better readability.

**Comment by yisiox** [comment]
@radeon2525 If you push your code I can try to replicate the issue, I can't make it out from the snippet.

**Comment by yashpola** [comment]
Probably need to add this to the initialise method of MainWindow. That's where I added my welcome message

**Comment by radeon2525** [comment]
@yisiox I have pushed my code, maybe you can try to see if it works!

**Comment by radeon2525** [comment]
@yashpola thank you for your help, the welcome message worked after inserting it in the initialise method
