### ISSUE TITLE
Is the course website down?

### ISSUE THREAD

**Issue by Jerome-j** [nus-cs2103-AY2324S2/forum#293]
<img width="1258" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/49815108/d4004d11-cf6d-4acd-8f45-7684f2e055cf">

Hello, it appears that the course website at https://nus-cs2103-ay2324s2.github.io/website/ is down. Anyone facing similar issues?

**Comment by damithc** [comment]
Yup. Thanks for the heads up @Jerome-j 
I'm working on it. Will update here soon.

**Comment by damithc** [comment]
Fixed.
