### ISSUE TITLE
Configuring checkstyle for lookarounds

### ISSUE THREAD

**Issue by tzyian** [nus-cs2103-AY2324S2/forum#294]
The [coding style](https://se-education.org/guides/conventions/java/intermediate.html#comments) for Javadoc notes to have the first sentence of method Javadoc start in the form `Returns...`, etc.

The autoformatter and the existing guide already takes care of most of the Javadoc style so I tried to configure `checkstyle` to check that the first word is capitalized and ends in "s". 

I can get the capitalization lint working, but I can't seem to get the ending to work.

```xml
<module name="Regexp">
    <property name="format" value="\/\*\*\s+?\* \w+?(?<!s)\b"/>
    <property name="message"
        value="Javadoc method description must start with a capitalized word ending in 's'"/>
    <property name="ignoreComments" value="false"/>
    <property name="illegalPattern" value="true"/>
</module>
```

I've tried testing both the above regex and other variations of `\/\*\*\s+?\* (?!.+?s).\b`. They work on online testers.

Or do lookarounds just not work in the `Regexp` module and require more sophisticated checks?

**Comment by yisiox** [comment]
You need to escape the `<` in xml files as `&lt;`.

**Comment by tzyian** [comment]
Ah that was the problem, thanks!

Is there anything that needs to be escaped in `\/\*\*\s+?\* (?!.+?s).\b`, or is my regex just wrong here?

**Comment by yisiox** [comment]
I don't think there's any characters here that need to be escaped - should only be quotes, less than, greater than, and ampersand. 

Sorry my knowledge of regex is still closer to DFAs, are you able to explain the intention of this regex? This looks like it is matching a word that doesn't contain s, though I could be very wrong.

**Comment by tzyian** [comment]
`\/\*\*\s+?\* \w+?(?<!s)\b` has a negative lookbehind to not capture anything inside the (?<!)

`\/\*\*\s+?\* (?!.+?s\b).` (I realised the one above had a few errors) is a negative lookahead to not capture anything inside the (?!) and only match after.

I suspect it's a error on my part, can't say I'm the best at lookarounds

TIL there's regex quantifiers too, regex is way too complicated haha

But thanks!

Edit: I just tried `\/\*\*\s+?\* (?!.+?s\b).` and it doesn't work in `checkstyle`, but seems to work on https://regex101.com/

**Comment by yisiox** [comment]
You have to make sure the flavour (is this the term?) of regex matches the Java one.

Edit: deleted the wrong part to prevent confusion.

Maybe if I use a space to limit the end of the word it is `.+(?!s)\s`

**Comment by tzyian** [comment]
Yep have checked the flavour. 
Also you can't greedily (or even lazily) match `.` before the negative lookahead because you don't know how much to match `.` before checking for the lookahead. 
Thanks though.

**Comment by wilsonwid** [comment]
Hi, it seems that this could work:
```xml
<module name="Regexp">
  <property name="format"
            value="\/\*\*(\s)+\*\s(\w)+(?&lt;!s)\b"/>
  <property name="message"
            value="Javadoc method description must start with a capitalized word ending in 's'"/>
  <property name="ignoreComments" value="false"/>
  <property name="illegalPattern" value="true"/>
</module>
```

**Comment by wilsonwid** [comment]
Hi Prof @damithc, how should we cite forum postings such as these in our `checkstyle.xml` code?

**Comment by damithc** [comment]
> Hi Prof @damithc, how should we cite forum postings such as these in our `checkstyle.xml` code?

@wilsonwid there is no need to cite forum posts as the forum is considered a resource provided by the course.

**Comment by wilsonwid** [comment]
Thank you Prof! @damithc

**Comment by tzyian** [comment]
> Hi, it seems that this could work:

Yep that works thanks haha. 
Just fyi, this regex is quite naive so it has false positives with non-method Javadoc as well. Although that can be easily circumvented since we don't have specifications for non-method Javadoc.
