### ISSUE TITLE
Class not found exception when trying to run duke.jar

### ISSUE THREAD

**Issue by ChuaZiLong** [nus-cs2103-AY2324S2/forum#296]
I ran ./gradlew clean shadowJar in IntelliJ to get the duke.jar into /build/libs.

When I ran java -jar duke.jar in the terminal on my laptop, it says:
Error: Could not find or load main class Duke
Caused by: java.lang.ClassNotFoundException: Duke

I tried compiling the .java files then rerunning ./gradlew clean shadowJar but I still got the same error.

Not sure what is going on, any help is appreciated

**Comment by wilsonwid** [comment]
Hi, is there any possibility that you have not updated the `build.gradle` file to the new GUI launcher? Specifically, this part should be changed, I believe:
```gradle
application {
    mainClass.set(...)
}
```

**Comment by amanzainal** [comment]
Are you running the command in the same directory as the jar file?

The jar file can be found in build/libs. Open a terminal there and try running the command again.

**Comment by ChuaZiLong** [comment]
I navigated to build/libs and ls shows duke.jar so I think I am in the right directory.

Duke.java is the file that launches the GUI and duke is the package name so I tried:

mainClass.set("Duke"), mainClass.set("duke"), mainClass.set("duke.Duke") but I still got the same error.

**Comment by wilsonwid** [comment]
Have you tried using `./gradlew run` first to see whether your code compiles?

**Comment by bachletuankhai** [comment]
Hi, I went in your code and saw that in `gradle.build`, you have `mainClass.set("seedu.duke.Duke")` on line 9 and `mainClassName = 'Duke'` on line 42. You should keep them the same and change the class name to the proper class (in this case, it supposed to be `duke.Duke`).

**Comment by ChuaZiLong** [comment]
Oops yeah after changing mainClassName to duke.Duke it worked fine. Thanks everyone
