### ISSUE TITLE
How detailed should the user guide be?

### ISSUE THREAD

**Issue by wxiaoyun** [nus-cs2103-AY2324S2/forum#297]
What are some of the things you included for your user guide?

I included:
- Short introduction
- Description for essential features (not all features)
- Similarly how to use the appropriate command for these features

What are your thoughts

**Comment by drustanyjt** [comment]
@ForAeons I also added a cheatsheet table of all the commands you could use for easier referencing.

**Comment by simkianseng** [comment]
I think can also include a table of contents.

**Comment by sindhurajain** [comment]
I'm also planning to include a few example use cases

**Comment by wxiaoyun** [comment]
Thanks everyone, I will be sure to include those too

**Comment by itstrueitstrueitsrealitsreal** [comment]
I added screenshots of the Ui in order for the user to better visualise if they're on the right track!

**Comment by UdhayaShan1** [comment]
^screenshots are the best, put it all in a directory and refer to them with gfmd
