### ISSUE TITLE
Citing project code of current student

### ISSUE THREAD

**Issue by wilsonwid** [nus-cs2103-AY2324S2/forum#298]
If I had an inspiration from the iP code of a current student and I implemented it without copy-pasting, how should I cite it? Should the citation still be in the following format (as referenced from the course website):

```java
//@@author {yourGithubUsername}-reused
//{Info about the source...}

{Reused code (possibly with minor modifications) here ...}

//@@author
```

**Comment by wilsonwid** [comment]
Moreover, is linking to the GitHub page of the source file that I had my inspiration from enough, or would putting in the GitHub permalink be better? It seems that putting the GitHub permalink would violate the checkstyle's maximum line length requirements.

**Comment by damithc** [comment]
@wilsonwid 
It would be good to cite the source for the inspiration.
Either type of link is OK.

**Comment by wilsonwid** [comment]
Okay, thank you Prof! Would the above format be alright for citation purposes? @damithc

**Comment by damithc** [comment]
@wilsonwid use `@@author {yourGithubUsername}-reused` only if the code is lifted almost verbatim from some other source. Otherwise (e.g., inspired by, or adapted heavily compared to the original source) just cite the source in a comment (without wrapping within a `@@author` tag)

**Comment by wilsonwid** [comment]
Okay, thank you Prof!
