### ISSUE TITLE
Minor spelling mistake in [Optional] Anonymous feedback for the course

### ISSUE THREAD

**Issue by ongzhili** [nus-cs2103-AY2324S2/forum#299]
Question 4 on Anonymous feedback for the course on Canvas

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/122247557/7f7a317d-9b30-4776-92d3-7b628b1f4582)

Minor spelling error in the first question

Actual:
>Qality of ....

Expected
>Quality of ....

**Comment by damithc** [comment]
Fixed. Thanks for reporting it @ongzhili
