### ISSUE TITLE
Minor typo in w2.3c

### ISSUE THREAD

**Issue by drustanyjt** [nus-cs2103-AY2324S2/forum#30]
At the bottom of [W2.3c](https://nus-cs2103-ay2324s2.github.io/website/schedule/week2/topics.html#w2-3-rcs-revision-history) the course website currently states:

> It is fine to learn the CLI way only (using Sourcetree is optional), especially if you normally prefer to work with CLI user GUI.

I think this is a typo and should be

> It is fine to learn the CLI way only (using Sourcetree is optional), especially if you normally prefer to work with CLI **over** GUI.

Screenshot for reference:
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/110999129/878e80dd-a6ea-41a9-832e-46adcf128993)

**Comment by damithc** [comment]
Thanks for reporting this, @drustanyjt 
Fixed.
