### ISSUE TITLE
Adding multiple product images in docs folder

### ISSUE THREAD

**Issue by yashpola** [nus-cs2103-AY2324S2/forum#300]
Are we allowed to add multiple images in docs folder to add in our UG? As long as there is a `Ui.png` file at the top-level of the folder, we can add any other subfolders/files/images?

**Comment by damithc** [comment]
@yashpola Yes, you may have any number of images in your UG. Our only restriction is that Ui.png contains only a single screenshot of the app (i.e., not multiple screenshots stitched together). 
The rest of the images can be anything you want them to be.

**Comment by yashpola** [comment]
@damithc thanks prof
