### ISSUE TITLE
Is it ok to have a long method body if it consists of multiple switch cases?

### ISSUE THREAD

**Issue by logical-1985516** [nus-cs2103-AY2324S2/forum#303]
As per the coding quality guidelines, the method length should be <= 30 LoC if possible. However, if a method has multiple switch cases, would it be exempt from this rule? Otherwise, each switch case has to be very short, and it seems quite difficult to shorten such a method or split it into multiple methods.

**Comment by damithc** [comment]
@logical-1985516 it's a guideline only, not a strict rule. So, you _may_ have methods longer than 30 lines if you feel shortening them is not worth the effort. It's a case-by-case judgement call you need to make. If you are not sure, you can post the code here and get inputs from others as to if it should be, and how it can be, shortened.

**Comment by bryanyee33** [comment]
Not sure if it will be useful, but you could try:

1. Abstracting out each of the cases into a different method, especially if multiple cases share common code.
2. Abstract out the entire switch-case block into a method, that returns the result of the switch-case. In this way you would be able to end with a return statement within each case instead of a break statement, which allows you to possibly combine your code within that return statement (this would pair well with point 1)

**Comment by yisiox** [comment]
@logical-1985516 This is subjective but I think it's only okay if you don't have complex logic visible in each case. For example, if the following reaches over 30 Loc because there's simply many commands I think it's mostly unavoidable and still clear to read. The details are also abstracted behind the methods which is also helpful since some cases have similar validation as @bryanyee33 suggested.
```java
String command = someParsingLogic(input);
String[] args = otherParsingLogic(input);
switch (command) {
case "list":
    someListSpecificArgsValidation(args);
    return new ListCommand(args);
case "todo":
    someTodoSpecificArgsValidation(args);
    return new TodoCommand(args);
...
```
This is in constrast to
```
switch (something) {
case 1:
    many
    lines
    of
    code
    break;
case 2:
    more
    lines
    of
    code
    break;
 ...
 ```

**Comment by camille-readbean** [comment]
I took a look at your parser code. It might be possible to do the input checking within the methods itself. 

https://github.com/logical-1985516/ip/blob/master/src/main/java/kitchensink/Parser.java
```java
        String command = input.split(" ")[0].toLowerCase();
        switch (command) {
        case "bye":
            if (!input.equalsIgnoreCase("bye")) {
                return new InvalidSyntaxException("bye").toString();
            }
            assert input.equals("bye") || input.equals("Bye") || input.equals("bYe") || input.equals("byE")
                    || input.equals("BYe") || input.equals("ByE") || input.equals("bYE") || input.equals("BYE");
            return ui.displayGoodBye();
        case "list":
            if (!input.equalsIgnoreCase("list")) {
                return new InvalidSyntaxException("list").toString();
            }
            assert input.equals("list") || input.equals("List") || input.equals("lIst") || input.equals("liSt")
                    || input.equals("lisT") || input.equals("LIst") || input.equals("LiSt") || input.equals("LisT")
                    || input.equals("lISt") || input.equals("lIsT") || input.equals("liST") || input.equals("LISt")
                    || input.equals("LIsT") || input.equals("LiST") || input.equals("lIST") || input.equals("LIST");
            return ui.displayTasks(taskList);
        case "mark": {
            if (input.split(" ").length != 2) {
                return new InvalidSyntaxException("mark").toString();
            }
            try {
                Integer.parseInt(input.split(" ")[1]);
            } catch (NumberFormatException e) {
                return new InvalidSyntaxException("mark").toString();
            }
            int taskNum = Integer.parseInt(input.split(" ")[1]);
            if (!taskList.isValidTaskNum(taskNum)) {
                return new TaskNotFoundException(taskList).toString();
            }
            return taskList.markTask(taskNum - 1, storage, ui);
        }
        case "unmark": {
            if (input.split(" ").length != 2) {
                return new InvalidSyntaxException("unmark").toString();
            }
            try {
                Integer.parseInt(input.split(" ")[1]);
            } catch (NumberFormatException e) {
                return new InvalidSyntaxException("unmark").toString();
            }
            int taskNum = Integer.parseInt(input.split(" ")[1]);
            if (!taskList.isValidTaskNum(taskNum)) {
                return new TaskNotFoundException(taskList).toString();
            }
            return taskList.unmarkTask(taskNum - 1, storage, ui);
        }
```

**Comment by guanquann** [comment]
> I took a look at your parser code. It might be possible to do the input checking within the methods itself.
> 
> https://github.com/logical-1985516/ip/blob/master/src/main/java/kitchensink/Parser.java
> 
> ```java
>         String command = input.split(" ")[0].toLowerCase();
>         switch (command) {
>         case "bye":
>             if (!input.equalsIgnoreCase("bye")) {
>                 return new InvalidSyntaxException("bye").toString();
>             }
>             assert input.equals("bye") || input.equals("Bye") || input.equals("bYe") || input.equals("byE")
>                     || input.equals("BYe") || input.equals("ByE") || input.equals("bYE") || input.equals("BYE");
>             return ui.displayGoodBye();
>         case "list":
>             if (!input.equalsIgnoreCase("list")) {
>                 return new InvalidSyntaxException("list").toString();
>             }
>             assert input.equals("list") || input.equals("List") || input.equals("lIst") || input.equals("liSt")
>                     || input.equals("lisT") || input.equals("LIst") || input.equals("LiSt") || input.equals("LisT")
>                     || input.equals("lISt") || input.equals("lIsT") || input.equals("liST") || input.equals("LISt")
>                     || input.equals("LIsT") || input.equals("LiST") || input.equals("lIST") || input.equals("LIST");
>             return ui.displayTasks(taskList);
>         case "mark": {
>             if (input.split(" ").length != 2) {
>                 return new InvalidSyntaxException("mark").toString();
>             }
>             try {
>                 Integer.parseInt(input.split(" ")[1]);
>             } catch (NumberFormatException e) {
>                 return new InvalidSyntaxException("mark").toString();
>             }
>             int taskNum = Integer.parseInt(input.split(" ")[1]);
>             if (!taskList.isValidTaskNum(taskNum)) {
>                 return new TaskNotFoundException(taskList).toString();
>             }
>             return taskList.markTask(taskNum - 1, storage, ui);
>         }
>         case "unmark": {
>             if (input.split(" ").length != 2) {
>                 return new InvalidSyntaxException("unmark").toString();
>             }
>             try {
>                 Integer.parseInt(input.split(" ")[1]);
>             } catch (NumberFormatException e) {
>                 return new InvalidSyntaxException("unmark").toString();
>             }
>             int taskNum = Integer.parseInt(input.split(" ")[1]);
>             if (!taskList.isValidTaskNum(taskNum)) {
>                 return new TaskNotFoundException(taskList).toString();
>             }
>             return taskList.unmarkTask(taskNum - 1, storage, ui);
>         }
> ```


>             assert input.equals("list") || input.equals("List") || input.equals("lIst") || input.equals("liSt")
>                     || input.equals("lisT") || input.equals("LIst") || input.equals("LiSt") || input.equals("LisT")
>                     || input.equals("lISt") || input.equals("lIsT") || input.equals("liST") || input.equals("LISt")
>                     || input.equals("LIsT") || input.equals("LiST") || input.equals("lIST") || input.equals("LIST");
Not sure if the assert statement here is useful/needed?

**Comment by logical-1985516** [comment]
Thanks everyone for the helpful comments, in the method parse in Parser class, I have managed to abstract the details of cases "bye" and "list" into a method, cases "mark", "unmark" and "delete" into another method, and cases "todo", "deadline" and "event" into their own methods. I have also managed to reduce the length of other long methods.
