### ISSUE TITLE
Necessary to create v0.1 release?

### ISSUE THREAD

**Issue by wilsonwid** [nus-cs2103-AY2324S2/forum#305]
Is it necessary to create a v0.1 release of the iP on GitHub, or is it only necessary to create the v0.2 release?

**Comment by UdhayaShan1** [comment]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39399745/43f7a4de-acdf-433d-9de3-09e23bb5fafe)

v0.1 iirc was part of A-Jar

**Comment by damithc** [comment]
@UdhayaShan1 It's good enough if the final version is released on GitHub, together with the JAR file. You are free to have more releasees too. We take the latest one as the final submission.

**Comment by wilsonwid** [comment]
Alright, thank you @UdhayaShan1 and Prof @damithc!
