### ISSUE TITLE
Typo in grade breakdown

### ISSUE THREAD

**Issue by chengjunyuan** [nus-cs2103-AY2324S2/forum#307]
There are two typos in the following paragraph taken from [here](https://nus-cs2103-ay2324s2.github.io/website/admin/gradeBreakdown.html).

> Here is another example question. Note the [SELECT ALL] at the **sart** of the **qusetion** text, which tells you that this question can have multiple correct answers, and you need to select all of them i.e., it is a checkbox type question
The answer is C, D.

The bolded words in the quote above are the typos, `sart` should be `start` and `qusetion` should be `question`.

**Comment by damithc** [comment]
@chengjunyuan Thanks for reporting this. Fixed.
