### ISSUE TITLE
Codecov Coverage Query

### ISSUE THREAD

**Issue by chiralcentre** [nus-cs2103-AY2324S2/forum#309]
Hi, I have been trying to set up the team repo for the TP. After setting up codecov on the repo, while the badge in README.md shows 75% coverage, the main dashboard in codecov shows the following "no data" message. Can I check if this is normal, and if not, how can I rectify the issue?

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/83827461/8c3e1f69-3397-45fb-9248-c8cf1319d074)

**Comment by damithc** [comment]
@chiralcentre Let's wait to hear from others how their Codecov set up compare to yours. For the time being, don't worry about it as Codecov set up is not critical to the tP.

**Comment by yashpola** [comment]
I have the same situation as yours so maybe its not unusual. I'm assuming it has something to do with properly running CI/CD on the tp so shld be a matter of time before we start seeing updates on the dashboard

**Comment by gosongying** [comment]
got the same issue also, it keep showing "no data".
