### ISSUE TITLE
Unable to launch jar file with double-click

### ISSUE THREAD

**Issue by yashpola** [nus-cs2103-AY2324S2/forum#311]
My jar file works fine with `java -jar` but doesn't launch upon double-click. Local version is Azul-11 and I'm on MacOS. Is there something special I need to configure or do? 

@damithc prof in the worst case would it be alright if the jar file only works from the command line?

**Comment by guanquann** [comment]
Mine also only works with the `java -jar` command. From the docs, it is ok.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/76832850/7e727935-5886-4d2a-b0ef-69307692d61b)

**Comment by damithc** [comment]
@yashpola yes, that's good enough.
Thanks for the pointer @guanquann

**Comment by yashpola** [comment]
@guanquann @damithc thank you
