### ISSUE TITLE
TP Forking

### ISSUE THREAD

**Issue by chiralcentre** [nus-cs2103-AY2324S2/forum#313]
This may be a trivial question, but I would like to check if owners of the TP repo in the team organisation are required to fork the TP repo to their personal Github account as well. In addition, it was mentioned that we are allowed to switch to a lighter workflow after the first iteration. If the team is interested to switch over to the feature branch workflow after v1.2, does this mean we no longer use our TP forks, and every team member clones the TP repo in the team organisation instead?

**Comment by damithc** [comment]
> This may be a trivial question, but I would like to check if owners of the TP repo in the team organisation are required to fork the TP repo to their personal Github account as well.

@chiralcentre Yes. The team repo is shared among team members. In addition, each member should have their own fork.

> In addition, it was mentioned that we are allowed to switch to a lighter workflow after the first iteration. If the team is interested to switch over to the feature branch workflow after v1.2, does this mean we no longer use our TP forks, and every team member clones the TP repo in the team organisation instead?

Yes, individual forks can be bypassed if you switch to a workflow that doesn't require the individual fork.

**Comment by drustanyjt** [comment]
@chiralcentre 
1. I believe everyone needs to create their own fork, if not you wouldn't be able to open a pull request without creating a new branch on the team repo (which sounds like a feature branch workflow).

2. Cloning the TP repo sounds like the best way, and aligns with this textbook diagram:
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/110999129/1d719af8-9073-4a41-a360-2be0abc13639)

**Comment by chiralcentre** [comment]
Thank you Prof for the response!
