### ISSUE TITLE
Merging A-gradle into master

### ISSUE THREAD

**Issue by jeong-jaeho** [nus-cs2103-AY2324S2/forum#315]
After completing up to A-packages, I've tried to merge the master into the add-gradle-support remote branch. It created a new commit with HEAD. But the new commit doesn't point to origin/HEAD this time.
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/109773933/20292046-8cd3-4f6d-97fb-a00fb93f3d46)

I've tried pushing both master and HEAD, but it meets the error.
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/109773933/3d3b7747-c1e7-4552-92fa-e8a8f27fae60)
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/109773933/5fe4074d-b538-4c63-afff-4bd564a98b75)

How do I resolve this issue?

**Comment by damithc** [comment]
@jeong-jaeho While waiting for peer inputs, let me share [this textbook topic](https://nus-cs2103-ay2324s2.github.io/website/se-book-adapted/chapters/gitAndGithub.html#branch-doing-multiple-parallel-changes:~:text=the%20feature1%20branch.-,To%20undo%20a%20merge,-%2C) which covers how to undo a merge.

**Comment by TarinPairor** [comment]
To keep changes made while in in the detached HEAD state maybe you can try to create a new branch, commit the changes, merge the changes again?

**Comment by choowengyan** [comment]
It seems like your local branch is not pointing to a branch but to a specific commit, so the current state is not suitable for pushing the changes directly. 

As such, try create a new branch and make some changes to your code. Then, add the changed files and commit your changes. You should be able to solve the issue after you push the new branch and switch back to master, and merge them into master branch.

**Comment by jeong-jaeho** [comment]
> It seems like your local branch is not pointing to a branch but to a specific commit, so the current state is not suitable for pushing the changes directly.
> 
> As such, try create a new branch and make some changes to your code. Then, add the changed files and commit your changes. You should be able to solve the issue after you push the new branch and switch back to master, and merge them into master branch.

@damithc Hello, should I try to undo merge first or attempt the suggestion on top of the current status?

**Comment by damithc** [comment]
> @damithc Hello, should I try to undo merge first or attempt the suggestion on top of the current status?

@jeong-jaeho Git mishaps usually have multiple ways to reverse.

Yes, one path you can try is to create a new branch at the current HEAD commit, and try to merge it back to master.

If that doesn't work, you can clone your fork to a new location and resume the project from that location.

**Comment by damithc** [comment]
@jeong-jaeho Also note:

You need to merge `add-gradle-support` to the `master` branch, not the other way around.
You need to fetch the remote branch to the local repo before merging it locally.
