### ISSUE TITLE
No main manifest attribute in Launcher.java jar file

### ISSUE THREAD

**Issue by TarinPairor** [nus-cs2103-AY2324S2/forum#316]
When I try to redo the steps of making the new jar file with IntelliJ/gradle from my duke.Launcher. I can't seem to make it run as it says: `no main manifest attribute`.

my jar file is running main from my `Launcher.java` file:
```
package duke;

import javafx.application.Application;


/**
 * A launcher class to workaround classpath issues.
 */
public class Launcher {
    public static void main(String[] args) {
        Application.launch(Main.class, args);
    }
}
```

There is a MANIFEST.MF class
```
Manifest-Version: 1.0
Main-Class: duke.Launcher
```

and my `build.gradle` has
```
application {
    mainClass.set("duke.Launcher")
}

```
I can run Launcher normally but not from the jar file. Any ideas why?

**Comment by aureliony** [comment]
Try running `./gradlew shadowJar` and use that jar file produced.

**Comment by zengzihui** [comment]
Your `build.gradle` should be correct, its same as mine one. I was able to get the jar file by using `./gradlew clean shadowJar` in the terminal, and after that use the jar file generated in the `build/libs/duke.jar`. Another jar file generated in this directory is not runnable for me as well.

**Comment by tankh99** [comment]
I've had this same issue too. See #301 if that helps

**Comment by azumieflare** [comment]
Running ```gradlew shadowJar``` then ```java -jar duke.jar``` in ```.\build\libs\``` seems to work fine. 
I'm not exactly sure why there is an extra ```ip-master.jar``` being created too but removing the line ```dependsOn("distZip", "distTar")``` from ```build.gradle``` seems to prevent the creation of that extra file.

**Comment by damithc** [comment]
@TarinPairor is the issue resolved?
