### ISSUE TITLE
Week 3 ip-4

### ISSUE THREAD

**Issue by Morninggloryyy** [nus-cs2103-AY2324S2/forum#317]
Hi! May I check in Week 3 ip-4, should I merge branches A-MoreOOP, A-Packages, A-Gradle, A-JUnit, A-Jar to master branch? if merging is needed, should I merge them one by one (e.g., merge "A-MoreOOP" to master once I finish commit for it) or merge them all at once (merge to master after all branches are done)? Also, I should tag after merging (like what is required in Level-7 and Level-8) right? Thank you in advance for your help! :))
<img width="618" alt="9eea6b9b951a4568f13a48254eb228c" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/156987743/250e247d-0a41-403b-a3c8-20ba7317ad2b">

**Comment by damithc** [comment]
> in Week 3 ip-4, should I merge branches A-MoreOOP, A-Packages, A-Gradle, A-JUnit, A-Jar to master branch? if merging is needed, should I merge them one by one (e.g., merge "A-MoreOOP" to master once I finish commit for it) or merge them all at once (merge to master after all branches are done)?

@Morninggloryyy one by one.

> Also, I should tag after merging (like what is required in Level-7 and Level-8) right?

Yes.

**Comment by Morninggloryyy** [comment]
@damithc Thank you so much for your clarification. Have a great week! :))
