### ISSUE TITLE
Navigation Bar Bug for Mobile Device

### ISSUE THREAD

**Issue by PallonCX** [nus-cs2103-AY2324S2/forum#318]
In our course website, usually the navigation bar for weekly schedule looks like below, where each component is clickable and each of them leads to different pages.

<img width="813" alt="Screenshot 2024-02-19 at 12 58 40 AM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/102943362/9877aaa6-51a2-4bd6-a7df-58ea75f6a2f3">

However, when the course website is accessed via mobile device (e.g. phone), sometimes part of the navigation bar is truncated, and it is not scrollable to access the remaining components. A demonstration of the scenario is shown below:

<img width="327" alt="Screenshot 2024-02-19 at 1 00 23 AM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/102943362/789c5509-b63d-49cf-9974-12ffd21b995d">

I suspect that this is due to the style setting (not sure the tech stack used is CSS or anything else) of the navigation bar, where the device's screen width is not sufficient to handle the width of navigation bar. Of course, it is possible that there is a way to access other components that I'm not aware of (except ticking the desktop site selection), please teach me the way in that case. Thank you!

**Comment by damithc** [comment]
@PallonCX Do the missing part become visible if you rotate the phone to landscape mode, or zoom out?

**Comment by PallonCX** [comment]
Without ticking the desktop site selection, I can't zoom out more, and zoom in doesn't show the missing part either.

When I rotate the phone to landscape mode, the missing parts are indeed visible. My concern is this may be a coincidence for my device due to my screen's length, but it may not work for other devices that have shorter screen length.

**Comment by damithc** [comment]
> When I rotate the phone to landscape mode, the missing parts are indeed visible. My concern is this may be a coincidence for my device due to my screen's length, but it may not work for other devices that have shorter screen length.

@PallonCX That's a fair observation. It may be possible to make this component more 'responsive' to narrow screen sizes. We'll have to look into this matter at a future time.

**Comment by PallonCX** [comment]
Alright, thanks prof!
