### ISSUE TITLE
Should we initialise variables with dummy value that will never be used?

### ISSUE THREAD

**Issue by PallonCX** [nus-cs2103-AY2324S2/forum#319]
In the Java coding standard guide provided below, we are encouraged to initialise variables with some values when we declare them.

<img width="992" alt="Screenshot 2024-02-19 at 1 08 47 AM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/102943362/3a243b2c-c529-4c88-968b-7d2260f554ee">

But in some cases such as follows:
```Java
int a = 0;
if (condition) {
    a = 1;
} else {
    a = 2;
}
System.out.println(a);
```

Regardless of the initialised value of the variable `a`, it will be overwritten in the if block, so is it still necessary to initialise `a` with some value?

Thank you in advance for helping!

**Comment by yisiox** [comment]
For this specific case, a ternary statement is probably most succinct and clear, and skips the initial value altogether.
```java
int a = (condition) ? 1 : 2;
```
But it does seem to fit somewhat into the case as explained by
> Sometimes it is impossible to initialize a variable to a valid value where it is declared. In these cases it should be left uninitialized rather than initialized to some phony value.

so it should be ok to leave it uninitialised, especially if it is set non trivially and `a` has no meaningful default value. However I think the guideline was probably aimed at non primitive types with no meaningful default, perhaps like:
```java
Command command;
if (condition) {
    someLogic();
    command = new redCommand();
} else {
    otherLogic();
    command = new blueCommand();
}
command.execute();
```

**Comment by PallonCX** [comment]
Ah, I was too focus on the codes and forgot to read the rationale. Thanks for pointing that out, it's clear to me now!
