### ISSUE TITLE
Query in Level-4

### ISSUE THREAD

**Issue by radeon2525** [nus-cs2103-AY2324S2/forum#32]
So far I have made 2 classes, which are Duke.java and Deadline.java. 

Task is a nested class inside Duke. I want to be able to correctly run this statement in Deadline.java. How can I do that:
                System.out.println("[D]" + " " + user_word.substring(9));
where user_word is the user input.

This line works in Duke.java but it wouldn't follow OOP principles, thus can someone tell how I can transfer this to Deadline.java

**Comment by UdhayaShan1** [comment]
You need not make task a nested class. It can be in its own file, Task.java

**Comment by radeon2525** [comment]
Alright understood, Thank you
