### ISSUE TITLE
In-video quiz bug

### ISSUE THREAD

**Issue by PallonCX** [nus-cs2103-AY2324S2/forum#320]
Some content videos will include quizzes (indicated with Q+ as shown below), which will stop the video progress automatically and pop out a quiz window. The video progress will be resumed only after users answer the quizzes.
<img width="180" alt="Screenshot 2024-02-19 at 1 17 00 AM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/102943362/d87cfe5b-f51f-4f53-abd4-b549987fd82e">

It is possible that the video progress is resumed without user answering the quizzes (I'm not sure with the trigger mechanism yet, but sometimes it happens when I refresh the page or long time inactive). When this happens, and when the second quiz comes (most of the videos have multiple in-video quizzes), even the user answered the second quiz, the video will not proceed because the system somehow detected that the first quiz is not answered.

When I encounter this bug, my solution is to drag the video progress bar to an earlier timing, so that the first quiz comes again, and I can answer it properly.

I understand that this bug is hard to replicated as the trigger mechanism is not cleared (from me) yet. If anyone has also faced this problem too, I hope my solution can help you, and please share your trigger mechanism too.

Thank you!

**Comment by damithc** [comment]
Thanks for reporting this, and for sharing the workaround, @PallonCX 
This is the behavior of the video delivery platform (Panopto) NUS uses, so it is beyond our control. Sorry about that.

**Comment by PallonCX** [comment]
Ah I see, thank you prof!
