### ISSUE TITLE
Alternative path VS Optional path

### ISSUE THREAD

**Issue by PallonCX** [nus-cs2103-AY2324S2/forum#321]
In Week 6 topic, we are introduced to sequence diagrams. Among that there are something called alternative paths and optional paths, as shown below:

<img width="701" alt="Screenshot 2024-02-19 at 1 34 35 AM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/102943362/dda1274e-b0d9-423d-95bf-3ce63c32afc1">
<img width="688" alt="Screenshot 2024-02-19 at 1 34 51 AM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/102943362/47e351af-4285-4c4f-82ae-7a9f983ff4c2">

My questions are:
1. Are they actually the same thing except that alternative paths **must have more than one** conditions (paths), and optional paths **must have only one** condition (path)?
2. Is there any rule related to whether the [condition] should be written on the left or right of the first activation bar (refer to the examples for alt and opt above)?

**Comment by tankh99** [comment]
I have a similar question actually. Is perhaps the below diagram not necessarily an optional path because it always happens at least once in the game? 
<img width="573" alt="Screenshot 2024-02-19 at 6 01 29 AM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/56617918/de08ae67-bee8-43f5-8a80-56932da4ebeb">

Whereas compared to an example where a user in an e-commerce store chooses a different product variant to check out.

**Comment by damithc** [comment]
> * Are they actually the same thing except that alternative paths **must have more than one** conditions (paths), and optional paths **must have only one** condition (path)?

@PallonCX technically, optional paths can be seen as a special case of alternative paths but that doesn't mean they are freely interchangeable. When drawing sequence diagrams, it is usually clear from the context which is a better fit for that context.

> * Is there any rule related to whether the [condition] should be written on the left or right of the first activation bar (refer to the examples for alt and opt above)?

No. It should be fine if the condition is given near the top edge of the frame.

**Comment by damithc** [comment]
> I have a similar question actually. Is perhaps the below diagram not necessarily an optional path because it always happens at least once in the game?
> <img alt="Screenshot 2024-02-19 at 6 01 29 AM" width="573" src="https://private-user-images.githubusercontent.com/56617918/305749732-de08ae67-bee8-43f5-8a80-56932da4ebeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMTA3MjYsIm5iZiI6MTcwODMxMDQyNiwicGF0aCI6Ii81NjYxNzkxOC8zMDU3NDk3MzItZGUwOGFlNjctYmVlOC00M2Y1LThhODAtNTY5MzJkYTRlYmViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDAyNDAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxMzQ0NTBkNDhlZTNhOTg4MTdkMDRmZjc2OGE1Mzc5MzZmMzE0ODliYzgzOWM1ZDg1ZGM2NjkzNWIzMTY0MTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jaDv4Pncb2O0RL7Pq_RGSvrEgHufVofsUofJyXa8HHo">

@tankh99 `at least one`, not `at least once`. Also, this constraint is applied to each travel through the frame, not the whole execution.

**Comment by PallonCX** [comment]
Alright, thank you for the clarification!
