### ISSUE TITLE
Typo in class website

### ISSUE THREAD

**Issue by E0735389** [nus-cs2103-AY2324S2/forum#322]
Inside level 10 collapsible box:

https://nus-cs2103-ay2324s2.github.io/website/schedule/week4/project.html#4-add-increments-as-branches-a-checkstyle-level-10-a-varargs

there is a typo (circled in orange in the image below) --- I think the `i` should be uppercase:

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/97508964/2b0f05b7-3813-403c-b6b3-8856c3f42d5a)

**Comment by damithc** [comment]
Fixed. Thanks for reporting this, @E0735389
