### ISSUE TITLE
Can you rename your project?

### ISSUE THREAD

**Issue by camille-readbean** [nus-cs2103-AY2324S2/forum#323]
Hi, my group would like to know if the name `TO BE CHANGED LATER` is something that will be with us for the rest of the course or do we have an option for changing it?

**Comment by damithc** [comment]
@camille-readbean did you mean the name of the tP? Yes, the tP name, target user, value proposition can be changed later. Just email us the new value any time.

**Comment by camille-readbean** [comment]
Thanks @damithc ! Hopefully we can come up with a proper name soon!
