### ISSUE TITLE
Can't run Launcher in JavaFX Tutorial Part 1

### ISSUE THREAD

**Issue by sarjinius** [nus-cs2103-AY2324S2/forum#324]
Hello, I've been running into this problem after following the steps in the tutorial.
Have anyone encountered this problem? If yes, how did you resolve it? Thank you!
![16A686A9-1384-41C8-B8FB-F7D58506B057](https://github.com/nus-cs2103-AY2324S2/forum/assets/122223898/6a077ad6-9d82-4c31-b7db-eb3cc848fa70)
![A1608AB0-4BC3-4D98-A3E9-08F8B5E6E081](https://github.com/nus-cs2103-AY2324S2/forum/assets/122223898/f9c23f79-e2a5-4e6e-843a-fc81666cb7c0)
![B12AC6FF-1734-49B2-A838-899FF4FC7042](https://github.com/nus-cs2103-AY2324S2/forum/assets/122223898/607e05ee-1595-450f-9c45-42212c6a8d15)

**Comment by taniatsq** [comment]
it might be an error in your classpath in build.gradle 

under application, try changing ```mainClass.set("seedu.duke.Duke")``` to ```mainClass.set("duke.Duke")```

**Comment by sarjinius** [comment]
Still doesn't work :(
![23840565-B6F3-4E86-B24D-96928FC24432](https://github.com/nus-cs2103-AY2324S2/forum/assets/122223898/904ff565-0154-4d9c-94bb-315ceec5533d)

**Comment by evedaktyl** [comment]
it might be that Launcher is your new entry point

under application, try changing
mainClass.set(“duke.Duke”) to
mainClass.set(“duke.Launcher”)

**Comment by sarjinius** [comment]
it doesn't work
FYI I'm using a MacBook with Apple M1 chip
![4A0ABA3C-9894-4A01-A415-859FD2EDC683](https://github.com/nus-cs2103-AY2324S2/forum/assets/122223898/4874efaa-cb8e-4a33-a088-e427914d0f34)

**Comment by c-wenlong** [comment]
what is your jdk version and name?

**Comment by damithc** [comment]
Some past issues that may be related https://github.com/nus-cs2103-AY2324S2/forum/issues?q=is%3Aissue+pipeline+

**Comment by sarjinius** [comment]
> what is your jdk version and name?
![Image 2-19-24 at 12 30 PM](https://github.com/nus-cs2103-AY2324S2/forum/assets/122223898/bc709b11-695d-41cb-a472-cedf3d5eba72)

**Comment by sarjinius** [comment]
Problem fixed after changing JDK in Project Structure, thanks!
