### ISSUE TITLE
Unknown Coding Standard Violation

### ISSUE THREAD

**Issue by Li-Zizhen** [nus-cs2103-AY2324S2/forum#325]
# May I know what's wrong with my code? I think it follows the standard.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/122284239/47f57deb-9b55-427a-85fd-23e62795bb4b)

**Comment by Jerome-j** [comment]
Hello i think the first word of your javadoc should be Executes, etc. 

`In method header comments, the first sentence should start in the form Returns ..., Sends ..., Adds ... etc. (not Return or Returning etc.)`

Refer to the Code Quality webpage for more info and examples

**Comment by Li-Zizhen** [comment]
Thank you, I didn't realize that.
