### ISSUE TITLE
A-AiAssisted Tag Issue

### ISSUE THREAD

**Issue by kailashgautham** [nus-cs2103-AY2324S2/forum#326]
Hi Prof @damithc,

I noticed that the A-AiAssisted tag is green in colour on the iP dashboard, but on the project website and the email we received, it says that it is an optional increment.

**Comment by damithc** [comment]
Thanks for reporting this, @kailashgautham That was a misconfiguration. Will correct it in the next dashboard update.

**Comment by damithc** [comment]
Fixed.
