### ISSUE TITLE
Codecov not updating even after setting repository secret

### ISSUE THREAD

**Issue by NeoHW** [nus-cs2103-AY2324S2/forum#327]
After setting up repository secret, and running the CICD pipeline. 
![Screenshot 2024-02-19 at 12 10 33 PM](https://github.com/nus-cs2103-AY2324S2/forum/assets/94470439/9cd8953a-2324-4930-9fad-98cfd40979c2)
The test coverage shows "No data" and there is no such output as expected below:
![Screenshot 2024-02-19 at 12 09 35 PM](https://github.com/nus-cs2103-AY2324S2/forum/assets/94470439/8f31eba5-e946-4814-8229-41ecfaad4b83)

Is anyone facing this issue too?

**Comment by camille-readbean** [comment]
This is to be expected see #309

**Comment by NeoHW** [comment]
> This is to be expected see #309

for #309: "the badge in README.md shows 75% coverage"

this is not the case here

**Comment by damithc** [comment]
@NeoHW You can let it be for now. Codecov is not critical for the tP and is not considered for grading. If the problem is not fixed even after there are few commits in your tP master branch, you can post here again.
