### ISSUE TITLE
Seeking clarification on the strictness of IP grading

### ISSUE THREAD

**Issue by cheahTJ** [nus-cs2103-AY2324S2/forum#329]
Hi all, may I check in the process of rectifying the deep nesting of my methods' implementation by changing the nested logic into a happy path which lengthen my method, would I be penalised on lengthy method now?

**Comment by damithc** [comment]
@cheahTJ the goal is not necessarily to reduce the LoC or the number of nesting levels of the method, but to increase the quality of the code. So, decide based on if you think a certain change would improve the code quality. Yes, sometimes there are tradeoffs, and you have to make a judgement call. 
Not to worry: there is no automatic penalty for exceeding a certain LoC or nesting depth. The evaluator/reviewer too will have to make a judgement call:  is this code of reasonable quality under the circumstances?
