### ISSUE TITLE
Query regarding tagging and A-TextUiTesting

### ISSUE THREAD

**Issue by itstrueitstrueitsrealitsreal** [nus-cs2103-AY2324S2/forum#33]
I've been working on my iP as outlined by the website, but had this nagging feeling that I didn't have to tag the level A-TextUiTesting (the level after 4 but before 5), as it did not follow the naming convention of previous or following levels, but I tagged it anyway. 

Should this be standard practice? Also, will it affect the grading of my iP?

Are there any teaching staff or students who care to weigh in about the issue? Any help is appreciated!

**Comment by damithc** [comment]
@itstrueitstrueitsrealitsreal The progress tracking scripts will not recognize tags that are not in the expected format. If a tag did not follow the given naming convention, you can create a new tag (following the correct naming format) now, and push them to your fork. Optional to delete the previous tags that are not in the expected format.

**Comment by itstrueitstrueitsrealitsreal** [comment]
Thanks for the clarification! Closing this issue.
