### ISSUE TITLE
Checkstyle error that can't be resolved

### ISSUE THREAD

**Issue by Lin-Shuang-Shuang** [nus-cs2103-AY2324S2/forum#330]
I have these imports on my file.
```
package lery;

import lery.task.Deadline;
import lery.task.Event;
import lery.task.Task;
import lery.task.TaskList;
import lery.task.Todo;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Scanner;
```

But when I run checkstyle I keep encountering this error.
`Import statement for 'java.io.IOException' is in the wrong order. Should be in the 'STANDARD_JAVA_PACKAGE' group, expecting not assigned imports on this line.`

I tried moving the import statements for java classes above the imports for lery, but IntelliJ does not seem to allow this and moved them back for me.

How do I resolve this error?

**Comment by LargeCrowd** [comment]
If you managed to setup Checkstyle properly using IntelliJ, it should tell you where the line is supposed to be placed. 

For me: IOException had to be the first import out of those starting with ```java``` 

i.e.
```
package catchat;

import java.io.IOException;
import java.util.Collections;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.geometry.Pos;
import javafx.scene.Node;
import javafx.scene.control.Label;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.HBox;
```

**Comment by aureliony** [comment]
You should configure IntelliJ to use a custom import order. There is a guide [here](https://stackoverflow.com/a/17194980).

**Comment by aureliony** [comment]
You should configure IntelliJ to use a custom import order. There is a guide [here](https://stackoverflow.com/a/17194980).

**Comment by Lin-Shuang-Shuang** [comment]
@aureliony This worked! Thanks!
