### ISSUE TITLE
Do we need to capitalize the first letter of explanation for parameter in java doc? 

### ISSUE THREAD

**Issue by Li-Zizhen** [nus-cs2103-AY2324S2/forum#331]
It is capitalized in the course website, but not in [Oracle's document](https://www.oracle.com/sg/technical-resources/articles/java/javadoc-tool.html)
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/122284239/ef644d86-112a-4eab-b768-b611f6f3422b)
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/122284239/6565dae0-82ec-451c-86b5-675354ab933d)

**Comment by damithc** [comment]
@Li-Zizhen In cases like this, follow our coding standard as much as possible. Capitalization for params does not have a universal standard; so, different style guides follow one or the other. 
In fact I've seen some JDK classes that uses capital letters. Even in AB3 both styles are used. So, it looks like this particular aspect of the coding standard is not followed very strictly, as it is not specified strictly either.

**Comment by Li-Zizhen** [comment]
Got it, thank you.
