### ISSUE TITLE
Does custom domain for github pages cause a problem for grading?

### ISSUE THREAD

**Issue by Dethada** [nus-cs2103-AY2324S2/forum#332]
I have github pages setup such that https://dethada.github.io/ redirects to https://dzhy.dev/ because I am using it to host my personal website. So https://dethada.github.io/ip redirects to https://dzhy.dev/ip

Will this be a problem for the grading?

**Comment by damithc** [comment]
> Will this be a problem for the grading?

@Dethada It's fine.
