### ISSUE TITLE
RepoSense icon is blurry

### ISSUE THREAD

**Issue by aureliony** [nus-cs2103-AY2324S2/forum#334]
The icon is blurry compared to the RepoSense website.

Expected:
![expected](https://github.com/nus-cs2103-AY2324S2/forum/assets/39163684/3ff247fb-d67a-4d4a-9efb-39c7caec2ef4)

Actual: 
![actual](https://github.com/nus-cs2103-AY2324S2/forum/assets/39163684/e8236824-b6de-4b25-b1bb-13bb2ab16837)

**Comment by damithc** [comment]
Thanks for raising this, @aureliony 
I've reposted it in https://github.com/reposense/RepoSense/issues/2128 for the RepoSense team to follow up
