### ISSUE TITLE
[Relative Path] My relative path to storage is not working when I run jar file on a different directory

### ISSUE THREAD

**Issue by c-wenlong** [nus-cs2103-AY2324S2/forum#335]
Here is the code snippet containing the file path.

`private static final String FILE_PATH = "./src/main/java/duke/memory/output.txt";`

**Comment by bachletuankhai** [comment]
You should create all parent folders by `file.getParentFile().mkdirs();` before creating the file if it is not found.

**Comment by UdhayaShan1** [comment]
If the jar file is run from Downloads for example, it is going to be unable to find this src/main/... (correct me if im wrong abt this)

Simply create a directory next to itself, with relative datapath like `private final String filePath = "data/task_lists.txt";`

**Comment by yisiox** [comment]
`.` means current directory, while `..` means parent directory.

If the program is executed from `C:/Users/User/Desktop/ip`, then `./src/main/java/duke/memory/output.txt` means to look for a output.txt in `C:/Users/User/Desktop/ip/src/main/java/duke/memory/output.txt`. Running it in `C:/Users/User/Documents` yields `C:/Users/User/Documents/ip/src/main/java/duke/memory/output.txt`.

#224 and #134 may be helpful as well.

**Comment by c-wenlong** [comment]
Thanks @bachletuankhai @UdhayaShan1 @yisiox for the help! :)
