### ISSUE TITLE
A-Assertions

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#336]
can someone explain what this is? Im not sure how to proceed doing this

**Comment by xinen26** [comment]
I personally added assertions in places of my code where I want to validate certain conditions. For example 
```
for (Task task : taskList) {
            assert task != null : "Task in TaskList cannot be null because operation cannot be carried out";
```

```
assert deletedTask != null : "Deleted task cannot be null because it can't be deleted";
```

**Comment by wxiaoyun** [comment]
Think of it as invariants you that must be true when your code executes to that line, but you want to enforce it during development. You can use assertion for that.

**Comment by baskargopinath** [comment]
thank you @xinen26

**Comment by guanquann** [comment]
For me, I made sure that user input cannot be empty

`assert !input.isEmpty() : "Input cannot be empty";`

**Comment by damithc** [comment]
> or me, I made sure that user input cannot be empty
> 
> `assert !input.isEmpty() : "Input cannot be empty";`

@guanquann what if the user hit enter without typing anything? Would that cause this assertion to fail?

**Comment by damithc** [comment]
For the record, assertions are covered in week 5 topics https://nus-cs2103-ay2324s2.github.io/website/schedule/week5/topics.html#W5-6
