### ISSUE TITLE
How to make the dimensions of the gui flexible

### ISSUE THREAD

**Issue by radeon2525** [nus-cs2103-AY2324S2/forum#337]
Right now my GUI seems to only be in one dimension, however if I expand or contract it, it doesn't adjust to according to the updated space. How can I fix this

**Comment by fy17ohhh** [comment]
For the children of `AnchorPane` in your `MainWindow`, you can set the edges of them to be anchored to an offset from the `AnchorPane`'s edges
<img width="949" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/103088135/32df6f88-183d-46d8-87ba-6dfc539b1c4e">

**Comment by radeon2525** [comment]
<AnchorPane maxHeight="-Infinity" maxWidth="-Infinity" minHeight="-Infinity" minWidth="-Infinity" prefHeight="600.0" prefWidth="400.0" xmlns="http://javafx.com/javafx/17" xmlns:fx="http://javafx.com/fxml/1" fx:controller="duke.MainWindow">
    <children>
        <TextField fx:id="userInput" layoutY="558.0" onAction="#handleUserInput" prefHeight="41.0" prefWidth="324.0" AnchorPane.bottomAnchor="1.0" />
        <Button fx:id="sendButton" layoutX="324.0" layoutY="558.0" mnemonicParsing="false" onAction="#handleUserInput" prefHeight="41.0" prefWidth="76.0" text="Send" />
        <ScrollPane fx:id="scrollPane" hbarPolicy="NEVER" hvalue="1.0" prefHeight="557.0" prefWidth="400.0" vvalue="1.0">
            <content>
                <VBox fx:id="dialogContainer" prefWidth="388.0" />
            </content>
        </ScrollPane>
    </children>
</AnchorPane>
This is my MainWindow so far, what should I do in this

**Comment by radeon2525** [comment]
This is my MainWindow, what should I do in this:

**Comment by radeon2525** [comment]
<AnchorPane maxHeight="-Infinity" maxWidth="-Infinity" minHeight="-Infinity" minWidth="-Infinity" prefHeight="600.0" prefWidth="400.0" xmlns="http://javafx.com/javafx/17" xmlns:fx="http://javafx.com/fxml/1" fx:controller="duke.MainWindow">
    <children>
        <TextField fx:id="userInput" layoutY="558.0" onAction="#handleUserInput" prefHeight="41.0" prefWidth="324.0" AnchorPane.bottomAnchor="1.0" />
        <Button fx:id="sendButton" layoutX="324.0" layoutY="558.0" mnemonicParsing="false" onAction="#handleUserInput" prefHeight="41.0" prefWidth="76.0" text="Send" />
        <ScrollPane fx:id="scrollPane" hbarPolicy="NEVER" hvalue="1.0" prefHeight="557.0" prefWidth="400.0" vvalue="1.0">
            <content>
                <VBox fx:id="dialogContainer" prefWidth="388.0" />
            </content>
        </ScrollPane>
    </children>
</AnchorPane>

**Comment by radeon2525** [comment]
This is my code in MainWindow, what should I do in this:

`<AnchorPane maxHeight="-Infinity" maxWidth="-Infinity" minHeight="-Infinity" minWidth="-Infinity" prefHeight="600.0" prefWidth="400.0" xmlns="http://javafx.com/javafx/17" xmlns:fx="http://javafx.com/fxml/1" fx:controller="duke.MainWindow">
    <children>
        <TextField fx:id="userInput" layoutY="558.0" onAction="#handleUserInput" prefHeight="41.0" prefWidth="324.0" AnchorPane.bottomAnchor="1.0" />
        <Button fx:id="sendButton" layoutX="324.0" layoutY="558.0" mnemonicParsing="false" onAction="#handleUserInput" prefHeight="41.0" prefWidth="76.0" text="Send" />
        <ScrollPane fx:id="scrollPane" hbarPolicy="NEVER" hvalue="1.0" prefHeight="557.0" prefWidth="400.0" vvalue="1.0">
            <content>
                <VBox fx:id="dialogContainer" prefWidth="388.0" />
            </content>
        </ScrollPane>
    </children>
</AnchorPane>`

**Comment by damithc** [comment]
> This is my code in MainWindow, what should I do in this:
> 
> `<AnchorPane maxHeight="-Infinity" maxWidth="-Infinity" minHeight="-Infinity" minWidth="-Infinity" prefHeight="600.0" prefWidth="400.0" xmlns="http://javafx.com/javafx/17" xmlns:fx="http://javafx.com/fxml/1" fx:controller="duke.MainWindow"> <children> <TextField fx:id="userInput" layoutY="558.0" onAction="#handleUserInput" prefHeight="41.0" prefWidth="324.0" AnchorPane.bottomAnchor="1.0" /> <Button fx:id="sendButton" layoutX="324.0" layoutY="558.0" mnemonicParsing="false" onAction="#handleUserInput" prefHeight="41.0" prefWidth="76.0" text="Send" /> <ScrollPane fx:id="scrollPane" hbarPolicy="NEVER" hvalue="1.0" prefHeight="557.0" prefWidth="400.0" vvalue="1.0"> <content> <VBox fx:id="dialogContainer" prefWidth="388.0" /> </content> </ScrollPane> </children> </AnchorPane>`

@radeon2525 Tip: You may want to use [fenced code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) to format your post for better readability.

**Comment by fy17ohhh** [comment]
> This is my code in MainWindow, what should I do in this:
> 
> `<AnchorPane maxHeight="-Infinity" maxWidth="-Infinity" minHeight="-Infinity" minWidth="-Infinity" prefHeight="600.0" prefWidth="400.0" xmlns="http://javafx.com/javafx/17" xmlns:fx="http://javafx.com/fxml/1" fx:controller="duke.MainWindow"> <children> <TextField fx:id="userInput" layoutY="558.0" onAction="#handleUserInput" prefHeight="41.0" prefWidth="324.0" AnchorPane.bottomAnchor="1.0" /> <Button fx:id="sendButton" layoutX="324.0" layoutY="558.0" mnemonicParsing="false" onAction="#handleUserInput" prefHeight="41.0" prefWidth="76.0" text="Send" /> <ScrollPane fx:id="scrollPane" hbarPolicy="NEVER" hvalue="1.0" prefHeight="557.0" prefWidth="400.0" vvalue="1.0"> <content> <VBox fx:id="dialogContainer" prefWidth="388.0" /> </content> </ScrollPane> </children> </AnchorPane>`

Set the anchor values for the children of `AnchorPane`, e.g.
`<TextField fx:id="userInput" layoutY="558.0" onAction="#handleUserInput" prefHeight="41.0" prefWidth="324.0" AnchorPane.bottomAnchor="1.0"  AnchorPane.bottomAnchor="1.0"/>`

**Comment by radeon2525** [comment]
Alright, I was able to fix this. Thank you
