### ISSUE TITLE
.jar file cannot run on a different OS

### ISSUE THREAD

**Issue by ChuaZiLong** [nus-cs2103-AY2324S2/forum#338]
I created the .jar file on a macbook pro and ran it and it worked fine.

But after I uploaded it to google drive and downloaded it on my windows desktop, I got an error.

Error: JavaFX runtime components are missing, and are required to run this application

**Comment by wxiaoyun** [comment]
You should upload the [shadowed jar file](https://nus-cs2103-ay2324s2.github.io/website/schedule/week6/project.html#4-submit-the-final-version-fri-feb-23rd-2359)

**Comment by ChuaZiLong** [comment]
Sorry here it is
[duke.jar.zip](https://github.com/nus-cs2103-AY2324S2/forum/files/14339005/duke.jar.zip)

**Comment by guanquann** [comment]
@ChuaZiLong I tried using your jar file and indeed it does not work on windows. Did you use Gradle shadow plugin?

**Comment by ChuaZiLong** [comment]
Yes I did, here is my build.gradle if it is helpful

```
plugins {
    id 'java'
    id 'application'
    id 'checkstyle'
    id 'com.github.johnrengelman.shadow' version '7.1.2'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

mainClassName = "duke.Duke"

application {
    mainClass.set("Launcher")
}


repositories {
    mavenCentral()
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
}

dependencies {
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.10.0'
    testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.10.0'
    String javaFxVersion = '17.0.7'

    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'linux'
}

test {
    useJUnitPlatform()
}

jar {
    manifest {
        attributes(
                'Main-Class': mainClassName
        )
    }
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
}

shadowJar {
    archiveFileName = 'duke.jar'
}
```

**Comment by damithc** [comment]
@ChuaZiLong how exactly did you build the jar file (i.e., which command or UI feature did you use to run the Gradle task?)

**Comment by ChuaZiLong** [comment]
i used gradle on intellij
double tap control -> ./gradlew clean shadowJar

**Comment by damithc** [comment]
@ChuaZiLong check if both JDK and JVM is set correctly, as specified [here](https://se-education.org/guides/tutorials/gradle.html#:~:text=Confirm%20the%20correct%20Java%20version%20is%20being%20used%20for%20Gradle). 
If they aren't, correct them, and build the JAR again.
If they are, perhaps share screenshots of the two settings?

**Comment by ChuaZiLong** [comment]
Oops I didn't configure the JVM properly. But even after changing it to the correct one and rebuilding using ./gradlew clean shadowJar, it cannot run on my Windows desktop and gives the same error as before.

Here are the JDK and JVM settings.

<img width="1440" alt="Screenshot 2024-02-20 at 2 48 16 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/122143961/5878e425-72a0-4963-bdd9-0f0f06147d0b">

<img width="1440" alt="Screenshot 2024-02-20 at 3 10 08 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/122143961/2be4b639-383a-4fd3-be6a-b0cbf2dcc7a9">

Here is the updated jar file if needed.
[duke.jar.zip](https://github.com/nus-cs2103-AY2324S2/forum/files/14340726/duke.jar.zip)

**Comment by damithc** [comment]
@ChuaZiLong A few more things to help narrow down:
1. Are you able to run the AB3 jar?
2. What's the output if you run `java -version` in a terminal?
3. Try running `./gradlew clean shadowjar` in a terminal to see if that makes a difference.

**Comment by ChuaZiLong** [comment]
1. Yes but I get 2 warnings 
Feb 20, 2024 4:12:01 PM seedu.address.Main main
WARNING: The warning about Unsupported JavaFX configuration below can be ignored.
Feb 20, 2024 4:12:01 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @6bc513e9'
2. (Windows) java 11.0.22 2024-01-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.22+9-LTS-219)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.22+9-LTS-219, mixed mode)
(Mac) openjdk 11.0.19 2023-04-18 LTS
OpenJDK Runtime Environment Zulu11.64+19-CA (build 11.0.19+7-LTS)
OpenJDK 64-Bit Server VM Zulu11.64+19-CA (build 11.0.19+7-LTS, mixed mode)
3. I got the same error as before

**Comment by sebin0817** [comment]
Hi, I got a similar error and my mistake was that my mainclass was not set properly. My Launcher is in java/duke/ui directory and had to specify the build.gradle file as such:

```
application {
    mainClass.set("duke.ui.Launcher")
}

shadowJar {
    archiveBaseName = "duke"
    archiveClassifier = null
    dependsOn("distZip", "distTar")
    mainClassName = "duke.ui.Launcher"
}
```

Perhaps double check your file structure?

**Comment by ChuaZiLong** [comment]
@sebin0817 nice it worked. Because my Launcher class is in Duke.java, I changed mainClassName to duke.Launcher instead and now it can run on Windows. Thanks everyone for the help.
