### ISSUE TITLE
Need help for pull request

### ISSUE THREAD

**Issue by Emberlynn-Loo** [nus-cs2103-AY2324S2/forum#339]
I merged and pushed both branches A-assertions and A-CodeQuality without making pull requests. I only realised now after everything is merged to the master branch that I was supposed to make pull requests. Is there any possible way to undo what I did so I can make pull requests this time or should I just upload new branches.

**Comment by damithc** [comment]
@Emberlynn-Loo it's OK, let them be. You can use pull requests for some other changes you do in the future. As long as you have merged _some_ branch in your fork using a PR, it should be fine (as you have achieved the learning objective already).

**Comment by Emberlynn-Loo** [comment]
Thank you! :)
