### ISSUE TITLE
Small typo in template for seeking help

### ISSUE THREAD

**Issue by itstrueitstrueitsrealitsreal** [nus-cs2103-AY2324S2/forum#34]
Hi, was browsing the different tags in the forum when I came across this typo:

Instead of:
> Template for seekling help

It should be:
>Template for ~~seekling~~ **seeking** help

Here's a screenshot for reference!
<img width="708" alt="Screenshot 2024-01-22 at 6 10 36 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/120318851/48331ac1-3cc3-4094-8db9-fd22da292ed7">

Thanks in advance to the teaching staff for maintaining the resources we have! 👍👍👍

**Comment by damithc** [comment]
Thanks for the report, @itstrueitstrueitsrealitsreal 
Fixed
