### ISSUE TITLE
Branch-9 and branch-10 not reflected

### ISSUE THREAD

**Issue by AwJoey** [nus-cs2103-AY2324S2/forum#340]
Hi Prof, 
I have completed level-9 and level-10, and created the branches. But it is not reflected in the iP dashboard. I have tried pushing the branches again, but it still does not work. May I seek assistance on what could be the issue?

Thank you!

Best regards,
Joey

**Comment by damithc** [comment]
@AwJoey See if the [this troubleshooting tip given at the top of the iP dashboard](https://nus-cs2103-ay2324s2.github.io/dashboards/contents/ip-progress.html#:~:text=Why%20is%20an%20increment%20related%20to%20a%20branch%20not%20green%3F) helps.

Let us know if that didn't work.

**Comment by AwJoey** [comment]
It has been resolved, thank you! :)
