### ISSUE TITLE
Name of iP

### ISSUE THREAD

**Issue by sindhurajain** [nus-cs2103-AY2324S2/forum#344]
Week 6's project tasks say we need to ensure that the name of the product name is not Duke. Can I leave my class names as Duke, DukeException, etc, as long as a different name appears in the GUI?

**Comment by damithc** [comment]
> Week 6's project tasks say we need to ensure that the name of the product name is not Duke. Can I leave my class names as Duke, DukeException, etc, as long as a different name appears in the GUI?

@sindhurajain Yes, that should be fine, although not ideal.

**Comment by sindhurajain** [comment]
thanks!
