### ISSUE TITLE
Possible bug in in-video quizzes: the "close" button at the top right corner should disappear upon completion

### ISSUE THREAD

**Issue by logical-1985516** [nus-cs2103-AY2324S2/forum#346]
I understand that clicking the "close" button prevents users from skipping past the quiz, if they have not done the quiz yet.

However, if a user has completed a quiz and wants to exit the quiz and continue with the video, it does not make sense for the user to click the "close" button.

As someone who is used to clicking the top right corner to close a quiz, I find this behaviour confusing and unintuitive. I would like to suggest that the "close" button should disappear if the user has completed the quiz, in both the results page and the review page. Does anyone feel the same way too?

If you want to get a clearer idea, this is a video of me trying to close the quiz and resume the video but failing to do so. (This also happens in the review page)
https://github.com/nus-cs2103-AY2324S2/forum/assets/107944536/5b2e5cb8-0952-4eed-8ee8-0d48e816d49d

**Comment by damithc** [comment]
@logical-1985516 I agree that the video player has some quirky behavior but it's not in our control. The behavior comes from a third-party platform NUS is using for video delivery. We are simply embedding their video player in our website.

**Comment by logical-1985516** [comment]
Noted with thanks, Prof Damith. I will close this issue now.
