### ISSUE TITLE
A-CodeQuality

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#347]
Im currently working on A-CodeQuality and have adjusted my code to the best of my knowledge, if possible could anyone take a look and let me know if theres any big issues i have in terms of code quality? 

This is the link to my IP:
https://github.com/bgopi23/ip

**Comment by damithc** [comment]
@bgopi23 perhaps it is easier if you post the link to your iP PR instead. It's easier to comment on a PR rather than a repo.

**Comment by yisiox** [comment]
@bgopi23 I added a PR review; mostly nits. Hope it is helpful.

**Comment by baskargopinath** [comment]
@yisiox thank u

**Comment by baskargopinath** [comment]
@damithc prof how do i do what you said?

**Comment by damithc** [comment]
> @damithc prof how do i do what you said?

@bgopi23 I'm referring to the PR you created in an earlier week.

You can go to the full list of PRs [here](https://github.com/nus-cs2103-AY2324S2/ip/pulls), locate your PR, and post the link here.

**Comment by baskargopinath** [comment]
@damithc thank u prof
