### ISSUE TITLE
[tP] Should feature list contain "nice-to-have" features

### ISSUE THREAD

**Issue by Javiery3889** [nus-cs2103-AY2324S2/forum#349]
Our group was wondering should the feature list for v1.2 consist of only must-have features that we want to implement for that iteration or can it contain features that we might not implement in this iteration, i.e. nice-to-have features.

If included, must the feature specification contain the specifications of these nice-to-have features as well? Thank you!

**Comment by damithc** [comment]
@Javiery3889 It's good enough for the v1.2 feature specification to contain just the must-have features. Optional to include nice-to-have features.
