### ISSUE TITLE
CredentialHelperSelector when push to remote repo

### ISSUE THREAD

**Issue by Li-Zizhen** [nus-cs2103-AY2324S2/forum#35]
I follow the steps on W2.4e Tools → Git and GitHub → push: Uploading data to other repos, and when I want to push my repo to my remote repo, a page pop-up asking me to select one option from CredentialHelperSelector, I select <no helper> and error show up. May I know how to solve this? Thank you.

**Comment by camille-readbean** [comment]
Can you show us the error or what error it is?

**Comment by Li-Zizhen** [comment]
I selected no helper, and the error is:
git -c diff.mnemonicprefix=false -c core.quotepath=false --no-optional-locks push -v --tags Myfork master:master
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.

**Comment by camille-readbean** [comment]
I assume you are on Windows and installed the Git Credential Manager
You have to use a helper and login with github 

https://docs.github.com/en/get-started/getting-started-with-git/caching-your-github-credentials-in-git?platform=windows#git-credential-manager

**Comment by damithc** [comment]
For those using SourceTree [https://se-education.org/guides/tutorials/sourcetree.html](https://se-education.org/guides/tutorials/sourcetree.html#connecting-sourcetree-to-your-github-account:~:text=Connecting%20Sourcetree%20to%20Your%20GitHub%20Account)

**Comment by damithc** [comment]
> I select and error show up.

@Li-Zizhen It might help if you can share which option did you select, and what was the error?

**Comment by lhy-hoyin** [comment]
Hi @Li-Zizhen, I am from a senior batch (dropping by the forum to help out where I can).

From what I am seeing, it seems that you are able to resolve the issue on your own by choosing the "manager" option from the list provided in the CredentialHelperSelector. Rather, you are unsure if its secure to choose "manager" as the helper.

I believe that the options can all be considered safe. The various options are just a choice of how you wish to store your credentials.

For example, according to [Git](https://github.com/GitCredentialManager/git-credential-manager), 
> To use a helper, you must first select one to use. Git currently includes the following helpers:
> 
> cache
> Cache credentials in memory for a short period of time. See [git-credential-cache[1]](https://git-scm.com/docs/git-credential-cache) for details.
> 
> store
> Store credentials indefinitely on disk. See [git-credential-store[1]](https://git-scm.com/docs/git-credential-store) for details.

Furthermore, [Git Credential Manager](https://github.com/git-ecosystem/git-credential-manager) is recognised as one of the [list of credential helpers](https://git-scm.com/doc/credential-helpers).

**Comment by lhy-hoyin** [comment]
On another note, (assuming that you are using Windows), if you have the issue of the _CredentialHelperSelector_ or the _Git Credential Manager for Windows_ popping up often to prompt for a username and/or password, you can see this [link](https://community.atlassian.com/t5/Sourcetree-questions/Git-Credential-Manager-for-Windows-Popups/qaq-p/579905) for a solution.

**Comment by Li-Zizhen** [comment]
Thanks for helping me out!
