### ISSUE TITLE
IP Grading standard for Git conventions

### ISSUE THREAD

**Issue by Ella-e** [nus-cs2103-AY2324S2/forum#350]
In the implementation section for the grading scheme of IP, under the Reasonable code quality part, it says that 'Git conventions' will be checked. May I check that what are things to be checked for this category. Will all the past commit messages be checked or only the most recent ones?

**Comment by damithc** [comment]
@Ella-e we'll check only the recent few commits.

**Comment by Ella-e** [comment]
I see, thank you prof.
