### ISSUE TITLE
[tP] When are we allowed to commit on the team repository directly?

### ISSUE THREAD

**Issue by E0735389** [nus-cs2103-AY2324S2/forum#351]
I notice that there is a team repository, and each person also has their own fork, so there are two ways to suggest a change:

* commit to the team repository directly,
* commit to the personal fork, then pull request to the team repository.

I assume that the latter is preferred. Is there any circumstance where we're allowed to do the former? (I already do that in order to do the step of making a team pull request before noticing that we're supposed to create individual forks in the next step)

**Comment by damithc** [comment]
@E0735389 In the tP you are expected to follow the forking workflow. More details [here](https://nus-cs2103-ay2324s2.github.io/website/admin/appendixE-gitHub.html#tp-workflow:~:text=Follow%20the%20forking%20workflow%20in%20your%20project). Will also be covered in an upcoming course briefing video (to be released by this Friday) covering the remainder of the tP.

**Comment by E0735389** [comment]
Should I be doing anything about the past commit? (I can just `push --force` it back but I suppose the easier way is just I follow the forking workflow from now on?)

**Comment by damithc** [comment]
> Should I be doing anything about the past commit? (I can just `push --force` it back but I suppose the easier way is just I follow the forking workflow from now on?)

@E0735389 Yes, you can follow the required workflow from now. No need to edit past commits.
