### ISSUE TITLE
TP tutorial: Adding a command

### ISSUE THREAD

**Issue by guanquann** [nus-cs2103-AY2324S2/forum#352]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/76832850/ff55de00-bcdb-4ec9-9507-8079f7de2852)

The very last line should be `return String.format(message, Messages.format(personToEdit));` instead so that it does not return the object.

**Comment by tankh99** [comment]
Hi, I've actually checked and yes, it outputs the object string rather than what is shown on the guide. We should be using `Messages.format()`

**Comment by damithc** [comment]
Thanks for checking, @tankh99 and for reporting this, @guanquann 
Will take note of this, to be fixed in the upstream repo later.
