### ISSUE TITLE
Merge and push inquiry

### ISSUE THREAD

**Issue by jeong-jaeho** [nus-cs2103-AY2324S2/forum#353]
I get that after you create a branch and try to merge the branch back to master, you should push both the master and the branch. 
My question is, whenever you create a new branch and repeat the process above, do you need to push all the created branches so far, even including the ones not relevant in this specific merge?
For instance, Level 7, 8 branches weren't involved in this merge. Should I include them as well when pushing?
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/109773933/1c322980-1e47-453c-a84b-1a0467b45e85)

**Comment by guohuang88** [comment]
If your branch-Level-7 and branch-Level-8 were pushed to remote(github) previously and there is no new changes in them then I do not think there is a need to include them.
If I am not wrong, when you push, it means that you want your local changes/commits to be updated on the remote.
