### ISSUE TITLE
Are we allowed to change how our tP code works?

### ISSUE THREAD

**Issue by tankh99** [nus-cs2103-AY2324S2/forum#354]
Let's say I don't like the way the tP codebase does certain things. Are we allowed to refactor it? Are there any potential downsides to doing so aside from the obvious "things don't work anymore"?

**Comment by damithc** [comment]
@tankh99 Yes, you are encouraged/welcome to improve AB3, both internal design as well as external behavior. But do ensure you have the approval of your team before merging such changes.

**Comment by tankh99** [comment]
Got it, thanks!
