### ISSUE TITLE
Tag not being updated on IP progress tracker

### ISSUE THREAD

**Issue by ararchch** [nus-cs2103-AY2324S2/forum#355]
**Context**: I finished my `A-CodeQuality` improvements last week. However, I tagged the wrong commit with the `A-CodeQuality` tag and pushed this change to the remote fork repo.

In an attempt to rectify this error, I thought a natural thing to do would be to delete the current tag and create a new one on the correct commit. I googled and came across a post that suggested that I can delete a tag by using the following command:
`git push --delete origin tagname`

So I used this command, and I think I ended up making it worse because the tag is deleted from the remote repo (I.e. when I visit [github.com/ararchch/ip/tags](github.com/ararchch/ip/tags) I cannot see the tag), but I still am unable to create a new tag with the name `A-CodeQuality` on the correct commit.  

When i run: `git tag -a A-CodeQuality bee38a1` where `bee38a1` is my commit id, I get the error: `fatal: tag 'A-CodeQuality' already exists`

As such, I think the progress tracker is also unable to see the tag and hence reflect my actual level of completion.
I would appreciate any advice on what to do next because I do seem to have dug myself into a hole here.

Thank you so much!

**Comment by tankh99** [comment]
Go to your repository and click on Tags.

Delete the tag on the repository. And then also delete the tag locally on your computer with `git tag -d tag-name`. Then checkout to master and re-add your tags via Git CLI, `git tag -a A-CodeQuality`

**Comment by damithc** [comment]
@ararchch As far as the iP dashboard is concerned, the tag simply needs to be in your fork and reachable from your master branch. It doesn't care which commit the tag is in.
