### ISSUE TITLE
Error: Could not find or load main class Duke

### ISSUE THREAD

**Issue by ZhiWei1010** [nus-cs2103-AY2324S2/forum#357]
Hi, Everytime I run runtest.sh, this error comes out:

Error: Could not find or load main class Duke
Caused by: java.lang.NoClassDefFoundError: duke/Duke (wrong name: Duke)

<img width="1339" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/60460444/61d2f1e2-1d81-44d4-a756-8c74c31a3997">

Any Ideo where I went wrong? Any help is appreciated!

**Comment by yisiox** [comment]
@ZhiWei1010 You can try 
1. delete the contents of `/bin`
2. change line 16 to `if ! javac -cp ../src/main/java -Xlint:none -d ../bin ../src/main/java/duke/*.java`
3. change line 23 to use the fully qualified name of the class `java -classpath ../bin duke.Duke < input.txt > ACTUAL.txt`
4. run `runtest.sh` again.

**Comment by fy17ohhh** [comment]
try `java -classpath ../bin duke.Duke < input.txt > ACTUAL.TXT` instead

**Comment by ZhiWei1010** [comment]
Hi thanks for the help @yisiox , I actually deleted the whole file as It is not needed anymore! Thank you regardless!
