### ISSUE TITLE
Is it still recommended to use branches and PRs in solo repos?

### ISSUE THREAD

**Issue by tankh99** [nus-cs2103-AY2324S2/forum#359]
In repositories that we know we are going to be working on solo, like our forks for the team project. How much more beneficial is it to use branches and PRs to merge our own code vs just pushing straight to master?

**Comment by sun-ruiheng** [comment]
In my opinion, it becomes less crucial but still incredibly useful. I can think of three main benefits:

1. Experimentation in several different directions, in parallel, while keeping a functional main branch safe.
2. There are automated CI/CD tools that activate on accepted PRs, including testing and deployment, so it would be good to make use of these. Especially in a big project where a careless push might end up disastrous.
3. Reviewing your own PR through the powerful "diffing" visualiser on GitHub is useful for catching bugs and reasoning about why you made certain changes.

However, I personally think layers of PR over other PRs might be too confusing for amateurs like me. Imagine reasoning about PRs from your fork's branches to your fork's master vs PRs from your fork to the main repo... :(

**Comment by tankh99** [comment]
Thanks for this clarification! I also do feel that making PRs is better. Because in the case you make an error, it's easier to revert. I'll close this now
