### ISSUE TITLE
Do we need to preserve original features after refactoring?

### ISSUE THREAD

**Issue by sun-ruiheng** [nus-cs2103-AY2324S2/forum#362]
Must the latest (submitted) version of iP retain every single feature along the way?
For example, there was a feature many weeks ago where we can load previously defined tasks from our storage. After implementing a GUI, this feature is lost unless we deliberately incorporate it again.

**Comment by tankh99** [comment]
Hi, I think it should be expected to maintain the storage feature of the iP. By right it shouldn't be difficult to do because you should be piping the string output from the original code into the new GUI

**Comment by damithc** [comment]
@sun-ruiheng yes, the iP features are cumulative, unless a new feature is specifically replacing a previous one (e.g., the GUI replaces the text UI).
Yes, as @tankh99 said, saving/loading feature should be retained.

**Comment by baskargopinath** [comment]
yes

**Comment by sun-ruiheng** [comment]
Uh oh
