### ISSUE TITLE
Committing fixes after final release

### ISSUE THREAD

**Issue by smolegz** [nus-cs2103-AY2324S2/forum#363]
I noticed that my JUnit tests had some bugs and I've already rectified and committed the new changes.

Question is, do we need to re-release our .jar file if we committed some minor code fixes (e.g. test code that failed)?

Thanks in advance for the response!

**Comment by damithc** [comment]
@smolegz You can do a new release if there is a change in the JAR file's behavior. Otherwise no need.

**Comment by smolegz** [comment]
Thank you Prof for the clarification. Will proceed to close this thread 🙂
