### ISSUE TITLE
Level-4

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#364]
The way I thought about the tasks is that todo is the most basic type of task and deadline is just a todo (with a date to finish by) and event is just a todo (with a start and end date)

Bcoz of this, I designed my code with 3 classes
Todo, Deadline (extends todo) and event (extends Todo)

However I was reading all the levels again from the beginning and noticed in level 4 that there should be a task class and Todo, Deadline and event should extend from Task instead.

Is is ok for me to leave it as it is? Or do I need to refactor my code completely for this

**Comment by damithc** [comment]
> Is is ok for me to leave it as it is?

@bgopi23 Yes, that's fine too.

**Comment by baskargopinath** [comment]
understood, thank u prof @damithc
