### ISSUE TITLE
As a Silicon Mac user, my jar file would not work right on my Window peers' computers. 

### ISSUE THREAD

**Issue by belligerentbeagle** [nus-cs2103-AY2324S2/forum#365]
Hi there, during development, I had to use Java 11 'Azul' version because I am using a silicon mac machine.

My Jar file runs without issue on a friend who also uses silicon mac, but when it comes to friends with Windows, it doesn't open. This error appears. What should we do in this case? It does not quite make sense to have my Windows friends download Java 11 Azul. 

```
$java --version
java 11.0.21 2023-10-17 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.21+9-LTS-193)
Java HotSpot(™) 64-Bit Server VM 18.9 (build 11.0.21+9-LTS-193,
mixed mode)

$java -jar snoopy.jar
Error: JavaFX runtime components are missing, and are required to run this application
```

Any help is appreciated. TIA!

Link to release .jar attached here: https://github.com/belligerentbeagle/ip/releases/tag/A-Release

**Comment by aureliony** [comment]
In your build.gradle, change `mainClass.set("Main")` to `mainClass.set("Launcher")`

**Comment by belligerentbeagle** [comment]
Thank you @aureliony , it worked!
