### ISSUE TITLE
Fulfilling Use-GMFD

### ISSUE THREAD

**Issue by TopKec** [nus-cs2103-AY2324S2/forum#367]
Might be a really dumb question, but I was checking through the ip-code dashboard and I noticed that this is marked as not completed for me.

As far as I can tell, I did make the relevant changes to my description, and I think I've gotten everything listed as the requirements. [requirements here](https://nus-cs2103-ay2324s2.github.io/website/schedule/week4/project.html#1-use-gfmd-in-the-pr-description)

Did I miss out on something obvious?

**Comment by Jerome-j** [comment]
Hi friend,
I think you forgot to create your GFMD here: https://github.com/nus-cs2103-AY2324S2/ip/pull/306

You can simply click on edit to create it now

<img width="739" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/49815108/e5d8d6fa-f40e-4ba7-95a8-c355f8798998">

**Comment by baskargopinath** [comment]
@TopKec ur supposed to update the description of the IP Pull request. i think u did it on ur README by accident

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/73015364/b82d0217-520e-4df5-bdfc-ce39b7b102d4)
i think if u follow this it should turn green after ur done

**Comment by TopKec** [comment]
Can't believe I missed that haha! Sorry for all the trouble! Thanks for the quick and prompt response all!
