### ISSUE TITLE
[Merging-PR]

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#368]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/73015364/6ad560c4-2dc6-4c63-a666-ed09c0237aa6)
is this the correct place to merge?

i commited my CodeQuality branch to github
now i create a pull req to master branch of my own ip?

**Comment by theman-oj10** [comment]
Hi,
Yes, this is the right way to merge. After fixing any merge conflicts, it is recommended to select `Create merge commit `when finalizing the merge.

**Comment by tzaph** [comment]
> ![image](https://private-user-images.githubusercontent.com/73015364/306692495-6ad560c4-2dc6-4c63-a666-ed09c0237aa6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MzY2ODUsIm5iZiI6MTcwODUzNjM4NSwicGF0aCI6Ii83MzAxNTM2NC8zMDY2OTI0OTUtNmFkNTYwYzQtMmRjNi00YzYzLWE2NjYtZWQwOWMwMjM3YWE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDE3MjYyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlYjNkY2M4YjkwZWJhOWI3MGQ5YzE1ZWRmMThlYmIwZmIyNDEyYmNmNzIzMTU5YjY1MjEyNGI5Zjg3ZDg4NmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VX5V12QutfBTPcwuGrfNJHzR8ojS33a9WVsCsyS0-ow) is this the correct place to merge?
> 
> i commited my CodeQuality branch to github now i create a pull req to master branch of my own ip?

Yes indeed, make sure that the master at the left (the branch you are merging to) belongs to your own repository. You should be able to see which branch belongs to which repo by clicking on the drop down list.

**Comment by baskargopinath** [comment]
thanks @tzaph @theman-oj10
