### ISSUE TITLE
What is "the classpath issue"?

### ISSUE THREAD

**Issue by E0735389** [nus-cs2103-AY2324S2/forum#369]
The launcher class has the following comment

```
/**
 * A launcher class to workaround classpath issues.
 */
```

But what is the issue exactly? The SE tutorial does not explain anything.

Of course I observe that if we put the `main` function in the `Duke` class directly then it will raise the classpath issue, but what exactly does the launcher do to avoid the error?

The documentation for `.launch()` isn't illuminating either.

https://docs.oracle.com/javase/8/javafx/api/javafx/application/Application.html#launch-java.lang.Class-java.lang.String...-

Meanwhile, the HelloFX application **can** put the main method in the same class as the `start` method:

https://github.com/openjfx/samples/blob/master/HelloFX/Gradle/hellofx/src/main/java/HelloFX.java#L19

**Comment by seanfirefox** [comment]
Hi, I am a senior from a previous batch.

Without logs on exactly what are the classpath issues that arise when you place the launch function inside `Duke.class`, I can only provide a rough guess. `Application.launch` ensures that the JavaFX Application runs on the Application thread judging from the decompiled Application class and the documentation.

Also, the `launch` function you see in the HelloFX Application is different from the one `Launcher.java` uses which takes in a class as an argument (Remember method overriding). Perhaps you can try to call `launch(args)` or `launch()` directly to see if it works.

As for what the launcher does exactly to avoid the error, the code below is the launch function that `Launcher.java` is calling.
```
public static void launch(Class<? extends Application> var0, String... var1) {
        LauncherImpl.launchApplication(var0, var1);
}
``` 
After more tracing, looking at the `launchApplication` function in the `LauncherImpl` class, it calls a function `setupJavaFXClassLoader` which presumably fixes the classpath error.
```
private static ClassLoader setupJavaFXClassLoader(File var0, String var1) {
        try {
            File var2 = var0.getParentFile();
            ArrayList var3 = new ArrayList();
            String var4 = var1;
            int var5;
            if (var1 != null) {
                for(; var4.length() > 0; var4 = var4.substring(var5 + 1)) {
                    var5 = var4.indexOf(" ");
                    File var7;
                    if (var5 < 0) {
                        var7 = var2 == null ? new File(var4) : new File(var2, var4);
                        if (var7.exists()) {
                            var3.add(fileToURL(var7));
                        } else if (verbose) {
                            System.err.println("Class Path entry \"" + var4 + "\" does not exist, ignoring");
                        }
                        break;
                    }

                    if (var5 > 0) {
                        String var6 = var4.substring(0, var5);
                        var7 = var2 == null ? new File(var6) : new File(var2, var6);
                        if (var7.exists()) {
                            var3.add(fileToURL(var7));
                        } else if (verbose) {
                            System.err.println("Class Path entry \"" + var6 + "\" does not exist, ignoring");
                        }
                    }
                }
            }

            if (!var3.isEmpty()) {
                ArrayList var9 = new ArrayList();
                var4 = System.getProperty("java.class.path");
                int var10;
                if (var4 != null) {
                    for(; var4.length() > 0; var4 = var4.substring(var10 + 1)) {
                        var10 = var4.indexOf(File.pathSeparatorChar);
                        if (var10 < 0) {
                            var9.add(fileToURL(new File(var4)));
                            break;
                        }

                        if (var10 > 0) {
                            String var12 = var4.substring(0, var10);
                            var9.add(fileToURL(new File(var12)));
                        }
                    }
                }

                var9.addAll(var3);
                URL[] var11 = (URL[])var9.toArray(new URL[0]);
                if (verbose) {
                    System.err.println("===== URL list");

                    for(int var13 = 0; var13 < var11.length; ++var13) {
                        System.err.println("" + var11[var13]);
                    }

                    System.err.println("=====");
                }

                return new URLClassLoader(var11, ClassLoader.getPlatformClassLoader());
            }
        } catch (Exception var8) {
        }

        return null;
    }
```

If you are interested on finding out more, you can try `Crtl+B` on the launch function in `Intellij` to find the initial declaration of the function in the decompiled class and trace the `LauncherImpl` class.

**Comment by garylow2001** [comment]
Hi @E0735389 , I am a senior from the previous batch dropping by to help.

When you have multiple classes in a project and you try to run the Java application from the command line, Java needs to know which class contains the main method to start the application. This is determined by the classpath.

If you have a class with the main method (Duke), but it's not the entry point specified in the classpath or it's not properly specified, Java won't be able to find and execute it. The launcher class is a workaround to ensure that the main method is invoked correctly, regardless of any potential classpath issues. (The exact details of how this works I am also unsure)

In JavaFX applications, the main method is in Application (or the class that extends it), and it's invoked indirectly by the JavaFX runtime when the application is launched. This is why you can have the main method in the same class as the start method in JavaFX applications without encountering classpath issues.

Recalling how I have set up my JavaFX project, I have a Launcher.java which contains the main method, which serves as the entry point for my application. Inside the main method of Launcher.java, `Application.launch(Main.class, args)`; is called (https://docs.oracle.com/javase/8/javafx/api/javafx/application/Application.html). This is invoking JavaFX's application launcher and specifying that the Main class should be used as the starting point for the JavaFX application. I then have a Main.java which extends Application, making it a JavaFX application class that overrides the start method, which is where the JavaFX application is initialized and displayed.
This allows Launcher.java to handle the launching of the JavaFX application, while Main.java focuses on setting up the JavaFX UI and initializing other logic.

**Comment by lhy-hoyin** [comment]
Hello @E0735389,
I hope the comments from your seniors are able to clarify your doubts. If so, perhaps you can close this issue. Otherwise, perhaps you can ask specific questions on what else you are not too sure about.
