### ISSUE TITLE
github desktop is asking me how am i planning to use this fork when i tried to clone it into my computer

### ISSUE THREAD

**Issue by bgopi23** [nus-cs2103-AY2324S2/forum#37]
its asking me to choose between
- contribute to parent project 
- for my own purposes

which should i choose?

**Comment by Jerome-j** [comment]
Hi, I just tried it earlier. Did you remember to uncheck the

**Comment by bgopi23** [comment]
i did all the insturctions stated like unchecking the copy master branch only option, and then going into the settings of the fork and enabling the issue tracker.

then i installed github desktop and tried to clone the fork onto my computer and got this prompt

**Comment by Jerome-j** [comment]
Ohhh maybe cos I did not use GitHub desktop to clone the fork. I used IntelliJ to clone the fork,

**Comment by damithc** [comment]
@bgopi23 The two 'officially' supported ways to perform Git operations are via SourceTree or using Git CLI, although we don't prohibit use of other Git clients. The issue you encountered is specific to GitHub Desktop, so let's see if any others using the same software can pitch in with a suggestion (I suspect it doesn't matter what you choose for that option).

On a related note, we also have the following caution:
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/c9df3f95-9e77-448e-8012-9bd888e89c5a)

**Comment by bgopi23** [comment]
@damithc i dont think it matters also since the option is optional, so i just skipped it and everything seems fine. i will update if i face any issues but i think it should be ok
