### ISSUE TITLE
Git-Standard

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#371]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/73015364/bcb1b219-9d50-4a7e-8254-10b9dce2d0bf)
for git standard do i leave space between title and body?

**Comment by damithc** [comment]
@bgopi23 I expect there is no need, as this UI clearly differentiates between the subject and the body, and is likely to auto-add a blank line between the subject and the body when it saves the commit message in Git.

**Comment by baskargopinath** [comment]
ok, thanks prof @damithc
