### ISSUE TITLE
Typo on link to generate a new JAR file

### ISSUE THREAD

**Issue by E0735389** [nus-cs2103-AY2324S2/forum#372]
On page https://nus-cs2103-ay2324s2.github.io/website/schedule/week5/project.html#1-generate-a-new-jar-file , in the sentence

> Refer to the [Gradle tutorial @SE-EDU/guides](https://se-education.org/guides/tutorials/gradle.html#creating-a-jar-file) to find how.

there is a link to `https://se-education.org/guides/tutorials/gradle.html#creating-a-jar-file`.

However, as far as I can see there is no such anchor on the target link.
On the other hand, `https://se-education.org/guides/tutorials/gradle.html#creating-jar-files` exists.

**Comment by damithc** [comment]
Fixed. thanks for reporting this, @E0735389
