### ISSUE TITLE
Granting permissions to github actions for tP 

### ISSUE THREAD

**Issue by tankh99** [nus-cs2103-AY2324S2/forum#373]
I'm trying to setup the markbind website, but am currently facing difficulties with it because I can't seem to grant github actions read and write access to my group's tP repo fork

<img width="1004" alt="Screenshot 2024-02-22 at 3 52 23 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/56617918/5f303e8b-d0d7-4b32-8ec8-fdc4d03f1fa0">

Some context:
- I have admin permissions
- I could previously set the read and write permissions for actions, but after merging `switch-docs-to-markbind` branch, I could no longer do so

I would appreciate greatly on any assistance regarding this. Thank you!

**Comment by damithc** [comment]
@tankh99 perhaps you've already set the org level permissions to 'read and write' (which means it is already applied to this repo)?

**Comment by Jerome-j** [comment]
Hi Khang Hou, commenting here as your team member.

It turns out that the Organization permissions was not set to enable "Read and Write permissions", therefore the tP which was part of the organisation was affected by this matter.


@tankh99 Please proceed to close the issue!

**Comment by tankh99** [comment]
Thank you @Jerome-j for your kind assistance. I have fixed it thanks to your help. I will proceed to close this issue

**Comment by MarcusGitty** [comment]
thank you for this, my team also encountered the same issue and is currently trying your fix !

**Comment by Jerome-j** [comment]
No worries. All the best! Happy to help :)
