### ISSUE TITLE
Small typo in AB3 tutorial: adding a command

### ISSUE THREAD

**Issue by itstrueitstrueitsrealitsreal** [nus-cs2103-AY2324S2/forum#374]
With reference to the [AB3 tutorial to add the remark functionality](https://nus-cs2103-ay2324s2.github.io/tp/tutorials/AddRemark.html), I spotted a typo which refers to the `logic.command` package, when it should actually be `logic.commands`.

The error is in the paragraph directly below the header that goes "Create a new remark command".

Thank you!

**Comment by damithc** [comment]
Thanks for reporting this, @itstrueitstrueitsrealitsreal 
Will make a note, to be fixed in the upstream repo at se-edu
