### ISSUE TITLE
Citing for specific Java functions that are researched

### ISSUE THREAD

**Issue by leejaegeun-sql** [nus-cs2103-AY2324S2/forum#375]
If I researched on how to use certain specific Java functions (such as trim()/ toLowerCase()/ java regex, which are used quite a few times in my program) from w3schools (for eg.), do I need to cite for every single trim() functions in my code?

**Comment by damithc** [comment]
@alphajae11 No need. But you should cite the source if you lifted a non-trivial code snippet from such a resource, in places where the code snippet was used.

**Comment by leejaegeun-sql** [comment]
Thank you @damithc 

Follow up question:
Just wanted to confirm again, for this point, which I am getting a bit confused by reuse policy.

I had some trouble with Storage class part which I had no solution to and wanted to reuse my teammates' some parts of **save functions** in storage class (Most likely, I will be lifting their code almost verbatim for that specific part.)

Do I check for above situation if I can make reference by doing this?

//@@author {my teammates' GithubUsername}-reused
//{Info about the source...}

{Reused code (possibly with minor modifications) here ...}

//@@author


Thank you in advance.

**Comment by damithc** [comment]
@alphajae11 it should be `//@@author {your GithubUsername}-reused` to indicate who reused the code.

In fact, `//@@author` annotations are more useful for the tP, not the iP. For the iP code, you can just add a comment to credit the source. No need for the `//@@author` tag.

**Comment by leejaegeun-sql** [comment]
Thank you very much @damithc !
