### ISSUE TITLE
Feature Specification Clarification

### ISSUE THREAD

**Issue by chiralcentre** [nus-cs2103-AY2324S2/forum#378]
Hi Prof can I check if we are allowed to deviate slightly from our feature specification document (eg. deviating on attribute types)? At the same time, can I check if it is possible for features to be GUI related (eg. better data visualisation) instead of being command related? Lastly, can I check if we are allowed to seek a consultation with the teaching team to get a sanity check on the team's progress and whether the feature specification fulfills the TP constraints?

**Comment by damithc** [comment]
> Hi Prof can I check if we are allowed to deviate slightly from our feature specification document (eg. deviating on attribute types)?

@chiralcentre Yes, the implementation may vary from the feature spec later, as necessary. However, the submitted feature spec needs to be _complete_. You shouldn't leave out parts, 'to be determined later'.

>At the same time, can I check if it is possible for features to be GUI related (eg. better data visualisation) instead of being command related? 

Yes, features can include changes to the GUI.

> Lastly, can I check if we are allowed to seek a consultation with the teaching team to get a sanity check on the team's progress and whether the feature specification fulfills the TP constraints?

Constraint compliance is a deliverable, so, we don't pre-check it before it is graded. You need to carefully review the constraints and cross check to ensure that you don't violate them. However, it is fine to post a query in the forum if there is a specific case that you have trouble figuring out if you are in compliance with a specific constraint.

**Comment by chiralcentre** [comment]
Thank you Prof for the response. Just to clarify, does that mean we are allowed to change the implementation of the features from what was stated in the feature specification later on? At the same time, for GUI related features, how should we write the feature specification, since there is no related command?

Lastly, my team is thinking of adding an email address field for a Person so that we can adapt the AB3 code for recruiters to contact candidates and manage the interview pipeline; can I check if this would be in line with the Evolve strategy? I am worried that our product might be viewed as going down the Morph route instead.

**Comment by damithc** [comment]
> Thank you Prof for the response. Just to clarify, does that mean we are allowed to change the implementation of the features from what was stated in the feature specification later on?

Yes, the feature spec is not a contract. It's simply a way to show that you 'have a plan'. The plan can (and should) change later as the project progresses. Adapting plans along the way is a learning outcome of the tP.

> for GUI related features, how should we write the feature specification, since there is no related command?

You can use a mock up to specify how the updated GUI will look like.

> Lastly, my team is thinking of adding an email address field for a Person so that we can adapt the AB3 code for recruiters to contact candidates and manage the interview pipeline; can I check if this would be in line with the Evolve strategy? I am worried that our product might be viewed as going down the Morph route instead.

Doesn't it already have an email address field? Or did I misunderstand your question?

**Comment by chiralcentre** [comment]
Thank you Prof for the response! Noted on the first two points.

> Doesn't it already have an email address field? Or did I misunderstand your question?

Yes I apologise for the mistake; I was referring to changing the validation rules for the email address to be stricter. In conjunction with this, can I check if adding features to allow recruiters (target audience) to keep track of interview status of candidates will be in line with the Evolve strategy, since we are no longer using AB3 as purely an addressbook? How do we tell the difference between the Evolve and Morph routes?

**Comment by damithc** [comment]
> Yes I apologise for the mistake; I was referring to changing the validation rules for the email address to be stricter. In conjunction with this, can I check if adding features to allow recruiters (target audience) to keep track of interview status of candidates will be in line with the Evolve strategy, since we are no longer using AB3 as purely an addressbook? How do we tell the difference between the Evolve and Morph routes?

@chiralcentre This should be fine. Quoting requirements:

>Note: the contacts should still remain the primary focus, even if there are other things being managed e.g., an address book app that is optimized for a user who lends out money to those contacts (not a loan management app).

**Comment by chiralcentre** [comment]
Thank you Prof for the clarification!
