### ISSUE TITLE
error when running Duke.main()

### ISSUE THREAD

**Issue by bgopi23** [nus-cs2103-AY2324S2/forum#38]
Error: Could not find or load main class Duke
Caused by: java.lang.ClassNotFoundException: Duke

my sdk is 11.0.17 and language level is sdk default

**Comment by yeoshuheng** [comment]
Did you compile the class before running the code?

I believe you can do so via javac Duke.java.

This should compile the class for you to run, but I'm not sure if this is the issue you are facing.

**Comment by yeoshuheng** [comment]
I'm not using intellij so I'm not sure :(

But maybe it could be an issue with project structure settings? I believe others were discussing a similar problem here: https://stackoverflow.com/questions/17300318/error-classnotfoundexception-in-intellij-idea

**Comment by bgopi23** [comment]
doesnt work

**Comment by UdhayaShan1** [comment]
Is the file name Duke? And is there a main method still in Duke?

**Comment by Jerome-j** [comment]
Are you able to create a basic Java hello world program?

**Comment by damithc** [comment]
@bgopi23 It might help to share screenshots of your IntelliJ project settings, and perhaps the full IntelliJ Window showing the error message.

**Comment by bgopi23** [comment]
i was able to fix it by removing the cloned repo from my local machine and re-cloning it from github to a new folder and set it up again
