### ISSUE TITLE
Javadoc: links to the standards and conventions page of our module for convenience?

### ISSUE THREAD

**Issue by E0735389** [nus-cs2103-AY2324S2/forum#380]
Currently, in the textbook in the Javadoc section, it's written

> In the absence of more extensive guidelines, [...]

Source:

* https://nus-cs2103-ay2324s2.github.io/website/schedule/week3/topics.html#implementation-documentation-tools-javadoc-how
* https://nus-cs2103-ay2324s2.github.io/website/se-book-adapted/chapters/documentation.html#how-4

But we do have a convention in our module:

https://nus-cs2103-ay2324s2.github.io/website/admin/standardsAndConventions.html#java

Maybe it's more convenient to mention that fact in the corresponding section in the textbook?

----

Rationale: when ctrl-K in the textbook to look for "Javadoc", the first resource that comes up are the 2 links above, which doesn't link to our module's convention.

**Comment by damithc** [comment]
It's a fair point @E0735389 
At the same time, I hesitate to include course-specific things in the textbook as the textbook is an independent resource on its own, used by multiple courses. Although MarkBind allows us to integrate the textbook reasonably well into the course website, I still prefer not to inject course-specific things into textbook pages. It's a tradeoff between convenience and reusability.
