### ISSUE TITLE
Can't view GitHub page using URL

### ISSUE THREAD

**Issue by Li-Zizhen** [nus-cs2103-AY2324S2/forum#381]
I think I have set up the GitHub page correctly, and the Docs are there. However, I can't access the page using the URL `https://li-zizhen.github.io/ip/`. May I ask how to solve this?
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/122284239/d9e5ba1b-85e8-4d39-a77d-7bd13dc15d94)
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/122284239/69187c26-b908-476d-87d0-8d1badcda171)
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/122284239/077e8807-1efb-4b9c-aed9-d1174f439dd1)

**Comment by camille-readbean** [comment]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/52031118/5f50ef65-893b-4bd4-833f-28856d0d1a25)
This may not be covered in the textbook (yet) so I may be using terms that is too technical bear with me.

You need to find a way to run this action. Currently as of writing, the status is `queued`.  
It may be GitHub is overloaded or something else.

**Comment by damithc** [comment]
@camille-readbean Good suggestion.

Seems to be a GitHub Actions bug. The remedy is to rerun the job (repo owner can rerun a job). Or simply push another commit to the master branch to trigger the job again.

**Comment by Li-Zizhen** [comment]
Thanks for the solution. I make some new commits, push them again, and the problem is resolved.
