### ISSUE TITLE
Github Pages does not recognise table of contents links to headings with code snippets

### ISSUE THREAD

**Issue by kjw142857** [nus-cs2103-AY2324S2/forum#383]
For context, I tried to create a table of contents for my user guide but faced an issue where the links in the TOC to any heading with a code snippet did not work, i.e. the page did not scroll down to that section. (This issue only happened during deployment to Github Pages and not on my local machine.) 

When I changed the affected headings by removing the code snippets,  the TOC worked normally and the links to the headings were active again.

<br/><br/>

Example of a heading that contains a code block
```
## Adding a deadline: `deadline`
```
<br/><br/>

Preview of the heading in Markdown
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/122250318/d34ca628-c109-48b2-b982-08045f030eb4)

**Comment by camille-readbean** [comment]
May you share how did your format the link?

Like 
`[link text](# Adding a deadline: `deadline`)`  or 
```
#adding-a-deadline-`deadline`
```

**Comment by kjw142857** [comment]
I used what Intellij recommended, which was `[link text](#adding-a-deadline--deadline)`

It could possibly be an IDE problem now that I think about it - I'm not sure it's the best idea to use Intellij to write Markdown code.

In addition. both the examples you gave did not work locally unfortunately. Is it possible that they would fail locally but work on Github Pages?

Edit: It appears that they do not work on Github Pages too after doing a manual test

**Comment by damithc** [comment]
@kjw142857 Deploy without a ToC first. After that, go to the generated page and find the correct link for each heading. 

Steps: Hover over a heading, and click on the 🔗 icon that appears. That will update the browser URL with the link for that heading. From that, you can deduce what you need to put in the ToC link (it should be of the format `[Heading Text](#heading-text)`.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/1f6ac3f5-d9cd-44b9-8aef-94f2c7e58ebc)

**Comment by kjw142857** [comment]
Thank you so much for the help Prof @damithc , I managed to find the correct representation!

For those wondering, the accurate format would be `[link text](#adding-a-deadline-deadline)`, i.e. no double hyphen before the code block, and no other delimiters.
