### ISSUE TITLE
Lengthy methods

### ISSUE THREAD

**Issue by cheahTJ** [nus-cs2103-AY2324S2/forum#384]
As suggested in my title, if I currently have long methods (30-50 LOC) for my parser class to consider all the cases a user might miss out in typing their command to prevent my application from crashing, is that justifiable and will I be penalised for not having a reasonable code quality?

Additionally, I would like to ask for the testing done by the marking team on our bot, would it just be checking if our application works according to how we describe it in our user guide or would there be tested with many edge cases?

**Comment by camille-readbean** [comment]
Potentially related. 
https://github.com/nus-cs2103-AY2324S2/forum/issues/303

**Comment by damithc** [comment]
> Additionally, I would like to ask for the testing done by the marking team on our bot, would it just be checking if our application works according to how we describe it in our user guide or would there be tested with many edge cases?

@cheahTJ It is meant to be tested from the user point of view i.e., mainly based on what is stated in the user guide, and for things not stated in the UG, based on typical user expectations.

**Comment by cheahTJ** [comment]
Thank you @camille-readbean, it was really helpful. Thank you prof for the verification! @damithc
