### ISSUE TITLE
Seeking clarification behind the error message: JavaFX runtime components are missing...

### ISSUE THREAD

**Issue by c-wenlong** [nus-cs2103-AY2324S2/forum#385]
## Problem
As I am a Mac user with M1 core, my `.jar` file runs fine on my friend's MacBook (M1) but not my other friends MacBook (Intel), and it doesn't run on 4/4 of my friends' Windows (Intel).

## How I fixed it.
Following #241 , I moved my `Launcher.java` from `src/java/kbot/gui` to  `src/java/kbot` as shown below after the change. Furthermore, I renamed my original file containing the `start()` method for the Application from `KBot.java` to `Main.java`.
<img width="342" alt="Screenshot 2024-02-23 at 14 39 18" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/122634467/5989aa50-8ff7-4519-b98c-2cfa2ee5689b">

## Question
So, at this moment, since I made the changes in a single commit, I do not understand what exactly made my jar file work. And I am seeking to clarify why my original program works for M1 Mac users but not for Intel users whereas the fix made it work on all devices.

**Comment by aureliony** [comment]
Refer to https://github.com/javafxports/openjdk-jfx/issues/236#issuecomment-426583174

**Comment by AidenLYT** [comment]
I have done the same thing as c-wenlong. Can run on MacOS, but still cannot run on WindowsOS

Files: 
<img width="241" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/110450637/16308373-4223-4c03-9cc1-984b2a98076f">

Error on WindowsOS: 
![telegram-cloud-photo-size-5-6251247452933962533-w](https://github.com/nus-cs2103-AY2324S2/forum/assets/110450637/b4ebd0c9-403a-4e57-b485-1c6d47c43db8)

**Comment by c-wenlong** [comment]
> Refer to [javafxports/openjdk-jfx#236 (comment)](https://github.com/javafxports/openjdk-jfx/issues/236#issuecomment-426583174)

Sorry, Im not exactly sure how the discussion here answers my concern about the error. 

>The reason is that the Java 11 runtime will check if the main class extends javafx.application.Application, and if that is the case, it strongly requires the javafx platform to be available as a module, and not as a jar for example.

What I gather from this is that the JavaFX module has to be present within the user's computer and that the main class has to extend Application, which were steps I took. Maybe you can help me draw the link here? Appreciate the help!

**Comment by E0735389** [comment]
looks somewhat similar to my question #369 (the provided comment just say "some classpath issue" with no explanation)

**Comment by aureliony** [comment]
> It was discussed here: http://mail.openjdk.java.net/pipermail/openjfx-dev/2018-June/021977.html

Quote from the java.net link:

> This error comes from sun.launcher.LauncherHelper in the java.base module.
The reason for this is that the Main app extends Application and has a main
method. If that is the case, the LauncherHelper will check for the
javafx.graphics module to be present as a named module:

> Optional<Module> om = ModuleLayer.boot().findModule(JAVAFX_GRAPHICS_MODULE_NAME);

> If that module is not present, the launch is aborted.
Hence, having the JavaFX libraries as jars on the classpath is not allowed
in this case.

In other words, it's the behaviour of sun.launcher.LauncherHelper itself. If you're interested you can read the source code here: https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/master/src/java.base/share/classes/sun/launcher/LauncherHelper.java

**Comment by c-wenlong** [comment]
Got it, I will just take it as a classpath specification that requires Launcher.java to be in the same directory as the other packages. Thanks!
