### ISSUE TITLE
GUI Not functioning fully

### ISSUE THREAD

**Issue by reetmitra** [nus-cs2103-AY2324S2/forum#387]
My tasks are getting displayed in the command line when I put the 'list' command in but not in the GUI interface. If i'm adding a new task for eg. 'todo call xyz' it's responding in the GUI with the appropriate response. My welcome message is also not coming up and my 'deadline' command is not working correctly. How to resolve this issue?

**Comment by fy17ohhh** [comment]
Note that in your  `mainWindow.fxml` file, you have `onAction="#handleUserInput"`, so make sure you have the correct content(i.e. the output string returned from other methods) added to the `dialogContainer` in the `handleUserInput() `method

**Comment by damithc** [comment]
@reetmitra if still not resolved, push the latest code to your fork (or a branch therein) and share the link here so that others can try to reproduce the problem.

**Comment by reetmitra** [comment]
it's been resolved thank you for the help @fy17ohhh
