### ISSUE TITLE
[MacOS] Resource Registered is not recognizable 

### ISSUE THREAD

**Issue by AidenLYT** [nus-cs2103-AY2324S2/forum#388]
After I ran Launcher.main, this error gets thrown.

<img width="1512" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/110450637/c76e7520-8d11-4fa9-a3b9-52e7a1191066">

**Comment by damithc** [comment]
@AidenLYT I recommend that you push the code to a branch in your fork and share the branch name here so that other can try to replicate the exact problem (or do a more thorough examination of the code).

**Comment by billyhoce** [comment]
@AidenLYT not sure if its related, but I'm using `xmlns="http://javafx.com/javafx/21` instead. Not sure if that will help you.
