### ISSUE TITLE
GUI Not returning list

### ISSUE THREAD

**Issue by reetmitra** [nus-cs2103-AY2324S2/forum#389]
When I use the list command, it's not returning anything. However, if i add a new task it's responding with the correct response. Could anyone help with fixing this issue?

**Comment by damithc** [comment]
I recommend that you push the code to a branch in your fork and share the branch name here so that other can try to replicate the exact problem (or do a more thorough examination of the code).

**Comment by reetmitra** [comment]
I managed to fix it, there was a missing method that was not being called correctly for the UI to be functioning correctly.
