### ISSUE TITLE
How to test against random behaviour

### ISSUE THREAD

**Issue by vnnamng** [nus-cs2103-AY2324S2/forum#39]
To add some personality to the Chatbot, I have been creating functions that randomize the conversations so that it randomly choose the replies, greetings and byes from lists of String. 
However, such methods does not allow for current testing method. I want to ask
  1. Is this approach is not testable?
  2. Is there a workaround? 
If such behaviour is not expected, I will change accordingly.
Thank you for your time!

**Comment by damithc** [comment]
@vnnamng 

> To add some personality to the Chatbot, I have been creating functions that randomize the conversations so that it randomly choose the replies, greetings and byes from lists of String.

Nice 👍 

> * Is this approach is not testable?
> * Is there a workaround?
>   If such behaviour is not expected, I will change accordingly.
>   Thank you for your time!

The I/O redirection testing can work only if the output is predictable. One workaround is to add a way to disable the random behavior during testing. Another is to use this technique for testing only the non-random behaviors (the random part can be tested manually). 
Others, feel free to suggest more workarounds ...

**Comment by yeoshuheng** [comment]
I was thinking if could also be possible to check if the output is within a certain set of values. (In this case, the list of strings you are getting the greetings from) ?

eg. psuedocode:

greetings = ["a", "b", "c", "d"]
if (output not in greetings) {
   fail test
}

I think this could be added to the .bat / .sh using grep commands. But I'm not too sure.
