### ISSUE TITLE
My one line of code is not working

### ISSUE THREAD

**Issue by Darkarche3** [nus-cs2103-AY2324S2/forum#390]
Hi, I have picked the task on prioritise from C in BCD. I have implemented it and it works correctly. However, when I try to return a statement to notify the user, the line does not run.

else if(command.equals("priority")){
            int index = Integer.parseInt(parser.parseModify(instruction));
            int prority = Integer.parseInt(parser.parsePriority(instruction));
            Task prioritiseTask = tasks.get(index-1);
            prioritiseTask.setPriority(prority);
            return ui.priorityMessage(prioritiseTask);
        }
 
 To be clear I am referring to the return statement.

public String priorityMessage(Task task){
        return "Priority hase been set to "  + task.getPriority() + " for " + task.toString();
    }
    
 this is the function.
 
 I plan to remove it if I cant solve it since deadline is near and it is optional but I was curious if this issue might mean larger issues with the rest of my code.
 
 Any advice would be appreciated.

**Comment by chiralcentre** [comment]
Are you referring to the line `return ui.priorityMessage(prioritiseTask);`? Can I check how do you know that the line is not run? It might be possible to implement a breakpoint in the IDE to trace through the execution of the code.

**Comment by damithc** [comment]
@Darkarche3 Tip: You may want to use [fenced code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) to format your post for better readability.

**Comment by damithc** [comment]
> the line does not run.

@Darkarche3 This is rather vague. What's the expected behavior and what's the actual behavior?

**Comment by Darkarche3** [comment]
Expected behaviour is to return a string that says "Priority has been set to " + whatever level user wants.

The actual behavior is that no such message is returned.

**Comment by yisiox** [comment]
@Darkarche3 Can I check how did you know it was not returned? Your master and BCD-extension branches it doesn't seem to match the code you sent here, as it seems like the return value isn't assigned to anything, and only the empty string is returned. 

If you are using IntelliJ you can use the [debugger](https://www.jetbrains.com/help/idea/debugging-code.html) and specifically the feature to [step](https://www.jetbrains.com/help/idea/stepping-through-the-program.html) through the program to see what is happening (as recommended by the week 6 topics).

**Comment by Darkarche3** [comment]
Hi, I managed to fix the issue. Thank you very much for the help.
