### ISSUE TITLE
Failing Git Standard for IP

### ISSUE THREAD

**Issue by chiralcentre** [nus-cs2103-AY2324S2/forum#391]
Hi can I check with the teaching team if I will be penalised for failing the Git Standard admin task (last 5 commit messages should not have easily detectable Git standard violations) on the IP tracker dashboard? I went through my past commits and I have identified the commit where I made the mistake, but I am not sure if I should amend it because that might change the date of the commit.

**Comment by damithc** [comment]
@chiralcentre To make it green, you can add a few more commits (with some minor updates to the code) so that the last five commits are compliant with the standard.

**Comment by chiralcentre** [comment]
Thanks Prof for the response! However, as the deadline for submission is in an hour's time and I have already released the JAR file on Github with smoke testing, I was thinking the timing might be a bit tight to perform smoke testing on a JAR file. Can I check if I will be penalised if I do not add commits such that the last five commits are compliant with the standard?

**Comment by damithc** [comment]
@chiralcentre No penalty for missing just a few deliverables. Also, there is no problem if you add a few more trivial commits after releasing the JAR file.

**Comment by chiralcentre** [comment]
Noted Prof! Thank you for the prompt response.
