### ISSUE TITLE
./gradlew clean shadowjar generates a zipped jar file.

### ISSUE THREAD

**Issue by KSSWSept20** [nus-cs2103-AY2324S2/forum#392]
When i try to generate a jar file using ./gradlew clean shadowjar, a zipped jar file which cannot be uploaded for submission as attached in the screenshot. However, when i direct to build/libs folder which contains these two tes.jar and ip.jar zip archive file in the terminal and run java -jar tes.jar, the chatbot can be opened. Is there anything wrong with my build.gradle or setting of my intellij?
Thanks in advance!

```
plugins {
    id 'java'
    id 'application'
    id 'com.github.johnrengelman.shadow' version '7.1.2'
    id 'checkstyle'
}

checkstyle {
    toolVersion = '10.2'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.10.0'
    testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.10.0'

    String javaFxVersion = '17.0.7'

    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'win'
}

test {
    useJUnitPlatform()

    testLogging {
        events "passed", "skipped", "failed"

        showExceptions true
        exceptionFormat "full"
        showCauses true
        showStackTraces true
        showStandardStreams = false
    }
}

application {
    mainClass.set("tes.Launcher")
}

shadowJar {
    archiveBaseName = "tes"
    archiveClassifier = null
    archiveFileName = 'tes.jar'
    dependsOn("distZip", "distTar")
}

run{
    standardInput = System.in
}
```
![Screenshot 2024-02-23 230909](https://github.com/nus-cs2103-AY2324S2/forum/assets/123055631/948f7489-6cd7-4711-bd6f-8b1453c429a9)
![Screenshot 2024-02-23 231253](https://github.com/nus-cs2103-AY2324S2/forum/assets/123055631/eb2f0db1-09e0-4c0a-a9ba-926cbef74d60)

**Comment by damithc** [comment]
@KSSWSept20 You may want to use [fenced code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) to format your post for better readability.

**Comment by tzyian** [comment]
A `jar` file is actually a `zip` file which you can unzip. In Windows if you select the option to always show file extensions it should still be a `jar` file. Or you may wish to change your default application for opening `jar` files.

Edit: for submission in GitHu releases you want to upload under binaries, not under the big text box

**Comment by camille-readbean** [comment]
@rertyy is right

Can you turn on view file extension in your file explorer. Should shows whether it's a `.jar` or `.zip`

It may be possible the `.jar` file extension was registered as a zip file so maybe the file extension is not correctly associated. But no issues.

I infer they are indeed named `.jar` from your post and `grade.build`

Just upload `tes.jar` for binary files in release

**Comment by KSSWSept20** [comment]
Issue solved, thanks a lot! @rertyy @camille-readbean
