### ISSUE TITLE
Typo in code tracing tutorial

### ISSUE THREAD

**Issue by drustanyjt** [nus-cs2103-AY2324S2/forum#396]
Here I believe it should be "user input ~in~ _is_ passed..."
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/110999129/025b7b15-2358-4727-b764-cb39fb953714)

Link: https://nus-cs2103-ay2324s2.github.io/tp/tutorials/TracingCode.html

**Comment by damithc** [comment]
Thanks for reporting this, @drustanyjt 
Will make a note, to be fixed in the upstream repo at se-edu
