### ISSUE TITLE
Requesting Permission to use third-party Library (fuzzywuzzy)

### ISSUE THREAD

**Issue by aureliony** [nus-cs2103-AY2324S2/forum#397]
## Library

[fuzzywuzzy](https://github.com/xdrop/fuzzywuzzy)

## Purpose

To calculate Levenshtein distance for string matching

## License

[GPL-2.0 license](https://github.com/xdrop/fuzzywuzzy?tab=readme-ov-file#GPL-2.0-1-ov-file)

**Comment by damithc** [comment]
Approved.
