### ISSUE TITLE
Requesting Permission to use third-party Library (javafx-gradle-plugin)

### ISSUE THREAD

**Issue by aureliony** [nus-cs2103-AY2324S2/forum#398]
## Library

[javafx-gradle-plugin](https://github.com/openjfx/javafx-gradle-plugin)

## Purpose

To simplify build.gradle, removing the need to specify multiple operating systems for JavaFX.

## License

[BSD-3-Clause license](https://github.com/openjfx/javafx-gradle-plugin#BSD-3-Clause-1-ov-file)

**Comment by damithc** [comment]
Approved.
