### ISSUE TITLE
jar file not opening

### ISSUE THREAD

**Issue by tahnya** [nus-cs2103-AY2324S2/forum#399]
when i run my project on intellij with gradle it works just fine, but when i created the jar file andtried to open it, nothing happened. there was no error message, just nothing happened lol. 

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/111273056/e5aafa0b-8f3a-48f1-8184-53d3a3d61b94)

when i double click on the .jar file then it shows this error message: 
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/111273056/ed8d40a9-92fb-46d0-8c00-8a97fb3397df)
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/111273056/d3f4e64a-ee20-4b57-9e4d-678d9ef57d9e)

ive updated the java version to 11 
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/111273056/6d90ab46-f48c-4fd9-ad6e-89b6551d86fe)

i'm not sure what to do now oops, im not even sure where this issue even comes from. a friend also tried to open the file on her laptop (we are both windows users) but nothing happened either.

**Comment by damithc** [comment]
@tahnya Are you able to run the AB3 jar file we have provided?
How did you create your jar file? Try creating it using `./gradlew clean shadowJar` and try again.

**Comment by tahnya** [comment]
@damithc Yep i can open and run the ab3 :) I created the jar file by typing `./gradlew clean shadowJar` in the terminal and clicking `ctrl + enter` this time, but nothing happened again :(
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/111273056/7744de4d-4e9e-4c1b-b5f1-635fb6517fb2)
 
the previous time i used the ` Tasks>shadow>shadowJar` from the gradle tool bar
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/111273056/3f8c0e01-dc8c-4e48-9a40-2873469bf159)

**Comment by damithc** [comment]
> Yep i can open and run the ab3 :) I created the jar file by typing `./gradlew clean shadowJar` in the terminal and clicking `ctrl + enter` this time, but nothing happened again :(

@tahnya try just the <kbd>enter</kbd> (not ctrl+enter)

Did you look in the `builds/libs` folder to find the jar file created by shadowJar?

**Comment by tahnya** [comment]
@damithc Yes i copied the signal.jar file from `builds/libs` in my repo to another empty folder `runtest` to run 

When i do `./gradlew clean shadowJar` in the terminal and click `enter` i get this:
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/111273056/08965aa0-0eb7-4d15-aeea-e093ba915098)

in project structure the jdk is here:
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/111273056/52c3ac9b-806e-4c7a-a0de-2b2123dca485)

JAVA_HOME in env variables 
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/111273056/5e7d277b-8944-4c9d-bcd0-465f511fdb1d)
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/111273056/c35b8aa4-43f4-46a0-9680-806b59b1d46b)

**Comment by damithc** [comment]
@tahnya if you change a system variable, you need to restart the terminal/IDE for it to take effect.
Also, if the current JAVA_HOME doesn't work, try setting it to the `bin` folder inside the current JDK folder, to see if that works.

**Comment by tahnya** [comment]
@damithc Okie after restarting it still shows this
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/111273056/1670b4af-3ea4-4797-a905-ecbc4e5d708f)

i changed the JAVA_HOME to `C:\Program Files\Java\11.0.17\bin` and restarted, still got this:
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/111273056/edd0377b-256d-4d2c-bd56-3a3f0c1fdd92)

I tried checking the java version and got this?? :0
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/111273056/bcdfec0b-2ff9-4f16-8648-6b1a3102093a)

should i try re downloading java 11? :(

**Comment by damithc** [comment]
@tahnya Changing JAVA_HOME to `bin` is probably the wrong thing to do. You can change that back.

Also check if there is a `C:\Program Files\Java\11.0.17\bin\java.exe`
Can you also share the value of your `PATH` system variable?

**Comment by damithc** [comment]
Uninstalling all java versions and reinstalling JDK 11 can be a last resort.

**Comment by azumieflare** [comment]
You can try changing ```mainClass.set("signal.Signal")``` in ```build.gradle``` to ```mainClass.set("Launcher")``` and try running ```gradlew shadowJar``` to create the .jar again.

**Comment by tahnya** [comment]
@damithc Okay! I managed to fix that by installing another java version haha 😅 Thank you though for helping 😄

**Comment by tahnya** [comment]
@azumieflare Thank you! that worked, now the jar file can open 😄
