### ISSUE TITLE
Small Typo

### ISSUE THREAD

**Issue by howen02** [nus-cs2103-AY2324S2/forum#4]
Should be 'since midnight' not 'till midnight'

At W1.1f

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/108785851/f56f00e4-ee46-427b-8683-9a06547e885a)

**Comment by E0735389** [comment]
By the way, you can click on the anchor :anchor: to link to the [direct section](https://nus-cs2103-ay2324s2.github.io/website/schedule/week1/topics.html#instance-methods). Too bad it doesn't directly link to the source code on GitHub.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/97508964/a430ff70-4ea2-4273-a9f6-c367fd56ab05)


Thinking about it, the pluralization in the example below would be wrong as well if the output is 1 (probably for simplicity)

**Comment by damithc** [comment]
@howen02 Thanks for the heads up. Fixed.
@E0735389 Thanks for bringing up the pluralization issue. Yes, the reason is to keep it simple.
