### ISSUE TITLE
Minor typo in textbook

### ISSUE THREAD

**Issue by E0735389** [nus-cs2103-AY2324S2/forum#400]
https://nus-cs2103-ay2324s2.github.io/website/se-book-adapted/projectDuke/index.html#d-trivia

> Provide the ability to learn/memorize thingse.g., learn vocabulary, answers to questions

Looks like there's a missing space before the `e.g.`.

**Comment by damithc** [comment]
Thanks @E0735389 
Will fix in the next website update.
