### ISSUE TITLE
Feature clarification: should we copy AB3 user guide?

### ISSUE THREAD

**Issue by E0735389** [nus-cs2103-AY2324S2/forum#401]
* Looking at the requirements of writing a feature specification https://nus-cs2103-ay2324s2.github.io/website/admin/tp-w6.html#2-draft-the-feature-specification, it feels like copying AB3 user guide would satisfy the condition, if I understood correctly?

  https://se-education.org/addressbook-level3/UserGuide.html#viewing-help--help

  However, I think a difference is that AB3 user guide does not contain e.g. the exact error message when a command fails.

Besides, I don't really understand what this feature list is supposed to be, since the features is mostly a subset of existing AB3 features --- if I understood correctly, "_complete_ detailed description" means we should still explain what the command do even though AB3 already does it.

So,
* if we copy down the exact feature set of AB3, would we have nothing to do to implement v1.2?
* are we allowed to specify less than the whole feature set of AB3 (in which case, after v1.2 is completed, I assume that the resulting product will have to have all the features in the union of existing features and feature specification?)

**Comment by damithc** [comment]
@E0735389 

1. Yes, you may copy parts of AB3 UG that is relevant to your v1.2
2. Yes, you need to add more details about error messages, validation rules, size limits etc. Also, you need to carefully consider the current AB3 behavior and decide if you want to keep that behavior or 'improve on' it in some way.
3. The less you need to do in v1.2, the better it is, as you get to reach the first version of your product faster. But it will not be zero work, as you need to change the product name at least.
4. You may remove existing features if they are not relevant to the final version of your product, although most existing features are expected to stay in some form or other.
5. Yes, you may specify only the features relevant for your v1.2 i.e., omit from the feature spec AB3 features that exist but not relevant to v1.2

**Comment by E0735389** [comment]
Regarding this point:

> You may remove existing features if they are not relevant to the final version of your product, although most existing features are expected to stay in some form or other.

Let's say that we don't include `find` in v1.2 feature specification or user guide, but with the caveat that if the user "accidentally" type it in then the program "somewhat" works (but might have slightly buggy behavior because the command was originally written for AB3). Would this be a problem?

(Or are we expected to remove it completely? Then how will we add it back in v1.3? Do we need to?)

------

> Yes, you may copy parts of AB3 UG that is relevant to your v1.2

Should we copy it, or should we just say "the feature is the same as explained in the user guide of AB3"?
E.g. this part could potentially be copied:

> :information_source: Notes about the command format:
> 
> Words in UPPER_CASE are the parameters to be supplied by the user.
> e.g. in add n/NAME, NAME is a parameter which can be used as add n/John Doe.
> 
> Items in square brackets are optional.
> e.g n/NAME [t/TAG] can be used as n/John Doe t/friend or as n/John Doe.
> 
> Items with …​ after them can be used multiple times including zero times.
> e.g. [t/TAG]…​ can be used as   (i.e. 0 times), t/friend, t/friend t/family etc.
> 
> Parameters can be in any order.
> e.g. if the command specifies n/NAME p/PHONE_NUMBER, p/PHONE_NUMBER n/NAME is also acceptable.
> 
> Extraneous parameters for commands that do not take in parameters (such as help, list, exit and clear) will be ignored.
> e.g. if the command specifies help 123, it will be interpreted as help.

or the part that validates email address:

> Emails should be of the format local-part@domain and adhere to the following constraints:
> 1. The local-part should only contain alphanumeric characters and these special characters, excluding the parentheses, (+_.-). The local-part may not start or end with any special characters.
> 2. This is followed by a '@' and then a domain name. The domain name is made up of domain labels separated by periods.
>   The domain name must:
>     - end with a domain label at least 2 characters long
>     - have each domain label start and end with alphanumeric characters
>     - have each domain label consist of alphanumeric characters, separated only by hyphens, if any.

**Comment by damithc** [comment]
> Let's say that we don't include `find` in v1.2 feature specification or user guide, but with the caveat that if the user "accidentally" type it in then the program "somewhat" works (but might have slightly buggy behavior because the command was originally written for AB3). Would this be a problem?
> 
> (Or are we expected to remove it completely? Then how will we add it back in v1.3? Do we need to?)

@E0735389 Sorry, my previous answer wasn't clear. You don't need to remove unused features in v1.2. But you should remove unused features by v1.4 as you are accountable for (and graded for) any feature that is present in that version.

> Should we copy it, or should we just say "the feature is the same as explained in the user guide of AB3"?

Copy it.
