### ISSUE TITLE
Queries about week3 ip-5

### ISSUE THREAD

**Issue by Morninggloryyy** [nus-cs2103-AY2324S2/forum#402]
Hi all, for week3 ip-5, should I tag after finishing each branch and push that branch, or tag and push all at once after merging? Thank you!!
<img width="624" alt="b6f335c15cec858fdadea1831c37f65" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/156987743/8188b089-8de7-4f90-9444-8ace88f93518">

**Comment by damithc** [comment]
@Morninggloryyy Tag after merging each branch. You can push any time but the tags/branches will not be visible to our scripts until you push them.

**Comment by Morninggloryyy** [comment]
@damithc Thank you so much for your clarification!
