### ISSUE TITLE
Problem with setting up github pages

### ISSUE THREAD

**Issue by reetmitra** [nus-cs2103-AY2324S2/forum#403]
My github pages is not getting set up it says invalid YAML format. How can I fix this?

**Comment by damithc** [comment]
@reetmitra You need to provide more details. What exactly were you trying to do (iP or tP, which increment, which step), where did you see the error message etc.

**Comment by reetmitra** [comment]
I was doing the iP, releasing the user guide increment. The page was not loading up and there was an error message.

<img width="652" alt="Screenshot 2024-02-24 at 4 54 43 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/63037606/aa5b8bbe-510b-4235-86fd-2c475c731de2">

**Comment by Jerome-j** [comment]
Hi I looked through your logs and I noted that your Readme.md has this on Line 1 and 2

```
---

```

I suspect this is causing a build issue.

**Comment by reetmitra** [comment]
Oh yes, it's fixed now, thank you!
