### ISSUE TITLE
Minor type in course website

### ISSUE THREAD

**Issue by bryanyee33** [nus-cs2103-AY2324S2/forum#404]
https://nus-cs2103-ay2324s2.github.io/tp/tutorials/TracingCode.html
In the tracing code tutorial page, it should be `JsonAddressBookStorage#saveAddressBook()` instead of `JsonAddressBook#saveAddressBook()`

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/65088428/58ff4d8d-0d0c-4c6c-b9ec-37f5cd7cdc9b)

**Comment by damithc** [comment]
@bryanyee33 Thanks for reporting it. I've noted it down, to be fixed in the upstream repo next semester.
