### ISSUE TITLE
Codecov Coverage for TP

### ISSUE THREAD

**Issue by chiralcentre** [nus-cs2103-AY2324S2/forum#405]
Can I check with the teaching team if we must pass the Codecov code coverage check as part of CI/CD in order to merge a PR for the TP? Updating and maintaining the unit tests as features increase can be quite a hassle, and I was wondering manual testing is allowed as well.

**Comment by damithc** [comment]
@chiralcentre passing CodeCov is not a requirement. 
Also note [our expectations on testing](https://nus-cs2103-ay2324s2.github.io/website/admin/tp-expectations.html#:~:text=Expectations%20on%20Testing)

**Comment by chiralcentre** [comment]
Noted Prof; thank you!
