### ISSUE TITLE
Generate new JAR file

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#406]
gradlew clean shadowJar

does anyone remember where to run this command to create a new JAR file? i forgot where

**Comment by dillontkh** [comment]
You can double press the `Control` and enter it in Intellij

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/40649376/91f8eb8a-7dd0-49c8-9fad-8c5ba0c41872)

Or you could `cd` to the directory containing gradlew and run it in the command prompt

**Comment by baskargopinath** [comment]
thx @dillontkh
