### ISSUE TITLE
Terminating upon "bye"

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#407]
is it ok to terminate without sending a bye message once user sends "bye"?

**Comment by sindhurajain** [comment]
I wouldn't do it that way - if it terminates without sending a bye message first, a user might think that it crashed even if it is working the way it's supposed to be working

**Comment by itstrueitstrueitsrealitsreal** [comment]
the user might see it as a bug or a crash

**Comment by baskargopinath** [comment]
@itstrueitstrueitsrealitsreal @sindhurajain how did u guys terminate

**Comment by itstrueitstrueitsrealitsreal** [comment]
#366

**Comment by baskargopinath** [comment]
thanks @itstrueitstrueitsrealitsreal 

for other people encountering this, i printed "Bye, closing in 5 seconds",
then used PauseTransition to delay 5 seconds before terminating the gui

**Comment by damithc** [comment]
To add, it's a subjective UX decision.  Some will appreciate (or wouldn't mind) a reply to the `bye` command but some users will be annoyed that the app doesn't quit immediately after it has been told to quit (in no uncertain terms) and lingers around to show a message that doesn't add any value, and delays them from whatever the next thing they intended to do (such as shut down the computer and go out).
