### ISSUE TITLE
Week 3 Branches notes

### ISSUE THREAD

**Issue by UdhayaShan1** [nus-cs2103-AY2324S2/forum#41]
<img width="799" alt="Screenshot 2024-01-22 220959" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/39399745/e9d1f2af-22ff-47b1-b0b0-9e42cde3a548">

<img width="446" alt="Screenshot 2024-01-22 221038" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/39399745/4f836d61-7f58-4b3e-ad25-0734b36e2810">

For this part, why is it not feature1 instead of 'master' (pic 1) and my HEAD remains at master.

**Comment by damithc** [comment]
@UdhayaShan1 while waiting for inputs from other classmates, some hints:
`origin/HEAD` refers to the `HEAD` label in the remote repository `origin`, not the local repo.
A commit is automatically added to the branch you are currently in.
When creating a new branch, it is likely you already switched to the new branch automatically (depending on how you create the branch).

**Comment by lshaoqin** [comment]
Hi @UdhayaShan1, from my perspective, it's true that the guide may be a little misleading. While on the `feature1` branch, commits should not move the `master` label as the guide claims. Instead, it should move the `feature1` label as is consistent with your screenshot, and the next screenshot in the guide.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/74029583/175e6226-2314-4bce-91ed-ca35dfbe85d4)

Your first screenshot, where `HEAD` is at the same point as `master`, seems to be referring to point 3 of the guide, where you were asked to switch back to the `master` branch.

`3. Switch to the master branch. Note how the changes you did in the feature1 branch are no longer in the working directory.`

So yes, I suspect there is a typo, where point 2 should say 
`Note how the **feature1** label and the HEAD label moves to the new commit (The HEAD label of the local repo is represented as  in Sourcetree).`

**Comment by damithc** [comment]
Ah, now I see where the confusion came from. The purpose of the following screenshot was just to show what the dot looks like. The rest of the screenshot content was irrelevant (in fact, it was from a different repo altogether).
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/57b32d1e-4ca8-486c-a7e4-21aa4727219b)

I'll replace it with the this instead:
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/f57cca34-1452-46b0-9e25-e4dc96693dd7)

**Comment by adammangzijun** [comment]
@UdhayaShan1
As explained in the brackets, the `HEAD` that they are referring to is the hollow circle in source tree, which refers to the branch you are currently working on right now on your _local_ machine.

## `origin/HEAD`:
- `origin/HEAD` is a pointer that references to the current commit that the default branch of the remote repository is pointing to.
- When you clone a repository, `origin/HEAD` points to the branch that is checked out by default.
- This is the branch that Git will check out by default when you clone the repository. It's a way for Git to know which branch is considered the main branch on the remote.

## `origin/master`:
- This refers to the "master" branch on the remote repository named "origin".
- It represents the state of the master branch at the remote repository at the time of your last fetch or pull.

**Now just to take note:**
- The name 'origin' is just a naming convention done by github  to denote the remote repository from which your local repository was cloned. 

Hope this helps with providing some information and clearing up some confusions.
