### ISSUE TITLE
PR and merge issue

### ISSUE THREAD

**Issue by jeong-jaeho** [nus-cs2103-AY2324S2/forum#411]
I successfully managed to create a PR and merged Assertions branch into Master branch.
I then created a new PR for CodeQuality branch, and resolved merge conflicts and created merge.
I then pulled the origin master using the following way:
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/109773933/c2d87069-d4e3-4926-bc5b-6d0b562fe46a)

But it seems the merge has taken the master branch into the CodeQuality branch, although I set from CodeQuality branch to Master branch within my PR. 
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/109773933/e662fb71-8c28-4c68-b552-fed803490d94)

When I go back into my remote repo, the PR is ironically yet to be merged, although I did merge already.
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/109773933/95ea4dbc-f05f-4836-93e6-f952b752946a)

I've tried undoing merge using hard reset mode, but the merge is still there. 
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/109773933/62756b22-ea92-41a5-9fff-2de8f5e23a98)

How do I undo the merge and redo the PR for Assertions?
Is it fine to just push the merged branch for CodeQuality into remote repo instead of completing the proper way of PR for CodeQuality?

**Comment by jeong-jaeho** [comment]
@damithc Hi, is it possible to ignore the PR for CodeQuality and just merge the merged commit back to the master branch? The CodeQuality branch is already a merged commit, so not sure if I can merge the CodeQuality branch back into master branch.

**Comment by damithc** [comment]
> @damithc Hi, is it possible to ignore the PR for CodeQuality and just merge the merged commit back to the master branch? The CodeQuality branch is already a merged commit, so not sure if I can merge the CodeQuality branch back into master branch.

@jeong-jaeho Yes, it's fine.

**Comment by damithc** [comment]
@jeong-jaeho To undo a merge, you should switch to the the branch that received the merge, and hard reset it to the commit before the merge commit.

**Comment by damithc** [comment]
> I've tried undoing merge using hard reset mode, but the merge is still there.
> ![image](https://private-user-images.githubusercontent.com/109773933/307568396-62756b22-ea92-41a5-9fff-2de8f5e23a98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NTMxNjgsIm5iZiI6MTcwODg1Mjg2OCwicGF0aCI6Ii8xMDk3NzM5MzMvMzA3NTY4Mzk2LTYyNzU2YjIyLWVhOTItNDFhNS05ZmZmLTJkZThmNWUyM2E5OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNVQwOTIxMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wODRkMDYwMjAwNTI3NTlkNDU2ODNhMmQzNTM5ZDM4YWM0MDhlMTRkNjRhNWI5MjUwNzZiNmU0YTEyOTU1YTQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.g4J4wXPWgW3VKOTKCGZlXnomNpdUJuAe6-QcNrRGfRo)

As per the above screenshot, you updated you `branch-A-CodeQuality` using GitHub UI (i.e., the latest `master` branch  was merged to `branch-A-CodeQuality` in your fork, which is fine too) but you haven't fetched that merge commit into your local repo yet.  Hence, your local `branch-A-CodeQuality`  is behind `origin/branch-A-CodeQuality`

**Comment by jeong-jaeho** [comment]
> > I've tried undoing merge using hard reset mode, but the merge is still there.
> > ![image](https://private-user-images.githubusercontent.com/109773933/307568396-62756b22-ea92-41a5-9fff-2de8f5e23a98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NTMxNjgsIm5iZiI6MTcwODg1Mjg2OCwicGF0aCI6Ii8xMDk3NzM5MzMvMzA3NTY4Mzk2LTYyNzU2YjIyLWVhOTItNDFhNS05ZmZmLTJkZThmNWUyM2E5OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNVQwOTIxMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wODRkMDYwMjAwNTI3NTlkNDU2ODNhMmQzNTM5ZDM4YWM0MDhlMTRkNjRhNWI5MjUwNzZiNmU0YTEyOTU1YTQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.g4J4wXPWgW3VKOTKCGZlXnomNpdUJuAe6-QcNrRGfRo)
> 
> As per the above screenshot, you updated you `branch-A-CodeQuality` using GitHub UI (i.e., the latest `master` branch was merged to `branch-A-CodeQuality` in your fork, which is fine too) but you haven't fetched that merge commit into your local repo yet. Hence, your local `branch-A-CodeQuality` is behind `origin/branch-A-CodeQuality`

Thanks for the guidance!
I've fetched the remote CQ branch into my local CQ branch, then merged the CQ branch to master like the following:
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/109773933/a0b7bc4a-f0a0-4dd9-b2bd-127046d07ba2)
Unfortunately, I couldn't do the PR method for CQ branch, but I've managed to push all the changes to origin/master.

Just for future reference, may I know what was the reason why the master branch was merged into CQ branch? For PR for CQ branch, I did correctly direct the PR route from local CQ branch to local master branch. There was a merge conflict, so I manually resolved the conflicting code in github web browser and confirmed merge. Then I pulled the merged status of remote repo back into my local master, but I faced the issue above (PR merge strangely not performed although checked, CQ branch merged into master).
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/109773933/c1f4c4f7-9c45-4943-a38c-8e9174103c73)

**Comment by damithc** [comment]
> so I manually resolved the conflicting code in github web browser

@jeong-jaeho Doing this kind of changes on the GitHub UI results in extra commits/merges. In this case, it resulted in the master branch being merged to your CQ branch. For beginners, it is best not to resolve conflicts or update branches using GitHub UI as don't get to see what's happening on the Git side when you do something using GitHub UI, resulting in this kind of 'mystery' changes to your fork.

**Comment by jeong-jaeho** [comment]
> > so I manually resolved the conflicting code in github web browser
> 
> @jeong-jaeho Doing this kind of changes on the GitHub UI results in extra commits/merges. In this case, it resulted in the master branch being merged to your CQ branch. For beginners, it is best not to resolve conflicts or update branches using GitHub UI as don't get to see what's happening on the Git side when you do something using GitHub UI, resulting in this kind of 'mystery' changes to your fork.

By the way, I've pushed the CQ branch without PR merging, unlike how I followed proper PR merging for Assertions branch. Will this lose marks in "Followed other requirements specified (e.g., how to use Git/GitHub for each increment, do peer reviews) in at least 4 weeks"?

**Comment by damithc** [comment]
> By the way, I've pushed the CQ branch without PR merging, unlike how I followed proper PR merging for Assertions branch. Will this lose marks in "Followed other requirements specified (e.g., how to use Git/GitHub for each increment, do peer reviews) in at least 4 weeks"?

It should be fine, @jeong-jaeho No penalty.
