### ISSUE TITLE
Request for smoke testing on mac

### ISSUE THREAD

**Issue by aureliony** [nus-cs2103-AY2324S2/forum#412]
I'd like to ask for help to smoke test my .jar file on Mac systems (both x86 and aarch64).

It's located at https://github.com/aureliony/ip/releases. Thank you!

**Comment by Jerome-j** [comment]
Hi I played around with it and it seems OK.

Device M2 Pro Macbook Pro 14"

<img width="833" alt="Screenshot 2024-02-25 at 4 28 48 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/49815108/f4358617-6fdf-4cf9-8c11-1e6cd341b5eb">
