### ISSUE TITLE
Creating fat JAR file help

### ISSUE THREAD

**Issue by DominicFuMJ** [nus-cs2103-AY2324S2/forum#413]
I'm having trouble creating a fat jar file. When I tried to create it and run it, it wouldn't run the GUI but the command line works Please help

**Comment by yisiox** [comment]
@DominicFuMJ How did you create or run it? But do check your `build.gradle` has the correct main class set, something like
```
application {
    mainClass.set("duke.Launcher")
}
```

**Comment by DominicFuMJ** [comment]
I created it using ./gradlew clean shadowJar.
I ran it using by calling java -jar {filename}.jar.

**Comment by DominicFuMJ** [comment]
I can now run the GUI. Thanks
