### ISSUE TITLE
Do we have to include UML diagrams when updating the DG for the TP?

### ISSUE THREAD

**Issue by Arixeyeion** [nus-cs2103-AY2324S2/forum#414]
For this portion of the week 7 project requirements:
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/122505234/044a67ea-41f2-4be7-af7e-2de73a409b30)

there is no mention of whether there is a need to include or update the UML diagrams as part of the TP. We would just like to check if there is a need to do so.

Tagging Team:
@Javiery3889
@KohGuanZeh
@Dethada
@YuZizhen

**Comment by damithc** [comment]
@Arixeyeion Updating UML diagrams is scheduled in a future week. Reason: we haven't covered the _drawing_ aspect of UML diagrams yet (we only covered the _interpreting_ aspect so far)
So, you only need to update the specific sections (and they don't contain UML diagrams).

**Comment by Arixeyeion** [comment]
Thank you prof!
