### ISSUE TITLE
Request for smoke testing for Mac and Linux

### ISSUE THREAD

**Issue by DominicFuMJ** [nus-cs2103-AY2324S2/forum#415]
Can someone help me with my smoke testing? Thank you
The .jar file is located here: https://github.com/DominicFuMJ/ip/releases/tag/A-Release

**Comment by sindhurajain** [comment]
I get this error message on mac:
<img width="570" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/115209308/c3104cea-78d9-4040-a170-925a237dd73d">

**Comment by DominicFuMJ** [comment]
Can someone help me with this error message?

**Comment by DominicFuMJ** [comment]
I think it because I made my code using Java SE 17 and your computer has Java SE 11. Does anyone know how to fix this?

**Comment by sindhurajain** [comment]
I think we're supposed to use Java SE 11 as per the course website:
<img width="715" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/115209308/1ec6a58f-69d1-4262-aa17-bc1ec52f4d67">
https://nus-cs2103-ay2324s2.github.io/website/schedule/week2/project.html

I'm using the Azul build of OpenJDK 11 as per the advisory for mac users

**Comment by DominicFuMJ** [comment]
What do I do?

**Comment by sindhurajain** [comment]
This seems similar: https://github.com/nus-cs2103-AY2324S2/forum/issues/370

Try following the comments here and see if it works

**Comment by DominicFuMJ** [comment]
Got it. Changed the version, made a new .jar file and updated the Release. Please check again. Thanks

**Comment by tankh99** [comment]
Hi there, am getting this error. I think it's still the same issue?
<img width="1125" alt="Screenshot 2024-02-25 at 5 57 43 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/56617918/297ad4fe-4378-46e6-a7ac-99991e610c1c">

**Comment by DominicFuMJ** [comment]
Yes. Trying to fix it.

**Comment by damithc** [comment]
@DominicFuMJ one drastic solution is to uninstall all other Java version from your computer so that you remove the possibility of using the wrong JDK version when building the JAR file.

Other than that, use the terminal to build the jar file, and use the following two commands (after running the first one, check output to confirm you are using Java 11).

```
$ java -version
$ ./gradlew clean shadowJar
```

Also note that you need to restart your IDE/terminal after changing a system variable such as PATH or JAVA_HOME

**Comment by DominicFuMJ** [comment]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/119829202/a91f4594-40cf-4c3a-888f-d0b6cfc83973)
I'm getting this when I try to debug my project. Can someone help?

**Comment by DominicFuMJ** [comment]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/119829202/b5efc407-8b88-4996-92eb-9382ced5291e)
It keep saying that my java version is 21.0.1. How do I change it?

**Comment by DominicFuMJ** [comment]
Hi, can someone help test my .jar file again. I want to see if it works for mac and linux. Thanks

**Comment by E0735389** [comment]
Still the same error.

```
Error: LinkageError occurred while loading main class victor.Launcher
        java.lang.UnsupportedClassVersionError: victor/Launcher has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```

**Comment by E0735389** [comment]
> ![image](https://private-user-images.githubusercontent.com/119829202/307582508-b5efc407-8b88-4996-92eb-9382ced5291e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NjE1OTksIm5iZiI6MTcwODg2MTI5OSwicGF0aCI6Ii8xMTk4MjkyMDIvMzA3NTgyNTA4LWI1ZWZjNDA3LThiODgtNDk5Ni05MmViLTkzODJjZWQ1MjkxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNVQxMTQxMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYzY3YWFkMmI5ZGJkMTg1ZDJhZTA3NDk1YzJkYjVkYjA5ZDQ3MzUzMDM3MmZhNGMyZjJmZDMwMjRlZDhiOWU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MGqMthqJ_8135wSHfNHZ9UdW3rgTuJFeajE1mGyX64o) It keep saying that my java version is 21.0.1. How do I change it?

Prof already replied above --- one drastic solution is to uninstall all other Java versions.

**Comment by DominicFuMJ** [comment]
How do I do that?

**Comment by E0735389** [comment]
Because I'm not using Windows here to test, you can e.g. try following the guide in [How do I uninstall Java on my Windows computer?](https://www.java.com/en/download/help/uninstall_java.html).

**Comment by DominicFuMJ** [comment]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/119829202/8ddb9abd-27ed-4ff8-af17-2e09b62748e2)
I tried to delete the SDK 17, but when I run the Launcher, I get this error message.
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/119829202/5ca54b5d-84b8-4b81-9695-6181cedba03c)
When I try to click on the "Try to find SDK" button, It creates the SDK 17 and shows this message.
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/119829202/bf370db9-d7e7-407a-8945-9c646a76eb27)
Please help. Thank you

**Comment by DominicFuMJ** [comment]
My Java version is now 11.0.22.
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/119829202/2d5f97f3-f44e-4681-8fd2-b25d282393e8)
I recreated a new .jar file and send it to the release.

**Comment by sindhurajain** [comment]
I tried your latest jar file on m2 mac and the GUI opened and I was able to carry out functions but I also got this message in my terminal:
<img width="564" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/115209308/06c495b3-649f-4d58-b221-fde6f5ef1e84">

**Comment by DominicFuMJ** [comment]
The Update File Error is my personal error message which displays when it cannot create a new data file to store all of the data.

**Comment by DominicFuMJ** [comment]
This occurs for the victor.jar. If I need to fix this, can someone help?

**Comment by DominicFuMJ** [comment]
I made some changes to the code so that the update file error no longer is a problem. Can someone help check if it still works for mac and linux? Thanks

**Comment by sindhurajain** [comment]
it works on m2 mac now, GUI works, saving and loading works, but I get that fxml warning though I don't think it's an issue (see https://github.com/nus-cs2103-AY2324S2/forum/issues/312)

**Comment by DominicFuMJ** [comment]
Thanks

**Comment by DominicFuMJ** [comment]
Just waiting to see with anyone with linux can help smoketest.

**Comment by DominicFuMJ** [comment]
Also, just confirming, I just need to post the .jar file in the github release and it is considered submitted right? Thanks

**Comment by damithc** [comment]
> Also, just confirming, I just need to post the .jar file in the github release and it is considered submitted right? Thanks

Yes, that's right @DominicFuMJ
