### ISSUE TITLE
Naming format for tP features issue tracker

### ISSUE THREAD

**Issue by Javiery3889** [nus-cs2103-AY2324S2/forum#417]
Hi, I would like to ask for the features that our team wishes to implement on Github issues must it be in the user story format? We are more inclined to name each issue with the feature description instead, e.g. "Update `edit` command".

Thanks!

Tagging my group: @AY2324S2-CS2103-F15-1

**Comment by damithc** [comment]
@Javiery3889 recording user stories in the issue tracker helps in tracking user requirements (i.e., using the issue tracker to track user requirements as well as features/bugs/tasks etc,, thus reducing the need for a dedicated requirements management tool), but it is not a hard requirement.
