### ISSUE TITLE
Messages.getErrorMessageForDuplicatePrefixes not giving deterministic error message

### ISSUE THREAD

**Issue by wxiaoyun** [nus-cs2103-AY2324S2/forum#418]
# Issue
I tried adding a new field to person, with cli prefix of "/nn" (nusnet id), but the error message generator method (Messages.getErrorMessageForDuplicatePrefixes) does not seem to produce duplicatePrefix error message in a consistent order. As such, the parse_repeatedNonTagValue_failure test is failing.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/81742181/79a23c77-d2e5-4662-84b9-87ab9b1b3970)

## Edited test
- I have tried: reordering the prefix in the expected output, but the generated expected error message is unaffected (it uses an unordered set)
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/81742181/e8626823-eff4-44f5-bbd1-ee72f227bdea)

**Comment by damithc** [comment]
@ForAeons While waiting for peer inputs, just a side note: If the current test structure is inadequate/unsuitable, you may change it as you see fit.

**Comment by wxiaoyun** [comment]
> @ForAeons While waiting for peer inputs, just a side note: If the current test structure is inadequate/unsuitable, you may change it as you see fit.

Thanks prof,

Resolved by sorting the prefixes

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/81742181/6075d5c6-a421-4f3e-a42f-978146a5df45)
