### ISSUE TITLE
How do I know if i committed and tagged properly?

### ISSUE THREAD

**Issue by bgopi23** [nus-cs2103-AY2324S2/forum#42]
I commited, then tagged, and then pushed. im currently doing level 2 (pushed level 0 and 1). how do i know if im doing it properly. im very scared as i continue on till level 6 if my commits/tags are wrong the whole thing will be messy

**Comment by damithc** [comment]
@bgopi23 we will be setting up a dashboard for you to self-monitor if your iP increments are detected by our scripts. However, this will take a few more days, as we are still collecting GitHub usernames from students.

In the meantime, let's give others a chance to share if they figured out ways to cross-check their tagging/committing/pushing.

> im very scared as i continue on till level 6 if my commits/tags are wrong the whole thing will be messy

Not to worry, these things can be corrected later, if needed.

**Comment by camille-readbean** [comment]
There is a command to see the associated tag.  
  
`git show level-1`
will show you the what commit level-1 is tagged to:

```
ip> git show level-1
tag Level-1
Tagger: [Snipped]
Date:   Mon Jan 22 18:00:00 2024 +0800

Echo and bye function

commit 85e9b72e761065[snipped] (tag: Level-1)
Author: Chin Rui Bin <>
Date:   Mon Jan 22 18:00:00 2024 +0800

    Level-1 Set up echo function

```

will update #36 with this as well
