### ISSUE TITLE
Can't upload the .jar file to the release.

### ISSUE THREAD

**Issue by DominicFuMJ** [nus-cs2103-AY2324S2/forum#420]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/119829202/bdce42af-8c9b-47d5-84ed-f7aee7232d7f)
I've been trying to upload the new .jar file to the release, but it has not been working. I tried to do ./gradlew clean shadowJar again and upload the new .jar file, but I still get this error message.

**Comment by sindhurajain** [comment]
I think it's just a browser problem - I found a similar problem here - https://github.com/orgs/community/discussions/40734

try clearing your browser cache or using a different browser

**Comment by DominicFuMJ** [comment]
Got it. I used Microsoft edge and it works. Thanks
