### ISSUE TITLE
Request for smoke testing for Mac and Linux 

### ISSUE THREAD

**Issue by DominicFuMJ** [nus-cs2103-AY2324S2/forum#421]
Can someone help me with my smoke testing? I tried to make the code work for java 11, but want someone to test it for me. Thank you
The .jar file is located here: https://github.com/DominicFuMJ/ip/releases/tag/A-Release

**Comment by damithc** [comment]
@DominicFuMJ On Windows;


>C:\todelete>java -jar victor.jar
Error: LinkageError occurred while loading main class victor.Launcher
        java.lang.UnsupportedClassVersionError: victor/Launcher has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0


Seems you used Java 17 this time.

**Comment by DominicFuMJ** [comment]
I'm not sure how to change it from Java 17 to Java 11. I tried to do what #370 did, but it still use Java 17.

**Comment by DominicFuMJ** [comment]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/119829202/8ddb9abd-27ed-4ff8-af17-2e09b62748e2)
I tried to delete the SDK 17, but when I run the Launcher, I get this error message.
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/119829202/5ca54b5d-84b8-4b81-9695-6181cedba03c)
When I try to click on the "Try to find SDK" button, It creates the SDK 17 and shows this message.
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/119829202/bf370db9-d7e7-407a-8945-9c646a76eb27)
Please help. Thank you

**Comment by damithc** [comment]
@DominicFuMJ, 

1. Ensure you have JDK 11 installed, and all other versions of JDK have been removed
2. Open a terminal and run `java -version` to confirm JDK 11 is the default. You might need to set the system variables PATH and JAVA_HOME to accomplish this step.
3. To give Intellij a clean slate, you can clone your fork to a new location in your computer, open it in Intellij, and ensure the JDK is set correctly, as described in steps 3(a) and 3(b) [here](https://se-education.org/guides/tutorials/gradle.html#:~:text=Confirm%20the%20correct%20Java%20version%20is%20being%20used)

**Comment by DominicFuMJ** [comment]
Hi. I managed to change it to JDK 11 and would like someone to help check to determine whether the updated .jar file works for mac and linux. Thanks
