### ISSUE TITLE
A-UserGuide

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#422]
<img width="770" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/73015364/c04fae15-b2ae-4839-8b9a-bdd60bb42197">

How do you make the `A-UserGuide` and `Published-UG` tags green? Is it by pushing our userguide changes with A-UserGuide tag?

**Comment by E0735389** [comment]
From https://nus-cs2103-ay2324s2.github.io/website/se-book-adapted/projectDuke/index.html#a-userguide :

> Go to https://{your username}.github.io/{repo name}/ to view the user guide of your product.

If that doesn't work, the tag won't turn green.

**Comment by damithc** [comment]
@bgopi23 `A-UserGuide` is based on Git tags. `Published UG` is based on if your UG is actually available for viewing (as @E0735389 mentioned)

BTW, you can click the 'details' link to find what each tag means.
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/d5b29b8c-d718-4bd7-9386-774ef5c2a562)

**Comment by baskargopinath** [comment]
thank u @damithc @E0735389
