### ISSUE TITLE
How does @nus-se-bot find the "related increments"?

### ISSUE THREAD

**Issue by E0735389** [nus-cs2103-AY2324S2/forum#423]
For forum questions, usually @nus-se-bot will post a comment such as

> Tagging a few other students (randomly selected) who have completed **related increments**, in case they can help

While it's pretty easy to detect which student have completed which increment, I find it quite interesting that the bot can supposedly tell which increment is **related** to a particular question on CS2103T forum.

How does the bot do that?

**Comment by damithc** [comment]
@E0735389 Good question. While the post is created using a bot account, it is not run automatically. Any time I see that a post needs attention from other students, I trigger the bot manually, before which I manually configure which increments/OS/expertise are relevant to the issue, how many students to tag etc.
