### ISSUE TITLE
Testcases fail after using Messages.format in tutorial_adding_command week 6

### ISSUE THREAD

**Issue by gavin331** [nus-cs2103-AY2324S2/forum#426]
From #352 , Messages.format solved the bug in RemarkCommand.java. However, after using Messages.format, the RemarkCommandTest.java failed. The actual and expected output below is from 1 of the failed testcase.

Expected :seedu.address.logic.commands.CommandResult{feedbackToUser=Added remark to Person: seedu.address.model.person.Person{name=Alice Pauline, phone=94351253, email=alice@example.com, address=123, Jurong West Ave 6, #08-111, remark=Some remark, tags=[[frien ...

Actual   :seedu.address.logic.commands.CommandResult{feedbackToUser=Added remark to Person: Alice Pauline; Phone: 94351253; Email: alice@example.com; Address: 123, Jurong West Ave 6, #08-111; Tags: [friends], showHelp=false, exit=false}

**Comment by chiralcentre** [comment]
I faced the same bug too; don't change the code to the one in issue #352. Either that, or you must refactor the unit tests to account for the change in the generateSuccessMessage method. For example, you can see in your log output that the expected person is a Person object, but the actual output is a String.

**Comment by gavin331** [comment]
Alright thanks!
