### ISSUE TITLE
TP Coding

### ISSUE THREAD

**Issue by chiralcentre** [nus-cs2103-AY2324S2/forum#427]
Can I check with the teaching team if we are allowed to start coding for v1.2 of the TP in conjunction with v1.1, or must we strictly code for v1.2 after v1.1 is completed? For example, my team is thinking of merging the code from tutorial 2 of setting up the codebase in week 6 as it is relevant to our project, but we are not sure if we can merge the PR before we do the UG/DG.

**Comment by damithc** [comment]
@chiralcentre It is OK to stay a little bit ahead of the schedule e.g. (0.5 week) but don't go too ahead either, because (a) it's harder to learn from, and correct, mistakes if you are long past the mistake by the time you learn about it (b) some tP tasks are tied to topics/tutorials covered in that week or the week immediately before.

**Comment by chiralcentre** [comment]
Hi Prof, thank you for the response. I noted in the week 7 workflow that we are allowed to start implementing v1.2 if we have time. To clarify again, does this mean express approval for us to start implementing features for v1.2 after v1.1 is done? At the same time, can I check again if we are allowed to merge in code from the RemarkCommand tutorial if it is relevant to our project while we are still in v1.1?

**Comment by damithc** [comment]
> I noted in the week 7 workflow that we are allowed to start implementing v1.2 if we have time. To clarify again, does this mean express approval for us to start implementing features for v1.2 after v1.1 is done? 

No need. You can go ahead.

>At the same time, can I check again if we are allowed to merge in code from the RemarkCommand tutorial if it is relevant to our project while we are still in v1.1?

Yes, we don't prohibit that, although probably better to delay it until the whole team is done with v1.1? It feels more 'normal' for the whole team to work together to finish v1.1 before some members start going into v1.2 tasks. It gives an incentive for faster team members to help slower ones, and an incentive for slower members to catch up so that the whole team can move forward faster.

**Comment by chiralcentre** [comment]
Noted Prof! Just to check for v1.1 are we required to use the issue tracker? As the work for v1.1 is all documentation related, can I check if we are allowed to use the issue tracker only for v1.2 onwards?

**Comment by damithc** [comment]
@chiralcentre You need to use issue tracker to record code-related tasks, and documentation files are a form of code too. So, you need to use the issue tracker for v1.1. In fact a goal of v1.1 is to practice the workflow, which means the workflow should be the same in v1.1 and v1.2.

**Comment by chiralcentre** [comment]
Thank you Prof for the response. However, as everyone in the team will be updating the same sections of the UG/DG (eg 2-4 user stories person), can I check how does a typical allocation of tasks via issues for documentation look like?

**Comment by damithc** [comment]
@chiralcentre Once you identify the feature areas each member works on, you can create issues such as `List-related UG updates`, `Find-related DG updates`

**Comment by chiralcentre** [comment]
Thank you Prof for the response. If every member on the team will be working on the same section (eg for user stories, I add user story 1-5, teammate adds user story 6-10 and so on), how will the issues look like? Will it be just be the same issues `update UG` duplicated five times?

**Comment by damithc** [comment]
@chiralcentre I think you missed this key phrase in my previous answer `Once you identify the feature areas each member works on, ...`
So,
`List-related UG updates` --> assigned to person-A
`Delete-related UG updates` --> assigned to person-B
and so on...

**Comment by chiralcentre** [comment]
Thank you Prof for the response! I misunderstood your response earlier.
