### ISSUE TITLE
Refactoring tp codebase

### ISSUE THREAD

**Issue by aureliony** [nus-cs2103-AY2324S2/forum#428]
Our team would like to refactor a large chunk of the tp codebase to improve extensibility and SWE principles.

This involves changing a significant portion of the codebase (in a single commit or otherwise), but the end product remains unchanged to the user.

Would this be acceptable or considered as violating any of the tp constraints?

**Comment by damithc** [comment]
@aureliony It is fine to refactor the existing code, but not _rewrite_ it. So, the code should be evolved in small steps, not deleted and rewritten in one go.
