### ISSUE TITLE
Is there supposed to be 2 jar files when you create a new shadow Jar file using Gradle

### ISSUE THREAD

**Issue by Darkarche3** [nus-cs2103-AY2324S2/forum#429]
Hi, I created the fat Jar file using Gradle. However, I have 2 files Area.jar and Ip.jar. My code works when I place the jar files in the same directory, but I am unsure if I should be getting 2 jar files. Is this the same for everyone?

I searched online and apparently the recent updates caused there to be 2 jar files, one from jar and one from shadow Jar.  However, I wish to double-confirm here.

**Comment by dillontkh** [comment]
Yup I get 2 `.jar` files as well.

**Comment by damithc** [comment]
@Darkarche3 @dillontkh Ignore the `ip.jar`; use the other one.

You can remove the line `dependsOn("distZip", "distTar")` in build.gradle to prevent the extra jar file being created.

**Comment by Darkarche3** [comment]
Thank you very much for your help!! The issue has been resolved!
