### ISSUE TITLE
Mismatched Tagging

### ISSUE THREAD

**Issue by yeoshuheng** [nus-cs2103-AY2324S2/forum#43]
I accidentally tagged and declared a certain level as completed (eg. level 1), but after a few more levels I realised a potential bug in level 1 and fixed it in a commit tagged in under another level (eg. Level 6).

Will this be an issue? Since the commit now technically belongs to both level 1 and level 6...

Will the completion of each level be graded according to the tags? Or would it be graded upon the final version (the one on level 6)?

**Comment by damithc** [comment]
@yeoshuheng It's fine. Don't worry about it.
For more info, see Q2 in this FAQ https://nus-cs2103-ay2324s2.github.io/website/schedule/week2/project.html#faq-about-ip-increments
