### ISSUE TITLE
REquest for smoketesting

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#431]
https://github.com/bgopi23/ip/releases

hi could anyone help me test if it works?

**Comment by Rishit02** [comment]
Seems to work fine. 
Get this weird warning though:

> Feb 26, 2024 2:12:31 PM com.sun.glass.ui.mac.MacApplication lambda$waitForReactivation$6
> WARNING: Timeout while waiting for app reactivation

But otherwise works fine.

**Comment by chengjunyuan** [comment]
Works fine on Mac! 😄

**Comment by baskargopinath** [comment]
thanks @chengjunyuan @Rishit02
