### ISSUE TITLE
Help with Smoke Testing Please

### ISSUE THREAD

**Issue by Jerome-j** [nus-cs2103-AY2324S2/forum#433]
Dear Friends,

Kindly assist to do smoke testing on my repo please :)

Manual: https://jerome-j.github.io/ip/
App Download: https://github.com/Jerome-j/ip/releases/tag/A-Release

Your help is very much appreciated!

Thank you!

**Comment by baskargopinath** [comment]
works for me but i think you should display a bye message before terminating @Jerome-j

**Comment by Jerome-j** [comment]
Thanks @bgopi23. However I think I personally prefer the quit immediately approach as mentioned in #407 pointed out by Prof Damith.

Thanks very much Gopi and have a great recess week!
