### ISSUE TITLE
Jar file not saving or reading data to text file

### ISSUE THREAD

**Issue by Alteqa** [nus-cs2103-AY2324S2/forum#434]
When I launch the chatbot on my intellij it runs with no problem, howeverm when I run it using the jar file it isnt able to read or add anything to the data file or arraylist andI am not sure why.

**Comment by damithc** [comment]
@Alteqa It might help if you share more details about the problematic behavior e.g., what's the error message (if any)?

**Comment by dillontkh** [comment]
I suspect the problem could lie in line `18` of your `Storage.java`:

`"src/main/java/data/hirwan.txt";`

You are using an absolute file path, which means when you compile the jar file, the path to your data file is no longer valid.

Try using a relative path like `./data/hirwan.txt` instead.

**Comment by damithc** [comment]
@Alteqa Did @dillontkh's suggestion help you resolve this issue?
