### ISSUE TITLE
Should source code be updated when release is updated?

### ISSUE THREAD

**Issue by sdevih** [nus-cs2103-AY2324S2/forum#436]
Hi, I have submitted the release on time, but I recently made a minor bug fix to my code. I then pushed the most recent version to my fork and created a new JAR file. 

When I updated my release with the newer JAR file, it only showed the updated JAR file, but the source code was not updated as seen below. I encountered a similar issue when trying to create a new release as well.

Would that be alright or is there anything else I should be doing so that the source code is updated? Thank you!
![MicrosoftTeams-image (4)](https://github.com/nus-cs2103-AY2324S2/forum/assets/111141881/f05a2b56-01f8-4552-8e67-c83133da8812)

**Comment by damithc** [comment]
@sdevih If there is a change to the code, you should create an entirely new release (because the source zip files are autogenerated by GitHub when you create the release).
For iP grading purposes, the current state of affairs is fine.
