### ISSUE TITLE
[IP] Forgot to release v0.1

### ISSUE THREAD

**Issue by alvislowyh** [nus-cs2103-AY2324S2/forum#437]
I forgot to release v0.1 but i went over to my old branch branch-A-JavaDocs to create a jar file and released it as pre release.
However, after that the portion of branch-A-JavaDocs got unticked on the ip dashboard. Did i do something wrong?
<img width="774" alt="Screenshot 2024-02-26 at 11 00 38 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/157791089/258ba6fc-29b0-4596-a5b0-05b067a234c8">

**Comment by baskargopinath** [comment]
i see the branch in your repo so i think the dashboard will turn green when it updates

**Comment by UdhayaShan1** [comment]
Making a guess here, since it updates when branch is merged with master and pushed.

I noticed updates to the java-doc branch recently, did you merge with master and push it?

**Comment by damithc** [comment]
@beefsausagee [This troubleshooting tip](https://nus-cs2103-ay2324s2.github.io/dashboards/contents/ip-progress.html#:~:text=Why%20is%20an%20increment%20related%20to%20a%20branch%20not%20green%3F) (at the top of the iP dashboard) has information on how to resolve your issue.
