### ISSUE TITLE
Code tracing tutorial 3 Removing Fields typo

### ISSUE THREAD

**Issue by UdhayaShan1** [nus-cs2103-AY2324S2/forum#438]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39399745/226816a8-b8eb-4911-a9fd-ad15d0c6d6b8)

This should be PersonListCard.fxml

**Comment by damithc** [comment]
Thanks @UdhayaShan1 
I've noted it, to be fixed in the upstream repo next semester.
