### ISSUE TITLE
Level-5

### ISSUE THREAD

**Issue by g-tejas** [nus-cs2103-AY2324S2/forum#44]
![CleanShot 2024-01-22 at 23 37 34@2x](https://github.com/nus-cs2103-AY2324S2/forum/assets/76802638/a442bc04-27e2-4b57-8ee9-af980e83d381)

For this Level-5, if we renamed our chatbot to another name do we still call it DukeException?

**Comment by damithc** [comment]
@g-tejas This is just an example name. You can use any suitable names for your exception classes.
