### ISSUE TITLE
Smoketest help (windows / linux)

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#440]
https://github.com/bgopi23/ip/releases/tag/A-Release2

could anyone help me smoketest this on windows and linux and let me know please
thanks in advance

**Comment by camille-readbean** [comment]
LGTM! Running on Windows 11 Java 11

**Comment by Teeesa7** [comment]
Works! Ran on Windows 11 Java 11 too

**Comment by NeoHW** [comment]
works well on mac java 11!

**Comment by ongzhili** [comment]
LGTM (Windows 10 Java11)

**Comment by baskargopinath** [comment]
thank u @ongzhili @NeoHW @Teee728 @camille-readbean
