### ISSUE TITLE
Smoke Test Help (Windows/ Linux)

### ISSUE THREAD

**Issue by choowengyan** [nus-cs2103-AY2324S2/forum#441]
Hi ! Would appreciate if anyone could help with smoke test on both Windows and Linux! You are welcomed to test it on Mac as well! Appreciate if you could let me know the result. 

You can download the release from [here](https://github.com/choowengyan/ip/releases/tag/A-UserGuide)

Thanks alot!

**Comment by simkianseng** [comment]
LGTM :smile:.

Perhaps can add this line of code, `dialog.setMinHeight(Region.USE_PREF_SIZE);` to the `DialogBox` constructor? This fixes the issue of the content of the label not being fully shown as it seems that overflow content appears to get cut off as shown below.

<img width="283" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/67402819/79e3d288-a25d-4457-b67b-9a16c890a31d">

**Comment by choowengyan** [comment]
@SimKianSeng Thank you so much! May I check with you if you tested it on Windows or Linux? 
Your recommendation of setting min height to the dialog box constructor was a great suggestion as well! Thanks!

**Comment by simkianseng** [comment]
Windows

**Comment by cbj252** [comment]
Hello senior from a previous batch here, testing on Ubuntu 22.04.3, accessed through Oracle VM VirtualBox.

All the commands work, but some of my commands are getting "eaten up" like the first command in my image, where I entered a command, but on the screen my command is gone and the system returns an invalid command. To be frank, I'm unsure what causes this issue, but I've done some testing and here's what I have:

- The most consistent way to trigger the bug is to highlight the command (with your mouse) before you put it in. I've never had a command where I did this succeed. However, this isn't the only way to trigger the bug - I've had it happen without highlighting my text.
- This occurs regardless of whether the command was valid or not.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/73173225/95f5d97b-8b16-46ab-a9a9-982db3c7a812)

**Comment by choowengyan** [comment]
@cbj252 Hi! Thanks alot for your input! I have just updated a new release with the link attached above (alternatively can get it from [here](https://github.com/choowengyan/ip/releases/tag/A-UserGuide)) 
Do you mind helping me to smoke test it again? I have fixed the commands "eaten up" issue and hopefully you are able to see the command guides on the GUI. 

Thanks!

**Comment by lhy-hoyin** [comment]
Hi @choowengyan, I'm a senior from a previous batch and is helping you to smoke test using Linux (Ubuntu 22.04.4).
For some context:, running `java --version`
```shell
openjdk 11.0.22 2024-01-16
OpenJDK Runtime Environment (build 11.0.22+7-post-Ubuntu-0ubuntu222.04.1)
OpenJDK 64-Bit Server VM (build 11.0.22+7-post-Ubuntu-0ubuntu222.04.1, mixed mode, sharing)
```

Running `java -jar Whisper.jar` gives:
```shell
Feb 29, 2024 1:55:31 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @1ee178c8'
Error in glXCreateNewContext, remote GLX is likely disabled
```

Testing of basic functionality seems to go well.
Good effort on the bounds checking of the task index inputted by the user :+1: 

---

If I may, I have some suggestions for the UI.

Currently, if the user enlarges the window (both vertically and horizontally) manually, the UI does not expand to fill the excess space, resulting the application looking ugly.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/88828097/00eebcb3-d688-42b9-b391-1e7d580a5c68)

**Comment by choowengyan** [comment]
@lhy-hoyin thanks for the testing! Will try to update the UI suggested!

**Comment by cbj252** [comment]
> @cbj252 Hi! Thanks alot for your input! I have just updated a new release with the link attached above (alternatively can get it from [here](https://github.com/choowengyan/ip/releases/tag/A-UserGuide)) Do you mind helping me to smoke test it again? I have fixed the commands "eaten up" issue and hopefully you are able to see the command guides on the GUI.
> 
> Thanks!

Hello, sorry for the late comment.

The help function now works, but I still have my commands eaten up:

![Screenshot from 2024-02-29 22-11-37](https://github.com/nus-cs2103-AY2324S2/forum/assets/73173225/eabe4379-7542-4a8d-8030-aa6f2c2c12f2)
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/73173225/58c764b5-62c8-48f9-95f6-b506192450a9)
![Screenshot from 2024-02-29 22-12-09](https://github.com/nus-cs2103-AY2324S2/forum/assets/73173225/545b0492-9ea4-4cbc-9d34-cad282876be5)

Apologies, I was not precise enough in my previous testing though: the command goes through, but the system appears to generate a new interaction where the user inputs an empty command which is responded to as "invalid" by the system. This new interaction is then put just below the correct interaction (see image 2). I've confirmed this occurs on both your previous and new release.

**Comment by lhy-hoyin** [comment]
Hi @choowengyan, I'm not too sure on the timeline, but is the smoke testing period over? If your submissions have been made, perhaps you want to close this issue?
