### ISSUE TITLE
Smoke Test (Windows/Linux)

### ISSUE THREAD

**Issue by dedsecrattle** [nus-cs2103-AY2324S2/forum#443]
Hello,

Please help me doing smoke test on Windows and Linux Platform 

Here is my Release - [Link](https://github.com/dedsecrattle/ip/releases/tag/A-Release)

**Comment by Wongqingyee** [comment]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/122243884/dedb1996-e693-45c4-9a03-b2472521c164)
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/122243884/b87b9278-1b13-4b67-a2eb-e50ad6faf12e)

looks good to me! (from Windows)

**Comment by cbj252** [comment]
Hello, senior from a previous batch here.

Works on Ubuntu 22.04.3, accessed through Oracle VM VirtualBox.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/73173225/d60e8e33-f5a8-40fa-95e9-db3f9108181e)

**Comment by dedsecrattle** [comment]
Thank You Everyone :)
