### ISSUE TITLE
Smoke Test Help for Windows/Linux!

### ISSUE THREAD

**Issue by ZhiWei1010** [nus-cs2103-AY2324S2/forum#445]
Hello! would anybody be able to help with smoke tests on Windows/Linux! Thank you!
You can download my release [here](https://github.com/ZhiWei1010/ip/releases/tag/A-Release)
You can access my user guide [here](https://zhiwei1010.github.io/ip/) as well

**Comment by whitesnowx** [comment]
Using Windows 10 with Java 11 works fine, tested the functions and displays similar to the user guide. 
👍 
![Capture](https://github.com/nus-cs2103-AY2324S2/forum/assets/68015911/534445f5-b460-4141-afbf-61bd58092fbc)

**Comment by chiaryan** [comment]
LGTM on my vm running ubuntu :)

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/53717471/fd7fe487-d429-43cf-8e86-f9dcb25dcc2d)

**Comment by ZhiWei1010** [comment]
Thank you @whitesnowx and @chiaryan !
