### ISSUE TITLE
Confused about Integration Approaches

### ISSUE THREAD

**Issue by jyztintan** [nus-cs2103-AY2324S2/forum#446]
In Week 7 topics, we learnt about:
- Late and one time vs early and frequent
- Big-bang vs incremental

Other than the aspect of when integration is started, I can't really see much differences between these 2 comparisons.
Isnt Late and One time <=> Big-Bang
and Early and frequent <=> Incremental

Any advice on this? Thanks!

**Comment by damithc** [comment]
Good question @jyztintan 
As this is not urgent, let's wait a while to see if other classmates have any insights to share about this.

**Comment by ZhiWei1010** [comment]
I have the same thoughts as you and feel that the association is valid! @jyztintan

**Comment by damithc** [comment]
As we just finished week 7 (which covers the[ relevant topic](https://nus-cs2103-ay2324s2.github.io/website/schedule/week7/topics.html#w7-5-integration-approaches)), this could be a good time to revive this discussion.

**Comment by jeremiahlzz** [comment]
My impression is also that the two are very similar and can sometimes be used interchangeably.


One small difference I can think of is with regards to the type of project you have; **waterfall or agile**:

* In waterfall, you are developing with a clear end in mind. The definition of late and one time is: 

> Late and one-time: wait till all components are completed and integrate all finished components near the end of the project.

which is well representative of waterfall. Thus, `Late and One time / Early and Frequent` would be more applicable.

* In agile, you are iteratively developing, with small goals along the way.  The definition of big bang is:

> Big-bang integration: integrate all components at the same time.

which has no mention of waiting for an `end of project`. We can simply wait for all major components and start integrating only at the end of each sprint. Thus, `Big-bang / Incremental` would be more applicable.

**Comment by damithc** [comment]
Let me add to this discussion with an example. 
Suppose there is a project that goes from Jan to Dec. The product has 5 sub components, A,B,C,D,E. Each component is developed in a separate branch of the repo.

Option 1: Do the first (and only) integration in December (just before delivery). Integrate A and B first, and then C, then D, and then add E as the last step. For example, merge A and B branches first, test, fix any issues, and then merge branch C, test, and fix any new issues, and so on.

Option 2: Integrate at the end of each month. Every time the integration happens, all new code from all 5 components are put together (e.g., merge all 5 branches) before testing and fixing any problems that emerged.

Now, try to match the following integration approaches to the above 2 options:
i) late-and-one-time
ii) early-and-frequent
iii) big bang
iv) incremental

**Comment by jyztintan** [comment]
Thanks Prof for the alternative perspective!

Option 1 it seems like it is late-and-one-time but incremental:
- Late and one time: involves a single phase of integration just before delivery.
- Components are still integrated one by one in a sequence, allowing for testing and issue resolution at each step (albeit might be rushed).

Option 2 seems like it is early-and-frequent but is always a new "big bang" at every iteration:
- Integration happens at the end of each month, allowing for frequent testing and issue resolution.
- At every iteration, this approach still involves integrating all new components and code together before testing.

Thank you everyone for your inputs, marking this issue as resolved.

**Comment by damithc** [comment]
> Thanks Prof for the alternative perspective!
> 
> Option 1 it seems like it is late-and-one-time but incremental:
> 
> * Late and one time: involves a single phase of integration just before delivery.
> * Components are still integrated one by one in a sequence, allowing for testing and issue resolution at each step (albeit might be rushed).
> 
> Option 2 seems like it is early-and-frequent but is always a new "big bang" at every iteration:
> 
> * Integration happens at the end of each month, allowing for frequent testing and issue resolution.
> * At every iteration, this approach still involves integrating all new components and code together before testing.
> 
> Thank you everyone for your inputs, marking this issue as resolved.

@jyztintan That's correct. I used this example so that you can also see there are two dimensions to integration.
1. **When** (and how often) you integrate
   * late and one-time
   * early and frequent
2. **In what order** you integrate the components
   * Incremental (top-down, bottom-up, sandwich -- these three are in [this optional topic](https://nus-cs2103-ay2324s2.github.io/website/book/integration/approaches/topDownVsBottomUp/))
   * big bang

The two dimensions are orthogonal. So, any option from the first can be combined with any option from the second.

The _continuous integration_ approach that we use in the tP is an extreme version of early and frequent. Normally this approach is incremental (i.e., add only one small change at a time) but can stray towards big bang if your PRs contain multiple big changes.
