### ISSUE TITLE
Smoke Test my iP for Mac

### ISSUE THREAD

**Issue by chiaryan** [nus-cs2103-AY2324S2/forum#447]
Hi everyone,

I'm looking for people to help me test whether my bot runs on other systems. in particular I want to see whether it runs on Mac platform.
You can download the JAR File [here](https://github.com/chiaryan/ip/releases/download/A-Release2/louie.jar)

My [user guide](https://chiaryan.github.io/ip/) if anyone wants to try out the commands :)

**Comment by jyztintan** [comment]
Hello, I just tested it on my Macbook M3 Pro, and it works fine.

I like the prioritise/deprioritise feature!

**Comment by chiaryan** [comment]
@jyztintan, thanks so much!
