### ISSUE TITLE
Smoke test help for Mac and Linux

### ISSUE THREAD

**Issue by nichee** [nus-cs2103-AY2324S2/forum#449]
Hey, Looking for people to help with smoke testing!
The download is here: https://github.com/nichee/ip/releases/tag/A-Release2

Thanks so much!

**Comment by cbj252** [comment]
Hello, senior from a previous batch here, testing on Ubuntu 22.04.3 via Oracle VirtualBox.

Your application runs, but always in an extremely small window that can't be resized. I've tried some methods to expand it, but could not do so.

Commands are still functional, like the bye command.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/73173225/2efdb024-ece9-48dd-bebe-b1b56ac0d467)

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/73173225/8df0001a-fb25-4d3e-a51e-93115f60e7d2)

**Comment by baskargopinath** [comment]
works on mac @nichee

**Comment by hansstanley** [comment]
Hi, senior here from a previous batch testing on Fedora 39 and openjdk 11.0.22.

On the first run, your app runs properly sized (but not resizable), but after closing and relaunching it, it becomes a really small window like others have experienced.

![Screenshot from 2024-03-02 08-58-46](https://github.com/nus-cs2103-AY2324S2/forum/assets/20805849/0f39216a-bd32-4ca1-afa2-1682bd4b8b83)

The commands seem to work well with good input, but there are a couple issues:

- The help message that lists all the available commands does not mention "find"
- Commands that take in a datetime parameter return a Java runtime error message when the datetime is not properly formatted

![Screenshot from 2024-03-02 08-56-28](https://github.com/nus-cs2103-AY2324S2/forum/assets/20805849/68d2c262-ce3d-4966-a102-84838bf16ee8)

**Comment by francisyzy** [comment]
Hello, senior from a previous batch here, testing on Kali. Works on the first try with the correct window size. Basic commands work well!

<img width="788" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/24467184/b4a65ee4-613e-4b98-8bae-d770300c9980">

**Comment by nichee** [comment]
Thanks! @francisyzy @hansstanley @bgopi23 @cbj252 
Will try to fix the resizing bug -_-
