### ISSUE TITLE
Regarding Main method for Application

### ISSUE THREAD

**Issue by dedsecrattle** [nus-cs2103-AY2324S2/forum#45]
I've few questions to ask - 

1. Can we modify the filename of the bot i.e Duke.java to our bot name i.e "botname.java"
2. Do we need to commit with specific messages for all the Levels ?
3. What should be the main entry point for the application (i.e I've created an Main.java file as an entry point for the bot)

**Comment by damithc** [comment]
> also is there any format or guidelines for the commit messages?

@dedsecrattle We are scheduled to start following the commit message format from week 3 (but you can start now if you want) -- See https://nus-cs2103-ay2324s2.github.io/website/admin/standardsAndConventions.html

**Comment by dedsecrattle** [comment]
Okay Thanks Prof

**Comment by dedsecrattle** [comment]
Done
