### ISSUE TITLE
Smoke Test Help

### ISSUE THREAD

**Issue by jonpwk** [nus-cs2103-AY2324S2/forum#450]
Hey, Looking for people to help with smoke testing!
The download is here: https://github.com/jonpwk/ip/releases/tag/v0.3

Thanks so much!

**Comment by damithc** [comment]
@jonpwk I suggest you check for all three platforms, just in case

**Comment by chin-herng** [comment]
Testing on Windows 11.

Your application does not run. The following error is displayed on the command window:

```
Error: JavaFX runtime components are missing, and are required to run this application
```

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/44641849/9ab52ba8-5faa-47a1-997c-0b0907c2d4c5)

**Comment by nichee** [comment]
Tested on Windows 11 with openJDK
![Screenshot_8](https://github.com/nus-cs2103-AY2324S2/forum/assets/45154216/32815e08-8803-4c18-a5f3-ea126d6c7dae)

App launches but "bye" command does not close the app.
There's also output to the CLI, not sure if it's intentional.
