### ISSUE TITLE
Error initializing QuantumRenderer

### ISSUE THREAD

**Issue by alfaloo** [nus-cs2103-AY2324S2/forum#451]
Hi all, thank you for visiting my thread.

Im having the issue that when I run my iP code through gradle, Im getting the error:
```java
Unsupported JavaFX configuration: classes were loaded from 'unnamed module @40040d57'
java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
```

I am aware that this issue has been posted to the forums before, however, mine is slightly different because if I just run my JAR file or click run at the top right for my Launcher, they both work perfectly fine. I am not sure if running through gradle is an iP requirement?

Thanks for any help!

<img width="1512" alt="Screenshot 2024-03-01 at 2 21 22 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/103179313/9b745730-32b0-4921-bb4c-9f543772b5e3">

**Comment by damithc** [comment]
@alfaloo can you also share your JDK and JVM settings, mentioned in scenario 1 step 3 [here](https://se-education.org/guides/tutorials/gradle.html#:~:text=Confirm%20the%20correct%20Java%20version)?

**Comment by alfaloo** [comment]
@damithc 
This fixed it! Thank you so much prof.

Sincerely apologise for my oversight. I better double check the docs next time!

For this also experiencing this issue, follow the instructions in the link below to configure JDK and JVM for Gradle too (not just in project structure)!

https://se-education.org/guides/tutorials/gradle.html#:~:text=Confirm%20the%20correct%20Java%20version
