### ISSUE TITLE
Updating README.md for tp

### ISSUE THREAD

**Issue by KSSWSept20** [nus-cs2103-AY2324S2/forum#453]
Are we supposed to change anything else of the README.md besides the UI mockup for week 7?

**Comment by damithc** [comment]
@KSSWSept20 The things to update in README are listed [here](https://nus-cs2103-ay2324s2.github.io/website/schedule/week7/project.html#:~:text=README%20page%3A%20Update%20it%20to%20match%20your%20project)

**Comment by KSSWSept20** [comment]
thank you prof!
