### ISSUE TITLE
smoke test help on windows and linux!

### ISSUE THREAD

**Issue by qinxutan** [nus-cs2103-AY2324S2/forum#454]
hello! requesting for smoke test help bc my application got this error (Error: JavaFX runtime components are missing, and are required to run this application) for windows and linux. you can download my ip from [(https://github.com/qinxutan/ip/releases/tag/A-Release)](https://github.com/qinxutan/ip/releases/tag/A-Release)

here is the [user guide](https://qinxutan.github.io/ip/)

thank you so much in advance! :,)

**Comment by damithc** [comment]
@qinxutan Is this the jar that failed our smoke test already, or a new one that you have updated with a potential fix?

**Comment by qinxutan** [comment]
A new one, Prof! I've updated it with a potential fix but still got this email today regarding the failed smoke tests :/

**Comment by damithc** [comment]
The email you received today was based on the yapper.jar uploaded on 02-28-2024 (MM-DD-YYYY) at 15:51:32
If this the same jar file you have in [(https://github.com/qinxutan/ip/releases/tag/A-Release)](https://github.com/qinxutan/ip/releases/tag/A-Release), there is no point doing further smoke testing i.e., the fix didn't work

**Comment by qinxutan** [comment]
Hi Prof, understood! I have uploaded a new jar file with potential fix (added dependencies for windows and linux), so it should be okay for further smoke testing now!

**Comment by francisyzy** [comment]
Hello, senior from a previous batch here, testing on Kali

I have tried running the jar file but it failed to launch. It has worked for others that I smoke tested for: https://github.com/nus-cs2103-AY2324S2/forum/issues/442#issuecomment-1974260899

<img width="419" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/24467184/cc0e5ab0-fe76-4a7f-ab82-f9ab187a6968">

**Comment by hansstanley** [comment]
Hi, I'm a senior testing on Fedora 39 and I got the same error on Java 11.

> java -version

```
openjdk version "11.0.22" 2024-01-16
OpenJDK Runtime Environment (Red_Hat-11.0.22.0.7-1) (build 11.0.22+7)
OpenJDK 64-Bit Server VM (Red_Hat-11.0.22.0.7-1) (build 11.0.22+7, mixed mode, sharing)
```

> java -jar yapper.jar

```
Error: Could not find or load main class yapper.Main
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application
```

**Comment by PyromancerBoom** [comment]
Hi! Testing on Windows 11, I got same errors as the seniors above.

> java -version
```
openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-86)
OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)
```

> java -jar yapper.jar
```
Error: Could not find or load main class yapper.Main
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application
```

Same error as above when I tried running the jar file using IntelliJ IDEA with Java 11 (corretto-11.0.22).

**Comment by amanzainal** [comment]
Hi! Testing on Windows 10, on both jdk-11 and jdk-17.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/69044708/df996106-bc16-4e23-a048-3cea0c9e4273)

Similar errors to the above, the error is likely not OS-specific or java specific

**Comment by lhy-hoyin** [comment]
> Hi Prof, understood! I have uploaded a new jar file with potential fix (added dependencies for windows and linux), so it should be okay for further smoke testing now!

Hello @qinxutan  (previous batch senior here), just a quick reminder to also re-upload the source code assets to ensure that the source code is an accurate representation of your jar file, of course unless prof @damithc (or the teaching team) has given different instructions.

**Comment by lhy-hoyin** [comment]
Hi. I am a previous catch senior helping to smoke test in Linux (Ubuntu 22.04.4).

Typing `java --version` gives
```shell
openjdk 11.0.22 2024-01-16
OpenJDK Runtime Environment (build 11.0.22+7-post-Ubuntu-0ubuntu222.04.1)
OpenJDK 64-Bit Server VM (build 11.0.22+7-post-Ubuntu-0ubuntu222.04.1, mixed mode, sharing)
```

Typing `java -jar yapper.jar` gives
```shell
Error: Could not find or load main class yapper.Main
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application
```

---

Not too sure if this might help:

(1) Check if you have multiple `public static void main(String[] args)`
- See `YapperLauncher.java`
- See `Main.java`

(2) Perhaps in your `build.gradle` you can change to
```gradle
application {
    mainClass.set('yapper.YapperLauncher')
 }
```
since your `public static void main(String[] args)` is located in `YapperLauncher`.

**Comment by qinxutan** [comment]
thank you everyone for the help, really appreciate it! I have changed the build.gradle class, hopefully it works! :,)

**Comment by damithc** [comment]
> thank you everyone for the help, really appreciate it! I have changed the build.gradle class, hopefully it works! :,)

@qinxutan Try to confirm. Hope not enough :-)
