### ISSUE TITLE
Header not updated for TP

### ISSUE THREAD

**Issue by chiralcentre** [nus-cs2103-AY2324S2/forum#456]
Hi I have updated `docs\_sass\minima\_base.scss` to reflect the new header but the website still shows AB-3 in the header. Can I check why this may occur? For reference, the relevant part of the code I modified in `docs\_sass\minima\_base.scss is:

```
@media print {
  /**
  * Prevents page break from cutting through content when printing
  */
  body {
    display: block;
  }
  /**
  * Replaces the top navigation menu with the project name when printing
  */
  .site-header .wrapper {
    display: none;
  }
  .site-header {
    text-align: center;
  }
  .site-header:before {
    content: "HireHub";
    font-size: 32px;
  }
}
```

**Comment by damithc** [comment]
@chiralcentre here's something you can do:
1. Go to [tP progress dashboard](https://nus-cs2103-ay2324s2.github.io/dashboards/contents/tp-progress.html) and find which teams have done the related tP task
2. Then, go to the [list of tP PRs](https://github.com/nus-cs2103-AY2324S2/tp/pulls) or the [tP code dashboard](https://nus-cs2103-ay2324s2.github.io/tp-dashboard/?search=&sort=groupTitle&sortWithin=title&timeframe=commit&mergegroup=&groupSelect=groupByRepos&breakdown=true&checkedFileTypes=docs~functional-code~test-code~other) to examine how they updated that file

**Comment by chiralcentre** [comment]
Thank you Prof for the advice! I fixed the issue by updating docs/_config.yml as well.
