### ISSUE TITLE
Do we need to re-write tests for v1.2?

### ISSUE THREAD

**Issue by Jerome-j** [nus-cs2103-AY2324S2/forum#457]
Hi all,

I was wondering if we needed to rewrite tests for v1.2 if we are adding in more features / modifying the current features.

Thank you!

Best regards,
Jerome

**Comment by damithc** [comment]
@Jerome-j It's up to you. More [here](https://nus-cs2103-ay2324s2.github.io/website/admin/tp-expectations.html#individual-expectations-on-testing:~:text=Expectations%20on%20Testing)

**Comment by chiralcentre** [comment]
Hi prof to add on this point if we have added more features which cause existing tests to fail, do we need to rewrite the tests such that they pass? I was thinking we need to rewrite the tests until all pass, since checking for test success is conducted as part of CI/CD.

**Comment by damithc** [comment]
> Hi prof to add on this point if we have added more features which cause existing tests to fail, do we need to rewrite the tests such that they pass? I was thinking we need to rewrite the tests until all pass, since checking for test success is conducted as part of CI/CD.

@chiralcentre There are several options you can choose from.

1. Update/add tests every time you change functional code. This is what normally happens in stable production systems. For example, most OSS projects will not accept a PR that has failing tests or not enough new tests to cover the new functional code.
2. Disable failing tests temporarily until the code is stable. This is suitable when the functional code is in a highly volatile state (e.g., you are still experimenting with the implementation). The benefit is that you avoid the cost of writing tests for functional code that might change again soon after. Some costs: (a) harder to detect regressions during the period tests are disabled (b) testing work pile up which could distort your estimate of real progress (c) forgetting to enable the tests in time
This is still a viable option during some stages of a tP e.g., during the early part of an iteration, or while a PR is still in 'draft' state, still getting early feedback from the team.
4. Decide certain tests are not worth the effort to maintain them, and delete them permanently. Less test code to maintain but higher risk of undetected regressions.
