### ISSUE TITLE
jar file too small

### ISSUE THREAD

**Issue by qinxutan** [nus-cs2103-AY2324S2/forum#459]
Hi! I received an email that my fat jar file turned out to be small in file size (shown below) but I have checked the file and it contains all the classes in my ip (also shown below). Could it be an issue with the code of my build.gradle? Or something else? 

![F29661E2-5EAF-4FCA-BF54-DAF835D22BAB](https://github.com/nus-cs2103-AY2324S2/forum/assets/122926007/16000d30-84cc-44ab-b506-7891c1b0f7d0)
![58460749-210A-4004-BAD4-863A0036CAE5](https://github.com/nus-cs2103-AY2324S2/forum/assets/122926007/a144e6da-cde5-41f0-9da4-7748de232c15)

**Comment by damithc** [comment]
@qinxutan How exactly did you create the JAR file? Try using the steps given [here](https://nus-cs2103-ay2324s2.github.io/website/schedule/week6/project.html#:~:text=To%20avoid%20version%20compatibility%20issues%2C%20we%20strongly%20recommend%20the%20following%20approach).
As you seem to be using a Mac, ensure that you are using the Zulu distribution of the JDK that we have prescribed for Mac users.

**Comment by qinxutan** [comment]
@damithc Hi Prof! I did use the exact same steps, and also used the zulu distribution of the jdk prescribed.

**Comment by azumieflare** [comment]
You might have to make some changes to the ```build.gradle``` file to follow https://se-education.org/guides/tutorials/javaFxPart1.html. 
I removed lines 12, 20-35 from ```build.gradle``` and copied the dependencies section over and it seems to build the jar and run fine.

**Comment by damithc** [comment]
> @damithc Hi Prof! I did use the exact same steps, and also used the zulu distribution of the jdk prescribed.

@qinxutan compare your build.gradle file with a few others' to see if there are differences.

**Comment by qinxutan** [comment]
@azumieflare thank you for the help!! it works fine now and is of the right file size :)

**Comment by qinxutan** [comment]
@damithc thank you Prof for the help! I have resolved the issue :)
