### ISSUE TITLE
requesting for smoke test help on linux and windows

### ISSUE THREAD

**Issue by qinxutan** [nus-cs2103-AY2324S2/forum#460]
hello! requesting for smoke test help bc my application got this error (Error: JavaFX runtime components are missing, and are required to run this application) for windows and linux. i have edited the build.gradle, which is probably the one causing the bug. you can download my ip from [(https://github.com/qinxutan/ip/releases/tag/A-Release)](https://github.com/qinxutan/ip/releases/tag/A-Release)

here is the [user guide](https://qinxutan.github.io/ip/)

thank you so much in advance! :,)

**Comment by MarcusGitty** [comment]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/122339963/d38b216e-3903-46bf-b311-fa040b46cb6f)

Hi, I've downloaded that jar file and the gui managed to run on my windows 11 pc !

**Comment by qinxutan** [comment]
@MarcusGitty thank u so much for helping to test :,,)
