### ISSUE TITLE
Unable to create PR to our own organisation's repo

### ISSUE THREAD

**Issue by cheahTJ** [nus-cs2103-AY2324S2/forum#461]
May I know how can I resolve this issue? This arises when I am trying to create a pull request from my forked repository to my team's repository. 

<img width="523" alt="Screenshot 2024-03-05 at 12 34 54 AM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/122202483/4b80f70a-e091-4113-8a7e-bd657b55f757">

**Comment by NeoHW** [comment]
The CI tools will not allow you to create the pull request if your current PR does not pass CI tests.
To solve this, you can take a look at the logs in the build to see which part of your code is causing the tests to fail; it would most likely be due to some checkstyle!

**Comment by cheahTJ** [comment]
@NeoHW  I tried running checkstyle test as such `gradlew checkstyleMain checkstyleTest` and it says I passed all the checkstyle so I am wondering if I could possibly fail other tests?

**Comment by NeoHW** [comment]
@cheahTJ Yeap, unfortunately, it seems that the checkstyleMain and checkstyleTest when using gradlew is not as comprehensive as the ones on github actions, my guess would be that they include all files instead of just the test and main folders

**Comment by cheahTJ** [comment]
@NeoHW I resolved it already. It turns out that that command was not comprehensive enough, and i was able to rectify the problem after clicking on the icon at the side to see whats wrong
