### ISSUE TITLE
Typo/Text cut off in Week 7 - Project - Update the UG

### ISSUE THREAD

**Issue by dillontkh** [nus-cs2103-AY2324S2/forum#462]
The text at the end of [this section](https://nus-cs2103-ay2324s2.github.io/website/schedule/week7/project.html#3-optional-update-the-ug) seems to have been cut off.

<img width="853" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/40649376/915b80cf-e4b8-45c6-b5b3-83de9bdafefe">

**Comment by damithc** [comment]
Thanks for the heads up @dillontkh 
Fixed.
