### ISSUE TITLE
Wrong location for Week 7 task 2 update project site site-wide-settings for Jeykll

### ISSUE THREAD

**Issue by camille-readbean** [nus-cs2103-AY2324S2/forum#463]
Under section B  

> You need to update the AB-3 in the top navigation bar of your project website (it's in docs\_sass\minima\_base.scss if using Jekyll, and in docs\_markbind\layouts\default.md if using MarkBind).  
  
The location should be `docs\_config.yml` instead for Jekyll.

https://nus-cs2103-ay2324s2.github.io/website/schedule/week7/project.html#2-update-project-website-aboutus-readme

**Comment by damithc** [comment]
Fixed. Thanks @camille-readbean

**Comment by damithc** [comment]
@camille-readbean Just realized both those files need to be updated. `docs_sass\minima_base.scss` affects the print view (e.g., when converting UG/DG to PDF format)
