### ISSUE TITLE
TP Github actions workflow failing with markdown files

### ISSUE THREAD

**Issue by camille-readbean** [nus-cs2103-AY2324S2/forum#465]
Our pull requests to our repo, https://github.com/AY2324S2-CS2103T-T17-1/tp/ are failing because of this:
  
https://github.com/AY2324S2-CS2103T-T17-1/tp/actions/runs/8156366139/job/22293791783?pr=6  

```
ERROR:../src/main/java/seedu/address/model/person/Remark.java:36: no newline at EOF.
ERROR:../src/test/java/seedu/address/logic/commands/RemarkCommandTest.java:36: no newline at EOF.
WARN:../README.md:6: trailing whitespace.
WARN:../README.md:16: trailing whitespace.
WARN:../docs/index.md:15: trailing whitespace.
WARN:../docs/index.md:16: trailing whitespace.
Error: Process completed with exit code 1.
```

It seems these checks were introduced in 2020 here:
https://github.com/AY2324S2-CS2103T-T17-1/tp/commit/e90e56a060214200a4743e43b5ca01b1a2b6e2fb  
  
Is there a need to have a newline at EOF? Also for TP do we need to have checkstyle?  
  
https://se-education.org/guides/conventions/java/
The resource above did not mention anything about needing newline in EOF, also trailing whitespace is a "feature" / part of markdown itself.

**Comment by damithc** [comment]
@camille-readbean 
Both are common conventions but are not specifically mentioned in our style guides. You are free to follow or disable them in Checkstyle.
