### ISSUE TITLE
Must we add in all use cases/features for our project's DG this week?

### ISSUE THREAD

**Issue by tankh99** [nus-cs2103-AY2324S2/forum#468]
Regarding the DG for this week's tasks, are we required to add in everything?

Because I'm afraid that our features might not have been concretised yet and we might end up having to drastically change the use cases later on.

**Comment by damithc** [comment]
@tankh99 You can capture _all_ requirements in user stories format (which is considered a _lightweight_ format) but delay writing use cases (which requires more work) until you are ready to start implementing those features.
That said, you should be fairly certain about what you'll implement in v1.2 by now (so, use cases for v1.2 features should be in the DG already).

**Comment by tankh99** [comment]
Understood, thank you prof!
