### ISSUE TITLE
Tutorial on adding new command

### ISSUE THREAD

**Issue by cheahTJ** [nus-cs2103-AY2324S2/forum#469]
Hi, I would like to confirm on the following task:

Submission: Do your changes in a branch named tutorial-adding-command, push to your fork, and create a PR from your fork to your team's repo. You may close the PR soon after.

By this, does it mean that after I create a PR from my fork to the team's repo, somebody will review it and close it subsequently WIHTOUT merging it into the team's code base (AKA it is not compulsory to have this new command in our address book right)?

**Comment by damithc** [comment]
> By this, does it mean that after I create a PR from my fork to the team's repo, somebody will review it and close it subsequently WIHTOUT merging it into the team's code base (AKA it is not compulsory to have this new command in our address book right)?

@cheahTJ Yes, that's right. No need to review or merge (unless you want to have that feature in your product). Just create and close, so that we can detect its presence.

**Comment by cheahTJ** [comment]
Got it, thank you prof!
