### ISSUE TITLE
My deadline command is not working.

### ISSUE THREAD

**Issue by reetmitra** [nus-cs2103-AY2324S2/forum#470]
Is there any way i could get some help on how to resolve my deadline command not working, I have tried multiple valid inputs but it doesn't seem to work.

**Comment by damithc** [comment]
@reetmitra You need to provide more details:
* What is the command?
* What's the expected behavior?
* What's the actual behavior?

**Comment by reetmitra** [comment]
@damithc the command is for eg : deadline submit ProjectX /by 2/12/2024 1800 should add this to the task list : "submit ProjectX" and the deadline "2nd Dec 2024, 6:00 PM". But the actual output just says: An unexpected error occured : null.

**Comment by reetmitra** [comment]
@damithc It seems to be working but the output is still showing An unexpected error occured : null. However running the list command displays the new deadline task added.

**Comment by tankh99** [comment]
Can you try debugging or printing out the exception? Clearly it's somewhere in the deadline module, but we can't really help you without any information

**Comment by reetmitra** [comment]
@tankh99 it seems to be an issue with a output string all the commands are working correctly but the "Got it I've added this task..." string is the one that I have to fix now.

**Comment by tankh99** [comment]
@reetmitra Then try taking a look at the output module in your code. Usually I'd just trace the process flow, from when the user keys in something to the output, and then locate the questionable code

**Comment by reetmitra** [comment]
<img width="398" alt="Screenshot 2024-03-06 at 4 21 52 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/63037606/c709bf00-f5ab-4f7a-89d6-8c12743a4c67">
<img width="398" alt="Screenshot 2024-03-06 at 4 22 28 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/63037606/84afe9b2-2142-4abc-85dd-7fa10ce8019b">
I managed to fix it to some extent, this is what I'm facing now

**Comment by damithc** [comment]
@reetmitra The technique that is most useful in this kind of situation is https://nus-cs2103-ay2324s2.github.io/website/book/intellij/debuggingBasic/

**Comment by reetmitra** [comment]
@damithc I managed to fix it and released a new JAR file so it works correctly, thank you for the help!
