### ISSUE TITLE
Codecov issues with trying to create pull request

### ISSUE THREAD

**Issue by cheahTJ** [nus-cs2103-AY2324S2/forum#471]
It says under details that 'Added lines #L26 - L30 were not covered by tests' etc, does it mean that for each methods we create, we have to concurrently test these methods or can we just merge these codes first then we conduct our tests afterwards?

![Screenshot 2024-03-06 at 6 44 01 PM](https://github.com/nus-cs2103-AY2324S2/forum/assets/122202483/3dc7d9dc-c52a-483a-a23c-91b6f497e7a7)

**Comment by Jerome-j** [comment]
While I am unable to comment on this codecov issue. I recommend naming your class as `NusId` instead of `Nusid`

**Comment by damithc** [comment]
@cheahTJ It's up to you. Somewhat similar to https://github.com/nus-cs2103-AY2324S2/forum/issues/457#issuecomment-1977905536

**Comment by cheahTJ** [comment]
@damithc @Jerome-j  Got it, thank youuu!!
