### ISSUE TITLE
Forked the team repo

### ISSUE THREAD

**Issue by Darkarche3** [nus-cs2103-AY2324S2/forum#473]
Hi, I have forked my team's repo over to my account but it's not been reflected in the TP tracker for almost a week. May I ask whether I have done it correctly or do I need to do it differently?

May I also know for this task, "Created a PR from the tutorial-adding-command branch", where can I find the tutorial-adding-command branch? 

Thank you very much!

**Comment by Jerome-j** [comment]
It appears that you have indeed forked last week. But maybe you might want to try push a commit to your own fork. Or better yet, create your README information and submit a PR.

**Comment by Darkarche3** [comment]
thanks @Jerome-j !

Can I check with you for the other task as well? Where is the tutorial-adding-command branch located? Some people completed it during recess week so I am guessing its not something we do after our tutorials.

Thank you!

**Comment by damithc** [comment]
> Hi, I have forked my team's repo over to my account but it's not been reflected in the TP tracker for almost a week. May I ask whether I have done it correctly or do I need to do it differently?

@Darkarche3 It's green. 
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/f02f5811-e9a0-455f-a695-2e86e42fe726)

**Comment by Jawad280** [comment]
@Darkarche3 The tutorial-adding-command is at the end of week 6 project page, at the following link :
[Tutorial 2 - Adding a new Command](https://nus-cs2103-ay2324s2.github.io/tp/tutorials/AddRemark.html)

**Comment by danielleloh** [comment]
@Darkarche3 you have to create the new branch named `tutorial-adding-command` and follow the tutorial, committing the changes to that branch. When you push the branch to your fork and make a PR with that branch to your team repo, that should fulfil the tutorial tag in the tP tracker.
