### ISSUE TITLE
remark command tutorial

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#474]
<img width="769" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/73015364/4ef833dc-671e-4e57-86b9-f9f2dabfd497">
if we use the code given in the tutorial do we need to declare reuse or is it meant for us to use?

**Comment by damithc** [comment]
@bgopi23 No need to declare reuse of code from learning materials provided by us.

**Comment by baskargopinath** [comment]
understood thank u prof @damithc
