### ISSUE TITLE
remark success message is different

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#476]
my message:
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/73015364/adf3287d-27c7-4ba3-9cde-5225fe1ad3be)

expected message:
<img width="729" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/73015364/1362b604-79e0-4e69-996b-37edac93c32d">

i followed the tutorial so im not sure why this is happeniong

**Comment by tankh99** [comment]
Hi, this is similar to #352. I believe that there's a typo in the tutorial. You're supposed to use `Messages.format()` to format the person object

**Comment by baskargopinath** [comment]
i see thank u @tankh99
