### ISSUE TITLE
Must we implement the features we came up with?

### ISSUE THREAD

**Issue by tankh99** [nus-cs2103-AY2324S2/forum#477]
During ideation of the feature specs, we each came up with individual features, however, the feature that I initially had in mind could not be implemented and therefore I had less features than expected. I was wondering if it's possible for me to do someone else's features so that I have equal work as everyone else while the original author still gets the documentation marks

**Comment by damithc** [comment]
@tankh99 Yes, that's fine from our end. It's up to the team to divide the features as you see fit. 
Similarly, you can take over the documentation of that feature (or maintenance of that documentation) if the other team member agrees with it. 
Keep in mind that if you are in charge of a part of documentation, you get credit for writing that part but also will have to take responsibility for any bugs in that part of the documentation. So, it is better if the person who implemented the feature is also accountable for the documentation of it.

**Comment by tankh99** [comment]
Understood, thank you!
