### ISSUE TITLE
Suggestion for GitHub issue description: missing part of the user story?

### ISSUE THREAD

**Issue by E0735389** [nus-cs2103-AY2324S2/forum#478]
In the textbook https://nus-cs2103-ay2324s2.github.io/website/admin/appendixE-gitHub.html#using-issues , there's a suggested issue title/description as follows:

> title | Add deadline
> -- | --
> Description | As a user I can so that I can keep track of my deadlines

Is it intentional that the statement is not

> As a user I can **add a deadline** so that I can keep track of my deadlines

? (admittedly it's already in the title but it looks grammatically incorrect that way?)

**Comment by damithc** [comment]
Fixed. Thanks for reporting this @E0735389
