### ISSUE TITLE
[tp] Checkstyle CI error

### ISSUE THREAD

**Issue by jskimdev** [nus-cs2103-AY2324S2/forum#479]
I updated the About Us page and pushed it to my forked repo, then pull request to main repo. However, there is a checkstyle error I don't understand. 
<img width="374" alt="Screenshot 2024-03-07 at 9 51 05 AM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/101090522/65f77d1f-86dd-4fa9-8672-b2eb5ef6fce6">
I removed the whitespace at line 38, but then I don't understand the line 51 error. Line 51 is where I wrote the role and there is next line which tells about my responsibilities. I did not change anything like format but only the texts. Could this be cause my team only got 4 people?

**Comment by guanquann** [comment]
You need to leave a new line after line 51

**Comment by jskimdev** [comment]
oh yeah I solved it. Thanks! I added an empty new line at the end
