### ISSUE TITLE
PR merging workflow issue

### ISSUE THREAD

**Issue by chiageng** [nus-cs2103-AY2324S2/forum#481]
After creating a PR and get approval from 2 peer reviewer, is the author of the PR do the merging himself/herself? Or should someone else responsible to merge the PR with a final checking? 

In my team, our workflow is that a PR(already assigned to milestone v1.1) have to get 2 peer reviewers' approval, and there will be a person responsible to merge the PR after the PR getting enough approval , however, it appears that my teammate's tp progress doesnt reflect v1.1 PR is done. May i know whether is this workflow is wrong? 

In our workflow, our team thought that it will be better to have minimal number of people responsible for the main team repo merging to reduce wrong code pushing issue into main branch. Quite confused in this part.

**Comment by damithc** [comment]
@chiageng It is not a requirement that the author merges their own PR (in fact it is discouraged). So, that should not affect tP dashboard recognizing PRs. If your team members' PRs are not recognized after the next dashboard update, let me know (together with the links of some PRs affected).
