### ISSUE TITLE
Debug mode not working

### ISSUE THREAD

**Issue by jeong-jaeho** [nus-cs2103-AY2324S2/forum#482]
I tried using debug mode for Main.main(), typed input as told to as the following:
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/109773933/7d9246e0-eabc-4806-9d38-716c352b41f1)

However, I'm not getting any debugging info at the moment like the following:
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/109773933/964ff72a-ac41-40ed-8a40-48f7c8ee8522)

May I know what is the issue?

**Comment by damithc** [comment]
@jeong-jaeho Where did you put the breakpoint? Can you share a screenshot of it?

**Comment by jeong-jaeho** [comment]
I forgot to place the breakpoint, apologies!
