### ISSUE TITLE
v1.1 PRs not reflected in individual tp progress dashboard

### ISSUE THREAD

**Issue by sindhurajain** [nus-cs2103-AY2324S2/forum#483]
<img width="737" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/115209308/288dea34-269b-4582-8152-62d5733161d1">

I created a few PRs and merged them myself after they were reviewed and approved. But those PRs did not get detected. Were the PRs supposed to be assigned to milestone v1.1 or were the PRs supposed to be assigned to issues which were assigned to milestones or both?

**Comment by drustanyjt** [comment]
@sindhurajain I believe that the PRs need to have the `v1.1` milestone (ie. _assigned_ to milestone `v1.1`)
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/110999129/df7b3388-a060-4569-9638-34515b4b02be)

**Comment by damithc** [comment]
Yup, as @drustanyjt said. Both the PR and the issue need to be assigned to the milestone.
