### ISSUE TITLE
TP Grading Question: 5B. Team-tasks

### ISSUE THREAD

**Issue by wxiaoyun** [nus-cs2103-AY2324S2/forum#485]
# Context
<img width="834" alt="Screenshot 2024-03-07 at 3 40 05 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/81742181/29a857d6-4a17-41a7-821a-49f3d41541d6">

Can I confirm that week 7 here is following the cs2103T definition of week 7 and work done over the recess week falls under week 7.

**Comment by damithc** [comment]
@ForAeons Yes, work during the recess week counts for week 7.
