### ISSUE TITLE
Full stop after each point of use case?

### ISSUE THREAD

**Issue by E0735389** [nus-cs2103-AY2324S2/forum#486]
I notice that sometimes Developer Guide of AddressBook level 3 uses full stop after a point, and sometimes it doesn't.

https://se-education.org/addressbook-level3/DeveloperGuide.html#use-cases

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/97508964/819fec3a-5b3a-4298-bcef-d226465faa08)

e.g. here in the MSS, full stop isn't used, and in extension 3a, it is used.

Does this matter?

**Comment by damithc** [comment]
While not a big deal, it is still better to be consistent. So, using a full stop is recommended.
