### ISSUE TITLE
Cannot update the image with same name

### ISSUE THREAD

**Issue by ZHANGTIANYAO1** [nus-cs2103-AY2324S2/forum#488]
Our team tried to update our Ui.png image, and after replace the original image, the github still show the old one instead of the new image. Also, when check the history of the image file, it shows that the image has been updated successfully. How to solve this issue?
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/88520881/a55f7225-72b8-4625-b6b0-ef4795b373f1)
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/88520881/39820d7e-d678-4e53-bbb1-5f042504afce)

**Comment by damithc** [comment]
> the github still show the old one instead of the new image.

@ZHANGTIANYAO1 Where exactly?
BTW, retain the name `tp` for your forks, as that is the fork name our scripts will look for.

**Comment by ZHANGTIANYAO1** [comment]
> > the github still show the old one instead of the new image.
> 
> @ZHANGTIANYAO1 Where exactly? BTW, retain the name `tp` for your forks, as that is the fork name our scripts will look for.

Thanks for your reply, it seems that github need sometime to update the image. Now it display the correct image.
