### ISSUE TITLE
Regular Expressions in iP Level 4

### ISSUE THREAD

**Issue by Jerome-j** [nus-cs2103-AY2324S2/forum#49]
Hello, I don't know whether to post this under the 3rd party libraries, or not.

I was doing the iP, and wondering if I could use regular expressions in the Level 4 - so that I can parse/validate the user input

For example, I want to do this to validate the *todo* command, which is followed by one or more lower case events that are to be added.

```java
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class Main {
    public static void main(String[] args) {
        Pattern pattern = Pattern.compile("todo [a-z]+$");
        Matcher matcher = pattern.matcher("todo command");

        boolean matchFound = matcher.find();
        System.out.println("match?" + matchFound);
    }
}
```

Thank you!

**Comment by tankh99** [comment]
Yes I have a similar question actually. I found that manually parsing the tokens in the input seem unnecessarily complicated

**Comment by damithc** [comment]
@Jerome-j @tankh99 Yes, you may use regular expressions in the iP.

**Comment by Jerome-j** [comment]
Thanks Prof!
