### ISSUE TITLE
Adding a new command tutorial issue

### ISSUE THREAD

**Issue by jeong-jaeho** [nus-cs2103-AY2324S2/forum#491]
I'm following through the tutorial line by line, and I'm getting 'cannot resolve symbol' error for parameter 'source':
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/109773933/d24ee8a7-2d3b-4d48-b396-beba2545d897)
I can't seem to find where the error is..

And I don't understand why 'new JsonAdaptedPerson(BENSON)' and 'person.toModelType()' are causing 'cannot resolve symbol' error:
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/109773933/c7373812-6027-41d8-98fd-00a2f136e327)

The declared param type and argument type are the same, but they keep causing compilation error..

**Comment by jeong-jaeho** [comment]
@damithc Since the tutorial is due today before today's briefing, I've pushed my current changes to my fork and created a PR to the team repo for now. I'm trying to resolve the compilation errors and planning to commit the fix and then close the PR. In the event that I cannot resolve the issues, does it meet the requirements by creating an unfinished PR that has unsuccessful check status..?
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/109773933/9a6038c1-de6d-484b-9aa7-a7242d2a81b8)

**Comment by damithc** [comment]
@jeong-jaeho It'll be marked as done even if the PR is failing CI checks. But recommended to figure out how to do the tutorial, as it is meant to prepare you for working with the tP code.
