### ISSUE TITLE
Java CI on TP Progress Dashboard indicate 'failing'

### ISSUE THREAD

**Issue by lynnetteeee** [nus-cs2103-AY2324S2/forum#492]
Our team completed our issues for milestone v1.1 before the deadline yesterday (Thursday 2359), but we realise the Java CI is failing on our progress dashboard. 
<img width="133" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/103313573/1be702aa-8c8d-42ad-9189-99d9ea4a44b1">

While we suspect that this may be because we merged some PRs that failed the Java CI, we still merged because of this line in the workflow guideline from the course website: 
> An exception to this guideline is when the failure is confirmed to be due to something you can afford to ignore
<img width="500" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/103313573/abc6719e-c045-4d2d-b295-0cb6d8160e51">

Given that all of the PRs that failed were due to trivial errors that did not affect our code correctness and could be ignored (see following screenshot for example): 
<img width="700" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/103313573/be612b41-9925-4b53-9830-6578dd7b271a">

How may we approach this problem? Any help would be kindly appreciated! Thank you!

**Comment by damithc** [comment]
@lynnetteeee Someone can create a new PR to fix this CI failure problem. You are free to make it a new release e.g., v1.1.1 or let it be part of the next release i.e., v1.2
On a separate note, the CI failure (as per the screenshot) was easily fixable. In future, try to avoid merging PRs with such easily-fixable problems (i.e., fix the problem before merging).

**Comment by lynnetteeee** [comment]
Oh I see, thank you Prof for clarifying!
