### ISSUE TITLE
Forking workflow questions

### ISSUE THREAD

**Issue by RunjiaChen** [nus-cs2103-AY2324S2/forum#494]
Hello guys, for the forking workflow, I would like to clarify the following: 

1. I create a branch on my local repo
2. I push the branch to my remote (which is a fork of my team project) 
3. I open a PR

Do I need to merge the fork back to master? Do I open another PR on my fork from the latest branch to the master branch? Thank you.

**Comment by aureliony** [comment]
The PR will be from your branch to the master branch of the team repo.

**Comment by damithc** [comment]
> Do I open another PR on my fork from the latest branch to the master branch? Thank you.

@RunjiaChen No. No need to create a PR within your own fork. 


> The PR will be from your branch to the master branch of the team repo.

Yup.

**Comment by UdhayaShan1** [comment]
Merging on the team repo to master and pulling it will 'auto' merge it to master on your local repo. Pushing it to your fork will do the same.

**Comment by RunjiaChen** [comment]
Thanks all for the help!
