### ISSUE TITLE
W8 quiz, what is meant by acceptable/correct

### ISSUE THREAD

**Issue by UdhayaShan1** [nus-cs2103-AY2324S2/forum#496]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39399745/a5dc324b-51ee-48ec-b822-94a56fd1837a)

As far as i understand, the names do not be labelled and activation bar can be removed. But if name is given, is it 'acceptable' to leave out this info in our sequence diagram. Hence making b) correct

Similarly,

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39399745/ebf4293d-01ad-491d-ad9f-e2a534051f6c)

A and D are technically correct, but D is omitting some details. So if given the methods, is it wrong to omit it? Im bit confused on when we can omit out such details. It is said here,

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39399745/eea24e11-5ee9-436e-a016-bda1a0071798)

**Comment by damithc** [comment]
@UdhayaShan1 It's acceptable to omit object names. Acceptable to omit members (i.e., attributes, methods) too.
BTW, for part 1, you should be able to see the correct answers after submitting the quiz.

**Comment by UdhayaShan1** [comment]
Oh ok missed that thanks!
