### ISSUE TITLE
TP team progress not updated

### ISSUE THREAD

**Issue by DominicFuMJ** [nus-cs2103-AY2324S2/forum#497]
Hi, for team [CS2103-F15-4](https://github.com/AY2324S2-CS2103-F15-4/tp), the tp team progress dashboard activities 'website adapted' and 'v1.1 wrap-up' is still marked as overdue. but my group has already what is required and fixed the problem for 'website adapted'. Could someone help explain what we are missing? Thank you

**Comment by damithc** [comment]
@DominicFuMJ If the changes were done after the last tP dashboard update (your v1.1 milestone was closed only one hour ago?), you need to wait till the next dashboard update for the changes to be detected.

**Comment by DominicFuMJ** [comment]
Ok. I will wait until the next update and see if it changes. Until then, I would keep this issue open if you don't mind.

**Comment by damithc** [comment]
@DominicFuMJ Also, you can click on the `details` link to find more details about what is required by each item.
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/c7467783-8fcb-4bd9-8baa-cf97ea7f54f8)
