### ISSUE TITLE
Minor typo in Week 7

### ISSUE THREAD

**Issue by tankh99** [nus-cs2103-AY2324S2/forum#498]
Under week 7 topics. It should be johnTan.md under point 3

<img width="1022" alt="Screenshot 2024-03-11 at 6 58 00 AM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/56617918/d8699030-aaaf-4272-a492-7e3f090d2ba1">

**Comment by damithc** [comment]
Fixed. Thanks for the bug report @tankh99
