### ISSUE TITLE
iP Peer Evaluation Survey: "Not enough code to evaluate" for Testing Portion.

### ISSUE THREAD

**Issue by SherisseTJW** [nus-cs2103-AY2324S2/forum#499]
Hi, can I ask when something falls under "Not enough code to evaluate" vs. "Not enough JUnit Tests. Exceptions not used or used poorly e.g., empty catch blocks."? 

Specifically, I have an assigned iP for which the tests exist, but are commented out..

**Comment by damithc** [comment]
@SherisseTJW tests (or anything else) in commented out code doesn't count.
