### ISSUE TITLE
Multiple commits per level

### ISSUE THREAD

**Issue by tankh99** [nus-cs2103-AY2324S2/forum#50]
Are we allowed to write in more detailed commit messages in between each level for a commit?

E.g. the example commit history
1. Level-4
2. feat: add deadline
3. feat: add event
4. feaT: add todo
5. Level-3

**Comment by damithc** [comment]
@tankh99 Indeed, you may commit as many times as you need (but _at least_ once per increment). Also related https://github.com/nus-cs2103-AY2324S2/forum/issues/45#issuecomment-1904434241

**Comment by tankh99** [comment]
Thanks!
