### ISSUE TITLE
Citing for reused AB3 code

### ISSUE THREAD

**Issue by wilsonwid** [nus-cs2103-AY2324S2/forum#500]
Hi, how do we cite code that is somewhat reused from AB3 code? As an example, if we used code that is similar to another class, how are we supposed to cite it?

**Comment by damithc** [comment]
@wilsonwid [No need to cite the reuse of AB3 code](https://nus-cs2103-ay2324s2.github.io/website/admin/appendixB-policies.html#policy-on-reuse:~:text=Giving%20credit%20to%20AB3%20code).

**Comment by wilsonwid** [comment]
Thank you Prof! @damithc
