### ISSUE TITLE
Advise for workflow to add big features

### ISSUE THREAD

**Issue by UdhayaShan1** [nus-cs2103-AY2324S2/forum#501]
Suppose I wish to morph the add command to take in new fields for example.

My idea is to create a main branch to update this command, but I have many issues to solve such as changing AddressBookParser, creating new classes and so on. From what I have seen, we should have a individual branch for each issue (or should we be doing this), or is it ok to close all issues with one branch? Cons of one branch each is risk of merge conflicts and lacking ability to integration test properly as without new classes there is no point in updating parser.

My alternative idea is as we go on, we create a branch from our feature branch we are working on and merge as we go on but this is not taught so I am assuming is a bad practice.

I appreciate any advise thanks.

**Comment by damithc** [comment]
@UdhayaShan1 Normally, a PR takes the product from one working version to another working version. So, if you want to add a new field to the `add` command, it should be one issue, one branch, one PR (similar to 'Add remark command' tutorial). For example, `Add photo field to the add command` (not `Update parser class to handle photo field`). In other words, as much as possible, stick to the breadth-first approach when defining tasks, not depth-first.

But if you are adding three fields to the `add` command, it can be broken down to three incremental changes, each adding one field (i.e., it will be three issues and three PRs).

**Comment by UdhayaShan1** [comment]
What about in this case where I have one PR with add command working but all tests failing. Then i have another PR (hence branch) to fix these tests, the first PR will fail CI and will never get merged. So by right, I have to fix these tests within the first PR itself?

Thanks

**Comment by damithc** [comment]
> What about in this case where I have one PR with add command working but all tests failing.

@UdhayaShan1 Ideally, tests should be added/updated in the same PR that changes the functional code, but you can deviate from this when circumstances justify it. Related FAQ [here](https://nus-cs2103-ay2324s2.github.io/website/schedule/week8/project.html#:~:text=FAQ%3A%20Do%20we%20have%20to%20keep%20updating%20tests%20when%20we%20update%20functional%20code%3F).
