### ISSUE TITLE
Codecov failed: Added line not covered by tests

### ISSUE THREAD

**Issue by tankh99** [nus-cs2103-AY2324S2/forum#502]
Hi all, I made some changes to the tP, but GitHub actions fail because tests are for some reason not covered. For classes that I created, I understand. However, for JavaFX classes like CommandBox, I don't see any test files for it to begin with even though previously, codecov was 75% without us touching the code. So my question here is, do we need to create the test files for files like CommandBox if those don't exist yet?

<img width="754" alt="Screenshot 2024-03-11 at 4 11 47 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/56617918/b9d26987-fb48-41be-b767-507e4c1d27bc">

<img width="516" alt="Screenshot 2024-03-11 at 4 11 17 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/56617918/af82c3b4-0850-44c0-b800-eebeea522b3c">

**Comment by damithc** [comment]
> So my question here is, do we need to create the test files for files like CommandBox if those don't exist yet?

@tankh99 Coverage decisions are entirely up to the team. We don't have any code coverage requirements when grading. So, if you think it is not worth or not practical/feasible to write tests for the code in a PR, you can still go ahead and merge the PR.

**Comment by tankh99** [comment]
Thanks @damithc!
