### ISSUE TITLE
Week 8 UML worked example 3

### ISSUE THREAD

**Issue by Javiery3889** [nus-cs2103-AY2324S2/forum#504]
Hi, for this example are there any implications as to making the `Message` class abstract below? Attached is the screenshot of the UML diagram discussed in the video. Thank you!

<img width="1188" alt="Screenshot 2024-03-11 at 21 41 47" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/28281451/34cbf272-d204-46a0-987f-be78f58be556">

**Comment by damithc** [comment]
@Javiery3889 That's fine too.
