### ISSUE TITLE
IP Peer Evaluations

### ISSUE THREAD

**Issue by xiaorui-ui** [nus-cs2103-AY2324S2/forum#505]
May I ask for the various requirements of the iP: Implementation, Project management, and documentation; are the grades decided by the Canvas survey submitted by the student evaluators, or are they decided by the tutors/profs? Thanks in advance!

**Comment by damithc** [comment]
@xiaorui-ui both.

**Comment by xiaorui-ui** [comment]
Noted, thanks prof!

**Comment by xiaorui-ui** [comment]
Additionally, if we figure out problems in our own code for IP, can we still change it or is it too late?

**Comment by damithc** [comment]
> Additionally, if we figure out problems in our own code for IP, can we still change it or is it too late?

@xiaorui-ui Yes, you can fix them now. Sooner the better, so that there is a chance the fix goes in before your iP is graded.

**Comment by baskargopinath** [comment]
@damithc prof before the ip is finally graded, will we be given a chance to fix our ip for any issues that we missed but was identified and raised by the graders?

**Comment by damithc** [comment]
> @damithc prof before the ip is finally graded, will we be given a chance to fix our ip for any issues that we missed but was identified and raised by the graders?

@bgopi23 Yes, we'll let you know if your iP doesn't make the bar for full marks.

**Comment by baskargopinath** [comment]
@damithc okay thank u prof

**Comment by ZhiWei1010** [comment]
@damithc Hi prof, just a follow-up question, does that mean that if we do not receive any information regarding our iP, we have met the bar for full marks?

**Comment by damithc** [comment]
> Hi prof, just a follow-up question, does that mean that if we do not receive any information regarding our iP, we have met the bar for full marks?

@ZhiWei1010 We'll inform you one way or the other.
