### ISSUE TITLE
Thoughts on creating a custom Date class?

### ISSUE THREAD

**Issue by guanquann** [nus-cs2103-AY2324S2/forum#506]
I am thinking of creating a Date class under the model package, but am wondering if it should be named differently since there is already a default Date class in java package.

**Comment by fy17ohhh** [comment]
could consider calling it `customDate` to avoid confusion

**Comment by c-wenlong** [comment]
I believe that if you import java.util.Date and also have your own Date class in the same file, the compiler will use your local version of Date.
