### ISSUE TITLE
"method" versus "operation" in class diagram?

### ISSUE THREAD

**Issue by E0735389** [nus-cs2103-AY2324S2/forum#507]
In https://nus-cs2103-ay2324s2.github.io/website/schedule/week8/topics.html#w8-1-revisiting-drawing-class-object-diagrams-basics

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/97508964/bcd3797e-27a4-411b-be4a-d484de5c8c49)

Is it true that the two "compartments" refers to the two boxes below the "class name" box? In that case, why is it that in the diagram, the two boxes are labeled "attributes" and "**methods**", while in the explanation, they're referred to as "attributes" and "**operations**"?

**Comment by damithc** [comment]
@E0735389 
> Is it true that the two "compartments" refers to the two boxes below the "class name" box?

Yes

> In that case, why is it that in the diagram, the two boxes are labeled "attributes" and "**methods**", while in the explanation, they're referred to as "attributes" and "**operations**"?

Although the switch between the two terms here was not intended, note that those two terms are interchangeable in this context. The top compartment is for attributes (aka _data_) and the bottom one is for methods (aka _operations_/_functions_)
