### ISSUE TITLE
How thorough should our PR reviews be?

### ISSUE THREAD

**Issue by jyztintan** [nus-cs2103-AY2324S2/forum#508]
While CS2103T has taught us the [best practices for PR reviews](https://se-education.org/guides/guidelines/PRs-reviewing.html), I realised it is mostly about the semantics and code quality visually. However, we have not really discussed much about the thorough technical aspects of reviewing. 

Here are some questions I would like to seek advice for with regard to this:
1) How thorough should we be reviewing our peer's PR in TP? What are some important things to look out for? (functionality, optimisation, coding style etc?)
2) Could you describe your typical workflow in submitting/accepting PRs? 
3) Is it necessary to pull our peer's PR and ensure everything runs well before approving? 

My group has decided on our general workflow to be: 
PR from individual fork to project's master branch -> all members look through PR -> (unsure if need to pull PR code and test) -> approve and merge when no visible issues

Would like to any relevant advice on this and with regard to our workflow would be good :)
Thank you!

Related info:
https://www.gustavwengel.dk/how-thoroughly-should-you-review-pull-requests

**Comment by damithc** [comment]
@jyztintan This is a good point for discussion. Thanks for sharing the relevant link too.
Others, feel free to pitch in with your views or share what your team is doing.

**Course admin perspective:** It's up to you. We do not directly enforce any requirement on this. How well you do this can affect your grade indirectly though e.g., if PR reviews are weak, low quality code could get merged, which can in turn affect grading for code quality and bugs in the product. If you 'overdo' PR reviews, you'll waste time/effort and slow down the progress, which can affect marks as well.

**Teaching/learning perspective:** Learning to optimize the _process_ is an intended learning outcome. You can do this iteratively. That is, the team can decide your own policy/process, and tweak it as you go. For example, you can decide to have a minimum of n reviews at rigor level X for each PR. After doing that for a while, you can evaluate how it is working, and tweak if necessary (reduce n or lower X if you feel like it is slowing down the project too much without helping to increase quality that much | increase n or set a higher X if you think the code being merged is below-par quality). 

**SE perspective:** The answer to your question depends on many things, such as target quality (higher target quality requires high rigor PR reviews), availability of reviewers, level of other quality assurance mechanisms in place (e.g., automated checks done on the code, such as Checkstyle). Might even vary based on type of PR (some PRs need closer scrutiny than others). Should reviewer run the code locally? This also depends on if (and how well) the work in the PR is covered by automated tests run by the CI.
Most long-running projects in real world will establish their own policies/norms, either written down formally or passed down informally (i.e., new devs follow what current devs do).

**Comment by dillontkh** [comment]
Just to share my PR review process:

1. Understand what the PR is supposed to achieve.
1. Go through the code to see what was changed, and get a rough understanding of how it was done.
    Things I look out for:
    1. Code readability
    1. Comments
    1. Any egregious coding standard/quality violations
1. If it was a significant feature (e.g. new command, UI changes), pull the PR and test the MSS.

On @jyztintan's 3rd point, I feel like it is the responsibility of the developer submitting the PR to ensure the program is in a usable state before submitting the PR, so pulling the PR and testing it should not be required every time.

**Comment by PallonCX** [comment]
For me, I usually read through all the code and try to understand why the code was added. I seek clarification from the teammate who made the change before approval.

Although this workflow may take some time, I believe it is worthwhile as it reduces the chance of introducing bugs and potential risks of failure.

As a side note, I prefer not to "stack" multiple changes into a single pull request. It takes the reviewer more time to understand the changes, or may encourage them to simply LGTM without thorough review, thereby increasing the vulnerability of the codebase.

**Comment by jyztintan** [comment]
Thanks everyone for your inputs!
