### ISSUE TITLE
Changing Parser in tP to use Apache Commons CLI Library 

### ISSUE THREAD

**Issue by camille-readbean** [nus-cs2103-AY2324S2/forum#509]
## Library

[Apache Commons CLI](https://commons.apache.org/proper/commons-cli/)

## Purpose

We want to explore potentially using this library to replace the parser in tP because the input format `p/(phone_number}` is not very verbose compared to CLI standards people are normally used to like `--phone {phone number}`. We also think it might be easier for development, abstraction. 

It is currently a hypothetical thought process, can we specify in NFR like parser library must be third party for example?

The Apache Commons CLI library provides an API for parsing command line options passed to programs. It's also able to print help messages detailing the options available for a command line tool.

Commons CLI supports different types of options:

- POSIX like options, for example `tar -zxvf foo.tar.gz`
- GNU like long options, for example `du --human-readable --max-depth=1`
- Java like properties, for example `java -Djava.awt.headless=true -Djava.net.useSystemProxies=true Foo`
- Short options with value attached, for example `gcc -O2 foo.c`
- long options with single hyphen, for example `ant -projecthelp`

A typical help message displayed by Commons CLI looks like this:

```
usage: ls
 -A,--almost-all          do not list implied . and ..
 -a,--all                 do not hide entries starting with .
 -B,--ignore-backups      do not list implied entried ending with ~
 -b,--escape              print octal escapes for nongraphic characters
    --block-size <SIZE>   use SIZE-byte blocks
 -c                       with -lt: sort by, and show, ctime (time of last
                          modification of file status information) with
                          -l:show ctime and sort by name otherwise: sort
                          by ctime
 -C                       list entries by columns
```     

## License

[Apache 2.0 License](https://www.apache.org/licenses/LICENSE-2.0)

Git repo: https://github.com/apache/commons-cli?tab=readme-ov-file

**Comment by damithc** [comment]
Approved.
