### ISSUE TITLE
No answer text provided for Week 9 Quiz Q15

### ISSUE THREAD

**Issue by Dethada** [nus-cs2103-AY2324S2/forum#514]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/24560736/db6587a9-b6dc-4eac-924b-60e5a6665ff1)

**Comment by damithc** [comment]
@Dethada Thanks for reporting this. Result of a Canvas bug. I've added the answers again.

**Comment by damithc** [comment]
For the record, this is the fixed version:

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/e08d266f-cd30-4093-b22b-45e9a50713ee)
