### ISSUE TITLE
How do I test my teammates PRs without merging to master

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#515]
Lets say my teammate made a feature on their tp repo on a branch and PRed to the team TP repo, how do I test this when it hasn't been merged to master yet?

**Comment by UdhayaShan1** [comment]
Add your team repo as a remote. 

`git fetch <remote_name> pull/<pr_no>/head:<branch-name>`
For eg,
`git fetch main-repo pull/95/head:v1.2-types-add_seller_buyer_status`

If you want to update the branch, switch to another branch and repeat

**Comment by jinhanfromNUS** [comment]
I do not know if there is any features dedicated to this scenerio, but the first though which came into my mind was, instead of pushing it into the master branch of team repo, can try push it to another temporary branch. Not sure whether it works tho, just an idea

**Comment by baskargopinath** [comment]
thanks @UdhayaShan1 @jinhanfromNUS

**Comment by damithc** [comment]
A more detailed explanation of what @UdhayaShan1 shared above ...

https://devopscube.com/checkout-git-pull-request/
