### ISSUE TITLE
Implementing undo feature from ab4

### ISSUE THREAD

**Issue by justincred** [nus-cs2103-AY2324S2/forum#516]
Hi, if currently I'm implementing the undo feature for v1.2a and its recommended to follow the ab4 undo feature. Would it count towards work done and is there a need to cite it as it says no need to cite for ab3?

**Comment by damithc** [comment]
@justincred 
1. Yes, you need to mention that the feature was ported/inspired/adapted (choose based on level of reuse) from AB4
2. Yes, it counts. As in the case of any reuse, the effort credited to you is the effort spent on reusing the code, not the effort required for implementing it from scratch.

**Comment by justincred** [comment]
ok thank you!
