### ISSUE TITLE
Acceptability on data corruption handling

### ISSUE THREAD

**Issue by tankh99** [nus-cs2103-AY2324S2/forum#519]
Hello, I'd like to ask  if it's acceptable to just use the current AB3 way of handling data corruption, which currently just regenerates a new JSON file upon finding incorrect data, such as an incorrect email format?.

Is this approach alright?

**Comment by damithc** [comment]
> Hello, I'd like to ask if it's acceptable to just use the current AB3 way of handling data corruption, which currently just regenerates a new JSON file upon finding incorrect data, such as an incorrect email format?.

@tankh99 Yes, this level of error handling is enough for errors in the data file.

**Comment by tankh99** [comment]
Thank you1
