### ISSUE TITLE
iP peer evaluation

### ISSUE THREAD

**Issue by Morninggloryyy** [nus-cs2103-AY2324S2/forum#522]
Hi! May I check which one I should select if there are at least two JUnit tests but no use of exceptions to handle errors? Thank you!
<img width="707" alt="bc4a67718d8df35b12e5b2a9502f2e3" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/156987743/5e95a1b2-ca9b-458d-8e60-a940ae719346">

**Comment by damithc** [comment]
@Morninggloryyy In that case it is considered 'below expectations'.

**Comment by Morninggloryyy** [comment]
@damithc Thank you so much for your clarification!
