### ISSUE TITLE
Wrong git commit message convention in pull requests

### ISSUE THREAD

**Issue by E0735389** [nus-cs2103-AY2324S2/forum#523]
Once in a while, my teammates doesn't follow the git commit message convention for a pull request.

In that case,
* does it matter for it to be fixed (or will I only be graded based on my commits)?
* If it does, should I recommend the teammates to learn "dangerous" git commands like `git reset`, `git rebase` etc. to fix the issues? (Although I notice that these commands are not taught in our module)

I assume it's not recommended to edit the commits once they're merged to master (among other reasons, one of them is that editing it later will change the timestamp), but I assume changing it before it's merged should be fine?

**Comment by damithc** [comment]
@E0735389 
* Git commit convention is graded based on who created the commit. So, you just need to follow the convention for your own commits.
* We don't prohibit editing past commits but note that it can change the timestamp of commits, and cause further problems to other team members if the original commit was already pulled by them.
* Violating the convention in 1-2 commits is unlikely to affect marks but more violations than that can affect marks.
