### ISSUE TITLE
Leave tests failing for intermediate states of the project?

### ISSUE THREAD

**Issue by E0735389** [nus-cs2103-AY2324S2/forum#524]
Is it (not) recommended to fix the tests for every pull request?

Generally I'd think the answer is yes, but consider the following case:
* a command X needs to have feature Y and Z added.
* One person sends a pull request to add feature Y, and modify the tests for X.
* Another person sends a pull request to add feature Z, and modify the tests for X.
It feels like the effort to modify tests are duplicated that way.

**Comment by damithc** [comment]
@E0735389 See if [this FAQ](https://nus-cs2103-ay2324s2.github.io/website/schedule/week8/project.html#:~:text=FAQ%3A%20Do%20we%20have%20to%20keep%20updating%20tests%20when%20we%20update%20functional%20code%3F) answers your question
