### ISSUE TITLE
Typo in textbook

### ISSUE THREAD

**Issue by E0735389** [nus-cs2103-AY2324S2/forum#525]
In https://nus-cs2103-ay2324s2.github.io/website/schedule/week8/project.html#tp-mid-v1-2

> While we are on the topic, also note that the architecture of AB3 doesn't **suite** every kind of application either.

I think it should be "suit" (I checked "suite" and it can only be used as a noun)

**Comment by damithc** [comment]
Good catch. Thanks @E0735389 
Fixed.
