### ISSUE TITLE
Questions on UML diagrams

### ISSUE THREAD

**Issue by tankh99** [nus-cs2103-AY2324S2/forum#527]
I'm still quite unsure about what I can and cannot do in UML diagrams, so please forgive the amount of questions I have here. If there are any answers to questions available on the CS2103 site or quizzes, please just let me know where to look for the answers. 

### General
1. If A and B, 2 classes in a system, both use the same database object to query data. Is that considered coupling?

### Sequence Diagrams
1. For alt paths, does the order of the partition matter? Are the executed in a waterfall manner like an actual if-else block?

**Long question**
In Quiz 8 Part 1, Q 21, there seems to are 2 valid interpretations of the following code
```java
Man m = new Man()
m.set(new Dog());
```
There seem to be 2 different interpretations of this creation. Are both valid?
1. You create the object and then pass it into the function
3. Inside the function, you create the object.
So my question here is that, in sequence diagrams, can there be multiple valid interpretations to the same code?

---

### Class & Object Diagrams
1. Is it okay to represent dependencies as dashed lines without any arrows, just like how class diagrams often have solid lines without navigabilities?
3. If we don't declare a visibility for a method or attribute, are they by default public? Or is that just unique to interfaces? What is the default visibility?
4. Is an abstract declaration still valid if {abstract} is not italicised but the text is not red? This question extends to the other headers like <<enumeration>> and <<interface>
5. In an abstract class, is it wrong to omit the {abstract{ modifier for the print() class in the below image?
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/56617918/8a15722a-edec-4049-9322-a167e5815847)
6. For attribute associations, if a list is initialised to an empty list at the start, does it have a default value? 
   1. If so, how do we show it?
   2. If no, then is showing default value optional? Does this extend to all attributes?
7. Does enumeration headers need to be bolded?
8. Can association roles and association labels appear on the same association at the same time?
9. In a class diagram, can we represent our associations as lines for some classes, and associations as attributes for other classes such that associations are not used as both lines and attributes at the same time. Is this valid?
10. Is an object diagram valid if there are associations between objects, but no navigability or association roles is denoted?

Thank you in advance!

**Comment by damithc** [comment]
@tankh99 Good questions. My answers below:

> 1. If A and B, 2 classes in a system, both use the same database object to query data. Is that considered coupling?

Let's say the database object is of class D.
Yes, this can result in a form of weak coupling, depending on the context. For example, if a change in the way class A uses D can potentially require a change in B as well, then B is coupled to A (as per the definition of coupling).


> 1. For alt paths, does the order of the partition matter? Are the executed in a waterfall manner like an actual if-else block?

No. As no more than one of the guard conditions can be true at any given time, the order doesn't matter.

> In Quiz 8 Part 1, Q 21, there seems to are 2 valid interpretations of the following code
> 
> ```java
> Man m = new Man()
> m.set(new Dog());
> ```
> 
> There seem to be 2 different interpretations of this creation. Are both valid?
> 
> 1. You create the object and then pass it into the function
> 2. Inside the function, you create the object.
>    So my question here is that, in sequence diagrams, can there be multiple valid interpretations to the same code?

Only one of these interpretations is correct. You can find out which one by doing a small experiment.

> 1. Is it okay to represent dependencies as dashed lines without any arrows, just like how class diagrams often have solid lines without navigabilities?

Dependencies are directional. So, there should be an arrowhead.


> 2\. If we don't declare a visibility for a method or attribute, are they by default public? Or is that just unique to interfaces? What is the default visibility?

There is no default visibility in UML, even for interfaces. If not shown, it means _unknown_. But in Java, interface members are implicitly public (no other choice). So, it doesn't matter if you show `+` or not for interface members in a UML diagram. They are already _known_ to be public.


> 3\. Is an abstract declaration still valid if {abstract} is not italicised but the text is not red? This question extends to the other headers like <> and <

🤔 hmm... why did you mention red? UML does not attribute any meaning to the color.

> 4\. In an abstract class, is it wrong to omit the {abstract{ modifier for the print() class in the below image?

Yes, that would be misleading i.e., showing an abstract method as a concrete method.


> For attribute associations, if a list is initialised to an empty list at the start, does it have a default value?
> 1. If so, how do we show it?
> 2. If no, then is showing default value optional? Does this extend to all attributes?

Using default value is optional. Furthermore, we don't normally show data structures such as lists in UML class diagrams. The use of multiplicity such as `*` already imply the use of some collection data structure, without needing to show the class (e.g., ArrayList) in the diagram.

> 6\. Does enumeration headers need to be bolded?

No. Bolding doesn't have any meaning in UML.


> 7\. Can association roles and association labels appear on the same association at the same time?

Yes, although often one is enough to convey the information they capture. Having both might not add any extra value.

> 8\. In a class diagram, can we represent our associations as lines for some classes, and associations as attributes for other classes such that associations are not used as both lines and attributes at the same time. Is this valid?

Yes. This is useful to draw attention to more important associations while giving less important ones a low profile.


> 9\. Is an object diagram valid if there are associations between objects, but no navigability or association roles is denoted?

Yes. Those are optional, same as in class diagrams.

**Comment by tankh99** [comment]
Hi Prof, thanks so much for you comprehensive answers. Just a couple follow-up questions

> > 2. If we don't declare a visibility for a method or attribute, are they by default public? Or is that just unique to interfaces? What is the default visibility?
> 
> There is no default visibility in UML, even for interfaces. If not shown, it means _unknown_. But in Java, interface members are implicitly public (no other choice). So, it doesn't matter if you show `+` or not for interface members in a UML diagram. They are already _known_ to be public.

However, what about normal classes? Are attributes/functions without any declared visibility by default package-private?

**Comment by damithc** [comment]
> However, what about normal classes? Are attributes/functions without any declared visibility by default package-private?

@tankh99 There is no default visibility in UML class diagrams. If not shown, it means _unknown_.

**Comment by tankh99** [comment]
> > However, what about normal classes? Are attributes/functions without any declared visibility by default package-private?
> 
> @tankh99 There is no default visibility in UML class diagrams. If not shown, it means _unknown_.

I understand that there's no default visibility in UML class diagrams, but what if we were designing a class diagram for a Java application? 

You previously mentioned that interface methods are public by default in Java. Then does the default visibility for normal classes also follow the behaviour of Java classes, which is to make methods like
```java
void sayHello() {...}
```
as package-private?

So in a class diagram if there's a method like `sayHello()` without any visibility behaviour, is it still considered unknown? Or is it considered as package-private (~)?

**Comment by damithc** [comment]
@tankh99 
```java
class Duck {
  void eat() { \* ... *\}
  public void fly() { \* ... *\}
}
```

Class diagram option A1: visibility not shown, which means visibility unknown (to the reader of the diagram). 
```mermaid
classDiagram
    class Duck{
        eat()
        fly()
    }
```
In the above, you can also see why we shouldn't assume the visibility is package private when not shown, because `fly()` is actually `public`.

Class diagram option A2: visibility shown/known
```mermaid
classDiagram
    class Duck{
        ~eat()
        +fly()
    }
```
PS: both options are valid. It's just A2 shows more info than A1.

-------
```java
interface Flyable{
  void fly();
]
```

Class diagram option B1: visibility shown (we show it as `public` because Java interface methods are implicitly public).
```mermaid
classDiagram
    class Flyable{
        <<interface>>
        +fly()
    }
```
Class diagram option B2: visibility not shown, but we still "know" it to be `public` as Java dictates that it is `public`.
```mermaid
classDiagram
    class Flyable{
        <<interface>>
        fly()
    }
```

Similarly, both options are valid.

**Comment by tankh99** [comment]
Thanks @damithc for clarifying. Correct me if I'm wrong, but what I'm understanding here is that in the context of Java class diagrams, classes should always have their visibilities declared, otherwise the class diagram is invalid. Interfaces, however, is an exception as we can assume visibilities to be public

**Comment by damithc** [comment]
> Correct me if I'm wrong, but what I'm understanding here is that in the context of Java class diagrams, classes should always have their visibilities declared, otherwise the class diagram is invalid.

@tankh99 Did you mean _UML class diagrams for Java programs should always show visibility_? That's not correct. Showing visibility is optional. For example, both options A1 and A2 in my previous post are valid. It's just that A1 shows less information than A2.

**Comment by tankh99** [comment]
> > Correct me if I'm wrong, but what I'm understanding here is that in the context of Java class diagrams, classes should always have their visibilities declared, otherwise the class diagram is invalid.
> 
> @tankh99 Did you mean _UML class diagrams for Java programs should always show visibility_? That's not correct. Showing visibility is optional. For example, both options A1 and A2 in my previous post are valid. It's just that A1 shows less information than A2.

Apologies for getting it wrong. Yes, I was referring to UML Class diagrams for Java programs. So I realise that showing visibility in class diagrams is optional. And that we cannot assume visibility for classes in class diagrams. But why can we assume so for interfaces?

Since Java 9, interface methods can be private, so we could have something like
```java
interface Flyable {
  private void fly();
}
```

And in our class diagrams, we have

```mermaid
classDiagram
  class Flyable {
    <<interface>>
    fly()
  }

```

Doesn't this mean we cannot assume that the Flyable interface method is public? Since it is actually also private?

**Comment by damithc** [comment]
> Since Java 9, interface methods can be private, so we could have something like
> 
> ```java
> interface Flyable {
>   private void fly();
> }
> ```

@tankh99 I don't think the above code works. 

Yes, recent Java versions added other very Java specific features such as default methods, and the ability to include private methods for internal use within the interface. But in the UML discussion we were focusing on regular interface methods i.e., the abstract methods that makes up the _interface_. Those cannot be private. Making them private would break the concept of an interface, as an interface is something you expose to the outside world, for other classes to implement or rely on. 
If you want to show those Java-specific private methods in a UML diagram (which is unlikely to be useful, as they are for internal use within the interface), you should show the visibility of all methods so that there is no ambiguity.

**Comment by tankh99** [comment]
> Yes, recent Java versions added other very Java specific features such as default methods, and the ability to include private methods for internal use within the interface. But in the UML discussion we were focusing on regular interface methods i.e., the abstract methods that makes up the _interface_. Those cannot be private. Making them private would break the concept of an interface, as an interface is something you expose to the outside world, for other classes to implement or rely on. If you want to show those Java-specific private methods in a UML diagram (which is unlikely to be useful, as they are for internal use within the interface), you should show the visibility of all methods so that there is no ambiguity.

Ahhh, I understand now! I was confused because I was wondering why we could assume visibility for interfaces but not classes. But this resolves it. Thanks so much for your patience Prof!
