### ISSUE TITLE
Week 9 Quiz Q15 No answer text provided (again)

### ISSUE THREAD

**Issue by yisiox** [nus-cs2103-AY2324S2/forum#528]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/107540644/6b90e572-36e9-4161-b138-e79ad2724849)

I am aware there should be some pictures here and this was raised in #514, but I am having this problem still. 

Just in case I have checked that I don't have any blockers of any sort active and am currently on the latest version of chrome.

**Comment by Jerome-j** [comment]
I can confirm that I face the same problem as you

**Comment by damithc** [comment]
@yisiox Yes, this was fixed earlier. When I preview the quiz, this is what I see:

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/2db83798-8af0-42de-b6b9-983b5f3570a0)

But it is possible that Canvas shows the old version of the question to those who started the quiz before I fixed the problem. Canvas does this kind of weird/stupid things.

**Comment by yisiox** [comment]
@damithc Got it, thank you Prof.
