### ISSUE TITLE
Question on branching and PR

### ISSUE THREAD

**Issue by JerryWang0000** [nus-cs2103-AY2324S2/forum#529]
Suppose I need to commit to update documentations in a project, and I initiate a branch called `branch-Ducumentation`. Now I can PR this branch to the upstream repo. Suppose after several rounds of PR I need to update the  documentation again. Do I just use the existing `branch-Documentation` branch or start a new branch? If former is the case, do I need to merge the master branch first to the current branch I'm working on?

**Comment by tankh99** [comment]
Hi, just adding my opinion here. In general, I think that it's okay to update documentations through several branches. Once a branch is merged, I think it's better to not reuse the same branch.

**Comment by damithc** [comment]
@JerryWang0000 Each PR should be from a separate branch (not an existing branch that was used for previous PRs).
