### ISSUE TITLE
Can we use StarUML to update our DG use case diagrams?

### ISSUE THREAD

**Issue by tankh99** [nus-cs2103-AY2324S2/forum#532]
I was just wondering if it's recommended to use StarUML or not

**Comment by damithc** [comment]
@tankh99 The course requirements for the diagramming tool are given [here](https://nus-cs2103-ay2324s2.github.io/website/admin/tp-deliverables.html#dg-tips:~:text=different%20UML%20diagrams.-,Diagramming%20tools,-%3A)

**Comment by tankh99** [comment]
Understood. We'll just stick to PlantUML for this
