### ISSUE TITLE
Undo command not working

### ISSUE THREAD

**Issue by radeon2525** [nus-cs2103-AY2324S2/forum#533]
I want to implement a undo command in my project, I can abstracted the undo command implementation from AB-4. However on making changes and then running the undo command,

The GUI says - "No more commands to undo!" even though I just added a person. 

The terminal says - "INFO: ----------------[USER COMMAND][undo]
Mar 18, 2024 1:34:56 PM seedu.address.ui.MainWindow executeCommand
INFO: An error occurred while executing command: undo"

Can someone tell me how to fix this

**Comment by chiralcentre** [comment]
This is so vague; it is very hard to help you if more information is not provided. Have you tried the debugging feature and stepping through the code one line at a time? Print out the error stack trace as well.

**Comment by radeon2525** [comment]
I was able to find and fix the bug, thank you
