### ISSUE TITLE
CI Failing for a weird reason

### ISSUE THREAD

**Issue by RunjiaChen** [nus-cs2103-AY2324S2/forum#534]
<img width="1714" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/142142406/7cf46222-d4cd-4fa3-a12b-bf5e85e48c67">
Hello, has anyone encountered this error for CI before? Can someone provide suggestions on how to solve this problem? Thank you!

**Comment by jovantanyk** [comment]
I've encountered it a few times, but usually rerunning the job seems to fix the issue

**Comment by RunjiaChen** [comment]
Thank you!
