### ISSUE TITLE
Only 3 UML diagrams to update for 5 members for week 9 TP task

### ISSUE THREAD

**Issue by Dethada** [nus-cs2103-AY2324S2/forum#535]
In the week 9 TP task 2 it states
> Each member is expected to update at least one UML diagram in the DG

However for our team, there is only 3 diagrams that require changes, but we have 5 members. How should we go about this?

@Javiery3889 @KohGuanZeh @Arixeyeion @YuZizhen

**Comment by damithc** [comment]
@Dethada Multiple people can update different parts of the diagram that is relevant to their work. Also, you can add more diagrams.

Also see the first two points given under [DG Tips](https://nus-cs2103-ay2324s2.github.io/website/admin/tp-deliverables.html#dg-tips:~:text=in%20future%20iterations.-,DG%20Tips,-Aim%20to%20showcase)

**Comment by Dethada** [comment]
Okay, thanks prof
