### ISSUE TITLE
When is the due date for updating UML diagrams?

### ISSUE THREAD

**Issue by Dethada** [nus-cs2103-AY2324S2/forum#536]
In the week 9 TP task 2 (Start updating UML diagrams in the DG) it states
> You may do this towards the end of v1.2, or soon after you finish it.

When exactly do we have to finish it by, is it Thu, Mar 21st 23:59?

@Javiery3889 @KohGuanZeh @Arixeyeion @YuZizhen

**Comment by damithc** [comment]
@Dethada weekly tasks without a specific deadline become overdue (i.e., red) after Friday 4pm, and we keep checking them for about a week after that (they can turn back to green if done within the following week).

**Comment by Dethada** [comment]
Got it, thanks prof
