### ISSUE TITLE
Requesting help for smoke test

### ISSUE THREAD

**Issue by yyccbb** [nus-cs2103-AY2324S2/forum#537]
My iP app works fine on Windows 11, but my peer reviewer reported bugs where the app simply gives "null" responses when supplied with any correct command. A screenshot submitted by the reviewer is attached.
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/35594369/0c64c681-e805-4046-828f-1298a1526fde)
It is greatly appreciated if anyone could help test the app under Windows that runs **java 11** or macOS that runs the prescribed java distribution [here](https://nus-cs2103-ay2324s2.github.io/website/admin/programmingLanguages.html).
* The release can be found at https://github.com/yyccbb/ip/releases/tag/A-Release
* The user guide can be found at https://yyccbb.github.io/ip/

**Comment by Jerome-j** [comment]
Hi it does not give me the null error

<img width="512" alt="Screenshot 2024-03-19 at 6 33 13 AM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/49815108/b4264dc6-186b-4c76-92bf-6ea1d2031ee9">

**Comment by leawang0** [comment]
Hi, senior from a previous batch here. I've tested your jar on Windows 11 and it appears everything worked fine. I have tried all commands and there is no null error.
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/83194176/f84461a2-c3db-4a22-904c-a6e00d2a0202)

You can consider revising the 'deadline' and 'event' sections in your UG! The sample test case given is incorrect because month and day is reversed.

**Comment by yyccbb** [comment]
> Hi, senior from a previous batch here. I've tested your jar on Windows 11 and it appears everything worked fine. I have tried all commands and there is no null error. ![image](https://private-user-images.githubusercontent.com/83194176/313904844-f84461a2-c3db-4a22-904c-a6e00d2a0202.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MTEzNTAsIm5iZiI6MTcxMDkxMTA1MCwicGF0aCI6Ii84MzE5NDE3Ni8zMTM5MDQ4NDQtZjg0NDYxYTItYzNkYi00YTIyLTkwNGMtYTZlMDBkMmEwMjAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDA1MDQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4NmViZGYxOTdlYjEyN2VjMzBkNWVhODc1MjAxMzViYzg1NmRmYjAzZGViNmI5NzEyNmUwZjk2YmQyNTA3YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6tQfxpVnpHJ2kf6rh92M4JvNLfPVShP-CYZ8fxOtb58)
> 
> You can consider revising the 'deadline' and 'event' sections in your UG! The sample test case given is incorrect because month and day is reversed.

Thank you for making me aware of this issue with the UG. I have fixed it!
