### ISSUE TITLE
How to make v1.2 light up on dashboard

### ISSUE THREAD

**Issue by RunjiaChen** [nus-cs2103-AY2324S2/forum#538]
Hello, does anyone know how to make the v1.2PR light up on the dashboard? 
<img width="1363" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/142142406/cc93106e-b262-4e4c-a73f-f84bcb4e5a0e">
I assigned my PR to a milestone, and the PR was closed by my teammate, but somehow it is not tracked on the dashboard? Thank you!

**Comment by damithc** [comment]
When was the PR merged? Was if before or after the most recent dashboard update?

**Comment by RunjiaChen** [comment]
Apologies, the dashboard has been updated.
