### ISSUE TITLE
Request for help with TP parser changing prefix

### ISSUE THREAD

**Issue by camille-readbean** [nus-cs2103-AY2324S2/forum#540]
My PR: https://github.com/AY2324S2-CS2103T-T17-1/tp/pull/26

Description:

Changing prefix to "--tags " instead of "t/" no longer allow input to only have the parameters. 
See https://github.com/AY2324S2-CS2103T-T17-1/tp/pull/26/files#
>  src/main/java/seedu/address/logic/parser/CliSyntax.java

Previously: `"add n/Etc t/"` (OK)  
Now: `"add --name etc --tags "` (Fail)

What causes this change in behavior? I am expecting that a change in prefix shouldn't result in a change in that as well

This result in test in `AddressBookParserTest` failing
PersonBuilder generates an empty Tag Set
"--tags " doesn't work with empty tags
So getEditPersonDecriptor returns no --tags flag with an empty set
this breaks the test as the Tag Set is now null instead of EmptySet
but then the editPersonDescription will be different from the one from PersonBuilder
hence the build fails
Make the tag Set non-empty, so it will be forced to generate a tag flag
the tag in the command and so it can update it

**Comment by damithc** [comment]
@camille-readbean To be clear, are you asking for ideas on debugging/fixing this problem you are facing?

**Comment by camille-readbean** [comment]
> @camille-readbean To be clear, are you asking for ideas on debugging/fixing this problem you are facing?

Hi yes, I meant to ask how does to fix this / what causes this difference

**Comment by seanfirefox** [comment]
Hi senior here,

```
public void setTags(Set<Tag> tags) {
    this.tags = (tags != null) ? new HashSet<>(tags) : null;
}
```
are you not able to just return an empty hashset rather than returning null? Then it will be like the `PersonBuilder` generating an empty tag set.

**Comment by lhy-hoyin** [comment]
Hi @camille-readbean,

I see that your PR has been merged. Additionally, in the PR description: "Temp Fixed by removing trailing white spaces in prefix".
I supposed that you have resolved the issue, albeit temporary.

Do you still required further assistance in investigating why/what caused this issue?

**Comment by camille-readbean** [comment]
> Hi @camille-readbean,
> 
> I see that your PR has been merged. Additionally, in the PR description: "Temp Fixed by removing trailing white spaces in prefix". I supposed that you have resolved the issue, albeit temporary.
> 
> Do you still required further assistance in investigating why/what caused this issue?

Hii, I think I will close the issue now. It's just a technical curiosity. I suspect it is the way regex handles it, the arguments have whitespace striped automatically so maybe it's an issue with that.
