### ISSUE TITLE
[Help wanted] Very long parameters in UML diagram

### ISSUE THREAD

**Issue by camille-readbean** [nus-cs2103-AY2324S2/forum#542]
Hi is it okay to replace long parameters with '...' or an alias, like `KEYWORD`

For example my current UML look like this

```
[-> LogicManager : execute("add ~--name=Name ~--phone=2103 ~--email=hello@Test ~--addr=Address ~--tags=hello ~--tags=Hi")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("add ~--name=Name ~--phone=2103 ~--email=hello@Test ~--addr=Address ~--tags=hello ~--tags=Hi"")
activate AddressBookParser
```

**Comment by damithc** [comment]
@camille-readbean Yes, if the resulting loss of information is worth the reduction in clutter.

**Comment by camille-readbean** [comment]
Alrights I decided to just shorten it to `add [ARGS]` and elaborate on ARGS in the developer guide.
