### ISSUE TITLE
Should our UML Diagrams follow exactly our v1.2 implementation?

### ISSUE THREAD

**Issue by tankh99** [nus-cs2103-AY2324S2/forum#543]
Right now due to time constraints, my team is skipping refactoring and just adding code on top of existing one. This means that classes like Model.java have functions for 2 different model types, Person and a new model type we added. This, however is a temporary measure and would likely be refactored away in v1.3. 

My question here is, do we need to update our UML diagrams exactly according to our current implementation, or what we envision the end result to be?

**Comment by damithc** [comment]
> My question here is, do we need to update our UML diagrams exactly according to our current implementation, or what we envision the end result to be?

@tankh99 Your decision. Either way is fine with us. The objective of the `UML Updated ` deliverable is to get you all started on UML diagramming earlier rather than later, which we still achieve irrespective of which of the two options you choose.

**Comment by tankh99** [comment]
Understood, thank you Prof!
