### ISSUE TITLE
Refactoring other members' tP ocde

### ISSUE THREAD

**Issue by tankh99** [nus-cs2103-AY2324S2/forum#546]
I'd like to ask what would happen in the grading if we were to refactor code, and some parts of it included someone else's code. Is it recommended to perform such a refactor? Or do we ask the person in charge to refactor?

**Comment by damithc** [comment]
@tankh99 either is fine. The team can decide. Also note:
1. While the [code dashboard](https://nus-cs2103-ay2324s2.github.io/tp-dashboard/?search=&sort=groupTitle&sortWithin=title&timeframe=commit&mergegroup=&groupSelect=groupByRepos&breakdown=true&checkedFileTypes=docs~functional-code~test-code~other) credits a line to the last author, [there is a way to override that and allocate a block of code to a specific author](https://nus-cs2103-ay2324s2.github.io/website/admin/tools.html#tool-reposense-for-authorship-tracking)
2. Each student is [graded for the quality of the code](https://nus-cs2103-ay2324s2.github.io/website/admin/tp-grading.html#tp-grading:~:text=2A.-,Code%20quality,-Evaluates%3A%20the) (e.g., coding standard compliance) based on the lines s/he authored, as per authorship indicated in the code dashboard

**Comment by tankh99** [comment]
Noted, thank you!
