### ISSUE TITLE
Commit messages automatically generated by git violates git convention rule?

### ISSUE THREAD

**Issue by E0735389** [nus-cs2103-AY2324S2/forum#547]
e.g. the commit messages

```
Merge remote-tracking branch 'upstream/master ' into long-branch-name
```

can definitely overrun the 72 character limit.

What's the recommended course of action? (just leave it be? Or rebase?)

**Comment by damithc** [comment]
@E0735389 It's OK to just leave it be. We ignore auto-generated merge commit messages when grading Git convention compliance.
