### ISSUE TITLE
Whether this method has arrow head problem?

### ISSUE THREAD

**Issue by Ella-e** [nus-cs2103-AY2324S2/forum#548]
Hi, I am not sure whether this method is considered a long method or suffer from arrow head problem. Could anyone help me take a look? If it does suffer from arrow head problem, how could I adjust to solve?

Where this method is called: ```nextTasks.sort(this::compareTaskByDate);```
```java
private int compareTaskByDate(Object o1, Object o2) {
        if (o1 instanceof Todo) {
            return 1;
        }
        if (o2 instanceof Todo) {
            return -1;
        }

        if (o1 instanceof Deadline) {
            if (o2 instanceof Deadline) {
                return ((Deadline) o1).getBy().compareTo(((Deadline) o2).getBy());
            }
            if (o2 instanceof Event) {
                return ((Deadline) o1).getBy().compareTo(((Event) o2).getBy());
            }
        }
        if (o1 instanceof Event) {
            if (o2 instanceof Deadline) {
                return ((Event) o1).getBy().compareTo(((Deadline) o2).getBy());
            }
            if (o2 instanceof Event) {
                return ((Event) o1).getBy().compareTo(((Event) o2).getBy());
            }
        }
        return 0;
    }
```

**Comment by yisiox** [comment]
I think it's not an issue, but should be the nesting can be eliminated by writing it like
```
if (cond1 && cond2) {
    return something;
}
if (cond1 && cond3) {
    return something;
}
```

**Comment by Ella-e** [comment]
Thank you very much! This is very helpful!

**Comment by damithc** [comment]
@Ella-e Something else that you might want to consider is whether there is a better way to implement this logic in the first place, instead of using `instanceof`

For example, see this page [Beware of instanceof operator](http://www.javapractices.com/topic/TopicAction.do?Id=31)
