### ISSUE TITLE
[TP] Unable to run on intelliJ

### ISSUE THREAD

**Issue by alvislowyh** [nus-cs2103-AY2324S2/forum#549]
I am using intelliJ for my TP and im running Azul Zulu 11.0.22 but i keep running into an error when trying to run. My groupmates do not have this issue. I am using MacBook air M2 
<img width="1470" alt="Screenshot 2024-03-20 at 1 08 47 AM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/157791089/7a9269b5-d146-4577-9ed2-211819a7e8b3">

**Comment by camille-readbean** [comment]
It may be caused by not having the dependency installed.

**Comment by damithc** [comment]
@beefsausagee When did you start having this problem? If it was halfway into the tP, what did you do just before that that could have caused this problem to crop up (e.g., changed some setting)?

**Comment by damithc** [comment]
@beefsausagee While waiting for inputs from others, here are some things you can try:
  * Run `./gradlew clean build`
  * Choose `File` -> `Invalidate caches`
  * Close Intellij -> Delete the `.idea` folder -> Re open the project in Intellij
  * Clone the fork to a different location and open the project in Intellij again to get a fresh start without losing changes you did so far.

**Comment by alvislowyh** [comment]
@damithc The last solution worked 
thank you so much Prof
