### ISSUE TITLE
Query on pushing fixed code

### ISSUE THREAD

**Issue by radeon2525** [nus-cs2103-AY2324S2/forum#55]
I pushed my code for Level-4, however I just realized that there was a bug in the output which I have now fixed. Should I just push the corrected code again with the tag "Level-4"?

**Comment by damithc** [comment]
@radeon2525 related: the second question of [this FAQ](https://nus-cs2103-ay2324s2.github.io/website/schedule/week2/project.html#faq-about-ip-increments)

**Comment by radeon2525** [comment]
Okay, thank you prof
