### ISSUE TITLE
Faced a bug, deleted own repo and forked/cloned again, run not available

### ISSUE THREAD

**Issue by jeong-jaeho** [nus-cs2103-AY2324S2/forum#550]
I faced a bug, so I tried deleting own repo and forked/cloned again from the team repo, but now running Main.java is not available.
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/109773933/12f8c05d-9dc6-4db4-be0e-e9c0e6c00289)
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/109773933/84bfac0e-9501-470b-aad3-04eceac8eaf8)

I have set the correct JDK, but I'm not sure what setup steps I missed out
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/109773933/101e1083-37a8-41f1-9255-d661de7519c5)

**Comment by drustanyjt** [comment]
Hi @jeong-jaeho I was wondering how you solved this problem.

**Comment by jeong-jaeho** [comment]
> Hi @jeong-jaeho I was wondering how you solved this problem.

you can set the src folder of your local repo as the Sources Root using "Mark directory as" after right clicking on src folder! It then lets you run Main.java
