### ISSUE TITLE
Activity diagram

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#552]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/73015364/722a5757-5040-4174-b12a-cdea04a54149)

how come the line to a4 doesnt need a condition [c4]?

**Comment by damithc** [comment]
@bgopi23 when there is one path without a condition, you can assume it as the `[Else]` path (which is the third simplification mentioned just above the diagram).

**Comment by baskargopinath** [comment]
i see, thank u prof @damithc
