### ISSUE TITLE
Acceptance testing with actual target user

### ISSUE THREAD

**Issue by tankh99** [nus-cs2103-AY2324S2/forum#553]
I was wondering if we did actual user acceptance testing on our target user, could we list this down anywhere in our final submission? For example, I was thinking of getting our target user to test our application and give feedback on its usability and features

**Comment by damithc** [comment]
@tankh99  While this is not a requirement, you are welcome to do that kind of UAT (user acceptance testing) on your tP. You can document this somewhere in the DG, as a reference for future developers (in case they want to repeat a similar test in future).

**Comment by tankh99** [comment]
Noted, thank you prof!
