### ISSUE TITLE
Revert a PR causing all changes ownership to one person

### ISSUE THREAD

**Issue by vnnamng** [nus-cs2103-AY2324S2/forum#554]
Hi Prof,
I recently merge a PR which causing some issue so I revert it, however upon revert, all the changes done in UML are under my name instead of my teammate's hence the marking script cannot capture.
What is the advice for this case?

**Comment by damithc** [comment]
@vnnamng hmm... how did a revert of a PR caused changes to work done by others? Can you point to the commit in concern?

**Comment by vnnamng** [comment]
> @vnnamng hmm... how did a revert of a PR caused changes to work done by others? Can you point to the commit in concern?

@damithc 
I think it is because the problem with the PR merged is improper track of the merge content, hence I have accidentally delete my teammates part, hence when revert, the readded content becomes mine.

Commit in concern:
https://github.com/AY2324S2-CS2103-F08-2/tp/commit/57a7fedcbc885d2b3ea733eaaf37c5f48e8243b1
https://github.com/AY2324S2-CS2103-F08-2/tp/commit/c38d11a6972964b79c074450213083bd6c93c9c7

**Comment by damithc** [comment]
@vnnamng As you later emailed me the list of commits the dashboard should ignore, I'll configure the dashboard to do so.

**Comment by vnnamng** [comment]
Thank you prof

**Comment by damithc** [comment]
@vnnamng Can you check the code dashboard and confirm those commits are now ignored?

**Comment by vnnamng** [comment]
@damithc I think it got ignored, thank you very much
