### ISSUE TITLE
PR Workflow for debugging teammate's code

### ISSUE THREAD

**Issue by tzyian** [nus-cs2103-AY2324S2/forum#556]
Context: My group was facing a huge annoying major bug which the person in charge couldn't fix.

GitHub doesn't seem to allow re-forking their repo because I already have a fork, so I cannot PR to their fork. So I'm cloning their PR, trying my fixes, then sending patches for them to apply once resolved. This lets them do their PR via the course forking workflow, but I don't get attributed for the changes I made, and then Git blame won't be effective anymore which may be troublesome down the line. It doesn't make sense for me to PR instead because they did the majority of the work. I do not think it is not a good idea to force merge code with major bugs to `master`, but the course workflow doesn't recognise PRs made to branches. 

What's the best way out of this? Or do I have to get write access to their repo, make a new branch on their repo and then PR from their repo to the original branch the PR is on (or just write to their branch directly and risk merge conflict)?

**Comment by E0735389** [comment]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/97508964/a5377179-8d5f-410f-a418-7db6ad943cb7)

You already "have access" to the teammate's repository, as long as the mark above is checked. Just add the remote and push directly to the branch.

**Comment by damithc** [comment]
@rertyy As @E0735389 mentioned above, there are ways your team member can give you write access to their fork. 

Related: You can use `@@author` tags to claim a code block as yours even if Git blame attributes it to someone else. More info [here](https://nus-cs2103-ay2324s2.github.io/website/admin/tools.html#tool-reposense-for-authorship-tracking)

Also note that for things such as helping to fix a bug in someone else's feature, it is better to let the feature author own the code. Claiming those lines/commits as yours doesn't earn you more marks (we don't calculate marks based on Loc) but it can cost you marks if there are other code quality issues (e.g., coding standard violations) in that code. So, a better alternative is to just fix the bug as a 'help' (provided to a colleague, and for the greater good of the team). Hopefully, team members will remember this and rate you accordingly when they submit peer evaluations for you. This is better than becoming 'accountable' for parts of someone else's feature.

**Comment by tzyian** [comment]
Oh I think I forgot to add the remote hence I kept pushing to my own repo hahaha.... thanks!

Noted on the code ownership thing. Because of the OOP, a change somewhere may require changes in quite a number of files so I was concerned about the Git blame; it's easier to trace to know who to ask for help. I suppose bug fixes don't really make that many changes so it should be ok. I'll continue with patches where convenient.

Thanks!
