### ISSUE TITLE
Does README need to be updated continuously for tP?

### ISSUE THREAD

**Issue by E0735389** [nus-cs2103-AY2324S2/forum#558]
Question in the title.

Because we're already updating the UG. Wouldn't it be simpler for the README to just say "Refer to the UG"?

**Comment by damithc** [comment]
@E0735389 README is for those visiting the GitHub project (e.g., other developers interested to learn about this project). UG is for end users. So, they are intended for different audiences. But yes, there is no need to repeat UG content is the README. For such content, you can point to the UG.

As you can see, the overlap between AB3 README and UG is quite low.

Also, there is no need to keep updating README as its content is unlikely to change later. Just need to update once to change it from AB3 to your project.

**Comment by E0735389** [comment]
Turns out the original AB3 README doesn't repeat the UG, and I just forget that someone in my team duplicates the information there. Sorry.
