### ISSUE TITLE
Query regarding TextUiTesting

### ISSUE THREAD

**Issue by radeon2525** [nus-cs2103-AY2324S2/forum#56]
On running the runtest.bat file I am getting the following output: 

cmd.exe /c runtest.bat
Comparing files ACTUAL.TXT and EXPECTED.TXT
FC: no differences encountered

Process finished with exit code 0

Just wanted to confirm if this is fine or should my system display something else like "test passed"?

**Comment by damithc** [comment]
@radeon2525 Let's wait to see how this compares to what other classmates are seeing. In the meantime, you can proceed with the rest of the project.

**Comment by radeon2525** [comment]
Ok prof, I will do that

**Comment by aureliony** [comment]
> On running the runtest.bat file I am getting the following output:
> 
> cmd.exe /c runtest.bat Comparing files ACTUAL.TXT and EXPECTED.TXT FC: no differences encountered
> 
> Process finished with exit code 0
> 
> Just wanted to confirm if this is fine or should my system display something else like "test passed"?

Yes, I get the same output as well.

**Comment by radeon2525** [comment]
Alright thank you for letting me know @aureliony
