### ISSUE TITLE
CATcher smoke test

### ISSUE THREAD

**Issue by RunjiaChen** [nus-cs2103-AY2324S2/forum#565]
Hello, I am a little confused as to what I am supposed to do for CATcher 

<img width="1576" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/142142406/04ba632a-1da0-4639-9e8a-30d6458795ce">

Are we just supposed to create a new issue on the website, and make sure there is a screenshot inside the bug report? What do we write inside the bug report and what screenshot do we use? Do we need to do anything to the alpha repo?

**Comment by damithc** [comment]
@RunjiaChen You are _smoke testing_ CATcher. So, do what a tester would do. That is,  verify that you are able to use CATcher on your computer, to do what you will be using it for later (i.e., report bugs you find in the tP you will be testing in the practical exam).

Specifically, use CATcher to report a few 'pretend' bugs, as if you are reporting bugs that you found while testing someone's tP.
