### ISSUE TITLE
Typo in course website for week 10 topics

### ISSUE THREAD

**Issue by yisiox** [nus-cs2103-AY2324S2/forum#568]
Under Design > Design Patterns > Introduction > What

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/107540644/7f4be28b-8614-42e4-8757-d6cc1208b9b9)

The book writes the author's name as **Erich** Gamma.

**Comment by damithc** [comment]
Fixed. Thanks for the bug report @yisiox
