### ISSUE TITLE
How to draw UML sequence diagrams for enum factories

### ISSUE THREAD

**Issue by yisiox** [nus-cs2103-AY2324S2/forum#570]
Our group opted to use the factory design pattern so that the functionalities of each command is more contained within the commands package to make it more extensible. However we're not sure how to draw the UML sequence diagram for it. Below is what we currently have:

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/107540644/946c6f74-7ae4-463c-8b0a-d09e0ae82d61)

How it works is:
1. `LogicManager` passes the user input to an `AddressBookParser`.
2. `AddressBookParser` uses the static method `CommandType::valueOf` (`CommandType` is an enum) to get the relevant command type.
3. `AddressBookParser` calls `createCommand()` of the command type enum object to get a `Command` object instantiated with the user input arguments.
4. The `Command` object is passed back to logic manager which can now execute it.

Any advice on whether this is correctly represented? Or if anyone can point us to a resource on how to draw sequence diagrams for enum factories it would be much appreciated. TIA

**Comment by damithc** [comment]
@yisiox The given diagram seems like a good representation of the steps you listed.
Another alternative is to abstract away the workings of the 'factory' steps. For example, `AddressbookParser` can do a self-call to a method `createCommandUsingFactory()` and you can add a note that it is not a real method but a simplification of the command creation steps. This ficticious method can be shown to call the `DeleteCommand` constructor.
That way, the following details can be omitted from the diagram.
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/dcb62805-104a-4452-a7ec-fe131b4ab6b4)

**Comment by yisiox** [comment]
@damithc Got it, thank you Prof
