### ISSUE TITLE
Git commit message convention for PR merges

### ISSUE THREAD

**Issue by Jaspertzx** [nus-cs2103-AY2324S2/forum#571]
Hello! Would like to ask if using the Git created merge subject is in violation of the [Git commit message conventions](https://se-education.org/guides/conventions/git.html).

For e.g. `Merge pull request 111 from <username>/<really-long-branch-name-that-my-groupmate-used>`

I understand that this merge commit will definitely be breaking the hard limit of 72 characters, but I created the merge as I couldn't figure out the best way to approach this.

Would like to have advice on
1. Is this in violation of the Git commit message conventions, or is that applicable only to personal commits only?
2. What convention should we follow for merge commit subject and body messages?

Thank you all in advance! and have a good weekend.

**Comment by jyztintan** [comment]
I think this is a duplicate of #547

**Comment by Jaspertzx** [comment]
My bad, thanks for linking it.
