### ISSUE TITLE
Minor typo in course website W10.4

### ISSUE THREAD

**Issue by jyztintan** [nus-cs2103-AY2324S2/forum#572]
Under [W10.4] Test Cases: Equivalence Partitioning, 
I think that 
"returns true if m (and int)..."
should be 
"returns true if m (**an~~d~~** int)..."

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/98398940/1eb93942-1eaa-4f8e-b913-955d2f66b9d8)

**Comment by damithc** [comment]
Fixed. Thanks for t he bug report @jyztintan
