### ISSUE TITLE
Example of direct association 

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#574]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/73015364/0a31151c-a9da-4abe-a4ba-b6ec441c75ba)

What is an example of direct association? 
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/73015364/0fd2f9c6-e4c3-4615-b565-89a445d0e2e0)

**Comment by damithc** [comment]
@bgopi23 Can you post a bigger screenshot showing more context?

**Comment by bgopi23** [comment]
@damithc i edited the post to include a bigger screenshot prof

**Comment by damithc** [comment]
@bgopi23 Did you hover over that text to read the tooltip given?

**Comment by baskargopinath** [comment]
@damithc yes prof but im not sure what it means

**Comment by aureliony** [comment]
It refers to the objects that are related to O by association. For example:
```
class A {
    B b;
    void m() { }
}

class B {
    void otherMethod() { }
}
```

In this case, `A::m` can call `b.otherMethod()` without violating the law of demeter.

Another example:
```
class A {
    ArrayList<B> list;
    void m() { }
}

class B {
    void otherMethod() { }
}
```

In this case, `A::m` can call `list.get(index).otherMethod()` without violating the law of demeter.

**Comment by aureliony** [comment]
It refers to the objects that are related to O by association. For example:
```
class A {
    B b;
    void m() { }
}

class B {
    void otherMethod() { }
}
```

In this case, `A::m` can call `b.otherMethod()` without violating the law of demeter.

**Comment by baskargopinath** [comment]
i see thank u @aureliony

**Comment by damithc** [comment]
Good answer @aureliony 💯
