### ISSUE TITLE
What to do if team member is not technically competent enough to implement a feature correctly?

### ISSUE THREAD

**Issue by E0735389** [nus-cs2103-AY2324S2/forum#575]
Suppose the problem is the following:

* a team member takes some task
* sends a pull request
* I point out some bugs in the implementation
* the team member doesn't know how to implement it correctly

What would be the desired course of action in this case?

* reject the pull request
* just merge it, and let another team member fix the bug (problem: in the final report, the new code will be associated to the new team member)
* simplify the feature specification such that the team member can implement it *correctly* (in this case, what if another team member decide to implement the increment in another pull request, which overrides the code authorship?)

**Comment by damithc** [comment]
@E0735389 Your team can decide case-by-case (e.g., ask the author if OK for someone to take over that specific PR and fix the problems), or adopt a general policy for your team (e.g., for important features, someone will take over if not merged by the internal milestone deadline).
At the end, the team can decide which part of the code belongs to which author (there is [a way to override the auto-detected authorship of a line](https://nus-cs2103-ay2324s2.github.io/website/admin/tools.html#tool-reposense-for-authorship-tracking)) and each member can indicate their own view of how much each person contributed to the implementation (when submitting peer evaluations). So, helping each other with the PR is allowed, and even encouraged, and doesn't affect the grading negatively. In fact, it will be mostly a win-win, as those who received help are expected to give high ratings (e.g., for mentorship) to those who helped.
