### ISSUE TITLE
Should we add javadocs to testcases

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#576]
As we add or update testcases, is it recommended to add javadocs for those testcases?
Also if we just update javadoc for testcases that we added or edited does that mean we need to now add javadocs to all the testcases so its not inconsistent?

**Comment by damithc** [comment]
@bgopi23 It's your teams decision. We check code quality in the final submission only. So, you can decide which is the optimum way to update javadocs (or any other code quality related task), by considering costs, benefits, risks etc.

**Comment by baskargopinath** [comment]
understood, thanks prof @damithc
