### ISSUE TITLE
DG scope and layout

### ISSUE THREAD

**Issue by Javiery3889** [nus-cs2103-AY2324S2/forum#577]
Hi, just to clarify the scope of the DG, would it be best to split the DG with regards to each feature implemented by each team member? If so, then the UML diagrams would be used to supplement each feature in the DG?

Also, with regards to the expected length of the DG design details, does the expected length refer to the length of the PDF after exporting?

Thank you!

@AY2324S2-CS2103-F15-1

**Comment by damithc** [comment]
> Hi, just to clarify the scope of the DG, would it be best to split the DG with regards to each feature implemented by each team member? If so, then the UML diagrams would be used to supplement each feature in the DG?

@Javiery3889 The organization of the DG should make sense from the reader POV. So, normally we divide it based on components but it is fine to also have sections explaining design and implementation of significant features.

> Also, with regards to the expected length of the DG design details, does the expected length refer to the length of the PDF after exporting?

The PDF version.

**Comment by Javiery3889** [comment]
Noted with thanks Prof
