### ISSUE TITLE
Query on Level-4 Deadline and Event

### ISSUE THREAD

**Issue by hjuntan** [nus-cs2103-AY2324S2/forum#58]
Do we need to take account of user error during implementation:
i.e. 
`deadline assignment /from today /to never`
or 
`event alone /by 13 Feb`
Would this consider a bug when implementing?

**Comment by damithc** [comment]
@hjuntan no need to handle errors while doing Level-4. Error handling is tackled in Level-5.

**Comment by hjuntan** [comment]
One more question: Are we suppose to support the ability to add Task (the general one) when we implement the todo, deadline and event?

**Comment by damithc** [comment]
@hjuntan No need. That one is the same as Todo.

**Comment by hjuntan** [comment]
Ok, thank you prof!
