### ISSUE TITLE
Logging : Helps and Tips?

### ISSUE THREAD

**Issue by AidenLYT** [nus-cs2103-AY2324S2/forum#580]
<img width="765" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/110450637/7f63c287-3195-4888-b76d-185dd11c59b0">

I have noticed that there is a `Logging` component in the v1.3 iteration. 

Is there a documentation as to how `Logging` works and should be done?

**Comment by yisiox** [comment]
The course materials are [here](https://nus-cs2103-ay2324s2.github.io/website/se-book-adapted/chapters/errorHandling.html#logging).

I find it useful in the context of either parallel code or large code bases where many objects exist simultaneously and code execution is difficult to trace. I can log at the "info" level which objects have been instantiated and which subroutines are running, and if debugging, use the higher severity levels and simply turn off the logging if I don't need them anymore. This is advantageous over printing to standard out, in which case I have to go back and delete or comment out debug print statements.

**Comment by drustanyjt** [comment]
@AidenLYT I find using logging quite liberally to be very helpful. Though it sometimes leads to cluttering the console, it has generally helped me identify the root cause of a problem much more efficiently than without.

**Comment by PallonCX** [comment]
Hi, I agree with @AidenLYT. For me, sometimes I faced a bug and I just want to have a quick peek on what's the value that a variable holding at a certain line of code. In this case, the first thing that comes to my mind is `System.out.println(variable)`.

I find logging to have similar usage, and it can be used in projects to maintain long-term sustainability.
