### ISSUE TITLE
Security issues with outdated jackson libraries in tp

### ISSUE THREAD

**Issue by aureliony** [nus-cs2103-AY2324S2/forum#582]
Would this be considered a bug in the practical exam? Should we update to a newer version of jackson?

![idea64_Q311Dv1Svu](https://github.com/nus-cs2103-AY2324S2/forum/assets/39163684/e3665946-56db-4fe0-bfb5-19edc3425c1a)
![idea64_RyPtFiSu3T](https://github.com/nus-cs2103-AY2324S2/forum/assets/39163684/66809337-3efa-4808-8b8f-7e9e0a5f2fcb)

**Comment by damithc** [comment]
@aureliony It will not be considered a bug, but you are welcome to update it. If you do, I encourage to share your fix with the rest of the class as well.

**Comment by aureliony** [comment]
Just an update, I bumped both versions to `2.17.0` and it's working fine.
