### ISSUE TITLE
Does efficiency matter?

### ISSUE THREAD

**Issue by E0735389** [nus-cs2103-AY2324S2/forum#584]
e.g. if we use an O(n^2) instead of an O(n) method.

Realistically, we won't ever have >1000 entries in the address book anyway.

**Edit**: Actually, the context here is more of a "if our teammates only know how to implement O(n^2), is my mark affected and is their mark affected".

**Comment by yashpola** [comment]
While its true that at the scale of AB3 its meaningless to talk about asymptotic performance, I feel like if O(n) was possible we should go for it? **As long as its readable** then writing more efficient methods now just saves future work when the product does need to be much more scalable.

Even for readability, we can use abstraction to hide the confusing details that tend to crop up with cleverer methods. The user of a search method for example does not need to see that a binary-search is implemented as opposed to be a simple for-loop

**Comment by damithc** [comment]
Good point for discussion. Let me chime in as well ...

If the cost (e.g., implementation effort, maintenance effort, risk of bugs, etc.) is negligible, go for the more efficient option. Usually, the difference is not negligible, and often, higher than one estimates at first.

So, unless the software is performance-critical and needs to be performant/scalable from the start, the suggested approach is:
1. First, make it work (i.e., do the simplest thing that can work)
2. Then, make it right (i.e., test, and fix any bugs)
3. Make it fast, but only if necessary (i.e., if performance is lower than needed, use systematic profiling to find bottlenecks, and fix them)

**Make it work -> make it right -> make it fast** is normally a good guideline for most cases, especially for iterative projects. For example, we don't even know if a certain feature will stay in the product or discarded in a later iteration, which means we should minimize upfront investment on it.


![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/3c3b2aba-ac18-4fef-ba67-e6be423d5b4a)

While on this topic, another related saying:

> Premature optimization is the root of all evil in programming. 

Caveat: The above are not hard rules that you need to follow _every_ time. As always, depends on the context. -- you need to make a judgement call on a case-by-case basis.

--------

> **Edit**: Actually, the context here is more of a "if our teammates only know how to implement O(n^2), is my mark affected and is their mark affected".

In the context of grading, we do not reward/penalize based on the algorithm used. Some related things that could affect your marks:

* performance lower than acceptable under normal load
* low code readability
* bugs in the functionality
* missing delivery deadlines
