### ISSUE TITLE
Java coding convention versus existing convention

### ISSUE THREAD

**Issue by E0735389** [nus-cs2103-AY2324S2/forum#585]
For example, `ArrayList`'s method to get its size is named `size()`, which is not a verb.

If we were to make our own method in our own class, should we follow `ArrayList` for consistency, or should we follow convention and name it `getSize()`?

Of course, for some method like `equals` and `hashCode`, we have no choice. But otherwise?

**Comment by damithc** [comment]
@E0735389 Follow our coding standard as much as possible, unless there is no choice.
