### ISSUE TITLE
How should we deal with optional integers?

### ISSUE THREAD

**Issue by tankh99** [nus-cs2103-AY2324S2/forum#587]
In our application, we have a field that is an optional integer, so it can be null. We initially thought of using an Integer object to represent this field so that it can be nullable, however, passing and storing null values differs from the original implementation as it stores empty strings by default. Is it recommended to follow this format and store the integer as a string in JSON, but parse it as an integer when converting it into an object? Or are both implementations both okay?

**Comment by damithc** [comment]
@tankh99 In case you are asking this from a grading perspective, either option is acceptable, provided the application is working as expected.

**Comment by tankh99** [comment]
> @tankh99 In case you are asking this from a grading perspective, either option is acceptable, provided the application is working as expected.

Indeed, the grading portion was my main concern. Thank you for clarification prof!
