### ISSUE TITLE
Team branching workflow

### ISSUE THREAD

**Issue by delishad21** [nus-cs2103-AY2324S2/forum#588]
Our team is in the midst of adding a very large feature and we would like to work on this feature on a separate branch in totality before merging it to our master branch. 

Our planned workflow is to create a branch (branch_largeFeature) on our upstream repository and work on that branch using the forking workflow (i.e. pulling from this new upstream branch, making our own branches and local commits and making pull requests to said upstream branch) 

When that feature is completed, we will create a PR to merge branch_largeFeature into our master.

Should we proceed in this manner? Will this workflow cause any issues with grading scripts?

**Comment by damithc** [comment]
@delishad21 It is fine to use this workflow (called the _feature branch_ workflow). But keep in mind that the bigger the branch is and the longer it lasts, the more you stray away from breadth-first iterative approach. Try to merge the simplest version of feature to the master branch first, and improve it incrementally using separate PRs. 'add a very large feature' already sounds like not breadth-first iterative.

**Comment by delishad21** [comment]
Alright got it! Thanks Prof
