### ISSUE TITLE
Interfaces in sequence diagrams

### ISSUE THREAD

**Issue by Javiery3889** [nus-cs2103-AY2324S2/forum#589]
Suppose I have a parameter of an interface type, e.g. `Predicate<Person>`, how can we represent such instances of an interface in a sequence diagram? Thanks!

**Comment by damithc** [comment]
@Javiery3889 You can use `Predicate<Person>` as the class name.
Also, not every bit of the code is needed, or suitable, to be represented as sequence diagrams. 
Somewhat related https://github.com/nus-cs2103-AY2324S2/forum/issues/570#issuecomment-2016402106

**Comment by Javiery3889** [comment]
Got it, thanks Prof!

**Comment by Javiery3889** [comment]
Hi Prof @damithc, just wanted to elaborate on my query. For the sequence diagram below, each field in a `Person` class would have its own `Predicate` class, e.g. `NameContainsKeywordPredicate`, that implements `Predicate<Person>`. I am not sure if it would be better to omit the `NameContainsKeywordPredicate()` method call as I want to generalise the sequence diagram for it to be applicable for all `Person` fields. But at the same time, omitting this method call might make it slightly unclear as how the parameter value, `John Doe`, is passed to the predicate.

<img width="828" alt="Screenshot 2024-03-26 at 17 50 35" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/28281451/e5ccc9c8-6d35-4462-ace5-379f9ad75bf3">

Thanks in advance!

**Comment by damithc** [comment]
@Javiery3889 Perhaps you can use a fake name such as `XPredicate` in the diagram and explain in the text what actual values `XPredicate` can be? Would that work?

**Comment by Javiery3889** [comment]
Ah, thanks Prof @damithc for the clarification!
