### ISSUE TITLE
Minor typo in Participation Dashboard page

### ISSUE THREAD

**Issue by Javiery3889** [nus-cs2103-AY2324S2/forum#59]
On the [Participation Dashboard](https://nus-cs2103-ay2324s2.github.io/dashboards/contents/participation.html) page

Instead of,
> Note: The LumiNUS quiz...

It should be,
> Note: The Canvas quiz...

Below is a screenshot for reference:
<img width="1011" alt="Screenshot 2024-01-23 at 16 39 58" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/28281451/37eebbfa-cad1-4182-952a-ba83b9481b5f">

**Comment by damithc** [comment]
Thanks for the report, @Javiery3889 
Fixed.
