### ISSUE TITLE
[ip] For those who did not pass first round of checks

### ISSUE THREAD

**Issue by c-wenlong** [nus-cs2103-AY2324S2/forum#590]
Could I check @damithc, for students who did not pass the first round of peer review for ip, but have rectified their issues and meet the bar now? Would there be a deduction of marks? Thanks!

(for me it was because I had added my JUnit tests to .gitignore so it would be quite a waste to have not achieve the full marks for ip)

**Comment by damithc** [comment]
@c-wenlong No, there won't be any deduction if the problem was rectified eventually.

**Comment by c-wenlong** [comment]
Noted, thanks Prof!
