### ISSUE TITLE
Github Gradle workflow failing

### ISSUE THREAD

**Issue by g-tejas** [nus-cs2103-AY2324S2/forum#591]
Link to build fail: https://github.com/AY2324S2-CS2103T-F14-3/tp/actions/runs/8432575139/job/23092547935?pr=79

![CleanShot 2024-03-26 at 16 19 26@2x](https://github.com/nus-cs2103-AY2324S2/forum/assets/76802638/8ac45bf3-74ad-4826-9973-5fe4cee908ec)

For some reason, my checkStyleTest is fail, and I get the error message above. But there's no Optional import in ParserUtilTest in the first place, as you can see [here](https://github.com/AY2324S2-CS2103T-F14-3/tp/pull/79/files#diff-ea1ddc1697d96e6e91f3ff74631e77043f61f67aab2530c644f399a5695e897f). I've tried re running multiple times, and the gradle checks pass locally. Anyone have any idea why?

Here's the full error, 
![CleanShot 2024-03-26 at 16 21 26@2x](https://github.com/nus-cs2103-AY2324S2/forum/assets/76802638/e0c892c0-7a21-41d1-be38-b05b3f7c37f3)

And how the imports of ParserUtilTest look like
![CleanShot 2024-03-26 at 16 22 02@2x](https://github.com/nus-cs2103-AY2324S2/forum/assets/76802638/9bb226bf-a2a6-4b66-85f3-c035b932c364)

**Comment by dillontkh** [comment]
I think it could be related to #544, where the CI is running based on the current code in your master branch, which does have an `Optional` import in the problematic file.

**Comment by g-tejas** [comment]
Thank you, this was indeed the case. didnt have a up to date master local branch 😭
