### ISSUE TITLE
Duplication of code in the textbook?

### ISSUE THREAD

**Issue by E0735389** [nus-cs2103-AY2324S2/forum#592]
In https://nus-cs2103-ay2324s2.github.io/website/schedule/week10/topics.html#implementation-error-handling-defensive-programming-enforcing-compulsory-associations I notice that the example code has significant code duplication.

```java
class Account {
    private Guarantor guarantor;

    public Account(Guarantor g) {
        if (g == null) {
            stopSystemWithMessage(
                    "multiplicity violated. Null Guarantor");
        }
        guarantor = g;
    }
    public void setGuarantor(Guarantor g) {
        if (g == null) {
            stopSystemWithMessage(
                    "multiplicity violated. Null Guarantor");
        }
        guarantor = g;
    }
    // ...
}
```

Why not just

```java
class Account {
    private Guarantor guarantor;

    public Account(Guarantor g) {
        setGuarantor(g);
    }
    public void setGuarantor(Guarantor g) {
        if (g == null) {
            stopSystemWithMessage(
                    "multiplicity violated. Null Guarantor");
        }
        guarantor = g;
    }
    // ...
}
```

?

**Comment by damithc** [comment]
Good observation @E0735389 
We did consider this before, and decided the one with the code duplication is more effective in visually indicating to textbook readers that an additional check is needed in _both_ creating and mutating.  This may not be obvious (or easily missed) in the second version.

But if this was production code we are likely to unify the duplicated code or use some other more elegant way to confirm the multiplicity is not violated.
