### ISSUE TITLE
Commit messages convention

### ISSUE THREAD

**Issue by jyztintan** [nus-cs2103-AY2324S2/forum#594]
Just wondering, in the context of CS2103, we are told to "Capitalize the first letter of the subject line" as one of the basic rules for commit messages. 

However, I realised that for the additional resource given: https://www.conventionalcommits.org/en/v1.0.0/ which follows 
`<type>[optional scope]: <description>`, the type is specified in lower case. I thought that this additional convention of git commit messages is more organised and succinct. However for the purpose of CS2103, should we not use this convention since it would fail the git commit message convention tracker?

**Comment by damithc** [comment]
@jyztintan If there is a `:` in the commit message, we ignore the part that comes before `:` when checking compliance. So, you _can_ use lower case for the type/scope prefix without being flagged for Git standard non-compliance.

**Comment by jyztintan** [comment]
Thanks Prof!
