### ISSUE TITLE
Seeking clarification for to-do this week

### ISSUE THREAD

**Issue by cheahTJ** [nus-cs2103-AY2324S2/forum#596]
Hi, may I seek some clarification on which file shall we update do this? My impression is that we have to update the `DeveloperGuide.md` file but in the subsequent portion of the description of task, it seems as though we are supposed to do up the UML diagram. Would appreciate it if I could get some clarification on this, thank you!

![Screenshot 2024-03-27 at 4 00 04 PM](https://github.com/nus-cs2103-AY2324S2/forum/assets/122202483/2de57432-7c7e-4aa3-8e39-435e48b28fee)

**Comment by damithc** [comment]
@cheahTJ To update the DG, you need to update `DeveloperGuide.md` _and_ various UML diagrams as well i.e., the DG is built from multiple source files --`DeveloperGuide.md` is the primary source file, but it's not the only one used by the DG.

**Comment by cheahTJ** [comment]
Thank you prof! May I also check the indicator for the above task for the DG is titled `DG Draft` right under the TP Individual Dashboard just to double confirm.

**Comment by damithc** [comment]
> Thank you prof! May I also check the indicator for the above task for the DG is titled `DG Draft` right under the TP Individual Dashboard just to double confirm.

Yes, that's correct @cheahTJ

**Comment by cheahTJ** [comment]
Alright thank you for the clarification prof, will proceed to close this issue now.
