### ISSUE TITLE
Not sure how to fix this

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#597]
it looks like theres an extra white space after the number, does anyone know which class i need to look into to fix this? im unable to figure out where this is

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/73015364/90bdf6cd-0671-4219-9374-e85462a74324)

**Comment by damithc** [comment]
Suggestion: Push the code to a branch and share here so that other can try to replicate/locate the problem.

**Comment by baskargopinath** [comment]
@damithc prof, this problem has been here before making any changes to ab3 as far as i know
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/73015364/3aca81f9-e675-4e2d-aa8d-40888cfc5ce4)

**Comment by damithc** [comment]
> @damithc prof, this problem has been here before making any changes in ab3 as far as i know
> ![image](https://private-user-images.githubusercontent.com/73015364/317275335-3aca81f9-e675-4e2d-aa8d-40888cfc5ce4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NDUzMTQsIm5iZiI6MTcxMTU0NTAxNCwicGF0aCI6Ii83MzAxNTM2NC8zMTcyNzUzMzUtM2FjYTgxZjktZTY3NS00ZTJkLWFhOGQtNDA4ODhjZmM1Y2U0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDEzMTAxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1NTI3NmMzM2VjOGZmNzFmN2E4NWQ5OWI1MTg2OTc3NzUyOGRhZTM2YmY2Njg2ODY3OGE0MDk4YjdjMWE5NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GNE2gp5YmLVdBE-EzEVw84RpatCXN0Yu1_inM_lGXzU)

Ah I see. And you want to make it like `1.John Doe` (i.e., no space between `1.` and `John`)?

**Comment by baskargopinath** [comment]
@damithc prof,
it looks like there is 2 whitespaces currently

`1.  Alex Yeoh`

i want it to be like

`1. Alex Yeoh`

But if this is how it looks when there is 1 whitespace i dont think we can fix it so im wondering if theres 1 or 2 whitespaces

**Comment by raysonchia** [comment]
That whitespace is set by the "spacing" property of the HBox, which you can find in the PersonListCard.fxml file.
It looks like the default spacing is set to 5. Possibly lowering it to 2.5 would suit your preferences.

**Comment by baskargopinath** [comment]
thank u @raysonchia that fixed it

**Comment by baskargopinath** [comment]
https://github.com/AY2324S2-CS2103T-W12-3/tp/issues/151
https://github.com/nus-cs2103-AY2324S2/forum/issues/597#issuecomment-2022739784

@damithc prof are these the intended behavior of original ab3 and if not should i create a pr to the original ab3 to fix it?

**Comment by damithc** [comment]
> @damithc prof are these the intended behavior of original ab3 and if not should i create a pr to the original ab3 to fix it?

@baskargopinath It may have been intended, for cosmetic purposes. But we  can consider changing if the resulting UI looks better  if there is only one space, or if there is a better way to achieve the same outcome.

**Comment by baskargopinath** [comment]
@damithc in my opinion i think it will look better with 1 space, 

the other issue raised [here](https://github.com/AY2324S2-CS2103T-W12-3/tp/issues/151) is misaligned names which is very minute i think this can be fixed as well as it is very unlikely future students will draw a vertical line to identify this bug

**Comment by damithc** [comment]
> @damithc in my opinion i think it will look better with 1 space,
> 
> the other issue raised [here](https://github.com/AY2324S2-CS2103T-W12-3/tp/issues/151) is misaligned names which is very minute i think this can be fixed as well as it is very unlikely future students will draw a vertical line to identify this bug

Sure. Go ahead @baskargopinath
