### ISSUE TITLE
Should a pull request be merged if it is known it has a bug?

### ISSUE THREAD

**Issue by E0735389** [nus-cs2103-AY2324S2/forum#598]
Context: #575.

Suppose the problem is the following:

* a team member takes some task
* sends a pull request
* I point out some bugs in the implementation
* the team member can fix the bug, but will takes a very long time

Is it recommended to **merge the feature anyway, and deal with the bug in a future pull request**?

I think:

* Advantage: Reduce the chance of merge conflict later on.
* Disadvantage: Increases the number of bugs that must be fixed, which would cause problem if not fixed by the strict deadline.
* What if the pull request furthermore fails the tests/makes the tests not compile?

**Comment by damithc** [comment]
@E0735389 In the context of the tP and v1.3, if the bug doesn't affect other members' work and it the PR passes CI, perhaps it is easier for everyone if the PR is merged first. If the bug is not fixed in the final version, only the author will be penalized.
