### ISSUE TITLE
Failing CI on master branch

### ISSUE THREAD

**Issue by delishad21** [nus-cs2103-AY2324S2/forum#599]
Our group merged a pull request that was passing CI. However, after merging it into the master branch, the master branch started to fail CI. We have fixed it with an additional pull request. Is this something that might affect grading?

**Comment by damithc** [comment]
@delishad21 No effect on grading. This kind of thing happens now and then. Kudos for fixing it quickly.

**Comment by delishad21** [comment]
Thanks for the quick reply prof!
