### ISSUE TITLE
typo(schedule): redundant closing bracket

### ISSUE THREAD

**Issue by ForAeons** [nus-cs2103-AY2324S2/forum#6]
# Typo on week 2 schedule page

## Location: 
- schedule/week2/notices-cs2103-fragment.md:57:75

## Expected:
`[bonus participation points](../../admin/participation.md)`

## Actual:
```
[bonus participation points](../../admin/participation.md))
                                                          ^
```

**Comment by damithc** [comment]
Thanks for catching this @ForAeons 
Fixed.
