### ISSUE TITLE
A-TextUiTesting Input Output Redirection

### ISSUE THREAD

**Issue by xiaorui-ui** [nus-cs2103-AY2324S2/forum#60]
Hi all,

I have been stuck on this section for quite a while. I understand that I have to write the expected input and output into their respective txt files. The guide stated we should use input/output redirection. However, I am not sure which folder to test from and what files to feed in(just Duke.java? Or all the .java files in the same folder?) I did not change the folder structure, so Duke is still in `./src/main/java` folder(wrt ip) and the scripts are in `./text-ui-test`. Their lowest common ancestor is the home folder. The app worked perfectly fine in CLI but this happened when I tried input/output redirection:
![Screenshot 2024-01-23 200223](https://github.com/nus-cs2103-AY2324S2/forum/assets/87259515/9211efcd-d902-4c63-89c6-c824d84562e8)
Can someone enlighten me what I am doing wrong? Thanks!

**Comment by Jerome-j** [comment]
Seems like your `Task.java` is not in your directory?

**Comment by xiaorui-ui** [comment]
Ah yes I just had to run `bash script.sh`, everything else was correct. Thanks!
