### ISSUE TITLE
Why shouldn't we merge our own PRs after its been approved by others?

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#602]
I read somewhere that we shouldnt merge our own PRs but not sure what the reason is

**Comment by damithc** [comment]
@bgopi23 What we discourage is to unilaterally merge code to master without getting inputs from other team members, especially for non-trivial changes. Still, it is up to the team to decide who can approve/merge PRs.

**Comment by baskargopinath** [comment]
thank u prof @damithc
