### ISSUE TITLE
Query about PR review comments

### ISSUE THREAD

**Issue by Li-Zizhen** [nus-cs2103-AY2324S2/forum#603]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/122284239/06ee11ae-b55c-4423-91c5-c11c6fbe7f7d)

Are comments for currently open pull requests counted for this part? Moreover, what are considered as comments for pull requests, does it contain general messages or just specific comments on lines? Thank you.

**Comment by damithc** [comment]
@Li-Zizhen 

> Are comments for currently open pull requests counted for this part? 

Yes.

>Moreover, what are considered as comments for pull requests, does it contain general messages or just specific comments on lines?

The latter.

**Comment by Li-Zizhen** [comment]
Thanks.
