### ISSUE TITLE
PE Setting (Remote vs Physical)

### ISSUE THREAD

**Issue by chiralcentre** [nus-cs2103-AY2324S2/forum#604]
Can I check with the teaching team if we are allowed to conduct the PE remotely, as seen in the week 12 instructions? In addition, should the entire team be unanimous in the PE setting (remote/physical), or is it ok for some team members to be onsite and others join remotely?

**Comment by damithc** [comment]
@chiralcentre Yes, you can do the PE remotely. 
And yes, some team members can do the PE remotely while the others do the PE in F2F mode.

**Comment by chiralcentre** [comment]
Thank you Prof for the clarification! To add on, can I check if the PE is open internet, and teammates are allowed to communicate over the web (eg WhatsApp,Telegram)?

**Comment by damithc** [comment]
> Thank you Prof for the clarification! To add on, can I check if the PE is open internet, and teammates are allowed to communicate over the web (eg WhatsApp,Telegram)?

@chiralcentre No, It is done under exam conditions. You are not allowed to communicate with each other. In fact, there is not much use communicating with team members as each member is testing a different product.

**Comment by chiralcentre** [comment]
Noted thanks Prof!
