### ISSUE TITLE
Individual Progress Tracker Issue

### ISSUE THREAD

**Issue by limcaaarl** [nus-cs2103-AY2324S2/forum#605]
Hi prof @damithc,

I was checking my individual progress track and noticed that my progress for UML_Updated went from green to red.
I'm not exactly sure when and how it happened.

For reference, I have exactly [3 lines edited](https://github.com/AY2324S2-CS2103-F09-1/tp/commit/59461ce10088dee2c3b9ce00bc086b9ca0de70fe).

**Comment by damithc** [comment]
@lokidoki102 This increment is based on the code dashboard. Check if those lines are still attributed to you in the code dashboard. It's possible that those lines were removed subsequently or someone else took over them after you edited them.

**Comment by baskargopinath** [comment]
@damithc prof is our code contributions checked only based on the code dashboard, because some of my code was moved by my teammate to another class and was no longer attributed to me

**Comment by damithc** [comment]
> @damithc prof is our code contributions checked only based on the code dashboard, because some of my code was moved by my teammate to another class and was no longer attributed to me

@bgopi23 yes code authorship is detected based on the code dashboard. There is a way to override the code authorship auto-detected by the code dashboard, using `@@author` tags. See https://nus-cs2103-ay2324s2.github.io/website/admin/tools.html#tool-reposense-for-authorship-tracking

**Comment by baskargopinath** [comment]
thanks prof @damithc

**Comment by limcaaarl** [comment]
> @lokidoki102 This increment is based on the code dashboard. Check if those lines are still attributed to you in the code dashboard. It's possible that those lines were removed subsequently or someone else took over them after you edited them.

This seems to be the case. Thanks prof @damithc!
