### ISSUE TITLE
OO Design for classes which refer to each other

### ISSUE THREAD

**Issue by tzyian** [nus-cs2103-AY2324S2/forum#606]
For our tp, we have `Order` and `Person`. Each `Person` has a `List<Order>`. However, `Order` class does not hold any `Person` object identifier, meaning that you can't go from `Order` to `Person`. 

In the GUI, we need to display both the `Order` and the `Person` it belongs to. 

Was wondering what's the best way to do this?

- Use circular references `:Person` -> `:Order` and `:Person` -> `:Order` by having a `Order::setPerson` method
- Pass `Pair<Person, Order>` instance around

**Comment by dillontkh** [comment]
If I'm understanding the question right, it seems you want bidirectional navigability between `Order` and `Person` objects.

Maybe a `private final Person` field in your `Order` class? Assuming the `Person` the `Order` is associated with doesn't change. Then you could pass the `Person` as an argument to the `Order`'s constructor.

**Comment by tzyian** [comment]
You're right, the `private final Person` makes more sense. Thanks.
