### ISSUE TITLE
Week 10 Topics: Video has quiz but is not labelled as so

### ISSUE THREAD

**Issue by billyhoce** [nus-cs2103-AY2324S2/forum#608]
In Week 10 topics: Quality Assurance → Test Case Design → Equivalence Partitions → What

The video on equivalence partitions contain a quiz, but it is not labelled as such on the header. Not sure if intended.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/84035425/65f7ccf2-107a-49a5-a772-ec6241a7c271)

**Comment by damithc** [comment]
@billyhoce Thanks for raising this. Yes, it was intended. Although that video has questions, we don't count this video when checking for in-video quiz participation (reason: to reduce the videos students need to watch to qualify for in-video participation)
