### ISSUE TITLE
Tutorial Video Bug

### ISSUE THREAD

**Issue by Ko-Khan** [nus-cs2103-AY2324S2/forum#609]
I am unsure if this was intended, but the in video quiz for Example 4 in week 10 tutorial  did not show up for me.

**Comment by damithc** [comment]
@Ko-Khan Thanks for raising this. It's intended. Only _some_ exercises have in-video questions attached to them. Ex4 doesn't have a question.

**Comment by Ko-Khan** [comment]
Thank you for the clarification!
