### ISSUE TITLE
"This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository."

### ISSUE THREAD

**Issue by bgopi23** [nus-cs2103-AY2324S2/forum#61]
when checking my commit on github everything looks fine but i see this warning

"This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository."

why is this happening?

**Comment by TiwKangXu** [comment]
Hi @bgopi23 , I'm from previous batch (dropping by in this forum to see if I can help with tech problems). Would you mind attaching a screenshot with the warning for better clarification?

**Comment by bgopi23** [comment]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/73015364/e05eccd4-7db6-464d-ba1a-c0a04b8f1e41)
@TiwKangXu

**Comment by lhy-hoyin** [comment]
@bgopi23 Would you be able to provide some more information? 

For example, 
- Which commit is it referring to? (Possible to provide link to it here? If your iP repo is public)
- Is this the only commit with this warning? How about your other commits? Do they have the same warning too?
- Which page on GitHub (eg. Code, Issues, Pull Requests, Actions, etc) is showing the warning?
- Perhaps expand the screenshot so we can better tell the context of the warning?

Also, for the commit which shows this warning, have you pushed the branch for that commit to GitHub?
You can try out the solution given in this [link](https://stackoverflow.com/questions/30658884/git-push-a-commit-that-doesnt-belong-to-any-branch).

**Comment by damithc** [comment]
> why is this happening?

@bgopi23 the most common cause of this error (given out by GitHub) is pushing a tag to your remote repo without pushing the corresponding commit. The remedy is to push the commit.

**Comment by bgopi23** [comment]
@lhy-hoyin it gives this same warning for all the commits
@damithc prof i am pushing the tag together with the commit

**Comment by billyhoce** [comment]
@bgopi23 I encountered a similar issue hence ended up in this post, these are my personal findings

1) For Level-0, upon completing my requirements and staging my changes, I did the following:
`git push`
`git push --tags`
This resulted in normal behaviour without the error message.

2) For Level-1,  upon completing my requirements and staging my changes, I did the following:
`git push --tags`
This resulted me in getting the same error as you did (Sorry forgot to screenshot)
Then, as suggested by prof @damithc, I did
`git push`
Which fixed the problem upon refreshing my github page

I suspect that you, like me, are doing `git push --tags`, thinking that this pushes both commits and tags but in reality it only pushes tags. Even though you can see the changes in the code from the tag, I think (correct me if I'm wrong) that its not how version control is meant to be done. From what you have described, it sounds like you have already done multiple "Levels" this way and I'm not sure how you can resolve it from there.

Maybe you can do the following (Someone else please advise if this is okay):
1. Delete all your tags on github and local repo
2. Do `git push` to push all your commits for the levels you have done
3. Tag all the levels you have done (on local repo)
4. Do `git push --tags` to push all the tags

I came up with this suggestion based on this FAQ on the website
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/84035425/359d4965-00ed-4f52-a121-b8cdbbcc2c2b)

Hope I helped, thanks!

**Comment by E0735389** [comment]
> it gives this same warning for all the commits

If I go to one of your commits https://github.com/bgopi23/ip/commit/ed097c1aab108c8f1e686d7f88bac6d8435f9497 , I don't see any warning. Neither does visiting any commit in your tags page https://github.com/bgopi23/ip/tags .

So either your statement is false, or the only possibility left is that somehow the warning isn't displayed on my machine, but it is displayed on your machine.

In the latter case, try visiting the site with a different device or a different browser.

**Comment by bgopi23** [comment]
https://github.com/nus-cs2103-AY2324S2/ip/commit/d251f090ec092d0fe4aa8353b02c8a10bd2ccbb4
@damithc

**Comment by bgopi23** [comment]
everyone i check has this issue so it might not be an issue

**Comment by E0735389** [comment]
Well, look at the URL:

https​://github.com/**nus-cs2103-AY2324S2**/ip/commit/d251f090ec092d0fe4aa8353b02c8a10bd2ccbb4

of course that commit doesn't belong to that (`nus-cs2103-AY2324S2`) repository, it belongs to your fork of the repository — that is, exactly what the warning message says.

Just visit https://github.com/bgopi23/ip/commit/d251f090ec092d0fe4aa8353b02c8a10bd2ccbb4 instead.

The question remains how would you ever come across that URL apart from typing it in the address bar manually.

**Comment by damithc** [comment]
> The question remains how would you ever come across that URL apart from typing it in the address bar manually.

This is indeed a good question. @bgopi23 where did you encounter the link to the page https://github.com/nus-cs2103-AY2324S2/ip/commit/d251f090ec092d0fe4aa8353b02c8a10bd2ccbb4 which shows the error message ?

**Comment by bgopi23** [comment]
@E0735389 makes sense
@damithc this is how i came across the url

<img width="507" alt="Screenshot 2024-01-24 at 2 30 25 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/73015364/b489ce2b-5fda-4189-be4d-979c8df4e9cf">


first i clicked this ^  (which i saw on my ip repository)

<img width="333" alt="Screenshot 2024-01-24 at 2 31 41 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/73015364/66d37e1a-dc3b-418c-a8d8-14dd4a7bf6c9">

then i clicked these ^ and saw the warning

**Comment by damithc** [comment]
> @damithc this is how i came across the url
> 
> <img alt="Screenshot 2024-01-24 at 2 30 25 PM" width="507" src="https://private-user-images.githubusercontent.com/73015364/299206526-b489ce2b-5fda-4189-be4d-979c8df4e9cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwODQ0OTIsIm5iZiI6MTcwNjA4NDE5MiwicGF0aCI6Ii83MzAxNTM2NC8yOTkyMDY1MjYtYjQ4OWNlMmItNWZkYS00MTg5LWJlNGQtOTc5YzhkZjRlOWNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDA4MTYzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5N2YzYTAxZTVlZjUxZmM1NDcwNDMyZjkzZjVkZTk4M2I5ZWNhNzRlZjA3YjY1NGYyYjg3Y2IwMDIwZjMzODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hpTJMTAtWSX8EZnn9F2T5LiIuPK_eQdNsiiKLL8r1wQ">
> first i clicked this ^ (which i saw on my ip repository)

@bgopi23 I see. In those pages GitHub is simply telling us that the commit in concern does not belong to the repo it is being compared to, which is the truth. So, we can ignore that warning.

On a side note, this discussion shows the importance of contextual information when troubleshooting -- e.g., the same error message can mean different things based on where it appears, steps you took to get there, etc.

**Comment by bgopi23** [comment]
thank you prof @damithc
