### ISSUE TITLE
Is GitHub commit messages subject to the checks as well?

### ISSUE THREAD

**Issue by UdhayaShan1** [nus-cs2103-AY2324S2/forum#610]
Noticed, some Github commits have very long subject line, is this subject to checks as well.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39399745/2b03dd25-1aba-4233-b0e3-e1e06069e1ff)

**Comment by damithc** [comment]
@UdhayaShan1 Yes. So, if GitHub doesn't give you a way to edit the commit message, commit locally instead.
However, we don't check for length of commit messages GitHub generates when merging a PR.

**Comment by UdhayaShan1** [comment]
Thanks!

**Comment by E0735389** [comment]
As far as I can remember, GitHub does give you a way to edit the commit message.

Nevertheless, there's a special case: automatically-generated merge commit message are not graded: #547
