### ISSUE TITLE
[Bug] Deadlink for resources in service-oriented style W11.2f

### ISSUE THREAD

**Issue by camille-readbean** [nus-cs2103-AY2324S2/forum#611]
https://nus-cs2103-ay2324s2.github.io/website/schedule/week11/topics.html#design-architecture-styles-service-oriented-style-what > resources

https://www.devteam.space/blog/microservices-vs-soa-and-api-comparison// is a 404 link  
  
https://www.devteam.space/blog/microservices-vs-soa-comparison/  
I found this link by the same writer

**Comment by damithc** [comment]
Fixed as suggested. Thanks @camille-readbean
