### ISSUE TITLE
Smoke testing catcher not updated in TP dashboard

### ISSUE THREAD

**Issue by chiralcentre** [nus-cs2103-AY2324S2/forum#612]
Can I check if there are any special steps to take for smoke testing CATcher app apart from creating a dummy issue in the app? I have created dummy issues in the app accordingly, but it is not reflected as completed on the TP progress dashboard.

**Comment by damithc** [comment]
@chiralcentre Did you submit the dummy bug report using CATcher UI, or created an issue by hand in your alpha repo issue tracker? It needs to be the former.

**Comment by chiralcentre** [comment]
Oh I believe I created the dummy bug report by hand in the repo, but I edited it in the CATcher UI. Can I check if my participation will be affected for this? I have created a new dummy bug report in the CATcher UI immediately.

**Comment by jmsandiegoo** [comment]
@chiralcentre You can try adding at least one image in one of your issues. That solved a similar problem I faced.

**Comment by damithc** [comment]
> Can I check if my participation will be affected for this?

@chiralcentre You can check the participation dashboard to see if your W10 is green.  If green, it's all good.

**Comment by chiralcentre** [comment]
Hi Prof I checked the dashboard and it appears the CATcher is not reflected as completed; however, I note that the dashboard was updated on a weekly basis. I will check again next week.
