### ISSUE TITLE
tP Grading for contributions to tP repo before 23 Feb

### ISSUE THREAD

**Issue by Dethada** [nus-cs2103-AY2324S2/forum#613]
I've made contributions to our tp repo before 23 Feb, and it's not tracked on the tp code dashboard, will those contributions be considered during tp grading?

**Comment by damithc** [comment]
@Dethada Normally, we consider only the work done during the tP coding period. But you can use `@@author` tags to claim authorship of additional code segment, as given [here](https://nus-cs2103-ay2324s2.github.io/website/admin/tools.html#tool-reposense-for-authorship-tracking).

**Comment by Dethada** [comment]
Okay, thanks prof
