### ISSUE TITLE
Changing UI in 1.4

### ISSUE THREAD

**Issue by delishad21** [nus-cs2103-AY2324S2/forum#614]
Under the details for 1.4 feature freeze, it is mentioned that no UI enhancements are allowed. But are we allowed to make changes to fix bugs such as text getting cut off due to misalignment or lack of space?

**Comment by damithc** [comment]
@delishad21 only if there is no other way for the user to see the text that has been cut off. If the user can see that text be resizing or using some other feature, the change will not be allowed.
