### ISSUE TITLE
Request to use opencsv library to read csv files

### ISSUE THREAD

**Issue by Pughal77** [nus-cs2103-AY2324S2/forum#615]
## Library

[opencsv](https://opencsv.sourceforge.net)

## Purpose

Our group intends to use it for reading from csv files so as to support importing of contacts from csv files to the addressBook

## License

It is released under the Apache 2 license, that can be seen [here](https://opencsv.sourceforge.net/licenses.html)

**Comment by damithc** [comment]
Approved.
