### ISSUE TITLE
Confusing timeline: When is the PE?

### ISSUE THREAD

**Issue by Jerome-j** [nus-cs2103-AY2324S2/forum#616]
Hi, based on Week 12 tasks, it states that we will have to choose between a physical or virtual PE before 16 April: https://nus-cs2103-ay2324s2.github.io/website/schedule/week12/admin.html.

But Week 13 page seems to indicate that the PE will be held on 12 April https://nus-cs2103-ay2324s2.github.io/website/schedule/week13/admin.html (PSL trying is misspelled as "tyring")

I appreciate clarification on the PE date please.

Thank you.

**Comment by damithc** [comment]
@Jerome-j PE date is given in https://nus-cs2103-ay2324s2.github.io/website/schedule/week13/project.html and in https://nus-cs2103-ay2324s2.github.io/website/schedule/week13/index.html

12th April (mentioned in https://nus-cs2103-ay2324s2.github.io/website/schedule/week13/admin.html) is the starting day of week 13, not the PE date. That page doesn't have any info on the PE (as in the Practical Exam).

Thanks for reporting the typo. Will fix.
