### ISSUE TITLE
Feature Freeze clarification

### ISSUE THREAD

**Issue by Ko-Khan** [nus-cs2103-AY2324S2/forum#617]
During the feature freeze, are we allowed to rewrite our code to improve readability so long as we don't add any new features. Are we also allowed to write test cases to improve coverage?

**Comment by damithc** [comment]
@Ko-Khan Yes. More info [here](https://nus-cs2103-ay2324s2.github.io/website/schedule/week12/project.html#:~:text=Allowed%20in%20the%20v1.4%20milestone%3A)

**Comment by guohuang88** [comment]
Are we allowed to add more UML diagrams in v1.4?

**Comment by damithc** [comment]
@guohuang88 Yes, that counts under [✔️ improving documentation](https://nus-cs2103-ay2324s2.github.io/website/schedule/week12/project.html#:~:text=improving%20documentation), which is allowed in v1.4.

**Comment by guohuang88** [comment]
@damithc okay thanks prof!

**Comment by Ko-Khan** [comment]
Sorry for the late closing
