### ISSUE TITLE
Validation when reading from JSON

### ISSUE THREAD

**Issue by chiralcentre** [nus-cs2103-AY2324S2/forum#618]
Can I check with the teaching team if we are expected to implement data validation for data read in from a JSON file, and will failure to do so be considered as a bug? For example, if I do not allow for two different Person to have the same email, am I expected to check for this when reading the data from the JSON file, or can I assume that the data input won't have this error?

**Comment by damithc** [comment]
@chiralcentre Depends on how the wrong data got into the file. 
If it was a due to a manual edit to the file, the following applies:
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/960d8e18-a97e-45d8-84cd-ef7947852be8)

If the error was caused by data entered by the user through the UI, it is the responsibility of the app to prevent/handle such errors.

**Comment by chiralcentre** [comment]
Thank you Prof for the response. Sorry to trouble you again, but are you referring to this section?
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/83827461/b0ae7569-3c14-4ba4-952e-7b77874cfc77)

**Comment by damithc** [comment]
> Thank you Prof for the response. Sorry to trouble you again, but are you referring to this section?
> ![image](https://private-user-images.githubusercontent.com/83827461/318278278-b0ae7569-3c14-4ba4-952e-7b77874cfc77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4OTY2ODgsIm5iZiI6MTcxMTg5NjM4OCwicGF0aCI6Ii84MzgyNzQ2MS8zMTgyNzgyNzgtYjBhZTc1NjktM2MxNC00YmE0LTk1MmUtN2I3Nzg3NGNmYzc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDE0NDYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3MTY4ZDg3MmZmY2JiOGNhM2QwODU4YzM2ZjNiODFkMDE0NmE3Y2EzZDlhNWMzNzUwZDgxM2RkN2Y5Yjk4YTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UYeK6iDS92UgtJbQ_UWB6HdckdWINXF74yHS867L-OU)

@chiralcentre, yes, more precisely the original AB3 version of this section.

**Comment by chiralcentre** [comment]
Noted thank you!
