### ISSUE TITLE
[IP] case sensitivity

### ISSUE THREAD

**Issue by bgopi23** [nus-cs2103-AY2324S2/forum#62]
do we have to account for case sensitive inputs?
for example:
if only "list" triggers the chatbot to bring up the list is it an issue?

**Comment by Jerome-j** [comment]
I hope that it is not case sensitive, since the project did not specify.

If a mixture of upper and lower case is allowed, then we might have to account for cases like `liST`?

**Comment by bgopi23** [comment]
> I hope that it is not case sensitive, since the project did not specify.
thats what im not sure abt

**Comment by damithc** [comment]
@bgopi23 When a behavior/aspect is not specified by us, we expect you to decide yourself i.e., you can consider the options and decide which is the best choice, factoring in things like implementation effort, impact on user experience.

**Comment by E0735389** [comment]
Given that most UNIX-related tools (bash shell) and popular programming languages (C++, Java, Python) are case-sensitive, requiring case sensitivity appears to be a reasonable option in my opinion.

**Comment by itstrueitstrueitsrealitsreal** [comment]
It depends on the user experience you want the user to have, for e.g if you feel making commands case insensitive provides a more seamless experience for users, you can go ahead with that approach.

Other examples I can think of are commands with /from and /to and /by for events and deadlines respectively being useful for users to know if they are explicitly specifying a deadline or event duration, but others may feel that it is obstructive and not very convenient for the user.

Hope I helped!

**Comment by bgopi23** [comment]
@damithc prof, i wanted to finish the requirements first and if i have extra time after that i would do stuff that makes it more user-friendly so was wondering if we would be penalised for stuff like making the inputs case sensitive which is not that user friendly.

**Comment by damithc** [comment]
> @damithc prof, i wanted to finish the requirements first and if i have extra time after that i would do stuff that makes it more user-friendly so was wondering if we would be penalised for stuff like making the inputs case sensitive which is not that user friendly.

@bgopi23 It is fine (in fact, recommended) to meet the minimum requirement first, and improve further later, if you have time. The tag can remain where you added it first, as it is simply a self declaration of progress -- we do not grade the iP at every tag.

**Comment by bgopi23** [comment]
understood prof thank you @damithc
