### ISSUE TITLE
W11.4b possible typo

### ISSUE THREAD

**Issue by UdhayaShan1** [nus-cs2103-AY2324S2/forum#620]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39399745/1524dd4f-4f08-4f3b-a136-a5667c8d7408)

If f is correct, and it 'is more likely to be a verification failure' then the explanation should be likely to be not meeting the requirements instead.

**Comment by damithc** [comment]
@UdhayaShan1 Are you referring to the last sentence in the requirements? It's meant to say 'A system crash is more likely to be a bug in the code (i.e., a verification failure), not a bug in the requirements (i.e., a validation failure)'

Does that clarify your doubt?

**Comment by UdhayaShan1** [comment]
My bad, got confused with the phrasing between 'correct requirements' and 'implemented correctly', thank you!
