### ISSUE TITLE
Does effort to write tests etc. count?

### ISSUE THREAD

**Issue by E0735389** [nus-cs2103-AY2324S2/forum#622]
In the website/textbook, it's written

> The expected level of functionality is what you could achieve if each member puts in an **implementation effort** equivalent to half of the implementation effort they put into the iP (i.e., it is set at half because, even after adding the extra overheads of doing the project as a team, and working with an exising codebase, we don't want the total tP effort of a student to exceed the total effort of iP -- in other words, we don't want the tP to take more effort than the iP).
Furthermore, we estimate that the above-mentioned bar will equate to about 300-400 lines of **functional code** (excluding testing and documentation) per person.

Does effort to write testing count? (e.g. if some team member writes little functional code but do a lot of testing)

Similar question for other "useless" tasks such as reviewing others' pull requests, update documentation, testing the app manually, etc.

**Comment by damithc** [comment]
> Does effort to write testing count? (e.g. if some team member writes little functional code but do a lot of testing)

@E0735389 This is just a rough benchmark for _you_ to gauge how much work to do. You can do less of one thing and more of something else, while still matching the equivalent of the expected effort.

> Similar question for other "useless" tasks such as reviewing others' pull requests, update documentation, testing the app manually, etc.

For one thing, they are as much, if not more, useful than writing code. 

Other than that, my reply above applies here as well.

**Comment by E0735389** [comment]
Conversely, if one writes ≥ 300 functional lines of code but does not write any test code, does that count negatively?

(Assume there's enough manual testing at the end to iron out any bug)

**Comment by damithc** [comment]
@E0735389 Everyone is expected to write _some_ automated tests.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/476b7ae7-2c59-460c-938e-82887055f07a)
