### ISSUE TITLE
Why is feature branch workflow considered lighter than forking workflow?

### ISSUE THREAD

**Issue by E0735389** [nus-cs2103-AY2324S2/forum#623]
From https://nus-cs2103-ay2324s2.github.io/website/admin/tp-w10.html :

> Switch to a lighter workflow:
> 
> While forking workflow is the safest (and is recommended), it is also rather heavy. You may switch to a simpler workflow if you wish. Refer the textbook to find more about [alternative workflows](https://nus-cs2103-ay2324s2.github.io/website/se-book-adapted/chapters/revisionControl.html):
The feature branches workflow: a reasonable alternative, but if you choose this, make sure your master branch is protected and most members have write access only (i.e., no admin access)
The centralized workflow: discouraged.
Even if you do switch, we still recommend that you use PR reviews, at least for PRs affecting others' features.

Why is it that feature branch workflow is considered lighter? I feel they're both the same: you create a new branch, you send a pull request, the pull request is reviewed.

Or is the textbook assuming that (minor) pull requests are no longer reviewed?

**Comment by damithc** [comment]
@E0735389 

It's considered lighter because you don't have to maintain a fork at all. 
There is no change in the requirement for PR reviews. PRs should be reviewed as you did before.

But yes, it is only _slightly_ lighter.
