### ISSUE TITLE
What to look out for dry run 

### ISSUE THREAD

**Issue by cheahTJ** [nus-cs2103-AY2324S2/forum#624]
Hi, I would like to check what areas should we focus on to catch for the team we are going to review for the dry run for PE?

**Comment by damithc** [comment]
@cheahTJ Report bugs in the UG and the product.
Also see <a href="https://nus-cs2103-ay2324s2.github.io/website/admin/tp-ped.html#:~:text=team%20to%20test.-,b)%20What%20to%20test,-PE%20Dry%20Run)">PE-D -> b) What to test</a>
Does the above answer your question?

**Comment by camille-readbean** [comment]
Hi prof, similar but do we have to care about index.md, developerguide, and any other pages?

**Comment by damithc** [comment]
@camille-readbean The scope of the PE-D is the JAR and the UG (pdf) only. In the PE, DG (pdf) is added to the scope.

**Comment by cheahTJ** [comment]
> @cheahTJ Report bugs in the UG and the product. Also see [PE-D -> b) What to test](https://nus-cs2103-ay2324s2.github.io/website/admin/tp-ped.html#:~:text=team%20to%20test.-,b)%20What%20to%20test,-PE%20Dry%20Run)) Does the above answer your question?

Yup thank you prof!
