### ISSUE TITLE
isEarlyAccess True for prepping 1.3 release

### ISSUE THREAD

**Issue by camille-readbean** [nus-cs2103-AY2324S2/forum#628]
Do we leave isEarlyAccess as true?

https://nus-cs2103-ay2324s2.github.io/tp/DevOps.html#making-a-release

https://nus-cs2103-ay2324s2.github.io/website/schedule/week11/project.html#3-release-v1-3-thu-apr-4th-23-59

Say we make a v1.3.1, is the one tested v1.3 or v1.3.1?

**Comment by damithc** [comment]
@camille-readbean We take the latest one, irrespective of the label or the version number. But remember not to leave it in draft mode, as doing so will make it hidden from others.
