### ISSUE TITLE
Minor typo in the textbook

### ISSUE THREAD

**Issue by E0735389** [nus-cs2103-AY2324S2/forum#631]
This `I` should be lowercase.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/97508964/96ff79c8-4130-4ece-8de7-b650a36405b5)

This is another one, the `:` after `PDF format` should be `.` I think.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/97508964/52d956d2-848d-4804-9a00-edddea30f4e6)

Also I don't think there should be a space here. (highlighted)

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/97508964/e4203ee8-8509-413c-8908-418eb5a8bd19)

There should only be two `o` here, if I recalled correctly.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/97508964/c6aa6679-3a90-44a4-bc18-57aa1eeef228)

Extraneous space before the comma.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/97508964/054528fb-8ba2-46d8-9467-2b7ff0dd881f)

**Comment by damithc** [comment]
@E0735389 Thanks for reporting these. 
All fixed, except for the extra space in front of `duplicate-flagging`. That one is caused by a bug in the MarkBind tooltip generation, and the MarkBind team is working on a fix.
