### ISSUE TITLE
Clarification in effort requirement

### ISSUE THREAD

**Issue by E0735389** [nus-cs2103-AY2324S2/forum#632]
The textbook has the following.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/97508964/00af5534-15cd-4d95-9127-eebf3c9ad132)

Just to clarify: 

> We expect most typical teams to score near to 5.

> Baseline: If your team received a value higher than 10 in step 1 and the team agrees that you did roughly an equal share of implementation work, you should receive full marks for effort.

This means that the estimation is that only about less than half of the class will get full mark of effort? (Assume the baseline means you need ≥ 2 points to get full mark for effort, and in a 5-scored team there is at most 2 members with full mark)

**Comment by damithc** [comment]
@E0735389 thanks for raising this. It should be `5`, not `10` (it used to be `10` in the previous semester but seems I forgot to change it here). Fixed. The updated version should be online within the next few minutes.
