### ISSUE TITLE
What does "assignee" mean in "The penalty for a bug is divided equally among assignees"?

### ISSUE THREAD

**Issue by E0735389** [nus-cs2103-AY2324S2/forum#633]
Textbook:

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/97508964/eebe0711-192f-4ed6-af7b-84ee76c7f98e)

Because it's talking about the **penalty**, I think the only reasonable interpretation is that the author of the line of code. But I thought each line of code has only one author?

**Comment by damithc** [comment]
@E0735389 In the PE, after the team is notified of the bug reported for their product, the team is able to assign members to each bug report, to indicate who takes the responsibility for that bug.

**Comment by E0735389** [comment]
So it's entirely up to us to decide who is responsible for the bug?

So for example if the bug is inherited from AB3 and nobody notices it, I suppose it would be fair to make each person take 1/5 of the penalty?

**Comment by damithc** [comment]
> So it's entirely up to us to decide who is responsible for the bug?
> 
> So for example if the bug is inherited from AB3 and nobody notices it, I suppose it would be fair to make each person take 1/5 of the penalty?

Yes and yes :-)
