### ISSUE TITLE
tP code dashboard: confusing coloring of line number

### ISSUE THREAD

**Issue by E0735389** [nus-cs2103-AY2324S2/forum#634]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/97508964/71eb927e-8e24-4664-9c9d-7403ffcbf4ba)

In this image (taken from tP code dashboard), apparently it means that in this file there are 10 lines owned by this user, where 8 lines are not blank.

Apparently, this has nothing to do with the **color** of the line numbers. I'd have thought that the lines with blue line number are those that is "significant" and "counts" toward the number in the bracket, but no, it's just an artifact because the comment is also in gray color.

**Comment by damithc** [comment]
@E0735389 There seems to be some issue with the syntax coloring library -- line numbers were not supposed to have different colors). Authorship is indicated by the background color green. The color of the line numbers doesn't matter.

**Comment by E0735389** [comment]
Looks like prof forwarded the issue to the RepoSense GitHub repository. Consider the issue solved then.
