### ISSUE TITLE
"Functional line of code" effort requirement 

### ISSUE THREAD

**Issue by E0735389** [nus-cs2103-AY2324S2/forum#635]
The textbook contains:

> Furthermore, we estimate that the above-mentioned bar will equate to about 300-400 lines of functional code (excluding testing and documentation) per person.

Nevertheless, in the tP code dashboard...

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/97508964/36bce0c4-4503-4482-844b-2467a81fd258)

The line counter includes the Javadoc lines too.

So, is the estimation above with respect to what the tP code dashboard count as "functional code", or does it exclude comments?

**Comment by damithc** [comment]
@E0735389 `300-400 lines of functional code` can include a reasonable amount of code comments.
