### ISSUE TITLE
Trouble writing unit cases when clipboard is involved

### ISSUE THREAD

**Issue by RunjiaChen** [nus-cs2103-AY2324S2/forum#636]
<img width="1158" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/142142406/ec5e7622-ec59-4dac-a1b9-dab7d2d877c4">

<img width="666" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/142142406/0cf5ee1f-65e2-449d-b799-b1939d24b9f0">
Hello, I am trying to write a unit test which tests the copying of a command to the clipboard. However, it returns this error message. I suspect that its due to the clipboard library, but I am unsure of how to circumvent this issue. Any help will be appreciated.

**Comment by damithc** [comment]
@RunjiaChen recommended: Push the code to a branch and share here so that other can try to replicate the problem.
