### ISSUE TITLE
FXML not maximising properly

### ISSUE THREAD

**Issue by RunjiaChen** [nus-cs2103-AY2324S2/forum#637]
Hello, I am implementing a feature that involves a pop window for AB3. However, When I maximise the pop window, the placement of all the box fall out of alignment. May I know if there is a way to fix this? 
<img width="1619" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/142142406/8fd19fe1-3c01-48eb-ad9e-2bdbef58bb75">
Also, are these visual defects considered bugs in the PE?

**Comment by damithc** [comment]
> Also, are these visual defects considered bugs in the PE?

@RunjiaChen Yes, as this is not a behavior a user would expect to see in a GUI.

**Comment by oeggy03** [comment]
Hi, I think you can try seeing if you have VGROW/ HGROW set properly? (If you are using any VBox/HBox here) Also I think it may depend on the root pane you are using: I think I've seen people encounter problems with Anchorpane before. 

You can try playing around with the different settings too if that helps. But I think its a bit hard to determine right now without knowing the exact components used

**Comment by lhy-hoyin** [comment]
To add on, you may also want to check out / read up on relative vs absolute position.

In your case, you would definitely want your UI elements to be relative to one another / pop up's corners.

---

Not too sure if this would be useful for you, but I thought I would leave it here.

https://docs.oracle.com/javafx/2/layout/size_align.htm

**Comment by hansstanley** [comment]
Hi, it's possible to anchor the elements to the AnchorPane as shown, by applying `AnchorPane.[top/left/bottom/right]Anchor` on the children of the AnchorPane.

<img width="912" alt="Screenshot 2024-04-03 at 00 31 41" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/20805849/87d61ad4-4ba0-4f10-9558-42f026e72852">

Afaik, I don't think AnchorPane can resize its children relative to each other. For that, you could consider a combination of VBox and HBox like the following:

```fxml
<AnchorPane prefHeight="600.0" prefWidth="400.0"
            xmlns="http://javafx.com/javafx/17" xmlns:fx="http://javafx.com/fxml/1"
            fx:controller="seedu.address.ui.CommandHelperWindow">
    <VBox AnchorPane.topAnchor="0" AnchorPane.leftAnchor="0" AnchorPane.bottomAnchor="0" AnchorPane.rightAnchor="0">
        <ScrollPane fx:id="scrollPane" hbarPolicy="NEVER" hvalue="1.0" vvalue="1.0"
                    VBox.vgrow="ALWAYS">
            <VBox fx:id="dialogContainer"/>
        </ScrollPane>
        <HBox VBox.vgrow="NEVER">
            <TextField fx:id="userInput" onAction="#handleUserInput" HBox.hgrow="ALWAYS" prefHeight="41.0"/>
            <Button fx:id="sendButton" mnemonicParsing="false" onAction="#handleUserInput"
                    prefWidth="76.0" prefHeight="41.0" text="Send" HBox.hgrow="NEVER"/>
        </HBox>
    </VBox>
</AnchorPane>
```

<img width="952" alt="Screenshot 2024-04-03 at 00 45 53" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/20805849/f5f24306-bd53-4b3c-a53a-6f76238f653b">

Hope this helps!

**Comment by SPWwj** [comment]
Hi @RunjiaChen, I'm a senior from a previous batch. @hansstanley provided a great solution to this issue. However, I'd like to refine the layout that you could use:

fillWidth="true" for VBox: This ensures that the VBox and its children, like the ScrollPane and HBox, will attempt to fill the width of the AnchorPane.
fitToWidth="true" for ScrollPane: This ensures that the ScrollPane's content will be sized to fit the width of the ScrollPane.

Full code:
```
<?xml version="1.0" encoding="UTF-8"?>
<?import javafx.scene.control.Button?>
<?import javafx.scene.control.ScrollPane?>
<?import javafx.scene.control.TextField?>
<?import javafx.scene.layout.AnchorPane?>
<?import javafx.scene.layout.VBox?>
<?import javafx.scene.layout.HBox?>

<AnchorPane prefHeight="600.0" prefWidth="400.0" xmlns="http://javafx.com/javafx/17" xmlns:fx="http://javafx.com/fxml/1" fx:controller="seedu.address.ui.CommandHelperWindow">
    <VBox fillWidth="true" AnchorPane.topAnchor="0" AnchorPane.bottomAnchor="0" AnchorPane.leftAnchor="0" AnchorPane.rightAnchor="0">
        <ScrollPane fx:id="scrollPane" VBox.vgrow="ALWAYS" fitToWidth="true">
            <VBox fx:id="dialogContainer" fillWidth="true"/>
        </ScrollPane>
      <HBox VBox.vgrow="NEVER">
            <TextField fx:id="userInput" onAction="#handleUserInput" HBox.hgrow="ALWAYS" prefHeight="41.0"/>
            <Button fx:id="sendButton" mnemonicParsing="false" onAction="#handleUserInput"
                    prefWidth="76.0" prefHeight="41.0" text="Send" HBox.hgrow="NEVER"/>
        </HBox>
    </VBox>
</AnchorPane>
```

Diff 
```
<ScrollPane fx:id="scrollPane" VBox.vgrow="ALWAYS" fitToWidth="true">
    <VBox fx:id="dialogContainer" fillWidth="true"/>
</ScrollPane>
```

Preview:
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/30100720/cd5a4c9c-ad39-4fa5-b1ff-5c2042b8dee8)

**Comment by RunjiaChen** [comment]
Thank you all for the help!
