### ISSUE TITLE
Calling static variables in Sequence Diagram

### ISSUE THREAD

**Issue by fy17ohhh** [nus-cs2103-AY2324S2/forum#639]
Hi, when drawing sequence diagrams, it is mentioned that 

> Method calls to static (i.e., class-level) methods are received by the class itself, not an instance of that class. You can use <<class>> to show that a participant is the class itself.

However, if we are calling a method of `Model` class which uses a parameter of `Model` class, what are some rules we should follow?
e.g. do we need to add use the `<<class>>` notation, and do we need to underline the static variable?

Here is the example Sequence Diagram
<img width="574" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/103088135/766572c0-26ca-405a-b8eb-c6d6c89bf9ae">

**Comment by damithc** [comment]
@fy17ohhh When using a class-level variable as a parameter, you can use `ClassName.variableName` syntax. They should not be underlined (underlining class-level members is used in class diagrams, not sequence diagrams).

**Comment by fy17ohhh** [comment]
> @fy17ohhh When using a class-level variable as a parameter, you can use `ClassName.variableName` syntax. They should not be underlined (underlining class-level members is used in class diagrams, not sequence diagrams).

Noted, thank you for the clarification!
