### ISSUE TITLE
Testing using multiple operating systems in PE?

### ISSUE THREAD

**Issue by E0735389** [nus-cs2103-AY2324S2/forum#640]
I notice that in the bug report phase, we're only allowed to use one operating system. Would it be allowed (theoretically) to use a virtual machine to test the program in multiple operating systems, which increases the chance of finding bugs?

Also, what's the policy on testing our tP (is there a way to request smoke test on multiple operating systems like the iP?)

**Comment by damithc** [comment]
@E0735389 Yes, you may use VMs, but use the same CATcher instance to report all bugs.

> Also, what's the policy on testing our tP (is there a way to request smoke test on multiple operating systems like the iP?)

Yes, you may get others' help to smoke test your tP on other OS'es, by posting in the forum.
Our own smoke tests also test the JAR on all three OS'es, but we only test if the JAR can launch without crashing.
