### ISSUE TITLE
HTML escaping in CATcher bug report

### ISSUE THREAD

**Issue by E0735389** [nus-cs2103-AY2324S2/forum#641]
In the textbook it's mentioned

>  If you need to include < or > symbols in your bug report, use HTML equivalents for 'less than' and 'greater than' instead (i.e., `&lt;` and `&gt;` e.g., `x &lt; y` instead of `x < y`).
Reason: CATcher and GitHub strips out content wrapped in < and >, for security reasons.

While this is technically correct, it's not very accurate e.g. if the user want to type `<` wrapped in backticks i.e. inline quotes, then verbatim `<` must be used.

Speaking of which, actually it's shorter to type `\<` and `\>`. I'd recommend using that in the textbook instead.

**Comment by damithc** [comment]
> actually it's shorter to type `\<` and `\>`. I'd recommend using that in the textbook instead.

Good point @E0735389 
I've updated instructions accordingly.
