### ISSUE TITLE
What's the difference between nus-pe-script and nus-pe-bot?

### ISSUE THREAD

**Issue by E0735389** [nus-cs2103-AY2324S2/forum#642]
Just curious. Seems that both goes around and open issues.

https://github.com/nus-pe-script

https://github.com/nus-pe-bot

Edit: fun fact, I found a few more ( https://github.com/soc-pe-bot https://github.com/soc-se-bot )

**Comment by damithc** [comment]
@E0735389 no difference. Due to large class size, we have to use multiple accounts to get around GitHub API limits.
