### ISSUE TITLE
Week 11 Topics 11.3 Video Quiz blank

### ISSUE THREAD

**Issue by billyhoce** [nus-cs2103-AY2324S2/forum#643]
Seems like there is a bug with the in-video quiz. Other video quizzes in week 11 work fine for me, just this one has an issue and I can't even skip forward the video as it just brings up this Quiz! Anyone else facing this issue?

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/84035425/89b112b6-cfc9-44c5-90f7-9e44c4472ebc)

**Comment by damithc** [comment]
@billyhoce what happens if you click the `close` button (on top right)?
Also, try a different browser (or an incognito browser) to see if that helps.

**Comment by billyhoce** [comment]
Was using chrome on PC. When i click close, it brings me to the part of the video right before the quiz (paused). The moment I play the video, the empty quiz pops up again.

I tried chrome on my phone and it worked. Will try clearing cache etc on my PC later. Thanks prof @damithc
