### ISSUE TITLE
CS2103T: allowed resource during PE?

### ISSUE THREAD

**Issue by E0735389** [nus-cs2103-AY2324S2/forum#644]
I notice on the website:

> Website: Course website (e.g., to look up PE info)
> Software: PDF reader (to read the UG/DG or other references such as the textbook)

Doesn't the course website already contain the textbook anyway? (and it's more convenient because there's Algolia DocSearch)

**Comment by damithc** [comment]
@E0735389 Some might prefer the PDF version of the textbook, for example, so that they can augment it with their own notes.
