### ISSUE TITLE
Request for the usage of CalendarFX

### ISSUE THREAD

**Issue by Ella-e** [nus-cs2103-AY2324S2/forum#645]
## Library

[CalendarFX](https://github.com/dlsc-software-consulting-gmbh/CalendarFX)

## Purpose

We want to use it to implement a calendar view of appointments, so it will appear more natural for the users to manage the appointments.

## License
Apache-2
https://github.com/dlsc-software-consulting-gmbh/CalendarFX

**Comment by damithc** [comment]
Approved.
