### ISSUE TITLE
Is it a bug if the application starts with no data shown because of illegal values in JSON?

### ISSUE THREAD

**Issue by yashpola** [nus-cs2103-AY2324S2/forum#646]
For example if I edit the JSON to have a non-ascii char such as an emoji, the application will launch with no data and display the exception in the terminal. This seems to be how it worked for AB3 fields such as email, so is it fine to maintain this standard and not treat it as a bug?

**Comment by damithc** [comment]
@yashpola That should be enough, unless your UG claims to have a higher level of support for edits to the data file. Also relevant is [this](https://nus-cs2103-ay2324s2.github.io/website/admin/tp-pe.html#:~:text=Handling%20manual%20edits%20to%20the%20data%20file).

**Comment by yashpola** [comment]
Thanks prof @damithc
