### ISSUE TITLE
Requesting help for CI checks

### ISSUE THREAD

**Issue by sarjinius** [nus-cs2103-AY2324S2/forum#648]
Hello, can anyone point out what went wrong here? Thank you.

![A5FD08EF-9D91-4EAC-9F44-CEBC003D9647](https://github.com/nus-cs2103-AY2324S2/forum/assets/122223898/660e2321-61e6-45dd-99fb-9c0d3fc08d23)
![6D54559D-9AF6-44F6-B18F-1751D51D6344](https://github.com/nus-cs2103-AY2324S2/forum/assets/122223898/86517438-08c8-4a84-b1a5-0f731294e862)

**Comment by drustanyjt** [comment]
@sarjinius EOF stands for End of File. You need to add a new line at the end of the file to comply with checkstyle (just go to the end of the file and press enter)

**Comment by sarjinius** [comment]
Oops, forgot to mention that I have added the new line already on my IntelliJ, but the change does not reflect on my git.

**Comment by sarjinius** [comment]
The last line in the file is line 28, although the error message states line 27.

**Comment by sarjinius** [comment]
Problem resolved, thank you.

**Comment by drustanyjt** [comment]
@sarjinius out of curiosity what was the issue?
