### ISSUE TITLE
Is the following class diagram format valid?

### ISSUE THREAD

**Issue by tankh99** [nus-cs2103-AY2324S2/forum#650]
I was creating my own class diagram, but I was facing difficulties trying to include methods and fields, so I removed the style.puml and got this format. Is this considered to be a valid format since it seems to be PlantUML's default?

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/56617918/4438059f-657e-4cdd-80a2-61e8bd84dcca)

**Comment by E0735389** [comment]
I think it's considered invalid, as mentioned in one of the tutorial the circled C is nonstandard.

Nevertheless, you can include these two
```
hide circle
skinparam classAttributeIconSize 0
```
which can be seen used in e.g. `diagrams/add-remark/RemarkClass.puml` file.

**Comment by tankh99** [comment]
> Nevertheless, you can include these two

Oh thank you for the answer and this tip!

**Comment by damithc** [comment]
@tankh99 You can also try to keep the `style.puml` but in override the style.puml setting that you want to deviate from (i.e., `hide members` setting)

See if the following works:
```
!include style.puml
show members
```

**Comment by tankh99** [comment]
> @tankh99 You can also try to keep the `style.puml` but in override the style.puml setting that you want to deviate from (i.e., `hide members` setting)
> 
> See if the following works:
> 
> ```
> !include style.puml
> show members
> ```

Noted with thanks!
