### ISSUE TITLE
"Planned enhancements" section in the developer guide in the dry run

### ISSUE THREAD

**Issue by E0735389** [nus-cs2103-AY2324S2/forum#651]
From the textbook:

>  We highly recommend adding an appendix named Planned Enhancements, listing fixes you propose to add in the near future, to counter known feature flaws.

However, in the dry run, the developer guide is not taken into consideration. What should we do instead? (That is, would features already in the planned enhancements be counted as a bug for the dry run?)

**Comment by damithc** [comment]
> However, in the dry run, the developer guide is not taken into consideration. What should we do instead? (That is, would features already in the planned enhancements be counted as a bug for the dry run?)

@E0735389 Yes, you may report any feature flaws in the PE dry run. Testers still get credit for reporting them and the dev team is not penalized for PE-D bug reports.

**Comment by E0735389** [comment]
But... does this mean testers can just look at the developer guide and report whatever there are in the planned enhancements section instead? How does that work?

**Comment by damithc** [comment]
> But... does this mean testers can just look at the developer guide and report whatever there are in the planned enhancements section instead? How does that work?

Yes. I suspect most teams have not filled up this part yet. Even if otherwise, as the receiving team will be rating testers for how useful their bug reports are, there is an incentive for testers to focus on bugs that can be fixed in v1.4, rather than just repeat the planned enhancements.
