### ISSUE TITLE
Filling up portion of what we did

### ISSUE THREAD

**Issue by cheahTJ** [nus-cs2103-AY2324S2/forum#653]
Hi, can I check if we need to fill up our individual's markdown file to indicate what are the exact features (with its corresponding commits) for this round of submission v1.3? Or we could do it for v1.4 or there is no need to do it as I don't see them on the course website, thank you for clarifying in advance!

**Comment by damithc** [comment]
@cheahTJ I think you are referring to the [PPP](https://nus-cs2103-ay2324s2.github.io/website/admin/tp-deliverables.html#deliverable-project-portfolio-page-ppp). It's optional to submit this semester.

**Comment by cheahTJ** [comment]
thank you for clarification prof!
