### ISSUE TITLE
Adding tests in v1.4

### ISSUE THREAD

**Issue by wilsonwid** [nus-cs2103-AY2324S2/forum#654]
Are we allowed to add additional tests in v1.4?

**Comment by damithc** [comment]
@wilsonwid Yes. More info [here](https://nus-cs2103-ay2324s2.github.io/website/schedule/week12/project.html#:~:text=Allowed%20in%20the%20v1.4%20milestone).

**Comment by wilsonwid** [comment]
Thank you Prof! @damithc
