### ISSUE TITLE
UserGuide

### ISSUE THREAD

**Issue by cheahTJ** [nus-cs2103-AY2324S2/forum#655]
Hi just to confirm, our userguide does not need to be released with our v1.3 jar file right since it can be accessed through our team's github site?

**Comment by damithc** [comment]
@cheahTJ Yes you do, as per [this](https://nus-cs2103-ay2324s2.github.io/website/schedule/week11/project.html#3-release-v1-3-thu-apr-4th-23-59).

**Comment by cheahTJ** [comment]
Thank you prof!
