### ISSUE TITLE
Assertions task turned back to red

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#657]
I added an assert statement in week 10 but i think the line of code became attributed to my groupmate somehow. How should i fix this because the assert tab turned red again

**Comment by damithc** [comment]
@bgopi23 You can override authorship auto-detected by RepoSense. See https://nus-cs2103-ay2324s2.github.io/website/admin/tools.html#tool-reposense-for-authorship-tracking

**Comment by baskargopinath** [comment]
thanks prof @damithc
