### ISSUE TITLE
PE Dry Run: ICube or LT15?

### ISSUE THREAD

**Issue by Jerome-j** [nus-cs2103-AY2324S2/forum#658]
Hi Prof,

In the email it was stated that "F2F mode, from the lecture venue (ICube Auditorium):". But on NUSMODs it states that our lecture venue is at LT15.

Can I please clarify if the PE-D is held at I3 or LT15?

I am taking the CS2103 (no T) variant BTW

**Comment by damithc** [comment]
Ooops... it should be LT15
I posted a correction announcement just now.
Thanks for the heads up @Jerome-j
