### ISSUE TITLE
I can't find my tags on my repo

### ISSUE THREAD

**Issue by timothysashimi** [nus-cs2103-AY2324S2/forum#66]
Hi all, after pushing my tags using CLI, i can't find it on my repo.

i used git tag -m "message" and git push --tags

How do i resolve this?

**Comment by Jerome-j** [comment]
Hello, I went into your repo and I could see two tags `Level-0` and `Level-1`
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/49815108/adcaa3f3-3dfe-4bc0-8086-34e1dfdf7905)

Please try to push each tag manually using `git push origin Level-4`

**Comment by itstrueitstrueitsrealitsreal** [comment]
Refresh your forked repo, click on tags on the right to see your tags.

**Comment by damithc** [comment]
@timothysashimi is this issue resolved now?
