### ISSUE TITLE
PE dry run: test using UG pdf or html?

### ISSUE THREAD

**Issue by aureliony** [nus-cs2103-AY2324S2/forum#660]
There seems to be conflicting information on the course website. Should we test the product based on the UG pdf, or the UG html on their github page?

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39163684/4a6874c7-80a2-467e-b01b-40ba7f6dbb64)

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39163684/96a4bdf8-9e99-431a-a7d1-d34fdaeeb401)

**Comment by damithc** [comment]
Should be the PDF. The incorrect info is a stale instruction from previous sem. Will fix. Thanks @aureliony fore reporting this.
