### ISSUE TITLE
Clarifying on whether our implementation is considered a bug or a feature flaw. 

### ISSUE THREAD

**Issue by delishad21** [nus-cs2103-AY2324S2/forum#661]
Our group has a find feature that **works** but not as intended due to certain implementation flaws. Under this find feature, we have a specific subfeature that requires the parsing of doubles instead of integers. However as we (incorrectly) parsed user input as integers, the feature now only works with integers (which is a subset of the items that it is supposed to find). It dosen't crash the application when used but it does limit a crucial functionality of our application. Is this considered a bug that we can fix?

**Comment by damithc** [comment]
@delishad21 Is the product still usable in the current state? In that case, support for double inputs can be given as a planned enhancement.
