### ISSUE TITLE
Improve CATcher's tab navigation

### ISSUE THREAD

**Issue by E0735389** [nus-cs2103-AY2324S2/forum#666]
In GitHub, it only takes 3 tab key presses to navigate from the title pane to the body pane in the issues window.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/97508964/63d0a468-b99e-4207-83c8-f8ce50e1fcaa)

However, in CATcher, pressing tabs navigate through **all** the formatting buttons. This is very inconvenient.

**Comment by damithc** [comment]
Thanks for the suggestion, @E0735389 
Posted in https://github.com/CATcher-org/CATcher/issues/1266
