### ISSUE TITLE
Is it okay to have alot of import statements to improve code quality inside the class?

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#667]
Lets say to use a message from another class and we are repeatedly doing

`Messages.ErrorMessage`

instead of this, could we keep importing all the necessary messages from Messages class so we can just write

`ErrorMessage`

**Comment by yashpola** [comment]
In my opinion its better not to do so as then the reference of where `ErrorMessage` is coming from is unclear i.e. the reader would instinctively search through the class to find the reference and failing to do so, would have to intuit that its an import

More importantly the method suggested will lead to a lot of unused imports which is a checkstyle violation and is also cumbersome

**Comment by baskargopinath** [comment]
i mean like this
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/73015364/d0af9d90-ea30-4149-83ba-f1ec20b1f541)
there wont be any unused imports @yashpola

**Comment by yashpola** [comment]
In this case, I would refer to the earlier point still. Unless for use in test code where we just use constants without worrying about where they came from, I think functional code should keep references clear especially if they are not findable easily in the current class itself

**Comment by baskargopinath** [comment]
@damithc prof is there any fixed rule for this that will cause us to be penalized?

**Comment by damithc** [comment]
> @damithc prof is there any fixed rule for this that will cause us to be penalized?

@bgopi23 No fixed rules for Java code, except the coding standard.

**Comment by baskargopinath** [comment]
thanks prof @damithc 
thanks @yashpola for your inputs
