### ISSUE TITLE
Is it necessary to follow bug reporting details format specified in PE-D guide?

### ISSUE THREAD

**Issue by ruijietay** [nus-cs2103-AY2324S2/forum#668]
<img width="735" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/47778098/3b31a7cb-ca60-4197-b3ec-169997363e8e">

In the PE-D guide, it states that a bug report should have enough details. This is followed by an example `steps to reproduce, expected, actual, and screenshots`. 

Does this mean we always have to include the steps to reproduce, the expected and actual values, and screenshots, for it to constitute as a good bug report?

**Comment by damithc** [comment]
@ruijietay The more you follow these the better. But they are guidelines. Application depends on case-by-case. In some cases, certain elements can be left out without losing much value.

**Comment by ruijietay** [comment]
Thank you for the clarification and quick reply 😄 
@damithc
