### ISSUE TITLE
Number of storage files

### ISSUE THREAD

**Issue by chiralcentre** [nus-cs2103-AY2324S2/forum#669]
Can I check with the teaching team if we are allowed to save data in multiple files in the same directory? For example, currently our team has saved data in three separate files for three different entities (persons, jobs, applications).

**Comment by damithc** [comment]
@chiralcentre 
1. First, you can cross-check against [tP constraints](https://nus-cs2103-ay2324s2.github.io/website/admin/tp-constraints.html#tp-constraints). If you are unsure if your team is violating a given constraint, you can raise here the specific doubt.
2.  Second, this behavior (like any other app behavior) can be the subject of bug reports in the PE (e.g., if a tester thinks this is a feature flaw). If that happens, each bug report needs to be decided on a case-by-case basis.

**Comment by chiralcentre** [comment]
Thank you Prof for the response. To be specific, I am unsure if my team is violating the constraint here, as the wording seems to imply that the data should only be stored in a singular file.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/83827461/f361a397-4e37-4e2b-a3fa-1a241447b88a)

**Comment by damithc** [comment]
@chiralcentre I see what you mean. No, the constraint was not meant to be 'only one data file'.

**Comment by chiralcentre** [comment]
Thank you Prof for the clarification!
