### ISSUE TITLE
Typo in "FAQs on what is allowed during the feature freeze"

### ISSUE THREAD

**Issue by Javiery3889** [nus-cs2103-AY2324S2/forum#670]
> If will be considered a feature change (i.e., not allowed to do) if,
<img width="757" alt="Screenshot 2024-04-06 at 09 29 46" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/28281451/097ceaab-8ffe-492b-ac80-2491da1a020f">

I think it should be:
>  It will be considered a feature change (i.e., not allowed to do) if,

**Comment by damithc** [comment]
Fixed. Thanks for the bug report @Javiery3889
