### ISSUE TITLE
Clarification on the differentiation between bugs and feature changes

### ISSUE THREAD

**Issue by ziyang27** [nus-cs2103-AY2324S2/forum#671]
Hi Profs, TAs, and friends

For context, our group has a select feature that displays the profile of the selected contact in a separate panel. The panel will update if the details of the selected contact are edited. Additionally, we also have a command that adds a tag cumulatively to a contact (addTag).

However, when a tag is added using the aforementioned addTag command, the changes will not be reflected in the profile panel at the side. Additionally, when the contact is deleted or the list is cleared, the details in the profile panel will not be removed.

May I ask if this constitutes 'incorrect' behavior as stated in the FAQ section in the textbook, under Feature Freeze or should we put it under Planned Enhancement? 

Thank you in advance and have a great day ahead!

**Comment by damithc** [comment]
@ziyang27 If this feature (i.e., auto-updating the panel when data changes) is already implemented but not working as expected due to a bug (e.g., the update action was hooked up to the wrong  event handler), it can be fixed. But if the feature was not implemented at all, it should not be added now, but can be listed as a _planned enhancement_.

**Comment by ziyang27** [comment]
@damithc Dear Prof, thank you for the clarification. May I ask one more question? 

Currently, we already have the (auto-updating the panel when the data changes) feature. However, it is only 'hooked up' to the edit command. We missed out the (1) delete command, (2) clear command, (3) addTag command. 

Thus leading to an inconsistency between the UI and the state of data as stated in FAQ Question 10:
<img width="427" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/122247192/fa8f0f4b-574f-4f04-845c-275728ffb479">

In this case will we be able to rectify it? Thank you so much in advance 😄

**Comment by damithc** [comment]
@ziyang27 In that case it goes beyond a bug fix, into 'not implemented fully' territory. So, we won't be allowing it but you can state in the UG that auto-updating is supported for edit command and the support for it w.r.t. other commands is coming in a future version. Also, you can list it as a planned enhancement. 
Alternatively, you may remove it from the edit feature as well, if you think it is better to be consistent across the app.

**Comment by ziyang27** [comment]
@damithc Dear Prof, understood! Thank you so much 😄

**Comment by damithc** [comment]
@ziyang27 After thinking further, I'm OK to allow this change. That is, you are free to follow my suggestion above or link up the auto-update feature to the remaining commands.

**Comment by ziyang27** [comment]
Dear Prof @damithc, thank you so much 😄
