### ISSUE TITLE
Definition of incorrect error message

### ISSUE THREAD

**Issue by SherisseTJW** [nus-cs2103-AY2324S2/forum#672]
Hi, can I check what is meant by incorrect error message as written in the website?

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/63995220/83fe43f5-38d7-4024-bcb8-f90fa63811aa)

For example, would this count as an incorrect error message? Since it does target the issue is in the Datetime argument provided, but does not explicitly state that the issue is because the time provided is invalid. 

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/63995220/fe2bc8ad-b0b8-4878-a470-ec5daff1cfb7)

Additionally, would I be allowed to add a new check and error message for this, or would I only be allowed to edit the existing error message.

**Comment by SherisseTJW** [comment]
Adding on, would we be allowed to fix something like this to standardise error messages?

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/63995220/ce016630-d1c3-4506-89dc-40b9ad84b221)

**Comment by damithc** [comment]
> For example, would this count as an incorrect error message? Since it does target the issue is in the Datetime argument provided, but does not explicitly state that the issue is because the time provided is invalid.
> 
> ![image](https://private-user-images.githubusercontent.com/63995220/320184866-fe2bc8ad-b0b8-4878-a470-ec5daff1cfb7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzODMyNDQsIm5iZiI6MTcxMjM4Mjk0NCwicGF0aCI6Ii82Mzk5NTIyMC8zMjAxODQ4NjYtZmUyYmM4YWQtYjBiOC00ODc4LWE0NzAtZWM1ZGFmZjFjZmI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDA1NTU0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhZDhlNmZhNjQ1YzYwMDc2ZWRjNGU0ZmQzMDI4ZjZhZDkxNzAyZjA0YzA5NTMzYTc3Yjg5ODdhYzEyOTkyODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H25epUTs53wk50J37AJ9nRaMBpr-lT7XqWRoBCJgotI)

@SherisseTJW you may update the error message to indicate the date/time needs to be valid as well.

> Additionally, would I be allowed to add a new check and error message for this, or would I only be allowed to edit the existing error message.

The following applies. 
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/34765d36-9f89-4906-82ac-e9870b3f6908)

Based on the screenshot provided, the invalid date is rejected already, which means it doesn't cause the kind of problems that qualify it to be fixed in v1.4






> Adding on, would we be allowed to fix something like this to standardise error messages?
> 
> ![image](https://private-user-images.githubusercontent.com/63995220/320185477-ce016630-d1c3-4506-89dc-40b9ad84b221.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzODM0MjAsIm5iZiI6MTcxMjM4MzEyMCwicGF0aCI6Ii82Mzk5NTIyMC8zMjAxODU0NzctY2UwMTY2MzAtZDFjMy00NTA2LTg5ZGMtNDBiOWFkODRiMjIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDA1NTg0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzZmY4OGU4NmM0NDkzODA3YTgxYTIzZDljODMzZjljNjZlMTY0YjBjYmIxNDY4Y2FhMzA2MDAyZmExYWJkMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lTqIHwppsydWCWEan8NBy9eKTvO2wURvSa4jgy39GXA)

_Standardizing_ is an enhancement, not a bug fix. So, not allowed.

**Comment by SherisseTJW** [comment]
Thanks for the clarification!
