### ISSUE TITLE
Question on Feature Freeze

### ISSUE THREAD

**Issue by MarcusGitty** [nus-cs2103-AY2324S2/forum#673]
Hi TA & Profs,

Our team have fixed some bugs that was indicated during PE before that in their local repo and have not merged them into our teams.

Some of this bug fix might be considered fixing of feature flaws.

I've checked and the commit time of this fixes is before 5 Apr 10am, 

could we merge these fixes in or would this violate the "feature-freeze" in v1.4

Thank you !

**Comment by damithc** [comment]
@MarcusGitty The following applies.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/52ac5a40-fe0e-44ba-9154-633771b8797a)

So, it is a question of if the enhancement was in v1.3 jar, not _when_ the enhancement was done.

**Comment by MarcusGitty** [comment]
Thank you prof !
