### ISSUE TITLE
Clarification on editing error messages

### ISSUE THREAD

**Issue by dillontkh** [nus-cs2103-AY2324S2/forum#674]
> For example, would this count as an incorrect error message? Since it does target the issue is in the Datetime argument provided, but does not explicitly state that the issue is because the time provided is invalid.
> 
> ![image](https://private-user-images.githubusercontent.com/63995220/320184866-fe2bc8ad-b0b8-4878-a470-ec5daff1cfb7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzODMyNDQsIm5iZiI6MTcxMjM4Mjk0NCwicGF0aCI6Ii82Mzk5NTIyMC8zMjAxODQ4NjYtZmUyYmM4YWQtYjBiOC00ODc4LWE0NzAtZWM1ZGFmZjFjZmI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDA1NTU0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhZDhlNmZhNjQ1YzYwMDc2ZWRjNGU0ZmQzMDI4ZjZhZDkxNzAyZjA0YzA5NTMzYTc3Yjg5ODdhYzEyOTkyODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H25epUTs53wk50J37AJ9nRaMBpr-lT7XqWRoBCJgotI)

@SherisseTJW you may update the error message to indicate the date/time needs to be valid as well.

_Originally posted by @damithc in https://github.com/nus-cs2103-AY2324S2/forum/issues/672#issuecomment-2040981929_

![Screenshot_20240406_192131_Firefox.jpg](https://github.com/nus-cs2103-AY2324S2/forum/assets/40649376/89dce754-8d1d-47df-9ccf-9977b79ee290)

@damithc Hi prof, my team and I are having trouble understanding the difference between this change you approved and FAQ Q6.

Specifically, the part where it mentions making error messages more specific is not allowed.

Could you kindly explain the difference?

**Comment by damithc** [comment]
@dillontkh My rationale for allowing this change was that the current error message is already at a certain specificity level but misses out a detail that should be included at that specificity level, making the message incomplete, and hence, incorrect i.e., it currently says 'the problem can be x or y' when in reality the problem can be 'x or y or z'.  If the original message was more general (e.g., 'the command has a problem'), I wouldn't have allowed the change.

**Comment by dillontkh** [comment]
Thanks for the quick reply prof!

Just to make sure I understand it correctly, editing the error message while remaining in the same "specificity level" is alright.

e.g. "time format incorrect!" -> "time should be in the format hh:mm" would be allowed, but

"Invalid syntax" -> "time format incorrect" would not be?

**Comment by damithc** [comment]
@dillontkh 'wrong format' and 'invalid value' are two different problems. Both are at same specificity level.  For example, 2024-02-31 is in correct format but an invalid date. So, rejecting 2024-02-31 as 'wrong format' is an incorrect behavior. The error message should be 'invalid value' but  that likely requires changes to the validity checks in place. So, the way to minimize code changes while also being correct is to call it 'wrong format OR invalid value'. My suggestions to the OP was along that line.

> e.g. "time format incorrect!" -> "time should be in the format hh:mm" would be allowed, but
> 
> "Invalid syntax" -> "time format incorrect" would not be?

In both cases, the original version is not incorrect. Both are making the message more informative/specific, and hence, not allowed.

**Comment by zhekaiii** [comment]
Edit: shifted this to #677

**Comment by damithc** [comment]
@zhekaiii can you post your question as a separate issue? Otherwise @dillontkh will not be able to close this issue when his question is answered.

**Comment by dillontkh** [comment]
I think I get it now, thanks prof!
