### ISSUE TITLE
Not sure if I'm improving code quality correctly

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#675]
When I was trying to reduce clutter in the parser classes, i created a bunch of getter methods. is this correct? or is this considered bad code quality under duplicate code

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/73015364/f1ed54c0-7441-4110-9c61-614a5d8331d3)

<hr>

Before:
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/73015364/6b597f8f-ed4e-4e54-b36a-b6f0e8000e02)

After: 
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/73015364/1c7bf2f8-7308-406b-905c-f65ce9649025)

**Comment by baskargopinath** [comment]
@damithc prof could you advice if possible as well?

**Comment by damithc** [comment]
> @damithc prof could you advice if possible as well?

@bgopi23 For subjective and context-specific discussions such as this one, I will monitor and join in only if some important point is missed or mis-stated. 

In general, as the code is meant for the consumption of developers, you are in a good position to see if the refactoring made this specific code better or worse for you. If it is hard to decide one way or the other, it is likely the benefit is not much.

BTW, if you share the link to the specific commit (containing this change), it might be easier for others to comment on it.

**Comment by baskargopinath** [comment]
@damithc understood prof, i ended up not committing it because i realised as you said if its so hard to decide, the benefits are probably too trivial. thank you!

**Comment by E0735389** [comment]
A downside of this approach: this increases coupling --- now the `ArgumentMultimap` depends on what prefixes are available, which is contained in the `Person` model.

There's nothing `Person`-specific in `ArgumentMultimap`.
