### ISSUE TITLE
Should user guide contain specific details?

### ISSUE THREAD

**Issue by acekhoon** [nus-cs2103-AY2324S2/forum#676]
Hello! I hope everyone is doing well:)

Our team has a small doubt on user guide design where we got a feedback from PE-D that the user guides must contain the expected messages for valid comments or some sort of screenshots to display the successful messages to the users in the guide for every command we created.

Is this necessary component / graded component of the UG side of this project?

Thank you!!

**Comment by damithc** [comment]
@acekhoon There is no such strict requirement. So, you need to decide case-by-case. For each case, ask if the cost of adding and maintaining (don't forget the maintenance cost, which is a longer term and higher cost compared to adding it the first time) that information is worth the value it provides to the user.

**Comment by acekhoon** [comment]
Thank you so much prof!!
