### ISSUE TITLE
Clarification on tweaking success messages

### ISSUE THREAD

**Issue by zhekaiii** [nus-cs2103-AY2324S2/forum#677]
Hi prof @damithc, regarding success messages, currently, we display a success message on editing a person, but it contains missing information. 

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/40530851/750c11d0-b833-496d-8bfb-dee1d43cd663)

May I clarify, is this considered a bug? Because the message is supposed to display all of the information, but it is currently missing, so it is not really working as intended (although we did not explicitly mention what the success message will show in our user guide)

**Comment by dillontkh** [comment]
Ok after getting clarification in #674 I hope my answer to this is correct...

I think adding birthday would not be allowed as the current information displayed is not _wrong_. Adding the birthday would fall under "Making user-facing info more informative" and therefore not allowed.

**Comment by damithc** [comment]
@zhekaiii While somewhat borderline (the success message seem to show some info of the edited person but not other info), as @dillontkh mentioned, this behavior is not incorrect. So, adding more info can be postponed to a future version.

**Comment by zhekaiii** [comment]
Thank you prof and dillon!
