### ISSUE TITLE
Clarification on fixing silently failing commands

### ISSUE THREAD

**Issue by wilsonwid** [nus-cs2103-AY2324S2/forum#678]
If the command is not run, but no visible error output was given in the console, it is considered as "silently failing" and hence an error message can be added, right?

**Comment by damithc** [comment]
@wilsonwid Yes, but give a minimal error message requires the minimal amount of code changes, to stay closer to the spirit of the feature freeze.

**Comment by wilsonwid** [comment]
Thank you Prof!
