### ISSUE TITLE
Clarification on bugs and workarounds

### ISSUE THREAD

**Issue by wilsonwid** [nus-cs2103-AY2324S2/forum#679]
Our team's application has a bug wherein the command will run only if the application has been run before. Hence there is a "workaround" for this by closing and re-running the application. Is this considered something that is able to be fixed in v1.4?

**Comment by damithc** [comment]
@wilsonwid I need more specifics. If you are not willing to share here, you can contact me vis MSTeams or email.

**Comment by wilsonwid** [comment]
Sure, thank you Prof!
