### ISSUE TITLE
Clarification regarding Q3 and Q5 of the FAQ

### ISSUE THREAD

**Issue by wilsonwid** [nus-cs2103-AY2324S2/forum#680]
Q3 of the FAQ states that:
> A: In that case, we go by the reasonable 'correct' behavior that one expects. For example, the UG might not specify what happens if a user typed an extra space after the first keyword of the command (e.g., mark[SPACE]1 vs mark[SPACE][SPACE]1) in which case the reasonable correct behavior is to ignore the extra space.

and Q5 of the FAQ states that:
> A: Can be allowed only if the current behavior causes the software to misbehave (i.e., crash, give incorrect results, store inconsistent data, or make it unusable for typical users).
Accepting seemingly 'unsuitable' values for an input (e.g., accepting numbers for a person name, empty value as a parameter):
This is not considered 'incorrect' (giving more freedom to the user is not necessarily incorrect) unless those unsuitable values causes the application to misbehave.
Validity checks on edits to the data file:
As per AB3 UG (which states the current level of support for editing the data file manually), only valid edits will be supported. If the file is invalid, the app will start with an empty file (not crash). You may rectify only if the current level of support doesn't meet that bar. Furthermore, you may state in the UG that certain incorrect edits to the datafile can result in unexpected behaviors, and caution users to edit the file only if they know what they are doing.
Handling extraneous inputs (e.g., extra parameters, repeated parameters etc.) in commands:
The command 'forgiving' these extraneous inputs (i.e., giving an output same as or similar to if those inputs are not present) is not incorrect. You can mention in the UG that such inputs will be ignored. AB3 already does a similar thing for some commands. Any special handling of such inputs can be left as a future enhancement.

Our team's product has a bug whereby starting datetimes for an event can be after the ending datetime. This means that it does qualify as "incorrect behaviour" based on Q3. However, in Q5, we can tweak validity checks "only if the current behaviour causes the software to misbehave". Are we allowed to fix this bug?

**Comment by baskargopinath** [comment]
i feel like you're allowed to fix this bug because its impossible for a start date to be after the end date.

**Comment by damithc** [comment]
@wilsonwid Q5 has higher priority in this case. Blocking unsuitable values is a nice to have enhancement. Hence, not blocking them is not incorrect. So, in this version of the product it's the users responsibility to ensure unsuitable start/end times are not entered.

**Comment by wilsonwid** [comment]
Thank you Prof!
