### ISSUE TITLE
Clarification on the fixing of bugs

### ISSUE THREAD

**Issue by alvinnzz** [nus-cs2103-AY2324S2/forum#681]
Our team application has a bug where a command called with a large number "1000000.05" results in a wrong number of "1000000.06" being returned due to the precision of using a float. Will setting the limit of the size of the number for the command be considered as a feature change? Otherwise, will using integer for the whole number part of the number and another integer for the decimal part of the number be alright?

**Comment by damithc** [comment]
@alvinnzz This bug can be fixed, but do it in a way that requires a minimal amount of code change.

**Comment by alvinnzz** [comment]
@damithc Alright prof! Will setting a minimum and maximum for the attribute be a violation of the the feature change?

**Comment by damithc** [comment]
@alvinnzz That seem like a behavior change unrelated to the specific error in concern. It's better if you fix the precision issue using an internal change instead.
