### ISSUE TITLE
Query regarding tP code reuse

### ISSUE THREAD

**Issue by radeon2525** [nus-cs2103-AY2324S2/forum#682]
Do I need to declare reuse if I have used the code from addressbook-4 for some implementations. The course website says the following: 

"Giving credit for reusing from course materials (e.g., course textbook, tutorials, resources from se-education.org) is not required, although you are welcome to do so. Reason: Those materials were created by the teaching team for you to use/reuse.".

And if we need to cite, how and where should I cite it.

**Comment by damithc** [comment]
@radeon2525 If you reuse code from AB4, it is better to cite it, as it wasn't given to you as a course resource (the way other se-edu guides/tutorials were given). You can cite it the same way you cite any other reuse.

**Comment by radeon2525** [comment]
Okay, thank you prof
