### ISSUE TITLE
Are we allowed to change the phone validation in v1.4?

### ISSUE THREAD

**Issue by logical-1985516** [nus-cs2103-AY2324S2/forum#683]
For instance, are we allowed to add additional validation for international phone numbers? E.g. validation disallows +65 8765 as a phone number even though there is validation for local Singapore phone numbers (without the country code) in 8 digit form.

**Comment by damithc** [comment]
@logical-1985516 Depends on what happens if such values are accepted, as per Q5 of this [FAQ](https://nus-cs2103-ay2324s2.github.io/website/schedule/week12/project.html#:~:text=FAQs%20on%20what%20is%20allowed%20during%20the%20feature%20freeze).

**Comment by logical-1985516** [comment]
Thank you prof for your response! I shall close this issue now.
