### ISSUE TITLE
Changing UI

### ISSUE THREAD

**Issue by chiralcentre** [nus-cs2103-AY2324S2/forum#684]
Can I check with the teaching team if we are allowed to make changes to the UI in v1.4 to allow for wrapping of text? Currently, the text is viewed in a straight line, and we are unable to see the fields if the text is very long. For example, for very long text fields, even when we go fullscreen, we are unable to see the full comment field, as seen in this case for Alex Yeoh. 

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/83827461/6e69e84c-21a8-4f3b-8ebb-e0c11b36df37)

At the same time, can I check if we are allowed to change the default screen size?

**Comment by damithc** [comment]
@chiralcentre For the first question, see if Q8 of this [FAQ](https://nus-cs2103-ay2324s2.github.io/website/schedule/week12/project.html#:~:text=FAQs%20on%20what%20is%20allowed%20during%20the%20feature%20freeze) answers it.

Changing the default window size doesn't sound like a bug fix, unless the current default size results in some incorrect behavior e.g., some elements are not accessible at all.

**Comment by chiralcentre** [comment]
Thank you Prof for the response! Can I check if our app is required to accommodate inputs that are as long as the width of the window? If that is the case, our app cannot display the full text in the main window no matter how much we resize because we do not have wrapping.

**Comment by damithc** [comment]
@chiralcentre It need not accommodate 'abnormal' inputs but if there is a possibility that a normal input cannot be viewed fully in _any_ way after inputting it, it is a bug that we can allow you to fix.

**Comment by chiralcentre** [comment]
Noted thank you for the clarification!

**Comment by acekhoon** [comment]
> @chiralcentre It need not accommodate 'abnormal' inputs but if there is a possibility that a normal input cannot be viewed fully in _any_ way after inputting it, it is a bug that we can allow you to fix.

Hi prof! Thank you so much for your clarification. If I understood that correctly, that means for the fields that might need longer than what Ui is able to display without possibility that the user sabotaging the app (e.g. job description or comments on individual candidates might need much more space to display than what our Ui is able to display at the moment) could be deemed as a bug to fix right? 

Thank you!!

**Comment by damithc** [comment]
> Hi prof! Thank you so much for your clarification. If I understood that correctly, that means for the fields that might need longer than what Ui is able to display without possibility that the user sabotaging the app (e.g. job description or comments on individual candidates might need much more space to display than what our Ui is able to display at the moment) could be deemed as a bug to fix right?

@acekhoon Yes. Note that this applies only if the missing part of the text is not viewable in _any_ way.  See below:

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/28739684-59f1-4a30-b7e1-1d74f8ee4b77)
