### ISSUE TITLE
Fixing a bug will change our original implementation

### ISSUE THREAD

**Issue by jessicawyz** [nus-cs2103-AY2324S2/forum#685]
Hi Profs and TAs,

We have a bug that is high severity. Tester reported that they can add 2 exams with the same details to the same person but when deleting, they can only delete the first exam and the second exam is null so it cannot be deleted.

This is because current code used 2 data structures to represent the data, ObservableList and HashSet. Thus when duplicate exams are added, it can be added to ObservableList as separate objects but can only be added to HashSet once. Therefore HashSet can only contain unique exams. This caused a discrepancy between the two lists.

Are we allowed to 
(a) change the implementation of exam using HashSet. (Would require a lot of code changes as exam is used in many commands)
(b) change the implementation of ObservableList such that it no longer allow duplicates

Thank you

**Comment by damithc** [comment]
@jessicawyz Yes, you can fix this bug. Choose the option that require less code changes.

**Comment by jessicawyz** [comment]
Thank you!

**Comment by jessicawyz** [comment]
Thank you!
