### ISSUE TITLE
How would the checks for violation of feature freeze be

### ISSUE THREAD

**Issue by Ella-e** [nus-cs2103-AY2324S2/forum#686]
Hi Prof, may I ask when would our product go through the checks for violation of feature freeze? Will it done before the end of v1.4 and inform us the result, so we can have a chance and time to revert to a former version?

**Comment by damithc** [comment]
@Ella-e It will be after the v1.4 submission deadline. So, there will be no chance to revert rogue fixes.

**Comment by Ella-e** [comment]
I see, thank you Prof!
