### ISSUE TITLE
Check on the violation of feature freezing for a UI feature that currently not written in the UG but has already implemented before feature freeze

### ISSUE THREAD

**Issue by Ella-e** [nus-cs2103-AY2324S2/forum#687]
Hi Prof, our product has a UI feature, a Calendar view of all the appointments, which is not stated in the UG currently. It contains a clickable calendar and a timeline for the day. It basically just reflect all the changes made to the appointments. While the acutally feature is implemented before feature freezing, it is not included in the UG before the feature freezing, are we allowed to preserve that feature and add some description of it into UG in v1.4?

Another thing to check is that currently the calendar support change of date only by clicking the respective button, with no specific command to do so. Can we still keep that feature by claiming it is just a form of UI display, or the only option left is to remove that feature?

Here is a screen recording of the calendar in working:
https://github.com/nus-cs2103-AY2324S2/forum/assets/60089102/4320217e-422f-4336-b696-9f4092561188

**Comment by damithc** [comment]
> Hi Prof, our product has a UI feature, a Calendar view of all the appointments, which is not stated in the UG currently. It contains a clickable calendar and a timeline for the day. It basically just reflect all the changes made to the appointments. While the acutally feature is implemented before feature freezing, it is not included in the UG before the feature freezing, are we allowed to preserve that feature and add some description of it into UG in v1.4?

@Ella-e was this feature included in the jar file used in the PE-D? If yes, it can be added to the UG.

> Another thing to check is that currently the calendar support change of date only by clicking the respective button, with no specific command to do so. Can we still keep that feature by claiming it is just a form of UI display, or the only option left is to remove that feature?

While the app needs to be optimized for keyboard users, there is no requirement that every feature must have a command equivalent.

**Comment by Ella-e** [comment]
> @Ella-e was this feature included in the jar file used in the PE-D? If yes, it can be added to the UG.

Yes, it is. Thank you Prof!

> While the app needs to be optimized for keyboard users, there is no requirement that every feature must have a command equivalent.

I see! Thank you very much Prof!
