### ISSUE TITLE
Clarification on issue classification

### ISSUE THREAD

**Issue by javierng2knus** [nus-cs2103-AY2324S2/forum#688]
Hi Profs and TAs, should the following issue be considered a feature flaw as indicated by the tester?

> The symbol "," might be present in some patients' offical names. Given that the official name should be supplied in a patient management app, disallowing the "," symbol would cause some patients' identification information unable to be inputted into the app.
> 
> Steps to reproduce:
> 
> 1. Type `add ic/S1234567D n/Alex, Wong`.
> 
> Observed: The app throws an error mentioning that names must consist of alphanumeric characters and spaces only.
> 
> ![image.png](https://raw.githubusercontent.com/benson1029/ped/main/files/2cb28bb6-17a3-47f5-aa05-971559872ac3.png)
> 
> Labels: `type.FeatureFlaw` `severity.Low`

According to the FAQ :
> Q5:
> Can we tweak validity checks for a user input, or error/exception handling?
> 
> A:
> Can be allowed only if the current behavior causes the software to misbehave (i.e., crash, give incorrect results, store inconsistent data, or make it unusable for typical users).

This can be considered unusable for typical users as certain user's names are considered invalid when they contain special characters. Thus it is considered a functionality bug if we are fixing to allow for those names.

Or it can also be considered as a documentation bug since the UG can be more specific in the fact that names does not support symbols and other special characters.

**Comment by damithc** [comment]
> Or it can also be considered as a documentation bug since the UG can be more specific in the fact that names does not support symbols and other special characters.

@javierng2knus This option is more in line with the spirit of the feature freeze, provided there is a reasonable workaround for the issue stated by the tester (e.g., omit those special characters from names)

**Comment by javierng2knus** [comment]
@damithc I see! So the user guide could include something along the lines of
> We do not support symbols or other special characters so you will need to omit them from the name.

And then afterwards we should adjust the error message to reflect the user guide?

**Comment by damithc** [comment]
> @damithc I see! So the user guide could include something along the lines of
> 
> > We do not support symbols or other special characters so you will need to omit them from the name.

@javierng2knus Yes

> And then afterwards we should adjust the error message to reflect the user guide?

Yes, but only if the current one is incorrect. If it is not incorrect, you should not make it more informative or specific.

**Comment by javierng2knus** [comment]
Thank you so much prof!
