### ISSUE TITLE
Does "coming soon" in the UG allow bypassing the feature freeze?

### ISSUE THREAD

**Issue by E0735389** [nus-cs2103-AY2324S2/forum#689]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/97508964/7235292f-b12b-4668-890c-ccbe77a39942)

If not, what's the point of having them in the UG at all?

The textbook is not clear on this point.

**Comment by SherisseTJW** [comment]
I think the `Coming Soon` counts as the Planned Enhancements section

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/63995220/e8c0d5f8-3220-424b-b596-07fe4d12f3ac)

**Comment by damithc** [comment]
@E0735389 Its main purpose is to give more room for students to write user-facing documentation. For example, if a student feels s/he hasn't contributed enough to the UG, they can add a 'Coming soon' feature to the DG.
