### ISSUE TITLE
Distinguishing Enhancement and Bug Fixing

### ISSUE THREAD

**Issue by SherisseTJW** [nus-cs2103-AY2324S2/forum#690]
In Q5 of the FAQ for the Feature Freeze, it is mentioned that we are able to make changes to validity checks only if it causes the software to misbehave, and it lists some examples of what is considered misbehaving. 

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/63995220/8bb9f693-5333-4c13-b125-b4d3f422fd44)

However, I can't seem to find a clear distinguishment between what is considered an enhancement, or what is considered a bug. 

Would I be correct to assume that the introduction of any validity checks for any Invalid Inputs (i.e., 30 February for some Date field, 1234 for Name) would all be considered as an Enhancement since the user can simply not input those when they are running the command? 

However, if hypothetically, we did introduce checks for said fields, just that they did not work correctly, then we are allowed to fix said validity check.

**Comment by damithc** [comment]
> Would I be correct to assume that the introduction of any validity checks for any Invalid Inputs (i.e., 30 February for some Date field, 1234 for Name) would all be considered as an Enhancement since the user can simply not input those when they are running the command?

@SherisseTJW  Yes, unless accepting such values causes the application to misbehave.

> However, if hypothetically, we did introduce checks for said fields, just that they did not work correctly, then we are allowed to fix said validity check.

Yes, if there is clear proof (based on revision history) the check already existed in the jar used for the PE-D but did not work correctly, you can fix it.

**Comment by SherisseTJW** [comment]
Hi! Thanks for the quick clarification again, really appreciate it
