### ISSUE TITLE
Removing reused code from TP for declaration

### ISSUE THREAD

**Issue by tzyian** [nus-cs2103-AY2324S2/forum#691]
I have one instance of code reuse with credit in my tp code, but it is not Java functional code. Specifically, some bash scripts that were helpful for my team at some point but not anymore. 
I have it demarcated with 

```
# @@author rertyy-reused
# Reused from ...
...
# @@author

```

If I were to remove these code from the repository, should I still declare that I have reused code?

**Comment by damithc** [comment]
@rertyy If you remove the reused code from the repo, there is no need to declare that you have reused code. But you still need to submit the reuse declaration in Canvas (_all_ students must submit it).

**Comment by tzyian** [comment]
Noted, thank you!
