### ISSUE TITLE
UG bug leads to feature flaw

### ISSUE THREAD

**Issue by Javiery3889** [nus-cs2103-AY2324S2/forum#692]
Hi,

Suppose we have a parameter `ADDRESS` that takes in any valid local home address, however this is not explicitly stated in the UG. The UG only states the valid character set for this parameter.

Certain edge cases such as `ADDRESS` with `@` character was not thought of during implementation, thus it would result in an error in such instances. I would like to clarify is this considered as a feature flaw, or can we treat this as a functionality bug.

If it is a feature flaw, then would it be best to clearly the definition of this parameter in the UG and add this edge case as a "Planned Enhancement"? Thank you!

**Comment by adammangzijun** [comment]
Hi, this is one of ur senior from previous batch.

From my past experience, I would classify this as a feature flaw. And yes, I think the best way to do it is to clearly state it in your UG/DG.

**Comment by damithc** [comment]
> Certain edge cases such as `ADDRESS` with `@` character was not thought of during implementation, thus it would result in an error in such instances.

@Javiery3889 What happens exactly in this case? does the application crash, reject with error message, store wrong values, etc.

**Comment by Javiery3889** [comment]
Thank you for your replies Prof @damithc and @adammangzijun, the application rejects with an error message in this case.

**Comment by damithc** [comment]
> Thank you for your replies Prof @damithc and @adammangzijun, the application rejects with an error message in this case.

I see. In that case, as you suggested, specify this limitation clearly in the UG and list it as a planned enhancement.

**Comment by Javiery3889** [comment]
@damithc Thanks Prof for your comments, will be closing this issue.
