### ISSUE TITLE
Difference between "Must fix" and "Good to fix" bugs

### ISSUE THREAD

**Issue by Javiery3889** [nus-cs2103-AY2324S2/forum#693]
Hi, I would just like to clarify the difference between the two types of the bugs since bugs usually fall under must fix?

**Comment by damithc** [comment]
@Javiery3889 Yes, it is ideal to fix _all_ bugs but if there is not enough time, you'll have to choose some over the others. In any case, it is better to start with higher priority bugs first. So, categorizing as must-fix and good-to-fix give you some kind of prioritization. Where you draw the line between the two is up to you. You can also use a different scheme e.g., high/medium/low-priority

**Comment by Javiery3889** [comment]
Ok thanks Prof
