### ISSUE TITLE
Are we allowed to standardize terms used in the error message?

### ISSUE THREAD

**Issue by ryanlimdx** [nus-cs2103-AY2324S2/forum#695]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/91833948/250d285f-1dc3-411b-8a3f-78fc78195df1)

Hi! Our team has a bug where we made a typo as 'Person' instead of 'Patient' in some of the error messages. Will we be allowed to change the term from person to patient to standardize the output? Thank you!

**Comment by damithc** [comment]
@ryanlimdx Standardizing is considered an enhancement, not a bug fix. Is there a possibility that using `person` instead of `patient` mislead/hinder the user?

**Comment by ryanlimdx** [comment]
Ah I see. Thanks prof!
