### ISSUE TITLE
Giving Credit for AI Help

### ISSUE THREAD

**Issue by drustanyjt** [nus-cs2103-AY2324S2/forum#696]
I have been using CoPilot within IntelliJ for all of the tP (getting good at generating CoPilot code feels like a useful skill in and of itself). Usually once I think of how I want a feature to be implemented, I would let CoPilot generate a majority of the important skeleton code (for a new class for example), and then change lower level details to match the design patterns I had in mind.

Based on the instructions for declaring code reuse in the website, it seems that the appropriate way to deal with this would be to add a comment above every new class and method I wrote mentioning that CoPilot was a source of inspiration for the code written.

Instead of this, would it be okay to mention that I "had CoPilot assistance for all of the code credited to me" in the README?

**Comment by damithc** [comment]
@drustanyjt Instead of the README, you can make such a declaration in the DG, in the Acknowledgements section. No need to add comment everywhere in the code.

**Comment by drustanyjt** [comment]
Will do, thanks Prof!

**Comment by damithc** [comment]
Thanks for bringing this up @drustanyjt 
I've updated the relevant instructions in the website as well.
