### ISSUE TITLE
Typo in PE Evaluation Instructions

### ISSUE THREAD

**Issue by xiaorui-ui** [nus-cs2103-AY2324S2/forum#698]
Hi team, the information on the course website regarding the PE-D evaluation seem to conflict each other. The following image is displayed in step 4 under "start fixing PED bugs" here: [fix ped bugs](https://nus-cs2103-ay2324s2.github.io/website/schedule/week12/project.html#2-start-fixing-ped-bugs-before-the-tutorial)

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/87259515/29ee4ff4-c507-41da-a4b7-0e44a5be88a6)

However, the evaluation form and evaluation rubric here seems to specify another set(see screenshot below) of correspondance: [ped](https://nus-cs2103-ay2324s2.github.io/website/schedule/week12/project.html#1-attend-the-practical-exam-dry-run-during-the-weekly-briefing-on-fri-apr-5th-counted-for-participation)
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/87259515/5680b8f3-2502-4f79-b43b-a07bc1746645)

May I clarify if the first one is a typo? Thanks in advance!

**Comment by damithc** [comment]
@xiaorui-ui Thanks for this bug report. The table in the first screenshot is outdated. Will update it shortly (to match the second screenshot).

**Comment by damithc** [comment]
Fixed.
