### ISSUE TITLE
Known Issues vs Planned Enhancements

### ISSUE THREAD

**Issue by dillontkh** [nus-cs2103-AY2324S2/forum#699]
Is there a standard for which type of issues to place in the UG's "Known Issues" section vs the DG's "Planned Enhancements"?

**Comment by damithc** [comment]
@dillontkh Good question.

DG's "Planned Enhancements" are immune from PE bug reporting. It's mostly for grading purposes (i.e., a course-specific item); not something you see often in real DGs.

UG's "Known Issues" is a way to caution users about limitations of the app. It is not course-specific but a normal thing one does in a UG. In terms of grading, informing users of an issue can reduce the severity of the issue but they are not totally immune from bug reporting.

There is no limit to how many known issues you can list in the UG, but listing many will put the product in a negative light. 

You can list things in both.

**Comment by dillontkh** [comment]
Understood, thanks prof!
