### ISSUE TITLE
[Question] [Quiz] When is the early submission period of Week 1 pre-req quiz 

### ISSUE THREAD

**Issue by camille-readbean** [nus-cs2103-AY2324S2/forum#7]
Hi I would like to ask is the Week 1 Quiz part of the participation marks and whether early submission applies for it, if so when is the "early" submission period?

https://canvas.nus.edu.sg/courses/56105/quizzes/31635

Thank you kind forum helpers

**Comment by damithc** [comment]
@camille-readbean The early submission bonus applies from week 2 onwards. It doesn't apply to the week 1 quiz.

**Comment by camille-readbean** [comment]
> @camille-readbean The early submission bonus applies from week 2 onwards. It doesn't apply to the week 1 quiz.

Thanks Prof! Will close the issue, updated the typo in my title as well.
