### ISSUE TITLE
Having an error with Automated Text UI Testing

### ISSUE THREAD

**Issue by TheodoreKooo** [nus-cs2103-AY2324S2/forum#70]
Hello, i am trying out the Automated Text UI Testing. I am on macOS and am getting the error runtest.sh: line 27: dos2unix: command not found.

Also, how should i present my input and outputs? e.g. should my input be "bye\n" instead of bye? 

Thanks

**Comment by E0735389** [comment]
Duplicate of #69

**Comment by E0735389** [comment]
Refer to the linked issue for how to install the program on Mac.

**Comment by bgopi23** [comment]
brew install dos2unix

i used System.out.print(...) instead of System.out.println(...) so i dont get an extra empty line when my chatbot sends the terminating message (bye)

**Comment by damithc** [comment]
@TheodoreKooo Is this issue resolved now?

**Comment by neyapraveen** [comment]
Hi @TheodoreKooo, if the issue is resolved do remember to close this issue :)
