### ISSUE TITLE
Clarification on UI fix

### ISSUE THREAD

**Issue by ziyang27** [nus-cs2103-AY2324S2/forum#700]
Dear Prof, TAs, and friends,

may I ask if I am allowed to edit my UI a little to wrap the text? I believe it is currently hindering normal usage, referencing the FAQ under the feature freeze section on the course website:
<img width="304" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/122247192/e0344158-aed3-400a-9f62-75eaf5cd3763">

Currently, if a name is too long and still valid, it will be cut off from the panel and **there is no other way to view it, even after changing the window size.**
<img width="153" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/122247192/d0167b4d-28b1-42ce-8ea2-0dd7b1f16c53">
The same thing is happening with the address field, entering a long but valid address will cause the address to be cut off.

Thus, may I ask if it is okay for me to just enable wrapping for these two fields specifically to enable the user to view them? Thank you in advance 😄

**Comment by damithc** [comment]
@ziyang27 Yes, if there is no other way for the user to view that information.

**Comment by ziyang27** [comment]
Dear Prof @damithc , thank you so much 👍
