### ISSUE TITLE
How do i add a SD frame over my sequence diagram?

### ISSUE THREAD

**Issue by UdhayaShan1** [nus-cs2103-AY2324S2/forum#702]
I have something like this to abstract the model interactions

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39399745/609c5364-2664-401b-bfd6-8c73c31f271c)

But i cant rly find a way to add a `sd` notation to put over my below diagram to link to this 

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39399745/0afc2645-efa4-4bb9-81a0-7443f3bd6afa)

To get something like this

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39399745/a87b7f3f-ebd1-4420-a887-ccb7fd1e8348)

Any help appreciated

**Comment by E0735389** [comment]
Looks like https://github.com/nus-cs2103-AY2223S1/forum/issues/384 has an answer.

**Comment by damithc** [comment]
> Looks like [nus-cs2103-AY2223S1/forum#384](https://github.com/nus-cs2103-AY2223S1/forum/issues/384) has an answer.

Thanks for sharing this @E0735389 
@UdhayaShan1 the solution given there should be close enough.

**Comment by UdhayaShan1** [comment]
Thanks for the help! @E0735389 

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39399745/4596585f-be3a-4c37-9a6b-63b652b6d590)


This is the best we can do i guess
