### ISSUE TITLE
Clarification of UI bug

### ISSUE THREAD

**Issue by Javiery3889** [nus-cs2103-AY2324S2/forum#704]
Hi, our team would like to ask if the following bug report will be considered a bug w.r.t [Q8](https://nus-cs2103-ay2324s2.github.io/website/schedule/week12/project.html#:~:text=of%20a%20feature%3F-,Q8,-%3A%20A%20UI) of the bugs FAQ:
>  Only if the behavior hinders normal usage i.e., the user not being able to see the full text in any way can be considered an 'incorrect' behavior, and hence, a bug.

The tester has reported that the help window is too large and cannot be resized, causing the window navigation buttons to not appear on the tester's screen (i.e. cannot close/minimise window). Would this translate to a bug as it hinders normal usage (potential bug fix would be to set the window to resizable), or would it be considered as feature flaw?

Thanks!

**Comment by damithc** [comment]
@Javiery3889 I think this problem is severe enough to hinder normal usage, and can be fixed. 
To keep within the spirit of the feature freeze, go for the fix that requires the least code change.

**Comment by Javiery3889** [comment]
Noted and thanks Prof @damithc for the insights!

**Comment by KohGuanZeh** [comment]
@damithc Hi Prof, I would like to follow up on this question as we are still unsure of the best way to fix the bug for v1.4

1. Should we go with the minimum code change, or are we allowed to implement longer code changes but retains our previous behavior as much as possible. To fix the bug, we can simply set the height of the window to be the max screen height and implement a scroll pane to ensure all commands are viewable. However, this would change the behavior for some other machines that did not face this issue as now their help window will fit the height of their screen. Is it acceptable to add more code to only change the size if it exceeds the max screen height?

2. Is it right to say that making our help window resizable is violating the feature freeze if our previous help window did not initially have this feature? Given that it is difficult to test whether our planned fix would work, we were discussing if we should allow the window to be resizable in the case where there is still issues with reading the text and the users can at the very least resize the window to fit their screen.

Thanks!

**Comment by damithc** [comment]
@KohGuanZeh 

> 1. Is it acceptable to add more code to only change the size if it exceeds the max screen height?

Yes, I think this is reasonable.


> 2\. Is it right to say that making our help window resizable is violating the feature freeze if our previous help window did not initially have this feature?

Yes, this would be an enhancement. But if you can reliably reproduce a case where the user can't read the text when the window is not resizable, you can self-report it as a bug (with enough details so that others can reproduce it as well) and fix it.

**Comment by KohGuanZeh** [comment]
Thanks for the clarification prof!
