### ISSUE TITLE
Error when running gradlew clean build

### ISSUE THREAD

**Issue by NeoHW** [nus-cs2103-AY2324S2/forum#705]
When running gradlew clean build locally, it passes everything except `:test` part.

![Screenshot 2024-04-08 at 1 53 36 PM](https://github.com/nus-cs2103-AY2324S2/forum/assets/94470439/963a13b2-9e14-44e6-a29a-45f84c94a251)

It has the following output message:
```
Execution failed for task ':test'.
> Process 'Gradle Test Executor 1' finished with non-zero exit value 1
```

Running with `--info`, `--scan` does not yield additional insights. 
With `--scan`, it has a series of the above message, except its Gradle Test Executor from 1 to 249 in running sequence. 
It also has an additional 
```
agent library failed to init: instrument
Error occurred during initialization of VM
```

I have tried `./gradlew --stop` according to https://stackoverflow.com/questions/23523831/gradle-build-fail-process-gradle-test-executor-1-finished-with-non-zero-exit but to no avail,

any insights would be greatly appreciated!

**Comment by damithc** [comment]
@NeoHW While waiting for inputs from others, here are some things you can try:
* Push the code to a branch/PR and see if CI passes on it
* If using Intellij, try these 'common remedies' one-at-a-time in this order:
  * Run `./gradlew clean build`
  * Choose `File` -> `Invalidate caches`
  * Close Intellij -> Delete the `.idea` folder -> Re open the project in Intellij
  * Clone the fork to a different location and open the project in Intellij again to get a fresh start without losing changes you did so far.

**Comment by NeoHW** [comment]
@damithc CI passes , so this is a local issue.
I have tried all the following suggestions:
* Run `./gradlew clean build`
* Choose `File` -> `Invalidate caches`
* Close Intellij -> Delete the `.idea` folder -> Re open the project in Intellij
* Clone the fork to a different location and open the project in Intellij again to get a fresh start without losing changes you did so far.

But unfortunately, none of them works for me

edit: My current machine is running on the M2 chip, and on java 11

**Comment by damithc** [comment]
@NeoHW perhaps share the link to your PR so that others can try to replicate it? Also, does this happen in the master branch as well?

**Comment by NeoHW** [comment]
This is the latest PR: https://github.com/AY2324S2-CS2103-F09-2/tp/pull/236
it passes CI. 

Yes, it is happening on both master branch and also on feature branches

**Comment by damithc** [comment]
@NeoHW When did this start happening? That might help you detect what caused the problem to appear.
Also, try running tests in a terminal using `.gradlew clean test` (outside of Intellij). Also run `java -version` to confirm the correct JDK is being used by the terminal.

**Comment by NeoHW** [comment]
It started happening today. No noticeable changes, I pulled in 2 simple commits from the upstream repo and created a branch to work on my feature fixes.
This problem then started.

I tried `./gradlew clean test` and `./gradlew clean build` in the IntelliJ terminal just now, and it led to the same error.

However, upon running tests both commands in a terminal **(outside of Intellij)**, I am able to get a build successfully message.

This means there is something wrong with Intellij....

**Comment by E0735389** [comment]
Might be some environment difference e.g. if the stack size in IntelliJ is set smaller than that outside, and the new change happens to make testing use more stack space, then it would crash inside IntelliJ.

But in any case, it would be difficult to guess given the situation.
