### ISSUE TITLE
Clarification on what is considered a Feature Flaw

### ISSUE THREAD

**Issue by Dethada** [nus-cs2103-AY2324S2/forum#706]
This is stated on the course website. I would like to clarify which of the cases below are valid feature flaws.

> Do not post suggestions but if the product is missing a critical functionality that makes the product less useful to the intended user,
> it can be reported as a bug of type Type.FeatureFlaw

Let feature X be a must have feature.
Let feature Y be a nice to have feature.

- Case 1: The application has feature X, however it would be a quality of life improvement if enhancement/feature Z is implemented. Can we report the absence of Z as a feature flaw?
- Case 2: If the application does not support feature Y. Can we report the lack of support for Y as a feature flaw?
- Case 3: If the application does not support feature X. I think in this case the lack of support for X is definitely a feature flaw.

**Comment by damithc** [comment]
@Dethada I'm assuming your questions are about the upcoming PE.

Answers: yes, yes, and yes.

But note that severity will vary across the three cases, and depends on exact features.

**Comment by Dethada** [comment]
Yeap, my question is about the upcoming PE. Alright thanks prof
