### ISSUE TITLE
Appendix: Planned Enhancements in UG or DG?

### ISSUE THREAD

**Issue by ThatGirlJam** [nus-cs2103-AY2324S2/forum#708]
If we want to add an appendix for planned enhancements, is it meant to be in the DG? Or perhaps could we put a version of this in the UG as well?

**Comment by damithc** [comment]
@ThatGirlJam In the DG, as per [here](https://nus-cs2103-ay2324s2.github.io/website/schedule/week12/project.html#:~:text=Using%20%27Planned%20Enhancements%27%20DG%20section%20to%20counter%20known%20feature%20flaws)

Also relevant: https://github.com/nus-cs2103-AY2324S2/forum/issues/699

**Comment by ThatGirlJam** [comment]
I see, thank you so much!
