### ISSUE TITLE
Feature freeze clarification regarding bug

### ISSUE THREAD

**Issue by jannaleong** [nus-cs2103-AY2324S2/forum#709]
There is a bug in 2 out of 15 of my groups commands where an exception is not thrown when a duplicate field is entered. This causes the feature to behave incorrectly, only considering the last field entered.

My group had already foreseen that duplicate fields in the command would cause issues and have already created a function to handle this. This function will detect duplicate fields in the commands and throw an error if there was a duplicate field.

However, for 2 of the commands, we had forgotten to call this function in our error handling. Thus the intended behaviour of throwing an error for duplicate fields was not displayed for these 2 commands. 

The fix for this bug, it is only a 1 line fix per command, to call the shared function that has already been created.

However, we wanted to check that we are allowed to do without violating the feature freeze.

We would really appreciate your clarification on this issue.

**Comment by damithc** [comment]
@jannaleong While this sounds like a genuine oversight, as the current behavior is not strictly incorrect, I'm afraid it doesn't pass the eligibility test for 'allowed' during the feature freeze. 

On a somewhat related note, this behavior used to be a deliberate optimization in an earlier version of AB3. That is, this behavior allows users to quickly retype a field they mistyped earlier in the command, which may be faster than navigating back to the place where the typo is and correcting it. So, this 'feature' was provided as a way for users to rectify mistakes faster. So, if you feel this feature can be useful for that purpose, you can present it as an 'experimental' feature enabled only for a few selected commands.

**Comment by jannaleong** [comment]
Understood :) Instead of reverting the entire commit which also encompassed other changes, is it alright if i just remove the 2 additional lines that corrected this feature flaw. Thank you for all the help!!

**Comment by damithc** [comment]
> Understood :) Instead of reverting the entire commit which also encompassed other changes, is it alright if i just remove the 2 additional lines that corrected this feature flaw. Thank you for all the help!!

@jannaleong Sure. 
Side note: this is why each commit should contain no more than one standalone change  :-)

**Comment by jannaleong** [comment]
Noted !! will be more careful of this in future projectss
