### ISSUE TITLE
Automated Text UI Testing - Required to edit both script files?

### ISSUE THREAD

**Issue by RyanNgWH** [nus-cs2103-AY2324S2/forum#71]
I indicated in the pre-course survey that windows is the OS I use most when programming. However, I have since migrated to a Linux based OS and will be using that going forward.

I have updated the `javac` command within the `runtest.sh` file to match my project structure and am using that file for testing. May i know if i am required to modify the `runtest.bat` file and ensure that it works as well?

**Comment by Jerome-j** [comment]
I think the `.bat` file is for Windows users

**Comment by RyanNgWH** [comment]
@Jerome-j @damithc Alright thank you for you help!
