### ISSUE TITLE
Are cosmetic issues in help messages fixable?

### ISSUE THREAD

**Issue by camille-readbean** [nus-cs2103-AY2324S2/forum#710]
Hi Prof, for example are bugs like these "fixable"?

https://github.com/AY2324S2-CS2103T-T17-1/tp/issues/109

or like 
https://github.com/AY2324S2-CS2103T-T17-1/tp/issues/88

these are purely comestic issues
edit:
i.e. are these considered "feature" flaws and not supposed to be fixed?

**Comment by damithc** [comment]
@camille-readbean The given two are typos; while minor, they are errors nevertheless. Can be fixed.
