### ISSUE TITLE
Feature Freeze Clarification

### ISSUE THREAD

**Issue by HusseinSafwan02** [nus-cs2103-AY2324S2/forum#711]
Hi Prof,

My team's intended jar file v1.3.1 unfortunately could not run for the PE dry run, though it seemed to be working when I tested it out locally. Hence the PE dry run testing was done on our released v1.3. Could I ask if it would be considered a violation of the feature freeze if my team were to proceed ahead with v1.3.1 which has some minor features added?

**Comment by damithc** [comment]
@HusseinSafwan02 You may consider v1.3.1 as the one that triggers the feature freeze, as it was released before the PE-D.

**Comment by HusseinSafwan02** [comment]
Alright Prof thank you!
