### ISSUE TITLE
Clarification if enforcing case sensitivity is an enhancement or bug

### ISSUE THREAD

**Issue by yuechen2001** [nus-cs2103-AY2324S2/forum#712]
Hi profs and fellow classmates,

Referring to this issue, 
https://github.com/AY2324S2-CS2103T-T12-1/tp/issues/149

Can I clarify if this is a bug or an enhancement? From my understanding, as per the website: 
"Accepting seemingly 'unsuitable' values for an input (e.g., accepting numbers for a person name, empty value as a parameter):
This is not considered 'incorrect' (giving more freedom to the user is not necessarily incorrect) unless those unsuitable values causes the application to misbehave."
- From this line of argument, it seems that allowing the user to input the same tech stack but in different cases is an enhancement. May I ask if this is the correct understanding, and if so should this be included in the Planned Enhancement section? Thanks in advance!

**Comment by damithc** [comment]
@yuechen2001 Yes, this looks like an enhancement. You can cross-refer Q7 in the FAQ in https://nus-cs2103-ay2324s2.github.io/website/schedule/week12/project.html

**Comment by yuechen2001** [comment]
Thanks prof! Will be closing this issue
