### ISSUE TITLE
Clarification on allowing for special characters in names

### ISSUE THREAD

**Issue by yuechen2001** [nus-cs2103-AY2324S2/forum#713]
With reference to this issue,
https://github.com/AY2324S2-CS2103T-T12-1/tp/issues/154

Will making adjustments to allow for names with special characters be considered an enhancement or bug fix? My understanding would be an enhancement, maybe the user can circumvent this issue (albeit with minor inconveniences) by not entering the special characters / replacing them with another character.

Appreciate any feedback and discussions!

**Comment by damithc** [comment]
@yuechen2001 You are correct 👍. This will be an enhancement.

**Comment by yuechen2001** [comment]
Thanks prof! Will be closing this issue.
