### ISSUE TITLE
Clarification on Case Sensitivity Bugs

### ISSUE THREAD

**Issue by tayziyi** [nus-cs2103-AY2324S2/forum#714]
<img width="802" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/122244694/61a3521d-e52d-4306-8c80-149ffb3083eb">

To replicate:
add n/John Dan p/98765431 e/[joE@g.com.sg](mailto:joE@g.com.sg) a/01/01/2024 a/02/01/2024 t/friends

add n/John Doe p/98765432 e/[joe@g.com.sg](mailto:joe@g.com.sg) a/01/01/2024 a/02/01/2024 t/friends t/owesMon

Expected Behavior: The system should enforce validation to prevent the same email address from being associated with more than one user profiles
Actual Behavior: Actual Behavior: The system allows the same email address to be added to different user profiles without validation

My question is - are all case sensitivity bugs labelled as feature flaw and we should not fix it?

**Comment by damithc** [comment]
> My question is - are all case sensitivity bugs labelled as feature flaw and we should not fix it?

@tayziyi you are correct. Tweaking case sensitivity is to be postponed to a later version.
