### ISSUE TITLE
Is updating the messages shown to the user in the app to match UG allowed?

### ISSUE THREAD

**Issue by jmsandiegoo** [nus-cs2103-AY2324S2/forum#715]
The application is just showing outdated error messages that doesn't include some command arguments specified in the UG. The thing is the application supports all these arguments fully as specified in the UG but I just forgot to update the messages shown to the user.

Here is an example issue:
https://github.com/AY2324S2-CS2103-F09-4/tp/issues/101 

I understand that it's better to update the UG but I feel like I'm removing fully working features I actually spent time working on in the application just because I forgot to specify in the application message feedback. Technically can it considered be a bug as it prevents user from editing some fields?

**Comment by damithc** [comment]
@jmsandiegoo Why is there a `...` here?
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/9ebeddb4-fa9c-44b5-89d7-faea9cfc9da6)

Also, can you confirm the editing of missing parameters (e.g., birthday) was already possible in the v1.3 jar and the only problem was that they are not mentioned in the error message?

**Comment by jmsandiegoo** [comment]
@damithc thank you for the timely response, the `...` here is to specify user can have multiple `i/` parameters. Regarding the missing parameters yes they are already implemented in the v1.3 jar and only the message is the problem.

**Comment by damithc** [comment]
@jmsandiegoo Yes, you can correct this error message to include missing parameters because without them it gives an incorrect instruction to the users.

**Comment by jmsandiegoo** [comment]
Alright thank you prof! @damithc
