### ISSUE TITLE
Clarifications on fixing wrong message shown related bugs

### ISSUE THREAD

**Issue by ys112** [nus-cs2103-AY2324S2/forum#716]
Hi, I have read through the FAQs and would like to seek confirmations whether it being cosmetic or incorrect text if the below 3 bugs can be fixed in v1.4:

1. [Details of bug 1](https://github.com/AY2324S2-CS2103-F15-3/tp/issues/176) : The command error message has a typo showing `import_fileFILE_PATH` instead of `import_file FILE_PATH`, while it has an example command below to show how to use correctly, can I still consider it as incorrect as per Q6 and fix it? 

2. [Details of bug 2](https://github.com/AY2324S2-CS2103-F15-3/tp/issues/151): The dialog window title is showing `help` but the appropiate title is `Email template`, can this consider as incorrect text and not cosmetic?

3. [Details of bug 3](https://github.com/AY2324S2-CS2103-F15-3/tp/issues/149): When the user clicks on import in the import dialog window without selecting file, the main app does not show any error message, while it does not cause the app to fail and technically just cause confusion / inconvenience to user as per Q1, would like to confirm that it still takes precedence under the "user action fails silently" and could be fixed to just show an error message.

 <br>

**For reference with the aforementioned issues,**  

**Q1:**
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/34358414/1aa07842-5add-43a8-9ade-9d47ea7dda41)

**Q6:**
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/34358414/3dbc4576-47ef-4ff8-82ec-dff5a3062d81)

**Comment by damithc** [comment]
@ys112 All three are allowed to be fixed.
