### ISSUE TITLE
Writing UG for CS2101

### ISSUE THREAD

**Issue by cheahTJ** [nus-cs2103-AY2324S2/forum#717]
Hi all, understand that all work will stop for CS2103 on Thursday but I was just wondering if we are able to continue using github as our code base to update our UG for CS2101 as the deadline for UG's submission is next Monday

**Comment by cheahTJ** [comment]
Additionally, can I also double confirm when is the hard deadline for fixing all the PED bugs?

**Comment by cheahTJ** [comment]
Hi, I just saw the hard deadline its on 15 Apr, did not realise it until I checked the agenda for next week. This thread is currently answered.

**Comment by damithc** [comment]
@cheahTJ Just submit the same UG for both courses. Creating two versions is unnecessary work. Beautifying the UG does not get extra marks as the we have an agreement with CS2101 that any further beatification beyond what AB3 UG has should not be given any extra credit.

**Comment by cheahTJ** [comment]
Got it, thank you prof!
