### ISSUE TITLE
Are we allowed to fix this warning message bug?

### ISSUE THREAD

**Issue by Ella-e** [nus-cs2103-AY2324S2/forum#718]
Is it considered a bug to be fixed in v1.4 because "ic/NRIC (optional but at least specify one)" is a wrong instruction? If user follow this instruction and leave the ic/ field empty would make the command fail.
<img width="899" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/60089102/527c2fb2-b0f2-4381-bb9d-94f00c1a87cd">

**Comment by damithc** [comment]
@Ella-e What is the proposed 'correct' version of the message?

**Comment by Ella-e** [comment]
It is supposed to be like that.
<img width="506" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/60089102/bf759787-5ab8-45f0-96c5-a79b6b19c370">

**Comment by damithc** [comment]
@Ella-e Yes, this can be fixed as the current one gives the wrong instructions to the user.

**Comment by Ella-e** [comment]
Okay! Thank you very much Prof!
