### ISSUE TITLE
Minor Typo in Admin Info Page

### ISSUE THREAD

**Issue by jieqiboh** [nus-cs2103-AY2324S2/forum#72]
In the [Admin Info](https://nus-cs2103-ay2324s2.github.io/website/admin/peerEvaluations.html) page, under the Admin Tools => TEAMMATES dropdown

In

> When the first feedback session is open on TEAMMATES, you will receive an eamil from TEAMMATES.

It should be,

> When the first feedback session is open on TEAMMATES, you will receive an email from TEAMMATES.

Below is a screenshot for reference:
<img width="785" alt="Screenshot 2024-01-25 at 11 48 23 AM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/93033071/022c7c19-92b7-4bd2-956f-70783e73e509">

**Comment by damithc** [comment]
Thanks for spotting/reporting this, @jieqiboh 
Fixed.
