### ISSUE TITLE
Suggestion: make a quiz for distinguishing bug and feature flaw

### ISSUE THREAD

**Issue by E0735389** [nus-cs2103-AY2324S2/forum#720]
Maybe as a graded component? So that the students can 

* get practice doing quiz, and
* prof can hopefully reduce the number of questions to answer on the forum.

On the other hand maybe this is slightly "subjective", so ungraded quiz (i.e. one placed in the textbook itself) may be better.

**Comment by baskargopinath** [comment]
i think an ungraded quiz of this before the actual pe would be great

**Comment by damithc** [comment]
@E0735389 Good suggestion.
We already have such an ungraded quiz to prepare students for the PE (covering how to decide the bug type but also the severity), but at the moment we don't have one that targets PE-D bug processing. For the latter, what we have (for now) is the FAQ in https://nus-cs2103-ay2324s2.github.io/website/schedule/week12/project.html
