### ISSUE TITLE
Clarification for feature freeze: Grammatical errors in output messages, sample data, integer overflow

### ISSUE THREAD

**Issue by billyhoce** [nus-cs2103-AY2324S2/forum#722]
## Grammatical errors in output messages for certain inputs
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/84035425/8a340f83-997e-4090-972e-015a2df97868)
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/84035425/d8d1ca40-9ea6-4ff8-86c2-c79ca0f6bfcd)
In the first image, the message should be "Added 1 point to Alex Yeoh". Can this be fixed in v1.4?

## Editing sample data to be more like real-use
Our application is a loyalty program, it stores orders and points awarded for making these orders. Our sample data currently does not make sense (i.e Alex made an order for cupcakes, and should have been awarded 200 points, but he has 0 points.)

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/84035425/985492b0-dda0-4df3-86d4-4f5221ea9b82)

Can we change Alex's points to reflect the correct amount which is 200

## Fixing Integer overflow
Currently, if an entry in our address book has `2147483647 points`, trying to add 1 point to the member will result in no change to points, but also no error/success message. On the other hand, another field our app stores in the same situation results in the field changing from `2147483647` to `-2147483648`. Can we introduce a maximum points (i.e 2,000,000,000) to prevent these from happening? Or can we only list this behaviour in the UG and park this under planned enhancements?

## Side question
Extreme values unlikely to appear with normal use, such as a name that is 300 characters long, cannot be fully shown in the UI in any way. Would this be considered a feature flaw in the PE?

**Comment by damithc** [comment]
@billyhoce 

1. You may change it as `point(s)` for all cases.
2. As the current points is incorrect, you can change the points (but no other changes)
3. This does not warrant a code change during the feature freeze. State in the UG the 'safe' range of values the application can operate within
4.  The following applies.
    ![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/91a43173-15b5-4a03-9a62-4c0589e09607)

**Comment by billyhoce** [comment]
Thank you prof!

**Comment by billyhoce** [comment]
Sorry Prof @damithc ,

Just one more question about sample data. Our application also contains a catalogue of items in the shop. The sample data as seen in the screenshot in the original post has Alex ordering a "cupcake". But the sample catalogue does not contain "cupcake". Can we add that in? Sorry for the trouble!

**Comment by damithc** [comment]
> Just one more question about sample data. Our application also contains a catalogue of items in the shop. The sample data as seen in the screenshot in the original post has Alex ordering a "cupcake". But the sample catalogue does not contain "cupcake". Can we add that in? Sorry for the trouble!

@billyhoce OK. But also consider removing that order entirely, as it seems to have multiple problems -- take whichever the option that requires fewer changes to the data file.
