### ISSUE TITLE
Clarification on feature freeze for error message

### ISSUE THREAD

**Issue by yleeyilin** [nus-cs2103-AY2324S2/forum#723]
Hi, I wanted to clarify if add a different error check to correct this behaviour falls under feature flaw or functionality bug. Any insights would be greatly appreciated! 
<img width="391" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/116061001/4d94f63f-1206-4644-b7d5-bc553a4a8c95">

**Comment by damithc** [comment]
@yleeyilin Why is the current error message incorrect, and what should be the correct error message?

Also note the Q6 of the FAQ in https://nus-cs2103-ay2324s2.github.io/website/schedule/week12/project.html

**Comment by yleeyilin** [comment]
Hi Prof, the current error message should not be saying that the field is empty since it is technically not. Will fixing this error message to detect this be considered a functionality bug? Any clarifications on this will be greatly appreciated. Thank you!

**Comment by damithc** [comment]
@yleeyilin In this case you can expand the scope of the message to cover this problem as well e.g., `field is empty or invalid`. Detecting this specific error and giving a more specific error message would be an enhancement, which is not allowed during the feature freeze.

**Comment by yleeyilin** [comment]
Oh okay thank you!
