### ISSUE TITLE
Query regarding "Planned Enhancement" section

### ISSUE THREAD

**Issue by Javiery3889** [nus-cs2103-AY2324S2/forum#725]
Hi,

Our team has a few fields (e.g. name, remark) that disallow certain characters e.g. `/` that makes the command harder to parse, however this has inevitably introduced feature flaws due to the inflexibility of the user input validation.

We wish to address this issue by including it the "Planned Enchancement" section of our DG, however we are wondering if we are allowed to combine all affected fields into a single enhancement. We would also like to ask how specific must we go into the implementation for this enhancement,  i.e. would "Allow users to enter special characters into these fields" be sufficient for our proposed solution?

Thanks!

**Comment by damithc** [comment]
@Javiery3889 Our rule is that if fixing one fixes the other automatically, they can be considered as one enhancement. Otherwise they should be two.

**Comment by Javiery3889** [comment]
Hi Prof @damithc , thank you for your reply. We would like to ask a follow up question whether the fix here refers to changes in the code base?

For example, if we would like to add more `DateTime` and `Date` formats as one of our "Planned Enhancement", can we combine the `Date` and `DateTime` enhancements as the `Date` and `DateTime` are **tied together implicitly**.  For instance, `DateTime` is used for our schedule command which is to schedule meeting at a certain datetime. Our find command allows us to find a meeting by a specific date. If we change the format for `DateTime` to relax the inputs, can we add the changing of the `Date` format together as one enhancement?

On a seperate note, would it be considered if `NotInScope` if we have clearly stated the `Date` and `DateTime` format restriction in our UG but a tester later reports to lack of multiple `Date` and `DateTime` formats during PE? i.e. our application only support `dd-MM-yyyy` format but tester wants `d-M-yyyy` format to be accepted as well.

Thank you!

**Comment by damithc** [comment]
> For example, if we would like to add more `DateTime` and `Date` formats as one of our "Planned Enhancement", can we combine the `Date` and `DateTime` enhancements as they belong in the same `.java` file and title it "Improve flexibility of DateTime and Date formats"? Or must we seperate `Date` and `DateTime` enhancement?

@Javiery3889 Hmm... this is a tough one. I guess if you can convince the PE tester that your proposed implementation will add support for multiple date formats, it should be fine to clump them as one. You might need to give some technical details of the implementation. Having all the code in one file is not sufficient nor required but you need to show that the natural way to implement this is as one shot, not as two separate features.

> On a seperate note, would it be considered if `NotInScope` if we have clearly stated the `Date` and `DateTime` format restriction in our UG but a tester later reports to lack of multiple `Date` and `DateTime` formats during PE? i.e. our application only support `dd-MM-yyyy` format but tester wants `d-M-yyyy` format to be accepted as well.

This one we need to wait till the PE to discuss. Related: Q14 in this FAQ https://nus-cs2103-ay2324s2.github.io/website/schedule/week12/project.html
Also see [this](https://nus-cs2103-ay2324s2.github.io/website/admin/tp-pe.html#:~:text=How%20to%20prove%20that%20something%20is%20response.NotInScope).
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/d86a5d84-6d28-46b1-aa1d-960441d4a65a)
