### ISSUE TITLE
Query About Bug Fix

### ISSUE THREAD

**Issue by itstrueitstrueitsrealitsreal** [nus-cs2103-AY2324S2/forum#726]
<img width="1055" alt="Screenshot 2024-04-09 at 2 23 40 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/120318851/e8c9edb7-a0fc-4653-924f-ef9d7213e0d7">

Hi, as you can tell from our screenshot, our group got a `severity.High` bug regarding the line breaks because the command to run the `.jar` file was too long.

I wanted to ask if such a case qualifies as a bug should it be reported as one for our actual release. Will it cause issues for our target audience, who are specified to be "CLI users"?

Thanks for the help!

**Comment by damithc** [comment]
@itstrueitstrueitsrealitsreal In the PE, the tester and the dev team are expected to attempt to reach a decision before teaching team steps in. Therefore, our policy is not to judge potential PE issues in advance, so as not to preempt the PE process.
 
As for this specific case, looks like it is easily remedied by adding a `<br>` to the line or giving the command below the sentence (as a single line)?

**Comment by itstrueitstrueitsrealitsreal** [comment]
Alright, thanks for the clarification and the advice!
