### ISSUE TITLE
Query Regarding Incorrect Error Messages

### ISSUE THREAD

**Issue by itstrueitstrueitsrealitsreal** [nus-cs2103-AY2324S2/forum#727]
In the same vein as #659, is changing the error message to be more general to cover more cases allowed? Q6 of the FAQ says that making the message more specific is not allowed, but what about the reverse if the current error is incorrect?
<img width="822" alt="Screenshot 2024-04-09 at 2 35 06 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/120318851/2d182b01-5c18-4853-87d5-77053f87abac">

**Comment by damithc** [comment]
@itstrueitstrueitsrealitsreal Yes. If the error can happen due to X, Y, and Z but the error message only covers X and Y, you may add `or Z` to the error message, or state the error message in a more general way e.g., `There is a problem in the parameters`

**Comment by itstrueitstrueitsrealitsreal** [comment]
Alright, thanks for the advice! Closing the issue.
