### ISSUE TITLE
Do we need to specify tagging message when creating tag?

### ISSUE THREAD

**Issue by PallonCX** [nus-cs2103-AY2324S2/forum#73]
Here is a screen-captured part from the given resource: https://nus-cs2103-ay2324s2.github.io/website/schedule/week2/topics.html

<img width="751" alt="Screenshot 2024-01-25 at 3 45 02 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/102943362/e832f6c3-9ed2-4550-b629-86bd0c9f511e">

I tried the given command, but it requires me to give a tagging message. After further research on https://git-scm.com/book/en/v2/Git-Basics-Tagging, looks like we can either make **lightweight** or **annotated** tags.

For **lightweight** tags:
git tag {tagname}

For **annotated** tags:
git tag -a {tagname} -m {tagging message}

I raise this issue to ask whether we need to specify tagging message when creating tag, and also highlight the attention of the teaching team if any rectification on the given material is required.

**Comment by E0735389** [comment]
There's a tip in #3. I think you can add a message if deemed descriptive, but it's not enforced.

**Comment by damithc** [comment]
@PallonCX lightweight tags are good enough for our purpose. So, you can omit the `-a` flag so that Git doesn't prompt you for a message.
```
git tag v1.0
```
I'll update the textbook section accordingly. Thanks for bringing this up.
@E0735389 Thanks for your inputs too.
