### ISSUE TITLE
Does changing code to prevent a crash violate feature freeze?

### ISSUE THREAD

**Issue by RingoftheKing** [nus-cs2103-AY2324S2/forum#730]
So for my tp, currently attempting to type in a command, with prefixes that are empty will trigger an `illegalArgumentException`,
which then causes the app to stop functioning normally (i.e. future typed commands always show an empty list).

Is it OK to introduce code that performs a check on an empty prefix AND include a NEW error message to stop the app from silently failing by telling them a prefix is empty? 

(the user can't see that the app has stopped due to `illegalArgumentException` but rather sees that the app doesn't respond below)

**Old behaviour**
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/90739493/4cd27176-31c6-40ad-9300-0022af3572a9)

**Proposed new behaviour**
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/90739493/8372678f-524b-4ce0-ae68-4b112ac5ad37)

**Comment by damithc** [comment]
@RingoftheKing Yes, this is a serious bug that needs fixing in v1.4
