### ISSUE TITLE
Permitted to bring back additional code that got somehow deleted in earlier commits?

### ISSUE THREAD

**Issue by yashpola** [nus-cs2103-AY2324S2/forum#732]
Hi, we had an extra validation for a user input that got somehow deleted through some other commits right before PE-D. Would it be a violation of v1.4 if we bring this back now? We can show the version of the repo at v1.3 to prove that the code had existed before but was unwittingly deleted as part of some commits

**Comment by damithc** [comment]
@yashpola Please send me (or post here) the relevant evidence.

**Comment by yashpola** [comment]
@damithc 

Hi prof, 

<img width="1153" alt="Screenshot 2024-04-09 at 8 36 10 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/105275750/ce470e0b-7e04-4f3b-baac-72d78f1312c8">
<br>
<br>
The check enclosed in red is what I'm referring to, from a commit 2 weeks ago which is sufficiently before PE-D. The commit hash is visible as well for cross-reference

**Comment by damithc** [comment]
@yashpola This commit (as per the warning at the top) is not part of your repo. Can you share the link to the commit itself, in your tP repo? Also, any idea why it got left out of v1.3 later?

**Comment by yashpola** [comment]
@damithc 
Hi prof [here's the link](https://github.com/nus-cs2103-AY2324S2/tp/commit/ceeb86be11a2752735044c829881168f7a379ad6#diff-9475bd41db35dc30c39c9439ee55151cdc42afa64be2eaf6d7b81a2d55c0a585) to the commit to our TP repo. The warning is likely since this original commit was to a branch in my fork of our team repo which was later merged to the team repo

Just to clarify, this is not the commit in which this line of code was first added. It's just showing that it was there during/before v1.3 

We suspect it got left out because we refactored the `execute` method of the `AddInterviewCommand` since it was too long, and when abstracting out multiple lines of code to become new methods, this line got left out since it is its own logical piece.

**Comment by damithc** [comment]
@yashpola Yes, you can add back this check.

**Comment by yashpola** [comment]
@damithc 
Thanks prof!
