### ISSUE TITLE
Clarification on if this violates feature freeze

### ISSUE THREAD

**Issue by cheahTJ** [nus-cs2103-AY2324S2/forum#733]
Hi. may I check if we amend and write in UG (we initially did not cater for wrong domain name in `email` field) to inform users to key the  domain name  correctly, and currently we HAVE NOT implemented a method to detect erroneous domain like for `email` field, can that be considered as fixing a bug and DOES NOT violate the feature freeze?

**Comment by damithc** [comment]
@cheahTJ This is just a change to the UG, right? Any UG change is allowed in v1.4

**Comment by cheahTJ** [comment]
Hi prof @damithc to answer your question, nope its not just changes to the UG because if we add in the UG "`email` field only accepts certain domain name", but if the user keys an inaccurate domain name, my app will still perform the command as it was not implemented earlier to detect incorrect domain name. So this is considered a feature flaw I suppose so are we able to amend our code to ensure that domain name HAVE to be correct?

**Comment by damithc** [comment]
I see. In that case, Q5 of the FAQ in https://nus-cs2103-ay2324s2.github.io/website/schedule/week12/project.html applies.

Doing some kind of validation for the email is considered an enhancement (hence, not allowed in v1.4).

**Comment by cheahTJ** [comment]
Thank you for the clarification prof! So if that is the case, setting our 'defence' by asking users to input the correct email domain in our UG would suffice right since we are not allowed to have these enhancements?

**Comment by damithc** [comment]
> So if that is the case, setting our 'defence' by asking users to input the correct email domain in our UG would suffice right since we are not allowed to have these enhancements?

@cheahTJ yes, that's what can be allowed in this version. Like any other enhancement not allowed in v1.4, tester can still report them as feature flaws, unless listed among planned enhancement. Keeping the user informed via the UG lowers the severity of the flaw. More importantly, if the feature flaw is later decided as [NotInScope](https://nus-cs2103-ay2324s2.github.io/website/admin/tp-pe.html#:~:text=How%20to%20prove%20that%20something%20is%20response.NotInScope), the team will not be penalized at all.

**Comment by cheahTJ** [comment]
Got it prof, thank you!
