### ISSUE TITLE
Class Diagram Dependency clarification

### ISSUE THREAD

**Issue by tankh99** [nus-cs2103-AY2324S2/forum#736]
If a class A has a function with a return type B only, and no other references to B, does it then have a dependency on B?

E.g.

```java
class A {
  B foo() {...}
}

class B { }
```

**Comment by baskargopinath** [comment]
i think yes? because without the existence of B, Class A wont compile

**Comment by UdhayaShan1** [comment]
On the other hand, I dont really think so, it merely returns B, it does not _make use of B_ in its code so any changes of B does not technically affect A

**Comment by tankh99** [comment]
> On the other hand, I dont really think so, it merely returns B, it does not _make use of B_ in its code so any changes of B does not technically affect A

Since the function in A has to construct B somehow, if B changes its constructor params, wouldn't A then need to change accordingly? In this way, would it not be a dependency?

**Comment by baskargopinath** [comment]
@UdhayaShan1 what if b doesnt exist? how is A going to compile

**Comment by tankh99** [comment]
I'm going to assume that this would imply that there A has a dependency on B here

**Comment by damithc** [comment]
> I'm going to assume that this would imply that there A has a dependency on B here

@tankh99 that is correct.
