### ISSUE TITLE
Is the object date and (always zero) time being displayed instead of just the date a bug?

### ISSUE THREAD

**Issue by kjw142857** [nus-cs2103-AY2324S2/forum#737]
Hi Prof @damithc , currently, our product allows users to enter only the start date and/or end date in yyyy-MM-dd when adding or editing a loan. However, when the loan is displayed the start and end time is displayed as well (due to a conversion issue) and is always set to midnight SGT. This time is not a property of the loan and it has never been intended for the loan to have a start and end time, as our commands only allow entering of the loan date. Would the display of the (default) time be considered a bug needing to be fixed?

Relevant issue:
https://github.com/AY2324S2-CS2103T-W13-1/tp/issues/154

**Comment by kjw142857** [comment]
In addition, I just realised that the display of the loan time might cause an inaccurate representation of the loan. For instance, a loan from `2024-01-01` to `2024-12-31` would be returned on time if it was returned on the last day. However, if the time was displayed, it would be `2024-01-01 00:00` to `2024-12-31 00:00`, so the user would think the loan was returned late if it was returned on `2024-12-31`, even though it was on time.

**Comment by damithc** [comment]
@kjw142857 Yes, this can be fixed.

**Comment by kjw142857** [comment]
Alright thank you Prof!
