### ISSUE TITLE
Are we allowed to fix the parsing of name if it doesnt allow special characters

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#738]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/73015364/512154c7-dcb7-437f-9889-810d3c5c1ba6)
 
 
 Are we allowed to fix this and let name have special characters?

**Comment by damithc** [comment]
@bgopi23 See Q5 of ohttps://nus-cs2103-ay2324s2.github.io/website/schedule/week12/project.html

**Comment by baskargopinath** [comment]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/73015364/9599dfde-b2fd-4b4e-b280-751ef394bee0)
thanks for the reply prof, since there is a workaround, can i confirm that we are not allowed to fix this? @damithc

**Comment by damithc** [comment]
@bgopi23 Yes, should not fix if there is a workaround.

**Comment by baskargopinath** [comment]
thank u prof @damithc
