### ISSUE TITLE
Clarification on what I can fix in v1.4

### ISSUE THREAD

**Issue by sindhurajain** [nus-cs2103-AY2324S2/forum#739]
Our team has a previously implemented feature pr/PRIORITY_LEVEL NAME which adds a priority level to a contact. The accepted values for PRIORITY_LEVEL are high, med and none. In the case where the user uses the correct command format but wrong argument (eg good priority level instead of high/med/none), can I modify the error message from "unknown command" to tell the user that they entered an invalid argument, and to use high/med/none instead?

<img width="846" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/115209308/7f2863a7-e621-4ef9-820a-c3af636b2064">

**Comment by damithc** [comment]
@sindhurajain We don't allow making the error message more specific but we allow widening the scope of the error message. e.g., `unknown command or unknown parameter value`

See Q6 for more info https://nus-cs2103-ay2324s2.github.io/website/schedule/week12/project.html

**Comment by sindhurajain** [comment]
@damithc Thanks for clarifying. Just another question- would it be ok to change the error message from unknown command to unknown parameter value since it’s changing the scope from command to parameter but not narrowing/widening?

**Comment by damithc** [comment]
@sindhurajain Yes, that should be fine.

**Comment by sindhurajain** [comment]
Got it, thank you!
