### ISSUE TITLE
Can we make confusing error messages more generic?

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#740]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/73015364/c49e0a0d-2106-4082-84f8-a3e5719f8878)

Can we change this to `Invalid command format` instead?

**Comment by damithc** [comment]
@bgopi23 Yes, making the error message more general is allowed, as per Q6 of https://nus-cs2103-ay2324s2.github.io/website/schedule/week12/project.html

**Comment by baskargopinath** [comment]
thanks prof @damithc
