### ISSUE TITLE
Clarification on if fixing this bug is a violation

### ISSUE THREAD

**Issue by ziiqii** [nus-cs2103-AY2324S2/forum#741]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/63834733/fe98e729-25cc-45d9-b642-698ec7f8f166)

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/63834733/1a333b7d-51fd-42fc-b155-91ff86ff852e)

Hi, could I confirm if I am allowed to fix this bug by allowing inputs such as "08"?
While the error message is not matching the input (bug), the user can workaround by simply typing "8", and adding leading zeroes is not a common input also.
Would like to fix this bug but not sure if it is a violation.

**Comment by damithc** [comment]
@ziiqii  I think the least logic-modifying remedy is to update the error message (and the UG) to mention that leading zeros should be omitted.

**Comment by ziiqii** [comment]
I see, thanks!
