### ISSUE TITLE
Fixing punctuation for error messages

### ISSUE THREAD

**Issue by chiralcentre** [nus-cs2103-AY2324S2/forum#742]
Can I check with the teaching team if we are allowed to add full stops at the end of error messages for v1,4? In the FAQ, it was stated we can fix spelling errors and grammar errors, but I am not too sure about modifying punctuation. At the same time, if we forgot to add spaces in the error message, are we allowed to add them as well?

**Comment by damithc** [comment]
@chiralcentre Yes, it's fine to fix punctuation errors.
