### ISSUE TITLE
Distinguishing Between a Feature Flaw and a Functionality Bug

### ISSUE THREAD

**Issue by itstrueitstrueitsrealitsreal** [nus-cs2103-AY2324S2/forum#748]
Hi, wanted to ask regarding this bug report my team received.

For context, the report was made about an attribute of an object in our app that did not have the deletion of the attribute when the object was deleted. 

Does this make up a feature flaw or a functionality bug? Thanks in advance!

**Comment by damithc** [comment]
@itstrueitstrueitsrealitsreal Can you share the specifics (what object and what attribute)? Hard to decide otherwise.

**Comment by itstrueitstrueitsrealitsreal** [comment]
The object is the person object, and each person has an array meetings as an attribute.

**Comment by damithc** [comment]
I see. What's the problematic behavior, from the users point of view? 
Reason for the above question: PE-D is a black-box text, which means the tester has no way to know there is an array of meetings that is not deleted, unless there is some user-visible behavior that goes with it.

**Comment by itstrueitstrueitsrealitsreal** [comment]
The user-visible behavior is that the meeting is still visible in the json file that stores the data. 

Related issue: https://github.com/AY2324S2-CS2103-F08-1/tp/issues/178

**Comment by damithc** [comment]
@itstrueitstrueitsrealitsreal If the data file contains data it should no longer contain, it's a bug that is eligible to be fixed in v1.4

**Comment by itstrueitstrueitsrealitsreal** [comment]
Thanks for the clarification, Prof.! Closing the issue now.
