### ISSUE TITLE
 Do tP deliverables require submission by only one person in the team?

### ISSUE THREAD

**Issue by AwJoey** [nus-cs2103-AY2324S2/forum#749]

**Comment by damithc** [comment]
@AwJoey Yes, one person per team. See [here](https://nus-cs2103-ay2324s2.github.io/website/schedule/week13/project.html#:~:text=Only%20one%20person%20need%20to%20submit%20on%20behalf%20of%20the%20team) for more details.

**Comment by AwJoey** [comment]
Ok thank you!
