### ISSUE TITLE
Are these considered feature flaw or bugs that can be fixed?

### ISSUE THREAD

**Issue by laney0808** [nus-cs2103-AY2324S2/forum#750]
1. A field is intended to be case-insensitive, but not explicitly stated in the UG. The imeplementation of case sensitivity has errors (e.g. left out for some classes, implemented in the wrong way) causing inconsistency in case sensitivity for different command. Is it a bug-fix to change implementation to a correct one?

2. If we discover a bug in a button's functionality that cannot be fixed easily, would it be permissible to change the button to a label instead? i.e. remove the feature of the button.

3. In cases where an error message addresses only part of the errors handled, e.g. only addesses problem A, B, but shown for problems A, B and C, would it be permissibe to change the error messages to talk about C as well?

**Comment by damithc** [comment]
> 1. A field is intended to be case-insensitive, but not explicitly stated in the UG. The imeplementation of case sensitivity has errors (e.g. left out for some classes, implemented in the wrong way) causing inconsistency in case sensitivity for different command. Is it a bug-fix to change implementation to a correct one?

@laney0808 Can fix, but limit the fix to the stated problem only.


> 2\. If we discover a bug in a button's functionality that cannot be fixed easily, would it be permissible to change the button to a label instead? i.e. remove the feature of the button.

Yes.

> 3\. In cases where an error message addresses only part of the errors handled, e.g. only addesses problem A, B, but shown for problems A, B and C, would it be permissibe to change the error messages to talk about C as well?

Yes, as per Q6 in https://nus-cs2103-ay2324s2.github.io/website/schedule/week12/project.html

**Comment by laney0808** [comment]
> > 1. A field is intended to be case-insensitive, but not explicitly stated in the UG. The imeplementation of case sensitivity has errors (e.g. left out for some classes, implemented in the wrong way) causing inconsistency in case sensitivity for different command. Is it a bug-fix to change implementation to a correct one?
> 
> @laney0808 Can fix, but limit the fix to the stated problem only.
> 
> > 2. If we discover a bug in a button's functionality that cannot be fixed easily, would it be permissible to change the button to a label instead? i.e. remove the feature of the button.
> 
> Yes.
> 
> > 3. In cases where an error message addresses only part of the errors handled, e.g. only addesses problem A, B, but shown for problems A, B and C, would it be permissibe to change the error messages to talk about C as well?
> 
> Yes, as per Q6 in https://nus-cs2103-ay2324s2.github.io/website/schedule/week12/project.html

Thank you so much!
