### ISSUE TITLE
Sequence Diagram question

### ISSUE THREAD

**Issue by tankh99** [nus-cs2103-AY2324S2/forum#751]
In sequence diagrams, we generally write the method names when pointing from one lifeline to another. However, is it possible that we can ignore writing names and instead write the general idea of what each action does? Like "filters appointments"

**Comment by damithc** [comment]
@tankh99 Yes. Example:
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/4a97557d-6480-499d-9602-0a538743f56a)

**Comment by tankh99** [comment]
I see, thank you Prof!
