### ISSUE TITLE
Fixing Program Name in Log File

### ISSUE THREAD

**Issue by drustanyjt** [nus-cs2103-AY2324S2/forum#752]
We received a functionality bug report (AY2324S2-CS2103T-F14-2/tp#205) that our Log File still had mentions of `addressbook`. The suggestion was to replace mentions of address book with our app name, but this seems very much like a cosmetic enhancement.

Would adding a note in the UG that the name of the app may not be the same as what appears in the Log file due to legacy reasons be a valid fix that appropriately accounts for this "bug"?

**Comment by damithc** [comment]
> Would adding a note in the UG that the name of the app may not be the same as what appears in the Log file due to legacy reasons be a valid fix that appropriately accounts for this "bug"?

@drustanyjt yes, this is fine, but if you wish, you may change it to the correct app name as well. Showing the old app name is qualifies as an error.

**Comment by baskargopinath** [comment]
@damithc prof what about if there are some mentions of ab3 in dg/javadocs ?

**Comment by damithc** [comment]
> @damithc prof what about if there are some mentions of ab3 in dg/javadocs ?

They can be changed as well.

**Comment by baskargopinath** [comment]
@damithc sorry prof, i mean to ask, is this an error? or only user facing stuff like dg/ug and json file


> @damithc prof what about if there are some mentions of ab3 in dg/javadocs ?

**Comment by damithc** [comment]
> @damithc sorry prof, i mean to ask, is this an error? or only user facing stuff like dg/ug and json file

The PE grades UG, DG, and the JAR behavior that is visible to testers.
For code quality, we only grade lines that are attributed to you in the code dashboard.
