### ISSUE TITLE
Query about violation of long method

### ISSUE THREAD

**Issue by jannaleong** [nus-cs2103-AY2324S2/forum#753]
For my groups tp, we have enhanced the original help feature such that we provide help for each individual command. 

For example : /help ; command : delete 
will result in help pop up window showing the command format for delete. 

However since my group has 15 commands, this results in a long if-else block as i need to return the correct message based on the command type. May I check that I am not violating any code quality issues as I'm not sure how else to improve the code as I need the if-else block to return the correct help message.

Below is part of the if-else block in my execute method in helpCommand.java

<img width="890" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/96218110/12c9948f-2801-4903-87a1-e3620aa08611">

**Comment by damithc** [comment]
@jannaleong any specific rule or guideline you are concerned about?

**Comment by jannaleong** [comment]
i am concerned about violating the constraint of having long methods that span >30 lines. currently it spans about 50 lines

**Comment by damithc** [comment]
> i am concerned about violating the constraint of having long methods that span >30 lines. currently it spans about 50 lines

Ah, I see. That's not a rule, just a guideline.
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/364ede28-91bb-4cf9-9946-1039f01b84ad)

In some cases, method longer than 30 lines is unavoidable.

**Others are welcome to pitch in with your thoughts, for example, ways (if any) to shorten this code.**

**Comment by baskargopinath** [comment]
@jannaleong it looks very neat as is, maybe you can add import statements for the help messages to shorten that part?

**Comment by jannaleong** [comment]
thank you for all the help :))
