### ISSUE TITLE
Scrollbar not working: feature flaw or bug?

### ISSUE THREAD

**Issue by zhekaiii** [nus-cs2103-AY2324S2/forum#754]
There is one segment in our UI that has a scrollbar for excessive content or if window is too small, but currently the scrollbar doesn't work (it's there but scrolling doesn't work). Users can resize their window and will be able to see more of the content. Is this considered a bug, or a feature flaw?

**Comment by damithc** [comment]
@zhekaiii If the scrollbar is there but it doesn't work (i.e., it is visibly and obviously 'broken'), it is eligible to be fixed, or can be removed too.

**Comment by zhekaiii** [comment]
Ok thank you prof!
