### ISSUE TITLE
Am I allowed to change this?

### ISSUE THREAD

**Issue by Jerome-j** [nus-cs2103-AY2324S2/forum#755]
Dear teaching team,

I would like to check on the following, whether the following changes are allowed?

1. Forget to change the default AB3 error message.
https://github.com/AY2324S2-CS2103-F08-2/tp/issues/281
https://github.com/AY2324S2-CS2103-F08-2/tp/issues/264
   Instead of saying "Tag names should be alphanumeric and should not be blank", instead the message should be saying "Affiliated with tags should be alphanumeric, single word and should not be blank"

**Comment by damithc** [comment]
@Jerome-j OK to update 'tag' to 'affiliated with'. The 'singe word' thing seems to be an separate enhancement though.

**Comment by Jerome-j** [comment]
Hi prof, thanks for the reply! In that case I will mention the single word in the UG then!
