### ISSUE TITLE
Query on Error message

### ISSUE THREAD

**Issue by bryanyee33** [nus-cs2103-AY2324S2/forum#756]
Dear teaching team,
May I ask if we are allowed to change the error message from

`At least one field to edit must be provided.` to `The new asset name must be different`

as there is only 1 field that can be edited, namely the asset name.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/65088428/47c00986-14c1-4ed9-b426-fe5d80bc88b9)

**Comment by damithc** [comment]
@bryanyee33 We don't allow making error messages more specific but we allow widening the scope of the message. In this example, we can allow you to change it to something like `At least one field to edit must be provided, for which the new value must be different from the old value.`
