### ISSUE TITLE
Clarification on whether changing REGEX for parsing is considered a bug 

### ISSUE THREAD

**Issue by yuechen2001** [nus-cs2103-AY2324S2/forum#757]
Regarding the issue mentioned by this PR, 
https://github.com/AY2324S2-CS2103T-T12-1/tp/pull/160
and this section of the course website
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/64315146/c0cfbcda-abda-4cc0-bc6c-f7ddd9792c98)

From my understanding, since we have already mentioned that our tech stack parser should accept any inputs with '_', adjusting the regex should be considered a bug fix as our parser incorrectly blocked a legitimate input due to an incorrect regex. Could I ask if this is the correct understanding? Thanks in advance!

**Comment by damithc** [comment]
@yuechen2001 The original regex accepts `#` but not `_`?

**Comment by yuechen2001** [comment]
> @yuechen2001 The original regex accepts `#` but not `_`?

yep that's correct prof. We realised it was an issue with our original regex that somehow didn't _. We changed the implementation of the regex and now it works as advertised.

**Comment by damithc** [comment]
@yuechen2001 In that case you can fix it. 
I asked because if the current behavior can't handle `#` either, the more appropriate remedy is to update the UG to match the current behavior.

**Comment by yuechen2001** [comment]
Thanks Prof! Will be closing this
