### ISSUE TITLE
Legality of Changes in 1.4

### ISSUE THREAD

**Issue by Ko-Khan** [nus-cs2103-AY2324S2/forum#758]
A tester raised an [issue](https://github.com/AY2324S2-CS2103T-F12-2/tp/issues/179) regarding the program doing nothing when it takes in garbage values, which in this case is a start date being later than an end date.
I had written an unique class exception `InvalidDatesException` for this and thrown this exception. However, it turns out that the code will only display error messages related to parse exceptions, so the command with garbage values will be rejected, but the error message will not be shown.

To fix this, I added this chunk of code 
` catch (InvalidDatesException x) {
            throw new ParseException(x.getMessage());}`
But my team worries that this may count as enhancement, and therefore violate the feature freeze. To add on, the user can currently tell that the command does not work as nothing happens when they enter the garbage command.

**Comment by damithc** [comment]
@Ko-Khan Failing silently is considered a bug. You can fix it. 
More info in Q6 in https://nus-cs2103-ay2324s2.github.io/website/schedule/week12/project.html

**Comment by Ko-Khan** [comment]
My worry is that this may not be counted as a silent failure, as the user can still tell something is wrong even though there is no explicit message saying so.

**Comment by damithc** [comment]
> My worry is that this may not be counted as a silent failure, as the user can still tell something is wrong even though there is no explicit message saying so.

@Ko-Khan Even that is eligible for fixing. If there is an error, the user needs to be informed.

**Comment by Ko-Khan** [comment]
Thank you for the clarification!
