### ISSUE TITLE
Question on whether fixing a search functionality bug using parsers without changing any input validation is okay

### ISSUE THREAD

**Issue by Joshy837** [nus-cs2103-AY2324S2/forum#759]
For this bug, in order to fix this bug, is it okay if I can parse the search query (e.g. `/search ; salary : $50/hr`) without making any changes to the validation of the search input. Because the feature flaw was that I did not use validation for `search` command, so would fixing this search functionality bug in order to search by integer without making any changes to the validation, be okay?

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/87865932/1c3b1848-4688-4c74-95a8-c6c96c4dddb8)

**Comment by damithc** [comment]
@Joshy837 From the user point of view, what's the current behavior, what's wrong with it, and what's the proposed new behavior?

**Comment by Joshy837** [comment]
From the user point of view, the current behaviour allows users to key in any String input without any validation to search for salary, and the search command works by matching the String query with existing String input. In this case, we identified this lack of input validation as our feature flaw. By right, our Salary field follows this format `$X/hr`, but the search command does not perform this validation, so users can key in anything from `$`, `$5`, `50` etc.

But the current functionality bug is that if the user searches for example, `$5`, the search command returns all contacts with salary field containing this string, which unfortunately includes `$50/hr`. This is clearly a bug as I used String search to perform the search.

The proposed new bahaviour to fix the bug would be to parse salary through a parser to trim the extra terms and search by matching the integer, but the main issue is that would it be alright if I use the parser without making any changes to validation (i.e. still allow invalid inputs), in order not to violate the feature freeze? Or would it be okay to add validation to reject invalid parsed inputs in this case?

**Comment by damithc** [comment]
@Joshy837 Using a substring match for this case may not be outright incorrect. In majority of the cases this is unlikely to hinder the user if the feature is used as intended. I can search for those paid $50 by looking up `$50/hr` right? If the user search for garbage, the results will be garbage as well.

**Comment by Joshy837** [comment]
Thanks prof! Yup, majority of cases substring search would not really be an issue, but the only main problem is if the user searches for `$5`, expecting to get all the salaries that is $5/hr, but also gets salaries with $50/hr as well. Will that then be considered as a functionality bug and something to be resolved? Without it becoming a feature flaw?

**Comment by damithc** [comment]
@Joshy837 You can use the UG to inform users how the results differ between `$5/hr` and `$5`. In fact the second one can be quite  useful if one wants to find those paid in the range 500-599 (yes, it will return extra results but it will contain all the target results as well).

**Comment by Joshy837** [comment]
Thanks prof! I'll update the user guide in this case instead and resolve this as follows. Thank you!
