### ISSUE TITLE
Having trouble troubleshooting iP Weekly Progress

### ISSUE THREAD

**Issue by LWS49** [nus-cs2103-AY2324S2/forum#76]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/111121080/c8cc40d7-b89f-43b3-b449-b1a7bf3aef76)

My iP increments are updating, but my iP Weekly Progress has no updates at all. I'm not sure what commits it tracks (and which branch/fork), so how should I start troubleshooting this?

**Comment by damithc** [comment]
@LWS49 Previously, your problem was the one mentioned below:
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/e00953c9-b7bd-41b6-9655-9803235aa336)

Now I see that you have fixed it already. Just need to wait till the next dashboard update and check again.
