### ISSUE TITLE
Help regarding plantuml and class diagram

### ISSUE THREAD

**Issue by camille-readbean** [nus-cs2103-AY2324S2/forum#761]
Hi, I would like to ask if the class diagram is okay, primarily on the multiplicity and labels.  
  
1. Is the symbols, green dots and red square okay? I got it from here: https://plantuml.com/class-diagram
2. I can't seem to add multiplicity / association roles on both side of the lines, is the current diagram okay? It meant to say a Client may have 0 to many Appointment
  1. I.e. something like [this, Class Diagram > Multiplicity](https://nus-cs2103-ay2324s2.github.io/website/se-book-adapted/chapters/modeling.html#class-diagrams-basics): 
![adminProfessorStudent](https://github.com/nus-cs2103-AY2324S2/forum/assets/52031118/1ff0add7-bcca-47a9-9f53-fa42d6f83a4f)

4. As I model Appointments as a List of Appointment, is this considered Composition or Aggregation, or is a simple association enough?
5. Is it okay to leave the attribute types as Java classes or should we generalise it more?

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/52031118/3166581f-b83c-45af-9720-b416a260264f)

**Comment by damithc** [comment]
@camille-readbean I'll answer the general questions. The rest seem specific to to your DG (which is a graded submission) -- but they can be discussed here with peers.

> 1. Is the symbols, green dots and red square okay? I got it from here: https://plantuml.com/class-diagram

The UML notations should be consistent with the notation we covered in the course, and other diagrams in the DG. Different diagrams in the DG should not follow different styles. Just follow what the existing diagrams do.
On a related note, you can follow the level of details in the current DG UML diagrams, if not sure how much details to give.

> 5\. Is it okay to leave the attribute types as Java classes or should we generalise it more?

Did you mean `int` etc.? Yes, that's fine.


> 4\. Composition or Aggregation, or is a simple association enough

It is not incorrect to show a composition as  simple association (composition symbol is optional)

**Comment by camille-readbean** [comment]
> The UML notations should be consistent with the notation we covered in the course, and other diagrams in the DG. Different diagrams in the DG should not follow different styles. Just follow what the existing diagrams do.
On a related note, you can follow the level of details in the current DG UML diagrams, if not sure how much details to give.

I managed to fix it by using `hide circle` and 
```
skinparam classAttributeIconSize 0
skinparam usecaseAttributeIconSize 0
```

>> 5. Is it okay to leave the attribute types as Java classes or should we generalise it more?
> Did you mean int etc.? Yes, that's fine.

I meant to say `Optional`, `List` `LocalDateTime` etc

> It is not incorrect to show a composition as simple association (composition symbol is optional)
Thanks!  
  
If it is within the scope of what you can answer, is the current multiplicity and association label sufficient, i.e. not have the association role?

**Comment by damithc** [comment]
> I managed to fix it by using `hide circle` and
> 
> ```
> skinparam classAttributeIconSize 0
> skinparam usecaseAttributeIconSize 0
> ```

I believe AB3 already provides a styles file that you can include in your PUML files to achieve a consistent look i.e., no need to do these settings in every PUML file.


> I meant to say `Optional`, `List` `LocalDateTime` etc

Yes, they can be used as well.

> If it is within the scope of what you can answer, is the current multiplicity and association label sufficient, i.e. not have the association role?

There is no need to use all of these at the same time. Sometimes, using one removes need to use another e.g., using association roles reduces the need for association labels (and vice versa).

**Comment by E0735389** [comment]
See also discussion in https://github.com/nus-cs2103-AY2324S2/forum/issues/650 .
