### ISSUE TITLE
Okay to point to user guide for testing instruction

### ISSUE THREAD

**Issue by camille-readbean** [nus-cs2103-AY2324S2/forum#762]
Hi Prof,

Our team decided to point the testing instructions in [Appendix: Instructions for manual testing](https://ay2324s2-cs2103t-t17-1.github.io/tp/DeveloperGuide.html#appendix-instructions-for-manual-testing) to point to a new user tutorial in our User Guide. Is this okay?  
  
> New User tutorial
> 1.   Run through the entire new user tutorial [in User Guide > Quick Start > New User Tutorial](https://ay2324s2-cs2103t-t17-1.github.io/tp/UserGuide.html#new-user-tutorial).
> 2.   The guide will take you through all essential features of SWEE.

**Comment by damithc** [comment]
@camille-readbean OK for the DG to point to the UG (but not the other way around).
