### ISSUE TITLE
Is this considered as a bug fix?

### ISSUE THREAD

**Issue by dhlee03** [nus-cs2103-AY2324S2/forum#765]
Dear teaching team,

- https://github.com/AY2324S2-CS2103T-F12-4/tp/issues/56
- https://github.com/AY2324S2-CS2103T-F12-4/tp/issues/57

Can these two issues considered as a bug fix? The storage of our app is currently storing every fields except the group field. For this reason, group fields always display zero value when we restart the program, even though we set them into different value before exiting the program using command. Our storage is designed to store every user information, and this is different from advertised behavior.

**Comment by damithc** [comment]
@dhlee03 Yes, this is a bug. Allowed to fix.

**Comment by dhlee03** [comment]
thank you Prof for the clarification!
