### ISSUE TITLE
Would this situation be a feature enhancement or a bug fix?

### ISSUE THREAD

**Issue by gerteck** [nus-cs2103-AY2324S2/forum#766]
Hi Everyone, 

I would like to clarify a bug report detailing the presence of duplicate persons. Currently, our implementations allows duplicate people to slip through, either via addition or editing of current persons. This causes some issues with other implemented commands such as pairing between persons. I would like to clarify if we were to rectify this issue, would this be allowable under v1.4? (would it violate feature freeze?)

It was not explicitly mentioned in our UG to disallow duplicate persons, and so as per [Q3](https://nus-cs2103-ay2324s2.github.io/website/schedule/week12/project.html#:~:text=FAQs%20on%20what%20is%20allowed%20during%20the%20feature%20freeze%3A) of the FAQ, would it be reasonable 'correct' to expect duplicate persons to be disallowed? Hence, would it be allowable to treat this as a bug fix, and implement a simple equality check and throw a general error?

Thanks in advance!

**Comment by damithc** [comment]
> This causes some issues with other implemented commands such as pairing between persons.

@gerteck Can you give an example of such an issue?

**Comment by gerteck** [comment]
@damithc 
For context: https://github.com/AY2324S2-CS2103T-T09-3/tp/issues/132
Due to the duplicate persons in the list, when pairing, the wrong person (at a earlier index than specified) in the list gets paired up, which is incorrect behaviour.

Edit: 
There is also another associated issue: (https://github.com/AY2324S2-CS2103T-T09-3/tp/issues/178)
Which causes an error to be thrown when pairing in the presence of duplicated persons

**Comment by damithc** [comment]
@gerteck I see. Yes, in that case you can update the code to prevent duplicates.
