### ISSUE TITLE
Am I allowed to make this change?

### ISSUE THREAD

**Issue by Jerome-j** [nus-cs2103-AY2324S2/forum#767]
Hi, can I check if this change is allowed?

This is an error that is brought up by one of the testers: https://github.com/AY2324S2-CS2103-F08-2/tp/issues/264

In AB3, you are allowed to leave the tag blank when editing (but you MUST specify the tag when you are creating a new person), but the original AB3 tag message does not accurately reflect that.

I am seeking to make a change like this:

```java
    public static final String MESSAGE_CONSTRAINTS = "The values for affiliated-with should be alphanumeric. "
            + "It can be blank for editing, but not for adding.";
```

**Comment by damithc** [comment]
@Jerome-j Yes, you can fix this, as the current error message is not entirely accurate.

**Comment by Jerome-j** [comment]
Thanks Prof!
