### ISSUE TITLE
Bug when multiple features are performed together during testing

### ISSUE THREAD

**Issue by chiageng** [nus-cs2103-AY2324S2/forum#768]
My team has developed pin/unpin feature to prioritize some important contact to stay at the top.

During out testing, we realised that, pin/unpin feature works perfectly fine on its own. However, after a pinned person is edited, the pin status disappear and the pin sequence is slightly messed up as even though pin status disappear, this contact is still inside "priority list" displaying to user. 

Our team know what's going on and understand which part of code missed up on handling the "pin" status. 

If we are going to fix this, is this consider feature bug or feature flaw?

**Comment by damithc** [comment]
@chiageng Sorry I missed this earlier. If editing a person shouldn't affect the pin status but it does in the current version, it can be fixed.
