### ISSUE TITLE
Is this considered a feature-flaw or bug?

### ISSUE THREAD

**Issue by Wyrkx** [nus-cs2103-AY2324S2/forum#770]
Hello everyone,

Our project has a schedule command, that when run, is supposed to display a schedule of events and reminders. Unfortunately, we did not do enough testing before v1.3, and as of now the schedule command only displays a blank window when run.
Is this considered a feature-flaw or bug?
relevant issue: https://github.com/AY2324S2-CS2103T-F12-3/tp/issues/130

**Comment by damithc** [comment]
@Wyrkx It's a bug. However, we still need to decide if the appropriate remedy (in the context of the feature freeze) is to remove the feature or fix it. 
Have you found the reason for this problem? For example,
a) the implementation of the said window was incomplete at the the JAR was released.
b) the window was fully implemented at the time of the JAR release  (and there is clear evidence of it e.g., the PR was merged before the deadline), but a bug caused the content to be not visible.
c) ...

**Comment by Wyrkx** [comment]
I believe it is a). I assume that in this case then that removing the feature is more appropriate?

**Comment by damithc** [comment]
> I believe it is a). I assume that in this case then that removing the feature is more appropriate?

@Wyrkx Yes, unless it is a must-have feature the absence of which affects other features as well -- in which case we can allow you to add a minimal version of it.

**Comment by Wyrkx** [comment]
Ok, thank you!
