### ISSUE TITLE
Question about UI bug

### ISSUE THREAD

**Issue by JukeBoxK** [nus-cs2103-AY2324S2/forum#771]
![question](https://github.com/nus-cs2103-AY2324S2/forum/assets/113361013/3bb7a46c-ac34-4445-b963-49a552fb56e0)

Are the above UI error fixable? The help message is missing a new line or a new space. I am not sure if this is considered a typo or just cosmetic adjustment.

**Comment by baskargopinath** [comment]
I think punctuation can be fixed but idk about formatting

**Comment by damithc** [comment]
@JukeBoxK Yes, you can add these three things. All three are considered typos.
