### ISSUE TITLE
Are we allowed to use ai tools to help generate javadocs?

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#773]
And if we do, do we need to declare it somewhere?

**Comment by damithc** [comment]
@bgopi23 Yes. More info [here](https://nus-cs2103-ay2324s2.github.io/website/admin/appendixB-policies.html#policy-on-reuse:~:text=Citing%20the%20use%20of%20AI%2Dgenerated%20code).

**Comment by baskargopinath** [comment]
@damithc thanks prof, however im not sure if we need to declare using ai tools for javadocs, as here it talks about using it for methods and class code
<img width="751" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/73015364/034fa77f-8341-4692-aa22-a47635b99283">

**Comment by damithc** [comment]
@bgopi23 applies to code comments (including javadocs) and any other documentation (such as UG or DG content).

**Comment by baskargopinath** [comment]
got it, thanks prof @damithc
