### ISSUE TITLE
Generalising Persons to Contacts

### ISSUE THREAD

**Issue by bryanyee33** [nus-cs2103-AY2324S2/forum#775]
May I ask if we are we allowed to generalise "Persons" to "Contacts" in our output messages?

![Screenshot_20240411-180249_Kiwi_Browser](https://github.com/nus-cs2103-AY2324S2/forum/assets/65088428/ef822345-4212-47a0-9afe-fed18e66b879)

**Comment by damithc** [comment]
@bryanyee33 Only if the current term is incorrect. Simply standardizing terms is considered an enhancement.

**Comment by bryanyee33** [comment]
Technically the term is incorrect, as what is listed are not persons but contacts. For our app, they may not necessarily be people, and can be companies as well.

**Comment by damithc** [comment]
> Technically the term is incorrect, as what is listed are not persons but contacts. For our app, they may not necessarily be people, and can be companies as well.

I see. In that case you can change it.
