### ISSUE TITLE
Is this considered a feature flaw or a fixable bug?

### ISSUE THREAD

**Issue by ys112** [nus-cs2103-AY2324S2/forum#776]
[Issue details](https://github.com/AY2324S2-CS2103-F15-3/tp/issues/175) 

Hi, the directory of the export file command did not check for inputs that allowed it to store in other directory with the extra input, could this be considered misbehavior and be able to fix?

**Comment by damithc** [comment]
@ys112 Seems the current behavior is not strictly incorrect? In that case it is an enhancement. For now, you can use the UG to inform the user of the current behavior.

**Comment by ys112** [comment]
Ok noted, thank you.
