### ISSUE TITLE
pUML not loading  on intellij

### ISSUE THREAD

**Issue by RunjiaChen** [nus-cs2103-AY2324S2/forum#777]
<img width="1095" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/142142406/c90947b4-52d0-40af-85fb-17f684952ca7">
Does anyone else face the same issue with regards to the puml diagrams? Some of them work, but others seem to have this error message.

**Comment by tankh99** [comment]
This is same issue I face. It's normal

**Comment by RunjiaChen** [comment]
Wait but I actually need to edit the diagram tho 🤡 How exactly do I do that if I cant even see the diagram

**Comment by damithc** [comment]
> Does anyone else face the same issue with regards to the puml diagrams? Some of them work, but others seem to have this error message.

@RunjiaChen This is odd. Perhaps restart the IDE. If  the same error persists, which ones work and which ones don't?

**Comment by aureliony** [comment]
This may be helpful: https://stackoverflow.com/questions/54413962/cant-render-component-diagram-with-plantuml-in-intellij

**Comment by RunjiaChen** [comment]
Thank you!
