### ISSUE TITLE
Valid boolean names

### ISSUE THREAD

**Issue by tankh99** [nus-cs2103-AY2324S2/forum#778]
Is this considered a valid boolean name?

<img width="658" alt="Screenshot 2024-04-11 at 7 29 52 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/56617918/2dff2689-8fd7-4168-a252-ad6a64b554be">

Similarly, are boolean names like `apptHasPerson` a valid boolean name in terms of CS2103's coding standard?

**Comment by vnnamng** [comment]
I have the same query!

**Comment by damithc** [comment]
OK to use `personsAreUnique` as `if personsAreUnique` reads very much like a boolean condition.

**Comment by tankh99** [comment]
> 
> 
> 
> 
>  OK to use `personsAreUnique` as `if personsAreUnique` reads very much like a boolean condition.

Thank you prof. I'll assume that 'apptHasPerson' is also a valid Boolean name from that reasoning

**Comment by damithc** [comment]
> Thank you prof. I'll assume that 'apptHasPerson' is also a valid Boolean name from that reasoning

@tankh99 Yes.
