### ISSUE TITLE
Is updating the help link allowed in v1.4?

### ISSUE THREAD

**Issue by ZhiWei1010** [nus-cs2103-AY2324S2/forum#780]
Hi prof @damithc , may I know if updating the help link is considered a bug? Currently our help link points to the home page of our project instead of the user guide. Is this considered a bug?

<img width="474" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/60460444/c3f4a726-7da6-45f2-afb7-a5aa415111a7">

**Comment by damithc** [comment]
@ZhiWei1010 Yes, can be fixed.

**Comment by ZhiWei1010** [comment]
Ok, thanks prof!
