### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by justincred** [nus-cs2103-AY2324S2/forum#781]
what if this isn't an enchancement and is a bug as once the app is loaded, the first person card will always be clicked and if there is only 1 person then this card blends into the background as shown and we have merged the fix already. Are we violating the feature freeze here if we fixed it? 
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/95204474/0eacfd0f-0109-447d-8e87-d564d9013911)

**Comment by damithc** [comment]
@justincred Is the selected card is always black? If the third card is selected, that one will become black while the rest alternate between blue and purple?

In any case this doesn't look like a bug, just a default behavior that might appear a bit puzzling to a first-time user.

**Comment by justincred** [comment]
Thanks @damithc, but this is permanent as there is always one card that is black and it is done upon startup, now it is fixed such that it only happens if it's clicked, otherwise in the event that there is only 1 person selected, it blends into the black background like so. 
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/95204474/f305f461-1ac7-45df-97d3-85ed64422f6c)

This is the fixed version 
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/95204474/268a9266-5b99-4fc2-b1d9-6a65336dacc9)

**Comment by damithc** [comment]
I see. So, if I understand you correctly, the first card is shown different from the rest without any acceptable reason (from the user's POV) for it. If that is the case, we can consider it as a bug.
