### ISSUE TITLE
Is this considered a bug or feature flaw? 

### ISSUE THREAD

**Issue by jocelyn-soh** [nus-cs2103-AY2324S2/forum#782]
A tester has reported that when on the "LAB05" tab, if a student is in multiple groups (e.g. TUT04 and LAB05 as shown in the picture below), the attendance table shown should only be for that specific group, in this case "LAB05", instead of all groups that the student is in. Can this be considered a bug that can be fixed since the UI is showing "excess" data i.e. "incorrect" data? 
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/110960191/435ee700-826c-45f1-a4ef-156af4c43aa1)

**Comment by damithc** [comment]
@jocelyn-soh What was the originally intended behavior for this case? What does your v1.3 UG says that should happen in this case?

**Comment by jocelyn-soh** [comment]
The v1.3 UG did not specify this case but our intended behavior is to only display the attendance for the group which the user's current tab is on.

**Comment by damithc** [comment]
@jocelyn-soh So currently, the timetable shows the same data irrespective of which tab is selected? In that case, it is a bug and can be fixed.

**Comment by jocelyn-soh** [comment]
@damithc Thanks for the clarification! Yes, the attendance table inside the person card remains the same regardless of which group tab the user is on, except for the "Results" tab which does not display the attendance table for brevity sake. 
Example of the "Results" tab: 
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/110960191/cf8c4df4-256c-4c54-970a-d6fbdbd7c8cd)


Using the example of person "Bernice Yu" in the screenshot in my original post, when I navigate to the "TUT04" tab, which is the other group that Bernice Yu is in, the same attendance table can be seen below.
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/110960191/9e47b34c-375d-4457-aac5-3392434ad3f5)

**Comment by damithc** [comment]
@jocelyn-soh Thanks for the clarification. Seems like a bug. You can fix it.
