### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by jocelyn-soh** [nus-cs2103-AY2324S2/forum#784]
A tester has reported that after executing the `mark` command to mark the attendance of a student in a particular group on a particular week when on one of the groups tab (e.g. "LAB10" tab), the program will switch back to the "Results" tab instead of remaining on the same tab. The expected behavior is to remain on the same tab but was not stated in the UG v1.3.  Is this considered a bug as it differs from normal expectation of the feature? 

Before marking attendance: 
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/110960191/0c88b050-abf0-467d-80e6-42dc848a53f3)

After marking attendance: 
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/110960191/5e9e75d7-b19e-4911-ad46-42c8a4791a76)

**Comment by damithc** [comment]
@jocelyn-soh Yes, this is unnatural and hinders usages.  However, it is still not error but a usability issue. So, I'm afraid your only recourse is to list it as a planned enhancement.

**Comment by jocelyn-soh** [comment]
I see, so to clarify this is considered a feature flaw not a bug?

**Comment by damithc** [comment]
Yes, fixing this would be an enhancement not a bug fix.
