### ISSUE TITLE
Is it okay to fix some commands not showing the full list after performing a search on the address book?

### ISSUE THREAD

**Issue by Joshy837** [nus-cs2103-AY2324S2/forum#787]
Issue: `Delete`, `Pin`, `Unpin`, `Undo` and `Redo` commands do not show the full list after operating on a filtered list (after `search`)

For example, I have 3 existing contacts in the address book, e.g. `Alice`, `Ben`, `Charlie`, and then I perform a `/search ; name : Alice` on the address book. This will display only `Alice` in the current UI. But let's say I perform `/pin ; name : Ben`, it pins this contact, but the UI still displays only `Alice` only without showing the remaining contacts, but internally the commands are just working properly. The main issue is forgetting to add this line of code `model.updateFilteredPersonList(true)`. Is it okay to fix this issue by adding this line of code? Technically it does not change any behaviour of the code since it is an issue of not updating the display of the contacts.

**Comment by damithc** [comment]
@Joshy837 Several teams had similar problems and we have consistently categorizing them as enhancements (i.e., the feature works but the usability can be improved). So, this one will have to go under planned enhancements.

**Comment by Joshy837** [comment]
Alright, thanks prof Damith!
