### ISSUE TITLE
UI feature bug?

### ISSUE THREAD

**Issue by yashma-sonara** [nus-cs2103-AY2324S2/forum#788]
I received this bug report for summary statistics for 0 students. Initially I thought it can be fixed by preventing the window to open for 0 students, but it seems like a feature change?

Would removing the A+ arrow be considered a fixable bug or feature change?

<img width="601" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/44407952/b3091f21-9257-4593-b05b-0f1819cf3457">

**Comment by damithc** [comment]
@yashma-sonara can you post a stats screenshot _with_ students, for comparison?

**Comment by yashma-sonara** [comment]
For reference, this is the way it looks with students. 

<img width="297" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/44407952/ae777598-211c-4010-9dff-59a330f72e02">

**Comment by damithc** [comment]
I see. Yes, the presence of the A+ arrow can be considered an incorrect behavior (it should not be there at all) and removed.

**Comment by yashma-sonara** [comment]
Thank you prof
