### ISSUE TITLE
Query regarding Level-7

### ISSUE THREAD

**Issue by radeon2525** [nus-cs2103-AY2324S2/forum#79]
I wanted to clarify on how we can save our chatbot conversation on the hard-disk, as I couldn't really find methods in the textbook that depict on what is asked in Level-7.

**Comment by E0735389** [comment]
You can look up how to read and write to files e.g. there's a tutorial at https://docs.oracle.com/javase/tutorial/essential/io/file.html .

That having said, you aren't supposed to be doing level 7 this week yet.

**Comment by damithc** [comment]
@radeon2525 As @E0735389 mentioned, Level-7 is scheduled in [week 3 project tasks](https://nus-cs2103-ay2324s2.github.io/website/schedule/week3/project.html). You can look among [week 3 topics](https://nus-cs2103-ay2324s2.github.io/website/schedule/week3/topics.html#W3-4c) to learn how to read/write files.

**Comment by radeon2525** [comment]
Prof @damithc ,

I wanted to clarify to what @E0735389 said about the timeline of the project, the website says that week-3 starts from Jan 26th onwards, so I was under the assumption that I should start the week-3 tasks as soon as possible. 

Please let me know if I have misunderstood the information and if I should start at a later date. Thank you.

**Comment by damithc** [comment]
> I wanted to clarify to what @E0735389 said about the timeline of the project, the website says that week-3 starts from Jan 26th onwards, so I was under the assumption that I should start the week-3 tasks as soon as possible.

No worries @radeon2525 It's fine to start weekly tasks a bit early, provided you don't go too far ahead or don't fall too far behind.
Technically, the week starts with the weekly briefing (i.e., Friday 4pm). This point wasn't as clear this time as in previous semesters because we released the first weekly briefing in advance this time. I'll make a note to make this clear in the future semesters.

**Comment by radeon2525** [comment]
Alright understood prof. Thank you for clarifying that
