### ISSUE TITLE
Is editing the Error Message to standardise with the UG allowed?

### ISSUE THREAD

**Issue by SherisseTJW** [nus-cs2103-AY2324S2/forum#791]
In our UG, we state that the End Time must be after or equal to the Start Time, 

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/63995220/e9af6d5e-e9e7-47dd-931a-bee641a8c9bc)

however, our error message only says End Time must be after Start Time.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/63995220/a7ab6c7a-c4fc-45e6-8aff-94fa68c5441c)

Can I just double confirm we are allowed to edit the error message to be the same as the UG, i.e., add the "or equal to" to the error message

**Comment by damithc** [comment]
@SherisseTJW Yes, this is an error of omission, and can be corrected.
