### ISSUE TITLE
Grammatical error in 2103 website

### ISSUE THREAD

**Issue by tengcharmaine** [nus-cs2103-AY2324S2/forum#792]
The 'implements' word is grammatically incorrect. Might be better to change it to 'implemented'.

<img width="908" alt="Screenshot 2024-04-12 at 1 39 47 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/122196137/e2e55592-8b87-4242-a830-1f80eaed8254">

**Comment by damithc** [comment]
Thanks for the bug report @tengcharmaine 
Fixed
