### ISSUE TITLE
Checking if these violates feature freeze.

### ISSUE THREAD

**Issue by Benson15912** [nus-cs2103-AY2324S2/forum#794]
Our application has an assignments feature where volunteers are assigned a volunteer activity.
However edits made to the volunteer are not reflected in the assignment list.
<img width="769" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/70809364/5b9c7f50-0bcb-4408-8267-dd56e6660679">
<img width="769" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/70809364/ab48c357-da79-49dd-8ab8-a987ce08ef22">

Can we fix this, or this violates feature freeze?

Can we also fix when deleting a person  will also cascade delete an assignment?

**Comment by damithc** [comment]
@Benson15912 Both sound like either UI being inconsistent with data, or an inconsistency within data itself. If that is the case, can be fixed.

**Comment by Benson15912** [comment]
Thanks prof
