### ISSUE TITLE
Bug or enhancement

### ISSUE THREAD

**Issue by raysonchia** [nus-cs2103-AY2324S2/forum#795]
https://github.com/AY2324S2-CS2103-F09-4/tp/issues/94

Our `Find` command allows the search for the gender attribute which has 3 possible vales `M`, `F` and `Prefer not to say`. The intended way to filter for these genders would be `find g/m`, `find g/f` and `find g/` respectively. We made a design consideration earlier to shorten `Prefer not to say` with an empty input instead. However, the command currently incorrectly parses this and throws an error to the user saying `Gender must be M, F or exclude argument in the command for 'Prefer not to say'` when entered `find g/`. Hence, there is no way for the user to find for the gender `Prefer not to say`. Would this be fixable or is it an enhancement?

**Comment by damithc** [comment]
@raysonchia What did the v1.3 UG say about this feature? Was the intended behavior described there?

**Comment by raysonchia** [comment]
> @raysonchia What did the v1.3 UG say about this feature? Was the intended behavior described there?

The UG mentions the behaviour of the empty input `g/` in other commands e.g. `add`, `edit`. The current error message for `find g/` also mentions this behaviour.


![](https://raw.githubusercontent.com/chenyixin0/ped/main/files/731d0392-1f38-4caf-946a-6e1e7588144d.png)

**Comment by damithc** [comment]
@raysonchia Yes, not accepting `g/` is  a bug. You can fix it.
