### ISSUE TITLE
Clarification on feature flaw for phone number

### ISSUE THREAD

**Issue by yleeyilin** [nus-cs2103-AY2324S2/forum#796]
Hi, in my team's implementation, we purposefully only allowed for one phone number as we felt that by allowing the users to add more than one phone number, it could be problematic as the users will now have to remember which phone number that is in use.
This intentional feature was already mentioned in the UG. 
 
However, we noted that in the guidelines, it was mentioned that: Phone number not allowed more than once, in which it would considered as a feature flaw. 

As such, I am hoping to seek clarifications on whether this will still be considered a feature flaw? Thank you!

**Comment by damithc** [comment]
@yleeyilin Is this inquiry about a change you already did in v1.4, or something you are planning to do in v1.4?
In either case, what's the previous behavior and what's the new behavior?

**Comment by yleeyilin** [comment]
@damithc 
We did not change this in v1.4.. We are considering if it is necessary to put it as a planned enhancement. 

Right now, the behaviour is that our contact card only accepts one phone field.

But we do not know if it is necessary to claim that as a feature flaw and put it under planned enhancement and we are hoping to seek your clarification on this. 

Thanks!

**Comment by damithc** [comment]
> But we do not know if it is necessary to claim that as a feature flaw and put it under planned enhancement and we are hoping to seek your clarification on this.

Ah I see. This is your decision, based on your opinion of whether that is an area in which the feature can be improved further. If you think limiting to one phone number is better than allowing more than one, that means you think it is not a feature flaw.
As you have only a limited number of slots in the planned enhancements list, you should pick the ones that are more likely to be reported by PE testers and of higher severity.
Also note that even if it was reported by a PE tester as a feature flaw, you will not be penalized if you can show that it is [NotInScope](https://nus-cs2103-ay2324s2.github.io/website/admin/tp-pe.html#:~:text=How%20to%20prove%20that%20something%20is%20response.NotInScope).
