### ISSUE TITLE
Is extreme user input considered as a bug?

### ISSUE THREAD

**Issue by acekhoon** [nus-cs2103-AY2324S2/forum#798]
Hi everyone,

https://github.com/AY2324S2-CS2103T-W08-1/tp/issues/164

Regarding the above issue, the tester provided a very extreme input for the index field. Even though the app does not crash nor it corrupts the data, it does not provide the best error message for the user, and similar happens for negative index or 0. Whenever the user provides the number outside of integer range or negative number & 0 as an index, it raises an invalid command error as above. Thus, I want to clarify whether generic error message that does not specifically tell the user that the "negative" or "zero" index provided is invalid is part of the valid bug (and whether we need to deal with this as a valid bug for v1.4).

Thank you!!

**Comment by damithc** [comment]
@acekhoon You are allowed to expand the scope of the error message e.g., `Invalid command format OR invalid value` but NOT allowed to add more specific details.
You can also update the UG to caution users against using these 'invalid' values, if you wish.
Relevant: Q6 of https://nus-cs2103-ay2324s2.github.io/website/schedule/week12/project.html

**Comment by acekhoon** [comment]
> @acekhoon You are allowed to expand the scope of the error message e.g., `Invalid command format OR invalid value` but allowed to add more specific details. You can also update the UG to caution users against using these 'invalid' values, if you wish. Relevant: Q6 of https://nus-cs2103-ay2324s2.github.io/website/schedule/week12/project.html

Hi prof, thank you very much for your reply! To summarize, we are allowed to expand the error message (invalid command format or invalid index provided!) but not allowed to add more details on our error messages right (e.g. we are not allowed to add extra messages on message class and codes that detect the invalid indices in the respective parser classes). Thanks!

**Comment by damithc** [comment]
> Hi prof, thank you very much for your reply! To summarize, we are allowed to expand the error message (invalid command format or invalid index provided!) but not allowed to add more details on our error messages right (e.g. we are not allowed to add extra messages on message class and codes that detect the invalid indices in the respective parser classes). Thanks!

Yes, that's correct @acekhoon

**Comment by acekhoon** [comment]
Thank you very much prof!
