### ISSUE TITLE
Updating code or UG

### ISSUE THREAD

**Issue by chiralcentre** [nus-cs2103-AY2324S2/forum#799]
Can I check with the teaching team if there is a discrepancy between the UG and the functionality of the code, should we update the UG or the code? For example, in our v1.3 UG we did not mention spaces are not allowed for tags and our examples have tags with spaces. However, when a tag with spaces is added, a message stating that "Tags can only contain alphanumeric characters" is shown. There are two ways to resolve this issue: we can either update the UG to explicitly mention that spaces are not allowed, or we can update the code for tag validation to allow spaces. I understand that its written in Q1 of the FAQ `If the current behavior differs from the UG but the current behavior is not strictly incorrect, update the UG to match the current behavior (in the interest of minimizing code changes). ` However, I am concerned that if I update only the UG, our tag feature disallowing spaces can be considered a feature flaw during the PE. Any advice will be greatly appreciated!

**Comment by damithc** [comment]
@chiralcentre 
1. Yes, updating the UG seems the appropriate course of action for this case.
2. Yes, it _can_ be reported as a feature flaw. To avoid a penalty, you can either list it under planned enhancements, or show that it is NotInScope after it is reported (NotInScope bugs are not penalized).

**Comment by chiralcentre** [comment]
Thank you Prof for the response! Can I check if planned enhancements should be in UG or in DG?

**Comment by damithc** [comment]
> Thank you Prof for the response! Can I check if planned enhancements should be in UG or in DG?

@chiralcentre Details are [here](https://nus-cs2103-ay2324s2.github.io/website/schedule/week12/project.html#:~:text=Using%20%27Planned%20Enhancements%27%20DG%20section%20to%20counter%20known%20feature%20flaws).

**Comment by chiralcentre** [comment]
Thank you Prof for the response! My apologies for missing out on that information
