### ISSUE TITLE
Accidentally deleted tag on GitHub

### ISSUE THREAD

**Issue by ashleyclx** [nus-cs2103-AY2324S2/forum#80]
I created the `A-Enums` tag and pushed to GitHub and was looking at my tags when I accidentally deleted on GitHub itself and I can't delete and repush the tag. Is there any way to rectify this?

**Comment by E0735389** [comment]
Just run `git push --tags` again?

**Comment by ashleyclx** [comment]
My bad, I must have typed the command wrongly. Thanks!
