### ISSUE TITLE
If a statement is factually wrong because of simplification, is it a bug?

### ISSUE THREAD

**Issue by E0735389** [nus-cs2103-AY2324S2/forum#801]
As in the title.

Sometimes it seems desirable for me to write a simplified description of the feature in the user guide. Even though the description is wrong in a few specific cases, in general it correctly describes the behavior and **the user can use the product effectively with the user guide**.

Would that be counted as a bug? (I'd say no because spelling out everything explicitly would hinder the reader because it makes the documentation harder to read)

**Comment by damithc** [comment]
@E0735389 You can also use something like `In typical usage, ...` to qualify the simplified description.
