### ISSUE TITLE
Are we allowed to standardise display messages?

### ISSUE THREAD

**Issue by logical-1985516** [nus-cs2103-AY2324S2/forum#802]
May I ask if standardising messages displayed to users would be a feature freeze violation? For instance, adding a "\n" before "Parameters", removing leading/trailing whitespaces, or standardising phrasing.

**Comment by damithc** [comment]
@logical-1985516 Yes, that would be an enhancement (not allowed during feature freeze). But you can fix spelling and grammar errors.

**Comment by logical-1985516** [comment]
Thank you Prof! I will close the issue now.
