### ISSUE TITLE
Clarification for editing the UI display command format

### ISSUE THREAD

**Issue by kaiyi27** [nus-cs2103-AY2324S2/forum#803]
The previous code for a particular command contains of three behaviour add, edit and delete but the display command format only mention is unclear for differentiate these 3 behaviour. The command example format is also contain only for adding (missing for edit and delete).

Is it ok to fix it by adding for other 2 missing information and structure the format to make it clear for these 3 behaviour.

**Comment by damithc** [comment]
@kaiyi27 I need more details. Give a screenshot of the current behavior and specify the proposed new behavior (and the reason for the change).

**Comment by kaiyi27** [comment]
This is the previous display of command format
<img width="620" alt="Screenshot 2024-04-12 at 11 24 01 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/122215691/8997a7ee-7fb6-46ed-9fcb-502e11e885f7">
<img width="716" alt="Screenshot 2024-04-12 at 11 24 06 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/122215691/f98378c8-3fe4-48ab-a369-135d069b4510">

This is the modify version
<img width="671" alt="Screenshot 2024-04-12 at 11 24 36 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/122215691/5adbc76c-17b4-4a77-b2e4-79071c76590c">
<img width="1059" alt="Screenshot 2024-04-12 at 11 24 42 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/122215691/53e5c0ca-3596-4f7d-bb29-363819a725f4">


Reason for changing:
1. The previous version is kind of unclear for the instruction and it only provide an example command format which is adding a policy. It also didnt state out properly what it stance for. In the UG, it have mentioned clearly already
2. Adding misinformation for other action such as edit and delete to make it clear to the user, and also differentiate to 3 section to make it easier to see.

**Comment by damithc** [comment]
@kaiyi27 OK to add these additional info to the error message.

**Comment by kaiyi27** [comment]
Ok thanks prof.
