### ISSUE TITLE
Some questions about the PE grading methodology

### ISSUE THREAD

**Issue by aureliony** [nus-cs2103-AY2324S2/forum#804]
After reading the PE page on the website, I have some uncertainties and would like to clarify them.

Firstly, regarding `response.NotInScope`: the tester could report everything from the Planned Enhancements section in the DG as feature flaws. The tester will gain credit for them. Does this affect the tester's accuracy? I think the website page is unclear about this.

Secondly, from my understanding, the tester can report all bugs as `severity.High`. If the developer then reponds with `severity.Low`, the tester can accept it and the tester's accuracy is unaffected (neither increases nor decreases).

If this is indeed true, then the tester could have just have _one_ accurate bug and "_SU_" the rest of the bugs by just reporting them as `severity.High` and accepting the dev's response, therefore achieving 100% accuracy. Is there some minimum amount of bugs required in order to qualify for this accuracy?

**Comment by damithc** [comment]
> Firstly, regarding `response.NotInScope`: the tester could report everything from the Planned Enhancements section in the DG as feature flaws. The tester will gain credit for them. Does this affect the tester's accuracy? I think the website page is unclear about this.

@aureliony The planned enhancements section is immune from bug reporting. They should not be reported by PE testers (unless the planned enhancement itself is flawed). If they are reported, they will not earn credit for the tester and will not be penalized for the dev team. But yes, reporting a bug that should not be reported will lower the tester's accuracy.


> Secondly, from my understanding, the tester can report all bugs as `severity.High`. If the developer then reponds with `severity.Low`, the tester can accept it and the tester's accuracy is unaffected (neither increases nor decreases).

Correct. 


> If this is indeed true, then the tester could have just have _one_ accurate bug and "_SU_" the rest of the bugs by just reporting them as `severity.High` and accepting the dev's response, therefore achieving 100% accuracy. Is there some minimum amount of bugs required in order to qualify for this accuracy?

A tester following this strategy will trigger two safety mechanisms:
* Bonus for accuracy will not kick in unless there is enough quantity to justify the bonus. 
* Too many mismatches between original and eventual severity (or other similar anomalies) will flag the case for manual inspection to see if the tester or the dev team was acting unreasonably or trying to game the system.

**Comment by aureliony** [comment]
Thank you for the prompt and detailed reply.
