### ISSUE TITLE
Validation from manual file changes

### ISSUE THREAD

**Issue by tankh99** [nus-cs2103-AY2324S2/forum#806]
Hello! I'd like to just ask how much validation is required to prevent against malicious manual file changes? For example, inserting a null in the JSON file or manipulating the preferences.json file to cause crashes. Are all these valid bugs?

**Comment by damithc** [comment]
@tankh99 given [here](https://nus-cs2103-ay2324s2.github.io/website/admin/tp-pe.html#:~:text=Handling%20manual%20edits%20to%20the%20data%20file):

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/5cdfe063-eb7f-4148-9c40-09e5e2970b8b)

Ensure the level of support is clearly specified in the UG.

**Comment by tankh99** [comment]
Thank you!
