### ISSUE TITLE
Discrepancy Between Course Site and Email Submission Instructions

### ISSUE THREAD

**Issue by itstrueitstrueitsrealitsreal** [nus-cs2103-AY2324S2/forum#807]
Hi, I received an email last night about PPP submissions, alongside the other file naming conventions I was supposed to adhere to for the tP submissions.

I saw that the PPP had to follow a file naming format and was supposed to be submitted on Canvas, but I see no dedicated assignment submission page for the PPP.

Is this because we are supposed to submit it along with the tP deliverables in the same submission?

In addition, upon referring to the [link](https://nus-cs2103-ay2324s2.github.io/website/schedule/week13/project.html) provided in the email about more details regarding submissions, it is stated that PDF submission is not required, despite the email instructing us to save the PPP in the form of a PDF format for Canvas.
![Screenshot 2024-04-13 at 12 55 12 PM](https://github.com/nus-cs2103-AY2324S2/forum/assets/120318851/98e2ad79-5187-473f-93b6-9c497bfb9a15)
Any clarifications regarding the above would be greatly appreciated! Thank you.

**Comment by damithc** [comment]
@itstrueitstrueitsrealitsreal Good catch. The email contained an outdated instruction. There is no PDF submission for the PDF.

**Comment by itstrueitstrueitsrealitsreal** [comment]
Thanks Prof.! Closing the issue now.
