### ISSUE TITLE
Declaration about function guide

### ISSUE THREAD

**Issue by chiageng** [nus-cs2103-AY2324S2/forum#808]
Hi prof, i have implemented undo redo feature using this guide provided, do i need to declare the guide link in code reuse declaration (since i am following the idea, will there be a need to declare "code reuse")?

https://se-education.org/addressbook-level4/DeveloperGuide.html#undo-redo-feature

**Comment by damithc** [comment]
@chiageng Yes, you need to declare it. You can mention the level of reuse as well (e.g., follow the design vs reuse code)

**Comment by chiageng** [comment]
Okay, thx prof
