### ISSUE TITLE
Is Wrong App Name Considered A Typo?

### ISSUE THREAD

**Issue by drustanyjt** [nus-cs2103-AY2324S2/forum#809]
A few of our error messages use the phrase "address book" / "AddressBook" instead of our new app name "ClinicMate". For example:

```
    public static final String MESSAGE_NO_MATCHING_IC = "There is nobody with the IC you specified. \n"
            + "You may use the add command to add the specific person to the address book.";
```

Is an error message displayed to the user if some IC is incorrect. Can we treat `the address book` as a typo and replace it with the phrase `ClinicMate` instead?

**Comment by damithc** [comment]
@drustanyjt Yes.

**Comment by drustanyjt** [comment]
Thanks @damithc for the prompt reply!
