### ISSUE TITLE
Automated Testing input.txt

### ISSUE THREAD

**Issue by DominicFuMJ** [nus-cs2103-AY2324S2/forum#81]
Hi, I'm having trouble with the input.txt. When I tried to write out the inputs and run the runtest.bat, it would only run the first line of the input. Only the first line is highlighted green, while the rest is white. How can I fix this? Thank you.

input.txt
todo read book
deadline return book /by Sunday
event project meeting /from Mon 2pm /to 4pm
bye

![Screenshot 2024-01-26 171720](https://github.com/nus-cs2103-AY2324S2/forum/assets/119829202/40a507a1-a7eb-4216-93aa-648e89737590)

**Comment by guanquann** [comment]
There is nothing wrong with it. It is yellow as todo is a keyword in intellij telling you that this part need to be completed in the future. https://www.jetbrains.com/help/idea/using-todo.html#add-multiline-todo

If it is only running your first line, it means that there might be something wrong with your code :D

**Comment by damithc** [comment]
> There is nothing wrong with it. It is yellow as todo is a keyword in intellij telling you that this part need to be completed in the future. https://www.jetbrains.com/help/idea/using-todo.html#add-multiline-todo

@guanquann is right. This is just Intellij thinking that this line is a 'note to self' you've made about something you need to do (due to the `todo` keyword), and helpfully highlighting it to make it more visible to you.

**Comment by DominicFuMJ** [comment]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/119829202/3547a79a-cb95-4cb0-bca5-0f4d2b3c2ef3)
This is my code to read the user input. Is there something wrong with it? Thanks

**Comment by Jerome-j** [comment]
Hi @DominicFuMJ is it possible to show the loop portion how you continuously read in input - until the "bye" command is entered? I suspect that somehow your userInput variable is not being updated say:

```java
while(Loop){
    userInput = myObj.nextLine();
}
```

**Comment by DominicFuMJ** [comment]
Yes, I placed the myObj inside a while loop, but when I place it outside the loop, it started working.

**Comment by Jerome-j** [comment]
What I recommend you to do is - maybe separate the assignment / initialisation of the variable `userInput`. General idea is as below

```java

String userInput;

while (!userInput.equals("bye")) {
     userInput = myObj.nextLine();
}

```

**Comment by E0735389** [comment]
@DominicFuMJ By the way, you're violating a handful of forum rules.

https://nus-cs2103-ay2324s2.github.io/website/admin/appendixD-help.html#what-not-to-do

* Avoid showing text as screenshots
* Isolate the problem. "My code doesn't work" isn't going to help even if you post the whole code.
* Don't hijack other threads: It is OK to chime in if you have the same problem as the OP but **don't ask a different (even if somewhat related) question in someone else's thread**.

(the last one is borderline because this is your own thread, although the question is different)

**Comment by timothysashimi** [comment]
Hi Dominic, if you're done with this issue can you close it? Thanks
