### ISSUE TITLE
Checking if this violate feature freeze

### ISSUE THREAD

**Issue by MarcusGitty** [nus-cs2103-AY2324S2/forum#811]
Hi prof, TA, fellow students.

Currently we loading from addressbook.json and checked the following parameters by their respective isValid and isNull methods.
-name
-phone
-email
-address
-subject
-payment
is checked and if invalid, a blank addressbook.json will be loaded.

We added a new field to persons, an Id class and only checked if it's null.

Can we check the validity of the Id to be in line with the others ?

 We feel that this would make our app meet the current level of support for manually editing the file from AB-3.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/122339963/0dec71b8-7d83-4a33-a6f1-6b0b3ca5bc85)

But we are unsure due to https://github.com/nus-cs2103-AY2324S2/forum/issues/724#issuecomment-2044115034

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/122339963/2b57cdf3-41b5-4dc1-a4d5-e143a0c83328)

Issues concerned:
https://github.com/AY2324S2-CS2103T-F10-2/tp/issues/147
https://github.com/AY2324S2-CS2103T-F10-2/tp/issues/151

**Comment by MarcusGitty** [comment]
Seems like i can't change the label, it should be a type-question. apologies !

**Comment by damithc** [comment]
@MarcusGitty By the 'current level of support' we mean 'if you edit the file correctly, things will work. But if you edited it wrongly, there's no guarantee that things will work'. So, I assume you already meet this bar?

**Comment by MarcusGitty** [comment]
Hi, thanks. I'll not merge the fixes in !
