### ISSUE TITLE
Clarification on violation of feature freeze while improving code quality

### ISSUE THREAD

**Issue by ziyang27** [nus-cs2103-AY2324S2/forum#812]
Dear Prof, TAs and friends,

may I ask if it is okay if I create a .copy() method in my Person object and use it in one of my existing functions which originally returns the `Person` object? 

For context, I am trying to improve my code quality with reference to this consideration:
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/122247192/0f72b31b-7ffc-4818-9571-dcb2f93d1670)

There are no apparent changes to the external behavior of the feature.

Thank you so much in advance 😄

**Comment by damithc** [comment]
> There are no apparent changes to the external behavior of the feature.

@ziyang27 In that case, there is no violation of the feature freeze.

**Comment by ziyang27** [comment]
Thank you Prof @damithc 😄
