### ISSUE TITLE
fixing duplicate contacts

### ISSUE THREAD

**Issue by justincred** [nus-cs2103-AY2324S2/forum#813]
hi are we allowed to fix this as a bug or is this regarded as a feature flaw instead as this is not intended with our intentions in the ug?
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/95204474/e2a2c0bf-e56c-44b4-818b-6b834c44d90e)

**Comment by damithc** [comment]
@justincred this will be an enhancement, as the current behavior is not strictly incorrect.

**Comment by justincred** [comment]
ok thank you @damithc , but isn't this a bug because it's possible for there to be more than one person with the same name but less possible for them to have the same address, phone number or email? But if it isn't able to be fixed, is it possible to either include it in the constraints in adding the person or in planned enhancement? many thanks!

**Comment by damithc** [comment]
> but isn't this a bug because it's possible for there to be more than one person with the same name but less possible for them to have the same address, phone number or email? 

@justincred As per Q5 in https://nus-cs2103-ay2324s2.github.io/website/schedule/week12/project.html tightening validity checks is allowed only in rare situations.
 
> But if it isn't able to be fixed, is it possible to either include it in the constraints in adding the person or in planned enhancement? many thanks!

Yes, you may mention in the UG what kind of values are expected for an input. And yes, you can mention more stringent validity checks as a planned enhancement.
