### ISSUE TITLE
Date time bug

### ISSUE THREAD

**Issue by justincred** [nus-cs2103-AY2324S2/forum#814]
Hi, this is one of our constraints, however we realised we did the check based on date only and not time so it is possible set dates that is the current day but the time has passed, is it possible to fix this bug then?
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/95204474/2b862f4b-622f-4e17-92c9-02f0970cbfdb)

**Comment by damithc** [comment]
@justincred can you post the relevant parts of the v1.3 UG?

**Comment by justincred** [comment]
hi @damithc , here is a screenshot from the v1.3 ug 
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/95204474/47633987-af6b-484d-aab3-da6ea8fcf2d7)
And just asking but if it was not in the ug before, are u not allowed to just include it in or it must be based on the v1.3 ug, thank you!

**Comment by damithc** [comment]
@justincred Looks like a bug in the current validity check. Can be fixed.

> And just asking but if it was not in the ug before, are u not allowed to just include it in or it must be based on the v1.3 ug, thank you!

Evidence of the behavior in v1.3 helps us decide if this is a new behavior being added or fixing a bug in an existing behavior.

**Comment by justincred** [comment]
alright thank you!
