### ISSUE TITLE
Where can we find the PDF version of the Java Coding Standard?

### ISSUE THREAD

**Issue by dillontkh** [nus-cs2103-AY2324S2/forum#815]
In the week 13 "Final Exam" course briefing video, around the 10:55 mark there is a mention of a Java Coding Standard PDF being provided, but I am unable to find it on Canvas. May I know where we can download it?

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/40649376/eee21355-c3d8-4772-8301-d2a624488b85)

**Comment by damithc** [comment]
@dillontkh Uploaded it to Canvas just now. Thanks for the heads up.

**Comment by dillontkh** [comment]
Thank you prof!
