### ISSUE TITLE
Checking if fixing pop up issues violates feature freeze

### ISSUE THREAD

**Issue by 0nesheep** [nus-cs2103-AY2324S2/forum#816]
Hi teaching team!

Our tp has a logging function. When the user enters a command, the app opens a pop up displaying the log list. 

However, during our internal testing, we realised that:
1. if the user adds a new log without closing the pop up, the new log does not get updated into the pop up
2. if the user enters the command to open the log window for person A, then, without closing the pop up, tries to use the command to open the log window for person B, the log window still logs for person A instead of person B. 
3. if the user minimizes the window, then tries to use the command, nothing happens and the window remains minimized.

These issues will be "solved" and the content will be updated if the user closes the log window after using the command before trying to open a new one.

Is it okay to fix this confusing behavior? Or should this be just written as a note in the UG?

Thank you so much in advance!

**Comment by damithc** [comment]
@0nesheep In the spirit of the feature freeze in place, you can update the UG to inform users that they are advised to close the log window as necessary. A more user-friendly fix can be listed under planned enhancements.

**Comment by 0nesheep** [comment]
> @0nesheep In the spirit of the feature freeze in place, you can update the UG to inform users that they are advised to close the log window as necessary. A more user-friendly fix can be listed under planned enhancements.

@damithc Understood! Thank you so much for the prompt reply :D
