### ISSUE TITLE
Changing regex for email

### ISSUE THREAD

**Issue by UdhayaShan1** [nus-cs2103-AY2324S2/forum#817]
The ab3's regex for `email` disallows continuous symbol `+.` will raise an error. This differs from its expected behaviour to allow such inputs. Is this considered a bug and can we fix this?

**Comment by damithc** [comment]
@UdhayaShan1 Can you give an example of a valid input that is currently rejected?

**Comment by UdhayaShan1** [comment]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39399745/16598c0b-758c-4c07-b9fb-fde227beeaa2)

This was raised by our testers, expected highlights `should only contain alphanumeric characters and these special characters, excluding the parentheses, (+_.-)`, so 

`ud+e@gmail.com` as expected parses

`ud+e_e@gmail.com` parses but

`ud+_e@gmail.com` is wrong

Something about continuous symbols raises this problem

**Comment by damithc** [comment]
@UdhayaShan1 Rejecting valid inputs is a bug and can be fixed, unless such data is not expected to be used (in normal usage), or if a reasonable workaround exists.

**Comment by UdhayaShan1** [comment]
Thanks Prof!
