### ISSUE TITLE
Are we allowed to change this message in v1.4?

### ISSUE THREAD

**Issue by logical-1985516** [nus-cs2103-AY2324S2/forum#821]
Currently, our clear command only deletes the person list (and not the job list), but the message refers to it as "database", e.g. "Clearing the database is irreversible. Proceed? (Y/N)". Are we allowed to change the word "database" to "address book" or "candidate list"?

**Comment by damithc** [comment]
@logical-1985516 Yes, because the message does not accurately reflect what actually happens.

**Comment by logical-1985516** [comment]
Thank you Prof! I will close this issue now.
