### ISSUE TITLE
Are screenshots required for UG?

### ISSUE THREAD

**Issue by chiralcentre** [nus-cs2103-AY2324S2/forum#822]
Can I check with the Prof if screenshots are strictly required for the UG? If screenshots are missing from the UG, is this grounds for a UG bug? The grading guidelines are not clear for this part.

**Comment by damithc** [comment]
@chiralcentre We don't have a rule that says it is compulsory to have screenshots in the UG. We do have a mention of screenshots [here](https://nus-cs2103-ay2324s2.github.io/website/admin/tp-deliverables.html#deliverable-user-guide-ug:~:text=Beware%20of%20overusing%20screenshots).

But a tester can certainly report a bug if there is a place where having a screenshot is better than not having one. Similarly, a tester can report a bug for having a screenshot where one isn't needed. So, it is case-by-case.

**Comment by chiralcentre** [comment]
Noted thank you Prof!
