### ISSUE TITLE
Can we fix a truncated message by increasing help window size?

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#823]
(https://github.com/AY2324S2-CS2103T-T17-3/tp/issues/349)

<img width="797" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/73015364/6b59776c-a2cd-4832-a919-892097150254">

are we allowed to fix this by increasing the help window width?

**Comment by damithc** [comment]
@bgopi23 See if Q8 in https://nus-cs2103-ay2324s2.github.io/website/schedule/week12/project.html helps you decide.

**Comment by baskargopinath** [comment]
@damithc prof, the window is not reziable and there is no other view of our help window. is it safe to assume that we can expand the width slightly?

**Comment by damithc** [comment]
@bgopi23 Yes, in that case it can be fixed.

**Comment by baskargopinath** [comment]
thank you for the clarification prof @damithc
