### ISSUE TITLE
Can we fix this?

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#824]
https://github.com/AY2324S2-CS2103T-T17-3/tp/issues/236

<img width="809" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/73015364/001b958d-366a-4913-af10-09431cde6f96">

https://github.com/nus-cs2103-AY2324S2/forum/assets/73015364/455f49e9-7f5f-4d68-8657-9fefafcbbc7d

**Comment by damithc** [comment]
@bgopi23 You can cross-check against the FAQ in https://nus-cs2103-ay2324s2.github.io/website/schedule/week12/project.html and post a follow up query here stating which point you are not sure about.

**Comment by baskargopinath** [comment]
@damithc prof, referring to Q1, we are not sure if we can fix it because

*  it could be argued that its technicaly not wrong to have a date on the weight graph when theres no weight associated with that date. 

* But on the other hand, if we removed the weight, there is no point keeping a random date value in the weight graph.

**Comment by damithc** [comment]
@bgopi23 You can remove it as it has no reason to be there anymore.

**Comment by baskargopinath** [comment]
thanks prof! @damithc
