### ISSUE TITLE
Incorrect help message

### ISSUE THREAD

**Issue by YowSiaoKang** [nus-cs2103-AY2324S2/forum#826]
```
Emails should be of the format local-part@domain and adhere to the following constraints:
1. The local-part should only contain alphanumeric characters and these special characters, excluding the parentheses, (+_.-). The local-part may not start or end with any special characters.
2. This is followed by a '@' and then a domain name. The domain name is made up of domain labels separated by periods.
The domain name must:
    - end with a domain label at least 2 characters long
    - have each domain label start and end with alphanumeric characters
    - have each domain label consist of alphanumeric characters, separated only by hyphens, if any.
```

For the following emails supplied, the above help message will be shown which seems to be an invalid help message.
- `a++a@aaa`: message specifies that '+' is supported in local-part but consecutive special characters results in error.
- `aaa@aaa.a-a`: message specifies that '-' is supported in domain label but it is not for the last domain label

I would like to clarify if fixing of the help message in our app is allowed. Thank you!

**Comment by damithc** [comment]
@YowSiaoKang What's the proposed change to the error message?

**Comment by YowSiaoKang** [comment]
Emails should be of the format local-part@domain and adhere to the following constraints:
1. The local-part should only contain alphanumeric characters and these special characters, excluding the parentheses, (+_.-). **Special characters must not be consecutive** and the local-part may not start or end with any special characters.
2. This is followed by a '@' and then a domain name. The domain name is made up of domain labels separated by periods.
The domain name must:
    - end with a domain label at least 2 characters long
    - have each domain label start and end with alphanumeric characters
    - have each domain label consist of alphanumeric characters, separated only by **a single** hyphen, if any. **Ending domain label should not contain any hyphens.**

**Comment by damithc** [comment]
@YowSiaoKang Yes, you can update the error message.

**Comment by YowSiaoKang** [comment]
Thank you prof!!! @damithc
