### ISSUE TITLE
Minor type in course website

### ISSUE THREAD

**Issue by bryanyee33** [nus-cs2103-AY2324S2/forum#83]
https://nus-cs2103-ay2324s2.github.io/website/schedule/week3/topics.html

In the Week 3 Topics page, it should be "FileWriter object" instead of "FileWrite object"
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/65088428/1d7a76b0-e617-4dbb-969f-b40d5e56a598)

**Comment by damithc** [comment]
Thanks for catching it, @bryanyee33 
Fixed.
