### ISSUE TITLE
Clarification on when resetting the contact list to be empty is considered a bug

### ISSUE THREAD

**Issue by kjw142857** [nus-cs2103-AY2324S2/forum#833]
From the PE readiness quiz, it seems that the user setting a duplicate entry in the address book through the CLI is considered a Severity.High bug when it causes the address book to be cleared:
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/122250318/8c6aca77-782e-41a4-92b4-676478b4a9a8)

Will non-CLI forms of user corruption of the data causing the address book to be cleared also be considered Severity.High bugs? For instance, let's say the user edits a name in the JSON file causing it to be a duplicate of another name, and the team has implemented the AB3 to detect this on startup and start with an empty address book (thus deleting all the data). Is this not a bug, a lower severity bug, or still a Severity.High bug (since the outcome is still "disastrous" but was intended by the team)?

**Comment by damithc** [comment]
@kjw142857 [This point](https://nus-cs2103-ay2324s2.github.io/website/admin/tp-pe.html#:~:text=Handling%20manual%20edits%20to%20the%20data%20file) about bugs related editing the data file is relevant here.
So, if a bug like the one you mentioned is reported, it will likely be categorized as NotInScope, in which case the severity is not important. But yes, the disastrous nature of the outcome push the severity higher but it also depends on how likely the problem to occur. Also note that AB3 UG recommends taking a backup of the datafile before editing it, which means  the outcome may not be disastrous anyway.

**Comment by kjw142857** [comment]
Noted Prof, thank you for your feedback!
