### ISSUE TITLE
Clarification Regarding Labels on Class Diagrams

### ISSUE THREAD

**Issue by itstrueitstrueitsrealitsreal** [nus-cs2103-AY2324S2/forum#834]
Hi, just wanted to clarify if using the `<<>>` notation to denote the implemented design patterns in our DG is acceptable.
As an example,
<img width="92" alt="Screenshot 2024-04-14 at 12 32 11 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/120318851/8951755c-9308-4637-b363-890cf78a45ad">
would indicate that Ui uses the Observer and Facade patterns.

Additionally, would it be acceptable to omit `<<interface>>` or `{abstract}` if we were to replace them with the name of a role in a design pattern? Thanks!

**Comment by damithc** [comment]
> Hi, just wanted to clarify if using the `<<>>` notation to denote the implemented design patterns in our DG is acceptable.
> As an example,
> <img alt="Screenshot 2024-04-14 at 12 32 11 PM" width="92" src="https://private-user-images.githubusercontent.com/120318851/322247580-8951755c-9308-4637-b363-890cf78a45ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwNzA3MzYsIm5iZiI6MTcxMzA3MDQzNiwicGF0aCI6Ii8xMjAzMTg4NTEvMzIyMjQ3NTgwLTg5NTE3NTVjLTkzMDgtNDYzNy1iMzYzLTg5MGNmNzhhNDVhZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNFQwNDUzNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOGY3Zjk4NDM5NGE3NmJlOTg5MzEyZDBhOTg2ZWViOWU2MzBlNjZiNGI4M2JkYmI2NTExYTM0NDM5NGM0ZGM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Hc8U12qvsXKV8nM55ELN1-A3DvTUk-mEoDn9TWfjYSI">
> would indicate that Ui uses the Observer and Facade patterns.

@itstrueitstrueitsrealitsreal Yes, in class diagrams (not in object diagrams as stated in the post subject)

> Additionally, would it be acceptable to omit `<<interface>>` or `{abstract}` if we were to replace them with the name of a role in a design pattern? Thanks!

No. These two are separate from the additional stereotypes you add to a class.

**Comment by itstrueitstrueitsrealitsreal** [comment]
Thanks for the clarification! 
I have updated the post subject accordingly.
In that case, I have an additional follow-up question:
Would the following be acceptable in a class diagram?
<img width="82" alt="Screenshot 2024-04-14 at 1 18 24 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/120318851/92698615-5991-4628-a58b-a57de552726c">

**Comment by damithc** [comment]
@itstrueitstrueitsrealitsreal It is fine to have multiple stereotypes for a UML entity.

**Comment by itstrueitstrueitsrealitsreal** [comment]
Thanks for the clarification! Marking this post as closed.
