### ISSUE TITLE
Clarification on grading requirements 

### ISSUE THREAD

**Issue by RunjiaChen** [nus-cs2103-AY2324S2/forum#836]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/142142406/6e3091f7-8548-43c3-8675-90a2bd43a640)
@damithc  Hello Prof, can I check what exactly do you mean by what's stated here? Is it a must to have all of the error handling techniques, (defensive, exceptions, assertions, logging), or do we just need to have some of them? Then for the ones we have, there is some evidence of usage?

**Comment by damithc** [comment]
@RunjiaChen It is not compulsory to have _all_ of them but good use of each can push your score higher.
When grading code quality, positive observations push the score higher, and negative observations pull the score lower. The final score will the cumulative result, subject to a cap.

**Comment by RunjiaChen** [comment]
Thank you!
