### ISSUE TITLE
Handling manual edits to file

### ISSUE THREAD

**Issue by tankh99** [nus-cs2103-AY2324S2/forum#837]
Hi there, I'm not sure if this has been asked before, but what happens if you make manual edits to a file and the application crashes? AB3 mentions that incorrect data editing will cause the data to be reset, but not handling crashes. If so, would this be considered a valid bug?

**Comment by damithc** [comment]
@tankh99 AB3 says `certain edits can cause the AddressBook to behave in unexpected ways`. If the edit is incorrect, all bets are off -- anything can happen.

**Comment by tankh99** [comment]
I see, thank you prof!
