### ISSUE TITLE
AB3 code reused

### ISSUE THREAD

**Issue by Ko-Khan** [nus-cs2103-AY2324S2/forum#839]
I had reused some of the classes from AB3 such as JsonAdaptedPerson and modified them to create classes such as JsonAdaptedArticle, JsonSerializableArticleBook. Do I need to declare this under reuse and will these new classes count towards my total lines of code written?

**Comment by damithc** [comment]
@Ko-Khan As per the below, following AB3 code need not be considered as reuse.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/679b60db-ee06-4b2f-acdd-85ac1755d4e8)

**Comment by Ko-Khan** [comment]
When they say `ensure such code doesn't appear under your name in the tP code dashboard`, does this mean that classes I added should not contribute to total lines of code written if they reuse AB3 code?

**Comment by damithc** [comment]
> When they say `ensure such code doesn't appear under your name in the tP code dashboard`, does this mean that classes I added should not contribute to total lines of code written if they reuse AB3 code?

@Ko-Khan No, it refers to existing AB3 code, not code you added that follow existing code.
