### ISSUE TITLE
Javadoc coding standard first line

### ISSUE THREAD

**Issue by UdhayaShan1** [nus-cs2103-AY2324S2/forum#84]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39399745/966f269a-d74a-454f-9246-9582107ab7ae)

What does this sentence mean
''In method header comments, the first sentence should start in the form Returns ..., Sends ..., Adds ... (not Return or Returnning etc.)''

Does it mean the first word should be only those three?

**Comment by damithc** [comment]
@UdhayaShan1 'in the form ...'  (i.e., not limited to those three words only)

**Comment by UdhayaShan1** [comment]
Thanks!
