### ISSUE TITLE
Question Regarding Sequence Diagram

### ISSUE THREAD

**Issue by itstrueitstrueitsrealitsreal** [nus-cs2103-AY2324S2/forum#840]
Hi, I wanted to ask if it is acceptable to use ellipsis for brevity's sake in sequence diagrams, as some of the commands we are using are quite long. 
Here's an example to show you what I mean...
<img width="231" alt="Screenshot 2024-04-14 at 5 44 37 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/120318851/fb2e2f00-941e-416b-b491-45c0ee442b6e">
as compared to:
<img width="426" alt="Screenshot 2024-04-14 at 5 47 11 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/120318851/1daaca4e-f9b4-4db7-b195-92fb5d8dd907">
Thanks for your time!

**Comment by damithc** [comment]
@itstrueitstrueitsrealitsreal Yes, you may use `...` to save space, if the omission of the details does not introduce ambiguities into the diagram.

**Comment by itstrueitstrueitsrealitsreal** [comment]
Thanks for the quick clarification Prof.! Closing this issue.
