### ISSUE TITLE
Submission Enquiry

### ISSUE THREAD

**Issue by g-tejas** [nus-cs2103-AY2324S2/forum#841]
![telegram-cloud-photo-size-5-6116349475128720205-y](https://github.com/nus-cs2103-AY2324S2/forum/assets/76802638/99136e2a-3661-4ab8-826a-427f938a1869)
I wanted to ask, is tagging the Release enough to qualify as a "submission" here? Or do we still need to tag a commit with v.1.4?

**Comment by damithc** [comment]
> I wanted to ask, is tagging the Release enough to qualify as a "submission" here?

Yes, that's enough @g-tejas
