### ISSUE TITLE
Reverting a PR due to possible violation of feature freeze

### ISSUE THREAD

**Issue by guanquann** [nus-cs2103-AY2324S2/forum#843]
Hello, our team had updated the default data file by accident. According to the FAQ, we should revert the PR. But we have also merged other PRs and we fear that reverting that particular PR may cause some issues. Can we simply update the PR and change back to the original values? Thanks

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/76832850/7313949c-fe82-4288-b282-1c767168760a)

This is the changes we made previously:
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/76832850/f1f127c5-20bf-4e22-9dea-7e233aeef1c8)

**Comment by damithc** [comment]
@guanquann You can do a new PR to reverse the changes as needed.

**Comment by guanquann** [comment]
Ok thank you.
