### ISSUE TITLE
Git commit messages

### ISSUE THREAD

**Issue by chiralcentre** [nus-cs2103-AY2324S2/forum#845]
Can I check with the teaching team if we will be penalised for not following Git commit message conventions? Currently I noticed that I forgot to capitalise the first word of my commit messages thus far. Is there any way to remedy this before the deadline?

**Comment by damithc** [comment]
@chiralcentre Yes, it is graded. We only check the last 10 commits though.

**Comment by chiralcentre** [comment]
Thank you Prof for the response! Just to clarify, are you referring to the last 10 commits in master for each person, or the last 10 commits in master as a whole?

**Comment by damithc** [comment]
> Thank you Prof for the response! Just to clarify, are you referring to the last 10 commits in master for each person, or the last 10 commits in master as a whole?

@chiralcentre each person. Note that commits of a merged branch become commits of the master branch. So, if you were to merge a branch with 10 of your commits, those 10 commits will be counted as your commits in the master branch.

**Comment by drustanyjt** [comment]
@damithc our team was working on documentation together by going through each line, committing at every few lines of changes, and as a result our most recent commits look something like this:

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/110999129/505766e8-9bef-4a86-96e7-d635deb65f74)

While it technically follows the formatting instructions of messages, would it be better to `reset` and `squash` the repetitive commits into one (for grading purposes)?

**Comment by damithc** [comment]
@drustanyjt Small commits are good. In future, you can make the commit message more descriptive e.g., `Fix typo in DG: haad -> had`
