### ISSUE TITLE
Will fixing dummy data violate feature freeze?

### ISSUE THREAD

**Issue by ThatGirlJam** [nus-cs2103-AY2324S2/forum#847]
Hi, was wondering if fixing dummy data is considered violating the feature freeze? Thanks

**Comment by damithc** [comment]
@ThatGirlJam Not allowed (unless the current version has errors), as per the list below:

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/a71b1cac-ba25-43f5-af33-f0af26c47bcb)

**Comment by ThatGirlJam** [comment]
Okay, thank you !
