### ISSUE TITLE
Minor typo in java standards

### ISSUE THREAD

**Issue by UdhayaShan1** [nus-cs2103-AY2324S2/forum#85]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39399745/f7ede9e6-3e2f-4035-8cd7-79d85fb3aaa0)

getMember_memberNotFount_nullReturned should be getMember_memberNotFound_nullReturned

AND

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39399745/484789e8-95a2-4141-bb65-c0caa4993971)

Should be Returning

**Comment by damithc** [comment]
Thanks for the bug report, @UdhayaShan1 
Fixed.
