### ISSUE TITLE
Are we allowed to add a limit for the input length of the "tag" field?

### ISSUE THREAD

**Issue by Ella-e** [nus-cs2103-AY2324S2/forum#851]
Hi prof,

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/60089102/4679e400-d104-46e1-a4db-061507d98e4e)
Tag is a one word allergy tag for the patient. Currently it doesn't have a limit in length. But if the word is too long, it will gets cut out by the UI with no way to see the full text. Can we change the length limit to the longest word in the world and recommend the users to use abbreviations when the word is very long?

**Comment by damithc** [comment]
@Ella-e In the UG, you can recommend to use short words. Enforcing a limit is may not be urgent, as there is no good reason for users to enter such long words anyway, especially after being cautioned not to. Enforcing the limit can be a future enhancement.

**Comment by Ella-e** [comment]
I see, thank you prof.
