### ISSUE TITLE
Is this considered a feature enhancement or bug fix?

### ISSUE THREAD

**Issue by Wyrkx** [nus-cs2103-AY2324S2/forum#855]
Due to forgetting to add one of the command prefixes to the ArgumentTokenizer one of our commands does not accept an optional argument as of v1.3. However, the UG was also not updated at the time of v1.3. 
Other than the tokenizer, all the other code was in place to utilise the optional argument during v1.3. Would adding the optional argument be considered a feature enhancement or bug fix in this case?

**Comment by damithc** [comment]
@Wyrkx This feature was not fully implemented by v1.3 and also not tested in the PE-D. So, it is not suitable to be included in v1.4. But if you leave the code in the repo, it can be used for other grading components such as code quality and effort.

**Comment by Wyrkx** [comment]
Alright, thank you!
