### ISSUE TITLE
Reposense report

### ISSUE THREAD

**Issue by Ko-Khan** [nus-cs2103-AY2324S2/forum#856]
While looking through my code dash board, I found the following commit:
![Screenshot 2024-04-15 174106](https://github.com/nus-cs2103-AY2324S2/forum/assets/111284975/2ef5832a-0cef-4f93-9e93-ded4163ecf99)
This was caused by removing additional versions of developer guide:
![Screenshot 2024-04-15 174246](https://github.com/nus-cs2103-AY2324S2/forum/assets/111284975/3c357c2b-f860-4391-a1df-e79e69e3d1d9)
Would this affect my tp grading?

**Comment by damithc** [comment]
@Ko-Khan It would not :-)
