### ISSUE TITLE
Is updating logging a violation of the feature freeze?

### ISSUE THREAD

**Issue by yisiox** [nus-cs2103-AY2324S2/forum#858]
Our group might want to add and edit some of the developer facing messages in logging, but we're not sure if it violates the feature freeze.

I'm referring to the course materials given on the feature freeze, but it's not clear to me if this counts under code quality and testing or minor tweaks since the user can potentially see the logging on a terminal.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/107540644/a3b55d73-b10d-4bd2-9f9f-d7842659867a)

**Comment by damithc** [comment]
@yisiox logging is considered an internal implementation detail. So, it is allowed.

**Comment by yisiox** [comment]
@damithc Noted, thank you Prof
