### ISSUE TITLE
Are we allowed to change version number in MainApp?

### ISSUE THREAD

**Issue by ZhiWei1010** [nus-cs2103-AY2324S2/forum#860]
Hi prof @damithc , are we allowed to change the VERSION to 1,4,0 in MainApp?

<img width="866" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/60460444/d1dad283-7a8c-409c-bfc3-93b5cd16ceeb">

**Comment by damithc** [comment]
@ZhiWei1010 Yes.

**Comment by ZhiWei1010** [comment]
Ok thanks prof!
