### ISSUE TITLE
DG on the wesbite does not reflect our DG markdown file

### ISSUE THREAD

**Issue by cheahTJ** [nus-cs2103-AY2324S2/forum#862]
Hi, I would like to check is it a glitch but we cannot seem to see some of our features which are written in the DG markdown file but it is not reflected on the github website for our DG. Could we get some assistance on this?

**Comment by damithc** [comment]
@cheahTJ Can give some more details? exactly what is missing? link to DG/file?
Note that GitHub Pages takes a few minutes to update site.

**Comment by cheahTJ** [comment]
Hi prof @damithc we have 2 features - its implementations and design considerations, the whole appendix (user stories, MSS, product scope) are all missing. And yup prof just an update, the last change to the DG was this morning and we just found out that it is not fully reflecting what we have in our markdown file.

**Comment by damithc** [comment]
hmm... seems the rest of the document appears if you remove these two UML diagrams 🤔 
```
<puml src="diagrams/FindSequenceDiagram.puml" alt="FindSequenceDiagram">

The following activity diagram summarizes what happens when a user inputs a `find` command:

<puml src="diagrams/FindActivityDiagram.puml" alt="FindActivityDiagram">
```

**Comment by cheahTJ** [comment]
Yes prof we just managed to figure that out, thank you so much !!! Will close the thread now.

**Comment by damithc** [comment]
What was the actual problem?

**Comment by camille-readbean** [comment]
Potentially bad behaviour here? 

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/52031118/813e26a3-7d76-4dce-a6f1-f0e5d2d0d49a)


Does not seem to warn on the console

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/52031118/56eca837-9a2f-465a-b352-25ac6e887ee1)


i.e. fail silent

**Comment by damithc** [comment]
@cheahTJ Reason: You forgot to close the tag in those two puml tags. `>` should be `/>`

**Comment by cheahTJ** [comment]
YUP prof the problem was exactly that
