### ISSUE TITLE
Override old submissions

### ISSUE THREAD

**Issue by UdhayaShan1** [nus-cs2103-AY2324S2/forum#863]
To confirm if we wish to override previous submissions, we just submit a new file and the latest is taken?

Thanks!

**Comment by itstrueitstrueitsrealitsreal** [comment]
I would think so, as per the instructions on the site.
<img width="918" alt="Screenshot 2024-04-15 at 11 38 29 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/120318851/f34943b8-2181-405a-9672-adec1190b383">

**Comment by damithc** [comment]
@UdhayaShan1 Yes.

**Comment by UdhayaShan1** [comment]
Sorry just sanity check 😥
