### ISSUE TITLE
Wrong naming convention on Github release v1.4

### ISSUE THREAD

**Issue by meowwtama** [nus-cs2103-AY2324S2/forum#866]
Our group completed the submission on Canvas before the stipulated deadline and we did not make any changes to our final submission. However, we wanted to rename the User Guide from the `[ ]` formatting in the Canvas submission to `User Guide` to make it more intuitive. Will this be possible and will it result in a grade deduction?

**Comment by damithc** [comment]
@meowwtama There was a naming convention for the submission files. It is given in https://nus-cs2103-ay2324s2.github.io/website/schedule/week13/project.html and was also emailed to you a few days ago, for good measure.

**Comment by meowwtama** [comment]
@damithc Just to clarify, I am asking about the User Guide and Developer Guide in the **Github** release. From what I can see, there isn't any specific naming convention for the files on the Github release, only for the Canvas submission. Thus, will it be possible to rename our UG and DG. Or is there not even a need to include the UG and DG in the Github release.

**Comment by damithc** [comment]
> @damithc Just to clarify, I am asking about the User Guide and Developer Guide in the **Github** release. From what I can see, there isn't any specific naming convention for the files on the Github release, only for the Canvas submission. Thus, will it be possible to rename our UG and DG. Or is there not even a need to include the UG and DG in the Github release.

Oh, I see. That didn't cross my mind because uploading them to GitHub wasn't required. So, that will not affect grading.

**Comment by itstrueitstrueitsrealitsreal** [comment]
As per the website:
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/120318851/948ffebe-7a5b-4b60-ac48-a9f672101660)

Although this isn't really clear on if we have to include the UG and DG in the release in any special naming format...

**Comment by meowwtama** [comment]
@damithc Okay thank you a lot prof!

@itstrueitstrueitsrealitsreal Thank you for your input! But what I asked for was pertaining to our UG and DG naming in the Github release and not the naming for the .jar file. Please see above for the prof's response.

I will now close this thread.
