### ISSUE TITLE
Minor bug in peer evaluation

### ISSUE THREAD

**Issue by jyztintan** [nus-cs2103-AY2324S2/forum#867]
Minor typo in the TEAMMATES peer evaluation for the description of "Good" for Q7.

<img width="178" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/98398940/f350b393-abf0-48b5-b081-ecbcc724751f">

I think that it should be "initiative" instead of "initiate".

**Comment by damithc** [comment]
Thanks for the bug report, @jyztintan 
Will fix in future rounds.
