### ISSUE TITLE
RepoSense for .yml files

### ISSUE THREAD

**Issue by drustanyjt** [nus-cs2103-AY2324S2/forum#869]
I noticed that the tP Code Dashboard does not show changes made to some GitHub actions I wrote. I was wondering if RepoSense filters out `.yml` files and/or the `.github` directory from being analyzed?

**Comment by damithc** [comment]
@drustanyjt I've added .yml files to the dashboard configuration. Your work in .yml files should be reflected in there now.

**Comment by drustanyjt** [comment]
Thanks prof @damithc, I see it now!
