### ISSUE TITLE
Minor Typo In TEAMMATES Q6

### ISSUE THREAD

**Issue by itstrueitstrueitsrealitsreal** [nus-cs2103-AY2324S2/forum#870]
There is a minor typo in the word "Exclude" for this question.
Thanks!
<img width="961" alt="Screenshot 2024-04-16 at 12 48 01 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/120318851/a1d916a0-5230-46e7-ab57-2235f3017cdf">

**Comment by damithc** [comment]
Thanks @itstrueitstrueitsrealitsreal 
Will fix for future rounds.
