### ISSUE TITLE
Pushing changes to local repo

### ISSUE THREAD

**Issue by jeong-jaeho** [nus-cs2103-AY2324S2/forum#871]
The website states not to update the code in the repo.
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/109773933/a918b734-b636-4a7f-b677-29431581fe7a)

Is it okay for me to pull all the changes from remote repo and push them into my local repo?
Everything was merged and submitted in time, it's just that my local repo is not updated with the most recent change in the remote repo.

**Comment by damithc** [comment]
@jeong-jaeho Yes, that should be fine.
