### ISSUE TITLE
Suggestion: modify the script to specify the title as "[TesterA]" instead of "[Tester A]" (next semester)

### ISSUE THREAD

**Issue by E0735389** [nus-cs2103-AY2324S2/forum#872]
So that we can use GitHub search feature to accurately filter the issues raised by that tester. At the moment it can be misleading because even with the quotes around, the words in the search query are still separately searched. (And "a" is a common word to appear.)

**Comment by damithc** [comment]
@E0735389 Good suggestion. In the email we sent earlier, we gave links that accurately lists bug reports reported by each tester.
