### ISSUE TITLE
tp Java CI failed, would that affect any part of our grading? And should/can we do anything about it? 

### ISSUE THREAD

**Issue by lynnetteeee** [nus-cs2103-AY2324S2/forum#873]
Hi, our group realised our tp's overall Java CI failed on the dashboard after we submitted our tp deliverables, and after investigating, we realise it is due to a failed Java CI action that we did not expect, since all the Java CI of our PRs passed. 

<img width="1503" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/103313573/006a5a9a-09e2-4103-b1ce-b0efdaa5ca18">

<img width="1510" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/103313573/d87720ac-26e1-4c49-be70-0d2af4c1066a">

Although the above shows a failed build, when we checked the PR #219, as shown in the "Checks" tab , it actually passed all the checks when it was merged, so we are unsure of how the build failed as well.
<img width="1512" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/103313573/df0105b7-2787-495d-b96a-c4d85071d4c4">

May we seek the advice of the teaching team on what we should/can do about the failing Java CI? And will it affect any part of our grading? Thank you 🙏 .

**Comment by damithc** [comment]
@lynnetteeee CI failing does not affect the grade.

**Comment by aureliony** [comment]
Seeing that the error was error 500 from the zulu server, you could click the "Re-run all jobs" button to get the green tick.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39163684/011383e9-2bd6-47cd-8de5-102b902ef19e)

**Comment by lynnetteeee** [comment]
Thank you for clarifying, Prof @damithc !

**Comment by lynnetteeee** [comment]
Oh, I just tried it and it worked out. Thank you for the tip @aureliony!
