### ISSUE TITLE
Are we allowed to close the tutorial add remark prs?

### ISSUE THREAD

**Issue by ZhiWei1010** [nus-cs2103-AY2324S2/forum#875]
Hi prof, are we allowed to close the add remark tutorial PRs?

Also, do we need to close all remaining issues including the issues from PE-D that are invalid (i.e. our repo should not have any open issues and PR or is-it ok to leave them)

**Comment by damithc** [comment]
> Hi prof, are we allowed to close the add remark tutorial PRs?


@ZhiWei1010  yes, that was always allowed.

> Also, do we need to close all remaining issues including the issues from PE-D that are invalid (i.e. our repo should not have any open issues and PR or is-it ok to leave them)

You should close all PRs/Issues tagged with v1.4 and close the milestone as well (i.e., wrap up v1.4). Closing other issues/PRs is up to you.

**Comment by ZhiWei1010** [comment]
Thanks for the clarifications prof!
