### ISSUE TITLE
Clarifying on the use of ALT in sequence diagrams

### ISSUE THREAD

**Issue by yleeyilin** [nus-cs2103-AY2324S2/forum#876]
Hi, the below screenshot is a picture from one of the tutorial slides which states that because of the opt box, we may not need to run both set() and reset().
![telegram-cloud-photo-size-5-6120827910542703566-y](https://github.com/nus-cs2103-AY2324S2/forum/assets/116061001/b7d3b1c4-96f3-413d-85fc-9b6d68d732cf)

However, in the screenshot of the textbook below, it is written that "it is acceptable for none of the alternative paths to be executed". This means that we do not really need opt box and alt alone will enable us to not need to run both set() and reset(). Is this a correct interpretation? I was slightly confused as it seems to differ from what was implied in the tutorial screenshot above. 
![telegram-cloud-photo-size-5-6120827910542703567-y](https://github.com/nus-cs2103-AY2324S2/forum/assets/116061001/89b26256-93fd-4e31-b58c-97d22db8b04b)

**Comment by UdhayaShan1** [comment]
I think the 'none of the altenative' isnt specific to the picture, the `else` could be some other condition. Here I believe at least one of the path must be executed, since there is no opt.

The opt is separate and still important regardless, add an opt and yes even with `else` its possible that we wont execute anything as we may not meet the opt condition.

**Comment by E0735389** [comment]
The "none of the alternative" means: "It is possible to omit the `else` block".

For example, if `a` is an integer, it is possible for an `alt` frame to have `[a==1]` and `[a==2]`, without `[else]`.

In that specific tutorial question however, you're already assuming `forward==!backward`, so if it were to get inside the `opt` box, at least one of the two branch must be executed.

**Comment by yleeyilin** [comment]
Ah okay thank you! @E0735389
