### ISSUE TITLE
Quiz 9P1 : Q28

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#879]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/73015364/5a19988e-d28e-4b3f-8cbc-65d4c3f7496e)

Why is this wrong?

**Comment by itstrueitstrueitsrealitsreal** [comment]
Square brackets are missing from branch conditions.

**Comment by baskargopinath** [comment]
thanks @itstrueitstrueitsrealitsreal
