### ISSUE TITLE
Using checkstyle.jar with google_checks.xml

### ISSUE THREAD

**Issue by lihaoquan** [nus-cs2103-AY2324S2/forum#88]
Hello, I tried to use [Checkstyle](https://github.com/checkstyle/checkstyle/tree/master) to check the coding standard of my iP.

The xml file that it is checking against is [google_checks.xml](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml).

I used this config file as the [Java coding standard](https://se-education.org/guides/conventions/java/intermediate.html) stated the following:

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/64543157/3dfd64da-a281-4142-9e90-e493f4d1d038)

However, when I ran the checkstyle.jar file, I encountered many indentation errors which came from the following sections in the [google_checks.xml](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml) file:
```xml
<module name="Indentation">
    <property name="basicOffset" value="2"/>
    <property name="braceAdjustment" value="2"/>
    <property name="caseIndent" value="2"/>
    <property name="throwsIndent" value="4"/>
    <property name="lineWrappingIndentation" value="4"/>
    <property name="arrayInitIndent" value="2"/>
</module>
...
<module name="LineLength">
    <property name="fileExtensions" value="java"/>
    <property name="max" value="100"/>
    <property name="ignorePattern" value="^package.*|^import.*|a href|href|http://|https://|ftp://"/>
</module>
```

I noticed that this was different from what was specified in the [Java coding standard](https://se-education.org/guides/conventions/java/intermediate.html) page:

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/64543157/c9781614-9090-4302-b366-9d66b01f2f65)

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/64543157/ef05b3b0-d620-4a21-84ac-2e15b6a66b27)

May I know if the following modifications are sufficient in utilizing [Checkstyle](https://github.com/checkstyle/checkstyle/tree/master) to check the formatting of my codes?
```xml
<module name="Indentation">
    <property name="basicOffset" value="4"/>
    <property name="braceAdjustment" value="4"/>
    <property name="caseIndent" value="0"/>
    <property name="throwsIndent" value="4"/>
    <property name="lineWrappingIndentation" value="4"/>
    <property name="arrayInitIndent" value="4"/>
</module>
...
<module name="LineLength">
    <property name="fileExtensions" value="java"/>
    <property name="max" value="120"/>
    <property name="ignorePattern" value="^package.*|^import.*|a href|href|http://|https://|ftp://"/>
</module>
```

Thank you.

**Comment by lihaoquan** [comment]
I just noticed that there is an  increment for **A-Checkstyle** in week 4, is it fine if I start using it now in week 3?

**Comment by damithc** [comment]
@lihaoquan Adding Checkstyle is an optional increment scheduled in week 4. If you are keen to add it earlier, you can follow the instructions given there https://nus-cs2103-ay2324s2.github.io/website/schedule/week4/project.html

--------

> I used this config file as the [Java coding standard](https://se-education.org/guides/conventions/java/intermediate.html) stated the following:
> 
> ![image](https://private-user-images.githubusercontent.com/64543157/299998609-3dfd64da-a281-4142-9e90-e493f4d1d038.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNzcyNTUsIm5iZiI6MTcwNjI3Njk1NSwicGF0aCI6Ii82NDU0MzE1Ny8yOTk5OTg2MDktM2RmZDY0ZGEtYTI4MS00MTQyLTllOTAtZTQ5M2Y0ZDFkMDM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDEzNDkxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiM2UyZGNjMjQ2ZWJjYTU5ODgzMzc2ODE3YmRkNjJhZTU3MGE2ZWJlMTI4ZDNjZWQ1M2RmNDRiYmZmNzYwN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.46KUtoZAA7Y-7mOk9SMY7WyGrf42kuS6ua2OdNJU-w8)

Google style is a _fallback_, to be used only when our coding standard doesn't specify something. So, it cannot be used directly in place of our coding standard (theirs is not a superset of ours).

**Comment by lihaoquan** [comment]
> @lihaoquan Adding Checkstyle is an optional increment scheduled in week 4. If you are keen to add it earlier, you can follow the instructions given there https://nus-cs2103-ay2324s2.github.io/website/schedule/week4/project.html
> 
> > I used this config file as the [Java coding standard](https://se-education.org/guides/conventions/java/intermediate.html) stated the following:
> > ![image](https://private-user-images.githubusercontent.com/64543157/299998609-3dfd64da-a281-4142-9e90-e493f4d1d038.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNzcyNTUsIm5iZiI6MTcwNjI3Njk1NSwicGF0aCI6Ii82NDU0MzE1Ny8yOTk5OTg2MDktM2RmZDY0ZGEtYTI4MS00MTQyLTllOTAtZTQ5M2Y0ZDFkMDM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDEzNDkxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiM2UyZGNjMjQ2ZWJjYTU5ODgzMzc2ODE3YmRkNjJhZTU3MGE2ZWJlMTI4ZDNjZWQ1M2RmNDRiYmZmNzYwN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.46KUtoZAA7Y-7mOk9SMY7WyGrf42kuS6ua2OdNJU-w8)
> 
> Google style is a _fallback_, to be used only when our coding standard doesn't specify something. So, it cannot be used directly in place of our coding standard (theirs is not a superset of ours).

Thank you for the clarification. I will use the checkstyle xml config from the AB3 project.
