### ISSUE TITLE
Peer Eval

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#881]
<img width="740" alt="Screenshot 2024-04-18 at 9 21 06 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/73015364/0895c72b-2a40-4d07-af85-8f7db57b686f">

Can i leave this blank if i agree with claimed contributions? Or do i have to put "NIL" in the answer box. Bcoz i dont see an (optional) tag

Also isnt this not applicable cuz PPP is optional this sem?

**Comment by damithc** [comment]
Yes, you may leave it blank, @bgopi23

**Comment by baskargopinath** [comment]
thanks prof @damithc
