### ISSUE TITLE
Clarification on duplicate issue.

### ISSUE THREAD

**Issue by drustanyjt** [nus-cs2103-AY2324S2/forum#883]
### Part 1
Say I'm a tester and I find some functionality bug through testing some command with the following integer inputs:

- `1` (works as intended)
- `0` (response not defined, command does not seem to work)
- `-1` (response not defined, command does not seem to work)

If the DG does not mention enough details about invalid inputs, I might assume that `0` and `-1` should fall into different equivalence partitions. Would it be reasonable to report them as 2 different issues during the PE? (since there's no penalty for reporting self-duplicates does it even matter?)

### Part 2
On the other hand, if I'm a dev and I receive these two as separate bugs, while it is possible to write two cases that handle `0` input and `-1` input independently, it feels like in real life, if I can show `0` and `-1` should reasonably fall under the same equivalence partition, then I would want to make one change that solves both cases. Would it make sense to mark the issue as a duplicate?

**Comment by damithc** [comment]
> ### Part 1
> Say I'm a tester and I find some functionality bug through testing some command with the following integer inputs:
> 
> * `1` (works as intended)
> * `0` (response not defined, command does not seem to work)
> * `-1` (response not defined, command does not seem to work)
> 
> If the DG does not mention enough details about invalid inputs, I might assume that `0` and `-1` should fall into different equivalence partitions. Would it be reasonable to report them as 2 different issues during the PE? (since there's no penalty for reporting self-duplicates does it even matter?)

@drustanyjt Yes, if in doubt, report as separate bugs.

> ### Part 2
> On the other hand, if I'm a dev and I receive these two as separate bugs, while it is possible to write two cases that handle `0` input and `-1` input independently, it feels like in real life, if I can show `0` and `-1` should reasonably fall under the same equivalence partition, then I would want to make one change that solves both cases. Would it make sense to mark the issue as a duplicate?

Yes, if your argument that fixing one automatically fixes the other, they will be accepted as one bug.

**Comment by drustanyjt** [comment]
Thanks prof @damithc!
