### ISSUE TITLE
Bug Quality

### ISSUE THREAD

**Issue by drustanyjt** [nus-cs2103-AY2324S2/forum#884]
The course textbook says this on bug quality for the pe:

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/110999129/bd8ac894-1e55-4f92-9964-f848c2d1b6ef)

As a developer I have the option to mark if bugs are incorrect are not, but it doesn't seem to have any mention about bug quality (except giving BOD to tester and try as hard as possible to replicate bugs).

Are quality of bug reports graded in some other way by someone else? While some of these seem to be implicitly tested when the severity level and reproducibility of a bug are contested by devs, there does not really seem to be a way to check for non-confrontational tone.

**Comment by damithc** [comment]
@drustanyjt As you mentioned, the lower the quality of the bug report, the higher the chance of the bug being rejected (or benefit of the doubt given to the dev team). 
In addition, if a tester submitted many poor quality bug reports that ended up with no consensus from the dev team, this will be flagged during the moderation phase for a possible additional penalty.

**Comment by drustanyjt** [comment]
Thanks prof @damithc!
