### ISSUE TITLE
Query on PE bug

### ISSUE THREAD

**Issue by Li-Zizhen** [nus-cs2103-AY2324S2/forum#885]
If the program can do something more than specified in the user guide, is that an error?

Example 1: If my input contains two 'n/' and the program runs but only uses the first name input. Is this an error?

Or 

Example 2: the UG says inputting student INDEX can delete the student, but I found out inputting student ID can also delete the student. Is this an error?

Or

Example 3: The UG says use a or d to sort, however I found A and D are also valid input, is this error?

**Comment by damithc** [comment]
@Li-Zizhen we don't want to pre-judge specific cases until the tester and the dev team had a chance to give their opinion. That said, in some cases the app doing something the UG does not mention can be considered a documentation bug, unless the missing info is considered obvious and not worth specifying.

**Comment by Li-Zizhen** [comment]
Thank you.
