### ISSUE TITLE
Severity of incorrect UML notation

### ISSUE THREAD

**Issue by tankh99** [nus-cs2103-AY2324S2/forum#886]
What is the severity of incorrect UML notations that are expected to be simple, such as missing out <<interface>> for an interface? Is the severity higher than less obvious notation errors?

**Comment by damithc** [comment]
@tankh99 given below is our guideline :
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/4231352a-fa7f-4299-a09d-cd558440bdba)

So it depends. Can be `severity.Low` or above.

**Comment by tankh99** [comment]
Noted, thank you prof!
