### ISSUE TITLE
General questions

### ISSUE THREAD

**Issue by tankh99** [nus-cs2103-AY2324S2/forum#887]
1. Quiz 11 Q16: How can MVC be different on Web vs on Mobile? <img width="596" alt="Screenshot 2024-04-19 at 1 07 42 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/56617918/41620c2c-0f7e-4c43-b1f4-e9b5373ad2a5">

3. Do we really need to draw an arrow from the left side to create the Dog class here? Can we just omit the arrow to the class dog?
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/56617918/4a7336ce-568e-42ef-9534-4671096e94f6)

4. Let’s say that in a class diagram, we have a class B which inherits an abstract method foo() from an abstract class A. IF this class B omits the method foo(), is the class diagram still valid? Main concern here is that since we omit foo() in the inherited concrete class, we might be omitting details like whether the function is abstract or concrete in the concrete class. 
   - Or can we just assume that since B is a concrete class, the abstract method is also a concrete method 
5. How does XP programming enable developers to quickly provide solutions immediately rather than later if the basis of XP is to prioritise refactoring?
6. What is an example of a project with a depth-first iterative model approach?
7. Are all types of navigability not allowed in CCDs? 
   - What about association roles?
   - What about association labels with arrows?
8. In a use case, what if system is an actor? Is it strictly always outside the system?

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/56617918/e2725a1e-ce85-4419-86b3-064b8fdae316)

**Comment by damithc** [comment]
@tankh99 Good questions. Maybe better to post as separate questions so that each can be discussed and resolved separately?

**Comment by tankh99** [comment]
@damithc Good point, I have posted them as separate questions
