### ISSUE TITLE
Are user stories and use cases supposed to be implemented?

### ISSUE THREAD

**Issue by tankh99** [nus-cs2103-AY2324S2/forum#888]
Are any of the following valid bugs to report?
- User stories that are written in the documentation, but not actually implemented? 
   - What if it is inside the future enhancements? Is it then valid?
-  What if use cases are missing for user stories?
- What if use cases include features that are not mentioned in the user stories?

**Comment by damithc** [comment]
@tankh99 Sorry, I missed this earlier.

> * User stories that are written in the documentation, but not actually implemented?
>   
>   * What if it is inside the future enhancements? Is it then valid?

User stories are  listed in the requirements, which is not limited to the current version but covers things yet to be implemented as well.

> * What if use cases are missing for user stories?

There is no rule to say every user story must have a use case. We we use cases when they add value.

> * What if use cases include features that are not mentioned in the user stories?

We started documenting requirements with listing user stories, which is a lightweight  way to gather and prioritize requirements. So, if done sincerely, every feature should have started its life in a user story.

**Comment by tankh99** [comment]
> @tankh99 Sorry, I missed this earlier.
> 
> > * User stories that are written in the documentation, but not actually implemented?
> >   
> >   * What if it is inside the future enhancements? Is it then valid?
> 
> User stories are listed in the requirements, which is not limited to the current version but covers things yet to be implemented as well.
> 
> > * What if use cases are missing for user stories?
> 
> There is no rule to say every user story must have a use case. We we use cases when they add value.
> 
> > * What if use cases include features that are not mentioned in the user stories?
> 
> We started documenting requirements with listing user stories, which is a lightweight way to gather and prioritize requirements. So, if done sincerely, every feature should have started its life in a user story.

Thank you prof, I understand now.
