### ISSUE TITLE
Quiz 11 Q16

### ISSUE THREAD

**Issue by tankh99** [nus-cs2103-AY2324S2/forum#889]
Quiz 11 Q16: How can MVC be different on Web vs on Mobile? <img width="596" alt="Screenshot 2024-04-19 at 1 07 42 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/56617918/41620c2c-0f7e-4c43-b1f4-e9b5373ad2a5">

**Comment by E0735389** [comment]
It's in the textbook...

> There are many variations of the MVC model used in different domains. For example, the one used in a desktop GUI could be different from the one used in a web application.

and you can also find [places](https://stackoverflow.com/questions/32342864/applying-mvc-with-javafx) saying the same thing...

> There are many different variations of this pattern. In particular, "MVC" in the context of a web application is interpreted somewhat differently to "MVC" in the context of a thick client (e.g. desktop) application (because a web application has to sit atop the request-response cycle). This is just one approach to implementing MVC in the context of a thick client application, using JavaFX. 

but I don't really understand it either.

**Comment by tankh99** [comment]
@E0735389 I do know that the usually, the V and C differ across web and mobile. E.g. Views in web refer to pages while in mobile, they refer to screens, however, I'm not sure if this was what the question was talking about

@damithc, could we get your opinion on this?

**Comment by damithc** [comment]
> and you can also find [places](https://stackoverflow.com/questions/32342864/applying-mvc-with-javafx) saying the same thing...

Yup. as add onto what's mentioned in that s/o post, MVC can span a wide area of the system, and hence, the overall architecture of the system (which vary widely from desktop to Web to mobile) can influence the way MVC is implemented. In a desktop app, everything could be in the same runtime, and anything can call anything else directly. In a Web app, different parts of the app can be on different machines altogether, and communication among them may not be as simple as calling a method. Similarly, the way Android apps are architectured could be different from iOS apps, and Web apps using Angular framework could work very differently from those using React, and so on. So, the exact implementation of MVC can vary, although the underlying spirit might remain the same.

Also note [this Wikipedia mention of MVC variants](https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller#:~:text=The%20MVC%20pattern%20subsequently%20evolved,adapted%20MVC%20to%20different%20contexts.).

**Comment by tankh99** [comment]
Noted, thank you prof
