### ISSUE TITLE
Sequence diagram constructor

### ISSUE THREAD

**Issue by tankh99** [nus-cs2103-AY2324S2/forum#890]
Do we really need to draw an arrow from the left side to create the Dog class here? Can we just omit the arrow to the class dog?
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/56617918/4a7336ce-568e-42ef-9534-4671096e94f6)

**Comment by E0735389** [comment]
As far as I can see, the highlighted code calls the constructor, so it would be suitable to draw the arrow.

Simplification (omitting unimportant detail) is possible, but that may mislead the reader into thinking that the object `d` has always been there.

**Comment by tankh99** [comment]
This makes sense, thank you @E0735389

**Comment by damithc** [comment]
@E0735389's answer is correct.
The Dog object is created during this interaction. You can omit that object entirely, to simplify. But if you include it in the diagram, omitting the construction of it can mislead the reader to think it existed from the beginning.
