### ISSUE TITLE
Omission of abstract method in class diagram

### ISSUE THREAD

**Issue by tankh99** [nus-cs2103-AY2324S2/forum#891]
Let’s say that in a class diagram, we have a class B which inherits an abstract method foo() from an abstract class A. IF this class B omits the method foo(), is the class diagram still valid? Main concern here is that since we omit foo() in the inherited concrete class, we might be omitting details like whether the function is abstract or concrete in the concrete class. 
   - Or can we just assume that since B is a concrete class, the abstract method is also a concrete method

**Comment by damithc** [comment]
Keep in mind that a class can omit members not relevant to the purpose of the diagram. So, depends on the purpose of the diagram. 
In the exam, we'll specify which details should be included.

**Comment by tankh99** [comment]
Noted, thank you @damithc
