### ISSUE TITLE
Example of depth-first iterative model?

### ISSUE THREAD

**Issue by tankh99** [nus-cs2103-AY2324S2/forum#893]
What is an example of a project with a depth-first iterative model approach? I can only imagine that a project would iteratively build fleshed out parts of the application in each iteration, and then at the final iteration, integrate them all together. 

A separate question, would this then be equivalent to the big bang approach?

**Comment by damithc** [comment]
@tankh99 Thanks for  raising this question, and the other similar questions you raised recently. Let's give the class a few more days to take part in the discussion. Ping me if not resolved at least 2 days before the exam.

**Comment by tankh99** [comment]
@damithc Bump

**Comment by damithc** [comment]
> What is an example of a project with a depth-first iterative model approach? I can only imagine that a project would iteratively build fleshed out parts of the application in each iteration, and then at the final iteration, integrate them all together.

a) There is no need to wait till the final iteration to integrate. The new component can be integrated to the product as it is built.

b) Another example of depth-first is to focus on one feature at a time. In the tP, if you focused v1.2 on completing the `add` command entirely  (with all bells and whistles), v1.2 on the `delete` command, and so on ...


> A separate question, would this then be equivalent to the big bang approach?

Not necessarily, as per (a) above

**Comment by tankh99** [comment]
Thank you!
