### ISSUE TITLE
Navigabilities in CCDs

### ISSUE THREAD

**Issue by tankh99** [nus-cs2103-AY2324S2/forum#894]
Are all types of navigability not allowed in CCDs? 
   - What about association roles?
   - What about association labels with arrows?

**Comment by damithc** [comment]
> Are all types of navigability not allowed in CCDs?

Yes, not allowed.

> * What about association roles?
> * What about association labels with arrows?

Both allowed.

**Comment by tankh99** [comment]
> > Are all types of navigability not allowed in CCDs?
> 
> Yes, not allowed.
> 
> > * What about association roles?
> > * What about association labels with arrows?
> 
> Both allowed.

How is it that association roles and association labels with arrows are not actually considered as navigabilities? Don't they both represent a direction?

**Comment by itstrueitstrueitsrealitsreal** [comment]
I think that navigabilities and labels are different with regards to navigabilities referring to a class containing a reference to another class, whereas labels are used to denote roles that objects have with relation to each other.

**Comment by tankh99** [comment]
I see, thanks @itstrueitstrueitsrealitsreal and @damithc

**Comment by damithc** [comment]
> I think that navigabilities and labels are different with regards to navigabilities referring to a class containing a reference to another class, whereas labels are used to denote roles that objects have with relation to each other.

Yes, navigabilities, roles, and labels, are independent of each other. Roles and labels describe the relationship, not the direction of the object reference. Labels have a direction too (denoted by the triangle), but that is just tells us which direction to read it.
