### ISSUE TITLE
Clarification regaring PE later

### ISSUE THREAD

**Issue by cheahTJ** [nus-cs2103-AY2324S2/forum#896]
Hi all, may I ask with regards to these following questions for the PE later:

1. Am I able to use my hand-written notes (e.g. notes on activity diagrams, sequence diagrams etc) while doing the PE? 
2. Would it be a hard timing for each phases of testing, when the first 1 hour is reached, the invigilator will ask us to stop doing product testing and move to the evaluation of documents etc?

**Comment by damithc** [comment]
> * Am I able to use my hand-written notes (e.g. notes on activity diagrams, sequence diagrams etc) while doing the PE?

@cheahTJ  Yes.

> * Would it be a hard timing for each phases of testing, when the first 1 hour is reached, the invigilator will ask us to stop doing product testing and move to the evaluation of documents etc?

Yes. Any further changes to a bug report after the deadline will invalidate the bug report automatically.

**Comment by cheahTJ** [comment]
Got it, thank you prof!
