### ISSUE TITLE
Typo in Admin: tP: Practical exam

### ISSUE THREAD

**Issue by camille-readbean** [nus-cs2103-AY2324S2/forum#899]
```
response.NotInScope: It is a valid issue but not something the team should be penalized for e.g., it was not related to features
   delivered in v1.4 or lower priority than the work already doen in v1.4.  
```

**doen**
Under
Instructions for Reviewing Bug Reports > Apply one of these labels >Response Labels: > response.NotInScope  
  
https://nus-cs2103-ay2324s2.github.io/website/admin/tp-pe.html#:~:text=Get%20CATcher%20%27warmed%2Dup%27

**Comment by damithc** [comment]
Thanks @camille-readbean 
Will fix in the next deployment.
