### ISSUE TITLE
Broken PowerPoint embedding

### ISSUE THREAD

**Issue by wilsonwid** [nus-cs2103-AY2324S2/forum#9]
## Description
There appears to be a broken PowerPoint embedding at this link:
[https://nus-cs2103-ay2324s2.github.io/website/book/revisionControl/remoteRepositories/](https://nus-cs2103-ay2324s2.github.io/website/book/revisionControl/remoteRepositories/). Moreover, hovering the mouse over the embedding causes a close button to appear on the top left that covers part of the text.

<img width="911" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/87320062/b0ac0e20-a6c7-4592-95f3-2fdb658119cd">

Edit: This also appears here: [https://nus-cs2103-ay2324s2.github.io/website/schedule/week2/topics.html#w2-4-rcs-remote-repos](https://nus-cs2103-ay2324s2.github.io/website/schedule/week2/topics.html#w2-4-rcs-remote-repos)

**Comment by damithc** [comment]
@wilsonwid Works for me (Chrome, on Windows).

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/5e018a1b-fc23-4857-913b-16000cba545f)

Embedded slides are best viewed in Chrome. 

The `X` button is expected behavior, BTW.

**Comment by wilsonwid** [comment]
I see, thank you Prof!
