### ISSUE TITLE
"[Optional] Comment on your response" field is lost on submit?

### ISSUE THREAD

**Issue by E0735389** [nus-cs2103-AY2324S2/forum#901]
on TEAMMATES, I type in some comment, then click submit, then I cannot recover the comment anywhere.

This will inconvenience the user, because the comment is needed to give to Question 2 (feedback for phase 3 of PE), but it is not unusual for the user to give the comment; then after clicking submit the user cannot copy paste to question 2 anymore.

(would `type.FunctionalityBug` `severity.Medium` be suitable for this one?)

**Comment by E0735389** [comment]
Looks like same browser incompatibility issue as #902.

**Comment by damithc** [comment]
@E0735389 Thanks for raising this. Will pass this info to the TEAMMATES team.
