### ISSUE TITLE
Data loss for free form questions

### ISSUE THREAD

**Issue by E0735389** [nus-cs2103-AY2324S2/forum#902]
I already submit all questions, but on refreshing the page, several questions (those that does not contain any combo box) turn blue again.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/97508964/8e3c167d-b532-4b35-af9b-c13697f9effc)

Can the data be recovered? (unfortunately I didn't download proof of submission either.)

**Comment by E0735389** [comment]
Looks like this is caused by some browser incompatibility issue.

That having said, I think TEAMMATES should have some safeguarding mechanism to detect if the submission is empty. This issue goes unnoticed for me the whole semester.

**Comment by E0735389** [comment]
Apparently caused by https://github.com/tinymce/tinymce/issues/9462 .

Hm... in that case it would be preferable for TEAMMATES to detect the bug instead of suppress it. Plus showing warning message "the text is empty".

**Comment by damithc** [comment]
@E0735389 The color indication is not working properly due to a race condition in how the page is loaded. The answer you submitted is still there. You should be able to see the answer if you expand the blue panels.

**Comment by E0735389** [comment]
I see. But at the same time the data itself is also lost (because of the issue linked above and that I was using an old browser). Switching to a supported browser makes it work (that the entered data is included in the proof of submission).

I think it would be preferable if TEAMMATES give a warning/error message if the submitted response is empty (which is the case for me when the error happens).

**Comment by damithc** [comment]
@E0735389 Thanks for raising this. Will pass this info to the TEAMMATES team.
