### ISSUE TITLE
Quiz 6 Question 22 Enquiry

### ISSUE THREAD

**Issue by Jaspertzx** [nus-cs2103-AY2324S2/forum#903]
In Quiz 6 Qns 22, why this this False? 
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/64065603/b0b0c7d2-b6f9-425d-8a65-f7362fe15369)

What if the object was de-referenced in the newGame() function, something like:
```
Minefield minefield = new Minefield();
... ... ...
Minefield minefield2 = new Minefield();
minefield  = minefield2;
```

Won't the first minefield object be de-referenced and deleted?
Or is it because there activation bar for the Minefield constructor is wrong and therefore the entire thing is wrong?

**Comment by E0735389** [comment]
The problem is that the lifeline must not continue past the X. https://nus-cs2103-ay2324s2.github.io/website/se-book-adapted/chapters/uml.html#object-deletion

**Comment by Jaspertzx** [comment]
Got it, thanks!
