### ISSUE TITLE
Finding 4 bugs is enough for full mark?

### ISSUE THREAD

**Issue by E0735389** [nus-cs2103-AY2324S2/forum#904]
In the textbook:

> For example, finding half of the bugs of that product or 4 bugs, whichever the lower, could earn you full marks.

Isn't this really low? Or does "could" mean "in some situation" such as "they're all `priority.High` and all correctly categorized"?

------

Speaking of which, regarding this part:

> You may report grammar issues as bugs but note that minor grammar issues that don't hinder the reader are allowed to be categorized as response.NotInScope (by the receiving team) -- such bugs earn only small amount or credit for the tester (hence, do not waste time reporting too many minor grammar errors).

If they adds up linearly (e.g. 5 NotInScope = 1 severity.Low, I don't know the grading criteria) wouldn't it still be beneficial?

For example if it takes on average 2 minutes to find and report a grammar bug, and 11 minutes to find and report a severity.Low bug, it would be beneficial to report grammar bug, isn't it?

**Comment by damithc** [comment]
> In the textbook:
> 
> > For example, finding half of the bugs of that product or 4 bugs, whichever the lower, could earn you full marks.
> 
> Isn't this really low? Or does "could" mean "in some situation" such as "they're all `priority.High` and all correctly categorized"?

Yes, depends on the nature of the bugs.  


> > You may report grammar issues as bugs but note that minor grammar issues that don't hinder the reader are allowed to be categorized as response.NotInScope (by the receiving team) -- such bugs earn only small amount or credit for the tester (hence, do not waste time reporting too many minor grammar errors).
> 
> If they adds up linearly (e.g. 5 NotInScope = 1 severity.Low, I don't know the grading criteria) wouldn't it still be beneficial?
> 
> For example if it takes on average 2 minutes to find and report a grammar bug, and 11 minutes to find and report a severity.Low bug, it would be beneficial to report grammar bug, isn't it?

There are safeguards to detect anomalies such as reporting a high number o bugs of a certain characteristics (e.g., low value bugs, non-reproducible bugs, rejected bugs,), high number of disputes etc. which we will then examine separately and moderate marks if necessary.
