### ISSUE TITLE
Typos in TEAMMATES form

### ISSUE THREAD

**Issue by E0735389** [nus-cs2103-AY2324S2/forum#905]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/97508964/6fe18e5c-81d8-4ab0-81c3-81c95ff0bf59)

Morph option is no longer allowed.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/97508964/ee4d7b7a-328d-4f6d-b83d-b6fa8e5995d6)

Two typos here.

**Comment by damithc** [comment]
Thanks @E0735389 
Fixed (for future semesters)
