### ISSUE TITLE
Mock Paper : Q1

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#907]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/73015364/e985323e-365f-4a54-87c5-34e69bd185c1)

For A2, is "The software must only allow NUS students to upload files" a NFR?

**Comment by baskargopinath** [comment]
I feel that scoping the system to only allow a certain target user to use it could be an NFR but im not sure

**Comment by damithc** [comment]
> For A2, is "The software must only allow NUS students to upload files" a NFR?

@bgopi23 Yes, that one goes into the NFR territory.

**Comment by baskargopinath** [comment]
@damithc then if we follow that logic 

cant we interpret this as a NFR as well

` the software must allow students to upload files`

we could read it as the software must `only let students` upload files

**Comment by damithc** [comment]
> we could read it as the software must `only let students` upload files

Don't insert arbitrary 'only'ies into the sentence :-)

If you do, there can be several other interpretations as well:

only the software must allow students to upload files
the software must allow only students to upload files
the software must allow students to only upload files
the software must allow students to upload only files

**Comment by baskargopinath** [comment]
good point! thank u prof @damithc
