### ISSUE TITLE
Custom class names for A-MoreOOP

### ISSUE THREAD

**Issue by wilsonwid** [nus-cs2103-AY2324S2/forum#91]
Are we allowed to customise class names for the `A-MoreOOP` level if we have made something similar to the classes listed there in the past?

**Comment by wilsonwid** [comment]
Additional question: should we cite the CS2103 textbook/webpage if we use content inspired from it in the iP (e.g., the code sample seen in the `A-MoreOOP` section)?

**Comment by damithc** [comment]
> Are we allowed to customise class names for the `A-MoreOOP` level if we have made something similar to the classes listed there in the past?

@wilsonwid Yes, class names are up to you.


> Additional question: should we cite the CS2103 textbook/webpage if we use content inspired from it in the iP (e.g., the code sample seen in the `A-MoreOOP` section)?

No need to cite our own textbook or course website.

**Comment by wilsonwid** [comment]
Thank you Prof @damithc !
