### ISSUE TITLE
What elements are considered "Optional" for UML diagrams

### ISSUE THREAD

**Issue by delishad21** [nus-cs2103-AY2324S2/forum#911]
The textbook says that "To reduce clutter, optional elements (e.g, activation bars, return arrows) may be omitted if the omission does not result in ambiguities or loss of relevant information."  The textbook does not seem to give a comprehensive list of what are considered "optional" elements.

Specifically, a tester identified that our group omitted an object deletion in a sequence diagram but the omission does not take away from what we wanted to describe with the diagram. Should this just be a cosmetic error? Or is object deletion not considered an optional element that can be omitted?

**Comment by damithc** [comment]
@delishad21 To give a general answer, it is fine to omit elements not important to the purpose of the diagram (or if the cost of including  it is not worth the benefits).  

The above applies to the deletion notation in sequence diagrams as well. So yes, it can be omitted.

In this case, it's a matter of whether you can convince the tester (or failing that, the teaching team) that the deletion is not important to the purpose of the diagram (or the cost of including it is not worth the benefits).

**Comment by delishad21** [comment]
Okay thanks prof!
