### ISSUE TITLE
Was the use of excel allowed in the PE?

### ISSUE THREAD

**Issue by delishad21** [nus-cs2103-AY2324S2/forum#913]
Our application consists of functionality that requires the use of external csv files. We had done our own testing using text editors to create our csv files. 

One of our testers had used Excel during the PE to generate these csv files and discovered a bug using it. While there might be a bug present, without the use of Excel, it is likely that this the user would not have caused our app to misbehave. We feel that this is unfair to our group as Excel is a turing complete software that should not have been allowed in the PE to begin with.

**Comment by damithc** [comment]
@delishad21 we allow the use of additional software (upon request) if the software is relevant to the testing of a specific product. So, unless users of your app are not supposed to use Excel either, the use of Excel in testing is within the PE rules.

**Comment by delishad21** [comment]
Noted prof thanks!
