### ISSUE TITLE
Seeking Clarification Regarding Bug Report Made in Part II

### ISSUE THREAD

**Issue by itstrueitstrueitsrealitsreal** [nus-cs2103-AY2324S2/forum#914]
Hi, wanted to check regarding this issue which was submitted after part 2 started, if this tester labelled this as a documentation bug, but the bug involves him running the application to check if the sample data in the application is the same as in the documentation, is this a functionality bug or a documentation bug?

This seems like a very grey area and I think it would be ideal if the teaching team were to step in...

https://github.com/nus-cs2103-AY2324S2/pe-dev-response/issues/4768

**Comment by damithc** [comment]
@itstrueitstrueitsrealitsreal there was no restriction on running the app during part II. But the bugs reported during that time cannot be functionality or feature design bugs.

In  any case, a bug could be noted down during part I and reported during part II; so, such a restriction cannot be enforced.

**Comment by itstrueitstrueitsrealitsreal** [comment]
Thanks for the quick reply! Closing the issue now.
