### ISSUE TITLE
Application crashes as a result of editing the data file wrongly

### ISSUE THREAD

**Issue by SherisseTJW** [nus-cs2103-AY2324S2/forum#917]
Hi, Can I confirm whether it is considered a bug if the data file is edited such that invalid values are added, and this results in the application crashing. 

Specifically, we do have the following line in our UG:
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/63995220/267f84d7-c997-4e57-92b6-37a0b66913bb)

If it is a bug, I assume it is a Low Severity (since the issue only occurs when the user edits the data file erroneously)? Or would it be high since the application crashes?

**Comment by damithc** [comment]
@SherisseTJW we have the following among [PE bug triaging guidelines](https://nus-cs2103-ay2324s2.github.io/website/admin/tp-pe.html#:~:text=Handling%20manual%20edits%20to%20the%20data%20file)
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/ee43f492-6d2d-45a3-8e32-0237d2c18408)

So, it is not a requirement to have more support than the above.

**Comment by SherisseTJW** [comment]
Ah understood! Thanks for the clarification
