### ISSUE TITLE
Are there any reasons to downgrade a bug that is not in scope?

### ISSUE THREAD

**Issue by benson1029** [nus-cs2103-AY2324S2/forum#918]
Our team received a bug report which should be not in scope (with high confidence). However, we feel that the severity of the bug should be Low instead of Medium. Since not in scope bugs do not carry any penalty for the team, is it wiser to just keep the severity as it is? Or are there any reasons (incentives) for us to downgrade the bug?

**Comment by kjw142857** [comment]
@benson1029 I think the below should answer your question!

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/122250318/86fd33c8-282e-4c75-8858-1f56df7f55f3)

**Comment by damithc** [comment]
@benson1029 (as @kjw142857 noted) it is safer to choose the correct severity.

**Comment by benson1029** [comment]
Ok thanks!
