### ISSUE TITLE
Labels of duplicates during bug triaging

### ISSUE THREAD

**Issue by tzyian** [nus-cs2103-AY2324S2/forum#919]
If I set `#1` as a duplicate of `#2` and accept `#2`, do I need to change the labels of `#2`?

The testers for `#1` and `#2` put different severities and types.

**Comment by damithc** [comment]
@rertyy the duplicates will inherit the response, type, and severity of the 'original'. So, no need to change labels of the duplicates.

**Comment by tzyian** [comment]
Noted, thank you!
