### ISSUE TITLE
Minor Typo in End of Week 2 Automated Email

### ISSUE THREAD

**Issue by triciiaaa** [nus-cs2103-AY2324S2/forum#92]
Not sure if the information below will be reused for subsequent automated emails but I noticed a typo under the Forum Participation section.

Instead of: 
> curios

It should be:
> curious

I have attached a screenshot for reference:
![Screenshot 2024-01-27 120315](https://github.com/nus-cs2103-AY2324S2/forum/assets/113182967/96df66ed-5645-4040-8243-a219227aba61)

**Comment by damithc** [comment]
Thanks for reporting this, @triciiaaa 
Will fix in future rounds.
