### ISSUE TITLE
Is the app assuming the user has an internet connection considered a bug?

### ISSUE THREAD

**Issue by kjw142857** [nus-cs2103-AY2324S2/forum#920]
Hi Prof @damithc, if the app assumes the user has access to all websites on the internet, something that is specifically not available in PE Phase 1 (especially Part I), is it reasonable to say that this is a bug? An example would be in the PDF DG "Getting Started" part, where instead of copying over the steps from the UG, the team links to their product website UG for the steps.

**Comment by damithc** [comment]
@kjw142857 While this not not ideal for the PE, it is not strictly wrong for the DG to link to the UG. During the PE, testers were allowed to use other websites (upon request) that they needed for the testing.

**Comment by kjw142857** [comment]
Ok, noted with thanks Prof!
