### ISSUE TITLE
Can minor formatting typos be counted as `NotInScope`?

### ISSUE THREAD

**Issue by Javiery3889** [nus-cs2103-AY2324S2/forum#921]
For typos such as missing periods at the end of sentences, can these be counted as `NotInScope` since it does not significantly impact the reader/user?

**Comment by damithc** [comment]
@Javiery3889 Our stance is avoiding/correcting obvious typos does not take a significant extra effort, and hence, should not have been postponed to a future version. Plus, correcting typos was allowed during the feature freeze. So, they don't qualify for `NotInScope`.
