### ISSUE TITLE
DG section format for the commands

### ISSUE THREAD

**Issue by guohuang88** [nus-cs2103-AY2324S2/forum#923]
Hi Prof @damithc, our team did not want to change the order of the sections as the contribution to the DG for the author will be changed due to git blame. Is this still considered a documentation bug?
<img width="792" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/52065528/0f16cb23-cc3c-40eb-853c-77f780f6f8cd">

**Comment by damithc** [comment]
@guohuang88 The authorship tracking issue has workarounds (e.g., use `@@author` to override authorship), so it can't be used as a reason for an issue with the DG.

**Comment by guohuang88** [comment]
okay thanks prof!
