### ISSUE TITLE
Practice Paper : P3.02

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#924]
Why is B correct and E wrong?

<img width="780" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/73015364/e8e7e2cf-5761-480d-a06e-521a1951d5d1">

**Comment by baskargopinath** [comment]
<img width="810" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/73015364/fcb545cd-e7a3-49da-b3cf-e52f5a4279ad">

If no access modifiers are specified doesn't it mean its public

**Comment by itstrueitstrueitsrealitsreal** [comment]
`~` is used for package-private attributes (no access modifier specified).

**Comment by baskargopinath** [comment]
@itstrueitstrueitsrealitsreal but isnt it public if no access modifier is specified so + is also correct?

**Comment by itstrueitstrueitsrealitsreal** [comment]
Can refer to this issue for further explanation: https://github.com/nus-cs2103-AY2223S1/forum/issues/491

**Comment by baskargopinath** [comment]
thank u @itstrueitstrueitsrealitsreal

**Comment by baskargopinath** [comment]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/73015364/3d266fba-f3b6-4959-9694-2680e53e4f4f)

but why is it stated here that default access modifier is public so its + for this?

**Comment by baskargopinath** [comment]
Ok i found out,

Interfaces : Default `public (+)`

Non-Interfaces : Default `package-private (~)`
