### ISSUE TITLE
Is user not familiar with JAVA installation considered a valid bug?

### ISSUE THREAD

**Issue by ZhiWei1010** [nus-cs2103-AY2324S2/forum#925]
Hello prof @damithc , is it a valid bug where user might not be familiar on how to install java since it is expected that user's computer should already have java?

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/60460444/ac6d4941-acfd-4d28-abce-9ac35446976e)
https://nus-cs2103-ay2324s2.github.io/website/admin/tp-constraints.html

Link to issue:
https://github.com/nus-cs2103-AY2324S2/pe-dev-response/issues/2097

**Comment by damithc** [comment]
@ZhiWei1010 You can decide how much Java expertise you expect the user to have, and then decide whether it is good to provide additional help to the user on a  Java related aspect such as installation.

Also, note the following slightly different questions:
* Was it wrong not to give more guidance to the user on X? If yes, the response could be `response.Accept`
* Is it good to give more guidance to the user on X, if not now, perhaps in a future version?  If yes, the response could be `response.NotInScope`
* Is your stance is that you should not give more guidance to the user on X, now or in future?  If yes, the response could be `response.Reject`

**Comment by ZhiWei1010** [comment]
Ok thanks prof!
