### ISSUE TITLE
Are we required to include ALL feature's use-cases in DG?

### ISSUE THREAD

**Issue by marcus-ny** [nus-cs2103-AY2324S2/forum#927]
My team has received a bug report stating that we are missing use-cases for features in the DG. However, according to week 7's task, the DG is not required to include exhaustively all feature's use-cases. May I clarify whether we are required to cover all use-cases?

<img width="834" alt="Screenshot 2024-04-21 at 4 55 37 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/117426083/56731667-8418-4090-8e0a-0a0b9af5cfc8">

**Comment by damithc** [comment]
@marcus-ny Including all use cases is not a requirement. They are to be used only when they add value.

**Comment by marcus-ny** [comment]
Thank you for the clarification prof@damithc !
