### ISSUE TITLE
Is weird email out of scope or feature flaw?

### ISSUE THREAD

**Issue by chiageng** [nus-cs2103-AY2324S2/forum#928]
Hi prof, our team has received this error as "medium feature flaw"

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/91059092/6deb0783-d768-4664-8aae-e2d9439a5d54)

As his justification is that this is one valid email that exists in real world. May i know whether is this considered out of scope as we dont really know this type of case beforehand.

**Comment by damithc** [comment]
@chiageng In general, rejecting valid inputs is not desirable.
'We didn't know about it' is not strictly a valid excuse, but the probability of actual usage can be used to determine severity and whether it can be NotInScope. For example, low probability of usage can be used to justify a lower severity, or lower priority to support it in the current version.

Also related:
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/cd84162f-7500-49b3-904a-db9ddc408e58)

**Comment by chiageng** [comment]
Okay thank you prof.
