### ISSUE TITLE
Issue unclear, conflicting information

### ISSUE THREAD

**Issue by ZhiWei1010** [nus-cs2103-AY2324S2/forum#929]
Hi prof, for a bug report that I received, the title and description directs error to find command but screenshot provided is for sort command. 

After reading the bug report, it seems like reporter mistakenly wrote sort command as find command. Can i classify it under unclear or straight up reject it since it has conflicting information, or should I treat it as a correct bug since I can understand what he is trying to express?

Link to issue:
https://github.com/nus-cs2103-AY2324S2/pe-dev-response/issues/1566

**Comment by damithc** [comment]
@ZhiWei1010 Given below are our guidelines on this kind of cases: 
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/a23091ae-773c-412a-9d7e-9781d430ad95)

If you can't figure out the problem even after a reasonable attempt to go beyond the info in the bug report, you may reject or classify as unclear (both are graded the same way).

**Comment by ZhiWei1010** [comment]
Ok thanks prof !
