### ISSUE TITLE
[PE]Can we reject an issue when its type is incorrect?

### ISSUE THREAD

**Issue by laney0808** [nus-cs2103-AY2324S2/forum#931]
CATcher states that for all issues submitted during 'documentation testing phase' that we can directly reject them if we think it is not a documentation issue. Whereas in PE instruction given on course website, we are supposed to change the type of the issue instead of directly rejecting them. May I ask whether we can reject an issue when its type is incorrect?

**Comment by damithc** [comment]
@laney0808 Are you referring to the two statements below?
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/f115cb8a-1fe1-4a0e-b1ad-7d01cef77eb4)

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/31e6f5c4-418d-46e7-af67-102fe5dde4b0)

If so, there is no contradiction between the two. The first one is referring to the nature of the bug, not the `type.*` label.

**Comment by laney0808** [comment]
I see. Thank you!
