### ISSUE TITLE
[PE] Is allowing user input in seemingly incorrect format a feature flaw or not in scope?

### ISSUE THREAD

**Issue by laney0808** [nus-cs2103-AY2324S2/forum#932]
This question is about not setting validation for inputs in certain formats. For example, the app may allow alphanumeric values in the "name" field, allow email in email@domain format (without .com) or allow empty input for certain fields. Are they considered feature flaw or not in scope?

**Comment by damithc** [comment]
> Are they considered feature flaw or not in scope?

@laney0808 These two can apply at the same time, as one is a `type.*` and the other is a `response.*`

**Comment by laney0808** [comment]
I see, thank you.
As a follow-up question, may I ask whether bug reports of type "the app does this, but it is not explicitly stated in the user guide" can be considered "not in scope" (assuming it can be replicated)? 
For example, "the application does allow duplicates of the same prefix in the input, but never explicitly says that it does this." when none of the features involve duplicates of a prefix.

**Comment by damithc** [comment]
@laney0808 See if the following helps with your question:
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/a1320a4a-5ff6-46d7-a088-00589fa15b3d)

**Comment by laney0808** [comment]
Thank you for your reply. As the two pointers seem to only address the issue of missing feature, may I ask whether they still need to be satisfied in the cases where it's not about a 'missing' feature, but an 'existing' feature?  For example, for the first question, the reported flaw is about putting 'too little' restriction on the input. The current restrictions are specified in the UG.  And for the second question, the reported flaw is about the existing mechanism of "allowing multiple prefix", that is not explicitly documented.

**Comment by damithc** [comment]
> Thank you for your reply. As the two pointers seem to only address the issue of missing feature, may I ask whether they still need to be satisfied in the cases where it's not about a 'missing' feature, but an 'existing' feature? For example, for the first question, the reported flaw is about putting 'too little' restriction on the input. The current restrictions are specified in the UG. And for the second question, the reported flaw is about the existing mechanism of "allowing multiple prefix", that is not explicitly documented.

@laney0808 the guideline applies to any desired change to the current behavior; it doesn't have to be an entirely new feature. 
If the inputs in concern doesn't crash your app, it satisfies the second condition, and hence, meets the 'at least one' bar.

**Comment by laney0808** [comment]
That completely clarifies my concerns. Thank you very much!
