### ISSUE TITLE
Are we required to split our special characters enhancement into multiple enhancements?

### ISSUE THREAD

**Issue by simkianseng** [nus-cs2103-AY2324S2/forum#937]
Our special character enhancements will be controlled by a single REGEX variable that will filter out special characters. We plan to add support for `-` and `/` characters. This support will also mean that other fields such as `NAME` and `TAG` have these support as well. Does this count as a single enhancement?

If this is not a single enhancement and a documentation bug, what severity level should it be?

**Comment by damithc** [comment]
> Our special character enhancements will be controlled by a single REGEX variable that will filter out special characters. We plan to add support for `-` and `/` characters. This support will also mean that other fields such as `NAME` and `TAG` have these support as well. Does this count as a single enhancement?

@SimKianSeng If you can provide proof (e.g., point to the relevant code) that fixing one REGEX will add that feature to multiple fields it can be considered as a single enhancement.
