### ISSUE TITLE
A Tricky Tester Response Scenario

### ISSUE THREAD

**Issue by benson1029** [nus-cs2103-AY2324S2/forum#938]
I will be using variables below for simplicity.

I tested commands `A` and `B` during the PE and they have inconsistent behaviours with each other. According to my judgement, command `A` has the correct behavior while command `B` doesn't. I proceeded to report the incorrect output of command `B` under `type.FunctionalityBug` (without mentioning command `A` at all).

However, now that the dev team argued that command `B` has the correct behaviour (which implies command `A` doesn't). It is possible to argue that the behaviour is consistent with the user guide (with ambiguity), while it clearly contradicts with the user stories in the DG.

What should I do in the tester response phase?

Action 1: Forgo the bug since I did not mention command `A` in the bug report.
Action 2: Continue arguing that command `B` has an incorrect behaviour. (i.e. disagree with the rejection)
Action 3: Adopt the team's logic but state that command `B` has a severe feature flaw.
Action 4: Report an issue with documentation.

All of Actions 2, 3 and 4 seem weird to me (and I'm not sure whether they are allowed), but choosing Action 1 means that there is a loophole in the PE which allows teams to get away with serious bugs (rather easily).

May someone advise for this? Thanks!

**Comment by aureliony** [comment]
It would be better if you could provide additional context (i.e., provide a link to the issue)

**Comment by benson1029** [comment]
> It would be better if you could provide additional context (i.e., provide a link to the issue)

I will be providing a link after the developer response phase is over, if the issue is still under discussion by then.

**Comment by benson1029** [comment]
Moving to #955
