### ISSUE TITLE
Inconsistent breakline

### ISSUE THREAD

**Issue by jinhanfromNUS** [nus-cs2103-AY2324S2/forum#939]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/111408810/67b1e7d1-4e70-4b7b-89ed-c22b238cf913)

It is without a doubt this is an amazing website. However, I found some really minor bug which may hinder the user. The breakline here is inconsistent, and it is different from the other bullet points in the same session.

It would be amazing if you are able to fix this small bug!

Type: type.documentationBug
Severity: severity.VeryLow

**Comment by aureliony** [comment]
I believe this is an issue with markbind itself. Our team experienced it when writing our DG. The workaround is to add `</li>` at the end of the bullet point.

**Comment by damithc** [comment]
@jinhanfromNUS Thanks for raising this. This bugs me as well. As @aureliony mentioned, this is [an issue with MarkBind](https://github.com/MarkBind/markbind/issues/447).
Another workaround is to avoid having blank lines in the middle of the list (such blank lines cause these extra blank lines in the rendered list, but in a different place from where the actual blank line is). I've fixed this specific case using that workaround.
