### ISSUE TITLE
Error in course website under Week 3 Topics

### ISSUE THREAD

**Issue by kwuunnn** [nus-cs2103-AY2324S2/forum#94]
# Description
<img width="321" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/101648483/c898d7a1-d027-479d-89f5-d83eed48267a">

Under W3.1d [Tools → Git and GitHub → Working with remote branches](https://nus-cs2103-ay2324s2.github.io/website/schedule/week3/topics.html#tools-git-and-github-working-with-remote-branches) 
For **CLI**, it states that the _-u (or --update) flag_.

However, upon checking the [Git Docs](https://git-scm.com/docs/git-push):
<img width="326" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/101648483/42b53fda-edf1-423a-8699-11093a64ba66">
It seems like the alternative for the _-u_ flag is _--set-upstream_ instead, and not _--update_

# Fix
Replace _--update_ flag with _--set-upstream_ flag

**Comment by damithc** [comment]
@kwuunnn Thanks for reporting this. Fixed.
