### ISSUE TITLE
Is it a bug if a symbol in the UML diagram is not defined?

### ISSUE THREAD

**Issue by kjw142857** [nus-cs2103-AY2324S2/forum#944]
If a symbol in the UML diagrams in the DG is not defined, is it a bug? An example would be the "X" after the activation bar in the sequence diagram.
In addition, do we need to elabourate on the limitations of PlantUML, or is it NotInScope? (e.g. the lifetime of an object extending to the end of the diagram, even if there is an "X")

**Comment by damithc** [comment]
> If a symbol in the UML diagrams in the DG is not defined, is it a bug? An example would be the "X" after the activation bar in the sequence diagram.

@kjw142857 You may use UML notations in the textbook, without defining them again. That's the benefit of using a standard notation.


> In addition, do we need to elabourate on the limitations of PlantUML? (e.g. the lifetime of an object extending to the end of the diagram, even if there is an "X")

Something related (from the AB3 DG):
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/d8bbb186-d2da-4657-bb4e-c8ffa46ad1c3)

**Comment by kjw142857** [comment]
Ok thank you Prof for your assistance!
