### ISSUE TITLE
Tutorial - Week 3

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#945]
is `header comment missing` the same as `missing javadocs`?

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/73015364/0c7521de-ae86-444f-95b0-d42dfad648ef)

**Comment by damithc** [comment]
@bgopi23 Yes.

**Comment by baskargopinath** [comment]
thanks prof @damithc
