### ISSUE TITLE
Canvas textbook certain info not available

### ISSUE THREAD

**Issue by DominicFuMJ** [nus-cs2103-AY2324S2/forum#946]
I was looking at the textbook pdf in the Canvas and saw that some info is closed with no way to open it. I'm not sure what to do about this?
Canvas
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/119829202/fbc44685-fce7-413e-a0ac-e85bcd8b00c3)
Course Website
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/119829202/5821d5fd-dfc0-4e3d-8baf-0f17030a01b7)

**Comment by damithc** [comment]
@DominicFuMJ As per the note just above those close sections, their content appear in another chapter. They are collapsed here to prevent the same content appearing twice in the PDF file.

**Comment by DominicFuMJ** [comment]
Noted. Thank you
