### ISSUE TITLE
Incorrect bug report

### ISSUE THREAD

**Issue by Ko-Khan** [nus-cs2103-AY2324S2/forum#948]
My team received a bug that does not apply to our project. But I could not find the instructions about what to do in this scenerio.

**Comment by damithc** [comment]
@Ko-Khan If it is just one bug, you can reject it with that reason. Also, share the issue number here (or email it to me)

**Comment by Ko-Khan** [comment]
It is issue #1685

**Comment by damithc** [comment]
It is likely the tester was looking at the wrong repo. You can reject the bug report with that reasoning, unless the bug report is still good enough for you to identify a similar problem in your own DG.

**Comment by Ko-Khan** [comment]
Thank you!
