### ISSUE TITLE
Query on help feature

### ISSUE THREAD

**Issue by bryanyee33** [nus-cs2103-AY2324S2/forum#949]
We got a bug report on the help feature, suggesting that it could have been better optimized for typists as it requires the use of a mouse to click & copy the link from another window.

While this is a suggestion and not a bug, having it optimized for fast typists is a constraint.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/65088428/26ec7ccf-c205-4502-9485-cfea9c9134d0)

Would this issue be considered notinscope? As the user would still have to use a mouse to access, paste the link into, and navigate the browser.

**Comment by damithc** [comment]
@bryanyee33 This constraint does not require every feature to be accessible via the keyboard. So, keyboard access to some features can be put off till future versions, if not as important as the work done in the current version.
