### ISSUE TITLE
Minor typos in Week 3 Quiz

### ISSUE THREAD

**Issue by ongzhili** [nus-cs2103-AY2324S2/forum#95]
### Description
Question 6 on Week 3 Quiz on Canvas

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/122247557/7356d9b8-4917-4797-bb10-24b6791aee05)

Minor spelling errors in the first 2 options:

> Spaced retrieval via revisiting topics multiple **timesr**

> Iterative **topicdelivery**

### Expected

> Spaced retrieval via revisiting topics multiple **times**

> Iterative **topic delivery**

**Comment by damithc** [comment]
Thanks for reporting this, @ongzhili 
In fact I fixed this earlier but I guess the change wasn't saved by Canvas. I saved it again just now.
