### ISSUE TITLE
Query on bug introduced by PDF conversion

### ISSUE THREAD

**Issue by evedaktyl** [nus-cs2103-AY2324S2/forum#950]
<img width="1008" alt="Screenshot 2024-04-22 at 4 31 43 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/123064287/19f26172-169b-4309-8754-5fd509230b88">

In the UG, even though the hyperlink at How to Use The User Guide is linked correctly to the intended section, the last two lines are somehow clickable as well. This was not an issue on our project's website. 

We are unsure whether this issue clearly falls under any of the documentation bugs listed below.
<img width="707" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/123064287/e1454e0e-0a94-4e24-b065-7a74bccb2fca">

**Comment by damithc** [comment]
@evedaktyl I can't answer that question myself. Other students might be too busy with their own team's bug triaging to give inputs. Perhaps you can put it to a vote among team members i.e., ask each member to come up with a response/type/severity that a reasonable tester is likely to agree with (as you were testers yourself, you should be able to put yourself in the tester's shoes)?
