### ISSUE TITLE
Query on use case extensions necessity

### ISSUE THREAD

**Issue by bryanyee33** [nus-cs2103-AY2324S2/forum#952]
May I ask if it is necessary to include extensions into use cases which do not provide any extra information? I could not find any information in the textbook for what extensions are necessary if at all.

This is referring to issue 5534, which would simply add:

*a. User chooses to no longer add.
Use case ends.

**Comment by damithc** [comment]
@bryanyee33 Yes, it is fine to omit extensions that do not add value.
