### ISSUE TITLE
Multiple bugs from same uml diagram

### ISSUE THREAD

**Issue by Ko-Khan** [nus-cs2103-AY2324S2/forum#953]
For bugs pertaining to the same uml diagram. Should they all be accepted as different bugs if the errors are different, or a single bug?

**Comment by damithc** [comment]
@Ko-Khan You can refer to the following guidelines when deciding:

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/a6d7ecb7-f981-40fa-93b1-28b9d3e15dd9)
