### ISSUE TITLE
Multiplicity

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#954]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/73015364/2be39977-3057-42fd-b3ee-4af8008eab68)

If * is the same as putting nothing, why do we put *?

**Comment by tankh99** [comment]
I think it's because if nothing is specified, nothing can be assumed, because no multiplicity can also represent 1 or 1..10

**Comment by baskargopinath** [comment]
so if nothing is specified it doesnt = `*`?

**Comment by tankh99** [comment]
> so if nothing is specified it doesnt = `*`?

Yes, if nothing is specified, we cannot assume any specific multiplicity.

**Comment by baskargopinath** [comment]
thanks @tankh99

**Comment by damithc** [comment]
> Yes, if nothing is specified, we cannot assume any specific multiplicity.

@tankh99 is correct 👍
