### ISSUE TITLE
Tester response when there are multiple bugs cause by related issues

### ISSUE THREAD

**Issue by ThatGirlJam** [nus-cs2103-AY2324S2/forum#956]
Hello, looking at the bugs I had reported, there are few that I reported as separate bug reports (as they had distinct issues) but were caused by a root issue [in particular, being able to edit an item which breaks the other functions of the application].

The team decided to reject the bug reporting the root issue citing that it is an intended feature.

Would it be appropriate if I mention these other bug reports in my response to their rejection? Or if not, perhaps elaborate on the bugs caused by this root problem? 

Likewise for the other bug reports, would it be alright to mention the root cause? Would they still be considered separate bugs?

Thank you.

**Comment by aureliony** [comment]
Check if it falls under this case:
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39163684/31e6ef61-43af-47e9-9c8a-5d9c693dfd53)

Without additional context, it would seem that the dev team should have labelled them as duplicates rather than rejected.

**Comment by ThatGirlJam** [comment]
Thanks!

**Comment by damithc** [comment]
> Likewise for the other bug reports, would it be alright to mention the root cause? Would they still be considered separate bugs?

@ThatGirlJam If you do not agree with the dev team's decision, you can provide additional info in your response. The teaching team will consider that additional info when making the final decision, but the teaching team also keep in mind that the dev team did not see this additional information in the original bug report. So, this additional info _can_ help your cause, but not as much as it could have if it was in the original bug report as well.

**Comment by ThatGirlJam** [comment]
I see, thank you very much! @damithc
