### ISSUE TITLE
Issue severity level

### ISSUE THREAD

**Issue by guanquann** [nus-cs2103-AY2324S2/forum#960]
> severity.VeryLow : A flaw that is purely cosmetic and does not affect usage e.g., a typo/spacing/layout/color/font issues in the docs or the UI that doesn't affect usage. Only cosmetic problems should have this label.

From the textbook, it looks like only UI issues should be VeryLow severity. However, there are a couple of non UI bugs I reported that are changed to VeryLow severity. Would it be right if I reject the team VeryLow severity? This is because the textbook also states that:

> However, if the dev team's argument is not too far from 'reasonable', it may be better to agree than disagree.

VeryLow and Low doesn't seem too off

**Comment by damithc** [comment]
> From the textbook, it looks like only UI issues should be VeryLow severity.

@guanquann As per given instructions, VeryLow can only be used for cosmetic issues in the UI or the docs. So, you can reject if the dev team did not comply with that.

**Comment by guanquann** [comment]
Noted, thanks
