### ISSUE TITLE
p1.05 Why is Option 2 not one of the Answers?

### ISSUE THREAD

**Issue by Jerome-j** [nus-cs2103-AY2324S2/forum#961]
<img width="775" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/49815108/e0360408-ca47-4e86-aef4-f5c33f97101c">

Consider the code block below (As generated by ChatGPT):

```java
// Abstract class Foo with abstract method process
abstract class Foo {
    void process();
}

// Concrete class Bar extending Foo
class Bar extends Foo {
    // Suppose we remove the process() method implementation.
    // This will cause a compile error because Bar is not abstract and
    // does not override the abstract method process() from Foo.

    // If we uncomment the below implementation, the code will compile successfully.
    // @Override
    // void process() {
    //     // implementation details
    // }
}

public class Main {
    public static void main(String[] args) {
        Foo foo = new Bar(); // This is fine if Bar has process() method implemented.
    }
}

```

I understand why 4 is one of the answers, and would like to check why 2 is not the answer?

When I compile the code I get

```bash
javac test.java 
test.java:19: error: class Main is public, should be declared in a file named Main.java
public class Main {
       ^
test.java:3: error: missing method body, or declare abstract
    void process();
         ^

```

**Comment by damithc** [comment]
@Jerome-j Perhaps you can share a screenshot of the question as well, to give more context?

**Comment by Jerome-j** [comment]
Good point, @damithc I have edited the post to include the question.

**Comment by tankh99** [comment]
@Jerome-j This is because the method shown inside the class diagram is concrete, not abstract like in your code. If it was abstract, there would be a {abstract} beside the method

**Comment by Jerome-j** [comment]
Thank you for your insightful comments, @tankh99. I really appreciate your astute observations and your impressive knowledge on this topic.

Will be closing this issue.
