### ISSUE TITLE
What is the purpose of the Implementation Section in the DG?

### ISSUE THREAD

**Issue by SherisseTJW** [nus-cs2103-AY2324S2/forum#962]
Hi, as per the Title, I am wondering what is the intended purpose of the Implementation Section in the DG? 

This question is two-fold:
1. What is the actual purpose? (I couldn't really find any specific details in the Website now that I go check again)
2. How do I handle my bug report rejected?

I was under the impression that it is used to go through the Implementation Details of **existing** features which have already been implemented, and not to cover the Proposed Implementation Details of **proposed** additional features. 

To provide context as to this question, there is a bug report I submitted for which the Implementation Section only contained details of **proposed** additional features (which are also not in the Planned Enhancements section although they are in the Future Updates section of the UG). In my bug report, I suggested that they be removed as it may confuse the user (due to my original impression of the section's purpose)

However, the team rejected the bug report, stating that the section is for Features which do not yet exist in the application. (Although, they somehow accepted another of my bug report which suggested that they add details of existing features)

**Comment by damithc** [comment]
@SherisseTJW The DG is for developers. So, implementation details (and everything else) are to guide current and future developers. It can contain details of current or (proposed) future features, although not compulsory to have either. So, whatever implementation details/ideas that might be useful for current/future developers can be there. For example, a developer can look into implementing a feature, and document the design alternatives s/he encountered during that research. While the feature may not get implemented right away, this documentation saves the trouble of future devs having to do the same research again in a later time.

As there was no requirement that _all_ future work should be listed in the 'planned enhancements' section, we can't also say that if something is not in the list of planned enhancements, it should not be in the implementation section.

A example of a legit bug in the implementation section of the DG is if it explains a current feature but the details given do not match the actual implementation. It can also have UML notation errors, incorrect explanations (e.g., citing the wrong design pattern/principle) etc.

**Comment by SherisseTJW** [comment]
Ahh, understood. Thanks for the clarification!
