### ISSUE TITLE
Fact Checking Sequence Diagram

### ISSUE THREAD

**Issue by c-wenlong** [nus-cs2103-AY2324S2/forum#963]
`In the CS2103T syllabus, it is not specified that boxes must refer to the package of the classes in that box.`

This was the response for a bug I spotted that one of their sequence diagram has a mislabeled class. 

<img width="742" alt="Screenshot 2024-04-23 at 12 25 28" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/122634467/051d244f-245c-4b45-8a6f-b0559897dd60">

In the above sequence diagram, it shows that the `Predicate` class is under `Logic`, however, after browsing their code, I noticed that their `Predicate` class is under `Model` in the project files.

<img width="322" alt="Screenshot 2024-04-23 at 12 26 44" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/122634467/8cd649e2-cc01-4ea0-9169-16ab53f097e3">

I was wondering if it is true that this is actually not in the scope of 2103? And if it is not in the scope, is it right for them to reject my bug report? Thank you for the help @damithc!

**Comment by damithc** [comment]
@c-wenlong Although not specified, the context (i.e., how the DG is structured based on components of the architecture) indicates that the boxes refer to _components_ (not _packages_ either, although there is a match between the two). 
So, it is not desirable that a class that is actually in component X appears inside the box Y, giving the impression that it belongs to component Y.

**Comment by c-wenlong** [comment]
@damithc Thank you Prof, for the clarification. I believe this should fall under `VeryLow` then, purely cosmetic, as it does not affect the usage of the product.
