### ISSUE TITLE
Raised functionality bug but teams wants to change bug type

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#965]
If i raised a valid functionality bug that the team agrees with, but they will address it by including it in the UG, are they allowed to change the bug type to documentationbug just because they will address it in the UG? isnt it still a functionality bug?

**Comment by damithc** [comment]
@bgopi23 This is the relevant guideline:

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/20cb2815-c5ac-499b-836d-94f4515e36fd)

Note that while credit varies between bug types, we never said documentation bugs are worth less than functionality bugs.

**Comment by baskargopinath** [comment]
thank u prof @damithc
