### ISSUE TITLE
Same punctuation errors in different files

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#966]
1. I found `punctuation error A` throughout the UG so raised it as one issue.

2. I found the same `punctuation error A` throughout the DG, so i raised it as another issue because they arent the same issue but similar.

The team has assigned 1. as a duplicate of 2. even though 2 cannot be solved by fixing 1. Is these 2 bugs really duplicates? or can i dispute this

**Comment by damithc** [comment]
@bgopi23 You can follow these guidelines for this case:

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/c67318b2-e646-402c-ad59-f64582247ba2)

**Comment by baskargopinath** [comment]
thanks prof @damithc
