### ISSUE TITLE
PE bot message has a grammatical error and has missing information

### ISSUE THREAD

**Issue by aureliony** [nus-cs2103-AY2324S2/forum#967]
Actual:
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39163684/b72ea6c7-92d7-4113-8713-2b5a7767d7fd)

Expected:
"Your response is not required ..."

Additionally, the team's response is not included even if they wrote one. This should be included in the bot's reply.

**Comment by damithc** [comment]
Both good suggestions @aureliony Thanks. Will file under possible improvements for CATcher.
