### ISSUE TITLE
p1.11 coding standard violation

### ISSUE THREAD

**Issue by UdhayaShan1** [nus-cs2103-AY2324S2/forum#968]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39399745/fb1caf6e-0a7e-4a03-acfe-c94698aa953c)

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39399745/89a33f4e-3a9c-42a4-a31f-2e5d347d0301)

Why is `abcd` not considered a violation as well, as the naming could be better and descriptive?

Or does the standards only apply from the se-edu page?

Thanks

**Comment by baskargopinath** [comment]
thats code quality violation not code standard i think

**Comment by aureliony** [comment]
> Or does the standards only apply from the se-edu page?

Yes, it is given in Canvas - handouts

**Comment by UdhayaShan1** [comment]
> thats code quality violation not code standard i think

Thanks I think its code quality not standard.

**Comment by damithc** [comment]
> Thanks I think its code quality not standard.

Correct. 👍
