### ISSUE TITLE
FileWriter/PrintWriter isnt writing to my file

### ISSUE THREAD

**Issue by jannaleong** [nus-cs2103-AY2324S2/forum#97]
Currently using intellij and java 11. For my task, I need to write the contents of my list everytime there is an update to my list. However, I am unable to write to the file using PrintWriter/FileWriter. belle.txt and Duke.txt are under the same directory. 

Excluding other parts of my code, it looks like this

```
public class Test {
    private static ArrayList<Task> list = new ArrayList<>();
    public static void main(String[] args) {
        String data = "This is a text inside the file.";
        try {
            FileWriter fw = new FileWriter("belle.txt");
            fw.write(data);
            fw.close();
            Scanner sc = new Scanner(System.in);
            sc.close();
        } catch (IOException e) {
            e.getStackTrace();
        }
    }}
```
    
However, it does not write to my belle.txt. The curious thing is if i start a brand new blank project, and use this code with Test.java and belle.txt in the same directory, it will write to belle.txt. Thank you for the help!!

**Comment by damithc** [comment]
@jannaleong while waiting for peer inputs, you may want to use [fenced code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) to format your post for better readability.

**Comment by E0735389** [comment]
there is not enough detail to tell what is going on, as evidenced by the fact that when you try to create a MWE, the error does not happen.

Nevertheless, you can try the following.

* print out the current working directory from the Java code itself, to see if it writes to the correct file.
* Immediately after writing it, try to read back from it from within the Java code and print out the observed content.
* There is also a possibility that another instance/thread (?) of the program is running, which overwrites the file.
