### ISSUE TITLE
Query on format errors

### ISSUE THREAD

**Issue by bryanyee33** [nus-cs2103-AY2324S2/forum#972]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/65088428/60ae46d7-8aac-48d9-aabd-64a732b64fc7)

May I ask for this example given for `Specificity of error message`, why is `2021-13-28` considered as a *format* error, and not an *invalid* input? Shouldn't format error be related only to the format of the input, i.e. `YYYY-MM-DD`, meaning an input such as `2021/02/30` is a format error but not an invalid input, since the format is wrong but it is a valid date?

**Comment by damithc** [comment]
@bryanyee33 depends on how you specify the format. Here, we assume the format already specifies that `MM` should be `1..12`
