### ISSUE TITLE
Query on PE bugs

### ISSUE THREAD

**Issue by xiaorui-ui** [nus-cs2103-AY2324S2/forum#973]
A few questions regarding PE bugs.

* For notinscope bugs, do the severity matter when calcuating our scores?
* Do rejected bugs affect our accuracy as the tester? 
* What about bugs marked as notInScope/issueUnclear/rejected/cannotReproduce and we as tester try to argue against them? How does the outcome affect our accuracy?

Thank you!

**Comment by UdhayaShan1** [comment]
For points 2 and 3, I am assuming it follows this

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39399745/cfe78c1e-edac-48f4-9a74-b89c73ea5edb)

For 2) if you accept, accuracy should not be affected.

**Comment by damithc** [comment]
> * For notinscope bugs, do the severity matter when calcuating our scores?

@xiaorui-ui Yes.



> * Do rejected bugs affect our accuracy as the tester?

As @UdhayaShan1 mentioned, it follows this table:


![image](https://private-user-images.githubusercontent.com/39399745/324763643-cfe78c1e-edac-48f4-9a74-b89c73ea5edb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4Njg5MzgsIm5iZiI6MTcxMzg2ODYzOCwicGF0aCI6Ii8zOTM5OTc0NS8zMjQ3NjM2NDMtY2ZlNzhjMWUtZWRhYy00OGY0LTlhNzQtYjg5YzczZWE1ZWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDEwMzcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5NjhmOGFjYzcwZjk1MWE2NTAyOTJiYTI5ODMzZjhiMWZkYmFkYzA1NTY4M2VkZjg1YmRkM2EwZTVjMDBiNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tn9ZjgogrXcgrydVG_x-2Ym9v4wPPgx_wwX6Zg0aKJA)
> 



> * What about bugs marked as notInScope/issueUnclear/rejected/cannotReproduce and we as tester try to argue against them? How does the outcome affect our accuracy?

Yes, if you dispute the response.* chosen by the dev team, and the teaching team agrees with you, your accuracy goes up. If the teaching team agrees with the dev team instead, your accuracy goes down.

**Comment by xiaorui-ui** [comment]
Thanks!
