### ISSUE TITLE
Query on running textbook on website during Final Exam

### ISSUE THREAD

**Issue by LargeCrowd** [nus-cs2103-AY2324S2/forum#975]
I understand that we are discouraged from using web browsers, not able to access the course website (no internet access) and we can run a local copy of the website on our computers. 

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/102574520/206b4d0a-3554-43fc-a7a4-e07eff69f9c5)

However, are we allowed to save the textbook portion of the website as an html file and "access" the website that way?
i.e. on Microsoft Edge, Save Page As (Ctrl + S)  -> "CS2103_T - Textbook.html"

It does not require internet access. The website version of the textbook is easier and more friendly to navigate, which is why I would prefer this if possible.

**Comment by LargeCrowd** [comment]
Wait nevermind, the links to sections dont work without internet access

**Comment by damithc** [comment]
> However, are we allowed to save the textbook portion of the website as an html file and "access" the website that way? i.e. on Microsoft Edge, Save Page As (Ctrl + S) -> "CS2103_T - Textbook.html"
> 
> It does not require internet access. The website version of the textbook is easier and more friendly to navigate, which is why I would prefer this if possible.

@LargeCrowd In this case, it is better to run a local copy of the website. Just saving html pages will not work because these pages use javascript to make things work.
