### ISSUE TITLE
Query on MSS

### ISSUE THREAD

**Issue by AidenLYT** [nus-cs2103-AY2324S2/forum#976]
The following is a modified MSS presented by the team I'm reviewing: 

Use Case: UC01 - Adding a contact

MSS
1. User enters command to add a contact
2. AB adds the contact to the contact list
3. AB shows a success message along with the added contact's details
Use case ends

Extension
* 2a. A field of the new contact to be added already exists 
   * 2a1. AB shows an error message
   Use case resumes at step 1.

<img width="893" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/110450637/4fc6151c-90f0-4a43-bb68-591bf444dfbe">

According to the course textbook, MSS only includes the externally visible behavior.
However, step 2 of the MSS presented by the team stated the internal details (process of AB adding contact into the list) and further extend from step 2. 

I surmised that Extension 2a should belong to step 1 instead, as step 1 stated the externally visible behavior. 
> Eg. 
> 1a. Command entered contains duplicated field as a contact in the contact list

The team rebutted that they have discussed with Prof and got the approval to present the MSS as above. Please do advise! 😟

**Comment by E0735389** [comment]
I feel this could be considered an externally visible behavior under reasonable interpretation, where "the contact list" is to be interpreted as "the contact list displayed on the screen".

On the other hand, writing it as "the contact list displayed **on the screen**" would be wrong as it includes too much specific detail.

**Comment by AidenLYT** [comment]
Thank you @E0735389  for the response!

Following up on your response, do correct me if I interpret it wrongly. Wouldn't step 2 be the 'process' of adding the contact to the contact list (internal). Then, step 3 will be the actual display of the display list (externally visible).

**Comment by damithc** [comment]
> According to the course textbook, MSS only includes the externally visible behavior.
> However, step 2 of the MSS presented by the team stated the internal details (process of AB adding contact into the list) and further extend from step 2.

@AidenLYT we should not be too strict about 'externally visible'. The user kind of 'sees' the contact being added in this case, even if it is done internally (like what @E0735389 mentioned).
That said, it could have been written it as 'AB adds the contact and informs the user' (without giving it as a separate step, or being specific about what is shown to the user)


> I surmised that Extension 2a should belong to step 1 instead, as step 1 stated the externally visible behavior.

Sometimes, it is hard to pinpoint whether to base the extension number on `n` or `n+1`. In most cases, either may be OK, as long as the reader gets the correct idea. Given use cases don't have a precise format or syntax, we shouldn't try to enforce one too strictly either.


> The team rebutted that they have discussed with Prof and got the approval to present the MSS as above. Please do advise! 😟

I don't remember such a query specifically, but perhaps they asked me in some other way and/or interpreted what I said in a way I didn't intend.

**Comment by AidenLYT** [comment]
Thank you prof for the clarification!
