### ISSUE TITLE
Incorrect Diagrams in the Textbook

### ISSUE THREAD

**Issue by fy17ohhh** [nus-cs2103-AY2324S2/forum#977]
In the Acitivity Diagrams Section in the Textbook
the 2 Example Activity Diagrams are incorrect
<img width="760" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/103088135/7eefeb24-544f-4750-a1ea-e2aa8e67c558">
<img width="1138" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/103088135/1fd2d94c-ae8d-4cc5-8e60-f76dc0d46d3b">

**Comment by damithc** [comment]
@fy17ohhh Can you give more details?
Note that the diagrams given are example activity diagrams (for reference), not given as the model answer to the question.

**Comment by fy17ohhh** [comment]
> @fy17ohhh Can you give more details? Note that the diagrams given are example activity diagrams (for reference), not given as the model answer to the question.

Oh sorry I misunderstood, I tot it is supposed to show the answer. Thank you for the clarification!
