### ISSUE TITLE
Two unidirectional vs bidirectional

### ISSUE THREAD

**Issue by sethteo** [nus-cs2103-AY2324S2/forum#979]
<img width="651" alt="Screenshot 2024-04-23 at 9 51 25 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/119569146/433b3a85-c065-4e54-9a03-466c018c3b43"> <br/>
Maybe using this question and option c as an example how would two unidirectional relationship look like if implemented in code 

Would just changing the attribute name for one of the associations of either Mat or Bot from "partner" to something else suffice?

**Comment by iamtr** [comment]
I think so, this is from the textbook:

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/52852142/af56fc26-f90f-444d-9a8f-555756695eae)

**Comment by damithc** [comment]
> Would just changing the attribute name for one of the associations of either Mat or Bot from "partner" to something else suffice?

An additional reference in case someone else is reading this thread, relevant comment https://github.com/nus-cs2103-AY2324S2/forum/issues/1003#issuecomment-2078623835
