### ISSUE TITLE
Minor typo in Week 3 (Weekly schedule → Deadline for weekly tasks)

### ISSUE THREAD

**Issue by Jerome-j** [nus-cs2103-AY2324S2/forum#98]
For this paragraph listed in Admin Weekly schedule → Deadline for weekly tasks:

> It's OK to make occasional mistakes in weekly tasks (making mistakes is a natural part of learning new things after all). If a weekly task was not accepted as 'done' due to a mistake you made, go ahead and rectify the mistake as soon as you can -- our grading scripts will not penalize such mistakes if they are corrected soon after.

The apostrophe of the abbreviated word `wont` is missing, i.e. `won't` should be the correct one.

**Comment by damithc** [comment]
Fixed. Thanks for reporting this, @Jerome-j
