### ISSUE TITLE
User Stories in DG

### ISSUE THREAD

**Issue by chiralcentre** [nus-cs2103-AY2324S2/forum#980]
Can I check with the teaching team if its considered a bug when user stories in the DG are not implemented within the app?

**Comment by damithc** [comment]
@chiralcentre See if [this point](https://nus-cs2103-ay2324s2.github.io/website/admin/tp-deliverables.html#deliverable-developer-guide-dg:~:text=The%20Appendix%3A%20Requirements%20section) helps.

**Comment by chiralcentre** [comment]
Hi Prof can I check which point you are referring to? I cannot seem to see any point regarding user stories.

**Comment by damithc** [comment]
> Hi Prof can I check which point you are referring to? I cannot seem to see any point regarding user stories.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/02c4163c-46e4-4971-a829-17c6adf8620f)

**Comment by chiralcentre** [comment]
Noted! If I understand this correctly, it means its ok for user stories not to be implemented within the app?

**Comment by damithc** [comment]
> Noted! If I understand this correctly, it means its ok for user stories not to be implemented within the app?

Yes.

**Comment by chiralcentre** [comment]
Noted! Thank you prof for the clarification
