### ISSUE TITLE
[PE] Are these considered duplicate bug reports?

### ISSUE THREAD

**Issue by laney0808** [nus-cs2103-AY2324S2/forum#981]
One of my bug report (A) has been marked by the dev team as 'duplicate' of another bug report (B).
Bug report A pointed out issue (1), while bug report B is composed of two issues, (1) and (2).

In the team's explanation for "marking as duplicate", they stated: Both are about issue (1).

However, in the team's explanation for "rejecting the bug report", they chose to reject issue (2) and did not address issue (1) at all.

In this case, should I agree on their "duplicate" decision before disagreeing to their rejection?

**Comment by damithc** [comment]
@laney0808 The two are independent. You can disagree with both. That is, you can explain why it is not a duplicate of the bug the team seems to be addressing, and why it should not be rejected either (i.e., give further reasons to strengthen details given in the initial bug report).

**Comment by laney0808** [comment]
> @laney0808 The two are independent. You can disagree with both. That is, you can explain why it is not a duplicate of the bug the team seems to be addressing, and why it should not be rejected either (i.e., give further reasons to strengthen details given in the initial bug report).

I see. Thank you for explaining!
