### ISSUE TITLE
Additional practice questions for part 2:  Sequence Diagram

### ISSUE THREAD

**Issue by tankh99** [nus-cs2103-AY2324S2/forum#983]
I have a couple of questions regarding the sequence diagram question. I will refer to the main function as the arrows from the left:
1. for the `creator().increase()` function, is it the main function calling it, or is it the factory class calling it?
2. Do we need an else block for alt paths in this case?

<img width="1006" alt="Screenshot 2024-04-24 at 7 22 41 AM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/56617918/173e7e64-0a16-4c2e-a625-1535e9c8d003">

**Comment by iantml** [comment]
For the second question, turns out textbook says

> No more than one alternative partitions be executed in an alt frame. That is, it is acceptable for none of the alternative partitions to be executed but it is not acceptable for multiple partitions to be executed.

**Comment by MarcusGitty** [comment]
<img width="772" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/122339963/54ce5363-f2d5-4c49-b611-1154f84130fc">

It can be split as 
Factory tempFactory = u.creator();
tempFactory.increase(1);

1. It's the unit class calling it since u is of type unit.
2.  The unit class calls it's own creator method that returns a factory 
3. this returned factory class calls it's own increase 1 class


<img width="771" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/122339963/f736421d-56c5-4f00-a85d-a558e077ef71">

From the textbook, it seems that the else block can be ommitted.

**Comment by tankh99** [comment]
> <img alt="image" width="772" src="https://private-user-images.githubusercontent.com/122339963/325499953-54ce5363-f2d5-4c49-b611-1154f84130fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwOTY0NzAsIm5iZiI6MTcxNDA5NjE3MCwicGF0aCI6Ii8xMjIzMzk5NjMvMzI1NDk5OTUzLTU0Y2U1MzYzLWYyZDUtNGM0OS1iNjExLTExNTRmODQxMzBmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNlQwMTQ5MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NzZhZWZkMDgwMjZkMzMxYTIxYzNkMmNjZmZjY2YyNjFlNmM4MzljNTI1MWVjOWYzZWQzOTBjZjYyMTkxOThmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3JeLqD-HpVBYNo7i77DJ5JLxdiBjYtaTuegERo0Uoak">
> It can be split as Factory tempFactory = u.creator(); tempFactory.increase(1);
> 
> 1. It's the unit class calling it since u is of type unit.
> 2. The unit class calls it's own creator method that returns a factory
> 3. this returned factory class calls it's own increase 1 class
> 
> <img alt="image" width="771" src="https://private-user-images.githubusercontent.com/122339963/325500727-f736421d-56c5-4f00-a85d-a558e077ef71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwOTY0NzAsIm5iZiI6MTcxNDA5NjE3MCwicGF0aCI6Ii8xMjIzMzk5NjMvMzI1NTAwNzI3LWY3MzY0MjFkLTU2YzUtNGYwMC1hODVkLWE1NThlMDc3ZWY3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNlQwMTQ5MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYTBkYzkxZGRjYWFmOWI4MThlZTZhMmE1YTExYjFmZjIyY2ZkY2RjYjIzZTIzOGRiNDYxNzU0Y2U0NmZkMzJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vHFyPO8VjRtyXtC63x-AFukKJr587L3fHxZf12lBDaU">
> From the textbook, it seems that the else block can be ommitted.

Thanks Marcus, this makes sense
