### ISSUE TITLE
What's the difference between buffers and padding?

### ISSUE THREAD

**Issue by LargeCrowd** [nus-cs2103-AY2324S2/forum#989]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/102574520/8afa9894-dc90-4837-a1dc-2183929b395a)

Hello, I need clarification please! This is one of the questions provided in the latest Course Topics video.
Isn't _padding_ the spacing between elements in frontend design/GUI stuff? Therefore, not related to _buffers_ , which is a project planning timeline thing?

**Comment by baskargopinath** [comment]
i cant find what padding is in textbook or course website also

**Comment by drustanyjt** [comment]
@LargeCrowd I also am not sure what is padding.

**Comment by damithc** [comment]
Tip: Google for `padding estimates` (which is the one related to [the topic in concern](https://nus-cs2103-ay2324s2.github.io/website/book/projectPlanning/buffers/)).

Other common phrases  that use the same word:  `padding the resume` , `padding the budget`.

**Comment by fy17ohhh** [comment]
If I'm understanding correctly, the difference is that
- `padding` is when you are confident that you need 3 days, but you still add 2 extra days to the deliverable deadline. (You do not need these 2 days)
- `buffer` is when you estimate that you need 3 days based on current information, but you add 2 extra days to absorb any unforeseen delays. (You do need these 2 days as effort/time estimations are hard in this case)

**Comment by drustanyjt** [comment]
I get the impression that buffers are meant to be more explicit (stakeholders/ other devs know that a specific period is meant to be a buffer period), while padding is a bit of a "lazier" way to make sure you don't run afoul of an agreed deadline by estimating you would need a long time.

**Comment by damithc** [comment]
> * `padding` is when you are confident that you need 3 days, but you still add 2 extra days to the deliverable deadline. (You do not need these 2 days)
> * `buffer` is when you estimate that you need 3 days based on current information, but you add 2 extra days to absorb any unforeseen delays. (You do need these 2 days as effort/time estimations are hard in this case)

@fy17ohhh The confidence level is the same in both cases -- i.e., we estimate it should take 3 days but we also know that it can take longer due to unexpected delays. The difference is in how we deal with this uncertainty. In padding, we just inflate the estimate to 5 days. With buffers, we add a separate 2-day buffer into the schedule.

> I get the impression that buffers are meant to be more explicit (stakeholders/ other devs know that a specific period is meant to be a buffer period), while padding is a bit of a "lazier" way to make sure you don't run afoul of an agreed deadline by estimating you would need a long time.

Yup.
