### ISSUE TITLE
Typo in forum README.md

### ISSUE THREAD

**Issue by rertyy** [nus-cs2103-AY2324S2/forum#99]
https://github.com/nus-cs2103-AY2324S2/forum/blob/master/README.md (the README of this repo)

`You can also subscribe to (or unsubsribe from) specific issues`

should be

`You can also subscribe to (or unsubscribe from) specific issues`

unsubsribe -> unsubscribe

**Comment by damithc** [comment]
Fixed. Thanks for reporting this @rertyy
