### ISSUE TITLE
UML Diagram for interfaces extending interface

### ISSUE THREAD

**Issue by tzyian** [nus-cs2103-AY2324S2/forum#991]
In UML for class diagram,

`class extends class` is solid line with arrow with arrowhead
`class implements interface` is dashed line with arrowhead

What about `interface extends interface`?

**Comment by tankh99** [comment]
To add on, what about abstract class implements interface?

**Comment by damithc** [comment]
`extends` -> solid line
`implements` -> dashed line

**Comment by tzyian** [comment]
Noted, thank you!
