### ISSUE TITLE
Practice exam p1.12 - solution unclear

### ISSUE THREAD

**Issue by aureliony** [nus-cs2103-AY2324S2/forum#992]
I think the given solution is not exactly correct, as changing the software's internal behavior without changing the external behaviour is still considered refactoring. "It changes the external behavior" would be a better answer.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/39163684/8d4ba6e0-3507-4faf-9efd-2d1ee0889c08)

**Comment by baskargopinath** [comment]
i think refactoring is changing the softwares `internal structure` and not `internal behaviour`

some code code changes might change the internal behaviour (such as performance) of the software that is not visible externally but this doesn't qualify under refactoring

**Comment by SherisseTJW** [comment]
I feel that "It changes the external behaviour" would be more appropriate actually. 

While refactoring is changing the **internal structure**, there is always the possibility of side-effects where it changes the **internal behaviour**, but we still consider it as refactoring

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/63995220/aaf629d4-811f-4216-bbdf-8a44c70d2726)

Having the rationale be just "It changes the behaviour" could result in confusion that such side effects are not allowed at all.

**Comment by damithc** [comment]
> I feel that "It changes the external behaviour" would be more appropriate actually.
> 
> While refactoring is changing the **internal structure**, there is always the possibility of side-effects where it changes the **internal behaviour**, but we still consider it as refactoring

Correct. 

Most examples we've given (for instance, the two examples given in https://nus-cs2103-ay2324s2.github.io/website/se-book-adapted/chapters/refactoring.html#what and the 10 examples given in https://nus-cs2103-ay2324s2.github.io/website/se-book-adapted/chapters/refactoring.html#how ) change the internal behavior.
