### ISSUE TITLE
Class Diagram Query

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#997]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/73015364/9d90eef9-47c0-4843-b21f-064a3f686f1e)

if in lid class, it is **not** specified that the box attribute is `the box for which this is the lid`, is it wrong to use a bi-directional arrow?

so we need another arrow from lid to box?

**Comment by fy17ohhh** [comment]
According to this in the texbook
<img width="690" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/103088135/9aca1d39-2715-4b37-a8da-af1edf4cc2af">
I think if not specified, using two unidirectional associations would be more appropriate

**Comment by baskargopinath** [comment]
@fy17ohhh i understand but is it wrong to use a bidirectional arrow? i feel that it is

**Comment by baskargopinath** [comment]
https://github.com/nus-cs2103-AY2324S2/forum/issues/1003#issuecomment-2078623835
