### ISSUE TITLE
Aggregation vs Composition

### ISSUE THREAD

**Issue by baskargopinath** [nus-cs2103-AY2324S2/forum#998]
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/73015364/390ec7e3-2fee-4978-b961-4b82b4d4e11b)

Why is history to repeatable a aggregation and not a composition relationship

**Comment by damithc** [comment]
@bgopi23 Perhaps you can also share why you think it is a composition?

**Comment by baskargopinath** [comment]
@damithc in the textbook it says for composition, if A is composed of B, if A is deleted, B will be deleted too.

If history is deleted, wont all repeatable objects be deleted too since its stored as a list inside history?

**Comment by logical-1985516** [comment]
> If history is deleted, wont all repeatable objects be deleted too since its stored as a list inside history?

From my understanding, the repeatable objects will still exist.
For example, a repeatable object may be stored in multiple histories. It does not make sense that deleting a history will delete repeatable objects stored in other histories.

Another analogy would be Person objects stored inside a Queue object. The people would not be deleted if the Queue object is deleted.

**Comment by baskargopinath** [comment]
cant u say the same for action and task then? then why is action to task a composition @logical-1985516

**Comment by logical-1985516** [comment]
Sorry, I am not too sure why this is the case. The best explanation I could give is that this seems to model the real world better, where tasks are tied to actions (tasks here can be ambiguous) while repeatable need not be tied to history.

**Comment by damithc** [comment]
Relevant: Q3 of week 9 briefing
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/1673303/f3e009c0-fc41-4d8e-9fec-33bf36417c22)

**Comment by baskargopinath** [comment]
thanks prof @damithc

**Comment by baskargopinath** [comment]
If anyone else doesn't understand this,

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/73015364/f9a1c56f-f591-4ccc-b1d1-1937ab024e89)
since it is clearly stated that Tasks are a **part** of an Action, this is a **whole-part** relationship, therefore composition.

It is not stated for history, so we cannot assume that it is composition.

Also, if, and just because repetable objects get deleted when history object is deleted, it doesnt mean that there is composition as it could just be a coincidence
